### ISSUE TITLE
[Bug] [Core] VerifyError: Bad type on operand stack

### ISSUE THREAD

**Issue by asdf2014** [apache/seatunnel#1147]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

```java
Exception in thread "main" java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    org/apache/flink/table/api/java/internal/StreamTableEnvironmentImpl.registerFunction(Ljava/lang/String;Lorg/apache/flink/table/functions/AggregateFunction;)V @1: invokestatic
  Reason:
    Type 'org/apache/flink/table/functions/AggregateFunction' (current frame, stack[0]) is not assignable to 'org/apache/flink/table/functions/UserDefinedAggregateFunction'
  Current Frame:
    bci: @1
    flags: { }
    locals: { 'org/apache/flink/table/api/java/internal/StreamTableEnvironmentImpl', 'java/lang/String', 'org/apache/flink/table/functions/AggregateFunction' }
    stack: { 'org/apache/flink/table/functions/AggregateFunction' }
  Bytecode:
    0x0000000: 2cb8 0027 4e2c b800 283a 042a b400 252b
    0x0000010: 2c2d 1904 b600 29b1                    

	at org.apache.flink.table.api.java.StreamTableEnvironment.create(StreamTableEnvironment.java:112)
	at org.apache.seatunnel.flink.FlinkEnvironment.createStreamTableEnvironment(FlinkEnvironment.java:118)
	at org.apache.seatunnel.flink.FlinkEnvironment.prepare(FlinkEnvironment.java:81)
	at org.apache.seatunnel.flink.FlinkEnvironment.prepare(FlinkEnvironment.java:43)
	at org.apache.seatunnel.config.ConfigBuilder.createEnv(ConfigBuilder.java:195)
	at org.apache.seatunnel.config.ConfigBuilder.<init>(ConfigBuilder.java:65)
	at org.apache.seatunnel.Seatunnel.entryPoint(Seatunnel.java:93)
	at org.apache.seatunnel.Seatunnel.run(Seatunnel.java:60)
	at org.apache.seatunnel.SeatunnelFlink.main(SeatunnelFlink.java:29)

Process finished with exit code 1
```

### SeaTunnel Version

The latest (2.0.5-SNAPSHOT)

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
}

source {
  FakeSourceStream {
   result_table_name = "fake"
   field_name = "name,age"
  }
}

transform {
}

sink {
  ConsoleSink {}
}
```

### Running Command

```shell
java org.apache.seatunnel.SeatunnelFlink -c application.conf
```

### Error Exception

```log
`java.lang.VerifyError: Bad type on operand stack`
```

### Flink or Spark Version

Version: 1.9.0, Commit ID: 9c32ed9

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by KyrieWang7** [comment]
todat i get the same bug,so how did u soulve it out
