### ISSUE TITLE
[Bug] [seatunnel-connector-spark-hudi] spark connector writes data to hudi error

### ISSUE THREAD

**Issue by wuchunfu** [apache/seatunnel#1164]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

can run normally, and write data

### SeaTunnel Version

2.0.5

### SeaTunnel Config

```conf
-
```

### Running Command

```shell
-
```

### Error Exception

```log
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.sql.execution.datasources.DataSourceUtils$.PARTITIONING_COLUMNS_KEY()Ljava/lang/String;
	at org.apache.hudi.DataSourceWriteOptions$.translateSqlOptions(DataSourceOptions.scala:214)
	at org.apache.hudi.HoodieSparkSqlWriter$.mergeParamsAndGetHoodieConfig(HoodieSparkSqlWriter.scala:721)
	at org.apache.hudi.HoodieSparkSqlWriter$.write(HoodieSparkSqlWriter.scala:91)
	at org.apache.hudi.DefaultSource.createRelation(DefaultSource.scala:164)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:45)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:86)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:80)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:80)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:668)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:668)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:78)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:668)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:276)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:270)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:228)
	at org.apache.seatunnel.spark.sink.Hudi.output(Hudi.scala:60)
	at org.apache.seatunnel.spark.sink.Hudi.output(Hudi.scala:30)
	at org.apache.seatunnel.spark.batch.SparkBatchExecution$.sinkProcess(SparkBatchExecution.scala:116)
	at org.apache.seatunnel.spark.batch.SparkBatchExecution$$anonfun$start$3.apply(SparkBatchExecution.scala:58)
	at org.apache.seatunnel.spark.batch.SparkBatchExecution$$anonfun$start$3.apply(SparkBatchExecution.scala:57)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at org.apache.seatunnel.spark.batch.SparkBatchExecution.start(SparkBatchExecution.scala:57)
	at org.apache.seatunnel.Seatunnel.entryPoint(Seatunnel.java:101)
	at org.apache.seatunnel.Seatunnel.run(Seatunnel.java:60)
	at org.apache.seatunnel.SeatunnelSpark.main(SeatunnelSpark.java:29)
```

### Flink or Spark Version

spark-2.4.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wuchunfu** [comment]
I seem to find a solution here https://github.com/apache/hudi/issues/3191, they have some people's solution is to upgrade spark version, so can we upgrade it? I have tried it and when I upgrade to `spark-2.4.8` the program works fine

**Comment by wuchunfu** [comment]
@CalvinKirs @leo65535 @simon824

**Comment by CalvinKirs** [comment]
Will it affect other components, in other words, will 2.4 be compatible with the current version?

**Comment by wuchunfu** [comment]
The current `spark` version in use is version `2.4.0` released in `2018` , I checked the `release notes` of `saprk-2.4.x` and it seems that no breaking changes were added in versions after `2.4.0`

**Comment by wuchunfu** [comment]
I tried `spark-2.4.0` and `hudi-0.7.0` here and they can write data normally, but `hudi-0.9.0` or newer version has some important features, such as: `Spark SQL DML and DDL Support`

**Comment by wuchunfu** [comment]
> Will it affect other components, in other words, will 2.4 be compatible with the current version?

The current spark version in use is version `2.4.0` released in `2018` , I checked the release notes of `saprk-2.4.x` and it seems that no breaking changes were added in versions after `2.4.0`

**Comment by wuchunfu** [comment]
I tried `spark-2.4.0` and `hudi-0.7.0` here and they can write data normally, but `hudi-0.9.0` or newer version has some important features, such as: `Spark SQL DML and DDL Support`

**Comment by simon824** [comment]
if it won't conflict with other components, i think it's a good idea to bump spark-2.4.0 to 2.4.8 @wuchunfu
