### ISSUE TITLE
[Bug] [connector] Use Hudi source  Serializable Exception

### ISSUE THREAD

**Issue by liujinhui1994** [apache/seatunnel#1273]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Use Hudi source  Serializable Exception！

### SeaTunnel Version

2.0.5-SNAPSHOT

### SeaTunnel Config

```conf
env {
  spark.app.name = "SeaTunnel"
  spark.master = local
}

source {
  hudi {
      hoodie.datasource.read.paths = "path"
      result_table_name="view_20220215"
  }
}

transform {
}

sink {
  Console {}
}
```

### Running Command

```shell
org.apache.seatunnel.example.spark.LocalSparkExample
Use this class to run locally
```

### Error Exception

```log
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Failed to serialize task 1, not attempting to retry it. Exception during serialization: java.io.NotSerializableException: org.apache.hadoop.fs.Path
Serialization stack:
	- object not serializable (class: org.apache.hadoop.fs.Path, value: file:/G:/tmp/2022)
	- element of array (index: 0)
	- array (class [Ljava.lang.Object;, size 1)
	- field (class: scala.collection.mutable.WrappedArray$ofRef, name: array, type: class [Ljava.lang.Object;)
	- object (class scala.collection.mutable.WrappedArray$ofRef, WrappedArray(file:/G:/tmp/2022))
	- writeObject data (class: org.apache.spark.rdd.ParallelCollectionPartition)
	- object (class org.apache.spark.rdd.ParallelCollectionPartition, org.apache.spark.rdd.ParallelCollectionPartition@6e3)
	- field (class: org.apache.spark.scheduler.ResultTask, name: partition, type: interface org.apache.spark.Partition)
	- object (class org.apache.spark.scheduler.ResultTask, ResultTask(1, 0))
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1887)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1875)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1874)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1874)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:926)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:926)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:926)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2108)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2057)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2046)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:737)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2061)
```

### Flink or Spark Version

2.0.5-SNAPSHOT run，unmodified version

### Java or Scala Version

2.0.5-SNAPSHOT run，unmodified version

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liujinhui1994** [comment]
@CalvinKirs    @leo65535 @simon824 @wuchunfu   please help me，am I missing something?

**Comment by liujinhui1994** [comment]
If you don't rely on seatunnel, it's ok. I looked through the source code and I didn't find the problem, can you remind me?

**Comment by simon824** [comment]
@liujinhui1994  Please check `hoodie.datasource.read.paths`, does the path you configured stored the hudi table?
BTW, this bug (#1164 ) about hudi was not fixed yet. You can manually downgrade the hudi version to fix it temporarily.

**Comment by liujinhui1994** [comment]
This is of course, it must be the hudi path @simon824

**Comment by liujinhui1994** [comment]
The error reported above should not be related to this problem https://github.com/apache/incubator-seatunnel/issues/1164

**Comment by liujinhui1994** [comment]
I already know what the problem is, it's a small problem with seatunnel, I will file a PR to fix it

**Comment by xleoken** [comment]
> I already know what the problem is, it's a small problem with seatunnel, I will file a PR to fix it

👍

**Comment by wuchunfu** [comment]
Fixed #1310

**Comment by bravekong** [comment]
@liujinhui1994  hello，May I ask you a question? I reported an error when using hudi as the source，

```
22/11/01 15:59:56 INFO TableSchemaResolver: Reading schema from hdfs://cluster:8020/hudi_data/person_infos/default/b7e36c6b-e264-4741-acad-9cde64a35aba-0_0-23-23_20221101145532.parquet
22/11/01 15:59:56 ERROR ApplicationMaster: User class threw exception: java.lang.NoSuchFieldError: NULL_VALUE
java.lang.NoSuchFieldError: NULL_VALUE
```

**Comment by legend91325** [comment]
@bravekong hi , have you fix this problem?  I have encounter this problem
