### ISSUE TITLE
[Bug] [JCommander] Error when starting start-seatunnel-flink.sh

### ISSUE THREAD

**Issue by JesseAtSZ** [apache/seatunnel#1356]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I use my own compiled version，mvn clean、mvn install、mvn package.
The size of the compiled jar package is about 800m.
![image](https://user-images.githubusercontent.com/35264598/156094355-1bf20a76-e48f-4c21-9165-60d4785fa09d.png)

Then I unzipped and used the installation package，an error occurred while running.

### SeaTunnel Version

Dev: 28e987539b9d38def39a061c5e229bd105e6ade1

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
}

source {
    FakeSourceStream {
      result_table_name = "fake"
      field_name = "name,age"
    }
}

transform {
    sql {
      sql = "select name,age from fake"
    }
}

sink {
  ConsoleSink {}
}
```

### Running Command

```shell
./start-seatunnel-flink.sh -c ../config/flink.streaming.conf.template

./start-seatunnel-sql.sh -c ../config/flink.streaming.conf.template
```

### Error Exception

```log
org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: Was passed main parameter '/opt/module/apache-seatunnel-incubating-2.0.5-SNAPSHOT/lib/seatunnel-core-flink.jar' but no main parameter was defined in your arg class
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:372)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222)
	at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114)
	at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:812)
	at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:246)
	at org.apache.flink.client.cli.CliFrontend.parseAndRun(CliFrontend.java:1054)
	at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1132)
	at org.apache.flink.runtime.security.contexts.NoOpSecurityContext.runSecured(NoOpSecurityContext.java:28)
	at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1132)
Caused by: com.beust.jcommander.ParameterException: Was passed main parameter '/opt/module/apache-seatunnel-incubating-2.0.5-SNAPSHOT/lib/seatunnel-core-flink.jar' but no main parameter was defined in your arg class
	at com.beust.jcommander.JCommander.initMainParameterValue(JCommander.java:954)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:755)
	at com.beust.jcommander.JCommander.parse(JCommander.java:356)
	at com.beust.jcommander.JCommander.parse(JCommander.java:335)
	at org.apache.seatunnel.config.command.CommandLineUtils.parseFlinkArgs(CommandLineUtils.java:46)
	at org.apache.seatunnel.SeatunnelFlink.main(SeatunnelFlink.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355)
	... 8 more
```

### Flink or Spark Version

Flink：1.13.0

### Screenshots

![image](https://user-images.githubusercontent.com/35264598/156094202-2c6a46cc-d5f3-46c4-9061-ce0cc821dc55.png)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JesseAtSZ** [comment]
The previous packaging command is：
1. mvn clean
2. mvn install
3. mvn package

I solved my problem by changing the packaging command to the following:
mvn clean package -DskipTests

The jar package size generated after this operation is 300m, about half of the previous size.

I don't know why it works.

**Comment by kalencaya** [comment]
I guess that typesafe config shade package may be the reason and I'm also not be familiar with maven, you can try more yourself.

Actually `mvn clean package -DskipTests` is only step of importing project into IDEA for me.

**Comment by libailin** [comment]
resaons 1 or 2:
1、 start-seatunnel-flink.sh may find two core flink jar:

```
assemblyJarName=$(find ${PLUGINS_DIR} -name seatunnel-core-flink*.jar)
```

2、 mvn clean package -DskipTests , builded two jar:

```
seatunnel-core-flink.jar
seatunnel-core-flink-2.0.5-SNAPSHOT-shaded.jar
```


resolve method:

please delete rm seatunnel-core-flink-2.0.5-SNAPSHOT-shaded.jar

```
cd seatunnel/lib
rm seatunnel-core-flink-2.0.5-SNAPSHOT-shaded.jar
```
