### ISSUE TITLE
[Bug] [spark-connector-jdbc] there are a NPE when sink in update mode

### ISSUE THREAD

**Issue by zhaomin1423** [apache/seatunnel#1409]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When the save mode is update.

### SeaTunnel Version

2.0.5-SNAPSHOT

### SeaTunnel Config

```conf
sink {
  jdbc {
        driver = "com.mysql.jdbc.Driver"
        saveMode = "update",
        truncate = "true",
        url = "",
        user = "",
        password =
        dbTable = ""
    }
}
```

### Running Command

```shell
LocalSparkExample
```

### Error Exception

```log
Exception in thread "main" java.lang.NullPointerException
	at org.apache.spark.sql.execution.datasources.jdbc2.JDBCRelation$.columnPartition(JDBCPartitioningInfo.scala:109)
	at org.apache.spark.sql.execution.datasources.jdbc2.DefaultSource.createRelation(DefaultSource.scala:38)
	at org.apache.spark.sql.execution.datasources.jdbc2.DefaultSource.createRelation(DefaultSource.scala:105)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:45)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
Please close this issue. Thanks.
