### ISSUE TITLE
input kudu  cannot  work  with seatunnel1.5.7

### ISSUE THREAD

**Issue by lorneWW** [apache/seatunnel#1457]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I tested the function of seatunnel and found that when the input is kudu, an error will be reported when executing the task. Always says kudu table not found. But the kudu table exists and can be used normally.
Below is the error message. Really appreciate it if you can help
**-----------------------------------------------------------------------------------**
2022-03-10 05:44:57 INFO  SparkUI:54 - Bound SparkUI to 0.0.0.0, and started at http://cdh1.f-qa.igen:13000
find and register UDFs & UDAFs
found and registered UDFs count[2], UDAFs count[0]
Exception in thread "main" java.lang.Exception: org.apache.kudu.client.NonRecoverableException: The table does not exist: table_name: "device.device_analysis_data_day"
	at io.github.interestinglab.waterdrop.Waterdrop$.main(Waterdrop.scala:62)
	at io.github.interestinglab.waterdrop.Waterdrop.main(Waterdrop.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: org.apache.kudu.client.NonRecoverableException: The table does not exist: table_name: "device.device_analysis_data_day"

### SeaTunnel Version

1.5.7

### SeaTunnel Config

```conf
spark {
  # seatunnel defined streaming batch duration in seconds
  spark.streaming.batchDuration = 5

  spark.app.name = "seatunnel"
  spark.ui.port = 13000
}

 input {
   kudu{
    kudu_master="cdh1.f-qa.igen:7051,cdh2.f-qa.igen:7051,cdh3.f-qa.igen:7051"
    kudu_table="device.device_analysis_data_day"
    result_table_name="current"
  }
 }
 filter {
   sql {
    sql = "select device_sn  from current limit 100 ",
  }
 }
output {
  Stdout {
  }
}
```

### Running Command

```shell
./bin/start-seatunnel.sh	--master local[4]  --deploy-mode client  --config ./config/application_kudu2s.conf
```

### Error Exception

```log
2022-03-10 05:44:57 INFO  SparkUI:54 - Bound SparkUI to 0.0.0.0, and started at http://cdh1.f-qa.igen:13000
find and register UDFs & UDAFs
found and registered UDFs count[2], UDAFs count[0]
Exception in thread "main" java.lang.Exception: org.apache.kudu.client.NonRecoverableException: The table does not exist: table_name: "device.device_analysis_data_day"
	at io.github.interestinglab.waterdrop.Waterdrop$.main(Waterdrop.scala:62)
	at io.github.interestinglab.waterdrop.Waterdrop.main(Waterdrop.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: org.apache.kudu.client.NonRecoverableException: The table does not exist: table_name: "device.device_analysis_data_day"
```

### Flink or Spark Version

spark version 2.3.0.cloudera4

### Java or Scala Version

java 1.8
scala 2.11

### Screenshots

11

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lorneWW** [comment]
ok

**Comment by allenchen0314** [comment]
you can try to write
 kudu_table="impala::device.device_analysis_data_day"
