### ISSUE TITLE
[Bug] [flink-connector-jdbc] jdbc related dependency scope is provided

### ISSUE THREAD

**Issue by kalencaya** [apache/seatunnel#1463]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

location on `seatunnel/pom.xml`, `flink-connector-jdbc_2.11` scope is `provided` and seatunnel release doesn't contain flink-connector-jdbc dependency.
```
<flink.scope>provided</flink.scope>

......

<dependency>
    <groupId>org.apache.flink</groupId>
    <artifactId>flink-connector-jdbc_${scala.binary.version}</artifactId>
    <version>${flink.version}</version>
    <scope>${flink.scope}</scope>
</dependency>
```
The same problem is MySQL JDBC driver dependency, and for license compliance, we have to warn people adding driver by themselves.
```
<!--Because the license is not in compliance, if you need to use MySQL, you can add it yourself-->
<dependency>
    <groupId>mysql</groupId>
    <artifactId>mysql-connector-java</artifactId>
    <version>${mysql.version}</version>
    <scope>test</scope>
</dependency>
```

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
not needed
```

### Running Command

```shell
not needed
```

### Error Exception

```log
not needed
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
@kalencaya @CalvinKirs 
Does this also happen on other dependencies related to flink-xx, like "flink-java", `flink-streaming-java_xx`...? 

Actually, I don't know why the scope of `flink-xx` is designed as `provided` in seatunnel, does this due to we want user to upload target dependency version by themselves? If so, this issue should be closed, otherwise, we may also need to remove `provided` of other dependencies.

**Comment by Hisoka-X** [comment]
Also confuses me, I think these plugin denpency should in plugins folder in release package. Like flink, user can move jar in release package for use it.

**Comment by ruanwenjun** [comment]
I guess this mainly due to we use `maven-shade-plugin`, this plugin make the package result into a fat jar.
And the reason why we do this is the seatunnel job is a flink job, we need to package it into a fat jar.

**Comment by ruanwenjun** [comment]
I test on 2.1.0, this happened due to miss `flink-connector-jdbc_xx`.

```java
java.lang.NoClassDefFoundError: org/apache/flink/connector/jdbc/JdbcInputFormat
	at org.apache.seatunnel.flink.source.JdbcSource.prepare(JdbcSource.java:163)
	at org.apache.seatunnel.flink.source.JdbcSource.prepare(JdbcSource.java:60)
	at org.apache.seatunnel.Seatunnel.lambda$prepare$0(Seatunnel.java:160)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.apache.seatunnel.Seatunnel.prepare(Seatunnel.java:160)
	at org.apache.seatunnel.Seatunnel.entryPoint(Seatunnel.java:104)
	at org.apache.seatunnel.Seatunnel.run(Seatunnel.java:65)
	at org.apache.seatunnel.SeatunnelFlink.main(SeatunnelFlink.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222)
	at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114)
	at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:812)
	at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:246)
	at org.apache.flink.client.cli.CliFrontend.parseAndRun(CliFrontend.java:1054)
	at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1132)
	at org.apache.flink.runtime.security.contexts.NoOpSecurityContext.runSecured(NoOpSecurityContext.java:28)
	at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1132)
Caused by: java.lang.ClassNotFoundException: org.apache.flink.connector.jdbc.JdbcInputFormat
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at org.apache.flink.util.FlinkUserCodeClassLoader.loadClassWithoutExceptionHandling(FlinkUserCodeClassLoader.java:64)
	at org.apache.flink.util.ChildFirstClassLoader.loadClassWithoutExceptionHandling(ChildFirstClassLoader.java:65)
	at org.apache.flink.util.FlinkUserCodeClassLoader.loadClass(FlinkUserCodeClassLoader.java:48)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 21 more
```

**Comment by kalencaya** [comment]
`FLINK_HOME/lib` provides Flink core dependencies, which not includes connectors released by Flink. Flink job jar has to provide needed connector and user-jar dependencies.

It is reasonable for flink core dependencies within `provided` scope and connector dependencies within default `compile` scope.

After I checked other flink connector dependency such as `flink-connector-kafka` and `flink-connector-elasticsearch6`, which already in default `compile` scope, `flink-connector-jdbc` within `provided` scope may be an unnoticed mistake.

**Comment by ruanwenjun** [comment]
> 

@kalencaya Yes, agree with you. The best practice to build a Flink application is just to set the scope of runtime dependencies to  provided, and other dependencies like connector needed to be compiled. So it's necessary to remove the scope provided of `flink-connector-jdbc_${scala.binary.version}`. 
We can find doc from [Flink Core and Application Dependencies](https://nightlies.apache.org/flink/flink-docs-release-1.13/docs/dev/datastream/project-configuration/#flink-core-and-application-dependencies)

cc @CalvinKirs

**Comment by Schiewatir** [comment]
one of the most unreliable, undocumented and definitely no any straight forward way to use Apache Flink connectors
