### ISSUE TITLE
[Bug] [Module Name] When start seatunnel, cause org.apache.flink.client.program.ProgramInvocationException.

### ISSUE THREAD

**Issue by dongzl** [apache/seatunnel#1480]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

```
------------------------------------------------------------
 The program finished with the following exception:

org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: The old planner has been removed in Flink 1.14. Please upgrade your table program to use the default planner (previously called the 'blink' planner).
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:372)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222)
	at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114)
	at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:812)
	at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:246)
	at org.apache.flink.client.cli.CliFrontend.parseAndRun(CliFrontend.java:1054)
	at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1132)
	at org.apache.flink.runtime.security.contexts.NoOpSecurityContext.runSecured(NoOpSecurityContext.java:28)
	at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1132)
Caused by: org.apache.flink.table.api.TableException: The old planner has been removed in Flink 1.14. Please upgrade your table program to use the default planner (previously called the 'blink' planner).
	at org.apache.flink.table.api.EnvironmentSettings$Builder.useOldPlanner(EnvironmentSettings.java:238)
	at org.apache.seatunnel.flink.FlinkEnvironment.createStreamTableEnvironment(FlinkEnvironment.java:115)
	at org.apache.seatunnel.flink.FlinkEnvironment.prepare(FlinkEnvironment.java:82)
	at org.apache.seatunnel.flink.FlinkEnvironment.prepare(FlinkEnvironment.java:44)
	at org.apache.seatunnel.config.ConfigBuilder.createEnv(ConfigBuilder.java:196)
	at org.apache.seatunnel.config.ConfigBuilder.<init>(ConfigBuilder.java:66)
	at org.apache.seatunnel.Seatunnel.entryPoint(Seatunnel.java:98)
	at org.apache.seatunnel.Seatunnel.run(Seatunnel.java:65)
	at org.apache.seatunnel.SeatunnelFlink.main(SeatunnelFlink.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355)
	... 8 more
```

### SeaTunnel Version

seatunnel: `apache-seatunnel-incubating-2.1.0`

### SeaTunnel Config

```conf
env {
  # You can set flink configuration here
  execution.parallelism = 1
  #execution.checkpoint.interval = 10000
  #execution.checkpoint.data-uri = "hdfs://localhost:9000/checkpoint"
}

source {
    SocketStream{
          result_table_name = "fake"
          field_name = "info"
    }
}

transform {
  Split{
    separator = "#"
    fields = ["name","age"]
  }
  sql {
    sql = "select * from (select info,split(info) as info_row from fake) t1"
  }
}

sink {
  ConsoleSink {}
}

```
```


### Running Command

```shell
./bin/start-seatunnel-flink.sh --config ./config/application.conf
```
```


### Error Exception

```log
------------------------------------------------------------
 The program finished with the following exception:

org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: The old planner has been removed in Flink 1.14. Please upgrade your table program to use the default planner (previously called the 'blink' planner).
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:372)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222)
	at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114)
	at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:812)
	at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:246)
	at org.apache.flink.client.cli.CliFrontend.parseAndRun(CliFrontend.java:1054)
	at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1132)
	at org.apache.flink.runtime.security.contexts.NoOpSecurityContext.runSecured(NoOpSecurityContext.java:28)
	at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1132)
Caused by: org.apache.flink.table.api.TableException: The old planner has been removed in Flink 1.14. Please upgrade your table program to use the default planner (previously called the 'blink' planner).
	at org.apache.flink.table.api.EnvironmentSettings$Builder.useOldPlanner(EnvironmentSettings.java:238)
	at org.apache.seatunnel.flink.FlinkEnvironment.createStreamTableEnvironment(FlinkEnvironment.java:115)
	at org.apache.seatunnel.flink.FlinkEnvironment.prepare(FlinkEnvironment.java:82)
	at org.apache.seatunnel.flink.FlinkEnvironment.prepare(FlinkEnvironment.java:44)
	at org.apache.seatunnel.config.ConfigBuilder.createEnv(ConfigBuilder.java:196)
	at org.apache.seatunnel.config.ConfigBuilder.<init>(ConfigBuilder.java:66)
	at org.apache.seatunnel.Seatunnel.entryPoint(Seatunnel.java:98)
	at org.apache.seatunnel.Seatunnel.run(Seatunnel.java:65)
	at org.apache.seatunnel.SeatunnelFlink.main(SeatunnelFlink.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355)
	... 8 more
```
```


### Flink or Spark Version

flink: `flink-1.14.3`

### Java or Scala Version

JDK 1.8

### Screenshots

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
Seatunnel base on flink 1.13.6 at now. So program will report error when running at flink 1.14.3.

**Comment by ruanwenjun** [comment]
> Seatunnel base on flink 1.13.6 at now. So program will report error when running at flink 1.14.3.

Yeah, I use this config running on 1.13.6, it was normal. May need to consider if Flink can be upgrade.

**Comment by dongzl** [comment]
Hi @BenJFan B, @ruanwenjun   Thanks for reply, I will test `1.13.6`. 

Maybe we can consider to upgrade Flink.

**Comment by ruanwenjun** [comment]
> Hi @BenJFan B, @ruanwenjun Thanks for reply, I will test `1.13.6`.
> 
> Maybe we can consider to upgrade Flink.

Agree with you.

**Comment by AdkinsHan** [comment]
> Hi @BenJFan B, @ruanwenjun Thanks for reply, I will test `1.13.6`.
> 
> Maybe we can consider to upgrade Flink.

do you have a plan
