### ISSUE TITLE
org.apache.flink.client.program.ProgramInvocationException

### ISSUE THREAD

**Issue by fpystart** [apache/seatunnel#1535]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I pack locally and upload it to the server for operation. An error is reported

### SeaTunnel Version

2.1.0

### SeaTunnel Config

```conf
The program finished with the following exception:

org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: Was passed main parameter '/home/puaiuc/seatunnel_test/apache-seatunnel-incubating-2.0.5-SNAPSHOT/lib/seatunnel-core-flink.jar' but no main parameter was defined in your arg class
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:372)
        at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222)
        at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114)
        at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:812)
        at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:246)
        at org.apache.flink.client.cli.CliFrontend.parseAndRun(CliFrontend.java:1054)
        at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1132)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1836)
        at org.apache.flink.runtime.security.contexts.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:41)
        at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1132)
Caused by: com.beust.jcommander.ParameterException: Was passed main parameter '/home/puaiuc/seatunnel_test/apache-seatunnel-incubating-2.0.5-SNAPSHOT/lib/seatunnel-core-flink.jar' but no main parameter was defined in your arg class
        at com.beust.jcommander.JCommander.initMainParameterValue(JCommander.java:954)
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:755)
        at com.beust.jcommander.JCommander.parse(JCommander.java:356)
        at com.beust.jcommander.JCommander.parse(JCommander.java:335)
        at org.apache.seatunnel.utils.CommandLineUtils.parseFlinkArgs(CommandLineUtils.java:44)
        at org.apache.seatunnel.SeatunnelFlink.main(SeatunnelFlink.java:26)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355)
        ... 11 more
```

### Running Command

```shell
./start-seatunnel-flink.sh --config ~/data_process_test/release_job/cm_pon_ori_olt.conf
```

### Error Exception

```log
The program finished with the following exception:

org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: Was passed main parameter '/home/puaiuc/seatunnel_test/apache-seatunnel-incubating-2.0.5-SNAPSHOT/lib/seatunnel-core-flink.jar' but no main parameter was defined in your arg class
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:372)
        at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222)
        at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114)
        at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:812)
        at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:246)
        at org.apache.flink.client.cli.CliFrontend.parseAndRun(CliFrontend.java:1054)
        at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1132)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1836)
        at org.apache.flink.runtime.security.contexts.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:41)
        at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1132)
Caused by: com.beust.jcommander.ParameterException: Was passed main parameter '/home/puaiuc/seatunnel_test/apache-seatunnel-incubating-2.0.5-SNAPSHOT/lib/seatunnel-core-flink.jar' but no main parameter was defined in your arg class
        at com.beust.jcommander.JCommander.initMainParameterValue(JCommander.java:954)
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:755)
        at com.beust.jcommander.JCommander.parse(JCommander.java:356)
        at com.beust.jcommander.JCommander.parse(JCommander.java:335)
        at org.apache.seatunnel.utils.CommandLineUtils.parseFlinkArgs(CommandLineUtils.java:44)
        at org.apache.seatunnel.SeatunnelFlink.main(SeatunnelFlink.java:26)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355)
        ... 11 more
```

### Flink or Spark Version

1.13.6

### Java or Scala Version

1.8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
Which commitid do your code version? I run local normaly
<img width="623" alt="image" src="https://user-images.githubusercontent.com/32387433/159454036-a6da3c7d-81c3-4513-9a37-292154e8bbfa.png">

**Comment by fpystart** [comment]
The latest submission, and I have no problem running locally, is that it cannot run on the server after packaging

![image](https://user-images.githubusercontent.com/102137792/159454695-e24720a7-e6c4-4104-97dc-34e6b709608d.png)

**Comment by fpystart** [comment]
The latest submission, and I have no problem running locally, is that it cannot run on the server after packaging

**Comment by Hisoka-X** [comment]
> The latest submission, and I have no problem running locally, is that it cannot run on the server after packaging

What mean for packaging? mvn package?

**Comment by fpystart** [comment]
yes
mvn package

**Comment by yx91490** [comment]
please rerun startup script with "bash -x ./start-seatunnel-flink.sh..." and paste log here for help.

**Comment by fpystart** [comment]
bash -x ./bin/start-seatunnel-flink.sh -c ~/data_process_test/debug_job/cm_pon_ori_onu_es.conf
+ [[ -c /home/puaiuc/data_process_test/debug_job/cm_pon_ori_onu_es.conf = *--help ]]
+ [[ -c /home/puaiuc/data_process_test/debug_job/cm_pon_ori_onu_es.conf = *-h ]]
+ [[ 2 -le 1 ]]
+ PARAMS=
+ ((  2  ))
+ case "$1" in
+ CONFIG_FILE=/home/puaiuc/data_process_test/debug_job/cm_pon_ori_onu_es.conf
+ is_exist /home/puaiuc/data_process_test/debug_job/cm_pon_ori_onu_es.conf
+ '[' -z /home/puaiuc/data_process_test/debug_job/cm_pon_ori_onu_es.conf ']'
+ shift 2
+ ((  0  ))
+ '[' -z /home/puaiuc/data_process_test/debug_job/cm_pon_ori_onu_es.conf ']'
+ '[' '!' -f /home/puaiuc/data_process_test/debug_job/cm_pon_ori_onu_es.conf ']'
+ eval set -- ''
++ set --
+++ dirname ./bin/start-seatunnel-flink.sh
++ cd ./bin
++ pwd
+ BIN_DIR=/home/puaiuc/seatunnel_test/apache-seatunnel-incubating-2.0.5-SNAPSHOT/bin
++ dirname /home/puaiuc/seatunnel_test/apache-seatunnel-incubating-2.0.5-SNAPSHOT/bin
+ APP_DIR=/home/puaiuc/seatunnel_test/apache-seatunnel-incubating-2.0.5-SNAPSHOT
+ CONF_DIR=/home/puaiuc/seatunnel_test/apache-seatunnel-incubating-2.0.5-SNAPSHOT/config
+ PLUGINS_DIR=/home/puaiuc/seatunnel_test/apache-seatunnel-incubating-2.0.5-SNAPSHOT/lib
+ DEFAULT_CONFIG=/home/puaiuc/seatunnel_test/apache-seatunnel-incubating-2.0.5-SNAPSHOT/config/application.conf
+ CONFIG_FILE=/home/puaiuc/data_process_test/debug_job/cm_pon_ori_onu_es.conf
++ find /home/puaiuc/seatunnel_test/apache-seatunnel-incubating-2.0.5-SNAPSHOT/lib -name 'seatunnel-core-flink*.jar'
+ assemblyJarName='/home/puaiuc/seatunnel_test/apache-seatunnel-incubating-2.0.5-SNAPSHOT/lib/seatunnel-core-flink-2.0.5-SNAPSHOT-shaded.jar
/home/puaiuc/seatunnel_test/apache-seatunnel-incubating-2.0.5-SNAPSHOT/lib/seatunnel-core-flink.jar'
+ '[' -f /home/puaiuc/seatunnel_test/apache-seatunnel-incubating-2.0.5-SNAPSHOT/config/seatunnel-env.sh ']'
+ source /home/puaiuc/seatunnel_test/apache-seatunnel-incubating-2.0.5-SNAPSHOT/config/seatunnel-env.sh
++ SPARK_HOME=/opt/spark
++ FLINK_HOME=/home/puaiuc/flink-1.13.6
++ export SEATUNNEL_PRINT_ASCII_LOGO=true
++ SEATUNNEL_PRINT_ASCII_LOGO=true
++ string_trim ''
++ echo
++ awk '{$1=$1;print}'
+ JVM_ARGS=
+ export JVM_ARGS
+ exec /home/puaiuc/flink-1.13.6/bin/flink run -c org.apache.seatunnel.SeatunnelFlink /home/puaiuc/seatunnel_test/apache-seatunnel-incubating-2.0.5-SNAPSHOT/lib/seatunnel-core-flink-2.0.5-SNAPSHOT-shaded.jar /home/puaiuc/seatunnel_test/apache-seatunnel-incubating-2.0.5-SNAPSHOT/lib/seatunnel-core-flink.jar --config /home/puaiuc/data_process_test/debug_job/cm_pon_ori_onu_es.conf
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/puaiuc/flink-1.13.6/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/puaiuc/hadoop-2.8.3/share/hadoop/common/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]

------------------------------------------------------------
 The program finished with the following exception:

org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: Was passed main parameter '/home/puaiuc/seatunnel_test/apache-seatunnel-incubating-2.0.5-SNAPSHOT/lib/seatunnel-core-flink.jar' but no main parameter was defined in your arg class
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:372)
        at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222)
        at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114)
        at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:812)
        at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:246)
        at org.apache.flink.client.cli.CliFrontend.parseAndRun(CliFrontend.java:1054)
        at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1132)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1836)
        at org.apache.flink.runtime.security.contexts.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:41)
        at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1132)
Caused by: com.beust.jcommander.ParameterException: Was passed main parameter '/home/puaiuc/seatunnel_test/apache-seatunnel-incubating-2.0.5-SNAPSHOT/lib/seatunnel-core-flink.jar' but no main parameter was defined in your arg class
        at com.beust.jcommander.JCommander.initMainParameterValue(JCommander.java:954)
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:755)
        at com.beust.jcommander.JCommander.parse(JCommander.java:356)
        at com.beust.jcommander.JCommander.parse(JCommander.java:335)
        at org.apache.seatunnel.utils.CommandLineUtils.parseFlinkArgs(CommandLineUtils.java:44)
        at org.apache.seatunnel.SeatunnelFlink.main(SeatunnelFlink.java:26)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355)
        ... 11 more
[puaiuc@oss-irms-187 apache-seatunnel-incubating-2.0.5-SNAPSHOT]$

**Comment by yx91490** [comment]
It seems that `seatunnel-core-flink-2.0.5-SNAPSHOT-shaded.jar` shouldn't appear in `lib` directory, how do you package? in `dev` branch, no this problem.

**Comment by fpystart** [comment]
![image](https://user-images.githubusercontent.com/102137792/160049993-b59165d3-fa74-46be-b993-e402dda78f20.png)

I packed it in the dev branch，and seatunnel-core-flink-2.0.5-SNAPSHOT-shaded.jar is in lib directory

**Comment by fpystart** [comment]
I solved this problem, thanks!
