### ISSUE TITLE
[Bug] [connector-spark-console] NoSuchMethodError org.apache.seatunnel.spark.Config

### ISSUE THREAD

**Issue by liujinhui1994** [apache/seatunnel#1595]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

An exception occurred when using LocalSparkExample to verify the seatunnel function

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
env {
  spark.app.name = "SeaTunnel"
  spark.executor.instances = 2
  spark.executor.cores = 1
  spark.executor.memory = "1g"
  spark.master = local
}

source {
    kafkaStream  {
    result_table_name = "my_dataset"
    topics = "test"
    consumer.group.id = "test_group"
    consumer.bootstrap.servers = "localhost:9092"
  }
}

transform {}

sink {
  Console {}
}
```

### Running Command

```shell
LocalSparkExample
```

### Error Exception

```log
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.seatunnel.spark.Config$.LIMIT()Ljava/lang/String;
	at org.apache.seatunnel.spark.sink.Console.checkConfig(Console.scala:56)
	at org.apache.seatunnel.command.BaseTaskExecuteCommand.pluginCheck(BaseTaskExecuteCommand.java:122)
	at org.apache.seatunnel.command.BaseTaskExecuteCommand.baseCheckConfig(BaseTaskExecuteCommand.java:60)
	at org.apache.seatunnel.command.spark.SparkTaskExecuteCommand.execute(SparkTaskExecuteCommand.java:45)
	at org.apache.seatunnel.command.spark.SparkTaskExecuteCommand.execute(SparkTaskExecuteCommand.java:32)
	at org.apache.seatunnel.Seatunnel.run(Seatunnel.java:48)
	at org.apache.seatunnel.example.spark.LocalSparkExample.main(LocalSparkExample.java:34)
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liujinhui1994** [comment]
https://github.com/apache/incubator-seatunnel/pull/1592   It will be resolved here, so close
