### ISSUE TITLE
[Bug] [Spark] Remove load plugins in SparkStarter

### ISSUE THREAD

**Issue by ruanwenjun** [apache/seatunnel#1650]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Since in the latest version of seatunnel, we deleted the plugin module.
So we don't need to add plugin'jar into `--jars`.

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
no
```

### Running Command

```shell
bash bin/start-seatunnel-spark.sh --master yarn --deploy-mode cluster -c config/spark.batch.conf.template
```

### Error Exception

```log
Exception in thread "main" java.nio.file.NoSuchFileException: plugins
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:220)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277)
	at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:323)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2804)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2882)
	at org.apache.seatunnel.utils.CompressionUtils.tarGzip(CompressionUtils.java:66)
	at org.apache.seatunnel.SparkStarter$ClusterModeSparkStarter.buildCommands(SparkStarter.java:379)
	at org.apache.seatunnel.SparkStarter.main(SparkStarter.java:98)
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Closed, maybe we cannot delete the plugins directory, this directory may store some schema file.
