### ISSUE TITLE
[Bug][help wanted][Source][JdbcSource] Flink JdbcSource getRowTypeInfo() throws NullPointerException

### ISSUE THREAD

**Issue by Coder-Gorson** [apache/seatunnel#1659]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

JdbcSource method throws NullPointerException when I run seatunnel demo .
Is this a bug? or I run with an error config.

### SeaTunnel Version

seatunnel-2.1.0

### SeaTunnel Config

```conf
env {
    execution.parallelism = 1
}

source {
  JdbcSource {
    driver = com.mysql.cj.jdbc.Driver
    url = "jdbc:mysql://192.168.31.??/prcd_db_dev"
    username = usr
    password = pwd
                   #varchar      varchar    varchar
    query = "select bp_appl_seq, cust_name, sale_prd_name from appl_info"
  }
}

transform {

}

sink {
  ConsoleSink{}
}
```

### Running Command

```shell
sh ./bin/start-seatunnel-flink.sh -c ./config/flink.batch.mysql2console
```

### Error Exception

```log
[seatunnel@cube_ycloans_app1 seatunnel-2.1.0]$ sh ./bin/start-seatunnel-flink.sh -c ./config/flink.batch.mysql2console 

------------------------------------------------------------
 The program finished with the following exception:

org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: null
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:372)
        at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222)
        at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114)
        at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:812)
        at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:246)
        at org.apache.flink.client.cli.CliFrontend.parseAndRun(CliFrontend.java:1054)
        at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1132)
        at org.apache.flink.runtime.security.contexts.NoOpSecurityContext.runSecured(NoOpSecurityContext.java:28)
        at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1132)
Caused by: java.lang.NullPointerException
        at org.apache.flink.api.java.typeutils.TupleTypeInfoBase.<init>(TupleTypeInfoBase.java:64)
        at org.apache.flink.api.java.typeutils.RowTypeInfo.<init>(RowTypeInfo.java:89)
        at org.apache.seatunnel.flink.source.JdbcSource.getRowTypeInfo(JdbcSource.java:210)
        at org.apache.seatunnel.flink.source.JdbcSource.prepare(JdbcSource.java:170)
        at org.apache.seatunnel.flink.source.JdbcSource.prepare(JdbcSource.java:60)
        at org.apache.seatunnel.Seatunnel.lambda$prepare$0(Seatunnel.java:160)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at org.apache.seatunnel.Seatunnel.prepare(Seatunnel.java:160)
        at org.apache.seatunnel.Seatunnel.entryPoint(Seatunnel.java:104)
        at org.apache.seatunnel.Seatunnel.run(Seatunnel.java:65)
        at org.apache.seatunnel.SeatunnelFlink.main(SeatunnelFlink.java:29)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355)
        ... 8 more
```

### Flink or Spark Version

flink-1.13.0

### Java or Scala Version

Java 1.8

### Screenshots

![image](https://user-images.githubusercontent.com/59015291/161901037-7b93ff90-92b1-4b99-b76b-a630ebb3ffe3.png)
![image](https://user-images.githubusercontent.com/59015291/161901200-32c513a8-6b7f-4e09-a2e0-663dbb7d5a1e.png)
![image](https://user-images.githubusercontent.com/59015291/161901286-05d5ad09-c50c-4934-bd30-0e88a8115f9b.png)
![image](https://user-images.githubusercontent.com/59015291/161901352-80c16446-ec14-47aa-a363-f3b04cb70d6f.png)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
Does column name is uppercase? But query command is lowercase

**Comment by Coder-Gorson** [comment]
> Does column name is uppercase? But query command is lowercase

Yes,you are right. Thanks.

**Comment by zhoutianmao** [comment]
I also have this problem.

**Comment by Hisoka-X** [comment]
> I also have this problem.

Please provide your config, and your database DDL

**Comment by zhoutianmao** [comment]
![image](https://user-images.githubusercontent.com/8804520/163713827-59b4e3c1-63d3-4efe-ac77-c22634af7683.png)
![image](https://user-images.githubusercontent.com/8804520/163713843-51cff0df-3616-4cff-be8b-4e05e23bd67f.png)

my config and my DDL.

Thanks.

**Comment by zhoutianmao** [comment]
![image](https://user-images.githubusercontent.com/8804520/163713878-1d270dcb-9b7f-45fb-9a78-c27f26ec4b32.png)

**Comment by zhoutianmao** [comment]
![image](https://user-images.githubusercontent.com/8804520/163713930-92317d8b-5f4d-4e13-88b0-5fef8c58b194.png)

**Comment by zhoutianmao** [comment]
![image](https://user-images.githubusercontent.com/8804520/163714043-b9ce0f3b-8d50-4baa-8afb-0a8e3a841965.png)

**Comment by zhoutianmao** [comment]
<img width="509" alt="image" src="https://user-images.githubusercontent.com/8804520/163714058-44b3c55c-e546-4625-8dfb-c875eccaf133.png">

**Comment by zhoutianmao** [comment]
My config  and my database DDL.
Thanks.

**Comment by Hisoka-X** [comment]
Your database is Oracle, Maybe we should do some work to support it. Tranck on #1709

**Comment by zhoutianmao** [comment]
Ok.Thanks.
