### ISSUE TITLE
[Bug] [seatunnel-core-base] Error when tar directory 'plugins' to file 'plugins.tar.gz'

### ISSUE THREAD

**Issue by xinda77** [apache/seatunnel#1739]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

when run seatunnel job ,i want to know  which version can we use 2.1.0 or 2.1.1 . like this simple error
Exception in thread "main" java.nio.file.AccessDeniedException: plugins.tar.gz
		at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
		at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
		at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
		at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
		at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
		at java.nio.file.Files.newOutputStream(Files.java:216)
		at org.apache.seatunnel.utils.CompressionUtils.tarGzip(CompressionUtils.java:62)
		at org.apache.seatunnel.SparkStarter$ClusterModeSparkStarter.buildCommands(SparkStarter.java:381)
		at org.apache.seatunnel.SparkStarter.main(SparkStarter.java:98)
	0 [main] INFO org.apache.seatunnel.utils.CompressionUtils - Tar directory 'plugins' to file 'plugins.tar.gz'. 1 [main] ERROR org.apache.seatunnel.utils.CompressionUtils - Error when tar directory 'plugins' to file 'plugins.tar.gz'.

### SeaTunnel Version

2.1.1

### SeaTunnel Config

```conf
..............
```

### Running Command

```shell
....................
```

### Error Exception

```log
Exception in thread "main" java.nio.file.AccessDeniedException: plugins.tar.gz
		at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
		at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
		at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
		at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
		at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
		at java.nio.file.Files.newOutputStream(Files.java:216)
		at org.apache.seatunnel.utils.CompressionUtils.tarGzip(CompressionUtils.java:62)
		at org.apache.seatunnel.SparkStarter$ClusterModeSparkStarter.buildCommands(SparkStarter.java:381)
		at org.apache.seatunnel.SparkStarter.main(SparkStarter.java:98)
	0 [main] INFO org.apache.seatunnel.utils.CompressionUtils - Tar directory 'plugins' to file 'plugins.tar.gz'. 1 [main] ERROR org.apache.seatunnel.utils.CompressionUtils - Error when tar directory 'plugins' to file 'plugins.tar.gz'.
```

### Flink or Spark Version

2.4.0-cdh6.3.2

### Java or Scala Version

1.8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
Please provide your environment, like Spark deployment mode (yarn or standalone), and your submit shell command.

**Comment by Hisoka-X** [comment]
And please make sure your SeaTunenl package permission is can be access with your start shell command's user.

**Comment by xinda77** [comment]
cluster mode,  why use shell to tar resource ? Don't be so different between versions. Don't refactor stable modules and focus on other directions

**Comment by Hisoka-X** [comment]
> cluster mode, why use shell to tar resource ? Don't be so different between versions. Don't refactor stable modules and focus on other directions

Compress resource is in Java code. Use shell to call java program. And can you provide permission for `plugins.tar.gz` and project root path?

**Comment by xinda77** [comment]
In the user directory(/home), and I can tar resource under the shell, 1.5 X and 2.1.0 are OK. The changes in this part are so big that the test work is not done well. users can't run job  with root

**Comment by xinda77** [comment]
> > cluster mode, why use shell to tar resource ? Don't be so different between versions. Don't refactor stable modules and focus on other directions
> 
> Compress resource is in Java code. Use shell to call java program. And can you provide permission for `plugins.tar.gz` and project root path?

Did you develop this code?, Can we go back to 2.1.0? Don't be so fancy on these simple functions that we can't be used

**Comment by Hisoka-X** [comment]
> > > cluster mode, why use shell to tar resource ? Don't be so different between versions. Don't refactor stable modules and focus on other directions
> > 
> > 
> > Compress resource is in Java code. Use shell to call java program. And can you provide permission for `plugins.tar.gz` and project root path?
> 
> Did you develop this code?, Can we go back to 2.1.0? Don't be so fancy on these simple functions that we can't be used

`plugins.tar.gz` have a long history, not develop on 2.1.1

**Comment by liuhe36** [comment]
mark
