### ISSUE TITLE
[Bug] [Connector] Clickhouse sink can not work correctly when use multiple hosts

### ISSUE THREAD

**Issue by xpleaf** [apache/seatunnel#1808]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When sink is ClickHouse and multiple hosts are configured:
```
sink {
	clickhouse {
    host = "192.168.56.101:8123,192.168.56.102:8123"
    ......
	}
}
```
All kinds of problems are triggered and the current system does not work properly. For details, see the exception information description in the Exception section.

The root cause of this problem is that the `split_mode` code is not compatible with multiple hosts. The processing logic of the `split_mode` code assumes that the host configuration item has only one address.This will cause ClickHouse Sink to fail if multiple hosts are specified, regardless of whether `split_mode` is used.

I have re-compatible the multi-host scenario in a subsequent commit without affecting the existing functionality, and when `split_mode` is false, data writes are load-balanced according to the multiple hosts specified.

### SeaTunnel Version

2.1.1/dev

### SeaTunnel Config

```conf
env {
  spark.app.name = "SeaTunnel"
  spark.sql.catalogImplementation = "hive"
  spark.executor.instances = 2
  spark.executor.cores = 1
  spark.executor.memory = "1g"
  spark.master = local
}

source {
  hive {
    pre_sql = "select id,key1,value1,key2,value2,key3,value3,dt from gac.tmp"
    result_table_name = "tmp"
  }
}

transform {}

sink {
	clickhouse {
    host = "192.168.10.101:8123,192.168.10.102:8123"
    clickhouse.socket_timeout = 50000
    database = "gac"
    table = "hive_tmp"
    fields = ["id", "key1", "value1", "key2", "value2", "key3", "value3", "dt"]
    username = "gac_se"
    password = "123456"
    bulk_size = 20000
    split_mode = false // or true
	}
}
```

### Running Command

```shell
default
```

### Error Exception
When host is set to multiple hosts.
When `split_mode` is true, the exception message is:
```log
Caused by: java.lang.IllegalArgumentException: port is missed or wrong
	at ru.yandex.clickhouse.ClickhouseJdbcUrlParser.parseClickhouseUrl(ClickhouseJdbcUrlParser.java:42)
	at ru.yandex.clickhouse.ClickhouseJdbcUrlParser.parse(ClickhouseJdbcUrlParser.java:30)
	at ru.yandex.clickhouse.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:69)
	at ru.yandex.clickhouse.ClickHouseDriver.connect(ClickHouseDriver.java:55)
	at ru.yandex.clickhouse.BalancedClickhouseDataSource.getConnection(BalancedClickhouseDataSource.java:194)
	at org.apache.seatunnel.spark.clickhouse.sink.Clickhouse$$anonfun$output$1$$anonfun$1.apply(Clickhouse.scala:84)
	at org.apache.seatunnel.spark.clickhouse.sink.Clickhouse$$anonfun$output$1$$anonfun$1.apply(Clickhouse.scala:82)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.seatunnel.spark.clickhouse.sink.Clickhouse$$anonfun$output$1.apply(Clickhouse.scala:82)
	at org.apache.seatunnel.spark.clickhouse.sink.Clickhouse$$anonfun$output$1.apply(Clickhouse.scala:80)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:935)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:935)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:402)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:408)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

When `split_mode` is false, the exception information is:
```log
Caused by: java.lang.IllegalArgumentException: port is missed or wrong
	at ru.yandex.clickhouse.ClickhouseJdbcUrlParser.parseClickhouseUrl(ClickhouseJdbcUrlParser.java:42)
	at ru.yandex.clickhouse.ClickhouseJdbcUrlParser.parse(ClickhouseJdbcUrlParser.java:30)
	at ru.yandex.clickhouse.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:69)
	at ru.yandex.clickhouse.ClickHouseDriver.connect(ClickHouseDriver.java:55)
	at ru.yandex.clickhouse.BalancedClickhouseDataSource.getConnection(BalancedClickhouseDataSource.java:194)
	at org.apache.seatunnel.spark.clickhouse.sink.Clickhouse$$anonfun$output$1$$anonfun$1.apply(Clickhouse.scala:84)
	at org.apache.seatunnel.spark.clickhouse.sink.Clickhouse$$anonfun$output$1$$anonfun$1.apply(Clickhouse.scala:82)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.seatunnel.spark.clickhouse.sink.Clickhouse$$anonfun$output$1.apply(Clickhouse.scala:82)
	at org.apache.seatunnel.spark.clickhouse.sink.Clickhouse$$anonfun$output$1.apply(Clickhouse.scala:80)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:935)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:935)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:402)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:408)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Flink or Spark Version

spark local

### Java or Scala Version

openjdk8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
closed by #1809
