### ISSUE TITLE
[Bug] [Flink-clikhouse] Clickhouse Sink runs on Flink

### ISSUE THREAD

**Issue by coolcut2012** [apache/seatunnel#1845]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Hi, I would like to configure a Clickhouse Sink to run on Flink. Could you please provide me with a correct configuration? Thank you very much
![image](https://user-images.githubusercontent.com/28479931/167762386-3f70549b-2201-4ddd-b3e0-e755027169a4.png)

![image](https://user-images.githubusercontent.com/28479931/167762286-8336d922-3bcd-4bf8-8e95-7e8e1a0f1da2.png)

### SeaTunnel Version

2.1.1

### SeaTunnel Config

```conf
Clickhouse {
    host = "127.0.0.1:8123"
    database = "default"
    table = "atest"
    fields = ["id", "name"]
    username = "default"
    password = "pwd"
}
```

### Running Command

```shell
./bin/start-seatunnel-flink.sh --config ./config/application.conf
```

### Error Exception

```log
Execute SeaTunnel Flink Job: ${FLINK_HOME}/bin/flink run -c org.apache.seatunnel.SeatunnelFlink /data/ssd/apache-seatunnel-incubating-2.1.1/lib/seatunnel-core-flink.jar --config ./config/application.conf

------------------------------------------------------------
 The program finished with the following exception:

org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: Execute Flink task error
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:372)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222)
	at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114)
	at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:812)
	at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:246)
	at org.apache.flink.client.cli.CliFrontend.parseAndRun(CliFrontend.java:1054)
	at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1132)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1754)
	at org.apache.flink.runtime.security.contexts.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:41)
	at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1132)
Caused by: java.lang.RuntimeException: Execute Flink task error
	at org.apache.seatunnel.command.flink.FlinkTaskExecuteCommand.execute(FlinkTaskExecuteCommand.java:63)
	at org.apache.seatunnel.command.flink.FlinkTaskExecuteCommand.execute(FlinkTaskExecuteCommand.java:39)
	at org.apache.seatunnel.Seatunnel.run(Seatunnel.java:48)
	at org.apache.seatunnel.SeatunnelFlink.main(SeatunnelFlink.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355)
	... 11 more
Caused by: java.lang.ClassCastException: org.apache.seatunnel.flink.clickhouse.sink.ClickhouseBatchSink cannot be cast to org.apache.seatunnel.flink.stream.FlinkStreamSink
	at org.apache.seatunnel.flink.stream.FlinkStreamExecution.start(FlinkStreamExecution.java:69)
	at org.apache.seatunnel.command.flink.FlinkTaskExecuteCommand.execute(FlinkTaskExecuteCommand.java:60)
	... 19 more
```

### Flink or Spark Version

flink 1.13.1

### Java or Scala Version

jdk8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Do you use a stream source? I guess you use a stream source with the batch sink, in fact, Clickhouse plugin just support batch mode, If you are interested in this, welcome to support the stream mode, this will not be a difficult job if we use the micro batch in stream mode.

**Comment by coolcut2012** [comment]
Yes, you are right. I am testing real-time consumption data from Kafka and storing it into ClickHouse. But I can't find batch source for Kafka. Do you have any suggestions? Thank you very much.
this my configuration:
env {
  # You can set flink configuration here
  execution.parallelism = 1
  job.name = "atest"
}

source {
 KafkaTableStream {
    consumer.bootstrap.servers = "127.0.0.1:9092"
    consumer.group.id = "atest"
    topics = atest
    format.type = json
    schema = "{\"id\":1,\"name\":\"atest\"}"
    format.allow-comments = "true"
    format.ignore-parse-errors = "true"
    result_table_name = atest_table
 }
}

transform {
}

sink {
  Clickhouse {
    host = "127.0.0.1:8123"
    database = "default"
    table = "atest"
    fields = ["id", "name"]
    username = "default"
    password = "pwd"
 }
}

**Comment by ruanwenjun** [comment]
@coolcut2012 I will submit a PR to support clickhouse stream plugin, but it will take some time. And it's also needed to check the plugin type before execute, we need to provide the imformation to tell user the plugin is not matched with the execute mode.

**Comment by coolcut2012** [comment]
Ok, thank you for your reply
