### ISSUE TITLE
[Bug] [examples] java.lang.ClassNotFoundException: Plugin class not found by name :[KafkaTableStream]

### ISSUE THREAD

**Issue by kim-up** [apache/seatunnel#1898]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

java.lang.ClassNotFoundException: Plugin class not found by name :[KafkaTableStream]
while I run on local env.

### SeaTunnel Version

branch of dev

### SeaTunnel Config

```conf
env {
  # You can set flink configuration here
  execution.parallelism = 1
  #execution.checkpoint.interval = 10000
  #execution.checkpoint.data-uri = "hdfs://localhost:9000/checkpoint"
}

source {
  # This is a example source plugin **only for test and demonstrate the feature source plugin**
    KafkaTableStream {
      result_table_name = "fake"
      .....// other configs
    }
}

transform {
    sql {
      sql = "select name,age from fake"
    }
}

sink {
  ConsoleSink {}
}
```

### Running Command

```shell
org.apache.seatunnel.example.flink.LocalFlinkExample.main()
```

### Error Exception

```log
Exception in thread "main" java.lang.RuntimeException: java.lang.ClassNotFoundException: Plugin class not found by name :[KafkaTableStream]
	at org.apache.seatunnel.core.base.config.PluginFactory.lambda$createPlugins$5(PluginFactory.java:191)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.apache.seatunnel.core.base.config.PluginFactory.createPlugins(PluginFactory.java:185)
	at org.apache.seatunnel.core.base.config.ExecutionContext.<init>(ExecutionContext.java:53)
	at org.apache.seatunnel.core.flink.command.FlinkTaskExecuteCommand.execute(FlinkTaskExecuteCommand.java:67)
	at org.apache.seatunnel.core.base.Seatunnel.run(Seatunnel.java:39)
	at org.apache.seatunnel.example.flink.LocalFlinkExample.main(LocalFlinkExample.java:40)
Caused by: java.lang.ClassNotFoundException: Plugin class not found by name :[KafkaTableStream]
	at org.apache.seatunnel.core.base.config.PluginFactory.createPluginInstanceIgnoreCase(PluginFactory.java:227)
	at org.apache.seatunnel.core.base.config.PluginFactory.lambda$createPlugins$5(PluginFactory.java:187)
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kim-up** [comment]
It needs to  add the `kafka-connector`  dependency to the `seatunnel-examples` module 

```
<dependency>
            <groupId>org.apache.seatunnel</groupId>
            <artifactId>seatunnel-connector-flink-kafka</artifactId>
            <version>${project.version}</version>
        </dependency>
```

**Comment by tangguol** [comment]
good
