### ISSUE TITLE
[Feature]Use hive-sink to save table as ORCFileFormat

### ISSUE THREAD

**Issue by dik111** [apache/seatunnel#1929]
seatunnel version :2.1.0
spark version : 2.4.4

Hi Teams:
 For some reason, I need to use hive-sink(spark) to save hive table as ORCFileFormat , is there any configuration item to achieve this requirement?

**Comment by Hisoka-X** [comment]
Have you try create hive table use orc format? then just use seatunnel load data into hive table.

**Comment by dik111** [comment]
> Have you try create hive table use orc format? then just use seatunnel load data into hive table.

I had tried this, but it doesn't work.
Here is my hive ORCformat table create command:
```sql
CREATE TABLE test.user_info ( 
 id BIGINT ,
 name VARCHAR(255) ,
 sex VARCHAR(255) ,
 update_time STRING ,
 create_time STRING ,
 update_time244 STRING ,
 day1234 STRING ,
 ts STRING)  
  ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' STORED AS orcfile
```
And here is my seatunnel(v2.1.0) conf file:
```
env {
	    spark.streaming.batchDuration = 5
	    spark.app.name = "seatunnel-app-mysql_hive_test.user_info"
	    spark.sql.catalogImplementation = "hive"
	    
	
	}
	source {
	    jdbc {
	        driver = "com.mysql.jdbc.Driver"
	        url = "jdbc:mysql://xxx:3306/test?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true"
	        table = "  (select id AS id , name AS name , sex AS sex , update_time AS update_time , create_time AS create_time , update_time244 AS update_time244 , day1234 AS day1234 , ts AS ts from test.user_info ) tmp"
	        result_table_name = "source_table"
	        user = "bigdata"
	        password = "***"
	            }
	}
	sink {
	    Hive {
	        source_table_name = "source_table"
	        result_table_name = "test.user_info"
	        save_mode = "append"
	    }
	}
	transform{}
```
It thorws error:
```
22157 [Driver] ERROR org.apache.spark.deploy.yarn.ApplicationMaster  - User class threw exception: org.apache.spark.sql.AnalysisException: The format of the existing table test.user_info is `HiveFileFormat`. It doesn't match the specified format `ParquetFileFormat`.;
org.apache.spark.sql.AnalysisException: The format of the existing table test.user_info is `HiveFileFormat`. It doesn't match the specified format `ParquetFileFormat`.;
	at org.apache.spark.sql.execution.datasources.PreprocessTableCreation$$anonfun$apply$2.applyOrElse(rules.scala:117)
	at org.apache.spark.sql.execution.datasources.PreprocessTableCreation$$anonfun$apply$2.applyOrElse(rules.scala:76)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$$anonfun$resolveOperatorsDown$1$$anonfun$2.apply(AnalysisHelper.scala:108)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$$anonfun$resolveOperatorsDown$1$$anonfun$2.apply(AnalysisHelper.scala:108)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:70)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$$anonfun$resolveOperatorsDown$1.apply(AnalysisHelper.scala:107)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$$anonfun$resolveOperatorsDown$1.apply(AnalysisHelper.scala:106)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:194)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$class.resolveOperatorsDown(AnalysisHelper.scala:106)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsDown(LogicalPlan.scala:29)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$class.resolveOperators(AnalysisHelper.scala:73)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperators(LogicalPlan.scala:29)
	at org.apache.spark.sql.execution.datasources.PreprocessTableCreation.apply(rules.scala:76)
	at org.apache.spark.sql.execution.datasources.PreprocessTableCreation.apply(rules.scala:72)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1$$anonfun$apply$1.apply(RuleExecutor.scala:87)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1$$anonfun$apply$1.apply(RuleExecutor.scala:84)
	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:57)
	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:66)
	at scala.collection.mutable.ArrayBuffer.foldLeft(ArrayBuffer.scala:48)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1.apply(RuleExecutor.scala:84)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1.apply(RuleExecutor.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:76)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.org$apache$spark$sql$catalyst$analysis$Analyzer$$executeSameContext(Analyzer.scala:127)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:121)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$$anonfun$executeAndCheck$1.apply(Analyzer.scala:106)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$$anonfun$executeAndCheck$1.apply(Analyzer.scala:105)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:201)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:105)
	at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:57)
	at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:55)
	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:47)
	at org.apache.spark.sql.execution.QueryExecution.withCachedData$lzycompute(QueryExecution.scala:61)
	at org.apache.spark.sql.execution.QueryExecution.withCachedData(QueryExecution.scala:60)
	at org.apache.spark.sql.execution.QueryExecution.optimizedPlan$lzycompute(QueryExecution.scala:66)
	at org.apache.spark.sql.execution.QueryExecution.optimizedPlan(QueryExecution.scala:66)
	at org.apache.spark.sql.execution.QueryExecution.sparkPlan$lzycompute(QueryExecution.scala:72)
	at org.apache.spark.sql.execution.QueryExecution.sparkPlan(QueryExecution.scala:68)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:77)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:77)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:76)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:676)
	at org.apache.spark.sql.DataFrameWriter.createTable(DataFrameWriter.scala:474)
	at org.apache.spark.sql.DataFrameWriter.saveAsTable(DataFrameWriter.scala:453)
	at org.apache.spark.sql.DataFrameWriter.saveAsTable(DataFrameWriter.scala:409)
	at org.apache.seatunnel.spark.sink.Hive.output(Hive.scala:62)
	at org.apache.seatunnel.spark.sink.Hive.output(Hive.scala:29)
	at org.apache.seatunnel.spark.batch.SparkBatchExecution.sinkProcess(SparkBatchExecution.java:90)
	at org.apache.seatunnel.spark.batch.SparkBatchExecution.start(SparkBatchExecution.java:105)
	at org.apache.seatunnel.Seatunnel.entryPoint(Seatunnel.java:107)
	at org.apache.seatunnel.Seatunnel.run(Seatunnel.java:65)
	at org.apache.seatunnel.SeatunnelSpark.main(SeatunnelSpark.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:684)
```

**Comment by Hisoka-X** [comment]
I check the code, seem like we should add option to support `ORC` in hive sink. Do you want to contribute this?

**Comment by dik111** [comment]
I had tried to change the source code about spark hive sink, but it doesn't work
``` scala
# Hive.scala
...
val frameWriter: DataFrameWriter[Row] = if (config.hasPath("save_mode")) {
        sinkFrame.write.format("orc").mode(config.getString("save_mode"))
      } else {
        sinkFrame.format("orc").write
      }
...
```
And then I found use hive sql can help me solve this problem - -!
```
env {
	    spark.streaming.batchDuration = 5
	    spark.app.name = "seatunnel-app-mysql_hive_test.user_info"
	    spark.sql.catalogImplementation = "hive"
	    
	
	}
	source {
	    jdbc {
	        driver = "com.mysql.jdbc.Driver"
	        url = "jdbc:mysql://xxx:3306/test?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true"
	        table = "  (select id AS id , name AS name , sex AS sex , update_time AS update_time , create_time AS create_time , update_time244 AS update_time244 , day1234 AS day1234 , ts AS ts from test.user_info ) tmp"
	        result_table_name = "source_table"
	        user = "bigdata"
	        password = "***"
	            }
	}
	sink {
	    Hive {
	        sql = "insert into test.user_info select * from source_table"
	    }
	}
	transform{}
```

**Comment by Hisoka-X** [comment]
I checked the source code about spark.
<img width="747" alt="image" src="https://user-images.githubusercontent.com/32387433/170402755-a9e9cc44-c59e-4d6b-9581-c070bed69607.png">
The orc is supported. Would you please provide your error log?

**Comment by dik111** [comment]
My fault, I got the path of seatunnel wrong.
I found that both the configuration items `.format("Hive")` and  the configuration items `.format("orc")` can solve this problem, but `.format("orc")` may require additional user Configuration, `.format("Hive")` can be written directly into the code, which way do you think is better?
https://blog.csdn.net/lvwenyuan_1/article/details/90697049

**Comment by Hisoka-X** [comment]
> I found that both the configuration items `.format("Hive")` and the configuration items `.format("orc")` can solve this problem, but `.format("orc")` may require additional user Configuration, `.format("Hive")` can be written directly into the code, which way do you think is better?

I prefer first one, just use `.format("Hive")` because this is hive sink connector.
