### ISSUE TITLE
[Bug] [Module Name] The write data to doris succeed but the flink job error :"TwoPhaseCommit": "false"

### ISSUE THREAD

**Issue by wl3207601** [apache/seatunnel#2006]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

source is mysql .sink is doris. write data to doris succeed but the flink job error :"TwoPhaseCommit": "false"

### SeaTunnel Version

2.1.1

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
}
source {
  JdbcSource {
    driver = com.mysql.jdbc.Driver
    url = "jdbc:mysql://localhost:3306/test"
    username = test
    query = "select * from authors"
}
}
transform {
}
sink {
  DorisSink {
      fenodes = "XX.XX.XX.XX:8030"
      database = test
      table = authors
      user = test
      password = pass
      batch_size = 5
      max_retries = 1
      interval = 5000
    }
}
```

### Running Command

```shell
./bin/start-seatunnel-flink.sh --config ./config/mysqltodoris_test.conf
```

### Error Exception

```log
Caused by: java.lang.RuntimeException: org.apache.flink.shaded.jackson2.com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "TwoPhaseCommit" (class org.apache.seatunnel.flink.doris.sink.RespContent), not marked as ignorable (17 known properties: "CommitAndPublishTimeMs", "ExistingJobStatus", "TxnId", "Message", "Status", "ReadDataTimeMs", "Label", "NumberUnselectedRows", "NumberFilteredRows", "StreamLoadPutTimeMs", "LoadBytes", "NumberLoadedRows", "NumberTotalRows", "LoadTimeMs", "WriteDataTimeMs", "BeginTxnTimeMs", "ErrorURL"])
 at [Source: (String)"{    "TxnId": 19600,    "Label": "flink_sink_20220612_000844_f0c4b4de7a6a4931927379e102daf2cb",    "TwoPhaseCommit": "false",    "Status": "Success",    "Message": "OK",    "NumberTotalRows": 4,    "NumberLoadedRows": 4,    "NumberFilteredRows": 0,    "NumberUnselectedRows": 0,    "LoadBytes": 43,    "LoadTimeMs": 75,    "BeginTxnTimeMs": 1,    "StreamLoadPutTimeMs": 1,    "ReadDataTimeMs": 0,    "WriteDataTimeMs": 38,    "CommitAndPublishTimeMs": 33}"; line: 1, column: 119] (through reference chain: org.apache.seatunnel.flink.doris.sink.RespContent["TwoPhaseCommit"])
	at org.apache.seatunnel.flink.doris.sink.DorisStreamLoad.load(DorisStreamLoad.java:99)
	at org.apache.seatunnel.flink.doris.sink.DorisOutputFormat.flush(DorisOutputFormat.java:214)
	... 5 more
```

### Flink or Spark Version

flink:1.13.6

### Java or Scala Version

java:1.8
scala:2.12

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hk-lrzy** [comment]
which doris version does you uesed?

**Comment by wl3207601** [comment]
doris1.0

**Comment by wl3207601** [comment]
> which doris version does you uesed?

doris1.0

**Comment by Zhouwen-CN** [comment]
There is a problem with the version of Doris. It sends data through a request. The response has some additional attributes, resulting in JSON parsing failure

**Comment by Zhouwen-CN** [comment]
I just tried, but no error was reported. Here is my configuration file

env {
  execution.parallelism = 1
}
source {
  JdbcSource {
      driver = "com.mysql.jdbc.Driver"
      url = "jdbc:mysql://localhost/test"
      username = "root"
      password = "root"
      result_table_name = "student_source"

  }
}
transform {
}
sink {
  DorisSink {
    source_table_name = "student_source"
    fenodes = "singlenode:8030"
    database = "chen_test"
    table = "student_result"
    user = "root"
    batch_size = 5
    doris.column_separator="\t"
    doris.columns="id,name,age"
  }
}

**Comment by wl3207601** [comment]
> env {
#2054 
thanks, the doris1.0+ version have this problem
