### ISSUE TITLE
[Bug] [seatunnel-core-flink] Exception on running start-seatunnel-flink.sh with APPLICATION_RUN option

### ISSUE THREAD

**Issue by mans2singh** [apache/seatunnel#2007]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

If I run the following command (start-seatunnel-flink.sh):

`bash-3.2$ apache-seatunnel-incubating-2.1.1-SNAPSHOT/bin/start-seatunnel-flink.sh`

I get the following usage message:

Usage: start-seatunnel-flink.sh [options]
  Options:
    -t, --check    check config (default: false)
 \* -c, --config   Config file
    -h, --help     Show the usage message
    -r, --run-mode job run mode, run or run-application (default: RUN) 
                   (values: [RUN, **APPLICATION_RUN**])
    -i, --variable variable substitution, such as -i city=beijing, or -i 
                   date=20190318 (default: [])

The `-r` mode shows two options `RUN` and `APPLICATION_RUN`.  

If I use `APPLICATION_RUN` option it throws an exception as shown below:

`bash-3.2$ apache-seatunnel-incubating-2.1.1-SNAPSHOT/bin/start-seatunnel-flink.sh -c apache-seatunnel-incubating-2.1.1-SNAPSHOT/config/flink.batch.conf.template -r APPLICATION_RUN

Exception in thread "main" java.lang.IllegalArgumentException: Run mode APPLICATION_RUN not supported
	at org.apache.seatunnel.core.flink.args.FlinkCommandArgs$RunModeConverter.convert(FlinkCommandArgs.java:85)
	at org.apache.seatunnel.core.flink.args.FlinkCommandArgs$RunModeConverter.convert(FlinkCommandArgs.java:71)
	at com.beust.jcommander.JCommander.convertValue(JCommander.java:1333)
	at com.beust.jcommander.ParameterDescription.addValue(ParameterDescription.java:249)
	at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:913)
	at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:894)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:724)
	at com.beust.jcommander.JCommander.parse(JCommander.java:356)
	at com.beust.jcommander.JCommander.parse(JCommander.java:335)
	at com.beust.jcommander.JCommander$Builder.build(JCommander.java:1191)
	at org.apache.seatunnel.core.flink.utils.CommandLineUtils.parseCommandArgs(CommandLineUtils.java:44)
	at org.apache.seatunnel.core.flink.FlinkEnvParameterParser.main(FlinkEnvParameterParser.java:40)`

### SeaTunnel Version

2.1.1-SNAPSHOT

### SeaTunnel Config

```conf
Using flink.batch.conf.template provided with the seatunnel configs.
```

### Running Command

```shell
apache-seatunnel-incubating-2.1.1-SNAPSHOT/bin/start-seatunnel-flink.sh -c apache-seatunnel-incubating-2.1.1-SNAPSHOT/config/flink.batch.conf.template -r APPLICATION_RUN
```

### Error Exception

```log
Exception in thread "main" java.lang.IllegalArgumentException: Run mode APPLICATION_RUN not supported
	at org.apache.seatunnel.core.flink.args.FlinkCommandArgs$RunModeConverter.convert(FlinkCommandArgs.java:85)
	at org.apache.seatunnel.core.flink.args.FlinkCommandArgs$RunModeConverter.convert(FlinkCommandArgs.java:71)
	at com.beust.jcommander.JCommander.convertValue(JCommander.java:1333)
	at com.beust.jcommander.ParameterDescription.addValue(ParameterDescription.java:249)
	at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:913)
	at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:894)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:724)
	at com.beust.jcommander.JCommander.parse(JCommander.java:356)
	at com.beust.jcommander.JCommander.parse(JCommander.java:335)
	at com.beust.jcommander.JCommander$Builder.build(JCommander.java:1191)
	at org.apache.seatunnel.core.flink.utils.CommandLineUtils.parseCommandArgs(CommandLineUtils.java:44)
	at org.apache.seatunnel.core.flink.FlinkEnvParameterParser.main(FlinkEnvParameterParser.java:40)
```

### Flink or Spark Version

Flink 1.13.6

### Java or Scala Version

Java 1.8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mans2singh** [comment]
Please assign this issue to me.  Thanks

**Comment by Hisoka-X** [comment]
Close by #2008
