### ISSUE TITLE
[Bug] [examples] spark-examples runs throwing exception 

### ISSUE THREAD

**Issue by waitingF** [apache/seatunnel#2011]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I cloned the repo and checkout to dev branch. then i build the code with command './mvnw install -Dmaven.test.skip' which returns ok.
Then I run the LocalSparkExample from IDEA, which return error.
the error log:
22/06/13 21:40:58 ERROR Seatunnel: Fatal Error, 
22/06/13 21:40:58 ERROR Seatunnel: Please submit bug report in https://github.com/apache/incubator-seatunnel/issues
22/06/13 21:40:58 ERROR Seatunnel: Reason:A master URL must be set in your configuration 
22/06/13 21:40:58 ERROR Seatunnel: Exception StackTrace:org.apache.spark.SparkException: A master URL must be set in your configuration
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:368)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2520)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:935)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:926)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:926)
	at org.apache.seatunnel.spark.SparkEnvironment.prepare(SparkEnvironment.java:106)
	at org.apache.seatunnel.spark.SparkEnvironment.prepare(SparkEnvironment.java:43)
	at org.apache.seatunnel.core.base.config.EnvironmentFactory.getEnvironment(EnvironmentFactory.java:61)
	at org.apache.seatunnel.core.base.config.ExecutionContext.<init>(ExecutionContext.java:49)
	at org.apache.seatunnel.core.spark.command.SparkTaskExecuteCommand.execute(SparkTaskExecuteCommand.java:62)
	at org.apache.seatunnel.core.base.Seatunnel.run(Seatunnel.java:39)
	at org.apache.seatunnel.example.spark.LocalSparkExample.main(LocalSparkExample.java:42)

is there any configuration I need to config to run the example? please help me

### SeaTunnel Version

version is : 2.1.1-SNAPSHOT
lastest git log is:
9ffa678c80053655499dbb2147a273a8708430bb

### SeaTunnel Config

```conf
none
```

### Running Command

```shell
run from IDEA
```

### Error Exception

```log
22/06/13 21:40:58 ERROR Seatunnel: Fatal Error, 
22/06/13 21:40:58 ERROR Seatunnel: Please submit bug report in https://github.com/apache/incubator-seatunnel/issues
22/06/13 21:40:58 ERROR Seatunnel: Reason:A master URL must be set in your configuration 
22/06/13 21:40:58 ERROR Seatunnel: Exception StackTrace:org.apache.spark.SparkException: A master URL must be set in your configuration
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:368)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2520)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:935)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:926)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:926)
	at org.apache.seatunnel.spark.SparkEnvironment.prepare(SparkEnvironment.java:106)
	at org.apache.seatunnel.spark.SparkEnvironment.prepare(SparkEnvironment.java:43)
	at org.apache.seatunnel.core.base.config.EnvironmentFactory.getEnvironment(EnvironmentFactory.java:61)
	at org.apache.seatunnel.core.base.config.ExecutionContext.<init>(ExecutionContext.java:49)
	at org.apache.seatunnel.core.spark.command.SparkTaskExecuteCommand.execute(SparkTaskExecuteCommand.java:62)
	at org.apache.seatunnel.core.base.Seatunnel.run(Seatunnel.java:39)
	at org.apache.seatunnel.example.spark.LocalSparkExample.main(LocalSparkExample.java:42)
```

### Java or Scala Version

openjdk version "1.8.0_332"
OpenJDK Runtime Environment (Zulu 8.62.0.19-CA-macos-aarch64) (build 1.8.0_332-b09)
OpenJDK 64-Bit Server VM (Zulu 8.62.0.19-CA-macos-aarch64) (build 25.332-b09, mixed mode)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wanghuan2054** [comment]
Please refer to the following links， have a try . https://blog.csdn.net/shenlanzifa/article/details/42679577

**Comment by waitingF** [comment]
thanks for reply, it works
