### ISSUE TITLE
Flink on Yarn Cluster 模式提交SeaTunnel Example程序失败异常

### ISSUE THREAD

**Issue by berg-xu** [apache/seatunnel#2061]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

我尝试基于Flink on Yarn Cluster 模式提交SeaTunnel Example程序。 执行命令参照官网所示：
![image](https://user-images.githubusercontent.com/45385723/175768634-637e6df8-fe34-4732-a01c-9f7311f518e8.png)

我在此基础上稍微做了点改动， 具体实际执行命令如下：
cd $SEATUNNEL_HOME
bin/start-seatunnel-flink.sh -m yarn-cluster -ynm seatunnel-1  -yqu root.smart-batch --config ./config/flink.streaming.conf.template

执行过程中， 输出异常日志信息如下：

![image](https://user-images.githubusercontent.com/45385723/175768792-5c9eeeef-ce47-4b30-aff0-dff4ba9207ce.png)

然后通过tail查看当前命令所执行的机器节点上$FLINK_HOME/log目录下日志， 获取的的错误日志信息如下(其实与上述日志信息差不多)：
![image](https://user-images.githubusercontent.com/45385723/175768837-d79a32e4-6e70-4eec-98ce-c993ed8c0a76.png)

最后查看对应的Yarn上的日志信息， 获取到的异常信息如下：
![image](https://user-images.githubusercontent.com/45385723/175768892-08340634-e53c-47d7-879a-4d65cc2fe49c.png)

从yarn的日志可以看到， 我能够猜测到的结论是scala版本冲突引起的， 但是我不确定我定位的问题是否准确， 我尝试了多种解决办法， 但是很可惜都是无效的。
 
请问该如何入手解决这个问题？ 该从什么方向角度来处理？

另外 各个组件的版本如下：
seatunnel===> V2.1.2
flink ===> V1.13.6
scala ===> V2.12.12
java ===> 8 

### SeaTunnel Version

seatunnel===> V2.1.2

### SeaTunnel Config

```conf
$SEATUNNEL_HOME/config/flink.streaming.conf.template
```

### Running Command

```shell
cd $SEATUNNEL_HOME
bin/start-seatunnel-flink.sh -m yarn-cluster -ynm seatunnel-1  -yqu root.smart-batch --config ./config/flink.streaming.conf.template
```

### Error Exception

```log
2022-06-25 18:01:29,466 INFO  org.apache.flink.yarn.YarnClusterDescriptor                  [] - No path for the flink jar passed. Using the location of class org.apache.flink.yarn.YarnClusterDescriptor to locate the jar
2022-06-25 18:01:29,643 INFO  org.apache.hadoop.conf.Configuration                         [] - resource-types.xml not found
2022-06-25 18:01:29,645 INFO  org.apache.hadoop.yarn.util.resource.ResourceUtils           [] - Unable to find 'resource-types.xml'.
2022-06-25 18:01:29,717 INFO  org.apache.flink.yarn.YarnClusterDescriptor                  [] - The configured JobManager memory is 1600 MB. YARN will allocate 2048 MB to make up an integer multiple of its minimum allocation memory (1024 MB, configured via 'yarn.scheduler.minimum-allocation-mb'). The extra 448 MB may not be used by Flink.
2022-06-25 18:01:29,718 INFO  org.apache.flink.yarn.YarnClusterDescriptor                  [] - The configured TaskManager memory is 1728 MB. YARN will allocate 2048 MB to make up an integer multiple of its minimum allocation memory (1024 MB, configured via 'yarn.scheduler.minimum-allocation-mb'). The extra 320 MB may not be used by Flink.
2022-06-25 18:01:29,718 INFO  org.apache.flink.yarn.YarnClusterDescriptor                  [] - Cluster specification: ClusterSpecification{masterMemoryMB=1600, taskManagerMemoryMB=1728, slotsPerTaskManager=1}
2022-06-25 18:01:30,325 WARN  org.apache.hadoop.hdfs.shortcircuit.DomainSocketFactory      [] - The short-circuit local reads feature cannot be used because libhadoop cannot be loaded.
2022-06-25 18:01:33,347 INFO  org.apache.flink.yarn.YarnClusterDescriptor                  [] - Submitting application master application_1656142708198_0146
2022-06-25 18:01:33,401 INFO  org.apache.hadoop.yarn.client.api.impl.YarnClientImpl        [] - Submitted application application_1656142708198_0146
2022-06-25 18:01:33,402 INFO  org.apache.flink.yarn.YarnClusterDescriptor                  [] - Waiting for the cluster to be allocated
2022-06-25 18:01:33,404 INFO  org.apache.flink.yarn.YarnClusterDescriptor                  [] - Deploying cluster, current state ACCEPTED

------------------------------------------------------------
 The program finished with the following exception:

org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: Execute Flink task error
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:372)
        at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222)
        at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114)
        at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:812)
        at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:246)
        at org.apache.flink.client.cli.CliFrontend.parseAndRun(CliFrontend.java:1054)
        at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1132)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1762)
        at org.apache.flink.runtime.security.contexts.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:41)
        at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1132)
Caused by: java.lang.RuntimeException: Execute Flink task error
        at org.apache.seatunnel.core.flink.command.FlinkTaskExecuteCommand.execute(FlinkTaskExecuteCommand.java:84)
        at org.apache.seatunnel.core.base.Seatunnel.run(Seatunnel.java:39)
        at org.apache.seatunnel.core.flink.SeatunnelFlink.main(SeatunnelFlink.java:33)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355)
        ... 11 more
Caused by: org.apache.flink.client.deployment.ClusterDeploymentException: Could not deploy Yarn job cluster.
        at org.apache.flink.yarn.YarnClusterDescriptor.deployJobCluster(YarnClusterDescriptor.java:481)
        at org.apache.flink.client.deployment.executors.AbstractJobClusterExecutor.execute(AbstractJobClusterExecutor.java:81)
        at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.executeAsync(StreamExecutionEnvironment.java:1956)
        at org.apache.flink.client.program.StreamContextEnvironment.executeAsync(StreamContextEnvironment.java:137)
        at org.apache.flink.client.program.StreamContextEnvironment.execute(StreamContextEnvironment.java:76)
        at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.execute(StreamExecutionEnvironment.java:1833)
        at org.apache.seatunnel.flink.stream.FlinkStreamExecution.start(FlinkStreamExecution.java:75)
        at org.apache.seatunnel.core.flink.command.FlinkTaskExecuteCommand.execute(FlinkTaskExecuteCommand.java:81)
        ... 18 more
Caused by: org.apache.flink.yarn.YarnClusterDescriptor$YarnDeploymentException: The YARN application unexpectedly switched to state FAILED during deployment.
Diagnostics from YARN: Application application_1656142708198_0146 failed 4 times in previous 10000 milliseconds due to AM Container for appattempt_1656142708198_0146_000004 exited with  exitCode: 1
Failing this attempt.Diagnostics: [2022-06-25 18:01:47.135]Exception from container-launch.
Container id: container_e20_1656142708198_0146_04_000001
Exit code: 1

[2022-06-25 18:01:47.137]Container exited with a non-zero exit code 1. Error file: prelaunch.err.
Last 4096 bytes of prelaunch.err :

[2022-06-25 18:01:47.139]Container exited with a non-zero exit code 1. Error file: prelaunch.err.
Last 4096 bytes of prelaunch.err :
```

### Flink or Spark Version

flink  version 1.13.6

### Java or Scala Version

java 8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
For better communication, we only accept English communication, please use English resubmit inssue.

**Comment by SinyoWong** [comment]
同样的问题，请问解决了么？
