### ISSUE TITLE
[Bug] [seatunnel-connectors] kafka source  ClassCastException: com.fasterxml.jackson.databind.node.ObjectNode cannot be cast to com.fasterxml.jackson.databind.node.ArrayNode

### ISSUE THREAD

**Issue by hanwei996** [apache/seatunnel#2355]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Kafka source format.type, multiple schema not matched, resulting in error: com.fasterxml.jackson.databind.node.ObjectNode cannot be cast to com.fasterxml.jackson.databind.node.ArrayNode

### SeaTunnel Version

2.1.2

### SeaTunnel Config

```conf
config/example02.conf

env {
    execution.parallelism = 1
}
source {
     KafkaTableStream {
         consumer.bootstrap.servers = "hadoop02:9092"
         consumer.group.id = "seatunnel5"
         topics = test_video
         result_table_name = test
         format.type = json
         schema = "{\"session_id\":\"string\",\"video_count\":\"int\",\"duration_time\":\"long\",\"user_id\":\"string\",\"user_age\":\"int\",\"city\":\"string\",\"session_start_time\":\"datetime\",\"session_end_time\":\"datetime\"}"
         format.ignore-parse-errors = "true"
    }
}
transform{
    sql {
        sql = "select user_id,city,user_age as age,video_count as video_sum,duration_time as max_duration_time,duration_time as min_duration_time,session_end_time as last_session_date from test"
        result_table_name = test2
    }
}
sink{
    DorisSink {
         source_table_name = test2
         fenodes = "hadoop02:8030"
         database = test_db
         table = example_user_video
         user = root
         password = anonymous123
         batch_size = 50
         doris.column_separator="\t"
         doris.columns="user_id,city,age,video_sum,max_duration_time,min_duration_time,last_session_date"
    }
}
```

### Running Command

```shell
bin/start-seatunnel-flink.sh --config config/example02.conf
```

### Error Exception

```log
Caused by: java.lang.RuntimeException: Json deserialization exception.
        at org.apache.seatunnel.common.utils.JsonUtils.parseArray(JsonUtils.java:255)
        at org.apache.seatunnel.flink.kafka.source.KafkaTableStream.prepare(KafkaTableStream.java:114)
        at org.apache.seatunnel.flink.kafka.source.KafkaTableStream.prepare(KafkaTableStream.java:51)
        at org.apache.seatunnel.core.base.command.BaseTaskExecuteCommand.lambda$prepare$0(BaseTaskExecuteCommand.java:66)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.apache.seatunnel.core.base.command.BaseTaskExecuteCommand.prepare(BaseTaskExecuteCommand.java:66)
        at org.apache.seatunnel.core.flink.command.FlinkApiTaskExecuteCommand.execute(FlinkApiTaskExecuteCommand.java:81)
        ... 18 more
Caused by: java.lang.ClassCastException: com.fasterxml.jackson.databind.node.ObjectNode cannot be cast to com.fasterxml.jackson.databind.node.ArrayNode
        at org.apache.seatunnel.common.utils.JsonUtils.parseArray(JsonUtils.java:253)
```

### Flink or Spark Version

flink v1.12.7

### Java or Scala Version

java 1.8
scala 2.12.15

### Screenshots

<img width="1127" alt="error" src="https://user-images.githubusercontent.com/43572770/182565903-e73d3606-db22-4161-a572-fae14888e5dc.png">

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 521daichen** [comment]
i have a same problem

**Comment by hanwei996** [comment]
> i have a same problem

Use the new version to fix the problem
