### ISSUE TITLE
[Bug] [Spark] org.apache.hadoop.hive.shims.HadoopShims.getHadoopConfNames()Ljava/util/Map

### ISSUE THREAD

**Issue by qianmoQ** [apache/seatunnel#2387]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Failed to load Hadoop configuration information

### SeaTunnel Version

2.1.3

### SeaTunnel Config

```conf
env {
  spark.app.name = "Hive2ClickHouse-localhost"
  spark.sql.catalogImplementation = "hive"
  spark.executor.instances = 2
  spark.executor.cores = 1
  spark.executor.memory = "1g"
}

source {
  Hive {
    pre_sql = "select * from default.github_events where ymd = '20220808'"
    result_table_name = "github_events"
  }
}

sink {
  Console{}
}
```

### Running Command

```shell
./bin/start-seatunnel-spark.sh --master local[4] --deploy-mode client --config ./config/spark.batch.clickhouse.conf
```

### Error Exception

```log
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.hadoop.hive.shims.HadoopShims.getHadoopConfNames()Ljava/util/Map;
	at org.apache.hadoop.hive.conf.HiveConf$ConfVars.<clinit>(HiveConf.java:370)
	at org.apache.hadoop.hive.conf.HiveConf.<clinit>(HiveConf.java:108)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.spark.util.Utils$.classForName(Utils.scala:234)
	at org.apache.spark.sql.SparkSession$.hiveClassesArePresent(SparkSession.scala:1111)
	at org.apache.spark.sql.SparkSession$Builder.enableHiveSupport(SparkSession.scala:890)
	at org.apache.seatunnel.spark.SparkEnvironment.prepare(SparkEnvironment.java:104)
	at org.apache.seatunnel.spark.SparkEnvironment.prepare(SparkEnvironment.java:43)
	at org.apache.seatunnel.core.base.config.EnvironmentFactory.getEnvironment(EnvironmentFactory.java:63)
	at org.apache.seatunnel.core.base.config.AbstractExecutionContext.<init>(AbstractExecutionContext.java:53)
	at org.apache.seatunnel.core.spark.config.SparkExecutionContext.<init>(SparkExecutionContext.java:48)
	at org.apache.seatunnel.core.spark.command.SparkTaskExecuteCommand.execute(SparkTaskExecuteCommand.java:53)
	at org.apache.seatunnel.core.base.Seatunnel.run(Seatunnel.java:40)
	at org.apache.seatunnel.core.spark.SeatunnelSpark.main(SeatunnelSpark.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:808)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:190)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:215)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:129)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

### Flink or Spark Version

Spark 2.2.0-cdh6.0.1

### Java or Scala Version

Java 1.8.0_252
Scala version 2.11.8

### Screenshots

![image](https://user-images.githubusercontent.com/20521442/183560044-cadca469-1580-4317-967d-6fa3c9cbd208.png)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
Please use spark 2.4.0 try again

**Comment by qianmoQ** [comment]
> Please use spark 2.4.0 try again

2.4.0, 2.4.5 both fail to run, same error message

**Comment by qianmoQ** [comment]
I have fixed it

**Comment by mohamedabidilcl** [comment]
How did you resolve it please ?
