### ISSUE TITLE
How to local start seatunnel (dev branch)

### ISSUE THREAD

**Issue by rmzf9192** [apache/seatunnel#2475]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

wo get seatunnel source code ,and local start seatunnel (dev branch)

### SeaTunnel Version

dev branche

### SeaTunnel Config

```conf
by idea start
```

### Running Command

```shell
java -jar org.apache.seatunnel.app.SeatunnelApplication
```

### Error Exception

```log
Caused by: java.net.MalformedURLException: no protocol: 127.0.0.1:12345/dolphinscheduler/v2/projects
	at java.base/java.net.URL.<init>(URL.java:645)
	at java.base/java.net.URL.<init>(URL.java:541)
	at java.base/java.net.URL.<init>(URL.java:488)
	at org.jsoup.helper.HttpConnection.url(HttpConnection.java:184)
	... 72 common frames omitted
```

### Flink or Spark Version

1.13

### Java or Scala Version

jdk11

### Screenshots

Caused by: java.net.MalformedURLException: no protocol: 127.0.0.1:12345/dolphinscheduler/v2/projects
	at java.base/java.net.URL.<init>(URL.java:645)
	at java.base/java.net.URL.<init>(URL.java:541)
	at java.base/java.net.URL.<init>(URL.java:488)
	at org.jsoup.helper.HttpConnection.url(HttpConnection.java:184)
	... 72 common frames omitted

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by john8628** [comment]
i have the same question, that needs the default config for dophischedule

**Comment by dijiekstra** [comment]
This url need start with http or https. 😊

**Comment by CalvinKirs** [comment]
> This url need start with http or https. 😊

hi, could you add some user-guide doc for this?

**Comment by dijiekstra** [comment]
> 

Documentation is necessary, and I'll start working on it next month

**Comment by dijiekstra** [comment]
> > 
> 
> Documentation is necessary, and I'll start working on it next month

reply to @CalvinKirs

**Comment by FWLamb** [comment]
Has the seatunne web deployment and use guidance document been prepared? Is there a follow-up development plan?
