### ISSUE TITLE
[Bug] [flink-connector-elasticsearch7] sink failure caused by unsupported deprecated TransportClient on 7.x

### ISSUE THREAD

**Issue by kalencaya** [apache/seatunnel#2539]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

flink-connector-elasticsearch7 work fails

### SeaTunnel Version

dev, 2.1.2, 2.1.3

### SeaTunnel Config

```conf
env {}

source {
    JdbcSource {
      driver = com.mysql.cj.jdbc.Driver
      url = "jdbc:mysql://localhost:3306/data_service"
      username = root
      password = 123456
      query = "select * from sample_data_e_commerce"
      result_table_name = sample_data_e_commerce
    }
}

transform {}

sink {
  Elasticsearch {
    source_table_name = sample_data_e_commerce
    hosts = ["localhost:9200"]
  }
}
```

### Running Command

```shell
unneeded
```

### Error Exception

```log
22/08/26 20:39:54 ERROR ElasticsearchOutputFormat: None of the configured nodes are available: [{#transport#-1}{hVAKLFNeSJm2OOzgoLL92Q}{localhost}{127.0.0.1:9200}]
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{hVAKLFNeSJm2OOzgoLL92Q}{localhost}{127.0.0.1:9200}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:352)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:248)
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:57)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:394)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:396)
	at org.elasticsearch.client.support.AbstractClient.bulk(AbstractClient.java:474)
	at org.elasticsearch.action.bulk.Retry$RetryHandler.execute(Retry.java:205)
	at org.elasticsearch.action.bulk.Retry.withBackoff(Retry.java:59)
	at org.elasticsearch.action.bulk.BulkRequestHandler.execute(BulkRequestHandler.java:62)
	at org.elasticsearch.action.bulk.BulkProcessor.execute(BulkProcessor.java:455)
	at org.elasticsearch.action.bulk.BulkProcessor.internalAdd(BulkProcessor.java:389)
	at org.elasticsearch.action.bulk.BulkProcessor.add(BulkProcessor.java:361)
	at org.elasticsearch.action.bulk.BulkProcessor.add(BulkProcessor.java:347)
	at org.apache.seatunnel.flink.elasticsearch.sink.ElasticsearchOutputFormat$2.add(ElasticsearchOutputFormat.java:116)
	at org.apache.seatunnel.flink.elasticsearch.sink.Elasticsearch.lambda$outputBatch$e5a96c4d$1(Elasticsearch.java:128)
	at org.apache.seatunnel.flink.elasticsearch.sink.ElasticsearchOutputFormat.writeRecord(ElasticsearchOutputFormat.java:134)
	at org.apache.flink.runtime.operators.DataSinkTask.invoke(DataSinkTask.java:240)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:779)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:566)
	at java.lang.Thread.run(Thread.java:748)
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
Can you provide your config and log, thanks.
