### ISSUE TITLE
X [ERROR] [plugin vite:dep-scan] Missing "./es/_mixins" export in "naive-ui" package

### ISSUE THREAD

**Issue by luckymlog** [apache/seatunnel#2564]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

X [ERROR] [plugin vite:dep-scan] Missing "./es/_mixins" export in "naive-ui" package

### SeaTunnel Version

last

### SeaTunnel Config

```conf
lasted
```

### Running Command

```shell
npm run dev
```

### Error Exception

```log
E:\project\seatunnel\incubator-seatunnel\seatunnel-ui>npm run dev

> seatunnel-ui@0.0.0 dev
> vite


  vite v2.9.15 dev server running at:

  > Local: http://localhost:3000/
  > Network: use `--host` to expose

  ready in 4780ms.

X [ERROR] [plugin vite:dep-scan] Missing "./es/_mixins" export in "naive-ui" package

    node_modules/vite/dist/node/chunks/dep-689425f3.js:38597:7:
      38597 │   throw new Error(
            ╵         ^

    at bail (E:\project\seatunnel\incubator-seatunnel\seatunnel-ui\node_modules\vite\dist\node\chunks\dep-689425f3.js:38597:8)
    at resolve (E:\project\seatunnel\incubator-seatunnel\seatunnel-ui\node_modules\vite\dist\node\chunks\dep-689425f3.js:38674:10)
    at resolveExports (E:\project\seatunnel\incubator-seatunnel\seatunnel-ui\node_modules\vite\dist\node\chunks\dep-689425f3.js:40982:12)
    at resolveDeepImport (E:\project\seatunnel\incubator-seatunnel\seatunnel-ui\node_modules\vite\dist\node\chunks\dep-689425f3.js:41000:31)
    at tryNodeResolve (E:\project\seatunnel\incubator-seatunnel\seatunnel-ui\node_modules\vite\dist\node\chunks\dep-689425f3.js:40773:20)
    at Context.resolveId (E:\project\seatunnel\incubator-seatunnel\seatunnel-ui\node_modules\vite\dist\node\chunks\dep-689425f3.js:40581:28)
    at Object.resolveId (E:\project\seatunnel\incubator-seatunnel\seatunnel-ui\node_modules\vite\dist\node\chunks\dep-689425f3.js:39254:55)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async resolve (E:\project\seatunnel\incubator-seatunnel\seatunnel-ui\node_modules\vite\dist\node\chunks\dep-689425f3.js:39466:26)
    at async E:\project\seatunnel\incubator-seatunnel\seatunnel-ui\node_modules\vite\dist\node\chunks\dep-689425f3.js:39626:34

  This error came from the "onResolve" callback registered here:

    node_modules/vite/dist/node/chunks/dep-689425f3.js:39616:18:
      39616 │             build.onResolve({
            ╵                   ~~~~~~~~~

    at setup (E:\project\seatunnel\incubator-seatunnel\seatunnel-ui\node_modules\vite\dist\node\chunks\dep-689425f3.js:39616:19)
    at handlePlugins (E:\project\seatunnel\incubator-seatunnel\seatunnel-ui\node_modules\esbuild\lib\main.js:855:23)
    at Object.buildOrServe (E:\project\seatunnel\incubator-seatunnel\seatunnel-ui\node_modules\esbuild\lib\main.js:1149:7)
    at E:\project\seatunnel\incubator-seatunnel\seatunnel-ui\node_modules\esbuild\lib\main.js:2110:17
    at new Promise (<anonymous>)
    at Object.build (E:\project\seatunnel\incubator-seatunnel\seatunnel-ui\node_modules\esbuild\lib\main.js:2109:14)
    at Object.build (E:\project\seatunnel\incubator-seatunnel\seatunnel-ui\node_modules\esbuild\lib\main.js:1956:51)
    at E:\project\seatunnel\incubator-seatunnel\seatunnel-ui\node_modules\vite\dist\node\chunks\dep-689425f3.js:39414:54
    at Array.map (<anonymous>)

  The plugin "vite:dep-scan" was triggered by this import

    src/components/monaco-editor/index.tsx:26:28:
      26 │ import { useFormItem } from 'naive-ui/es/_mixins'
         ╵                             ~~~~~~~~~~~~~~~~~~~~~

X [ERROR] [plugin vite:dep-scan] Missing "./es/_utils" export in "naive-ui" package

    node_modules/vite/dist/node/chunks/dep-689425f3.js:38597:7:
      38597 │   throw new Error(
            ╵         ^

    at bail (E:\project\seatunnel\incubator-seatunnel\seatunnel-ui\node_modules\vite\dist\node\chunks\dep-689425f3.js:38597:8)
    at resolve (E:\project\seatunnel\incubator-seatunnel\seatunnel-ui\node_modules\vite\dist\node\chunks\dep-689425f3.js:38674:10)
    at resolveExports (E:\project\seatunnel\incubator-seatunnel\seatunnel-ui\node_modules\vite\dist\node\chunks\dep-689425f3.js:40982:12)
    at resolveDeepImport (E:\project\seatunnel\incubator-seatunnel\seatunnel-ui\node_modules\vite\dist\node\chunks\dep-689425f3.js:41000:31)
    at tryNodeResolve (E:\project\seatunnel\incubator-seatunnel\seatunnel-ui\node_modules\vite\dist\node\chunks\dep-689425f3.js:40773:20)
    at Context.resolveId (E:\project\seatunnel\incubator-seatunnel\seatunnel-ui\node_modules\vite\dist\node\chunks\dep-689425f3.js:40581:28)
    at Object.resolveId (E:\project\seatunnel\incubator-seatunnel\seatunnel-ui\node_modules\vite\dist\node\chunks\dep-689425f3.js:39254:55)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async resolve (E:\project\seatunnel\incubator-seatunnel\seatunnel-ui\node_modules\vite\dist\node\chunks\dep-689425f3.js:39466:26)
    at async E:\project\seatunnel\incubator-seatunnel\seatunnel-ui\node_modules\vite\dist\node\chunks\dep-689425f3.js:39626:34

  This error came from the "onResolve" callback registered here:

    node_modules/vite/dist/node/chunks/dep-689425f3.js:39616:18:
      39616 │             build.onResolve({
            ╵                   ~~~~~~~~~

    at setup (E:\project\seatunnel\incubator-seatunnel\seatunnel-ui\node_modules\vite\dist\node\chunks\dep-689425f3.js:39616:19)
    at handlePlugins (E:\project\seatunnel\incubator-seatunnel\seatunnel-ui\node_modules\esbuild\lib\main.js:855:23)
    at Object.buildOrServe (E:\project\seatunnel\incubator-seatunnel\seatunnel-ui\node_modules\esbuild\lib\main.js:1149:7)
    at E:\project\seatunnel\incubator-seatunnel\seatunnel-ui\node_modules\esbuild\lib\main.js:2110:17
    at new Promise (<anonymous>)
    at Object.build (E:\project\seatunnel\incubator-seatunnel\seatunnel-ui\node_modules\esbuild\lib\main.js:2109:14)
    at Object.build (E:\project\seatunnel\incubator-seatunnel\seatunnel-ui\node_modules\esbuild\lib\main.js:1956:51)
    at E:\project\seatunnel\incubator-seatunnel\seatunnel-ui\node_modules\vite\dist\node\chunks\dep-689425f3.js:39414:54
    at Array.map (<anonymous>)

  The plugin "vite:dep-scan" was triggered by this import

    src/components/monaco-editor/index.tsx:27:21:
      27 │ import { call } from 'naive-ui/es/_utils'
         ╵                      ~~~~~~~~~~~~~~~~~~~~

Build failed with 2 errors:
node_modules/vite/dist/node/chunks/dep-689425f3.js:38597:7: ERROR: [plugin: vite:dep-scan] Missing "./es/_mixins" export in "naive-ui" package
node_modules/vite/dist/node/chunks/dep-689425f3.js:38597:7: ERROR: [plugin: vite:dep-scan] Missing "./es/_utils" export in "naive-ui" package
```

### Flink or Spark Version

Flink

### Java or Scala Version

1.8

### Screenshots

#

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
@songjianet Hi,PTAL. Thanks
