### ISSUE TITLE
[Bug] [connector-fake] Invalid date 'February 29' as '2022' is not a leap year

### ISSUE THREAD

**Issue by zhaomin1423** [apache/seatunnel#2572]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Invalid date 'February 29' as '2022' is not a leap year

### SeaTunnel Version

2.1.3-SNAPSHOT

### SeaTunnel Config

```conf
none
```

### Running Command

```shell
run SeaTunnelApiExample
```

### Error Exception

```log
Caused by: java.time.DateTimeException: Invalid date 'February 29' as '2022' is not a leap year
	at java.time.LocalDate.create(LocalDate.java:429)
	at java.time.LocalDate.of(LocalDate.java:269)
	at java.time.LocalDateTime.of(LocalDateTime.java:311)
	at org.apache.seatunnel.connectors.seatunnel.fake.source.FakeRandomData.randomLocalDateTime(FakeRandomData.java:125)
	at org.apache.seatunnel.connectors.seatunnel.fake.source.FakeRandomData.randomColumnValue(FakeRandomData.java:93)
	at org.apache.seatunnel.connectors.seatunnel.fake.source.FakeRandomData.randomRow(FakeRandomData.java:65)
	at org.apache.seatunnel.connectors.seatunnel.fake.source.FakeSourceReader.pollNext(FakeSourceReader.java:57)
	at org.apache.seatunnel.translation.source.ParallelSource.run(ParallelSource.java:125)
	at org.apache.seatunnel.translation.spark.common.source.batch.ParallelBatchPartitionReader.lambda$prepare$0(ParallelBatchPartitionReader.java:97)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 3 more
```

### Screenshots

<img width="1318" alt="image" src="https://user-images.githubusercontent.com/49054376/187504322-4efd9d20-1a0c-4f19-8b63-e8920c267915.png">

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
closed by #2573
