### ISSUE TITLE
[Bug] [Spark-Kafka-Console] Spark Streaming failure caused by no data in batch time

### ISSUE THREAD

**Issue by miaoze8** [apache/seatunnel#2576]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

If spark streaming does not get new data within the batch time, it will continue to perform data analysis, resulting in an error.

Reproduction steps:
1. Create an empty topic
2. Use spark streaming to read topic, convert JSON and output it to console
3. Start the task, and an error will be triggered after waiting for a batch to be executed

### SeaTunnel Version

2.1.3

### SeaTunnel Config

```conf
env {
  spark.app.name = "SeaTunnel-Kafka-test"
  spark.dynamicAllocation.enabled = false
  spark.executor.instances = 4
  spark.executor.cores = 1
  spark.executor.memory = "4g"
  spark.stream.batchDuration = 10
  spark.streaming.backpressure.enabled = "true"
  spark.streaming.kafka.maxRatePerPartition = 100000  
  spark.streaming.queue = "realtime"
  # spark.streaming.stopGracefullyOnShutdown = "true"
  
  # Kerberos配置
  spark.yarn.keytab = /home/test/test.keytab
  spark.yarn.principal = test
}

source {
    kafkaStream {
      topics = "test002"
      consumer.bootstrap.servers = "test:9092"
      consumer.group.id = "test02"
      consumer.auto.offset.reset = "earliest"
    }
}

transform {
  json {
    source_field = "raw_message"
    result_table_name = "test002"
  }

  sql {
        # sql里可直接引用前面定义的各个临时表
        sql = "SELECT province_code,member_code,member_phone,creation_date,last_update_date FROM test002"
    }

}

sink {

     console {
       limit = 10
       # serializer = "json"
     }
}
```

### Running Command

```shell
nohup /opt/seatunnel/apache-seatunnel-incubating-2.1.3_spark/bin/start-seatunnel-spark.sh --master yarn --deploy-mode client --config /opt/seatunnel/apache-seatunnel-incubating-2.1.3_spark/config-test/test.conf > /opt/seatunnel/apache-seatunnel-incubating-2.1.3_spark/logs-test/test.log 2>&1 &
```

### Error Exception

```log
22/08/31 10:30:06 INFO storage.BlockManagerInfo: Removed broadcast_1_piece0 on jykpro016:36678 in memory (size: 9.4 KB, free: 366.3 MB)
22/08/31 10:30:06 INFO scheduler.JobScheduler: Finished job streaming job 1661913000000 ms.0 from job set of time 1661913000000 ms
22/08/31 10:30:06 ERROR scheduler.JobScheduler: Error running job streaming job 1661913000000 ms.0
org.apache.spark.sql.AnalysisException: cannot resolve '`province_code`' given input columns: []; line 1 pos 7;
'Project ['province_code, 'member_code, 'member_phone, 'creation_date, 'last_update_date]
+- SubqueryAlias `test002`
   +- LogicalRDD false

	at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:42)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1$$anonfun$apply$3.applyOrElse(CheckAnalysis.scala:110)
```

### Flink or Spark Version

CDH 6.3.2- Spark 2.4.0

### Java or Scala Version

JDK1.8  Scala 2.11

### Screenshots

<img width="1396" alt="image" src="https://user-images.githubusercontent.com/3348537/187579843-0a2f7706-c791-4243-9508-a8cee456416a.png">

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by miaoze8** [comment]
Add empty dataset verification
https://github.com/apache/incubator-seatunnel/pull/2578#issue-1356988700
