### ISSUE TITLE
[Bug] java.lang.NoClassDefFoundError: org/apache/flink/table/api/bridge/java/StreamTableEnvironment

### ISSUE THREAD

**Issue by yihui8776** [apache/seatunnel#2598]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

when run the example as docker flink 

got the exception
java.lang.NoClassDefFoundError: org/apache/flink/table/api/bridge/java/StreamTableEnvironment

### SeaTunnel Version

2.1.3

### SeaTunnel Config

```conf
same as example in deploy/docker/flink/config/
```

### Running Command

```shell
docker run -it --rm   -v $(pwd)/config:/seatunnel/config    -v $(pwd)/config/flink-conf.yaml:/flink/conf/flink-conf.yaml   --network flink_local   -e FLINK_PROPERTIES="jobmanager.rpc.address: jobmanager"   yihui8776/seatunnel-flink:v1 /seatunnel/bin/start-seatunnel-flink.sh --config /seatunnel/config/application.conf
Export JVM_ARGS: -Dexecution.parallelism=1
```

### Error Exception

```log
Export JVM_ARGS: -Dexecution.parallelism=1
Execute SeaTunnel Flink Job: ${FLINK_HOME}/bin/flink run -c org.apache.seatunnel.core.flink.SeatunnelFlink /seatunnel/lib/seatunnel-core-flink.jar --config /seatunnel/config/application.conf
Starting execution of program
java.lang.NoClassDefFoundError: org/apache/flink/table/api/bridge/java/StreamTableEnvironment
        at org.apache.seatunnel.flink.FlinkEnvironment.createStreamTableEnvironment(FlinkEnvironment.java:173)
        at org.apache.seatunnel.flink.FlinkEnvironment.prepare(FlinkEnvironment.java:93)
        at org.apache.seatunnel.flink.FlinkEnvironment.prepare(FlinkEnvironment.java:55)
        at org.apache.seatunnel.core.base.config.EnvironmentFactory.getEnvironment(EnvironmentFactory.java:63)
        at org.apache.seatunnel.core.base.config.AbstractExecutionContext.<init>(AbstractExecutionContext.java:53)
        at org.apache.seatunnel.core.flink.config.FlinkExecutionContext.<init>(FlinkExecutionContext.java:48)
        at org.apache.seatunnel.core.flink.command.FlinkApiTaskExecuteCommand.execute(FlinkApiTaskExecuteCommand.java:68)
        at org.apache.seatunnel.core.base.Seatunnel.run(Seatunnel.java:40)
        at org.apache.seatunnel.core.flink.SeatunnelFlink.main(SeatunnelFlink.java:34)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:576)
        at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:438)
        at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:274)
        at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:746)
        at org.apache.flink.client.cli.CliFrontend.runProgram(CliFrontend.java:273)
        at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:205)
        at org.apache.flink.client.cli.CliFrontend.parseParameters(CliFrontend.java:1010)
        at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1083)
        at org.apache.flink.runtime.security.NoOpSecurityContext.runSecured(NoOpSecurityContext.java:30)
        at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1083)
Caused by: java.lang.ClassNotFoundException: org.apache.flink.table.api.bridge.java.StreamTableEnvironment
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 23 more
(base) root@k8s-master1:/media/nizhengqi/7a646073-10bf-41e4-9
```

### Flink or Spark Version

flnik 1.9

### Java or Scala Version

java 8

### Screenshots

Export JVM_ARGS: -Dexecution.parallelism=1
Execute SeaTunnel Flink Job: ${FLINK_HOME}/bin/flink run -c org.apache.seatunnel.core.flink.SeatunnelFlink /seatunnel/lib/seatunnel-core-flink.jar --config /seatunnel/config/application.conf
Starting execution of program
java.lang.NoClassDefFoundError: org/apache/flink/table/api/bridge/java/StreamTableEnvironment
        at org.apache.seatunnel.flink.FlinkEnvironment.createStreamTableEnvironment(FlinkEnvironment.java:173)
        at org.apache.seatunnel.flink.FlinkEnvironment.prepare(FlinkEnvironment.java:93)
        at org.apache.seatunnel.flink.FlinkEnvironment.prepare(FlinkEnvironment.java:55)
        at org.apache.seatunnel.core.base.config.EnvironmentFactory.getEnvironment(EnvironmentFactory.java:63)
        at org.apache.seatunnel.core.base.config.AbstractExecutionContext.<init>(AbstractExecutionContext.java:53)
        at org.apache.seatunnel.core.flink.config.FlinkExecutionContext.<init>(FlinkExecutionContext.java:48)
        at org.apache.seatunnel.core.flink.command.FlinkApiTaskExecuteCommand.execute(FlinkApiTaskExecuteCommand.java:68)
        at org.apache.seatunnel.core.base.Seatunnel.run(Seatunnel.java:40)
        at org.apache.seatunnel.core.flink.SeatunnelFlink.main(SeatunnelFlink.java:34)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:576)
        at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:438)
        at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:274)
        at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:746)
        at org.apache.flink.client.cli.CliFrontend.runProgram(CliFrontend.java:273)
        at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:205)
        at org.apache.flink.client.cli.CliFrontend.parseParameters(CliFrontend.java:1010)
        at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1083)
        at org.apache.flink.runtime.security.NoOpSecurityContext.runSecured(NoOpSecurityContext.java:30)
        at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1083)
Caused by: java.lang.ClassNotFoundException: org.apache.flink.table.api.bridge.java.StreamTableEnvironment
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 23 more
(base) root@k8s-master1:/media/nizhengqi/7a646073-10bf-41e4-9

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ashulin** [comment]
What is the version of Flink?

**Comment by yihui8776** [comment]
> What is the version of Flink?

1.9

**Comment by ashulin** [comment]
For V1 connectors, Flink 1.13+ is supported；
For V2 connectors, Flink 1.12+ is supported
