### ISSUE TITLE
[Bug] [FlinkTransform] Flink Transform can't covert BigDeciamlTypeInfo

### ISSUE THREAD

**Issue by hk-lrzy** [apache/seatunnel#2816]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Flink sql can't use `BigDecimalTypeInfo`. 

### SeaTunnel Version

dev-branch

### SeaTunnel Config

```

env {
  # You can set flink configuration here
  execution.parallelism = 1
  job.mode = "BATCH"
  execution.planner = "blink"
  #execution.checkpoint.interval = 10000
  #execution.checkpoint.data-uri = "hdfs://localhost:9000/checkpoint"
}

source {
  # This is a example source plugin **only for test and demonstrate the feature source plugin**
  FakeSource {
    result_table_name = "fake"
    schema = {
      fields {
        user_id = "bigint",
        date = "date",
        city = "string",
        age = "smallint",
        sex = "smallint",
        price = "decimal(9,2)",
        price_float = "float",
        price_double = "double",
        last_visit_date = "timestamp",
        cost = "bigint",
        max_dwell_time = "int",
        min_dwell_time = "int"
      }
    }
  }
}

transform {
  sql {
    sql = "select user_id,`date`,city,age,sex ,price,price_float,price_double,last_visit_date,cost,max_dwell_time,min_dwell_time from fake"
  }

  # If you would like to get more information about how to configure seatunnel and see full list of transform plugins,
  # please go to https://seatunnel.apache.org/docs/transform/sql
}

sink {
  Console {}

  # If you would like to get more information about how to configure seatunnel and see full list of sink plugins,
  # please go to https://seatunnel.apache.org/docs/category/sink-v2
}
```

### Running Command

```shell
example.
```

### Error Exception

```
Caused by: org.apache.flink.table.codegen.CodeGenException: Incompatible types of expression and result type. Expression[GeneratedExpression(result$10,isNull$11,,Decimal(9,2),false)] type is [Decimal(9,2)], result type is [GenericType<java.math.BigDecimal>]
	at org.apache.flink.table.codegen.CodeGenerator$$anonfun$generateResultExpression$2.apply(CodeGenerator.scala:379)
	at org.apache.flink.table.codegen.CodeGenerator$$anonfun$generateResultExpression$2.apply(CodeGenerator.scala:377)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.flink.table.codegen.CodeGenerator.generateResultExpression(CodeGenerator.scala:377)
	at org.apache.flink.table.codegen.CodeGenerator.generateConverterResultExpression(CodeGenerator.scala:295)
	at org.apache.flink.table.plan.nodes.datastream.StreamScan$class.generateConversionProcessFunction(StreamScan.scala:115)
	at org.apache.flink.table.plan.nodes.datastream.StreamScan$class.convertToInternalRow(StreamScan.scala:74)
	at org.apache.flink.table.plan.nodes.datastream.DataStreamScan.convertToInternalRow(DataStreamScan.scala:46)
	at org.apache.flink.table.plan.nodes.datastream.DataStreamScan.translateToPlan(DataStreamScan.scala:90)
	at org.apache.flink.table.plan.nodes.datastream.DataStreamCalc.translateToPlan(DataStreamCalc.scala:73)
```

### Flink or Spark Version

flink

### Java or Scala Version

java 1.8
scala 2.11

### Screenshots

![img_v2_3fce8574-d9df-4d55-8e6b-4d44ee0b35bg](https://user-images.githubusercontent.com/14176134/191249774-51e58799-33c3-488a-888c-ccf94bfb5efd.jpg)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment]
link https://github.com/apache/incubator-seatunnel/issues/2872
