### ISSUE TITLE
[Bug][seatunnel-translation-spark] java.lang.NoSuchMethodError: java.lang.Math.multiplyExact(JI)J

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#2826]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Running MongodbIT throw java.lang.NoSuchMethodError: java.lang.Math.multiplyExact(JI)J

### SeaTunnel Version

dev branch

### SeaTunnel Config

```conf
https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-e2e/seatunnel-spark-connector-v2-e2e/connector-mongodb-spark-e2e/src/test/resources/mongodb/mongodb_source_and_sink.conf
```

### Running Command

```shell
https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-e2e/seatunnel-spark-connector-v2-e2e/connector-mongodb-spark-e2e/src/test/java/org/apache/seatunnel/e2e/spark/v2/mongodb/MongodbIT.java
```

### Error Exception

```log
2022-09-20T16:29:46.6598281Z 22/09/20 16:29:45 INFO MongodbSourceReader: Read mongodb document: Document{{id=0, c_map=Document{{key=1}}, c_array=[1], c_string=string, c_boolean=false, c_tinyint=1, c_smallint=1, c_int=1, c_bigint=1, c_float=1.1, c_double=1.1, c_decimal=1.1, c_bytes=org.bson.types.Binary@445c13, c_date=Tue Sep 20 00:00:00 UTC 2022, c_timestamp=Timestamp{value=1663691367968, seconds=387, inc=1539024416}}}
2022-09-20T16:29:46.6598964Z 22/09/20 16:29:45 ERROR MongodbSourceReader: Failed to read mongodb
2022-09-20T16:29:46.6599410Z java.lang.NoSuchMethodError: java.lang.Math.multiplyExact(JI)J
2022-09-20T16:29:46.6600107Z 	at org.apache.seatunnel.translation.spark.common.utils.InstantConverterUtils.toEpochMicro(InstantConverterUtils.java:38)
2022-09-20T16:29:46.6601013Z 	at org.apache.seatunnel.translation.spark.common.serialization.InternalRowConverter.convert(InternalRowConverter.java:84)
2022-09-20T16:29:46.6603170Z 	at org.apache.seatunnel.translation.spark.common.serialization.InternalRowConverter.convert(InternalRowConverter.java:113)
2022-09-20T16:29:46.6604111Z 	at org.apache.seatunnel.translation.spark.common.serialization.InternalRowConverter.convert(InternalRowConverter.java:77)
2022-09-20T16:29:46.6605025Z 	at org.apache.seatunnel.translation.spark.common.serialization.InternalRowConverter.convert(InternalRowConverter.java:66)
2022-09-20T16:29:46.6605879Z 	at org.apache.seatunnel.translation.spark.common.InternalRowCollector.collect(InternalRowCollector.java:42)
2022-09-20T16:29:46.6606671Z 	at org.apache.seatunnel.translation.spark.common.InternalRowCollector.collect(InternalRowCollector.java:27)
2022-09-20T16:29:46.6607489Z 	at org.apache.seatunnel.connectors.seatunnel.mongodb.source.MongodbSourceReader.pollNext(MongodbSourceReader.java:103)
2022-09-20T16:29:46.6664429Z 	at org.apache.seatunnel.translation.source.ParallelSource.run(ParallelSource.java:125)
2022-09-20T16:29:46.6665271Z 	at org.apache.seatunnel.translation.spark.common.source.batch.ParallelBatchPartitionReader.lambda$prepare$0(ParallelBatchPartitionReader.java:97)
2022-09-20T16:29:46.6665969Z 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2022-09-20T16:29:46.6666380Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2022-09-20T16:29:46.6666898Z 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
2022-09-20T16:29:46.6667545Z 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
2022-09-20T16:29:46.6668117Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2022-09-20T16:29:46.6668601Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2022-09-20T16:29:46.6668975Z 	at java.lang.Thread.run(Thread.java:748)
```

### Screenshots

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/14371345/191393325-f0bcb4d0-7135-4603-a9e1-82efe4ba7617.png">

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hailin0** [comment]
<img width="1318" alt="image" src="https://user-images.githubusercontent.com/14371345/191393527-832f47a3-c488-4d48-b0ca-43153ead911c.png">
