### ISSUE TITLE
Run e2etestcase for windows docker problem for help

### ISSUE THREAD

**Issue by guanboo** [apache/seatunnel#2876]
This is  my Environment message:

![image](https://user-images.githubusercontent.com/110977641/192087414-7ca66a9d-2865-4dfb-939f-54dffa245baf.png)

I run(dev) FakeSourceToConsoleIT.testFakeSourceToConsoleSink() error . 
logs:

```log
org.apache.seatunnel.e2e.flink.v2.fake.FakeSourceToConsoleIT,testFakeSourceToConsoleSink
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/D:/workgit/mav-lib/org/apache/logging/log4j/log4j-slf4j-impl/2.17.1/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/D:/workgit/mav-lib/org/slf4j/slf4j-log4j12/1.7.25/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
15:41:37.413 [docker-java-stream--1007472360] ERROR com.github.dockerjava.api.async.ResultCallbackTemplate - Error during callback
com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"received unexpected HTTP status: 500 Server Error"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.16.3.jar:?]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.16.3.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]

java.util.concurrent.CompletionException: com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"received unexpected HTTP status: 500 Server Error"}
```

**Comment by msftgitsklsd** [comment]
You could try this mirror "https://bz8ea7hh.mirror.aliyuncs.com", I got the same error msg, already sloved after changed this config

**Comment by guanboo** [comment]
hi bro thx, but  this url（https://bz8ea7hh.mirror.aliyuncs.com）  can not visit

**Comment by ashulin** [comment]
hi, @guanboo 
I can't reproduce your problem in my windows10 environment.
![image](https://user-images.githubusercontent.com/36807946/193357698-40d4883e-e983-43f6-8185-23c26cc8cb00.png)

looks like your network problem, maybe you can add (Although I didn't add this)
``` json
"registry-mirrors": [
        "http://hub-mirror.c.163.com",
        "https://docker.mirrors.ustc.edu.cn",
        "https://registry.docker-cn.com"
    ]
```
 to docker deskop/settings/Docker Engine.

like this:
![image](https://user-images.githubusercontent.com/36807946/193357872-a5d00660-6303-4ed6-b5cb-776f54a01677.png)
