### ISSUE TITLE
[Bug] [ST-Engine] Can not run more than one job in a node

### ISSUE THREAD

**Issue by EricJoy2048** [apache/seatunnel#2918]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Can not run more than one job in a node

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
env {
  # You can set flink configuration here
  job.mode = "STREAMING"
  execution.checkpoint.interval = 5000
}

source {
  # This is a example source plugin **only for test and demonstrate the feature source plugin**
    FakeSource {
      result_table_name = "fake"
      field_name = "name,age",
    }
}

transform {
}

sink {
  Console {
  }
}
```

### Running Command

```shell
first job: sh seatunnel.sh --config ../config/stream_fake_to_console.conf -e local

second job: sh seatunnel.sh --config ../config/stream_fake_to_console.conf -e local
```

### Error Exception

```log
Sep 27, 2022 6:22:33 PM com.hazelcast.client.impl.connection.ClientConnectionManager
WARNING: hz.client_1 [seatunnel_default_cluster-465044] [5.1] Exception during initial connection to [localhost]:5801: com.hazelcast.client.AuthenticationException: Authentication failed. The configured cluster name on the client (see ClientConfig.setClusterName()) does not match the one configured in the cluster or the credentials set in the Client security config could not be authenticated
Sep 27, 2022 6:22:33 PM com.hazelcast.client.impl.connection.ClientConnectionManager
WARNING: hz.client_1 [seatunnel_default_cluster-465044] [5.1] Unable to get live cluster connection, retry in 1050 ms, attempt: 2, cluster connect timeout: INFINITE, max backoff: 30000 ms
Sep 27, 2022 6:22:34 PM com.hazelcast.client.impl.connection.ClientConnectionManager
INFO: hz.client_1 [seatunnel_default_cluster-465044] [5.1] Trying to connect to [localhost]:5801
Sep 27, 2022 6:22:34 PM com.hazelcast.client.impl.connection.tcp.TcpClientConnection
WARNING: hz.client_1 [seatunnel_default_cluster-465044] [5.1] ClientConnection{alive=false, connectionId=3, channel=NioChannel{/127.0.0.1:49554->localhost/127.0.0.1:5801}, remoteAddress=null, lastReadTime=2022-09-27 18:22:34.239, lastWriteTime=2022-09-27 18:22:34.237, closedTime=2022-09-27 18:22:34.239, connected server version=null} closed. Reason: Failed to authenticate connection
com.hazelcast.client.AuthenticationException: Authentication failed. The configured cluster name on the client (see ClientConfig.setClusterName()) does not match the one configured in the cluster or the credentials set in the Client security config could not be authenticated
        at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.checkAuthenticationResponse(TcpClientConnectionManager.java:995)
        at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.onAuthenticated(TcpClientConnectionManager.java:898)
        at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.getOrConnectToAddress(TcpClientConnectionManager.java:615)
        at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.lambda$doConnectToCandidateCluster$3(TcpClientConnectionManager.java:505)
        at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.connect(TcpClientConnectionManager.java:459)
        at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.doConnectToCandidateCluster(TcpClientConnectionManager.java:505)
        at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.doConnectToCluster(TcpClientConnectionManager.java:411)
        at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.connectToCluster(TcpClientConnectionManager.java:372)
        at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:381)
        at com.hazelcast.client.HazelcastClient.constructHazelcastClient(HazelcastClient.java:460)
        at com.hazelcast.client.HazelcastClient.newHazelcastClientInternal(HazelcastClient.java:416)
        at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:136)
        at org.apache.seatunnel.engine.client.SeaTunnelHazelcastClient.<init>(SeaTunnelHazelcastClient.java:46)
        at org.apache.seatunnel.engine.client.SeaTunnelClient.<init>(SeaTunnelClient.java:33)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:68)
        at org.apache.seatunnel.core.starter.Seatunnel.run(Seatunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:31)
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 15810785091** [comment]
Version 2.3.1 has the same problem

**Comment by happydts** [comment]
+1 为什么不能运行多个作业

**Comment by happydts** [comment]
奥，使用cluster模式就可以在一个节点跑多个任务了
