### ISSUE TITLE
[Bug] [seatunnel-api]ClickhouseSource Prepare Error

### ISSUE THREAD

**Issue by FWLamb** [apache/seatunnel#2967]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When I do the clickhouse e2e test：
```log
22/10/01 16:03:50 ERROR Seatunnel: Fatal Error, 

22/10/01 16:03:50 ERROR Seatunnel: Please submit bug report in https://github.com/apache/incubator-seatunnel/issues

22/10/01 16:03:50 ERROR Seatunnel: Reason:PluginName: Clickhouse, PluginType: source, Message: clickhouse, server ClickHouseNode(addr=http:clickhouse:8123, db=default)@-2009623697 

22/10/01 16:03:50 ERROR Seatunnel: Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: PluginName: Clickhouse, PluginType: source, Message: clickhouse, server ClickHouseNode(addr=http:clickhouse:8123, db=default)@-2009623697
```

**Clickhouse configuration file**
```conf
env {
  execution.parallelism = 1
  job.mode = "BATCH"
}

source {
 Clickhouse {
     host = "clickhouse:8123"
     database = "default"
     sql = "select * from source_table"
     username = "default"
     password = ""
     result_table_name = "source_table"
    }
}

transform {
}

sink {
  Clickhouse {
    host = "clickhouse:8123"
    database = "default"
    table = "sink_table"
    fields = [
    "id",
    "c_map",
    "c_array",
    "c_string",
    "c_boolean",
    "c_int8",
    "c_int16",
    "c_int32",
    "c_int64",
    "c_float32",
    "c_float64",
    "c_decimal",
    "c_date",
    "c_datetime",
    "c_nullable"
    ]
    username = "default"
    password = ""
   }
}
```

### SeaTunnel Version

V2

### SeaTunnel Config

```conf
null
```

### Running Command

```shell
null
```

### Error Exception

```log
22/10/01 16:03:40 INFO AbstractPluginDiscovery: Discovery plugin jar: Clickhouse at: file:/tmp/seatunnel/connectors/seatunnel/connector-clickhouse-2.1.3-SNAPSHOT-2.11.12.jar
22/10/01 16:03:40 INFO AbstractPluginDiscovery: Load plugin: PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='Clickhouse'} from classpath
22/10/01 16:03:50 ERROR SparkApiTaskExecuteCommand: Run SeaTunnel on spark failed.
org.apache.seatunnel.api.common.PrepareFailException: PluginName: Clickhouse, PluginType: source, Message: clickhouse, server ClickHouseNode(addr=http:clickhouse:8123, db=default)@-2009623697
	at org.apache.seatunnel.connectors.seatunnel.clickhouse.source.ClickhouseSource.prepare(ClickhouseSource.java:91)
	at org.apache.seatunnel.core.starter.spark.execution.SourceExecuteProcessor.initializePlugins(SourceExecuteProcessor.java:78)
	at org.apache.seatunnel.core.starter.spark.execution.AbstractPluginExecuteProcessor.<init>(AbstractPluginExecuteProcessor.java:49)
	at org.apache.seatunnel.core.starter.spark.execution.SourceExecuteProcessor.<init>(SourceExecuteProcessor.java:49)
	at org.apache.seatunnel.core.starter.spark.execution.SparkExecution.<init>(SparkExecution.java:48)
	at org.apache.seatunnel.core.starter.spark.command.SparkApiTaskExecuteCommand.execute(SparkApiTaskExecuteCommand.java:53)
	at org.apache.seatunnel.core.starter.Seatunnel.run(Seatunnel.java:40)
	at org.apache.seatunnel.core.starter.spark.SeatunnelSpark.main(SeatunnelSpark.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
22/10/01 16:03:50 ERROR Seatunnel: 

===============================================================================


22/10/01 16:03:50 ERROR Seatunnel: Fatal Error, 

22/10/01 16:03:50 ERROR Seatunnel: Please submit bug report in https://github.com/apache/incubator-seatunnel/issues

22/10/01 16:03:50 ERROR Seatunnel: Reason:PluginName: Clickhouse, PluginType: source, Message: clickhouse, server ClickHouseNode(addr=http:clickhouse:8123, db=default)@-2009623697 

22/10/01 16:03:50 ERROR Seatunnel: Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: PluginName: Clickhouse, PluginType: source, Message: clickhouse, server ClickHouseNode(addr=http:clickhouse:8123, db=default)@-2009623697
	at org.apache.seatunnel.core.starter.spark.command.SparkApiTaskExecuteCommand.execute(SparkApiTaskExecuteCommand.java:57)
	at org.apache.seatunnel.core.starter.Seatunnel.run(Seatunnel.java:40)
	at org.apache.seatunnel.core.starter.spark.SeatunnelSpark.main(SeatunnelSpark.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
 
22/10/01 16:03:50 ERROR Seatunnel: 
===============================================================================



Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: PluginName: Clickhouse, PluginType: source, Message: clickhouse, server ClickHouseNode(addr=http:clickhouse:8123, db=default)@-2009623697
	at org.apache.seatunnel.core.starter.spark.command.SparkApiTaskExecuteCommand.execute(SparkApiTaskExecuteCommand.java:57)
	at org.apache.seatunnel.core.starter.Seatunnel.run(Seatunnel.java:40)
	at org.apache.seatunnel.core.starter.spark.SeatunnelSpark.main(SeatunnelSpark.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
22/10/01 16:03:50 INFO SparkContext: Invoking stop() from shutdown hook
22/10/01 16:03:50 INFO SparkUI: Stopped Spark web UI at http://81c36bcb7cd6:4040
22/10/01 16:03:50 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
22/10/01 16:03:50 INFO MemoryStore: MemoryStore cleared
22/10/01 16:03:50 INFO BlockManager: BlockManager stopped
22/10/01 16:03:50 INFO BlockManagerMaster: BlockManagerMaster stopped
22/10/01 16:03:50 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
22/10/01 16:03:50 INFO SparkContext: Successfully stopped SparkContext
22/10/01 16:03:50 INFO ShutdownHookManager: Shutdown hook called
22/10/01 16:03:50 INFO ShutdownHookManager: Deleting directory /tmp/spark-934762ea-de63-48ab-867d-d5f505295419
22/10/01 16:03:50 INFO ShutdownHookManager: Deleting directory /tmp/spark-cb4f3033-5c4d-4d2e-8486-ac6d8d236d1f
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ashulin** [comment]
@Hisoka-X PTAL

**Comment by ashulin** [comment]
Since your Clickhouse does not have a password, you can try setting userName to "".

**Comment by FWLamb** [comment]
> Since your Clickhouse does not have a password, you can try setting userName to "".

The same error occurred

**Comment by Hisoka-X** [comment]
Working fine with my env.
![image](https://user-images.githubusercontent.com/32387433/194691277-11359565-fe53-4360-8d95-b3ac42c10443.png)
