### ISSUE TITLE
seatunnel-transform-flink-udf  Class loading failed

### ISSUE THREAD

**Issue by Tanj0304** [apache/seatunnel#3171]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: Flink job executed failed
	at org.apache.seatunnel.core.starter.flink.command.FlinkApiTaskExecuteCommand.execute(FlinkApiTaskExecuteCommand.java:55)
	at org.apache.seatunnel.core.starter.Seatunnel.run(Seatunnel.java:39)
	at org.apache.seatunnel.example.flink.v2.SeaTunnelApiExample.main(SeaTunnelApiExample.java:42)
Caused by: org.apache.seatunnel.core.starter.exception.TaskExecuteException: SeaTunnel transform task: udf execute error
	at org.apache.seatunnel.core.starter.flink.execution.TransformExecuteProcessor.execute(TransformExecuteProcessor.java:83)
	at org.apache.seatunnel.core.starter.flink.execution.FlinkExecution.execute(FlinkExecution.java:68)
	at org.apache.seatunnel.core.starter.flink.command.FlinkApiTaskExecuteCommand.execute(FlinkApiTaskExecuteCommand.java:53)
	... 2 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: test_1
	at org.apache.seatunnel.flink.transform.UDF.registerFunction(UDF.java:71)
	at org.apache.seatunnel.core.starter.flink.execution.TransformExecuteProcessor.execute(TransformExecuteProcessor.java:79)
	... 4 more
Caused by: java.lang.ClassNotFoundException: test_1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.apache.seatunnel.flink.transform.UDF.registerFunction(UDF.java:68)
	... 5 more

### SeaTunnel Version

2.3.0-beta-release

### SeaTunnel Config

```conf
# 配置参数
env {
    # You can set flink configuration here
    job.name=kafka_to_console
    job.mode=STREAMING
    execution.parallelism = 1
}

# 在 source 所属的块中配置数据源
source {
    Kafka {
        bootstrap.servers = "127.0.0.1:9092"
        topic = test
	consumer.group = "seatunnel"
        result_table_name = test
        }
}

# 在 transform 的块中声明转换插件
transform {
    udf {
        function.test_1 = "org.apache.seatunnel.flink.transform.UdfTest"
    }
    sql {
        sql = "select test_1(kafka_topic) from test"
    }
}

# 在 sink 块中声明要输出到哪
sink {
    Console {}
}
```

### Running Command

```shell
Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: Flink job executed failed
	at org.apache.seatunnel.core.starter.flink.command.FlinkApiTaskExecuteCommand.execute(FlinkApiTaskExecuteCommand.java:55)
	at org.apache.seatunnel.core.starter.Seatunnel.run(Seatunnel.java:39)
	at org.apache.seatunnel.example.flink.v2.SeaTunnelApiExample.main(SeaTunnelApiExample.java:42)
Caused by: org.apache.seatunnel.core.starter.exception.TaskExecuteException: SeaTunnel transform task: udf execute error
	at org.apache.seatunnel.core.starter.flink.execution.TransformExecuteProcessor.execute(TransformExecuteProcessor.java:83)
	at org.apache.seatunnel.core.starter.flink.execution.FlinkExecution.execute(FlinkExecution.java:68)
	at org.apache.seatunnel.core.starter.flink.command.FlinkApiTaskExecuteCommand.execute(FlinkApiTaskExecuteCommand.java:53)
	... 2 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: test_1
	at org.apache.seatunnel.flink.transform.UDF.registerFunction(UDF.java:71)
	at org.apache.seatunnel.core.starter.flink.execution.TransformExecuteProcessor.execute(TransformExecuteProcessor.java:79)
	... 4 more
Caused by: java.lang.ClassNotFoundException: test_1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.apache.seatunnel.flink.transform.UDF.registerFunction(UDF.java:68)
	... 5 more
```

### Error Exception

```log
Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: Flink job executed failed
	at org.apache.seatunnel.core.starter.flink.command.FlinkApiTaskExecuteCommand.execute(FlinkApiTaskExecuteCommand.java:55)
	at org.apache.seatunnel.core.starter.Seatunnel.run(Seatunnel.java:39)
	at org.apache.seatunnel.example.flink.v2.SeaTunnelApiExample.main(SeaTunnelApiExample.java:42)
Caused by: org.apache.seatunnel.core.starter.exception.TaskExecuteException: SeaTunnel transform task: udf execute error
	at org.apache.seatunnel.core.starter.flink.execution.TransformExecuteProcessor.execute(TransformExecuteProcessor.java:83)
	at org.apache.seatunnel.core.starter.flink.execution.FlinkExecution.execute(FlinkExecution.java:68)
	at org.apache.seatunnel.core.starter.flink.command.FlinkApiTaskExecuteCommand.execute(FlinkApiTaskExecuteCommand.java:53)
	... 2 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: test_1
	at org.apache.seatunnel.flink.transform.UDF.registerFunction(UDF.java:71)
	at org.apache.seatunnel.core.starter.flink.execution.TransformExecuteProcessor.execute(TransformExecuteProcessor.java:79)
	... 4 more
Caused by: java.lang.ClassNotFoundException: test_1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.apache.seatunnel.flink.transform.UDF.registerFunction(UDF.java:68)
	... 5 more
```

### Flink or Spark Version

flink 1.13.6

### Java or Scala Version

1.8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Tanj0304** [comment]
properties.forEach((k, v) -> {
            classNames.add(String.valueOf(v));
            functionNames.add(String.valueOf(k));
        });

**Comment by Hisoka-X** [comment]
Same with #3250
