### ISSUE TITLE
[Bug] [sink-hive] Table in instance of org.apache.seatunnel.connectors.seatunnel.hive.sink.HiveSink

### ISSUE THREAD

**Issue by kali2077** [apache/seatunnel#3315]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

when sink hive,it throws error like 'Table in instance of org.apache.seatunnel.connectors.seatunnel.hive.sink.HiveSink'

### SeaTunnel Version

seatunnel-2.3.0-beta

### SeaTunnel Config

```conf
env {
        execution.parallelism = 1
 
}
 
source {

    Jdbc {
        url = "jdbc:mysql://xxxxxxxxx:3306/xxxxxx?serverTimezone=GMT%2b8"
        driver = "com.mysql.cj.jdbc.Driver"
        connection_check_timeout_sec = 1000
        user = "xxxxx"
        password = "xxxxxx"
        query = "select id  ,create_time from tableA  limit 100;"
    }
 
}
 
transform {
}
 
sink {
    Hive{
    table_name = "ods_fdds.test_orc"
    metastore_uri = "thrift://192.168.249.63:9083"
    # partition_by = ["20221106"]
    sink_columns = "id,create_time"
}
}
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/hive.conf -e local
```

### Error Exception

```log
十一月 07, 2022 10:09:52 上午 org.apache.seatunnel.engine.server.TaskExecutionService
严重: [localhost]:5801 [seatunnel_default_cluster-866610] [5.1] TaskGroupID : taskGroupLocation is null  deploy error with Exception: com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassCastException: cannot assign instance of org.apache.hadoop.hive.metastore.api.Table to field org.apache.seatunnel.connectors.seatunnel.hive.sink.HiveSink.tableInformation of type org.apache.hadoop.hive.metastore.api.Table in instance of org.apache.seatunnel.connectors.seatunnel.hive.sink.HiveSink
        at com.hazelcast.internal.serialization.impl.SerializationUtil.handleException(SerializationUtil.java:111)
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:274)
        at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject.deserializeWithCustomClassLoader(CustomClassLoadedObject.java:66)
        at org.apache.seatunnel.engine.server.TaskExecutionService.deployTask(TaskExecutionService.java:152)
        at org.apache.seatunnel.engine.server.dag.physical.PhysicalVertex.lambda$deployOnLocal$0(PhysicalVertex.java:185)
        at org.apache.seatunnel.engine.server.dag.physical.PhysicalVertex.deployInternal(PhysicalVertex.java:222)
        at org.apache.seatunnel.engine.server.dag.physical.PhysicalVertex.deployOnLocal(PhysicalVertex.java:182)
        at org.apache.seatunnel.engine.server.dag.physical.PhysicalVertex.deploy(PhysicalVertex.java:208)
        at org.apache.seatunnel.engine.server.scheduler.PipelineBaseScheduler.lambda$deployTask$6(PipelineBaseScheduler.java:183)
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassCastException: cannot assign instance of org.apache.hadoop.hive.metastore.api.Table to field org.apache.seatunnel.connectors.seatunnel.hive.sink.HiveSink.tableInformation of type org.apache.hadoop.hive.metastore.api.Table in instance of org.apache.seatunnel.connectors.seatunnel.hive.sink.HiveSink
        at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2133)
        at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1305)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2251)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2169)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2245)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2169)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2245)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2169)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
        at java.util.HashMap.readObject(HashMap.java:1404)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2136)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2245)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2169)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
        at com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:92)
        at com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:85)
        at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:268)
        ... 13 more

十一月 07, 2022 10:09:52 上午 org.apache.seatunnel.engine.server.dag.physical.PhysicalVertex
信息: Job SeaTunnel (641821571299672065), Pipeline: [(1/1)], task: [Hive-AggregatedCommitterTask (1/1)], taskGroupLocation: [TaskGroupLocation(jobId=641821571299672065, pipelineId=1, taskGroupId=3)] turn from state DEPLOYING to RUNNING.
十一月 07, 2022 10:09:52 上午 org.apache.seatunnel.engine.server.TaskExecutionService
严重: [localhost]:5801 [seatunnel_default_cluster-866610] [5.1] TaskGroupID : taskGroupLocation is null  deploy error with Exception: com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassCastException: cannot assign instance of org.apache.hadoop.hive.metastore.api.Table to field org.apache.seatunnel.connectors.seatunnel.hive.sink.HiveSink.tableInformation of type org.apache.hadoop.hive.metastore.api.Table in instance of org.apache.seatunnel.connectors.seatunnel.hive.sink.HiveSink
        at com.hazelcast.internal.serialization.impl.SerializationUtil.handleException(SerializationUtil.java:111)
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:274)
        at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject.deserializeWithCustomClassLoader(CustomClassLoadedObject.java:66)
        at org.apache.seatunnel.engine.server.TaskExecutionService.deployTask(TaskExecutionService.java:152)
        at org.apache.seatunnel.engine.server.dag.physical.PhysicalVertex.lambda$deployOnLocal$0(PhysicalVertex.java:185)
        at org.apache.seatunnel.engine.server.dag.physical.PhysicalVertex.deployInternal(PhysicalVertex.java:222)
        at org.apache.seatunnel.engine.server.dag.physical.PhysicalVertex.deployOnLocal(PhysicalVertex.java:182)
        at org.apache.seatunnel.engine.server.dag.physical.PhysicalVertex.deploy(PhysicalVertex.java:208)
        at org.apache.seatunnel.engine.server.scheduler.PipelineBaseScheduler.lambda$deployTask$6(PipelineBaseScheduler.java:183)
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassCastException: cannot assign instance of org.apache.hadoop.hive.metastore.api.Table to field org.apache.seatunnel.connectors.seatunnel.hive.sink.HiveSink.tableInformation of type org.apache.hadoop.hive.metastore.api.Table in instance of org.apache.seatunnel.connectors.seatunnel.hive.sink.HiveSink
        at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2133)
        at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1305)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2251)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2169)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2245)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2169)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2245)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2169)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
        at java.util.ArrayList.readObject(ArrayList.java:791)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:105
```

### Java or Scala Version

jdk1.8.0_144

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment]
@Hisoka-X  PTAL

@kali2077  can you config the Hive connector reference https://seatunnel.apache.org/docs/2.3.0-beta/connector-v2/sink/Hive ? I found the `sink_columns ` is not right.

**Comment by Hisoka-X** [comment]
Can you use dev branch to test again? Thanks!
