### ISSUE TITLE
[Bug] [Seatunnel-dist] cannot load sql transform plugin

### ISSUE THREAD

**Issue by Grypse** [apache/seatunnel#3744]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Cannot load sql transform plugin from lib/ directory.

### SeaTunnel Version

2.3.1-snapshot

### SeaTunnel Config

```conf
seatunnel:
    engine:
       backup-count: 1
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/v2.batch.config.template -e local
```

### Error Exception

```log
2022-12-16 21:49:54,439 ERROR org.apache.seatunnel.core.starter.Seatunnel - 

===============================================================================


2022-12-16 21:49:54,439 ERROR org.apache.seatunnel.core.starter.Seatunnel - Fatal Error, 

2022-12-16 21:49:54,439 ERROR org.apache.seatunnel.core.starter.Seatunnel - Please submit bug report in https://github.com/apache/incubator-seatunnel/issues

2022-12-16 21:49:54,439 ERROR org.apache.seatunnel.core.starter.Seatunnel - Reason:Plugin PluginIdentifier{engineType='seatunnel', pluginType='transform', pluginName='sql'} not found. 

2022-12-16 21:49:54,443 ERROR org.apache.seatunnel.core.starter.Seatunnel - Exception StackTrace:java.lang.RuntimeException: Plugin PluginIdentifier{engineType='seatunnel', pluginType='transform', pluginName='sql'} not found.
	at org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery.createPluginInstance(AbstractPluginDiscovery.java:200)
	at org.apache.seatunnel.engine.core.parse.ConnectorInstanceLoader.loadTransformInstance(ConnectorInstanceLoader.java:95)
	at org.apache.seatunnel.engine.core.parse.JobConfigParser.sampleAnalyze(JobConfigParser.java:326)
	at org.apache.seatunnel.engine.core.parse.JobConfigParser.parse(JobConfigParser.java:125)
	at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.getLogicalDag(JobExecutionEnvironment.java:129)
	at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:121)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:91)
	at org.apache.seatunnel.core.starter.Seatunnel.run(Seatunnel.java:39)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:31)
 
2022-12-16 21:49:54,443 ERROR org.apache.seatunnel.core.starter.Seatunnel - 
===============================================================================



Exception in thread "main" java.lang.RuntimeException: Plugin PluginIdentifier{engineType='seatunnel', pluginType='transform', pluginName='sql'} not found.
	at org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery.createPluginInstance(AbstractPluginDiscovery.java:200)
	at org.apache.seatunnel.engine.core.parse.ConnectorInstanceLoader.loadTransformInstance(ConnectorInstanceLoader.java:95)
	at org.apache.seatunnel.engine.core.parse.JobConfigParser.sampleAnalyze(JobConfigParser.java:326)
	at org.apache.seatunnel.engine.core.parse.JobConfigParser.parse(JobConfigParser.java:125)
	at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.getLogicalDag(JobExecutionEnvironment.java:129)
	at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:121)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:91)
	at org.apache.seatunnel.core.starter.Seatunnel.run(Seatunnel.java:39)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:31)
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hailin0** [comment]
https://github.com/apache/incubator-seatunnel/issues/3178

transform-v2 currently unsupported sql transform
