### ISSUE TITLE
[Bug] [Transform-UDF]  Seatunnel 2.3.0-beta version, does v2 not support udf?

### ISSUE THREAD

**Issue by 521daichen** [apache/seatunnel#3747]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Seatunnel 2.3.0-beta version, does v2 not support udf?

### SeaTunnel Version

2.3.0-beta

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
  job.mode = "STREAMING"
}

source {
    Jdbc {
        result_table_name = "test"
        url = "jdbc:mysql://localhost/t"
        driver = "com.mysql.cj.jdbc.Driver"
        connection_check_timeout_sec = 100
        user = "root"
        password = "123456789"
        query = "select name from test"
    }
    Jdbc {
        result_table_name = "test_middle"
        url = "jdbc:mysql://localhost/t"
        driver = "com.mysql.cj.jdbc.Driver"
        connection_check_timeout_sec = 100
        user = "root"
        password = "123456789"
        query = "select name,age from test_middle"
    }
}


transform {
    udf {
        function.test_1 = "org.apache.seatunnel.flink.transform.UdfTest"
    }
    sql {
        result_table_name = "t1"
        sql = "select with_dylan(t1.name) as `name`, t2.age as `age` from test as t1 inner join test_middle as t2 on t1.name=t2.name"
    }
    sql {
        result_table_name = "t2"
        sql = "select t1.name as `n`, t2.age as `a` from test as t1 inner join test_middle as t2 on t1.name=t2.name"
    }
}

sink {
    Jdbc {
        source_table_name = "t1"
        driver = "com.mysql.cj.jdbc.Driver"
        url = "jdbc:mysql://localhost:3306/t"
        user = root
        password = 123456789
        query = "insert into test_sink(name, age) values(?,?)"
    }
    Http {
        source_table_name = "t2"
        url = "http://localhost:9999/save"
        headers {
            token = "9e32e859ef044462a257e1fc76730066"
        }
     }
}
```

### Running Command

```shell
./bin/start-seatunnel-flink-connector-v2.sh \
--config ./config/1.conf
```

### Error Exception

```log
--config ./config/1.conf
Execute SeaTunnel Flink Job: ${FLINK_HOME}/bin/flink run -c org.apache.seatunnel.core.starter.flink.SeatunnelFlink /Users/dylan/flink/apache-seatunnel-incubating-2.3.0-beta/lib/seatunnel-flink-starter.jar --config ./config/1.conf -Dpipeline.name=SeaTunnel

------------------------------------------------------------
 The program finished with the following exception:

org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: Plugin PluginIdentifier{engineType='seatunnel', pluginType='transform', pluginName='udf'} not found.
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:372)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222)
	at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114)
	at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:812)
	at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:246)
	at org.apache.flink.client.cli.CliFrontend.parseAndRun(CliFrontend.java:1054)
	at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1132)
	at org.apache.flink.runtime.security.contexts.NoOpSecurityContext.runSecured(NoOpSecurityContext.java:28)
	at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1132)
Caused by: java.lang.RuntimeException: Plugin PluginIdentifier{engineType='seatunnel', pluginType='transform', pluginName='udf'} not found.
	at org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery.createPluginInstance(AbstractPluginDiscovery.java:137)
	at org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery.createPluginInstance(AbstractPluginDiscovery.java:99)
	at org.apache.seatunnel.core.starter.flink.execution.TransformExecuteProcessor.lambda$initializePlugins$0(TransformExecuteProcessor.java:56)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.apache.seatunnel.core.starter.flink.execution.TransformExecuteProcessor.initializePlugins(TransformExecuteProcessor.java:60)
	at org.apache.seatunnel.core.starter.flink.execution.AbstractPluginExecuteProcessor.<init>(AbstractPluginExecuteProcessor.java:56)
	at org.apache.seatunnel.core.starter.flink.execution.TransformExecuteProcessor.<init>(TransformExecuteProcessor.java:45)
	at org.apache.seatunnel.core.starter.flink.execution.FlinkExecution.<init>(FlinkExecution.java:60)
	at org.apache.seatunnel.core.starter.flink.command.FlinkApiTaskExecuteCommand.execute(FlinkApiTaskExecuteCommand.java:51)
	at org.apache.seatunnel.core.starter.Seatunnel.run(Seatunnel.java:39)
	at org.apache.seatunnel.core.starter.flink.SeatunnelFlink.main(SeatunnelFlink.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355)
```

### Flink or Spark Version

flin version: 1.13.0

### Java or Scala Version

jdk8

### Screenshots

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/21999616/208224708-9528042a-b249-448e-9726-f9141cef218c.png">

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by luclin** [comment]
这个问题解决了吗？
