### ISSUE TITLE
[Bug] [connector-elasticsearch] Base on SeaTunnel Engine Cluster Mode, elasticsearch source is not working well

### ISSUE THREAD

**Issue by chaorongzhi** [apache/seatunnel#3811]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Base on SeaTunnel Engine Cluster Mode,I was able to run the following example with idea, then compiled and packaged it and ran it with an error.

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
  job.mode = "BATCH"
}

source {
    Elasticsearch {
        hosts = ["http://localhost:9200"]
        index = "index1"
        schema = {
          fields {
            title = string
            category = string
            price = int
          }
        }
    }
}

transform {
}

sink {
   Console{}
}
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/es2es.conf
```

### Error Exception

```log
2022-12-27 19:44:26,888 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel_default_cluster] [5.1] Task TaskGroupLocation{jobId=660085528888082433, pipelineId=1, taskGroupId=30000} complete with state FAILED
2022-12-27 19:44:26,889 INFO  org.apache.seatunnel.engine.server.dag.physical.PhysicalVertex - Job SeaTunnel (660085528888082433), Pipeline: [(1/1)], task: [Elasticsearch-SourceTask (1/1)] turn to end state FAILED.
2022-12-27 19:44:26,889 ERROR org.apache.seatunnel.engine.server.dag.physical.PhysicalVertex - Job SeaTunnel (660085528888082433), Pipeline: [(1/1)], task: [Elasticsearch-SourceTask (1/1)] end with state FAILED and Exception: java.lang.LinkageError: loader constraint violation: when resolving method "org.apache.seatunnel.common.utils.JsonUtils.parseObject(Ljava/lang/String;)Lcom/fasterxml/jackson/databind/node/ObjectNode;" the class loader (instance of org/apache/seatunnel/engine/common/loader/SeatunnelChildFirstClassLoader) of the current class, org/apache/seatunnel/connectors/seatunnel/elasticsearch/client/EsRestClient, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for the method's defining class, org/apache/seatunnel/common/utils/JsonUtils, have different Class objects for the type com/fasterxml/jackson/databind/node/ObjectNode used in the signature
        at org.apache.seatunnel.connectors.seatunnel.elasticsearch.client.EsRestClient.getDocsFromScrollRequest(EsRestClient.java:204)
        at org.apache.seatunnel.connectors.seatunnel.elasticsearch.client.EsRestClient.searchByScroll(EsRestClient.java:175)
        at org.apache.seatunnel.connectors.seatunnel.elasticsearch.source.ElasticsearchSourceReader.pollNext(ElasticsearchSourceReader.java:80)
        at org.apache.seatunnel.engine.server.task.flow.SourceFlowLifeCycle.collect(SourceFlowLifeCycle.java:115)
        at org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask.collect(SourceSeaTunnelTask.java:68)
        at org.apache.seatunnel.engine.server.task.SeaTunnelTask.stateProcess(SeaTunnelTask.java:157)
        at org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask.call(SourceSeaTunnelTask.java:74)
        at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:357)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

2022-12-27 19:44:26,890 ERROR org.apache.seatunnel.engine.server.dag.physical.SubPlan - Task TaskGroupLocation{jobId=660085528888082433, pipelineId=1, taskGroupId=30000} Failed in Job SeaTunnel (660085528888082433), Pipeline: [(1/1)], Begin to cancel other tasks in this pipeline.
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
This is a bug only appear on seatunnel engine. Cause our seatunnel common use jackson as dependency, and `JsonUtils` and `ObjectNode` will be parent classloader loaded (which AppClassloader), also cause es connector use jackson as dependency, so `ObjectNode` will load use childfirst classloader(which SeaTunnelChildFirstClassloader). The different classloader make this bug happend.
I think we should add jackson into alway parentfirst loader list in `SeatunnelChildFirstClassLoader::DEFAULT_PARENT_FIRST_PATTERNS`. Also support use `seatunnel.yaml` change DEFAULT_PARENT_FIRST_PATTERNS.

**Comment by Carl-Zhou-CN** [comment]
I want to try
