### ISSUE TITLE
[Bug] [Sink] java.net.UnknownHostException

### ISSUE THREAD

**Issue by xiaofan2022** [apache/seatunnel#3895]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Caused by: java.net.UnknownHostException: nameservice1

### SeaTunnel Version

2.3.0

### SeaTunnel Config

```conf
env {
  execution.parallelism = 20
  job.mode = "BATCH"
}

source {
    Jdbc {
        parallelism=20
        url = "jdbc:mysql:host:3306/log"
        driver = "com.mysql.cj.jdbc.Driver"
        connection_check_timeout_sec = 100
        user = ""
        password = ""
        query = "select * from table limit 100 "
        partition_column = "id"
        partition_num = 20
    }
}

transform {

}

sink {
        Hive {
                table_name = "test.log"
                parallelism=10
                metastore_uri = "thrift://master1:9083"
                sink_columns = ["id", "topic"]
          }
}
```

### Running Command

```shell
sh ./bin/seatunnel.sh --config zeta_mysql_hive.conf
```

### Error Exception

```log
Caused by: java.net.UnknownHostException: nameservice1
	at org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:445) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.1-SNAPSHOT]
	at org.apache.hadoop.hdfs.NameNodeProxiesClient.createProxyWithClientProtocol(NameNodeProxiesClient.java:132) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.1-SNAPSHOT]
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:351) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.1-SNAPSHOT]
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:285) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.1-SNAPSHOT]
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:168) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.1-SNAPSHOT]
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3237) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.1-SNAPSHOT]
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:123) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.1-SNAPSHOT]
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3286) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.1-SNAPSHOT]
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3254) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.1-SNAPSHOT]
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:478) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.1-SNAPSHOT]
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:226) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.1-SNAPSHOT]
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:462) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.1-SNAPSHOT]
	at org.apache.seatunnel.connectors.seatunnel.file.sink.util.FileSystemUtils.getFileSystem(FileSystemUtils.java:67) ~[classes/:?]
	at org.apache.seatunnel.connectors.seatunnel.file.sink.util.FileSystemUtils.getOutputStream(FileSystemUtils.java:73) ~[classes/:?]
	at org.apache.seatunnel.connectors.seatunnel.file.sink.writer.TextWriteStrategy.getOrCreateOutputStream(TextWriteStrategy.java:114) ~[classes/:?]
	at org.apache.seatunnel.connectors.seatunnel.file.sink.writer.TextWriteStrategy.write(TextWriteStrategy.java:75) ~[classes/:?]
	at org.apache.seatunnel.connectors.seatunnel.file.sink.BaseFileSinkWriter.write(BaseFileSinkWriter.java:108) ~[classes/:?]
	at org.apache.seatunnel.connectors.seatunnel.file.sink.BaseFileSinkWriter.write(BaseFileSinkWriter.java:43) ~[classes/:?]
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:161) ~[classes/:?]
	... 15 more
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TyrantLucifer** [comment]
Add `hdfs_site_path` configuration in hive plugin.

**Comment by xiaofan2022** [comment]
hdfs_site_path is supported in hive sink？

**Comment by TyrantLucifer** [comment]
> hdfs_site_path is supported in hive sink？

yup.

**Comment by LIXINING0518** [comment]
I also appear this problem, can you provide configuration hdfs-site.xml?

![image](https://user-images.githubusercontent.com/73978113/228186664-59fc8fcd-ce9a-4225-a420-c574bd316a59.png)

![image](https://user-images.githubusercontent.com/73978113/228186828-2211f97a-21c4-476c-bfa4-8cb3cda18d7a.png)

**Comment by LIXINING0518** [comment]
> 我也出现了这个问题，你能提供配置hdfs-site.xml吗？


env {
  job.mode = "BATCH"
  #execution.checkpoint.interval = 10000
  #execution.checkpoint.data-uri = "hdfs://hdfscluster:9000/checkpoint"
}
 
source {
    Jdbc {
        url = "jdbc:mysql://10.3.7.226/wisdom_microhabitat?serverTimezone=GMT%2b8"
        driver = "com.mysql.cj.jdbc.Driver"
        user = "root"
        password = "123456"
        query = "select * from microhabitat_total_2022"
    }
}
 
transform {
}
 
sink {
  Hive {
    table_name = "default.microhabitat_total_2022"
    metastore_uri = "thrift://10.3.6.24:9083"
  }
 
}

**Comment by taodejin** [comment]
env {
  # You can set flink configuration here
  parallelism = 3
  job.name="test_hive_source_to_hive"
}

source {
  Hive {
    table_name = "default.flink_test"
    metastore_uri = "thrift://10.251.181.13:9083"
  }
}

sink {
  # choose stdout output plugin to output data to console

  Hive {
    table_name = "default.datax_test"
    metastore_uri = "thrift://10.251.181.13:9083"
  }
}

I also encountered this problem, how to solve it？

**Comment by HSLife1991** [comment]
the error "java.net.UnknownHostException" happened again, i configured checkpoint-storage parameter in seatunnel.yaml for checkpoint-storage config, but it met this error when i trigger hive task.

hdfs://fmxprod is the fs.defaultFS in hdfs core-site config, but my seatunnel config is like this:

seatunnel:
  engine:
    history-job-expire-minutes: 1440
    backup-count: 1
    queue-type: blockingqueue
    print-execution-info-interval: 60
    print-job-metrics-info-interval: 60
    slot-service:
      dynamic-slot: true
    checkpoint:
      interval: 10000
      timeout: 60000
      storage:
        type: hdfs
        max-retained: 3
        plugin-config:
          namespace: /tmp/seatunnel/checkpoint_snapshot
          storage.type: hdfs
          fs.defaultFS: hdfs://bc-gcp-sg-node01.internal:8020


Error info:
org.apache.seatunnel.connectors.seatunnel.file.source.reader.AbstractReadStrategy.getFileNamesByPath(AbstractReadStrategy.java:127)
		at org.apache.seatunnel.connectors.seatunnel.file.hdfs.source.BaseHdfsFileSource.prepare(BaseHdfsFileSource.java:76)
		at org.apache.seatunnel.connectors.seatunnel.hive.source.HiveSource.prepare(HiveSource.java:176)
		at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSource(JobConfigParser.java:85)
		at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:317)
		at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:179)
		at org.apache.seatunnel.engine.core.job.AbstractJobEnvironment.getLogicalDag(AbstractJobEnvironment.java:109)
		at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:73)
		at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:143)
		... 2 more
	Caused by: java.net.UnknownHostException: fmxprod
