### ISSUE TITLE
[Bug] Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: Writing job aborted.

### ISSUE THREAD

**Issue by hanyujunsir** [apache/seatunnel#3905]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Configuration file :
env {
  execution.parallelism = 2
  job.mode = "BATCH"
}

source {
  Hive {

        table_name = "ads_yunpos.ads_yunpos_data_overview_month"
        metastore_uri = "thrift://"
  }
}

transform {
  sql {
    sql = "select * from ads_yunpos.ads_yunpos_data_overview_month"
  }
}
sink {
  Clickhouse {
    host = ""
    database = "ads_yunpos"
    table = "ads_yunpos_data_overview_month5"
    fields = ["first_p", "second_p", "seq", "cnt", "brand", "busi_type", "ym"]
    username = "default"
    password = ""
    bulk_size = 20000
  }
}
Execute the startup command and report an error.

### SeaTunnel Version

2.3.0

### SeaTunnel Config

```conf
Configuration file :
env {
  execution.parallelism = 2
  job.mode = "BATCH"
}

source {
  Hive {

        table_name = "ads_yunpos.ads_yunpos_data_overview_month"
        metastore_uri = ""
  }
}

transform {
  sql {
    sql = "select * from ads_yunpos.ads_yunpos_data_overview_month"
  }
}
sink {
  Clickhouse {
    host = ""
    database = "ads_yunpos"
    table = "ads_yunpos_data_overview_month5"
    fields = ["first_p", "second_p", "seq", "cnt", "brand", "busi_type", "ym"]
    username = "default"
    password = ""
    bulk_size = 20000
  }
}
```

### Running Command

```shell
./bin/start-seatunnel-spark-connector-v2.sh \
--master local[4] \
--deploy-mode client \
--config ./config/spark.streaming.conf.template2
```

### Error Exception

```log
Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: Writing job aborted
```

### Flink or Spark Version

spark : 2.3.3

### Java or Scala Version

java8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TyrantLucifer** [comment]
2.3.0 does not support spark 2.3.x, please use 2.4.x instead of and try again.

**Comment by seayij** [comment]
2023-05-18 17:17:38,239 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Fatal Error, 

2023-05-18 17:17:38,239 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Please submit bug report in https://github.com/apache/incubator-seatunnel/issues

2023-05-18 17:17:38,239 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Reason:SeaTunnel job executed failed 

2023-05-18 17:17:38,240 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:181)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: java.lang.NullPointerException
        at org.apache.seatunnel.connectors.seatunnel.tdengine.typemapper.TDengineTypeMapper.mapping(TDengineTypeMapper.java:85)
        at org.apache.seatunnel.connectors.seatunnel.tdengine.source.TDengineSource.getSTableMetaInfo(TDengineSource.java:115)
        at org.apache.seatunnel.connectors.seatunnel.tdengine.source.TDengineSource.prepare(TDengineSource.java:92)
        at org.apache.seatunnel.engine.core.parse.ConnectorInstanceLoader.loadSourceInstance(ConnectorInstanceLoader.java:64)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.sampleAnalyze(JobConfigParser.java:371)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.parse(JobConfigParser.java:132)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:112)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.getLogicalDag(JobExecutionEnvironment.java:155)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:147)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:140)
        ... 2 more
### 同步TDengine数据出现的错误是什么原因``
