### ISSUE TITLE
[Bug] [Zeta] A checkpoint exception may be thrown when the active cancel task terminates with an exception

### ISSUE THREAD

**Issue by liugddx** [apache/seatunnel#3914]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

A checkpoint exception may be thrown when the active cancel task terminates with an exception.

```
java.lang.NullPointerException: null
	at org.apache.seatunnel.engine.server.checkpoint.operation.CheckpointFinishedOperation.lambda$run$0(CheckpointFinishedOperation.java:82) ~[seatunnel-engine-server-2.3.1-SNAPSHOT-2.11.12.jar:2.3.1-SNAPSHOT]
	at org.apache.seatunnel.common.utils.RetryUtils.retryWithException(RetryUtils.java:47) ~[seatunnel-common-2.3.1-SNAPSHOT-2.11.12.jar:2.3.1-SNAPSHOT]
	at org.apache.seatunnel.engine.server.checkpoint.operation.CheckpointFinishedOperation.run(CheckpointFinishedOperation.java:79) ~[seatunnel-engine-server-2.3.1-SNAPSHOT-2.11.12.jar:2.3.1-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) ~[hazelcast-5.1.jar:5.1]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:273) ~[hazelcast-5.1.jar:5.1] ```

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
-
```

### Running Command

```shell
-
```

### Error Exception

```log
java.lang.NullPointerException: null
	at org.apache.seatunnel.engine.server.checkpoint.operation.CheckpointFinishedOperation.lambda$run$0(CheckpointFinishedOperation.java:82) ~[seatunnel-engine-server-2.3.1-SNAPSHOT-2.11.12.jar:2.3.1-SNAPSHOT]
	at org.apache.seatunnel.common.utils.RetryUtils.retryWithException(RetryUtils.java:47) ~[seatunnel-common-2.3.1-SNAPSHOT-2.11.12.jar:2.3.1-SNAPSHOT]
	at org.apache.seatunnel.engine.server.checkpoint.operation.CheckpointFinishedOperation.run(CheckpointFinishedOperation.java:79) ~[seatunnel-engine-server-2.3.1-SNAPSHOT-2.11.12.jar:2.3.1-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) ~[hazelcast-5.1.jar:5.1]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:273) ~[hazelcast-5.1.jar:5.1]


2023-01-10 07:02:59,915 WARN  org.apache.seatunnel.engine.server.master.JobMaster - Job testStreamJobRestoreIn3NodeMasterDown (665088045128613889), Pipeline: [(1/1)] checkpoint have error, cancel the pipeline
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
https://github.com/apache/incubator-seatunnel/actions/runs/3880896087/jobs/6619393675
