### ISSUE TITLE
[Bug] [seatunnel-connectors-v2] when I use connector-cdc-mysql to read mysql-bin data,a ClassCastException error is reported

### ISSUE THREAD

**Issue by hanyuncai** [apache/seatunnel#3929]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

java.lang.RuntimeException: SplitFetcher thread 0 received unexpected exception while polling the records
        at org.apache.seatunnel.connectors.seatunnel.common.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:166)
        at org.apache.seatunnel.connectors.seatunnel.common.source.reader.fetcher.SplitFetcher.run(SplitFetcher.java:82)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: io.debezium.relational.TableId cannot be cast to io.debezium.relational.TableId
        at org.apache.seatunnel.connectors.seatunnel.cdc.mysql.source.MySqlDialect.createFetchTaskContext(MySqlDialect.java:121)
        at org.apache.seatunnel.connectors.seatunnel.cdc.mysql.source.MySqlDialect.createFetchTaskContext(MySqlDialect.java:54)
        at org.apache.seatunnel.connectors.cdc.base.source.reader.IncrementalSourceSplitReader.checkSplitOrStartNext(IncrementalSourceSplitReader.java:132)
        at org.apache.seatunnel.connectors.cdc.base.source.reader.IncrementalSourceSplitReader.fetch(IncrementalSourceSplitReader.java:64)
        at org.apache.seatunnel.connectors.seatunnel.common.source.reader.fetcher.FetchTask.run(FetchTask.java:53)
        at org.apache.seatunnel.connectors.seatunnel.common.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:163)
        ... 6 more

### SeaTunnel Version

seatunnel=2.3.0

### SeaTunnel Config

```conf
env{
  execution.parallelism=1
  job.mode = "STREAMING"
  job.name = "seatunnel-mysql-cdc"
  jars = "/opt/servers/seatunnel-2.3.0/connectors/seatunnel/connector-cdc-mysql-2.3.0.jar"
  checkpoint.interval = 1000
}

source {
  MySQL-CDC {
    result_table_name = "mysql-cdc"
    parallelism = 1
    server-id = 5656
    port = 3306
    hostname = "xxx.xxx.xxx.xx"
    username = "kingshardadmin"
    password = "***********"
    database-name = "test"
    table-name = "table1"
    base-url = "jdbc:mysql://xxx.xxx.xxx.xx:3306"
    startup.mode = "INITIAL"
    stop.mode = "NEVER"
#   server-time-zone = "UTC+8"
  }
}

transform{

}
sink{
   console{
   }
}
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/example/streaming/mysql_cdc_to_console.template -e local
```

### Error Exception

```log
[MySQL-CDC-SourceTask (1/1)] end with state FAILED and Exception: java.lang.RuntimeException: One or more fetchers have encountered exception
        at org.apache.seatunnel.connectors.seatunnel.common.source.reader.fetcher.SplitFetcherManager.checkErrors(SplitFetcherManager.java:143)
        at org.apache.seatunnel.connectors.seatunnel.common.source.reader.SourceReaderBase.getNextFetch(SourceReaderBase.java:155)
        at org.apache.seatunnel.connectors.seatunnel.common.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:91)
        at org.apache.seatunnel.connectors.cdc.base.source.reader.IncrementalSourceReader.pollNext(IncrementalSourceReader.java:94)
        at org.apache.seatunnel.engine.server.task.flow.SourceFlowLifeCycle.collect(SourceFlowLifeCycle.java:115)
        at org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask.collect(SourceSeaTunnelTask.java:68)
        at org.apache.seatunnel.engine.server.task.SeaTunnelTask.stateProcess(SeaTunnelTask.java:157)
        at org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask.call(SourceSeaTunnelTask.java:74)
        at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:357)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: SplitFetcher thread 0 received unexpected exception while polling the records
        at org.apache.seatunnel.connectors.seatunnel.common.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:166)
        at org.apache.seatunnel.connectors.seatunnel.common.source.reader.fetcher.SplitFetcher.run(SplitFetcher.java:82)
        ... 5 more
Caused by: java.lang.ClassCastException: io.debezium.relational.TableId cannot be cast to io.debezium.relational.TableId
        at org.apache.seatunnel.connectors.seatunnel.cdc.mysql.source.MySqlDialect.createFetchTaskContext(MySqlDialect.java:121)
        at org.apache.seatunnel.connectors.seatunnel.cdc.mysql.source.MySqlDialect.createFetchTaskContext(MySqlDialect.java:54)
        at org.apache.seatunnel.connectors.cdc.base.source.reader.IncrementalSourceSplitReader.checkSplitOrStartNext(IncrementalSourceSplitReader.java:132)
        at org.apache.seatunnel.connectors.cdc.base.source.reader.IncrementalSourceSplitReader.fetch(IncrementalSourceSplitReader.java:64)
        at org.apache.seatunnel.connectors.seatunnel.common.source.reader.fetcher.FetchTask.run(FetchTask.java:53)
        at org.apache.seatunnel.connectors.seatunnel.common.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:163)
        ... 6 more
```

### Flink or Spark Version

flink=1.13.0
spark=2.3.0

### Java or Scala Version

java=1.8
scala=2.11.12

### Screenshots

![image](https://user-images.githubusercontent.com/59333569/212026587-f2edf7e6-7460-4f2e-94fb-edd3358e803a.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 2000liux** [comment]
please assigner to me. I try to solve this problem。

**Comment by sunnyzhuzhu** [comment]
Hi ~ This bug maybe fixed in dev branch code. I have found this problem in version 2.3.0, but this question not appears in dev code. @hanyuncai

**Comment by TyrantLucifer** [comment]
Bug is fixed, if you have any problems with this, please reopen it and discuss with community.

**Comment by simonChen0317** [comment]
2.3.0 still has this bug

**Comment by simonChen0317** [comment]
@TyrantLucifer  fix in 2.3.0？

**Comment by javaonepiece** [comment]
2.3.0确实还有这个bug

**Comment by simonChen0317** [comment]
@TyrantLucifer how fix it？

**Comment by TyrantLucifer** [comment]
dev branch, 2.3.1 release.

**Comment by simonChen0317** [comment]
@TyrantLucifer noe found dev branch, 2.3.1 release.。 is  2.3.0-release branch？ has builded tar.gz？

**Comment by TyrantLucifer** [comment]
> @TyrantLucifer noe found dev branch, 2.3.1 release.。 is 2.3.0-release branch？ has builded tar.gz？
2.3.1 has not be released. You can build the dev branch by yourself.

**Comment by zhangzhangzhangzy** [comment]
java.lang.ClassCastException: cannot assign instance of io.debezium.relational.TableId to field org.apache.seatunnel.connectors.cdc.base.source.split.SnapshotSplit.tableId of type io.debezium.relational.TableId in instance of org.apache.seatunnel.connectors.cdc.base.source.split.SnapshotSplit
	at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2301) ~[?:1.8.0_352]
	at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1431) ~[?:1.8.0_352]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2436) ~[?:1.8.0_352]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2354) ~[?:1.8.0_352]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2212) ~[?:1.8.0_352]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1668) ~[?:1.8.0_352]
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:2118) ~[?:1.8.0_352]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1656) ~[?:1.8.0_352]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:502) ~[?:1.8.0_352]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:460) ~[?:1.8.0_352]
	at org.apache.seatunnel.common.utils.SerializationUtils.deserialize(SerializationUtils.java:91) ~[seatunnel-starter.jar:2.3.0]
	at org.apache.seatunnel.engine.server.task.operation.source.AssignSplitOperation.lambda$run$1(AssignSplitOperation.java:57) ~[seatunnel-starter.jar:2.3.0]
	at org.apache.seatunnel.common.utils.RetryUtils.retryWithException(RetryUtils.java:47) ~[seatunnel-starter.jar:2.3.0]
	at org.apache.seatunnel.engine.server.task.operation.source.AssignSplitOperation.run(AssignSplitOperation.java:54) ~[seatunnel-starter.jar:2.3.0]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) [seatunnel-starter.jar:2.3.0]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:273) [seatunnel-starter.jar:2.3.0]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) [seatunnel-starter.jar:2.3.0]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213) [seatunnel-starter.jar:2.3.0]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:411) [seatunnel-starter.jar:2.3.0]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:438) [seatunnel-starter.jar:2.3.0]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:601) [seatunnel-starter.jar:2.3.0]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:580) [seatunnel-starter.jar:2.3.0]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:541) [seatunnel-starter.jar:2.3.0]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:241) [seatunnel-starter.jar:2.3.0]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:61) [seatunnel-starter.jar:2.3.0]
	at org.apache.seatunnel.engine.server.utils.NodeEngineUtil.sendOperationToMemberNode(NodeEngineUtil.java:40) [seatunnel-starter.jar:2.3.0]
	at org.apache.seatunnel.engine.server.execution.TaskExecutionContext.sendToMember(TaskExecutionContext.java:43) [seatunnel-starter.jar:2.3.0]
	at org.apache.seatunnel.engine.server.task.context.SeaTunnelSplitEnumeratorContext.assignSplit(SeaTunnelSplitEnumeratorContext.java:55) [seatunnel-starter.jar:2.3.0]
	at org.apache.seatunnel.api.source.SourceSplitEnumerator$Context.assignSplit(SourceSplitEnumerator.java:104) [seatunnel-starter.jar:2.3.0]
	at org.apache.seatunnel.connectors.cdc.base.source.enumerator.IncrementalSourceEnumerator.assignSplits(IncrementalSourceEnumerator.java:160) [connector-cdc-mysql-2.3.0.jar:2.3.0]
	at org.apache.seatunnel.connectors.cdc.base.source.enumerator.IncrementalSourceEnumerator.run(IncrementalSourceEnumerator.java:72) [connector-cdc-mysql-2.3.0.jar:2.3.0]
	at org.apache.seatunnel.engine.server.task.SourceSplitEnumeratorTask.stateProcess(SourceSplitEnumeratorTask.java:239) [seatunnel-starter.jar:2.3.0]
	at org.apache.seatunnel.engine.server.task.SourceSplitEnumeratorTask.call(SourceSplitEnumeratorTask.java:124) [seatunnel-starter.jar:2.3.0]
	at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:357) [seatunnel-starter.jar:2.3.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_352]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_352]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_352]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_352]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]

**Comment by zhangzhangzhangzy** [comment]
java.lang.ClassCastException: cannot assign instance of io.debezium.relational.TableId to field org.apache.seatunnel.connectors.cdc.base.source.split.SnapshotSplit.tableId of type io.debezium.relational.TableId in instance of org.apache.seatunnel.connectors.cdc.base.source.split.SnapshotSplit
	at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2301) ~[?:1.8.0_352]
	at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1431) ~[?:1.8.0_352]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2436) ~[?:1.8.0_352]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2354) ~[?:1.8.0_352]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2212) ~[?:1.8.0_352]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1668) ~[?:1.8.0_352]
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:2118) ~[?:1.8.0_352]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1656) ~[?:1.8.0_352]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:502) ~[?:1.8.0_352]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:460) ~[?:1.8.0_352]
	at org.apache.seatunnel.common.utils.SerializationUtils.deserialize(SerializationUtils.java:91) ~[seatunnel-starter.jar:2.3.0]
	at org.apache.seatunnel.engine.server.task.operation.source.AssignSplitOperation.lambda$run$1(AssignSplitOperation.java:57) ~[seatunnel-starter.jar:2.3.0]
	at org.apache.seatunnel.common.utils.RetryUtils.retryWithException(RetryUtils.java:47) ~[seatunnel-starter.jar:2.3.0]
	at org.apache.seatunnel.engine.server.task.operation.source.AssignSplitOperation.run(AssignSplitOperation.java:54) ~[seatunnel-starter.jar:2.3.0]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) [seatunnel-starter.jar:2.3.0]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:273) [seatunnel-starter.jar:2.3.0]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) [seatunnel-starter.jar:2.3.0]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213) [seatunnel-starter.jar:2.3.0]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:411) [seatunnel-starter.jar:2.3.0]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:438) [seatunnel-starter.jar:2.3.0]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:601) [seatunnel-starter.jar:2.3.0]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:580) [seatunnel-starter.jar:2.3.0]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:541) [seatunnel-starter.jar:2.3.0]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:241) [seatunnel-starter.jar:2.3.0]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:61) [seatunnel-starter.jar:2.3.0]
	at org.apache.seatunnel.engine.server.utils.NodeEngineUtil.sendOperationToMemberNode(NodeEngineUtil.java:40) [seatunnel-starter.jar:2.3.0]
	at org.apache.seatunnel.engine.server.execution.TaskExecutionContext.sendToMember(TaskExecutionContext.java:43) [seatunnel-starter.jar:2.3.0]
	at org.apache.seatunnel.engine.server.task.context.SeaTunnelSplitEnumeratorContext.assignSplit(SeaTunnelSplitEnumeratorContext.java:55) [seatunnel-starter.jar:2.3.0]
	at org.apache.seatunnel.api.source.SourceSplitEnumerator$Context.assignSplit(SourceSplitEnumerator.java:104) [seatunnel-starter.jar:2.3.0]
	at org.apache.seatunnel.connectors.cdc.base.source.enumerator.IncrementalSourceEnumerator.assignSplits(IncrementalSourceEnumerator.java:160) [connector-cdc-mysql-2.3.0.jar:2.3.0]
	at org.apache.seatunnel.connectors.cdc.base.source.enumerator.IncrementalSourceEnumerator.run(IncrementalSourceEnumerator.java:72) [connector-cdc-mysql-2.3.0.jar:2.3.0]
	at org.apache.seatunnel.engine.server.task.SourceSplitEnumeratorTask.stateProcess(SourceSplitEnumeratorTask.java:239) [seatunnel-starter.jar:2.3.0]
	at org.apache.seatunnel.engine.server.task.SourceSplitEnumeratorTask.call(SourceSplitEnumeratorTask.java:124) [seatunnel-starter.jar:2.3.0]
	at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:357) [seatunnel-starter.jar:2.3.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_352]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_352]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_352]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_352]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]

**Comment by feng01world** [comment]
also blocked by this issue in 2.3.0 for mysql cdc.  I decide to build it from source code of 2.3.1 SNAPSHOT

**Comment by feng01world** [comment]
![image](https://user-images.githubusercontent.com/36727453/225871965-777d1b39-bd4b-4193-9307-d1fdc13d0802.png)

![image](https://user-images.githubusercontent.com/36727453/225873352-286d1487-fe69-47a4-b696-84b283629891.png)


![image](https://user-images.githubusercontent.com/36727453/225873283-41266d6a-aad4-4dc0-aafd-10d7c011ff33.png)


I have realized it successfully with 2.31-SNAPTSHOT. /

some problems solved:
1. make sure mysql bin log format is ROW mode.
2. grant some super priviledges to the mysql account configed in the seatunnel config file. if not correct, you can find the notification from the seatunnel log.

**Comment by sangeetha1706** [comment]
> ![image](https://user-images.githubusercontent.com/36727453/225871965-777d1b39-bd4b-4193-9307-d1fdc13d0802.png)
> 
> ![image](https://user-images.githubusercontent.com/36727453/225873352-286d1487-fe69-47a4-b696-84b283629891.png)
> 
> ![image](https://user-images.githubusercontent.com/36727453/225873283-41266d6a-aad4-4dc0-aafd-10d7c011ff33.png)
> 
> I have realized it successfully with 2.31-SNAPTSHOT. /
> 
> some problems solved:
> 
> 1. make sure mysql bin log format is ROW mode.
> 2. grant some super priviledges to the mysql account configed in the seatunnel config file. if not correct, you can find the notification from the seatunnel log.

when im updating the source table im not getting seatunnelRow#kind=update

**Comment by fengcheche** [comment]
2.3.3还有这个错误
![image](https://github.com/apache/seatunnel/assets/7406807/6b6549fb-e8d2-4651-8862-f14ac98abe1b)

**Comment by itfuyun** [comment]
![image](https://github.com/apache/seatunnel/assets/30425030/81d76443-d820-4335-b670-9e7be06d2391)
我用的2.3.3版本 也一直这个错误

**Comment by pietiaonan** [comment]
> ![image](https://private-user-images.githubusercontent.com/30425030/297576896-81d76443-d820-4335-b670-9e7be06d2391.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMzk3MDEsIm5iZiI6MTcwODIzOTQwMSwicGF0aCI6Ii8zMDQyNTAzMC8yOTc1NzY4OTYtODFkNzY0NDMtZDgyMC00MzM1LWI2NzAtOWU3YmUwNmQyMzkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDA2NTY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4MzFlYjU0M2RlYTZlZGQzNWNhZGVhN2FiYzllNzc2N2Q3MjZhMjIzZGE1Y2ZiZTRiYjg4NTc5NzgzMWNiOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0PvL5CY5xXNPvRp9N80JEi9DROd8-MtBQd8o2s4anTw) 我用的2.3.3版本 也一直这个错误

我也一直报这个错误，请问解决了吗

**Comment by yangwan216** [comment]
2.3.3版本中还是有这个错误，看前面的回复说2.3.1已经解决？
<img width="1517" alt="截屏2024-04-22 15 01 42" src="https://github.com/apache/seatunnel/assets/132556068/86812b4a-2360-4bd0-ab95-ae1c48cd4558">

**Comment by simonChen0317** [comment]
我也不太清楚，不知道是否解决发自我的手机-------- 原始邮件 --------发件人： Angel Yang ***@***.***>日期： 2024年4月22日周一 15:02收件人： apache/seatunnel ***@***.***>抄送： simonChen0317 ***@***.***>, Comment ***@***.***>主    题： Re: [apache/seatunnel] [Bug] [seatunnel-connectors-v2] when I use connector-cdc-mysql to read mysql-bin data,a ClassCastException error is reported (Issue #3929)
2.3.3版本中还是有这个错误，看前面的回复说2.3.1已经解决？
2024-04-22.15.01.42.png (view on web)

**Comment by gmlworld** [comment]
按网上的教程部署中，有一步操作是将 connnect下的jar包拷贝到lib目录下，使用sh脚本启动的时候加载了两份相同的jar，导致了对象冲突。删除lib中拷贝过去的connect-*.jar 就没问题了。
