### ISSUE TITLE
[Bug] seatunnel run with flink operator error

### ISSUE THREAD

**Issue by voidking** [apache/seatunnel#3998]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

[Flink operator 1.3.1](https://nightlies.apache.org/flink/flink-kubernetes-operator-docs-main/docs/try-flink-kubernetes-operator/quick-start/) worked fine.    
As I followed the [seatunnel document](https://seatunnel.apache.org/docs/2.3.0/start-v2/kubernetes/) to run seatunnel demo, the error was accur after excute `kubectl logs -f deploy/seatunnel-flink-streaming-example`.
```
2023-01-30 03:37:22,704 ERROR org.apache.seatunnel.core.starter.Seatunnel                  [] - Fatal Error,

2023-01-30 03:37:22,704 ERROR org.apache.seatunnel.core.starter.Seatunnel                  [] - Please submit bug report in https://github.com/apache/incubator-seatunnel/issues

2023-01-30 03:37:22,704 ERROR org.apache.seatunnel.core.starter.Seatunnel                  [] - Reason:Plugin PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='FakeSourceStream'} not found.

2023-01-30 03:37:22,706 ERROR org.apache.seatunnel.core.starter.Seatunnel                  [] - Exception StackTrace:java.lang.RuntimeException: Plugin PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='FakeSourceStream'} not found.
	at org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery.createPluginInstance(AbstractPluginDiscovery.java:137)
	at org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery.createPluginInstance(AbstractPluginDiscovery.java:99)
	at org.apache.seatunnel.core.starter.flink.execution.SourceExecuteProcessor.initializePlugins(SourceExecuteProcessor.java:117)
	at org.apache.seatunnel.core.starter.flink.execution.AbstractPluginExecuteProcessor.<init>(AbstractPluginExecuteProcessor.java:56)
	at org.apache.seatunnel.core.starter.flink.execution.SourceExecuteProcessor.<init>(SourceExecuteProcessor.java:59)
	at org.apache.seatunnel.core.starter.flink.execution.FlinkExecution.<init>(FlinkExecution.java:59)
	at org.apache.seatunnel.core.starter.flink.command.FlinkApiTaskExecuteCommand.execute(FlinkApiTaskExecuteCommand.java:51)
	at org.apache.seatunnel.core.starter.Seatunnel.run(Seatunnel.java:39)
	at org.apache.seatunnel.core.starter.flink.SeatunnelFlink.main(SeatunnelFlink.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222)
	at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114)
	at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.runApplicationEntryPoint(ApplicationDispatcherBootstrap.java:242)
	at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.lambda$runApplicationAsync$1(ApplicationDispatcherBootstrap.java:212)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.flink.runtime.concurrent.akka.ActorSystemScheduledExecutorAdapter$ScheduledFutureTask.run(ActorSystemScheduledExecutorAdapter.java:159)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
``` 

[seatunnel.log](https://github.com/voidking/hexo-storage/blob/main/k8s-seatunnel/seatunnel.log)

### FlinkDeployment
```yaml
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: seatunnel-flink-streaming-example
spec:
  image: seatunnel:2.3.0-beta-flink-1.13
  flinkVersion: v1_13
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
  serviceAccount: flink
  jobManager:
    replicas: 1
    resource:
      memory: "1024m"
      cpu: 1
  taskManager:
    resource:
      memory: "1024m"
      cpu: 1
  podTemplate:
    spec:
      containers:
        - name: flink-main-container
          volumeMounts:
            - name: seatunnel-config
              mountPath: /data/flink.streaming.conf
              subPath: flink.streaming.conf
      volumes:
        - name: seatunnel-config
          configMap:
            name: seatunnel-config
            items:
            - key: flink.streaming.conf
              path: flink.streaming.conf
  job:
    jarURI: local:///opt/seatunnel/lib/seatunnel-flink-starter.jar
    entryClass: org.apache.seatunnel.core.starter.flink.SeatunnelFlink
    args: ["--config", "/data/flink.streaming.conf"]
    parallelism: 2
    upgradeMode: stateless
```

### Dockerfile
```
FROM flink:1.13

ENV SEATUNNEL_VERSION="2.3.0-beta"
ENV SEATUNNEL_HOME="/opt/seatunnel"

RUN mkdir -p $SEATUNNEL_HOME

RUN wget https://archive.apache.org/dist/incubator/seatunnel/${SEATUNNEL_VERSION}/apache-seatunnel-incubating-${SEATUNNEL_VERSION}-bin.tar.gz
RUN tar -xzvf apache-seatunnel-incubating-${SEATUNNEL_VERSION}-bin.tar.gz

RUN cp -r apache-seatunnel-incubating-${SEATUNNEL_VERSION}/* $SEATUNNEL_HOME/
RUN rm -rf apache-seatunnel-incubating-${SEATUNNEL_VERSION}*
RUN rm -rf $SEATUNNEL_HOME/connectors/seatunnel
```

### SeaTunnel Version

2.3.0-beta

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
}

source {
  FakeSourceStream {
    result_table_name = "fake"
    field_name = "name,age"
  }
}

transform {
  sql {
    sql = "select name,age from fake"
  }
}

sink {
  ConsoleSink {}
}
```

### Running Command

```shell
kubectl apply -f flink-deployment.yaml -n flink-operator
```

### Error Exception

```log
2023-01-30 03:37:22,704 ERROR org.apache.seatunnel.core.starter.Seatunnel                  [] - Fatal Error,

2023-01-30 03:37:22,704 ERROR org.apache.seatunnel.core.starter.Seatunnel                  [] - Please submit bug report in https://github.com/apache/incubator-seatunnel/issues

2023-01-30 03:37:22,704 ERROR org.apache.seatunnel.core.starter.Seatunnel                  [] - Reason:Plugin PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='FakeSourceStream'} not found.

2023-01-30 03:37:22,706 ERROR org.apache.seatunnel.core.starter.Seatunnel                  [] - Exception StackTrace:java.lang.RuntimeException: Plugin PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='FakeSourceStream'} not found.
	at org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery.createPluginInstance(AbstractPluginDiscovery.java:137)
	at org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery.createPluginInstance(AbstractPluginDiscovery.java:99)
	at org.apache.seatunnel.core.starter.flink.execution.SourceExecuteProcessor.initializePlugins(SourceExecuteProcessor.java:117)
	at org.apache.seatunnel.core.starter.flink.execution.AbstractPluginExecuteProcessor.<init>(AbstractPluginExecuteProcessor.java:56)
	at org.apache.seatunnel.core.starter.flink.execution.SourceExecuteProcessor.<init>(SourceExecuteProcessor.java:59)
	at org.apache.seatunnel.core.starter.flink.execution.FlinkExecution.<init>(FlinkExecution.java:59)
	at org.apache.seatunnel.core.starter.flink.command.FlinkApiTaskExecuteCommand.execute(FlinkApiTaskExecuteCommand.java:51)
	at org.apache.seatunnel.core.starter.Seatunnel.run(Seatunnel.java:39)
	at org.apache.seatunnel.core.starter.flink.SeatunnelFlink.main(SeatunnelFlink.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222)
	at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114)
	at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.runApplicationEntryPoint(ApplicationDispatcherBootstrap.java:242)
	at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.lambda$runApplicationAsync$1(ApplicationDispatcherBootstrap.java:212)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.flink.runtime.concurrent.akka.ActorSystemScheduledExecutorAdapter$ScheduledFutureTask.run(ActorSystemScheduledExecutorAdapter.java:159)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

### Flink or Spark Version

flink version 1.13

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
Use version 2.3.0

**Comment by voidking** [comment]
After change version to 2.3.0, it report the following error.   
I think the entrypoint jar or class has been changed from 2.3.0-beta. What is the right entrypoint for 2.3.0?
```
org.apache.flink.util.FlinkException: Could not load the provided entrypoint class.
	at org.apache.flink.client.deployment.application.ClassPathPackagedProgramRetriever.getPackagedProgram(ClassPathPackagedProgramRetriever.java:178) ~[flink-dist_2.12-1.13.6.jar:1.13.6]
	at org.apache.flink.kubernetes.entrypoint.KubernetesApplicationClusterEntrypoint.getPackagedProgram(KubernetesApplicationClusterEntrypoint.java:101) ~[flink-dist_2.12-1.13.6.jar:1.13.6]
	at org.apache.flink.kubernetes.entrypoint.KubernetesApplicationClusterEntrypoint.main(KubernetesApplicationClusterEntrypoint.java:71) [flink-dist_2.12-1.13.6.jar:1.13.6]
Caused by: org.apache.flink.client.program.ProgramInvocationException: JAR file does not exist '/opt/seatunnel/lib/seatunnel-flink-starter.jar'
	at org.apache.flink.client.program.PackagedProgram.checkJarFile(PackagedProgram.java:617) ~[flink-dist_2.12-1.13.6.jar:1.13.6]
	at org.apache.flink.client.program.PackagedProgram.loadJarFile(PackagedProgram.java:465) ~[flink-dist_2.12-1.13.6.jar:1.13.6]
	at org.apache.flink.client.program.PackagedProgram.<init>(PackagedProgram.java:135) ~[flink-dist_2.12-1.13.6.jar:1.13.6]
	at org.apache.flink.client.program.PackagedProgram.<init>(PackagedProgram.java:65) ~[flink-dist_2.12-1.13.6.jar:1.13.6]
	at org.apache.flink.client.program.PackagedProgram$Builder.build(PackagedProgram.java:691) ~[flink-dist_2.12-1.13.6.jar:1.13.6]
	at org.apache.flink.client.deployment.application.ClassPathPackagedProgramRetriever.getPackagedProgram(ClassPathPackagedProgramRetriever.java:167) ~[flink-dist_2.12-1.13.6.jar:1.13.6]
	... 2 more
Caused by: java.io.IOException: JAR file does not exist '/opt/seatunnel/lib/seatunnel-flink-starter.jar'
	at org.apache.flink.util.JarUtils.checkJarFile(JarUtils.java:46) ~[flink-dist_2.12-1.13.6.jar:1.13.6]
	at org.apache.flink.client.program.PackagedProgram.checkJarFile(PackagedProgram.java:615) ~[flink-dist_2.12-1.13.6.jar:1.13.6]
	at org.apache.flink.client.program.PackagedProgram.loadJarFile(PackagedProgram.java:465) ~[flink-dist_2.12-1.13.6.jar:1.13.6]
	at org.apache.flink.client.program.PackagedProgram.<init>(PackagedProgram.java:135) ~[flink-dist_2.12-1.13.6.jar:1.13.6]
	at org.apache.flink.client.program.PackagedProgram.<init>(PackagedProgram.java:65) ~[flink-dist_2.12-1.13.6.jar:1.13.6]
	at org.apache.flink.client.program.PackagedProgram$Builder.build(PackagedProgram.java:691) ~[flink-dist_2.12-1.13.6.jar:1.13.6]
	at org.apache.flink.client.deployment.application.ClassPathPackagedProgramRetriever.getPackagedProgram(ClassPathPackagedProgramRetriever.java:167) ~[flink-dist_2.12-1.13.6.jar:1.13.6]
	... 2 more
```

**Comment by voidking** [comment]
Got it! The right path is /opt/seatunnel/starter/seatunnel-flink-starter.jar
But then it report the same error as 2.3.0-beta.

**Comment by liugddx** [comment]
> /opt/seatunnel/lib/seatunnel-flink-starter.jar
Can you provide a PR to fix it?

**Comment by voidking** [comment]
I have run seatunnel with k8s flink demo successfully. I'd like to make a PR.  

So far, I have found several problems in the document [《Set Up with Kubernetes 2.3.0》](https://seatunnel.apache.org/docs/2.3.0/start-v2/kubernetes/):
1. The document version is  2.3.0. But it use 2.3.0-beta source code in the document.
2. The flink operator is too old. `helm add repo` will report 404 error. The recommended version is flink operator 1.3.1
3. The FakeSourceStream and ConsoleSink have been discarded? 
  a. The demo is totally change from version 2.1.2. But it still use the same flink.streaming.conf. It should be change like [《Quick Start With Flink 2.3.0》](https://seatunnel.incubator.apache.org/zh-CN/docs/2.3.0/start-v2/locally/quick-start-flink). 
  b. I haven't find the seatunnel.fake.source.FakeSourceStream.class in the connector-fake-2.3.0.jar. Where can I find it?
  c. The seatunnel.sink.ConsoleSink didn't show in the plugin-mapping.properties file.
4. It's too complex to prepare a flink.streaming.conf. The simple way is using configmap.
5. The seatunnel-flink.yaml should be updated. 
  a. If use flink operator version 1.3.1, the apiVersion should be `flink.apache.org/v1beta1`
  b. The right jarURI is `local:///opt/seatunnel/starter/seatunnel-flink-starter.jar`, not `jarURI: local:///opt/seatunnel/lib/seatunnel-flink-starter.jar`
  c. Mount configmap in pod.
6. The Dockerfile should remove command `RUN rm -rf $SEATUNNEL_HOME/connectors/seatunnel`. Because the connector-fake-2.3.0.jar and connector-console-2.3.0.jar are in the directory.

If the above is wrong, please point out. Thanks!
Then I will provide a PR to fix the problems in the document  [《Set Up with Kubernetes 2.3.0》](https://seatunnel.apache.org/docs/2.3.0/start-v2/kubernetes/).

**Comment by liugddx** [comment]
> 

Really looking forward to your pr.
