### ISSUE TITLE
[Bug] Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/hive/metastore/api/MetaException

### ISSUE THREAD

**Issue by seeker-jie** [apache/seatunnel#4006]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

The Hive Connector(v2) does not work

### SeaTunnel Version

2.3.0

### SeaTunnel Config

```conf
env {
  spark.streaming.batchDuration = 5
  spark.app.name = "seatunnel"
  spark.ui.port = 13000
  spark.sql.catalogImplementation = "hive"
}

source {
  Redis {
    host = localhost
    port = 6379
    keys = "key*"
    data_type = key
    hash_key_parse_mode = all
  }
}
transform {
}

sink{
  Hive {
    table_name = "test.test_redis_to_hive"
    metastore_uri = "thrift://localhost:10000"
  }
}
```

### Running Command

```shell
seatunnel.sh --config ./config/redis2hive.conf -e local
```

### Error Exception

```log
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/hive/metastore/api/MetaException
	at org.apache.seatunnel.connectors.seatunnel.hive.config.HiveConfig.getTableInfo(HiveConfig.java:51)
	at org.apache.seatunnel.connectors.seatunnel.hive.sink.HiveSink.prepare(HiveSink.java:86)
	at org.apache.seatunnel.engine.core.parse.ConnectorInstanceLoader.loadSinkInstance(ConnectorInstanceLoader.java:80)
	at org.apache.seatunnel.engine.core.parse.JobConfigParser.sampleAnalyze(JobConfigParser.java:346)
	at org.apache.seatunnel.engine.core.parse.JobConfigParser.parse(JobConfigParser.java:125)
	at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.getLogicalDag(JobExecutionEnvironment.java:129)
	at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:121)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:91)
	at org.apache.seatunnel.core.starter.Seatunnel.run(Seatunnel.java:39)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:31)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.hive.metastore.api.MetaException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 10 more
```

### Flink or Spark Version

spark: 2.4.8
hive: 2.3.4

### Java or Scala Version

java: 1.8.0_322
scala: 2.12.17

### Screenshots

<img width="1505" alt="image" src="https://user-images.githubusercontent.com/46879926/215474478-9f9b5a61-1542-44c3-b554-eb6d8cff1b7d.png">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by msftgitsklsd** [comment]
It seems your running commond is wrong, spark starting script is start-seatunnel-spark-connector-v2.sh

**Comment by seeker-jie** [comment]
> It seems your running commond is wrong, spark starting script is start-seatunnel-spark-connector-v2.sh

Thank you, you are right, It's working.

**Comment by rewerma** [comment]
But the ERROR still exists when use internal engine
