### ISSUE TITLE
org.apache.seatunnel.connectors.seatunnel.clickhouse.exception.ClickhouseConnectorException: ErrorCode:[COMMON-10], ErrorDescription:[Flush data operation that in sink connector failed] - Clickhouse execute batch statement error

### ISSUE THREAD

**Issue by hanyujunsir** [apache/seatunnel#4025]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Synchronize clickhouse from hive,When hive has a large amount of data, it cannot write clickhouse

### SeaTunnel Version

2.3.0

### SeaTunnel Config

```conf
env {
  # You can set spark configuration here
  # see available properties defined by spark: https://spark.apache.org/docs/latest/configuration.html#available-properties
  spark.app.name = "SeaTunnel"
  spark.executor.instances = 4
  spark.executor.cores = 2
  spark.executor.memory = "1g"
  spark.network.timeout = 600s
}

source {
        
  Hive {
    parallelism = 2
    table_name = "tmp.XXXX"
    metastore_uri = "thrift://XXXXX"
  }

}

transform {
}

sink {

  Clickhouse {
    host = "172.17.5.XX:XXX"
    database = "dws_yunpos"
    table = "dws_yunpos_city_product"
    username = "default"
    password = "XXXXXX"
  }
}
```

### Running Command

```shell
./bin/start-seatunnel-spark-connector-v2.sh \
--master local[4] \
--deploy-mode client \
--config ./config/spark.batch.conf.template
```

### Error Exception

```log
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost, executor driver): org.apache.seatunnel.connectors.seatunnel.clickhouse.exception.ClickhouseConnectorException: ErrorCode:[COMMON-10], ErrorDescription:[Flush data operation that in sink connector failed] - Clickhouse execute batch statement error
        at org.apache.seatunnel.connectors.seatunnel.clickhouse.sink.client.ClickhouseSinkWriter.flush(ClickhouseSinkWriter.java:121)
        at org.apache.seatunnel.connectors.seatunnel.clickhouse.sink.client.ClickhouseSinkWriter.write(ClickhouseSinkWriter.java:77)
        at org.apache.seatunnel.connectors.seatunnel.clickhouse.sink.client.ClickhouseSinkWriter.write(ClickhouseSinkWriter.java:43)
        at org.apache.seatunnel.translation.spark.sink.SparkDataWriter.write(SparkDataWriter.java:58)
        at org.apache.seatunnel.translation.spark.sink.SparkDataWriter.write(SparkDataWriter.java:37)
        at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$$anonfun$run$3.apply(WriteToDataSourceV2Exec.scala:118)
        at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$$anonfun$run$3.apply(WriteToDataSourceV2Exec.scala:116)
        at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1394)
        at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2Exec.scala:146)
        at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec$$anonfun$doExecute$2.apply(WriteToDataSourceV2Exec.scala:67)
        at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec$$anonfun$doExecute$2.apply(WriteToDataSourceV2Exec.scala:66)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:123)
        at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: java.io.IOException: Write timed out after 30000 ms
        at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:77)
        at com.clickhouse.jdbc.internal.InputBasedPreparedStatement.addBatch(InputBasedPreparedStatement.java:316)
        at org.apache.seatunnel.connectors.seatunnel.clickhouse.sink.client.executor.SimpleBatchStatementExecutor.addToBatch(SimpleBatchStatementExecutor.java:45)
        at org.apache.seatunnel.connectors.seatunnel.clickhouse.sink.client.executor.BufferedBatchStatementExecutor.executeBatch(BufferedBatchStatementExecutor.java:54)
        at org.apache.seatunnel.connectors.seatunnel.clickhouse.sink.client.ClickhouseSinkWriter.flush(ClickhouseSinkWriter.java:119)
        ... 18 more
```

### Flink or Spark Version

Spark 2.4.6

### Java or Scala Version

java1.8

### Screenshots

![image](https://user-images.githubusercontent.com/118161653/215937881-6068ee55-c997-4b5c-95b0-c019aa75b423.png)
![image](https://user-images.githubusercontent.com/118161653/215937914-ff6cb5a3-cdcb-4781-b0bb-4ab8675f2e09.png)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
This is a bug by clickhouse-jdbc. Already fixed by #3910

**Comment by hanyujunsir** [comment]
> 这是clickhouse-jdbc的一个错误。已被#3910修复
I created the jdbc and lib files，
![image](https://user-images.githubusercontent.com/118161653/216218602-73bd8a82-2970-46a1-8c21-838da9582a2b.png)
But a new mistake was reported.
![image](https://user-images.githubusercontent.com/118161653/216218676-200bdc4a-92bd-40eb-89a0-28a5f3a0fc52.png)
Please tell me what this is about. Thank you.

**Comment by Hisoka-X** [comment]
Please use Clickhouse Source, not JDBC source

**Comment by hanyujunsir** [comment]
I'm sorry, I don't understand what you mean. Could you be more specific?
I want to write the data to Clickhouse. I can't use the Clickhouse file on the official website. Now I write it in jdbc instead.

**Comment by hanyujunsir** [comment]
![image](https://user-images.githubusercontent.com/118161653/216223258-cab3986f-c7ee-4c6e-9141-595884377618.png)
![image](https://user-images.githubusercontent.com/118161653/216223315-026acd6f-2e70-4a89-922c-041736e646a1.png)
Thank you.

**Comment by Hisoka-X** [comment]
Please use https://seatunnel.apache.org/docs/2.3.0/connector-v2/sink/Clickhouse

**Comment by hanyujunsir** [comment]
I reinstalled it. The problem has been solved. Thank you very much

**Comment by hanyujunsir** [comment]
Again, I can read data from hive using the Spark engine, but the Flink engine and the Seatunnel engine will always report errors. May I ask, do the last two engines support reading data from hive? Thank you

**Comment by Hisoka-X** [comment]
Please provide your error log

**Comment by hanyujunsir** [comment]
Seatunnel 2.3.0
![image](https://user-images.githubusercontent.com/118161653/216541335-9d63d0e6-5899-4094-b04b-35882884a5ea.png)
Flink 1.13.3
Execute SeaTunnel Flink Job: ${FLINK_HOME}/bin/flink run -c org.apache.seatunnel.core.starter.flink.SeatunnelFlink /opt/soft/apache-seatunnel-incubating-2.3.0/starter/seatunnel-flink-starter.jar --config ./config/spark.streaming.conf.template -Dpipeline.name=SeaTunnel
Setting HADOOP_CONF_DIR=/etc/hadoop/conf because no HADOOP_CONF_DIR or HADOOP_CLASSPATH was set.
Setting HBASE_CONF_DIR=/etc/hbase/conf because no HBASE_CONF_DIR was set.
java.lang.NoSuchMethodError: org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(Lorg/apache/hadoop/hive/conf/HiveConf;)V
        at org.apache.seatunnel.connectors.seatunnel.hive.utils.HiveMetaStoreProxy.<init>(HiveMetaStoreProxy.java:44)
        at org.apache.seatunnel.connectors.seatunnel.hive.utils.HiveMetaStoreProxy.getInstance(HiveMetaStoreProxy.java:56)
        at org.apache.seatunnel.connectors.seatunnel.hive.config.HiveConfig.getTableInfo(HiveConfig.java:51)
        at org.apache.seatunnel.connectors.seatunnel.hive.source.HiveSource.prepare(HiveSource.java:67)
        at org.apache.seatunnel.core.starter.flink.execution.SourceExecuteProcessor.initializePlugins(SourceExecuteProcessor.java:115)
        at org.apache.seatunnel.core.starter.flink.execution.AbstractPluginExecuteProcessor.<init>(AbstractPluginExecuteProcessor.java:53)
        at org.apache.seatunnel.core.starter.flink.execution.SourceExecuteProcessor.<init>(SourceExecuteProcessor.java:56)
        at org.apache.seatunnel.core.starter.flink.execution.FlinkExecution.<init>(FlinkExecution.java:77)
        at org.apache.seatunnel.core.starter.flink.command.FlinkApiTaskExecuteCommand.execute(FlinkApiTaskExecuteCommand.java:53)
        at org.apache.seatunnel.core.starter.Seatunnel.run(Seatunnel.java:39)
        at org.apache.seatunnel.core.starter.flink.SeatunnelFlink.main(SeatunnelFlink.java:34)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355)
        at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222)
        at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114)
        at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:812)
        at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:246)
        at org.apache.flink.client.cli.CliFrontend.parseAndRun(CliFrontend.java:1054)
        at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1132)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1836)
        at org.apache.flink.runtime.security.contexts.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:41)
        at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1132)

**Comment by Hisoka-X** [comment]
you should put hive-exec.jar in flink lib (flink engine) or seatunnel plugins directory (seatunnel engine)

**Comment by Hisoka-X** [comment]
you should put hive-exec.jar in flink lib (flink engine) or seatunnel plugins directory (seatunnel engine)

**Comment by Hisoka-X** [comment]
you should put hive-exec.jar in flink lib (flink engine) or seatunnel plugins directory (seatunnel engine)

**Comment by hanyujunsir** [comment]
That's what I did, but it didn't work.
![image](https://user-images.githubusercontent.com/118161653/216859850-023d1178-a2c4-4e82-8095-b77979ba217f.png)

**Comment by hanyujunsir** [comment]
That's what I did, but I still reported it wrong
![image](https://user-images.githubusercontent.com/118161653/216869398-da94cedf-e561-443f-ba59-7e28382fe30b.png)
![image](https://user-images.githubusercontent.com/118161653/216869416-ae774ad9-4c1c-4bd6-9137-1748fdd75d86.png)

**Comment by hanyujunsir** [comment]
That's what I did, but I still reported it wrong.
![image](https://user-images.githubusercontent.com/118161653/216869782-dfccbdbd-d37a-4c63-bf20-7fbad43d4867.png)
![image](https://user-images.githubusercontent.com/118161653/216869800-326f859c-0512-40b6-b881-29cb86d09aa5.png)
Why is that?

**Comment by Hisoka-X** [comment]
have you restart your cluster?

**Comment by hanyujunsir** [comment]
Yes, I rebooted.

**Comment by Hisoka-X** [comment]
cluster and client should put jar both.
