### ISSUE TITLE
[Bug] [Connector-v2] es source mapping NullPointerException

### ISSUE THREAD

**Issue by kpretty** [apache/seatunnel#4074]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

es source NullPointerException

### SeaTunnel Version

2.3.0

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
  job.mode = "BATCH"
  job.name = "opensearch to console"
}

source {
  Elasticsearch {
    hosts = ["xxx:9200"]
    index = "filebeat1"
    source = ["agent.name"]
  }
}

transform {

}

sink {
  Console {}
}
```

### Running Command

```shell
bin/seatunnel.sh --config jobs/01-es-no-transform-console.conf -e local
```

### Error Exception

```log
Exception in thread "main" java.lang.NullPointerException
	at org.apache.seatunnel.connectors.seatunnel.elasticsearch.client.EsRestClient.getFieldTypeMappingFromProperties(EsRestClient.java:323)
	at org.apache.seatunnel.connectors.seatunnel.elasticsearch.client.EsRestClient.getFieldTypeMapping(EsRestClient.java:309)
	at org.apache.seatunnel.connectors.seatunnel.elasticsearch.source.ElasticsearchSource.prepare(ElasticsearchSource.java:66)
	at org.apache.seatunnel.engine.core.parse.ConnectorInstanceLoader.loadSourceInstance(ConnectorInstanceLoader.java:60)
	at org.apache.seatunnel.engine.core.parse.JobConfigParser.sampleAnalyze(JobConfigParser.java:314)
	at org.apache.seatunnel.engine.core.parse.JobConfigParser.parse(JobConfigParser.java:125)
	at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.getLogicalDag(JobExecutionEnvironment.java:129)
	at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:121)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:91)
	at org.apache.seatunnel.core.starter.Seatunnel.run(Seatunnel.java:39)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:31)
```

### Flink or Spark Version

no!!! this is local

### Java or Scala Version

1.8

### Screenshots

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/77819741/217203938-b678168b-c165-4f29-9b1c-674599d9b894.png">

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kpretty** [comment]
I have solved it and submitted pr #4073
