### ISSUE TITLE
[Bug][Transform-v2][Spark] FieldMapper ClassCastException

### ISSUE THREAD

**Issue by baiguang10** [apache/seatunnel#4081]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

使用FakeSource生成数据执行输出到控制台没问题，使用FiledMap映射之后会报类型转换异常的错误

```
env {
  execution.parallelism = 1
  #spark.app.name = "SeaTunnel"
  #spark.executor.instances = 2
  #spark.executor.cores = 1
  #spark.executor.memory = "1g"
  #spark.master = local
}

source {
    FakeSource {
      result_table_name = "fake"
      row.num = 16
      schema = {
        fields {
          age = timestamp
          sex = date
        }
      }
    }
}

transform {
    FieldMapper {
        source_table_name = "fake"
        result_table_name = "result"
        field_mapper = {
            age = age
            sex = sex
        }
  }
}

sink {
  Console {
        source_table_name = "result"
  }
}
```

### SeaTunnel Version

dev分支

### SeaTunnel Config

```conf
seatunnel基本使用默认设置，使用seatunnel用spark3.4.1单节点去执行任务
```

### Running Command

```shell
../../bin/start-seatunnel-spark-3-connector-v2.sh  --master local[4]  --deploy-mode client  --config test
```

### Error Exception

```log
23/02/08 03:10:55 INFO CodeGenerator: Code generated in 29.388814 ms
23/02/08 03:10:55 ERROR SparkTaskExecuteCommand: Run SeaTunnel on spark failed.
org.apache.seatunnel.core.starter.exception.TaskExecuteException: SeaTunnel transform task: FieldMapper execute error
        at org.apache.seatunnel.core.starter.spark.execution.TransformExecuteProcessor.execute(TransformExecuteProcessor.java:93)
        at org.apache.seatunnel.core.starter.spark.execution.SparkExecution.execute(SparkExecution.java:61)
        at org.apache.seatunnel.core.starter.spark.command.SparkTaskExecuteCommand.execute(SparkTaskExecuteCommand.java:58)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:39)
        at org.apache.seatunnel.core.starter.spark.SeaTunnelSpark.main(SeaTunnelSpark.java:31)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:958)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassCastException: java.sql.Timestamp cannot be cast to java.lang.Long
        at org.apache.seatunnel.translation.spark.serialization.InternalRowConverter.reconvert(InternalRowConverter.java:194)
        at org.apache.seatunnel.translation.spark.serialization.InternalRowConverter.reconvert(InternalRowConverter.java:211)
        at org.apache.seatunnel.translation.spark.serialization.InternalRowConverter.reconvert(InternalRowConverter.java:187)
        at org.apache.seatunnel.translation.spark.serialization.InternalRowConverter.reconvert(InternalRowConverter.java:178)
        at org.apache.seatunnel.core.starter.spark.execution.TransformExecuteProcessor.sparkTransform(TransformExecuteProcessor.java:110)
        at org.apache.seatunnel.core.starter.spark.execution.TransformExecuteProcessor.execute(TransformExecuteProcessor.java:88)
        ... 16 more
![image](https://user-images.githubusercontent.com/46086591/217420595-e8f5b42c-0599-4a38-837d-6141f001357b.png)
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hailin0** [comment]
root cause：
java.sql.Timestamp cannot be cast to java.lang.Long, `org.apache.seatunnel.translation.spark.serialization.InternalRowConverter#convert(org.apache.seatunnel.api.table.type.SeaTunnelRow)` method not called before `org.apache.seatunnel.core.starter.spark.execution.TransformExecuteProcessor.sparkTransform` executes
