### ISSUE TITLE
[Bug] [Connect jdbc] ErrorDescription:[No suitable dialect factory found]

### ISSUE THREAD

**Issue by eanfs** [apache/seatunnel#4162]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

use jdbc Connect and copy mysql-connector-java-8.0.28.jar to plugins/jdbc/lib 
got exception below

### SeaTunnel Version

2.3.0

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
  job.mode = "BATCH"
}

source {
    Jdbc {
        url = "jdbc:mysql://localhost:3306/mysql?serverTimezone=GMT%2b8"
        driver = "com.mysql.cj.jdbc.Driver"
        connection_check_timeout_sec = 100
        user = "root"
        password = "WGlEaW5nQ2xvdW"
        query = "select * from help_keyword"
    }
}

transform {

}

sink {
    Console {}
}
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/test-batch-mysql.conf -e local
```

### Error Exception

```log
Exception in thread "main" org.apache.seatunnel.connectors.seatunnel.jdbc.exception.JdbcConnectorException: ErrorCode:[JDBC-06], ErrorDescription:[No suitable dialect factory found] - Could not find any jdbc dialect factories that implement 'org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.JdbcDialectFactory' in the classpath.
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.JdbcDialectLoader.load(JdbcDialectLoader.java:53)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.source.JdbcSource.prepare(JdbcSource.java:80)
	at org.apache.seatunnel.engine.core.parse.ConnectorInstanceLoader.loadSourceInstance(ConnectorInstanceLoader.java:60)
	at org.apache.seatunnel.engine.core.parse.JobConfigParser.sampleAnalyze(JobConfigParser.java:314)
	at org.apache.seatunnel.engine.core.parse.JobConfigParser.parse(JobConfigParser.java:125)
	at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.getLogicalDag(JobExecutionEnvironment.java:129)
	at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:121)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:91)
	at org.apache.seatunnel.core.starter.Seatunnel.run(Seatunnel.java:39)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:31)
```

### Java or Scala Version

java 11

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by eanfs** [comment]
run the same config was success with java 8.0.362

**Comment by zorrofox** [comment]
I have the same problem in Java 11 in docker `eclipse-temurin:11-jre-jammy`, and I will try `eclipse-temurin:8-jre-jammy`.

**Comment by zorrofox** [comment]
I think this indeed the Java11 issue, can someone look at this?

**Comment by YuriyGavrilov** [comment]
manly the same but little bit diff. with Trino JDBC Driver.
https://trino.io/docs/current/client/jdbc.html
