### ISSUE TITLE
[Bug] Plugin PluginIdentifier{engineType='seatunnel', pluginType='transform', pluginName='sql'

### ISSUE THREAD

**Issue by xuchang-66** [apache/seatunnel#4197]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

use transform sql error.

### SeaTunnel Version

2.3.0

### SeaTunnel Config

```conf
.
```

### Running Command

```shell
./apache-seatunnel-incubating-2.3.1-SNAPSHOT/bin/start-seatunnel-spark-2-connector-v2.sh --master local[2] --deploy-mode client --config ./es2hive.conf
```

### Error Exception

```log
23/02/23 15:41:05 ERROR SeaTunnel: Fatal Error, 

23/02/23 15:41:05 ERROR SeaTunnel: Please submit bug report in https://github.com/apache/incubator-seatunnel/issues

23/02/23 15:41:05 ERROR SeaTunnel: Reason:Plugin PluginIdentifier{engineType='seatunnel', pluginType='transform', pluginName='sql'} not found. 

23/02/23 15:41:05 ERROR SeaTunnel: Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: Plugin PluginIdentifier{engineType='seatunnel', pluginType='transform', pluginName='sql'} not found.
        at org.apache.seatunnel.core.starter.spark.command.SparkTaskExecuteCommand.execute(SparkTaskExecuteCommand.java:63)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.spark.SeaTunnelSpark.main(SeaTunnelSpark.java:35)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:900)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:192)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:217)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

### Flink or Spark Version

spark 2.4.0

### Java or Scala Version

jdk 1.8

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TyrantLucifer** [comment]
![image](https://user-images.githubusercontent.com/51053924/224650633-99ac316a-c1c5-4021-91cb-3a39c4850036.png)

![image](https://user-images.githubusercontent.com/51053924/224650652-45e2659a-b27b-46fc-9d72-96a13844735e.png)

Since 2.3.1, SQL plugin will be refactored. You can refer to https://seatunnel.apache.org/docs/transform-v2/sql

**Comment by somnmos** [comment]
@TyrantLucifer Do you plan to support multi-source JDBC connector in seatunnel zeta engine?
