### ISSUE TITLE
[Bug] connector-influxdb dependency influxdb-java's version shuld be 2.15 not 2.21

### ISSUE THREAD

**Issue by zhengyuan-cn** [apache/seatunnel#4230]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

It's Happened NoSuchMethod when the dependency of  influxdb-java's version 2.1 .
detail:
23/02/27 10:50:06 INFO AbstractPluginDiscovery: Load plugin: PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='InfluxDB'} from classpath
Exception in thread "main" java.lang.NoSuchMethodError: kotlin.collections.ArraysKt.copyInto([B[BIII)[B
        at shaded.okio.Segment.writeTo(Segment.kt:169)
        at shaded.okio.Segment.compact(Segment.kt:152)
        at shaded.okio.Buffer.write(Buffer.kt:1842)
        at shaded.okio.Buffer.read(Buffer.kt:1854)
        at shaded.okio.Buffer.writeAll(Buffer.kt:1642)
        at shaded.okio.Options$Companion.buildTrieRecursive(Options.kt:187)
        at shaded.okio.Options$Companion.buildTrieRecursive(Options.kt:174)
        at shaded.okio.Options$Companion.buildTrieRecursive$default(Options.kt:113)
        at shaded.okio.Options$Companion.of(Options.kt:72)
        at shaded.okhttp3.internal.Util.<clinit>(Util.kt:71)
        at shaded.okhttp3.internal.concurrent.TaskRunner.<clinit>(TaskRunner.kt:309)
        at shaded.okhttp3.ConnectionPool.<init>(ConnectionPool.kt:41)
        at shaded.okhttp3.ConnectionPool.<init>(ConnectionPool.kt:47)
        at shaded.okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.kt:471)
        at org.apache.seatunnel.connectors.seatunnel.influxdb.client.InfluxDBClient.getInfluxDB(InfluxDBClient.java:42)
        at org.apache.seatunnel.connectors.seatunnel.influxdb.source.InfluxDBSource.prepare(InfluxDBSource.java:84)
        at org.apache.seatunnel.core.starter.spark.execution.SourceExecuteProcessor.initializePlugins(SourceExecuteProcessor.java:88)
        at org.apache.seatunnel.core.starter.spark.execution.AbstractPluginExecuteProcessor.<init>(AbstractPluginExecuteProcessor.java:49)
        at org.apache.seatunnel.core.starter.spark.execution.SourceExecuteProcessor.<init>(SourceExecuteProcessor.java:51)
        at org.apache.seatunnel.core.starter.spark.execution.SparkExecution.<init>(SparkExecution.java:50)
        at org.apache.seatunnel.core.starter.spark.command.SparkApiTaskExecuteCommand.execute(SparkApiTaskExecuteCommand.java:54)
        at org.apache.seatunnel.core.starter.Seatunnel.run(Seatunnel.java:39)
        at org.apache.seatunnel.core.starter.spark.SeatunnelSpark.main(SeatunnelSpark.java:34)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:855)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:930)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:939)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

### SeaTunnel Version

2.3.0

### SeaTunnel Config

```conf
env {
    spark.executor.memory="8G"
    spark.driver.memory="4g"
    spark.app.name="SeaTunnel"
    spark.executor.instances="3"
}
 source{

InfluxDB {
    url="http://10.x.x.22:8086"
    database="data_iot"
    password="xxxxx"
    sql="select time,temp3 from lunzi where time >= '2023-01-11 16:18:00' and time < '2023-01-11 16:19:00' tz('Asia/Shanghai')"
   
    fields {
      time = BIGINT
      temp3 = INT
    }

}


}
 transform{

sql {
    source_table_name="source1"
    sql="select id,time,value from source1"
    result_table_name="transform31"
}


}
 sink{

kafka {
    source_table_name="transform31"
    topic="seatunnel-test"
    bootstrap.servers="10.x.x.21:9192,10.x.x.22:9192,10.x.x.23:9192"
}


}
```

### Running Command

```shell
./bin/start-seatunnel-spark-connector-v2.sh --master spark://hadoop02:7077 --deploy-mode client --config ./config/influx.to.kafka.template
```

### Error Exception

```log
23/02/27 10:50:06 INFO AbstractPluginDiscovery: Load plugin: PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='InfluxDB'} from classpath
Exception in thread "main" java.lang.NoSuchMethodError: kotlin.collections.ArraysKt.copyInto([B[BIII)[B
        at shaded.okio.Segment.writeTo(Segment.kt:169)
        at shaded.okio.Segment.compact(Segment.kt:152)
        at shaded.okio.Buffer.write(Buffer.kt:1842)
        at shaded.okio.Buffer.read(Buffer.kt:1854)
        at shaded.okio.Buffer.writeAll(Buffer.kt:1642)
        at shaded.okio.Options$Companion.buildTrieRecursive(Options.kt:187)
        at shaded.okio.Options$Companion.buildTrieRecursive(Options.kt:174)
        at shaded.okio.Options$Companion.buildTrieRecursive$default(Options.kt:113)
        at shaded.okio.Options$Companion.of(Options.kt:72)
        at shaded.okhttp3.internal.Util.<clinit>(Util.kt:71)
        at shaded.okhttp3.internal.concurrent.TaskRunner.<clinit>(TaskRunner.kt:309)
        at shaded.okhttp3.ConnectionPool.<init>(ConnectionPool.kt:41)
        at shaded.okhttp3.ConnectionPool.<init>(ConnectionPool.kt:47)
        at shaded.okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.kt:471)
        at org.apache.seatunnel.connectors.seatunnel.influxdb.client.InfluxDBClient.getInfluxDB(InfluxDBClient.java:42)
        at org.apache.seatunnel.connectors.seatunnel.influxdb.source.InfluxDBSource.prepare(InfluxDBSource.java:84)
        at org.apache.seatunnel.core.starter.spark.execution.SourceExecuteProcessor.initializePlugins(SourceExecuteProcessor.java:88)
        at org.apache.seatunnel.core.starter.spark.execution.AbstractPluginExecuteProcessor.<init>(AbstractPluginExecuteProcessor.java:49)
        at org.apache.seatunnel.core.starter.spark.execution.SourceExecuteProcessor.<init>(SourceExecuteProcessor.java:51)
        at org.apache.seatunnel.core.starter.spark.execution.SparkExecution.<init>(SparkExecution.java:50)
        at org.apache.seatunnel.core.starter.spark.command.SparkApiTaskExecuteCommand.execute(SparkApiTaskExecuteCommand.java:54)
        at org.apache.seatunnel.core.starter.Seatunnel.run(Seatunnel.java:39)
        at org.apache.seatunnel.core.starter.spark.SeatunnelSpark.main(SeatunnelSpark.java:34)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:855)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:930)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:939)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

### Flink or Spark Version

spark 2.4.8

### Java or Scala Version

jdk 1.8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhengyuan-cn** [comment]
not allow dowgrade version
