### ISSUE TITLE
No configuration setting found for key 'query' - apache seatunnel

### ISSUE THREAD

**Issue by sangeetha1706** [apache/seatunnel#4329]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

im trying to synchronize from one mysql table to another mysql table.

### SeaTunnel Version

apache-seatunnel-incubating-2.3.0

### SeaTunnel Config

```conf
env {
   job.mode = "BATCH"
}

source {
jdbc{
        url ="jdbc:mysql://10.0.0.82:3306/test?serverTimezone=GMT%2b8",
        driver = "com.mysql.cj.jdbc.Driver",
        user = "hauser",
        password = "Hauser@7ujm",
        query = "select * from SOURCE_USER"

}
}
transform {
}

sink {
jdbc{
        table_name = "SINK_USER"
        url = "jdbc:mysql://10.0.0.82:3306/test?serverTimezone=GMT%2b8"
        driver = "com.mysql.cj.jdbc.Driver"
        user = "hauser"
        password = "Hauser@7ujm"

}
}
```

### Running Command

```shell
./bin/seatunnel.sh -c ./config/mysql-mysql.conf -e LOCAL
```

### Error Exception

```log
Exception StackTrace:org.apache.seatunnel.shade.com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'query'
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:174)
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
	at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:250)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.config.JdbcSourceOptions.<init>(JdbcSourceOptions.java:45)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.source.JdbcSource.prepare(JdbcSource.java:77)
	at org.apache.seatunnel.engine.core.parse.ConnectorInstanceLoader.loadSourceInstance(ConnectorInstanceLoader.java:60)
	at org.apache.seatunnel.engine.core.parse.JobConfigParser.sampleAnalyze(JobConfigParser.java:314)
	at org.apache.seatunnel.engine.core.parse.JobConfigParser.parse(JobConfigParser.java:125)
	at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.getLogicalDag(JobExecutionEnvironment.java:129)
	at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:121)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:91)
	at org.apache.seatunnel.core.starter.Seatunnel.run(Seatunnel.java:39)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:31)
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TyrantLucifer** [comment]
![image](https://user-images.githubusercontent.com/51053924/224649686-311a39b8-6e03-409a-96b6-ab373d1b963f.png)

Remove these commas
