### ISSUE TITLE
run sqlserver cdc task failed

### ISSUE THREAD

**Issue by fttat** [apache/seatunnel#4460]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I have configed a seatunnel job for sqlserver cdc,but when i ran job use command " ./bin/seatunnel.sh --config ./config/pg_to_mysql.conf -e local",then come accross some error messages:

2023-03-31 10:43:49,834 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Fatal Error,

2023-03-31 10:43:49,834 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Please submit bug report in https://github.com/apache/incubator-seatunnel/issues

2023-03-31 10:43:49,834 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Reason:SeaTunnel job executed failed

2023-03-31 10:43:49,837 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:181)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:877)
        at org.apache.seatunnel.connectors.seatunnel.cdc.sqlserver.source.config.SqlServerSourceConfigFactory.create(SqlServerSourceConfigFactory.java:49)
        at org.apache.seatunnel.connectors.seatunnel.cdc.sqlserver.source.source.SqlServerDialect.<init>(SqlServerDialect.java:55)
        at org.apache.seatunnel.connectors.seatunnel.cdc.sqlserver.source.source.SqlServerIncrementalSource.createDataSourceDialect(SqlServerIncrementalSource.java:118)
        at org.apache.seatunnel.connectors.cdc.base.source.IncrementalSource.prepare(IncrementalSource.java:117)
        at org.apache.seatunnel.engine.core.parse.ConnectorInstanceLoader.loadSourceInstance(ConnectorInstanceLoader.java:64)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.sampleAnalyze(JobConfigParser.java:371)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.parse(JobConfigParser.java:132)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:112)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.getLogicalDag(JobExecutionEnvironment.java:155)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:147)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:140)
        ... 2 more

2023-03-31 10:43:49,837 ERROR org.apache.seatunnel.core.starter.SeaTunnel -
===============================================================================

Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:181)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:877)
        at org.apache.seatunnel.connectors.seatunnel.cdc.sqlserver.source.config.SqlServerSourceConfigFactory.create(SqlServerSourceConfigFactory.java:49)
        at org.apache.seatunnel.connectors.seatunnel.cdc.sqlserver.source.source.SqlServerDialect.<init>(SqlServerDialect.java:55)
        at org.apache.seatunnel.connectors.seatunnel.cdc.sqlserver.source.source.SqlServerIncrementalSource.createDataSourceDialect(SqlServerIncrementalSource.java:118)
        at org.apache.seatunnel.connectors.cdc.base.source.IncrementalSource.prepare(IncrementalSource.java:117)
        at org.apache.seatunnel.engine.core.parse.ConnectorInstanceLoader.loadSourceInstance(ConnectorInstanceLoader.java:64)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.sampleAnalyze(JobConfigParser.java:371)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.parse(JobConfigParser.java:132)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:112)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.getLogicalDag(JobExecutionEnvironment.java:155)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:147)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:140)

### SeaTunnel Version

seatunnel 2.3.1

### SeaTunnel Config

```conf
env {
  job.mode = "STREAMING"
}
source {
  SqlServer-CDC {
    result_table_name = "sales"    
    username = ""
    password = ""
    database-names = ["DM"]
    table-names = ["DM.dbo.sales"]
    base-url="jdbc:sqlserver://10.110.44.29:1433;databaseName=DM"
  }
}
transform {
}
sink {
        jdbc {
        url = "jdbc:mysql://10.10.44.29:3306/inputdata"
        driver = "com.mysql.cj.jdbc.Driver"
        user = "root"
        password = "root"            
        table = sales
        }
}
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/pg_to_mysql.conf -e local
```

### Error Exception

```log
2023-03-31 10:43:49,834 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Fatal Error,
 1067  2023-03-31 10:43:49,834 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Please submit bug report in https://github.com/apache/incubator-seatunnel/issues
 1068  2023-03-31 10:43:49,834 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Reason:SeaTunnel job executed failed
 1069  2023-03-31 10:43:49,837 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
 1070          at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:181)
 1071          at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
 1072          at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
 1073  Caused by: java.lang.NullPointerException
 1074          at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:877)
 1075          at org.apache.seatunnel.connectors.seatunnel.cdc.sqlserver.source.config.SqlServerSourceConfigFactory.create(SqlServerSourceConfigFactory.java:49)
 1076          at org.apache.seatunnel.connectors.seatunnel.cdc.sqlserver.source.source.SqlServerDialect.<init>(SqlServerDialect.java:55)
 1077          at org.apache.seatunnel.connectors.seatunnel.cdc.sqlserver.source.source.SqlServerIncrementalSource.createDataSourceDialect(SqlServerIncrementalSource.java:118)
 1078          at org.apache.seatunnel.connectors.cdc.base.source.IncrementalSource.prepare(IncrementalSource.java:117)
 1079          at org.apache.seatunnel.engine.core.parse.ConnectorInstanceLoader.loadSourceInstance(ConnectorInstanceLoader.java:64)
 1080          at org.apache.seatunnel.engine.core.parse.JobConfigParser.sampleAnalyze(JobConfigParser.java:371)
 1081          at org.apache.seatunnel.engine.core.parse.JobConfigParser.parse(JobConfigParser.java:132)
 1082          at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:112)
 1083          at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.getLogicalDag(JobExecutionEnvironment.java:155)
 1084          at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:147)
 1085          at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:140)
 1086          ... 2 more
 1087  2023-03-31 10:43:49,837 ERROR org.apache.seatunnel.core.starter.SeaTunnel -
 1088  ===============================================================================
 1089  Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
 1090          at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:181)
 1091          at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
 1092          at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
 1093  Caused by: java.lang.NullPointerException
 1094          at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:877)
 1095          at org.apache.seatunnel.connectors.seatunnel.cdc.sqlserver.source.config.SqlServerSourceConfigFactory.create(SqlServerSourceConfigFactory.java:49)
 1096          at org.apache.seatunnel.connectors.seatunnel.cdc.sqlserver.source.source.SqlServerDialect.<init>(SqlServerDialect.java:55)
 1097          at org.apache.seatunnel.connectors.seatunnel.cdc.sqlserver.source.source.SqlServerIncrementalSource.createDataSourceDialect(SqlServerIncrementalSource.java:118)
 1098          at org.apache.seatunnel.connectors.cdc.base.source.IncrementalSource.prepare(IncrementalSource.java:117)
 1099          at org.apache.seatunnel.engine.core.parse.ConnectorInstanceLoader.loadSourceInstance(ConnectorInstanceLoader.java:64)
 1100          at org.apache.seatunnel.engine.core.parse.JobConfigParser.sampleAnalyze(JobConfigParser.java:371)
 1101          at org.apache.seatunnel.engine.core.parse.JobConfigParser.parse(JobConfigParser.java:132)
 1102          at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:112)
 1103          at org.apache.seatunnel.engine.client.job.JobExecu
 1104          at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:147)
 1105          at org.apache.seatunnel.core.star
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment]
<img width="889" alt="image" src="https://user-images.githubusercontent.com/32193458/229273103-05d4150f-ceb9-4d50-a8fa-3f3a4eeb442f.png">

From the code I found `hostname` is required. Please add it .

**Comment by EricJoy2048** [comment]
I created an issue about this. https://github.com/apache/incubator-seatunnel/issues/4473 . 
Would you like to propose a pr to fix it？

**Comment by kim-up** [comment]
![image](https://user-images.githubusercontent.com/9264192/229357065-b5390eef-bf8b-4ee9-8c2c-fbdd2be1e6ab.png)

What I see is that "hostname" is parsed from "base-url". There is no need to set "hostname" separately.

**Comment by marsqd** [comment]
以下配置测试 SQL Server CDC 成功，可以参考（官方文档 https://seatunnel.apache.org/docs/2.3.1/connector-v2/source/SqlServer-CDC/ 有点不对）。

source {
   SqlServer-CDC {
    result_table_name = "fake"
    hostname = "10.32.x.x"
    port = "1433"
    username = "user1"
    password = "user1"
    database-names = ["synctestdb"]
    table-names = ["synctestdb.dbo.t1"]

    debezium {
        database.encrypt = true
        database.trustServerCertificate = true
    }
   }
}
