### ISSUE TITLE
[Bug] [hive source] read hive partition text error

### ISSUE THREAD

**Issue by 15810785091** [apache/seatunnel#4465]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

![image](https://user-images.githubusercontent.com/53160760/229050190-06830ece-0977-4e39-a5d6-55a9685f4fd6.png)
When reading the hive partition file, an error is reported when the partition data exists.

Sample data
drop table th_db.aaa;
create table th_db.aaa(
 uid string,
 text string
)partitioned by(dt string);

insert overwrite table th_db.aaa partition(dt='2023-03-03')
select '11111',NULL
UNION ALL
select '22222',NULL
;
Data View
![image](https://user-images.githubusercontent.com/53160760/229670701-3c4d8a22-dec0-4250-a583-8f7462c1c80e.png)
![image](https://user-images.githubusercontent.com/53160760/229670746-e3931dce-ee4f-43c4-9ef7-5364d30e61f1.png)

### SeaTunnel Version

2.3.1         hive 2.1.1+cdh6.3.2

### SeaTunnel Config

```conf
env {
    execution.parallelism = 1
    job.name = "weibo.article.hive2doris"
    job.mode = "BATCH"
}

source {
  Hive {
    table_name = "th_db.aaa"
    metastore_uri = "thrift://xxxxxx:9083"
    hdfs_site_path = "/etc/hadoop/conf/hdfs-site.xml"
    read_partitions = ["dt=2023-03-03"]
    result_table_name = "test2"
  }


}

transform {

}

sink {
  Console {
    source_table_name = "test2"
  }
}
```

### Running Command

```shell
/bin/seatunnel.sh --config test.conf -e local
```

### Error Exception

```log
Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:181)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: org.apache.seatunnel.connectors.seatunnel.file.exception.FileConnectorException: ErrorCode:[COMMON-01], ErrorDescription:[File operation failed, such as (read,list,write,move,copy,sync) etc...] - Read data from this file [hdfs://nameservice1/user/hive/warehouse/ims_dim.db/ft_user_snwb/dt=2023-02-08/000000_0] failed
        at org.apache.seatunnel.connectors.seatunnel.file.source.BaseFileSourceReader.pollNext(BaseFileSourceReader.java:70)
        at org.apache.seatunnel.engine.server.task.flow.SourceFlowLifeCycle.collect(SourceFlowLifeCycle.java:135)
        at org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask.collect(SourceSeaTunnelTask.java:84)
        at org.apache.seatunnel.engine.server.task.SeaTunnelTask.stateProcess(SeaTunnelTask.java:161)
        at org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask.call(SourceSeaTunnelTask.java:89)
        at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:526)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NumberFormatException: For input string: "\N"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Long.parseLong(Long.java:589)
        at java.lang.Long.parseLong(Long.java:631)
        at org.apache.seatunnel.format.text.TextDeserializationSchema.convert(TextDeserializationSchema.java:206)
        at org.apache.seatunnel.format.text.TextDeserializationSchema.deserialize(TextDeserializationSchema.java:120)
        at org.apache.seatunnel.format.text.TextDeserializationSchema.deserialize(TextDeserializationSchema.java:44)
        at org.apache.seatunnel.connectors.seatunnel.file.source.reader.TextReadStrategy.lambda$read$0(TextReadStrategy.java:73)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at org.apache.seatunnel.connectors.seatunnel.file.source.reader.TextReadStrategy.read(TextReadStrategy.java:69)
        at org.apache.seatunnel.connectors.seatunnel.file.source.BaseFileSourceReader.pollNext(BaseFileSourceReader.java:66)
        ... 10 more

        at org.apache.seatunnel.engine.client.job.ClientJobProxy.waitForJobComplete(ClientJobProxy.java:119)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:174)
        ... 2 more
2023-03-31 15:15:05,904 INFO  org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand - run shutdown hook because get close signal
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 15810785091** [comment]
![image](https://user-images.githubusercontent.com/53160760/229051574-f5f1001d-4a59-496d-b6dd-02b9a51d8800.png)
hdfs file

**Comment by lightzhao** [comment]
Check if your hive schema is consistent with the data schema.

**Comment by 15810785091** [comment]
The versions are inconsistent. My version is 2.1，Spark is the same error.

**Comment by 15810785091** [comment]
From the new compilation project, modifying hive to 2.1.1 still reports the same error.

**Comment by EricJoy2048** [comment]
whats `\N` ?

**Comment by 15810785091** [comment]
hive NULL data is stored by default \N

**Comment by 15810785091** [comment]
I understand that the seatunnel did not process \N when cutting hive data, and should convert \N data''
