### ISSUE TITLE
[BUG] [connector-v2] [paimon sink] read mysql data and sink data to paimon casued nullpoint exception

### ISSUE THREAD

**Issue by gitfortian** [apache/seatunnel#4505]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

read mysql data and sink data to paimon casued nullpoint exception

### SeaTunnel Version

2.3.1

### SeaTunnel Config

```conf
env {
    execution.parallelism = 4
    job.mode = "BATCH"
    checkpoint.interval = 360000
}

source {
    Jdbc {
      url = "jdbc:mysql://xxx/dinky?useSSL=false"
      driver = "com.mysql.cj.jdbc.Driver"
      connection_check_timeout_sec = 100
      user = "root"
      password = "xxx"
      query = "select * from dlink_job_history"
    }
}

sink {
    Paimon {
      warehouse = "hdfs://hdp01:8020/paimon/warehouse",
      database = "ods",
      table = "dlink_job_history"
    }
}
```

### Running Command

```shell
bin/seatunnel.sh --config config/mysql-paimon.conf -m local
```

### Error Exception

```log
2023-04-06 14:07:10,922 ERROR org.apache.seatunnel.engine.server.dag.physical.SubPlan - Task TaskGroupLocation{jobId=696239445162065921, pipelineId=1, taskGroupId=50000} Failed in Job SeaTunnel_Job (696239445162065921), Pipeline: [(1/1)], Begin to cancel other tasks in this pipeline.
2023-04-06 14:07:10,923 INFO  org.apache.seatunnel.engine.server.dag.physical.SubPlan - Job SeaTunnel_Job (696239445162065921), Pipeline: [(1/1)] turn from state RUNNING to CANCELING.
2023-04-06 14:07:10,924 INFO  org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator - start clean pending checkpoint cause Pipeline turn to end state.
2023-04-06 14:07:10,924 INFO  org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator - skip this checkpoint cause by completedCheckpoint is null
2023-04-06 14:07:10,926 INFO  org.apache.seatunnel.engine.server.dag.physical.PhysicalVertex - Job SeaTunnel_Job (696239445162065921), Pipeline: [(1/1)], task: [pipeline-1 [Source[0]-Jdbc-default-identifier]-SplitEnumerator (1/1)] turn from state RUNNING to CANCELING.
2023-04-06 14:07:10,927 INFO  org.apache.seatunnel.engine.server.dag.physical.PhysicalVertex - Job SeaTunnel_Job (696239445162065921), Pipeline: [(1/1)], task: [pipeline-1 [Sink[0]-Paimon-default-identifier]-AggregatedCommitterTask (1/1)] turn from state RUNNING to CANCELING.
2023-04-06 14:07:10,928 INFO  org.apache.seatunnel.engine.server.dag.physical.PhysicalVertex - Send cancel Job SeaTunnel_Job (696239445162065921), Pipeline: [(1/1)], task: [pipeline-1 [Sink[0]-Paimon-default-identifier]-AggregatedCommitterTask (1/1)] operator to member [localhost]:5801
2023-04-06 14:07:10,928 INFO  org.apache.seatunnel.engine.server.dag.physical.PhysicalVertex - Send cancel Job SeaTunnel_Job (696239445162065921), Pipeline: [(1/1)], task: [pipeline-1 [Source[0]-Jdbc-default-identifier]-SplitEnumerator (1/1)] operator to member [localhost]:5801
2023-04-06 14:07:10,928 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-863812] [5.1] Task (TaskGroupLocation{jobId=696239445162065921, pipelineId=1, taskGroupId=3}) need cancel.
2023-04-06 14:07:10,929 WARN  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-863812] [5.1] Interrupted task 40000 - org.apache.seatunnel.engine.server.task.SinkAggregatedCommitterTask@5bc4cebe
2023-04-06 14:07:10,929 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-863812] [5.1] Task (TaskGroupLocation{jobId=696239445162065921, pipelineId=1, taskGroupId=1}) need cancel.
2023-04-06 14:07:10,929 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-863812] [5.1] taskDone, taskId = 40000, taskGroup = TaskGroupLocation{jobId=696239445162065921, pipelineId=1, taskGroupId=3}
2023-04-06 14:07:10,929 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-863812] [5.1] Task TaskGroupLocation{jobId=696239445162065921, pipelineId=1, taskGroupId=3} complete with state CANCELED
2023-04-06 14:07:10,929 WARN  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-863812] [5.1] Interrupted task 20000 - org.apache.seatunnel.engine.server.task.SourceSplitEnumeratorTask@4dc5c01a
2023-04-06 14:07:10,929 INFO  org.apache.seatunnel.engine.server.dag.physical.PhysicalVertex - Job SeaTunnel_Job (696239445162065921), Pipeline: [(1/1)], task: [pipeline-1 [Sink[0]-Paimon-default-identifier]-AggregatedCommitterTask (1/1)] turn to end state CANCELED.
2023-04-06 14:07:10,929 INFO  org.apache.seatunnel.engine.server.dag.physical.PhysicalVertex - Job SeaTunnel_Job (696239445162065921), Pipeline: [(1/1)], task: [pipeline-1 [Sink[0]-Paimon-default-identifier]-AggregatedCommitterTask (1/1)] end with state CANCELED
2023-04-06 14:07:10,929 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-863812] [5.1] taskDone, taskId = 20000, taskGroup = TaskGroupLocation{jobId=696239445162065921, pipelineId=1, taskGroupId=1}
2023-04-06 14:07:10,930 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-863812] [5.1] Task TaskGroupLocation{jobId=696239445162065921, pipelineId=1, taskGroupId=1} complete with state CANCELED
2023-04-06 14:07:10,932 INFO  org.apache.seatunnel.engine.server.dag.physical.PhysicalVertex - Job SeaTunnel_Job (696239445162065921), Pipeline: [(1/1)], task: [pipeline-1 [Source[0]-Jdbc-default-identifier]-SplitEnumerator (1/1)] turn to end state CANCELED.
2023-04-06 14:07:10,932 INFO  org.apache.seatunnel.engine.server.dag.physical.PhysicalVertex - Job SeaTunnel_Job (696239445162065921), Pipeline: [(1/1)], task: [pipeline-1 [Source[0]-Jdbc-default-identifier]-SplitEnumerator (1/1)] end with state CANCELED
2023-04-06 14:07:11,005 INFO  org.apache.seatunnel.engine.server.master.JobMaster - release the pipeline Job SeaTunnel_Job (696239445162065921), Pipeline: [(1/1)] resource
2023-04-06 14:07:11,005 INFO  org.apache.seatunnel.engine.server.service.slot.DefaultSlotService - received slot release request, jobID: 696239445162065921, slot: SlotProfile{worker=[localhost]:5801, slotID=3, ownerJobID=696239445162065921, assigned=true, resourceProfile=ResourceProfile{cpu=CPU{core=0}, heapMemory=Memory{bytes=0}}, sequence='98c2bb73-d06f-4f02-9672-feb96f9f9a6c'}
2023-04-06 14:07:11,006 INFO  org.apache.seatunnel.engine.server.service.slot.DefaultSlotService - received slot release request, jobID: 696239445162065921, slot: SlotProfile{worker=[localhost]:5801, slotID=1, ownerJobID=696239445162065921, assigned=true, resourceProfile=ResourceProfile{cpu=CPU{core=0}, heapMemory=Memory{bytes=0}}, sequence='98c2bb73-d06f-4f02-9672-feb96f9f9a6c'}
2023-04-06 14:07:11,006 INFO  org.apache.seatunnel.engine.server.service.slot.DefaultSlotService - received slot release request, jobID: 696239445162065921, slot: SlotProfile{worker=[localhost]:5801, slotID=2, ownerJobID=696239445162065921, assigned=true, resourceProfile=ResourceProfile{cpu=CPU{core=0}, heapMemory=Memory{bytes=0}}, sequence='98c2bb73-d06f-4f02-9672-feb96f9f9a6c'}
2023-04-06 14:07:11,010 INFO  org.apache.seatunnel.engine.server.dag.physical.SubPlan - Job SeaTunnel_Job (696239445162065921), Pipeline: [(1/1)] end with state FAILED
2023-04-06 14:07:11,010 INFO  org.apache.seatunnel.engine.server.dag.physical.PhysicalPlan - cancel job Job SeaTunnel_Job (696239445162065921) because makeJobEndWhenPipelineEnded is true
2023-04-06 14:07:11,010 INFO  org.apache.seatunnel.engine.server.dag.physical.PhysicalPlan - Job SeaTunnel_Job (696239445162065921) turn from state RUNNING to CANCELLING.
2023-04-06 14:07:11,012 WARN  org.apache.seatunnel.engine.server.dag.physical.SubPlan - Job SeaTunnel_Job (696239445162065921), Pipeline: [(1/1)] is in end state FAILED, can not be cancel
2023-04-06 14:07:11,012 INFO  org.apache.seatunnel.engine.server.dag.physical.PhysicalPlan - Job SeaTunnel_Job (696239445162065921) turn from state CANCELLING to FAILING.
2023-04-06 14:07:11,013 INFO  org.apache.seatunnel.engine.server.dag.physical.PhysicalPlan - Job SeaTunnel_Job (696239445162065921) turn from state FAILING to FAILED.
2023-04-06 14:07:11,030 INFO  org.apache.seatunnel.engine.client.job.ClientJobProxy - Job (696239445162065921) end with state FAILED
2023-04-06 14:07:11,030 INFO  com.hazelcast.core.LifecycleService - hz.client_1 [seatunnel-863812] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is SHUTTING_DOWN
2023-04-06 14:07:11,037 INFO  com.hazelcast.internal.server.tcp.TcpServerConnection - [localhost]:5801 [seatunnel-863812] [5.1] Connection[id=1, /127.0.0.1:5801->/127.0.0.1:55703, qualifier=null, endpoint=[127.0.0.1]:55703, remoteUuid=bb88be4a-263c-4b15-abf6-099277a17afe, alive=false, connectionType=JVM, planeIndex=-1] closed. Reason: Connection closed by the other side
2023-04-06 14:07:11,038 INFO  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-863812] [5.1] Removed connection to endpoint: [localhost]:5801:9f6c09a4-b3aa-4450-be80-6260ed6a0937, connection: ClientConnection{alive=false, connectionId=1, channel=NioChannel{/127.0.0.1:55703->localhost/127.0.0.1:5801}, remoteAddress=[localhost]:5801, lastReadTime=2023-04-06 14:07:11.025, lastWriteTime=2023-04-06 14:07:09.206, closedTime=2023-04-06 14:07:11.033, connected server version=5.1}
2023-04-06 14:07:11,038 INFO  com.hazelcast.core.LifecycleService - hz.client_1 [seatunnel-863812] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is CLIENT_DISCONNECTED
2023-04-06 14:07:11,041 INFO  com.hazelcast.client.impl.ClientEndpointManager - [localhost]:5801 [seatunnel-863812] [5.1] Destroying ClientEndpoint{connection=Connection[id=1, /127.0.0.1:5801->/127.0.0.1:55703, qualifier=null, endpoint=[127.0.0.1]:55703, remoteUuid=bb88be4a-263c-4b15-abf6-099277a17afe, alive=false, connectionType=JVM, planeIndex=-1], clientUuid=bb88be4a-263c-4b15-abf6-099277a17afe, clientName=hz.client_1, authenticated=true, clientVersion=5.1, creationTime=1680761219157, latest clientAttributes=lastStatisticsCollectionTime=1680761229193,enterprise=false,clientType=JVM,clientVersion=5.1,clusterConnectionTimestamp=1680761219144,clientAddress=127.0.0.1,clientName=hz.client_1,credentials.principal=null,os.committedVirtualMemorySize=11219894272,os.freePhysicalMemorySize=2503786496,os.freeSwapSpaceSize=0,os.maxFileDescriptorCount=1024000,os.openFileDescriptorCount=140,os.processCpuTime=42300000000,os.systemLoadAverage=0.78,os.totalPhysicalMemorySize=33566371840,os.totalSwapSpaceSize=0,runtime.availableProcessors=16,runtime.freeMemory=154326024,runtime.maxMemory=477626368,runtime.totalMemory=298319872,runtime.uptime=12292,runtime.usedMemory=143996168, labels=[]}
2023-04-06 14:07:11,041 INFO  com.hazelcast.core.LifecycleService - hz.client_1 [seatunnel-863812] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is SHUTDOWN
2023-04-06 14:07:11,042 INFO  org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand - Closed SeaTunnel client......
2023-04-06 14:07:11,042 INFO  com.hazelcast.core.LifecycleService - [localhost]:5801 [seatunnel-863812] [5.1] [localhost]:5801 is SHUTTING_DOWN
2023-04-06 14:07:11,049 INFO  com.hazelcast.internal.partition.impl.MigrationManager - [localhost]:5801 [seatunnel-863812] [5.1] Shutdown request of Member [localhost]:5801 - 9f6c09a4-b3aa-4450-be80-6260ed6a0937 this is handled
2023-04-06 14:07:11,061 INFO  com.hazelcast.instance.impl.Node - [localhost]:5801 [seatunnel-863812] [5.1] Shutting down connection manager...
2023-04-06 14:07:11,063 INFO  com.hazelcast.instance.impl.Node - [localhost]:5801 [seatunnel-863812] [5.1] Shutting down node engine...
2023-04-06 14:07:11,087 INFO  com.hazelcast.instance.impl.NodeExtension - [localhost]:5801 [seatunnel-863812] [5.1] Destroying node NodeExtension.
2023-04-06 14:07:11,087 INFO  com.hazelcast.instance.impl.Node - [localhost]:5801 [seatunnel-863812] [5.1] Hazelcast Shutdown is completed in 40 ms.
2023-04-06 14:07:11,087 INFO  com.hazelcast.core.LifecycleService - [localhost]:5801 [seatunnel-863812] [5.1] [localhost]:5801 is SHUTDOWN
2023-04-06 14:07:11,087 INFO  org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand - Closed HazelcastInstance ......
2023-04-06 14:07:11,087 INFO  org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand - Closed metrics executor service ......
2023-04-06 14:07:11,087 ERROR org.apache.seatunnel.core.starter.SeaTunnel -

===============================================================================


2023-04-06 14:07:11,087 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Fatal Error,

2023-04-06 14:07:11,087 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Please submit bug report in https://github.com/apache/incubator-seatunnel/issues

2023-04-06 14:07:11,087 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Reason:SeaTunnel job executed failed

2023-04-06 14:07:11,089 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:181)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: java.lang.RuntimeException: java.lang.NullPointerException
        at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:206)
        at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:59)
        at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:39)
        at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:27)
        at org.apache.seatunnel.engine.server.task.group.queue.IntermediateBlockingQueue.handleRecord(IntermediateBlockingQueue.java:76)
        at org.apache.seatunnel.engine.server.task.group.queue.IntermediateBlockingQueue.collect(IntermediateBlockingQueue.java:51)
        at org.apache.seatunnel.engine.server.task.flow.IntermediateQueueFlowLifeCycle.collect(IntermediateQueueFlowLifeCycle.java:52)
        at org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask.collect(TransformSeaTunnelTask.java:73)
        at org.apache.seatunnel.engine.server.task.SeaTunnelTask.stateProcess(SeaTunnelTask.java:161)
        at org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask.call(TransformSeaTunnelTask.java:78)
        at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:526)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.NullPointerException
        at org.apache.paimon.data.AbstractBinaryWriter.writeString(AbstractBinaryWriter.java:60)
        at org.apache.paimon.data.BinaryRowWriter.writeString(BinaryRowWriter.java:25)
        at org.apache.seatunnel.connectors.seatunnel.paimon.utils.RowConverter.convert(RowConverter.java:361)
        at org.apache.seatunnel.connectors.seatunnel.paimon.sink.PaimonSinkWriter.write(PaimonSinkWriter.java:107)
        at org.apache.seatunnel.connectors.seatunnel.paimon.sink.PaimonSinkWriter.write(PaimonSinkWriter.java:49)
        at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:201)
        ... 15 more

        at org.apache.seatunnel.engine.client.job.ClientJobProxy.waitForJobComplete(ClientJobProxy.java:119)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:174)
        ... 2 more

2023-04-06 14:07:11,089 ERROR org.apache.seatunnel.core.starter.SeaTunnel -
===============================================================================



Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:181)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: java.lang.RuntimeException: java.lang.NullPointerException
        at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:206)
        at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:59)
        at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:39)
        at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:27)
        at org.apache.seatunnel.engine.server.task.group.queue.IntermediateBlockingQueue.handleRecord(IntermediateBlockingQueue.java:76)
        at org.apache.seatunnel.engine.server.task.group.queue.IntermediateBlockingQueue.collect(IntermediateBlockingQueue.java:51)
        at org.apache.seatunnel.engine.server.task.flow.IntermediateQueueFlowLifeCycle.collect(IntermediateQueueFlowLifeCycle.java:52)
        at org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask.collect(TransformSeaTunnelTask.java:73)
        at org.apache.seatunnel.engine.server.task.SeaTunnelTask.stateProcess(SeaTunnelTask.java:161)
        at org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask.call(TransformSeaTunnelTask.java:78)
        at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:526)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.NullPointerException
        at org.apache.paimon.data.AbstractBinaryWriter.writeString(AbstractBinaryWriter.java:60)
        at org.apache.paimon.data.BinaryRowWriter.writeString(BinaryRowWriter.java:25)
        at org.apache.seatunnel.connectors.seatunnel.paimon.utils.RowConverter.convert(RowConverter.java:361)
        at org.apache.seatunnel.connectors.seatunnel.paimon.sink.PaimonSinkWriter.write(PaimonSinkWriter.java:107)
        at org.apache.seatunnel.connectors.seatunnel.paimon.sink.PaimonSinkWriter.write(PaimonSinkWriter.java:49)
        at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:201)
        ... 15 more

        at org.apache.seatunnel.engine.client.job.ClientJobProxy.waitForJobComplete(ClientJobProxy.java:119)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:174)
        ... 2 more
2023-04-06 14:07:11,091 INFO  org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand - run shutdown hook because get close signal
```

### Java or Scala Version

scala2.12

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gitfortian** [comment]
mysql  ddl:
create table dinky.dlink_job_history
(
    id                         int           not null comment 'id'
        primary key,
    tenant_id                  int default 1 not null comment 'tenant id',
    job_json                   json          null comment 'Job information json',
    exceptions_json            json          null comment 'error message json',
    checkpoints_json           json          null comment 'checkpoints json',
    checkpoints_config_json    json          null comment 'checkpoints configuration json',
    config_json                json          null comment 'configuration',
    jar_json                   json          null comment 'Jar configuration',
    cluster_json               json          null comment 'cluster instance configuration',
    cluster_configuration_json json          null comment 'cluster config',
    update_time                datetime      null comment 'update time'
)
    comment 'Job history details' charset = utf8mb4;


paimon ddl:
CREATE TABLE if not exists ods.dlink_job_history (
    id                         int             comment 'id',
    tenant_id                  int             comment 'tenant id',
    job_json                   string          null comment 'Job information json',
    exceptions_json            string          null comment 'error message json',
    checkpoints_json           string          null comment 'checkpoints json',
    checkpoints_config_json    string          null comment 'checkpoints configuration json',
    config_json                string          null comment 'configuration',
    jar_json                   string          null comment 'Jar configuration',
    cluster_json               string          null comment 'cluster instance configuration',
    cluster_configuration_json string          null comment 'cluster config',
    update_time                TIMESTAMP(0)      null comment 'update time',
    PRIMARY KEY (id) NOT ENFORCED
);

数据样例：
1, 1, '{"jid": "13732c1c008242ba68218383febe3213", "now": 1673084550421, "name": "flinksql", "plan": {"jid": "13732c1c008242ba68218383febe3213", "name": "flinksql", "type": "STREAMING", "nodes": [{"id": "cbc357ccb763df2852fee8c4fc7d55f2", "operator": "", "description": "[1]:TableSourceScan(table=[[my_catalog, default_database, Orders]], fields=[order_number, price, buyer, order_time])<br/>+- Sink: Collect table sink<br/>", "parallelism": 1, "operator_strategy": "", "optimizer_properties": {}}]}, "state": "CANCELED", "duration": 97371, "end-time": 1673084523589, "vertices": [{"id": "cbc357ccb763df2852fee8c4fc7d55f2", "name": "Source: Orders[1] -> Sink: Collect table sink", "tasks": {"FAILED": 0, "CREATED": 0, "RUNNING": 0, "CANCELED": 1, "FINISHED": 0, "CANCELING": 0, "DEPLOYING": 0, "SCHEDULED": 0, "RECONCILING": 0, "INITIALIZING": 0}, "status": "CANCELED", "metrics": {"read-bytes": 0, "write-bytes": 0, "read-records": 0, "write-records": 0, "read-bytes-complete": true, "write-bytes-complete": true, "accumulated-busy-time": "NaN", "accumulated-idle-time": 0, "read-records-complete": true, "write-records-complete": true, "accumulated-backpressured-time": 0}, "duration": 89530, "end-time": 1673084523583, "start-time": 1673084434053, "parallelism": 1, "maxParallelism": 128}], "start-time": 1673084426218, "timestamps": {"FAILED": 0, "CREATED": 1673084426408, "FAILING": 0, "RUNNING": 1673084427378, "CANCELED": 1673084523589, "FINISHED": 0, "SUSPENDED": 0, "CANCELLING": 1673084523442, "RESTARTING": 0, "RECONCILING": 0, "INITIALIZING": 1673084426218}, "isStoppable": false, "status-counts": {"FAILED": 0, "CREATED": 0, "RUNNING": 0, "CANCELED": 1, "FINISHED": 0, "CANCELING": 0, "DEPLOYING": 0, "SCHEDULED": 0, "RECONCILING": 0, "INITIALIZING": 0}, "maxParallelism": -1}', '{"timestamp": null, "truncated": false, "all-exceptions": [], "root-exception": null, "exceptionHistory": {"entries": [], "truncated": false}}', '{"counts": {"total": 0, "failed": 0, "restored": 0, "completed": 0, "in_progress": 0}, "latest": {"failed": null, "restored": null, "completed": null, "savepoint": null}, "history": [], "summary": {"state_size": {"avg": 0, "max": 0, "min": 0, "p50": "NaN", "p90": "NaN", "p95": "NaN", "p99": "NaN", "p999": "NaN"}, "persisted_data": {"avg": 0, "max": 0, "min": 0, "p50": "NaN", "p90": "NaN", "p95": "NaN", "p99": "NaN", "p999": "NaN"}, "processed_data": {"avg": 0, "max": 0, "min": 0, "p50": "NaN", "p90": "NaN", "p95": "NaN", "p99": "NaN", "p999": "NaN"}, "checkpointed_size": {"avg": 0, "max": 0, "min": 0, "p50": "NaN", "p90": "NaN", "p95": "NaN", "p99": "NaN", "p999": "NaN"}, "alignment_buffered": {"avg": 0, "max": 0, "min": 0, "p50": 0, "p90": 0, "p95": 0, "p99": 0, "p999": 0}, "end_to_end_duration": {"avg": 0, "max": 0, "min": 0, "p50": "NaN", "p90": "NaN", "p95": "NaN", "p99": "NaN", "p999": "NaN"}}}', '{"mode": "at_least_once", "timeout": 600000, "interval": 9223372036854775807, "min_pause": 0, "state_backend": "HashMapStateBackend", "max_concurrent": 1, "externalization": {"enabled": false, "delete_on_cancellation": true}, "changelog_storage": "memory", "checkpoint_storage": "FileSystemCheckpointStorage", "unaligned_checkpoints": false, "state_changelog_enabled": false, "aligned_checkpoint_timeout": 0, "tolerable_failed_checkpoints": 0, "checkpoints_after_tasks_finish": true, "changelog_periodic_materialization_interval": 600000}', '{"jid": "13732c1c008242ba68218383febe3213", "name": "flinksql", "execution-config": {"user-config": {}, "execution-mode": "PIPELINED", "job-parallelism": 1, "restart-strategy": "Cluster level default restart strategy", "object-reuse-mode": false}}', null, '{"id": 1, "name": "flink-1.16-yarn-session", "note": null, "type": "yarn-session", "alias": "flink-1.16-yarn-session", "hosts": "hdp03:32956", "status": 1, "taskId": null, "enabled": true, "version": "1.16.0", "tenantId": 1, "createTime": [2023, 1, 7, 16, 43, 51], "updateTime": [2023, 1, 7, 16, 43, 51], "autoRegisters": false, "jobManagerHost": "xxx:32956", "clusterConfigurationId": null}', null, '2023-01-07 17:42:30'
