### ISSUE TITLE
[Bug] [MYSQL CDC] Data row is smaller than a column index

### ISSUE THREAD

**Issue by huang714669** [apache/seatunnel#4601]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

使用mysqlcdc将源数据同步的目标mysql实例中，前面同步历史数据正常，到最后增量同步报Data row is smaller than a column index异常，原数据库和目标数据库版本都是mysql 5.7.x

### SeaTunnel Version

2.3.1

### SeaTunnel Config

```conf
env {
  job.mode = "STREAMING"
  execution.parallelism = 1 
  checkpoint.interval = 10000
}
source {
  MySQL-CDC {
    result_table_name = "source"
  #  parallelism = 1 
    server-id = 5656
    username = "root"
    password = "test1234"
    table-names = ["xx.source"]
    base-url = "jdbc:mysql://xxxx:3306/xx"
    startup.mode = "initial"
    debezium {
        snapshot.mode = "never"
        decimal.handling.mode = "double"
    }   
  }
}
#transform {
#}
sink {
    jdbc {
            url = "jdbc:mysql://xxxx:3306/xx"
            driver = "com.mysql.cj.jdbc.Driver"
            user = "root"
            password = "xx"
            database = "xx" 
            table = target
            # cdc options
            primary_keys = ["id"]
            source_table_name = "source"
            support_upsert_by_query_primary_key_exist = true
          
     }   
}
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/v2.mysqlcdc.conf.template -e local > seatunnel.log 2>&1 &
```

### Error Exception

```log
2023-04-18 01:08:24,019 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
    at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:181)
    at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
    at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: java.lang.RuntimeException: One or more fetchers have encountered exception
    at org.apache.seatunnel.connectors.seatunnel.common.source.reader.fetcher.SplitFetcherManager.checkErrors(SplitFetcherManager.java:147)
    at org.apache.seatunnel.connectors.seatunnel.common.source.reader.SourceReaderBase.getNextFetch(SourceReaderBase.java:159)
    at org.apache.seatunnel.connectors.seatunnel.common.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:92)
    at org.apache.seatunnel.connectors.cdc.base.source.reader.IncrementalSourceReader.pollNext(IncrementalSourceReader.java:92)
    at org.apache.seatunnel.engine.server.task.flow.SourceFlowLifeCycle.collect(SourceFlowLifeCycle.java:135)
    at org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask.collect(SourceSeaTunnelTask.java:84)
    at org.apache.seatunnel.engine.server.task.SeaTunnelTask.stateProcess(SeaTunnelTask.java:161)
    at org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask.call(SourceSeaTunnelTask.java:89)
    at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:526)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: SplitFetcher thread 0 received unexpected exception while polling the records
    at org.apache.seatunnel.connectors.seatunnel.common.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:165)
    at org.apache.seatunnel.connectors.seatunnel.common.source.reader.fetcher.SplitFetcher.run(SplitFetcher.java:81)
    ... 5 more
Caused by: org.apache.kafka.connect.errors.ConnectException: An exception occurred in the change event producer. This connector will be stopped.
    at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:42)
    at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleEvent(MySqlStreamingChangeEventSource.java:366)
    at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.lambda$execute$25(MySqlStreamingChangeEventSource.java:842)
    at com.github.shyiko.mysql.binlog.BinaryLogClient.notifyEventListeners(BinaryLogClient.java:1125)
    at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:973)
    at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:599)
    at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:857)
    ... 1 more
Caused by: io.debezium.DebeziumException: Error processing binlog event
    ... 7 more
Caused by: org.apache.kafka.connect.errors.ConnectException: Error while processing event at offset {transaction_id=null, ts_sec=1681739628, file=mysql-bin.000121, pos=96096841, gtids=d1ce04e2-5830-11ec-b9ae-b8cef6c118f8:1-4440890,f9ae30a6-435d-11ec-ac31-b8cef6b6efb5:1-29861, row=1, server_id=323561, event=4}
    at io.debezium.pipeline.EventDispatcher.dispatchDataChangeEvent(EventDispatcher.java:253)
    at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.lambda$handleDelete$8(MySqlStreamingChangeEventSource.java:705)
    at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleChange(MySqlStreamingChangeEventSource.java:732)
    at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleDelete(MySqlStreamingChangeEventSource.java:704)
    at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.lambda$execute$20(MySqlStreamingChangeEventSource.java:828)
    at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleEvent(MySqlStreamingChangeEventSource.java:349)
    ... 6 more
Caused by: org.apache.kafka.connect.errors.ConnectException: Data row is smaller than a column index, internal schema representation is probably out of sync with real database schema
    at io.debezium.relational.TableSchemaBuilder.validateIncomingRowToInternalMetadata(TableSchemaBuilder.java:221)
    at io.debezium.relational.TableSchemaBuilder.lambda$createValueGenerator$5(TableSchemaBuilder.java:250)
    at io.debezium.relational.TableSchema.valueFromColumnData(TableSchema.java:141)
    at io.debezium.relational.RelationalChangeRecordEmitter.emitDeleteRecord(RelationalChangeRecordEmitter.java:133)
    at io.debezium.relational.RelationalChangeRecordEmitter.emitChangeRecords(RelationalChangeRecordEmitter.java:54)
    at io.debezium.pipeline.EventDispatcher.dispatchDataChangeEvent(EventDispatcher.java:217)
    ... 11 more

    at org.apache.seatunnel.engine.client.job.ClientJobProxy.waitForJobComplete(ClientJobProxy.java:119)
    at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:174)
    ... 2 more
```

### Java or Scala Version

openjdk version "11.0.18" 2023-01-17 LTS

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Level1Accelerator** [comment]
+1

**Comment by Level1Accelerator** [comment]
> +1

2.3.12，mysqlcdc

**Comment by DanielLeens** [comment]
Thanks for confirming that you may still be seeing a similar symptom on 2.3.12. I checked the original issue again. The historical stack here is in the Debezium binlog-processing path, where the incoming row shape no longer matches the internal schema metadata.

At the moment, though, the new update only says `2.3.12, mysqlcdc` and does not include a current full stack trace or reproduction details. Because the original report was from 2.3.1, I do not want to assume the 2026 reproduction is automatically the same root cause. Could you please share the full current stack trace, the table DDL, whether any online DDL happened before the failure, and the minimal SeaTunnel config?
