### ISSUE TITLE
[Bug] [connector-cdc] Don't support sending SourceEvent

### ISSUE THREAD

**Issue by jiangzzwy** [apache/seatunnel#4609]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

使用Zeta引擎执行CDC抽取数据进入Kafka是正常的，但是切换到Flink引擎就报错了；报如下错误：Caused by: java.lang.UnsupportedOperationException: Flink ParallelSource don't support sending SourceEvent. Please implement the `SupportCoordinate` marker interface on the SeaTunnel source.

### SeaTunnel Version

2.3.1

### SeaTunnel Config

```conf
env {
  execution.parallelism = 3
  job.mode = "STREAMING"
  checkpoint.interval = 2000
}

source {
   MySQL-CDC {
    result_table_name = "fake"
    parallelism = 1
    server-id = 5656
    username = "root"
    password = "***"
    table-names = ["ke.t_1","ke.t_2"]
    base-url = "jdbc:mysql://ZBMac-VPFV0G77T:3306/ke"
  }
}

sink {

    Kafka {
      topic = "t_count"
      bootstrap.servers = "localhost:9092"
  }

}
```

### Running Command

```shell
% ./bin/start-seatunnel-flink-13-connector-v2.sh --config ./config/fmq_kafka1.template -d
```

### Error Exception

```log
Caused by: java.lang.UnsupportedOperationException: Flink ParallelSource don't support sending SourceEvent. Please implement the `SupportCoordinate` marker interface on the SeaTunnel source.
	at org.apache.seatunnel.translation.source.ParallelReaderContext.sendSourceEventToEnumerator(ParallelReaderContext.java:61)
	at org.apache.seatunnel.connectors.cdc.base.source.reader.IncrementalSourceReader.reportFinishedSnapshotSplitsIfNeed(IncrementalSourceReader.java:148)
	at org.apache.seatunnel.connectors.cdc.base.source.reader.IncrementalSourceReader.addSplits(IncrementalSourceReader.java:115)
	at org.apache.seatunnel.translation.source.ParallelSource.addSplits(ParallelSource.java:181)
	at org.apache.seatunnel.translation.source.ParallelEnumeratorContext.assignSplit(ParallelEnumeratorContext.java:62)
	at org.apache.seatunnel.api.source.SourceSplitEnumerator$Context.assignSplit(SourceSplitEnumerator.java:101)
	at org.apache.seatunnel.connectors.cdc.base.source.enumerator.IncrementalSourceEnumerator.assignSplits(IncrementalSourceEnumerator.java:159)
	at org.apache.seatunnel.connectors.cdc.base.source.enumerator.IncrementalSourceEnumerator.run(IncrementalSourceEnumerator.java:69)
	at org.apache.seatunnel.translation.source.ParallelSource.lambda$run$0(ParallelSource.java:126)
	... 7 more
```

### Flink or Spark Version

1.12.5

### Java or Scala Version

java

### Screenshots

![image](https://user-images.githubusercontent.com/23492991/232695706-3e218cdf-63ba-43a9-af32-806555803701.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hailin0** [comment]
here https://github.com/apache/incubator-seatunnel/issues/4605
