### ISSUE TITLE
[Bug] [Connectors V2] data type in array is not supported: DateTime

### ISSUE THREAD

**Issue by PayneZx** [apache/seatunnel#4654]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When i use seatunnel transfer data,source is clickhouse,but clickhouse have a column type is `Array(DateTime)`

### SeaTunnel Version

2.3.1

### SeaTunnel Config

```conf
env {
  execution.parallelism = 2
  job.mode = "BATCH"
  checkpoint.interval = 10000
}

source {
  Clickhouse {
    host = "xxx:8123"
    database = "xx"
    sql = "select * from xx"
    username = "xxx"
    password = "xxx"
    # result_table_name = "xxx"
  }

  # If you would like to get more information about how to configure Seatunnel and see full list of source plugins,
  # please go to https://seatunnel.apache.org/docs/category/source-v2
}

sink {
  Hive {
    table_name = "xxx"
    metastore_uri = "thrift://xxx:9083"
  }
}
```

### Running Command

```shell
sh bin/seatunnel.sh --config config/xxx.batch.config -e local
```

### Error Exception

```log
Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:181)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.connectors.seatunnel.clickhouse.exception.ClickhouseConnectorException: ErrorCode:[COMMON-07], ErrorDescription:[Unsupported data type] - data type in array is not supported: DateTime
	at org.apache.seatunnel.connectors.seatunnel.clickhouse.util.TypeConvertUtil.convert(TypeConvertUtil.java:66)
	at org.apache.seatunnel.connectors.seatunnel.clickhouse.source.ClickhouseSource.prepare(ClickhouseSource.java:112)
	at org.apache.seatunnel.engine.core.parse.ConnectorInstanceLoader.loadSourceInstance(ConnectorInstanceLoader.java:64)
	at org.apache.seatunnel.engine.core.parse.JobConfigParser.sampleAnalyze(JobConfigParser.java:371)
	at org.apache.seatunnel.engine.core.parse.JobConfigParser.parse(JobConfigParser.java:132)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:112)
	at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.getLogicalDag(JobExecutionEnvironment.java:155)
	at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:147)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:140)
	... 2 more
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by PayneZx** [comment]
I want to know what is the reason for not supporting Array(DateTime)

**Comment by EricJoy2048** [comment]
> I want to know what is the reason for not supporting Array(DateTime)

Do you have some ideas to support it?

**Comment by PayneZx** [comment]
I originally added an instance of datetime to `BasicType`,and modify ` equals` function for datetime type.But when I try to add type process in `TypeConvertUtil.valueUnwrap`, in ArrayType check add code,like
```
            } else if (LocalDateTime[].class.equals(typeClass)) {
                return record.asArray(LocalDateTime.class);
```
it can't  work,error message is `Cannot cast java.time.OffsetDateTime to java.sql.Timestamp`. Now i don't how to complete this part of the conversion.
