### ISSUE TITLE
org.apache.pulsar.client.impl.ConsumerImpl - [my-topic] [my-topic] Closed Consumer (not connected)

### ISSUE THREAD

**Issue by fyzn12** [apache/seatunnel#4684]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

When I started a job with the Seatunnel Engine, the pulsar connection was established and immediately disconnected。
My source configuration is as follows：
source {
  # This is a example source plugin **only for test and demonstrate the feature source plugin**
  Pulsar {
      result_table_name = "test-user"
      topic = "my-topic"
      subscription.name = "my-topic"
      client.service-url = "pulsar://localhost:6650"
      subscription.type = "Shared"
      admin.service-url = "http://localhost:8080"
      format = text
      cursor.startup.mode = "LATEST"
      #cursor.stop.mode = "NEVER"
      topic-discovery.interval = 1
      schema = {
       fields {
         __value__ = "String"
       }
      }
  }
}

Could you please tell me how to change the source of pulsar so that the consumer of pulsar will not disconnect？

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fyzn12** [comment]
The job executes without error, but the pulsar consumer is disconnected after the connection

**Comment by kim-up** [comment]
Your job mode is `batch`?

Try run it use `STREAMING`:
```
env {
 ....
  job.mode = "STREAMING"
 ....
```

**Comment by fyzn12** [comment]
> STREAMING

My job mode is STREAMING

**Comment by fyzn12** [comment]
> Your job mode is `batch`?
> 
> Try run it use `STREAMING`:
> 
> ```
> env {
>  ....
>   job.mode = "STREAMING"
>  ....
> ```
My env configuration is as follows：

env {
  # You can set flink configuration here
  execution.parallelism = 2
  job.mode = "STREAMING"
  checkpoint.interval = 2000
  #execution.checkpoint.interval = 10000
  #execution.checkpoint.data-uri = "hdfs://localhost:9000/checkpoint"
}

**Comment by fyzn12** [comment]
I get the following error when executing with the flink engine：
java.lang.NoClassDefFoundError: Could not initialize class org.apache.pulsar.client.admin.internal.PulsarAdminImpl
	at org.apache.pulsar.client.admin.internal.PulsarAdminBuilderImpl.build(PulsarAdminBuilderImpl.java:47)
	at org.apache.seatunnel.connectors.seatunnel.pulsar.config.PulsarConfigUtil.createAdmin(PulsarConfigUtil.java:46)
	at org.apache.seatunnel.connectors.seatunnel.pulsar.source.enumerator.PulsarSplitEnumerator.open(PulsarSplitEnumerator.java:132)
	at org.apache.seatunnel.translation.source.ParallelSource.open(ParallelSource.java:111)
	at org.apache.seatunnel.translation.flink.source.BaseSeaTunnelSourceFunction.open(BaseSeaTunnelSourceFunction.java:78)
	at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:34)
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:101)
	at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.initializeStateAndOpenOperators(RegularOperatorChain.java:107)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreGates(StreamTask.java:734)
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$SynchronizedStreamTaskActionExecutor.call(StreamTaskActionExecutor.java:100)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreInternal(StreamTask.java:709)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restore(StreamTask.java:675)
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:952)
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:921)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:745)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:562)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by kim-up** [comment]
@fyzn12  Which seaTunnel version did you use ?

**Comment by fyzn12** [comment]
> @fyzn12 Which seaTunnel version did you use ?

2.3.1

**Comment by fyzn12** [comment]
> > @fyzn12 Which seaTunnel version did you use ?
> 
> 2.3.1

My flink version is 1.17

**Comment by kim-up** [comment]
@fyzn12  I have reappeared.
![image](https://user-images.githubusercontent.com/9264192/235083500-cfe13f28-a0a0-40bc-a3de-0cf55662be9c.png)

You can temporarily put the related packages of  `org.slf4j:jul-to-slf4j:1.7.25` into flink/lib or seatunnel/lib and try again

**Comment by hailin0** [comment]
reference
https://github.com/apache/incubator-seatunnel/pull/4118

**Comment by kim-up** [comment]
@hailin0 Received, I  will submit a pr to solve it.

**Comment by fyzn12** [comment]
> org.slf4j:jul-to-slf4j:1.7.25

I have put org.slf4j:jul-to-slf4j:1.7.25 dependency package can start normally, but using the flink engine still cannot start normally
