### ISSUE TITLE
[Bug] [connector-v2] Can't find config file when spark standalone cluster submit

### ISSUE THREAD

**Issue by liuyongfei1** [apache/seatunnel#4707]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

when spark standalone cluster submit seatunnel job，Can't find config file。
一：config.file:

env {
  execution.parallelism = 1
  job.mode = "BATCH"
}

source {
    FakeSource {
      result_table_name = "fake"
      row.num = 16
      schema = {
        fields {
          name = "string"
          age = "int"
        }
      }
    }
}

sink {
  Console {}
}

二. command
/data/app/apache-seatunnel-incubating-2.3.1/bin/start-seatunnel-spark-2-connector-v2.sh --master spark://starrocks-33:7077 --deploy-mode cluster --config /data/app/apache-seatunnel-incubating-2.3.1/config/seatunnel.streaming.conf_lyf_test_0505.template

三.Following error occurred:
23/05/05 16:10:35 ERROR SeaTunnel: 

===============================================================================

23/05/05 16:10:35 ERROR SeaTunnel: Fatal Error, 

23/05/05 16:10:35 ERROR SeaTunnel: Please submit bug report in https://github.com/apache/incubator-seatunnel/issues

23/05/05 16:10:35 ERROR SeaTunnel: Reason:ErrorCode:[COMMON-01], ErrorDescription:[File operation failed, such as (read,list,write,move,copy,sync) etc...] - Can't find config file: seatunnel.streaming.conf_lyf_test_0505.template 

23/05/05 16:10:35 ERROR SeaTunnel: Exception StackTrace:org.apache.seatunnel.common.exception.SeaTunnelRuntimeException: ErrorCode:[COMMON-01], ErrorDescription:[File operation failed, such as (read,list,write,move,copy,sync) etc...] - Can't find config file: seatunnel.streaming.conf_lyf_test_0505.template
	at org.apache.seatunnel.core.starter.utils.FileUtils.checkConfigExist(FileUtils.java:68)
	at org.apache.seatunnel.core.starter.spark.command.SparkTaskExecuteCommand.execute(SparkTaskExecuteCommand.java:50)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.spark.SeaTunnelSpark.main(SeaTunnelSpark.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.worker.DriverWrapper$.main(DriverWrapper.scala:65)
	at org.apache.spark.deploy.worker.DriverWrapper.main(DriverWrapper.scala)
 
23/05/05 16:10:35 ERROR SeaTunnel: 

### SeaTunnel Version

2.3.1

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
  job.mode = "BATCH"
}

source {
    FakeSource {
      result_table_name = "fake"
      row.num = 16
      schema = {
        fields {
          name = "string"
          age = "int"
        }
      }
    }
}

sink {
  Console {}
}
```

### Running Command

```shell
/data/app/apache-seatunnel-incubating-2.3.1/bin/start-seatunnel-spark-2-connector-v2.sh --master spark://starrocks-33:7077 --deploy-mode cluster --config /data/app/apache-seatunnel-incubating-2.3.1/config/seatunnel.streaming.conf_lyf_test_0505.template
```

### Error Exception

```log
23/05/05 16:10:35 ERROR SeaTunnel: 

===============================================================================


23/05/05 16:10:35 ERROR SeaTunnel: Fatal Error, 

23/05/05 16:10:35 ERROR SeaTunnel: Please submit bug report in https://github.com/apache/incubator-seatunnel/issues

23/05/05 16:10:35 ERROR SeaTunnel: Reason:ErrorCode:[COMMON-01], ErrorDescription:[File operation failed, such as (read,list,write,move,copy,sync) etc...] - Can't find config file: seatunnel.streaming.conf_lyf_test_0505.template 

23/05/05 16:10:35 ERROR SeaTunnel: Exception StackTrace:org.apache.seatunnel.common.exception.SeaTunnelRuntimeException: ErrorCode:[COMMON-01], ErrorDescription:[File operation failed, such as (read,list,write,move,copy,sync) etc...] - Can't find config file: seatunnel.streaming.conf_lyf_test_0505.template
	at org.apache.seatunnel.core.starter.utils.FileUtils.checkConfigExist(FileUtils.java:68)
	at org.apache.seatunnel.core.starter.spark.command.SparkTaskExecuteCommand.execute(SparkTaskExecuteCommand.java:50)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.spark.SeaTunnelSpark.main(SeaTunnelSpark.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.worker.DriverWrapper$.main(DriverWrapper.scala:65)
	at org.apache.spark.deploy.worker.DriverWrapper.main(DriverWrapper.scala)
 
23/05/05 16:10:35 ERROR SeaTunnel:
```

### Flink or Spark Version

spark 2.4.8，standalone模式，且是单节点

### Java or Scala Version

java 1.8

### Screenshots

![Snipaste_2023-05-05_16-11-36](https://user-images.githubusercontent.com/4757906/236408784-19dbfe01-5b04-42ac-95b8-11d121972780.jpg)

![Snipaste_2023-05-05_16-16-45](https://user-images.githubusercontent.com/4757906/236409131-787acc1e-3a75-4d96-844a-a7009804caae.jpg)

![Snipaste_2023-05-05_16-15-25](https://user-images.githubusercontent.com/4757906/236408802-628de0d0-b0ba-406b-b99b-77318a92bb27.jpg)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment]
@TyrantLucifer  PTAL.

**Comment by TyrantLucifer** [comment]
Use client mode submit job，not cluster mode
