### ISSUE TITLE
[Bug] [Transform] Transform-V2 sql add column error can't find field "xx新增字段内容"

### ISSUE THREAD

**Issue by gaopeng666** [apache/seatunnel#4785]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I want to synchronize csv data to Doris, and add a field in transform SQL, but the error can't find field "xxx" is reported, which can be used in the previous 2.1.3 v1 version

### SeaTunnel Version

2.3.1

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
  job.mode = "BATCH"
}

source {
  
 LocalFile {
  path = "/root/test.csv"
  file_format_type = "csv"
  skip_header_row_number = 1
  schema {
    fields {
	  time = string
	  device_id = string
	  signal_id = string
	  value = string
	  string_value = string
	  create_time = string
    }
 }
 result_table_name = "c_electricity"
}

}


transform {
 sql {
    source_table_name = "c_electricity"
    query = "select TRIM(BOTH '\"' FROM time) as time, TRIM(BOTH '\"' FROM device_id) as device_id, TRIM(BOTH '\"' FROM signal_id) as signal_id, \"xx新增字段内容\" as source, TRIM(BOTH '\"' FROM value) as value, TRIM(BOTH '\"' FROM string_value) as string_value, TRIM(BOTH '\"' FROM create_time) as create_time from c_electricity"
    result_table_name = "c_electricity_new"
 }
}

sink {
 Doris {
		source_table_name = "c_electricity_new"
        fenodes = "172.16.150.19:8030"
        username = root
        password = "Trendy@123"
        table.identifier = "ecs_analyze.c_electricity"
        sink.enable-2pc = "true"
        sink.label-prefix = "c_electricity_1"
        doris.config = {
          format = "csv"
          column_separator = ","
        }
    } 

}
```

### Running Command

```shell
bin/seatunnel.sh --config ./config/test.conf
```

### Error Exception

```log
2023-05-19 15:27:18,947 ERROR org.apache.seatunnel.core.starter.SeaTunnel - 

===============================================================================


2023-05-19 15:27:18,947 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Fatal Error, 

2023-05-19 15:27:18,947 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Please submit bug report in https://github.com/apache/incubator-seatunnel/issues

2023-05-19 15:27:18,947 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Reason:SeaTunnel job executed failed 

2023-05-19 15:27:18,948 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:181)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: java.lang.IllegalArgumentException: can't find field "广东"
	at org.apache.seatunnel.api.table.type.SeaTunnelRowType.indexOf(SeaTunnelRowType.java:82)
	at org.apache.seatunnel.transform.sqlengine.zeta.ZetaSQLType.getExpressionType(ZetaSQLType.java:86)
	at org.apache.seatunnel.transform.sqlengine.zeta.ZetaSQLEngine.typeMapping(ZetaSQLEngine.java:162)
	at org.apache.seatunnel.transform.SQLTransform.transformRowType(SQLTransform.java:90)
	at org.apache.seatunnel.transform.common.AbstractSeaTunnelTransform.setTypeInfo(AbstractSeaTunnelTransform.java:69)
	at org.apache.seatunnel.engine.core.parse.JobConfigParser.sampleAnalyze(JobConfigParser.java:387)
	at org.apache.seatunnel.engine.core.parse.JobConfigParser.parse(JobConfigParser.java:132)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:112)
	at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.getLogicalDag(JobExecutionEnvironment.java:155)
	at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:147)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:140)
	... 2 more
 
2023-05-19 15:27:18,949 ERROR org.apache.seatunnel.core.starter.SeaTunnel - 
===============================================================================



Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:181)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: java.lang.IllegalArgumentException: can't find field "广东"
	at org.apache.seatunnel.api.table.type.SeaTunnelRowType.indexOf(SeaTunnelRowType.java:82)
	at org.apache.seatunnel.transform.sqlengine.zeta.ZetaSQLType.getExpressionType(ZetaSQLType.java:86)
	at org.apache.seatunnel.transform.sqlengine.zeta.ZetaSQLEngine.typeMapping(ZetaSQLEngine.java:162)
	at org.apache.seatunnel.transform.SQLTransform.transformRowType(SQLTransform.java:90)
	at org.apache.seatunnel.transform.common.AbstractSeaTunnelTransform.setTypeInfo(AbstractSeaTunnelTransform.java:69)
	at org.apache.seatunnel.engine.core.parse.JobConfigParser.sampleAnalyze(JobConfigParser.java:387)
	at org.apache.seatunnel.engine.core.parse.JobConfigParser.parse(JobConfigParser.java:132)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:112)
	at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.getLogicalDag(JobExecutionEnvironment.java:155)
	at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:147)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:140)
	... 2 more
```

### Flink or Spark Version

seatunnel engine 

### Java or Scala Version

jdk 1.8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
Hi @rewerma ,PTAL.

**Comment by gaopeng666** [comment]
Problem solved, ANSI SQL added string query is ' instead of "
`if (expression instanceof StringValue) {
            return BasicType.STRING_TYPE;
        }
        if (expression instanceof Column) {
            String columnName = ((Column) expression).getColumnName();
            return inputRowType.getFieldType(inputRowType.indexOf(columnName));
        }`
