### ISSUE TITLE
[Bug] failed to run seatunnel with flink operator following the guidance of document

### ISSUE THREAD

**Issue by kksxf** [apache/seatunnel#4788]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I tried to run seatunnel demo following the guidance of [seatunnel document](https://seatunnel.apache.org/docs/2.3.1/start-v2/kubernetes/), but an error occurred after deployment using `kubectl apply -f seatunnel-flink.yaml`   

```
2023-05-19 12:35:17,812 ERROR org.apache.flink.runtime.entrypoint.ClusterEntrypoint        [] - Could not create application program.                                                                    
  org.apache.flink.util.FlinkException: Could not load the provided entrypoint class.                                                                                                                       
      at org.apache.flink.client.deployment.application.ClassPathPackagedProgramRetriever.getPackagedProgram(ClassPathPackagedProgramRetriever.java:178) ~[flink-dist_2.12-1.13.6.jar:1.13.6]               
      at org.apache.flink.kubernetes.entrypoint.KubernetesApplicationClusterEntrypoint.getPackagedProgram(KubernetesApplicationClusterEntrypoint.java:101) ~[flink-dist_2.12-1.13.6.jar:1.13.6]             
      at org.apache.flink.kubernetes.entrypoint.KubernetesApplicationClusterEntrypoint.main(KubernetesApplicationClusterEntrypoint.java:71) [flink-dist_2.12-1.13.6.jar:1.13.6]                             
  Caused by: org.apache.flink.client.program.ProgramInvocationException: JAR file does not exist '/opt/seatunnel/starter/seatunnel-flink-starter.jar'                                                       
      at org.apache.flink.client.program.PackagedProgram.checkJarFile(PackagedProgram.java:617) ~[flink-dist_2.12-1.13.6.jar:1.13.6]                                                                        
      at org.apache.flink.client.program.PackagedProgram.loadJarFile(PackagedProgram.java:465) ~[flink-dist_2.12-1.13.6.jar:1.13.6]                                                                         
      at org.apache.flink.client.program.PackagedProgram.<init>(PackagedProgram.java:135) ~[flink-dist_2.12-1.13.6.jar:1.13.6]                                                                              
      at org.apache.flink.client.program.PackagedProgram.<init>(PackagedProgram.java:65) ~[flink-dist_2.12-1.13.6.jar:1.13.6]                                                                               
      at org.apache.flink.client.program.PackagedProgram$Builder.build(PackagedProgram.java:691) ~[flink-dist_2.12-1.13.6.jar:1.13.6]                                                                       
      at org.apache.flink.client.deployment.application.ClassPathPackagedProgramRetriever.getPackagedProgram(ClassPathPackagedProgramRetriever.java:167) ~[flink-dist_2.12-1.13.6.jar:1.13.6]               
      ... 2 more                                                                                                                                                                                            
  Caused by: java.io.IOException: JAR file does not exist '/opt/seatunnel/starter/seatunnel-flink-starter.jar'                                                                                              
      at org.apache.flink.util.JarUtils.checkJarFile(JarUtils.java:46) ~[flink-dist_2.12-1.13.6.jar:1.13.6]                                                                                                 
      at org.apache.flink.client.program.PackagedProgram.checkJarFile(PackagedProgram.java:615) ~[flink-dist_2.12-1.13.6.jar:1.13.6]                                                                        
      at org.apache.flink.client.program.PackagedProgram.loadJarFile(PackagedProgram.java:465) ~[flink-dist_2.12-1.13.6.jar:1.13.6]                                                                         
      at org.apache.flink.client.program.PackagedProgram.<init>(PackagedProgram.java:135) ~[flink-dist_2.12-1.13.6.jar:1.13.6]                                                                              
      at org.apache.flink.client.program.PackagedProgram.<init>(PackagedProgram.java:65) ~[flink-dist_2.12-1.13.6.jar:1.13.6]                                                                               
      at org.apache.flink.client.program.PackagedProgram$Builder.build(PackagedProgram.java:691) ~[flink-dist_2.12-1.13.6.jar:1.13.6]                                                                       
      at org.apache.flink.client.deployment.application.ClassPathPackagedProgramRetriever.getPackagedProgram(ClassPathPackagedProgramRetriever.java:167) ~[flink-dist_2.12-1.13.6.jar:1.13.6]               
      ... 2 more
```

**Dockerfile**
```
FROM flink:1.13

ENV SEATUNNEL_VERSION="2.3.1"
ENV SEATUNNEL_HOME = "/opt/seatunnel"

RUN mkdir -p $SEATUNNEL_HOME

RUN wget https://archive.apache.org/dist/incubator/seatunnel/${SEATUNNEL_VERSION}/apache-seatunnel-incubating-${SEATUNNEL_VERSION}-bin.tar.gz
RUN tar -xzvf apache-seatunnel-incubating-${SEATUNNEL_VERSION}-bin.tar.gz

RUN cp -r apache-seatunnel-incubating-${SEATUNNEL_VERSION}/* $SEATUNNEL_HOME/
RUN rm -rf apache-seatunnel-incubating-${SEATUNNEL_VERSION}*
```

**FlinkDeployment**

```
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: seatunnel-flink-streaming-example
spec:
  image: seatunnel:2.3.1-flink-1.13
  flinkVersion: v1_13
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
  serviceAccount: flink
  jobManager:
    replicas: 1
    resource:
      memory: "1024m"
      cpu: 1
  taskManager:
    resource:
      memory: "1024m"
      cpu: 1
  podTemplate:
    spec:
      containers:
        - name: flink-main-container
          volumeMounts:
            - name: seatunnel-config
              mountPath: /data/seatunnel.streaming.conf
              subPath: seatunnel.streaming.conf
      volumes:
        - name: seatunnel-config
          configMap:
            name: seatunnel-config
            items:
            - key: seatunnel.streaming.conf
              path: seatunnel.streaming.conf
  job:
    jarURI: local:///opt/seatunnel/starter/seatunnel-flink-starter.jar
    entryClass: org.apache.seatunnel.core.starter.flink.SeatunnelFlink
    args: ["--config", "/data/seatunnel.streaming.conf"]
    parallelism: 2
    upgradeMode: stateless

```

I believe there are several places in the document need to be updated or corrected in SeaTunnel 2.3.1
I will summarize theses places to help the demo work in SeaTunnel 2.3.1 and maybe submit a PR later if that helps 

### SeaTunnel Version

2.3.1

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
  job.mode = "STREAMING"
  checkpoint.interval = 2000
}

source {
    FakeSource {
      result_table_name = "fake"
      row.num = 160000
      schema = {
        fields {
          name = "string"
          age = "int"
        }
      }
    }
}

transform {

}

sink {
  Console {}
}
```

### Running Command

```shell
kubectl apply -f seatunnel-flink.yaml
```

### Error Exception

```log
2023-05-19 12:35:17,812 ERROR org.apache.flink.runtime.entrypoint.ClusterEntrypoint        [] - Could not create application program.                                                                    
  org.apache.flink.util.FlinkException: Could not load the provided entrypoint class.                                                                                                                       
      at org.apache.flink.client.deployment.application.ClassPathPackagedProgramRetriever.getPackagedProgram(ClassPathPackagedProgramRetriever.java:178) ~[flink-dist_2.12-1.13.6.jar:1.13.6]               
      at org.apache.flink.kubernetes.entrypoint.KubernetesApplicationClusterEntrypoint.getPackagedProgram(KubernetesApplicationClusterEntrypoint.java:101) ~[flink-dist_2.12-1.13.6.jar:1.13.6]             
      at org.apache.flink.kubernetes.entrypoint.KubernetesApplicationClusterEntrypoint.main(KubernetesApplicationClusterEntrypoint.java:71) [flink-dist_2.12-1.13.6.jar:1.13.6]                             
  Caused by: org.apache.flink.client.program.ProgramInvocationException: JAR file does not exist '/opt/seatunnel/starter/seatunnel-flink-starter.jar'                                                       
      at org.apache.flink.client.program.PackagedProgram.checkJarFile(PackagedProgram.java:617) ~[flink-dist_2.12-1.13.6.jar:1.13.6]                                                                        
      at org.apache.flink.client.program.PackagedProgram.loadJarFile(PackagedProgram.java:465) ~[flink-dist_2.12-1.13.6.jar:1.13.6]                                                                         
      at org.apache.flink.client.program.PackagedProgram.<init>(PackagedProgram.java:135) ~[flink-dist_2.12-1.13.6.jar:1.13.6]                                                                              
      at org.apache.flink.client.program.PackagedProgram.<init>(PackagedProgram.java:65) ~[flink-dist_2.12-1.13.6.jar:1.13.6]                                                                               
      at org.apache.flink.client.program.PackagedProgram$Builder.build(PackagedProgram.java:691) ~[flink-dist_2.12-1.13.6.jar:1.13.6]                                                                       
      at org.apache.flink.client.deployment.application.ClassPathPackagedProgramRetriever.getPackagedProgram(ClassPathPackagedProgramRetriever.java:167) ~[flink-dist_2.12-1.13.6.jar:1.13.6]               
      ... 2 more                                                                                                                                                                                            
  Caused by: java.io.IOException: JAR file does not exist '/opt/seatunnel/starter/seatunnel-flink-starter.jar'                                                                                              
      at org.apache.flink.util.JarUtils.checkJarFile(JarUtils.java:46) ~[flink-dist_2.12-1.13.6.jar:1.13.6]                                                                                                 
      at org.apache.flink.client.program.PackagedProgram.checkJarFile(PackagedProgram.java:615) ~[flink-dist_2.12-1.13.6.jar:1.13.6]                                                                        
      at org.apache.flink.client.program.PackagedProgram.loadJarFile(PackagedProgram.java:465) ~[flink-dist_2.12-1.13.6.jar:1.13.6]                                                                         
      at org.apache.flink.client.program.PackagedProgram.<init>(PackagedProgram.java:135) ~[flink-dist_2.12-1.13.6.jar:1.13.6]                                                                              
      at org.apache.flink.client.program.PackagedProgram.<init>(PackagedProgram.java:65) ~[flink-dist_2.12-1.13.6.jar:1.13.6]                                                                               
      at org.apache.flink.client.program.PackagedProgram$Builder.build(PackagedProgram.java:691) ~[flink-dist_2.12-1.13.6.jar:1.13.6]                                                                       
      at org.apache.flink.client.deployment.application.ClassPathPackagedProgramRetriever.getPackagedProgram(ClassPathPackagedProgramRetriever.java:167) ~[flink-dist_2.12-1.13.6.jar:1.13.6]               
      ... 2 more
```

### Flink or Spark Version

flink version 1.13

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kksxf** [comment]
As mentioned earlier, there are several places in the document: [Set Up with Kubernetes v2.3.1](https://seatunnel.apache.org/docs/2.3.1/start-v2/kubernetes/) that have to be modified if you want to run the demo on flink operator (flink version 1.13)

1. The jarURI in FlinkDeployment should be modified to `local:///opt/seatunnel/starter/seatunnel-flink-13-starter.jar`
2. The entryClass in FlinkDeployment should be modified to `org.apache.seatunnel.core.starter.flink.SeaTunnelFlink`
3. The redundant whitespace around the equal sign have to be removed while setting `SEATUNNEL_HOME` in Dockerfile, otherwise the seatunnel cannot find the plugins in the right path

If i am wrong about something, please let me know

**Comment by liugddx** [comment]
> As mentioned earlier, there are several places in the document: [Set Up with Kubernetes v2.3.1](https://seatunnel.apache.org/docs/2.3.1/start-v2/kubernetes/) that have to be modified if you want to run the demo on flink operator (flink version 1.13)
> 
> 1. The jarURI in FlinkDeployment should be modified to `local:///opt/seatunnel/starter/seatunnel-flink-13-starter.jar`
> 2. The entryClass in FlinkDeployment should be modified to `org.apache.seatunnel.core.starter.flink.SeaTunnelFlink`
> 3. The redundant whitespace around the equal sign have to be removed while setting `SEATUNNEL_HOME` in Dockerfile, otherwise the seatunnel cannot find the plugins in the right path
> 
> If i am wrong about something, please let me know

Great!  Can you submit a pr?

**Comment by kksxf** [comment]
> > As mentioned earlier, there are several places in the document: [Set Up with Kubernetes v2.3.1](https://seatunnel.apache.org/docs/2.3.1/start-v2/kubernetes/) that have to be modified if you want to run the demo on flink operator (flink version 1.13)
> > 
> > 1. The jarURI in FlinkDeployment should be modified to `local:///opt/seatunnel/starter/seatunnel-flink-13-starter.jar`
> > 2. The entryClass in FlinkDeployment should be modified to `org.apache.seatunnel.core.starter.flink.SeaTunnelFlink`
> > 3. The redundant whitespace around the equal sign have to be removed while setting `SEATUNNEL_HOME` in Dockerfile, otherwise the seatunnel cannot find the plugins in the right path
> > 
> > If i am wrong about something, please let me know
> 
> Great! Can you submit a pr?

Sure, i will submit a PR later
