### ISSUE TITLE
Can SQL server cdc support SQL server 2008R

### ISSUE THREAD

**Issue by zhaoyvli** [apache/seatunnel#4862]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

There was an error running SQL server cdc. So I want to know if SQL server2008R is supported

### SeaTunnel Version

2.3.1

### SeaTunnel Config

```conf
env {
  job.mode = "STREAMING"
}
source{
  SqlServer-CDC {
    hostname = "127.0.0.1"
    port = "1433"
    username = "sa"
    password = "1234567"
    database-name = ["ods"]
    table-name = ["dbo.a"]
  }
}
sink {
    Console {
    }
}
```

### Running Command

```shell
./bin/seatunnel.sh --config ./job/test.conf -e local
```

### Error Exception

```log
2023-05-31 00:20:54,275 INFO  org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand - Closed HazelcastInstance ......
2023-05-31 00:20:54,275 ERROR org.apache.seatunnel.core.starter.SeaTunnel - 

===============================================================================


2023-05-31 00:20:54,276 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Fatal Error, 

2023-05-31 00:20:54,276 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Please submit bug report in https://github.com/apache/incubator-seatunnel/issues

2023-05-31 00:20:54,276 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Reason:SeaTunnel job executed failed 

2023-05-31 00:20:54,279 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:181)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: java.lang.NullPointerException
        at org.apache.seatunnel.connectors.seatunnel.cdc.sqlserver.source.config.SqlServerSourceConfigFactory.create(SqlServerSourceConfigFactory.java:54)
        at org.apache.seatunnel.connectors.seatunnel.cdc.sqlserver.source.source.SqlServerDialect.<init>(SqlServerDialect.java:55)
        at org.apache.seatunnel.connectors.seatunnel.cdc.sqlserver.source.source.SqlServerIncrementalSource.createDataSourceDialect(SqlServerIncrementalSource.java:118)
        at org.apache.seatunnel.connectors.cdc.base.source.IncrementalSource.prepare(IncrementalSource.java:117)
        at org.apache.seatunnel.engine.core.parse.ConnectorInstanceLoader.loadSourceInstance(ConnectorInstanceLoader.java:64)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.sampleAnalyze(JobConfigParser.java:371)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.parse(JobConfigParser.java:132)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:112)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.getLogicalDag(JobExecutionEnvironment.java:155)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:147)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:140)
        ... 2 more
 
2023-05-31 00:20:54,279 ERROR org.apache.seatunnel.core.starter.SeaTunnel - 
===============================================================================



Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:181)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: java.lang.NullPointerException
        at org.apache.seatunnel.connectors.seatunnel.cdc.sqlserver.source.config.SqlServerSourceConfigFactory.create(SqlServerSourceConfigFactory.java:54)
        at org.apache.seatunnel.connectors.seatunnel.cdc.sqlserver.source.source.SqlServerDialect.<init>(SqlServerDialect.java:55)
        at org.apache.seatunnel.connectors.seatunnel.cdc.sqlserver.source.source.SqlServerIncrementalSource.createDataSourceDialect(SqlServerIncrementalSource.java:118)
        at org.apache.seatunnel.connectors.cdc.base.source.IncrementalSource.prepare(IncrementalSource.java:117)
        at org.apache.seatunnel.engine.core.parse.ConnectorInstanceLoader.loadSourceInstance(ConnectorInstanceLoader.java:64)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.sampleAnalyze(JobConfigParser.java:371)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.parse(JobConfigParser.java:132)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:112)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.getLogicalDag(JobExecutionEnvironment.java:155)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:147)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:140)
        ... 2 more
```

### Java or Scala Version

java.version=1.8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by exxiang** [comment]
Can you assign this problem to me, I will finish it, thanks

**Comment by zhaoyvli** [comment]
Sure, thanks.

**Comment by Carl-Zhou-CN** [comment]
You can try using the correct configuration to try database-names, table-names

**Comment by exxiang** [comment]
There is a bug in this version，Only database-names and table-name can correct running

**Comment by zhaoyvli** [comment]
`
env {
  job.mode = "STREAMING"
}
source{
  SqlServer-CDC {
    hostname = "127.0.0.1"
    port = "1433"
    username = "sa"
    password = "1234567"
    database-names = ["ods"]
    table-names = ["dbo.a"]
  }
}
sink {
    Console {
    }
}
`
After error correction, it can run successfully, There is no problem adding or modifying data in the table, but deleting the data program will end and restarting will fail. @Carl-Zhou-CN 
[error_log.txt](https://github.com/apache/seatunnel/files/11626368/error_log.txt)

**Comment by Carl-Zhou-CN** [comment]
@MrZhao1024B Sorry for replying you so late, this problem has been fixed on the latest branch, you can try the latest branch

**Comment by Carl-Zhou-CN** [comment]
#4377
