### ISSUE TITLE
with 2.3.1 run SeaTunnelEngineExample got Unrecognized client message received with type: 0xde0200

### ISSUE THREAD

**Issue by MrLiuzy** [apache/seatunnel#4884]
When run the example org.apache.seatunnel.example.engine.SeaTunnelEngineExample in seatunnel-engine-examples, I got the follow error:
```
2023-06-05 11:26:23,709 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Fatal Error, 

2023-06-05 11:26:23,709 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Please submit bug report in https://github.com/apache/incubator-seatunnel/issues

2023-06-05 11:26:23,709 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Reason:SeaTunnel job executed failed 

2023-06-05 11:26:23,710 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:181)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.example.engine.SeaTunnelEngineExample.main(SeaTunnelEngineExample.java:43)
Caused by: java.util.concurrent.CompletionException: java.lang.UnsupportedOperationException: Unrecognized client message received with type: 0xde0200
	at com.hazelcast.spi.impl.AbstractInvocationFuture.wrapInCompletionException(AbstractInvocationFuture.java:1347)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.cascadeException(AbstractInvocationFuture.java:1340)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.unblockApply(AbstractInvocationFuture.java:842)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.thenApplyAsync(AbstractInvocationFuture.java:137)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.thenApplyAsync(ClientInvocationFuture.java:116)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.thenApply(AbstractInvocationFuture.java:123)
	at org.apache.seatunnel.engine.client.SeaTunnelHazelcastClient.requestAndGetCompletableFuture(SeaTunnelHazelcastClient.java:123)
	at org.apache.seatunnel.engine.client.SeaTunnelHazelcastClient.requestOnMasterAndGetCompletableFuture(SeaTunnelHazelcastClient.java:132)
	at org.apache.seatunnel.engine.client.job.ClientJobProxy.submitJob(ClientJobProxy.java:80)
	at org.apache.seatunnel.engine.client.job.ClientJobProxy.<init>(ClientJobProxy.java:54)
	at org.apache.seatunnel.engine.client.job.JobClient.createJobProxy(JobClient.java:61)
	at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:151)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:140)
	... 2 more
Caused by: java.lang.UnsupportedOperationException: Unrecognized client message received with type: 0xde0200
	at com.hazelcast.client.impl.protocol.task.NoSuchMessageTask.processMessage(NoSuchMessageTask.java:45)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:153)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:116)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
 
2023-06-05 11:26:23,710 ERROR org.apache.seatunnel.core.starter.SeaTunnel - 
===============================================================================



Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:181)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.example.engine.SeaTunnelEngineExample.main(SeaTunnelEngineExample.java:43)
Caused by: java.util.concurrent.CompletionException: java.lang.UnsupportedOperationException: Unrecognized client message received with type: 0xde0200
	at com.hazelcast.spi.impl.AbstractInvocationFuture.wrapInCompletionException(AbstractInvocationFuture.java:1347)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.cascadeException(AbstractInvocationFuture.java:1340)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.unblockApply(AbstractInvocationFuture.java:842)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.thenApplyAsync(AbstractInvocationFuture.java:137)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.thenApplyAsync(ClientInvocationFuture.java:116)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.thenApply(AbstractInvocationFuture.java:123)
	at org.apache.seatunnel.engine.client.SeaTunnelHazelcastClient.requestAndGetCompletableFuture(SeaTunnelHazelcastClient.java:123)
	at org.apache.seatunnel.engine.client.SeaTunnelHazelcastClient.requestOnMasterAndGetCompletableFuture(SeaTunnelHazelcastClient.java:132)
	at org.apache.seatunnel.engine.client.job.ClientJobProxy.submitJob(ClientJobProxy.java:80)
	at org.apache.seatunnel.engine.client.job.ClientJobProxy.<init>(ClientJobProxy.java:54)
	at org.apache.seatunnel.engine.client.job.JobClient.createJobProxy(JobClient.java:61)
	at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:151)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:140)
	... 2 more
Caused by: java.lang.UnsupportedOperationException: Unrecognized client message received with type: 0xde0200
	at com.hazelcast.client.impl.protocol.task.NoSuchMessageTask.processMessage(NoSuchMessageTask.java:45)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:153)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:116)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
```

anyone can help me?

**Comment by zhilinli123** [comment]
Has the hi problem been solved?
You can provide more detailed information about this problem, such as your conf script, system environment, etc

**Comment by zeeneddie** [comment]
how did you start your engine server and client example?

**Comment by MrLiuzy** [comment]
I kown why. The SPI services resource was clean by the IDE. After use maven update, everything became correct.

**Comment by mengflow** [comment]
> I kown why. The SPI services resource was clean by the IDE. After use maven update, everything became correct.

That's right
