### ISSUE TITLE
[Bug] [flink] Can't find config file

### ISSUE THREAD

**Issue by shixiutao** [apache/seatunnel#4894]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

when use bin/start-seatunnel-flink-13-connector-v2.sh to submit seatunnel job， yarn report error：
Reason:ErrorCode:[COMMON-01], ErrorDescription:[File operation failed, such as (read,list,write,move,copy,sync) etc...] - Can't find config file: /opt/apache-seatunnel-incubating-2.3.1/config/v2.streaming.conf.template 

### SeaTunnel Version

2.3.1

### SeaTunnel Config

```conf
env {
  # You can set flink configuration here
  execution.parallelism = 2
  job.mode = "STREAMING"
  checkpoint.interval = 2000
  #execution.checkpoint.interval = 10000
  #execution.checkpoint.data-uri = "hdfs://localhost:9000/checkpoint"
}
source {
  # This is a example source plugin **only for test and demonstrate the feature source plugin**
  FakeSource {
    parallelism = 2
    result_table_name = "fake"
    row.num = 16
    schema = {
      fields {
        name = "string"
        age = "int"
      }
    }
  }
  # If you would like to get more information about how to configure Seatunnel and see full list of source plugins,
  # please go to https://seatunnel.apache.org/docs/category/source-v2
}
sink {
  Console {
  }
}
```

### Running Command

```shell
./bin/start-seatunnel-flink-13-connector-v2.sh --master yarn-application -e run-application --config /opt/apache-seatunnel-incubating-2.3.1/config/v2.streaming.conf.template 
```

### Error Exception

```log
local log：
The program finished with the following exception:
org.apache.flink.client.deployment.ClusterDeploymentException: Couldn't deploy Yarn Application Cluster
        at org.apache.flink.yarn.YarnClusterDescriptor.deployApplicationCluster(YarnClusterDescriptor.java:465)
        at org.apache.flink.client.deployment.application.cli.ApplicationClusterDeployer.run(ApplicationClusterDeployer.java:67)
        at org.apache.flink.client.cli.CliFrontend.runApplication(CliFrontend.java:213)
        at org.apache.flink.client.cli.CliFrontend.parseAndRun(CliFrontend.java:1057)
        at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1132)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
        at org.apache.flink.runtime.security.contexts.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:41)
        at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1132)

Exit code: 2
Stack trace: ExitCodeException exitCode=2: 
        at org.apache.hadoop.util.Shell.runCommand(Shell.java:561)
        at org.apache.hadoop.util.Shell.run(Shell.java:478)
        at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:738)
        at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:213)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)


yarn log：
Reason:ErrorCode:[COMMON-01], ErrorDescription:[File operation failed, such as (read,list,write,move,copy,sync) etc...] - Can't find config file: /opt/apache-seatunnel-incubating-2.3.1/config/v2.streaming.conf.template
```

### Flink or Spark Version

flink 1.13.2

### Java or Scala Version

java1.8.0_151

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhilinli123** [comment]
In my opinion, your problem with this mode of operation is that you can try **pre-job** mode,If you want to run in **run-application** mode you can try to store the file in hdfs

**Comment by shixiutao** [comment]
> In my opinion, your problem with this mode of operation is that you can try **pre-job** mode,If you want to run in **run-application** mode you can try to store the file in hdfs

I can use the **yarn-per-job** mode to run normally on Yarn. But in the **yarn-application** mode, do I have to upload the config file to **HDFS** first? Didn't the flink. sh script automatically upload to **HDFS**? Or do you know if there are other configuration settings that do not require uploading the config file to **HDFS** in advance

**Comment by shixiutao** [comment]
I placed the config file in hdfs and re executed Flink.sh, but still reported an error. I checked the source code of seatunnel2.3.1 and found that I was checking whether the local directory config file exists. However, the Flink run application mode performs task parsing on jobmanager, and I suspect it was not considered in the implementation

command：/opt/apache-seatunnel-incubating-2.3.1/bin/start-seatunnel-flink-13-connector-v2.sh --master yarn-application -e run-application --config hdfs://seatunnel/remote-flink-dist/seatunnel.config 

yarn error：
ErrorDescription:[File operation failed, such as (read,list,write,move,copy,sync) etc...] - Can't find config file: hdfs:/seatunnel/remote-flink-dist/seatunnel.config

the source code in seatunnel 2.3.1:
![Image_20230607095206](https://github.com/apache/seatunnel/assets/8542648/7b201551-456d-4768-bf8f-828fbe4668bc)

![Image_20230607095220](https://github.com/apache/seatunnel/assets/8542648/ac10c68c-322e-4b5b-a56c-8c9a09229322)

**Comment by zhaoli2333** [comment]
Have you solved this problem?
Is there any solution except modifying the source code?
