### ISSUE TITLE
[Bug] [hazelcast] During the execution of hazelcast, an error has been reported when operating the keyboard Ctrl+c, please handle it gracefully

### ISSUE THREAD

**Issue by section9-lab** [apache/seatunnel#4909]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

During the execution of hazelcast, an error has been reported when operating the keyboard Ctrl+c, please handle it gracefully.

### SeaTunnel Version

apache-seatunnel-incubating-2.3.1

### SeaTunnel Config

```conf
env {
  # You can set flink configuration here
  execution.parallelism = 1
  job.mode = "STREAMING"
  #checkpoint.interval = 2000
  #execution.checkpoint.interval = 10000
  #execution.checkpoint.data-uri = "hdfs://localhost:9000/checkpoint"
}

source {
  # This is a example source plugin **only for test and demonstrate the feature source plugin**
  FakeSource {
    parallelism = 2
    result_table_name = "fake"
    row.num = 2000
    schema = {
      fields {
        name = "string"
        age = "int"
      }
    }
  }

  # If you would like to get more information about how to configure Seatunnel and see full list of source plugins,
  # please go to https://seatunnel.apache.org/docs/category/source-v2
}

sink {
  Console {
  }

  # If you would like to get more information about how to configure Seatunnel and see full list of sink plugins,
  # please go to https://seatunnel.apache.org/docs/category/sink-v2
}
```

### Running Command

```shell
apache-seatunnel-incubating-2.3.1$ ./bin/seatunnel.sh --config config/v2.streaming.conf.template -e local
```

### Error Exception

```log
^C2023-06-09 20:12:29,554 INFO  com.hazelcast.instance.impl.Node - [localhost]:5801 [seatunnel-117476] [5.1] Running shutdown hook... Current state: ACTIVE
2023-06-09 20:12:29,554 INFO  org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand - run shutdown hook because get close signal
2023-06-09 20:12:29,554 WARN  org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand - Task will be closed due to client shutdown.
2023-06-09 20:12:29,555 INFO  com.hazelcast.core.LifecycleService - [localhost]:5801 [seatunnel-117476] [5.1] [localhost]:5801 is SHUTTING_DOWN
2023-06-09 20:12:29,557 WARN  com.hazelcast.instance.impl.Node - [localhost]:5801 [seatunnel-117476] [5.1] Terminating forcefully...
2023-06-09 20:12:29,557 INFO  com.hazelcast.instance.impl.Node - [localhost]:5801 [seatunnel-117476] [5.1] Shutting down connection manager...
2023-06-09 20:12:29,558 INFO  org.apache.seatunnel.engine.server.dag.physical.PhysicalPlan - Job SeaTunnel_Job (719524197411323905) turn from state RUNNING to CANCELLING.
2023-06-09 20:12:29,558 INFO  com.hazelcast.internal.server.tcp.TcpServerConnection - [localhost]:5801 [seatunnel-117476] [5.1] Connection[id=1, /127.0.0.1:5801->/127.0.0.1:37131, qualifier=null, endpoint=[127.0.0.1]:37131, remoteUuid=20b90a13-d9a3-4360-a0f5-acb6da8f0fc2, alive=false, connectionType=JVM, planeIndex=-1] closed. Reason: TcpServer is stopping
2023-06-09 20:12:29,560 INFO  com.hazelcast.client.impl.connection.tcp.TcpClientConnection - hz.client_1 [seatunnel-117476] [5.1] ClientConnection{alive=false, connectionId=1, channel=NioChannel{/127.0.0.1:37131->localhost/127.0.0.1:5801}, remoteAddress=[localhost]:5801, lastReadTime=2023-06-09 20:12:26.756, lastWriteTime=2023-06-09 20:12:29.555, closedTime=2023-06-09 20:12:29.559, connected server version=5.1} closed. Reason: Connection closed by the other side
2023-06-09 20:12:29,561 INFO  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-117476] [5.1] Removed connection to endpoint: [localhost]:5801:75173497-1595-41a7-828a-b9a92cdbb9d2, connection: ClientConnection{alive=false, connectionId=1, channel=NioChannel{/127.0.0.1:37131->localhost/127.0.0.1:5801}, remoteAddress=[localhost]:5801, lastReadTime=2023-06-09 20:12:26.756, lastWriteTime=2023-06-09 20:12:29.555, closedTime=2023-06-09 20:12:29.559, connected server version=5.1}
2023-06-09 20:12:29,561 INFO  com.hazelcast.core.LifecycleService - hz.client_1 [seatunnel-117476] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is CLIENT_DISCONNECTED
2023-06-09 20:12:29,562 INFO  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-117476] [5.1] Trying to connect to cluster: seatunnel-117476
2023-06-09 20:12:29,562 INFO  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-117476] [5.1] Trying to connect to Member [localhost]:5801 - 75173497-1595-41a7-828a-b9a92cdbb9d2
2023-06-09 20:12:29,562 INFO  com.hazelcast.instance.impl.Node - [localhost]:5801 [seatunnel-117476] [5.1] Shutting down node engine...
2023-06-09 20:12:29,563 WARN  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-117476] [5.1] Exception during initial connection to Member [localhost]:5801 - 75173497-1595-41a7-828a-b9a92cdbb9d2: com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address localhost/127.0.0.1:5801
2023-06-09 20:12:29,564 WARN  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-117476] [5.1] Unable to get live cluster connection, retry in 1000 ms, attempt: 1, cluster connect timeout: 3000 ms, max backoff: 30000 ms
2023-06-09 20:12:29,576 WARN  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-117476] [5.1] Interrupted task 40000 - org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask@1f63548f
2023-06-09 20:12:29,576 WARN  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-117476] [5.1] Interrupted task 40001 - org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask@3a32440f
2023-06-09 20:12:29,576 WARN  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-117476] [5.1] Interrupted task 20000 - org.apache.seatunnel.engine.server.task.SourceSplitEnumeratorTask@c275b79
2023-06-09 20:12:29,576 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-117476] [5.1] taskDone, taskId = 20000, taskGroup = TaskGroupLocation{jobId=719524197411323905, pipelineId=1, taskGroupId=1}
2023-06-09 20:12:29,576 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-117476] [5.1] taskDone, taskId = 40001, taskGroup = TaskGroupLocation{jobId=719524197411323905, pipelineId=1, taskGroupId=30001}
2023-06-09 20:12:29,576 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-117476] [5.1] taskDone, taskId = 40000, taskGroup = TaskGroupLocation{jobId=719524197411323905, pipelineId=1, taskGroupId=30000}
2023-06-09 20:12:29,577 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-117476] [5.1] Task TaskGroupLocation{jobId=719524197411323905, pipelineId=1, taskGroupId=1} complete with state FAILED
2023-06-09 20:12:29,576 WARN  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-117476] [5.1] Interrupted task 50001 - org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask@51d89cda
2023-06-09 20:12:29,576 WARN  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-117476] [5.1] Interrupted task 50000 - org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask@4e368447
2023-06-09 20:12:29,585 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-117476] [5.1] taskDone, taskId = 50001, taskGroup = TaskGroupLocation{jobId=719524197411323905, pipelineId=1, taskGroupId=30001}
2023-06-09 20:12:29,585 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-117476] [5.1] taskDone, taskId = 50000, taskGroup = TaskGroupLocation{jobId=719524197411323905, pipelineId=1, taskGroupId=30000}
2023-06-09 20:12:29,586 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-117476] [5.1] Task TaskGroupLocation{jobId=719524197411323905, pipelineId=1, taskGroupId=30001} complete with state FAILED
2023-06-09 20:12:29,586 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-117476] [5.1] Task TaskGroupLocation{jobId=719524197411323905, pipelineId=1, taskGroupId=30000} complete with state FAILED
2023-06-09 20:12:29,609 INFO  com.hazelcast.instance.impl.NodeExtension - [localhost]:5801 [seatunnel-117476] [5.1] Destroying node NodeExtension.
2023-06-09 20:12:29,609 INFO  com.hazelcast.instance.impl.Node - [localhost]:5801 [seatunnel-117476] [5.1] Hazelcast Shutdown is completed in 52 ms.
2023-06-09 20:12:29,610 INFO  com.hazelcast.core.LifecycleService - [localhost]:5801 [seatunnel-117476] [5.1] [localhost]:5801 is SHUTDOWN
2023-06-09 20:12:29,739 WARN  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-117476] [5.1] Could not connect to member 75173497-1595-41a7-828a-b9a92cdbb9d2, reason com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address localhost/127.0.0.1:5801
2023-06-09 20:12:30,564 INFO  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-117476] [5.1] Trying to connect to Member [localhost]:5801 - 75173497-1595-41a7-828a-b9a92cdbb9d2
2023-06-09 20:12:30,565 WARN  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-117476] [5.1] Exception during initial connection to Member [localhost]:5801 - 75173497-1595-41a7-828a-b9a92cdbb9d2: com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address localhost/127.0.0.1:5801
2023-06-09 20:12:30,565 WARN  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-117476] [5.1] Unable to get live cluster connection, retry in 1050 ms, attempt: 2, cluster connect timeout: 3000 ms, max backoff: 30000 ms
2023-06-09 20:12:30,740 WARN  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-117476] [5.1] Could not connect to member 75173497-1595-41a7-828a-b9a92cdbb9d2, reason com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address localhost/127.0.0.1:5801
2023-06-09 20:12:31,615 INFO  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-117476] [5.1] Trying to connect to Member [localhost]:5801 - 75173497-1595-41a7-828a-b9a92cdbb9d2
2023-06-09 20:12:31,616 WARN  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-117476] [5.1] Exception during initial connection to Member [localhost]:5801 - 75173497-1595-41a7-828a-b9a92cdbb9d2: com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address localhost/127.0.0.1:5801
2023-06-09 20:12:31,616 WARN  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-117476] [5.1] Unable to get live cluster connection, retry in 946 ms, attempt: 3, cluster connect timeout: 3000 ms, max backoff: 30000 ms
2023-06-09 20:12:31,740 WARN  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-117476] [5.1] Could not connect to member 75173497-1595-41a7-828a-b9a92cdbb9d2, reason com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address localhost/127.0.0.1:5801
2023-06-09 20:12:32,562 INFO  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-117476] [5.1] Trying to connect to Member [localhost]:5801 - 75173497-1595-41a7-828a-b9a92cdbb9d2
2023-06-09 20:12:32,563 WARN  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-117476] [5.1] Exception during initial connection to Member [localhost]:5801 - 75173497-1595-41a7-828a-b9a92cdbb9d2: com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address localhost/127.0.0.1:5801
2023-06-09 20:12:32,563 WARN  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-117476] [5.1] Unable to get live cluster connection, cluster connect timeout (3000 ms) is reached. Attempt 4.
2023-06-09 20:12:32,563 INFO  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-117476] [5.1] Unable to connect to any address from the cluster with name: seatunnel-117476. The following addresses were tried: [[localhost]:5801]
2023-06-09 20:12:32,563 WARN  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-117476] [5.1] Could not connect to any cluster, shutting down the client: Unable to connect to any cluster.
2023-06-09 20:12:32,564 INFO  com.hazelcast.core.LifecycleService - hz.client_1 [seatunnel-117476] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is SHUTTING_DOWN
2023-06-09 20:12:32,596 INFO  org.apache.seatunnel.engine.client.job.ClientJobProxy - Job (719524197411323905) end with unknown state, and throw Exception: java.util.concurrent.ExecutionException: com.hazelcast.client.HazelcastClientNotActiveException: Client is shutting down
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
        at org.apache.seatunnel.engine.client.job.ClientJobProxy.lambda$waitForJobComplete$0(ClientJobProxy.java:97)
        at org.apache.seatunnel.common.utils.RetryUtils.retryWithException(RetryUtils.java:48)
        at org.apache.seatunnel.engine.client.job.ClientJobProxy.waitForJobComplete(ClientJobProxy.java:93)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:174)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: com.hazelcast.client.HazelcastClientNotActiveException: Client is shutting down
        at com.hazelcast.client.impl.spi.impl.ClientInvocation.notifyExceptionWithOwnedPermission(ClientInvocation.java:316)
        at com.hazelcast.client.impl.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:209)
        at com.hazelcast.client.impl.spi.impl.ClientInvocation.retry(ClientInvocation.java:235)
        at com.hazelcast.client.impl.spi.impl.ClientInvocation.run(ClientInvocation.java:216)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
Caused by: java.io.IOException: No connection found to cluster.
        at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.checkInvocationAllowed(TcpClientConnectionManager.java:548)
        at com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl.checkInvocationAllowed(ClientInvocationServiceImpl.java:294)
        at com.hazelcast.client.impl.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:178)
        ... 11 more

2023-06-09 20:12:32,597 INFO  com.hazelcast.core.LifecycleService - hz.client_1 [seatunnel-117476] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is SHUTDOWN
2023-06-09 20:12:32,597 INFO  org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand - Closed SeaTunnel client......
2023-06-09 20:12:32,598 INFO  org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand - Closed HazelcastInstance ......
2023-06-09 20:12:32,598 INFO  org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand - Closed metrics executor service ......
2023-06-09 20:12:32,598 ERROR org.apache.seatunnel.core.starter.SeaTunnel -

===============================================================================


2023-06-09 20:12:32,598 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Fatal Error,

2023-06-09 20:12:32,598 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Please submit bug report in https://github.com/apache/incubator-seatunnel/issues

2023-06-09 20:12:32,598 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Reason:SeaTunnel job executed failed

2023-06-09 20:12:32,599 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:181)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.hazelcast.client.HazelcastClientNotActiveException: Client is shutting down
        at org.apache.seatunnel.engine.client.job.ClientJobProxy.waitForJobComplete(ClientJobProxy.java:114)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:174)
        ... 2 more
Caused by: java.util.concurrent.ExecutionException: com.hazelcast.client.HazelcastClientNotActiveException: Client is shutting down
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
        at org.apache.seatunnel.engine.client.job.ClientJobProxy.lambda$waitForJobComplete$0(ClientJobProxy.java:97)
        at org.apache.seatunnel.common.utils.RetryUtils.retryWithException(RetryUtils.java:48)
        at org.apache.seatunnel.engine.client.job.ClientJobProxy.waitForJobComplete(ClientJobProxy.java:93)
        ... 3 more
Caused by: com.hazelcast.client.HazelcastClientNotActiveException: Client is shutting down
        at com.hazelcast.client.impl.spi.impl.ClientInvocation.notifyExceptionWithOwnedPermission(ClientInvocation.java:316)
        at com.hazelcast.client.impl.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:209)
        at com.hazelcast.client.impl.spi.impl.ClientInvocation.retry(ClientInvocation.java:235)
        at com.hazelcast.client.impl.spi.impl.ClientInvocation.run(ClientInvocation.java:216)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
Caused by: java.io.IOException: No connection found to cluster.
        at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.checkInvocationAllowed(TcpClientConnectionManager.java:548)
        at com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl.checkInvocationAllowed(ClientInvocationServiceImpl.java:294)
        at com.hazelcast.client.impl.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:178)
        ... 11 more

2023-06-09 20:12:32,599 ERROR org.apache.seatunnel.core.starter.SeaTunnel -
===============================================================================



Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:181)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.hazelcast.client.HazelcastClientNotActiveException: Client is shutting down
        at org.apache.seatunnel.engine.client.job.ClientJobProxy.waitForJobComplete(ClientJobProxy.java:114)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:174)
        ... 2 more
Caused by: java.util.concurrent.ExecutionException: com.hazelcast.client.HazelcastClientNotActiveException: Client is shutting down
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
        at org.apache.seatunnel.engine.client.job.ClientJobProxy.lambda$waitForJobComplete$0(ClientJobProxy.java:97)
        at org.apache.seatunnel.common.utils.RetryUtils.retryWithException(RetryUtils.java:48)
        at org.apache.seatunnel.engine.client.job.ClientJobProxy.waitForJobComplete(ClientJobProxy.java:93)
        ... 3 more
Caused by: com.hazelcast.client.HazelcastClientNotActiveException: Client is shutting down
        at com.hazelcast.client.impl.spi.impl.ClientInvocation.notifyExceptionWithOwnedPermission(ClientInvocation.java:316)
        at com.hazelcast.client.impl.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:209)
        at com.hazelcast.client.impl.spi.impl.ClientInvocation.retry(ClientInvocation.java:235)
        at com.hazelcast.client.impl.spi.impl.ClientInvocation.run(ClientInvocation.java:216)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
Caused by: java.io.IOException: No connection found to cluster.
        at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.checkInvocationAllowed(TcpClientConnectionManager.java:548)
        at com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl.checkInvocationAllowed(ClientInvocationServiceImpl.java:294)
        at com.hazelcast.client.impl.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:178)
        ... 11 more
2023-06-09 20:12:32,595 ERROR org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand - Cancel job failed.
java.util.concurrent.ExecutionException: com.hazelcast.client.HazelcastClientNotActiveException: Client is shutting down
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_362]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928) ~[?:1.8.0_362]
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.lambda$execute$1(ClientExecuteCommand.java:154) ~[seatunnel-starter.jar:2.3.1]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_362]
Caused by: com.hazelcast.client.HazelcastClientNotActiveException: Client is shutting down
        at com.hazelcast.client.impl.spi.impl.ClientInvocation.notifyExceptionWithOwnedPermission(ClientInvocation.java:316) ~[seatunnel-starter.jar:2.3.1]
        at com.hazelcast.client.impl.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:209) ~[seatunnel-starter.jar:2.3.1]
        at com.hazelcast.client.impl.spi.impl.ClientInvocation.retry(ClientInvocation.java:235) ~[seatunnel-starter.jar:2.3.1]
        at com.hazelcast.client.impl.spi.impl.ClientInvocation.run(ClientInvocation.java:216) ~[seatunnel-starter.jar:2.3.1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_362]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_362]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_362]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_362]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_362]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_362]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_362]
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[seatunnel-starter.jar:2.3.1]
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[seatunnel-starter.jar:2.3.1]
Caused by: java.io.IOException: No connection found to cluster.
        at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.checkInvocationAllowed(TcpClientConnectionManager.java:548) ~[seatunnel-starter.jar:2.3.1]
        at com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl.checkInvocationAllowed(ClientInvocationServiceImpl.java:294) ~[seatunnel-starter.jar:2.3.1]
        at com.hazelcast.client.impl.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:178) ~[seatunnel-starter.jar:2.3.1]
        at com.hazelcast.client.impl.spi.impl.ClientInvocation.retry(ClientInvocation.java:235) ~[seatunnel-starter.jar:2.3.1]
        at com.hazelcast.client.impl.spi.impl.ClientInvocation.run(ClientInvocation.java:216) ~[seatunnel-starter.jar:2.3.1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_362]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_362]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_362]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_362]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_362]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_362]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_362]
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[seatunnel-starter.jar:2.3.1]
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[seatunnel-starter.jar:2.3.1]
wangdachui@007-NC01:~/apache-seatunnel-incubating-2.3.1$ cat config/v2.streaming.conf.template
```

### Flink or Spark Version

no

### Java or Scala Version

no

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
This exception is normal because it is a streaming task. Do you have any suggestions?

**Comment by section9-lab** [comment]
At the end of pressing Ctrl+c, there are too many Java stack error messages, thinking that an error was encountered during deactivation, and it is recommended to print a more elegant stop log.

**Comment by liugddx** [comment]
> At the end of pressing Ctrl+c, there are too many Java stack error messages, thinking that an error was encountered during deactivation, and it is recommended to print a more elegant stop log.

Great suggestion. Can you provide a pr to fix this?
