### ISSUE TITLE
[Bug] [Module Name] Bug title

### ISSUE THREAD

**Issue by yujian225** [apache/seatunnel#4912]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

st2.3.1中的sink.label-prefix = "label"，里面的label必须每次手动指定，所以需要用st的传参。但是根据文档中的方式传参有问题，不能实现。

### SeaTunnel Version

seatunnel2.3.1

### SeaTunnel Config

```conf
env {
  job.mode = "BATCH"
  execution.parallelism = 1
}

source {
  Jdbc {
    url = "jdbc:mysql:// :3306/demo?serverTimezone=GMT%2b8"
    driver = "com.mysql.cj.jdbc.Driver"
    connection_check_timeout_sec = 100
    user = "root"
    password = " @"
    query = "SELECT id,p_name,create_time FROM user_cdc"
  }
}
transform { }
sink {
   Doris {
        fenodes = " :8030"
        username = root
        password = "@"
        table.identifier = "doris_demo.user_cdc"
        sink.enable-2pc = "true"
        sink.label-prefix = "a_${label}"
        doris.config = {
            format="json"
            read_json_by_line="true"
        }
  }
}
```

### Running Command

```shell
./bin/seatunnel.sh --config test -e local -i label=test3
```

### Error Exception

```log
Caused by: org.apache.seatunnel.connectors.doris.exception.DorisConnectorException: ErrorCode:[Doris-01], ErrorDescription:[stream load error] - stream load error: [ANALYSIS_ERROR]errCode = 2, detailMessage = Label format error. regex: ^[-_A-Za-z0-9]{1,128}$, label: a_${label}_0_1, see more in null
	at org.apache.seatunnel.connectors.doris.sink.writer.DorisSinkWriter.prepareCommit(DorisSinkWriter.java:140)
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:158)
	... 15 more

	at org.apache.seatunnel.engine.client.job.ClientJobProxy.waitForJobComplete(ClientJobProxy.java:119)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:174)
	... 2 more
2023-06-12 09:59:57,210 INFO  org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand - run shutdown hook because get close signal
```

### Screenshots

![image](https://github.com/apache/seatunnel/assets/88439948/757161b6-ebe7-4200-9c89-cdd58069e08f)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by exxiang** [comment]
You can give it a try,  sink.label-prefix = "a_"${label}""

**Comment by yujian225** [comment]
> 试过了，也是不行的
