### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: can't find field xxx

### ISSUE THREAD

**Issue by glinxx** [apache/seatunnel#4919]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When I use the replace of transformer, I am prompted that I cannot find the field, but when I print out the table from the console, I can see that the field exists. What's the matter

### SeaTunnel Version

2.3.1

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
  job.mode = "BATCH"
}

source {

  Kafka {
    result_table_name = "doc_log"
    topic = "topic_name"
    bootstrap.servers = "127.0.0.1:9092"
    consumer.group = "seatunnel_group_test"
    kafka.config = {
      auto.offset.reset = "earliest"
    }
  }
  
}


transform {
  Replace {
    source_table_name = "doc_log"
    result_table_name = "doc_log2"
    replace_field = "ROWGUID"
    pattern = "test"
    replacement = ""
    is_regex = true
  }
}

sink {
  Console {
    source_table_name ="doc_log2" 
  }
}
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/conf.d/endoc.conf -e local
```

### Error Exception

```log
2023-06-14 09:11:08,906 ERROR org.apache.seatunnel.core.starter.SeaTunnel -

===============================================================================


2023-06-14 09:11:08,906 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Fatal Error,

2023-06-14 09:11:08,906 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Please submit bug report in https://github.com/apache/incubator-seatunnel/issues

2023-06-14 09:11:08,906 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Reason:SeaTunnel job executed failed

2023-06-14 09:11:08,908 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:181)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: java.lang.IllegalArgumentException: can't find field ROWGUID
        at org.apache.seatunnel.api.table.type.SeaTunnelRowType.indexOf(SeaTunnelRowType.java:82)
        at org.apache.seatunnel.transform.ReplaceTransform.setInputRowType(ReplaceTransform.java:105)
        at org.apache.seatunnel.transform.common.SingleFieldOutputTransform.transformRowType(SingleFieldOutputTransform.java:41)
        at org.apache.seatunnel.transform.common.AbstractSeaTunnelTransform.setTypeInfo(AbstractSeaTunnelTransform.java:69)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.sampleAnalyze(JobConfigParser.java:387)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.parse(JobConfigParser.java:132)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:112)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.getLogicalDag(JobExecutionEnvironment.java:155)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:147)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:140)
        ... 2 more

2023-06-14 09:11:08,908 ERROR org.apache.seatunnel.core.starter.SeaTunnel -
===============================================================================



Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:181)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: java.lang.IllegalArgumentException: can't find field ROWGUID
        at org.apache.seatunnel.api.table.type.SeaTunnelRowType.indexOf(SeaTunnelRowType.java:82)
        at org.apache.seatunnel.transform.ReplaceTransform.setInputRowType(ReplaceTransform.java:105)
        at org.apache.seatunnel.transform.common.SingleFieldOutputTransform.transformRowType(SingleFieldOutputTransform.java:41)
        at org.apache.seatunnel.transform.common.AbstractSeaTunnelTransform.setTypeInfo(AbstractSeaTunnelTransform.java:69)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.sampleAnalyze(JobConfigParser.java:387)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.parse(JobConfigParser.java:132)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:112)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.getLogicalDag(JobExecutionEnvironment.java:155)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:147)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:140)
        ... 2 more
```

### Java or Scala Version

java 1.8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhilinli123** [comment]
You're trying to declare a schema
reference:
https://github.com/apache/seatunnel/blob/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-kafka-e2e/src/test/resources/kafka/kafkasource_earliest_to_console.conf

**Comment by glinxx** [comment]
> You're trying to declare a schema reference: https://github.com/apache/seatunnel/blob/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-kafka-e2e/src/test/resources/kafka/kafkasource_earliest_to_console.conf
Thank you, I'm not familiar enough
