### ISSUE TITLE
[Bug] [seatunnel for spark] seatunnel start with spark error

### ISSUE THREAD

**Issue by WeirsWesley** [apache/seatunnel#4924]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

seatunnel start use this can success.
`sh /opt/apache-seatunnel-incubating-2.3.1/bin/seatunnel.sh --config /opt/configTemp/142003.json -e local`

start with spark err
`sh /opt/apache-seatunnel-incubating-2.3.1/bin/start-seatunnel-spark-3-connector-v2.sh --master local[4] --deploy-mode client --config /opt/configTemp/142003.json`

### SeaTunnel Version

2.3.1

### SeaTunnel Config

```conf
//142003.json
{
	"env": {
		"job.mode": "BATCH",
		"spark.app.name": "mysql-mysql",
		"spark.app.id": "mysql-mysql-1",
		"spark.streaming.batchDuration": "5",
		"spark.executor.instances": "2",
		"spark.executor.cores": "1",
		"spark.executor.memory": "1g"
	},
	"source": [{
		"driver": "com.mysql.cj.jdbc.Driver",
		"password": "******",
		"plugin_name": "jdbc",
		"result_table_name": "test_user_bak",
		"table": "test_user",
		"query": "select * from test_source.test_user ",
		"url": "jdbc:mysql://192.168.*.*:3306/test_source",
		"user": "root"
	}],
	"sink": [{
		"driver": "com.mysql.cj.jdbc.Driver",
		"password": "******",
		"save_mode": "append",
		"database": "test_target",
		"table": "test_user_bak",
		"plugin_name": "jdbc",
		"source_table_name": "test_user",
		"query": "INSERT INTO test_target.test_user_bak (id,name,mail,id_card,remark) VALUES (?, ?, ?, ?, ?)",
		"url": "jdbc:mysql://192.168.*.*:3306/test_target",
		"user": "root"
	}],
	"transform": []
}
```

### Running Command

```shell
//success
sh /opt/apache-seatunnel-incubating-2.3.1/bin/seatunnel.sh --config /opt/configTemp/142003.json -e local

//error
sh /opt/apache-seatunnel-incubating-2.3.1/bin/start-seatunnel-spark-3-connector-v2.sh --master local[4] --deploy-mode client --config /opt/configTemp/142003.json
```

### Error Exception

```log
23/06/14 16:39:43 ERROR SparkTaskExecuteCommand: Run SeaTunnel on spark failed.
org.apache.spark.sql.AnalysisException: Table or view not found: test_user;
'UnresolvedRelation [test_user], [], false

        at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:42)
        at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis$1(CheckAnalysis.scala:126)
        at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis$1$adapted(CheckAnalysis.scala:97)
        at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:263)
        at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis(CheckAnalysis.scala:97)
        at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis$(CheckAnalysis.scala:92)
        at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:182)
        at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:205)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:330)
        at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:202)
        at org.apache.spark.sql.execution.QueryExecution.$anonfun$analyzed$1(QueryExecution.scala:75)
        at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
        at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:183)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
        at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:183)
        at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:75)
        at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:73)
        at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:65)
        at org.apache.spark.sql.Dataset$.$anonfun$ofRows$1(Dataset.scala:90)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
        at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:88)
        at org.apache.spark.sql.DataFrameReader.table(DataFrameReader.scala:641)
        at org.apache.seatunnel.core.starter.spark.execution.SparkAbstractPluginExecuteProcessor.fromSourceTable(SparkAbstractPluginExecuteProcessor.java:83)
        at org.apache.seatunnel.core.starter.spark.execution.SinkExecuteProcessor.execute(SinkExecuteProcessor.java:101)
        at org.apache.seatunnel.core.starter.spark.execution.SparkExecution.execute(SparkExecution.java:74)
        at org.apache.seatunnel.core.starter.spark.command.SparkTaskExecuteCommand.execute(SparkTaskExecuteCommand.java:60)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.spark.SeaTunnelSpark.main(SeaTunnelSpark.java:35)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:966)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:191)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:214)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1054)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1063)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
23/06/14 16:39:43 ERROR SeaTunnel:

===============================================================================


23/06/14 16:39:43 ERROR SeaTunnel: Fatal Error,

23/06/14 16:39:43 ERROR SeaTunnel: Please submit bug report in https://github.com/apache/incubator-seatunnel/issues

23/06/14 16:39:43 ERROR SeaTunnel: Reason:Table or view not found: test_user;
'UnresolvedRelation [test_user], [], false


23/06/14 16:39:43 ERROR SeaTunnel: Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: Table or view not found: test_user;
'UnresolvedRelation [test_user], [], false

        at org.apache.seatunnel.core.starter.spark.command.SparkTaskExecuteCommand.execute(SparkTaskExecuteCommand.java:63)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.spark.SeaTunnelSpark.main(SeaTunnelSpark.java:35)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:966)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:191)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:214)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1054)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1063)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

### Flink or Spark Version

spark 3.2.4

### Java or Scala Version

jdk 1.8

### Screenshots

![image](https://github.com/apache/seatunnel/assets/58406500/468298ed-4831-40d6-a4b9-021cfb2984b5)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhilinli123** [comment]
Can you provide your.conf file?

**Comment by zhilinli123** [comment]
Did you try to reproduce this problem using.conf files

**Comment by WeirsWesley** [comment]
> Did you try to reproduce this problem using.conf files

I try to use .conf file, but also err.

![image](https://github.com/apache/seatunnel/assets/58406500/55cd10e5-3e48-41c0-ac23-5ab6eee82205)

//142111.conf
`env {
	job.mode = "BATCH"
	spark.app.name = "mysql-mysql"
	spark.app.id = "mysql-mysql-1"
	spark.streaming.batchDuration = 5
	spark.executor.instances = 2
	spark.executor.cores = 1
	spark.executor.memory = "1g"
}
source {
	jdbc {
		driver = "com.mysql.cj.jdbc.Driver",
			password = "******",
			result_table_name = "test_user_bak",
			table = "test_user",
			query = "select * from test_source.test_user ",
			url = "jdbc:mysql://192.168.*.*:3306/test_source",
			user = "root"
	}
}
sink {
	jdbc {
		driver = "com.mysql.cj.jdbc.Driver",
			password = "******",
			save_mode = "append",
			database = "test_target",
			table = "test_user_bak",
			source_table_name = "test_user",
			query = "INSERT INTO test_target.test_user_bak (id,name,mail,id_card,remark) VALUES (?, ?, ?, ?, ?)",
			url = "jdbc:mysql://192.168.*.*:3306/test_target",
			user = "root"
	}
}
transform {}
`
![image](https://github.com/apache/seatunnel/assets/58406500/11643a33-8d3b-4b5b-b500-2268176ee4cd)

**Comment by zhilinli123** [comment]
Ok, I will confirm this question. Thank you for your reply

**Comment by zhilinli123** [comment]
Your configuration is not legal, I suggest you look at the website to see how to use it believe it is better and easier to get started

reference:https://seatunnel.apache.org/docs/connector-v2/source/Mysql

**Comment by WeirsWesley** [comment]
> Your configuration is not legal, I suggest you look at the website to see how to use it believe it is better and easier to get started
> 
> reference:https://seatunnel.apache.org/docs/connector-v2/source/Mysql

Thank you very much. This version of the document is much more detailed than what I saw on the  [seatunel official website](https://seatunnel.incubator.apache.org/docs/2.3.1/connector-v2/source/Jdbc) and the problem has been resolved.

**Comment by zhilinli123** [comment]
Problem solved, please close it at any time thank you
