### ISSUE TITLE
[Bug] [E2E] mysql-cdc e2e error

### ISSUE THREAD

**Issue by hailin0** [apache/seatunnel#4944]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

2023-06-14T07:09:35.3926415Z [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 117.428 s <<< FAILURE! - in org.apache.seatunnel.connectors.seatunnel.cdc.mysql.MysqlCDCIT
2023-06-14T07:09:35.3927515Z [ERROR] testMysqlCdcCheckDataE2e{TestContainer}[1]  Time elapsed: 77.414 s  <<< ERROR!
2023-06-14T07:09:35.3928649Z org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in org.apache.seatunnel.connectors.seatunnel.cdc.mysql.MysqlCDCIT iterable lengths differ, expected: <3> but was: <0> within 1 minutes.
2023-06-14T07:09:35.3929539Z 	at org.apache.seatunnel.connectors.seatunnel.cdc.mysql.MysqlCDCIT.testMysqlCdcCheckDataE2e(MysqlCDCIT.java:131)
2023-06-14T07:09:35.3930140Z Caused by: org.opentest4j.AssertionFailedError: iterable lengths differ, expected: <3> but was: <0>
2023-06-14T07:09:35.3930722Z 	at org.apache.seatunnel.connectors.seatunnel.cdc.mysql.MysqlCDCIT.lambda$testMysqlCdcCheckDataE2e$1(MysqlCDCIT.java:134)

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
e2e module
```

### Running Command

```shell
running e2e
```

### Error Exception

```log
org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in
```

### Screenshots

<img width="1200" alt="image" src="https://github.com/apache/seatunnel/assets/14371345/475bc834-3788-432c-96a7-59d20dba1934">

https://pipelines.actions.githubusercontent.com/serviceHosts/5f1d2e93-1249-42e2-b16d-ed31c598c5d5/_apis/pipelines/1/runs/57693/signedlogcontent/51?urlExpires=2023-06-19T02%3A06%3A09.4036866Z&urlSigningMethod=HMACV1&urlSignature=BhkQ3dSzcsLgxOGfoih7hGovqDwmj7lOLz%2FzLResQb0%3D

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhilinli123** [comment]
I'm trying to fix it, and everyone is welcome to fix it,It can be assigned to me temporarily
