### ISSUE TITLE
[Bug] [kafkaSink] The producer attempted a transactional operation in an invalid state

### ISSUE THREAD

**Issue by k8slight** [apache/seatunnel#4949]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When "semantics=EXACTLY_ONCE" is configured in kafkaSink, the data cannot be written successfully
The exception is as follows.
[org.apache.kafka.common.errors.InvalidTxnStateException: The producer attempted a transactional operation in an invalid state.]

### SeaTunnel Version

2.3.2

### SeaTunnel Config

```conf
kafka {
      topic = "mysql_user"
      bootstrap.servers = "node2:9092,node3:9092,node4:9092"
      format = json
      kafka.request.timeout.ms = 60000
      semantics = EXACTLY_ONCE
      kafka.config = {
        acks = "all"
        request.timeout.ms = 60000
        buffer.memory = 33554432
      }
  }
```

### Running Command

```shell
./bin/seatunnel.sh -c /data/config/zeta-mysql-to-kafka-batch.conf -m local
```

### Error Exception

```log
2023-06-19 15:53:01,640 INFO  org.apache.kafka.clients.producer.internals.TransactionManager - [Producer clientId=producer-SeaTunnel6884-1, transactionalId=SeaTunnel6884-1] Transiting to fatal error state due to org.apache.kafka.common.errors.InvalidTxnStateException: The producer attempted a transactional operation in an invalid state.
	2023-06-19 15:53:01,641 ERROR org.apache.seatunnel.engine.server.checkpoint.operation.CheckpointFinishedOperation - [localhost]:5802 [seatunnel-686191] [5.1] org.apache.kafka.common.errors.InvalidTxnStateException: The producer attempted a transactional operation in an invalid state.
	
	org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: org.apache.kafka.common.errors.InvalidTxnStateException: The producer attempted a transactional operation in an invalid state.
	
		at org.apache.seatunnel.engine.server.checkpoint.operation.CheckpointFinishedOperation.lambda$run$0(CheckpointFinishedOperation.java:97) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
		at org.apache.seatunnel.common.utils.RetryUtils.retryWithException(RetryUtils.java:48) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
		at org.apache.seatunnel.engine.server.checkpoint.operation.CheckpointFinishedOperation.run(CheckpointFinishedOperation.java:81) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
		at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) [seatunnel-starter.jar:2.3.3-SNAPSHOT]
		at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:273) [seatunnel-starter.jar:2.3.3-SNAPSHOT]
		at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) [seatunnel-starter.jar:2.3.3-SNAPSHOT]
		at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213) [seatunnel-starter.jar:2.3.3-SNAPSHOT]
		at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:175) [seatunnel-starter.jar:2.3.3-SNAPSHOT]
		at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:139) [seatunnel-starter.jar:2.3.3-SNAPSHOT]
		at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) [seatunnel-starter.jar:2.3.3-SNAPSHOT]
		at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [seatunnel-starter.jar:2.3.3-SNAPSHOT]
	2023-06-19 15:53:01,664 ERROR org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator - complete checkpoint failed
	java.util.concurrent.CompletionException: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: org.apache.kafka.common.errors.InvalidTxnStateException: The producer attempted a transactional operation in an invalid state.
	
		at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[?:1.8.0_361]
		at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[?:1.8.0_361]
		at java.util.concurrent.CompletableFuture.biRelay(CompletableFuture.java:1300) ~[?:1.8.0_361]
		at java.util.concurrent.CompletableFuture$BiRelay.tryFire(CompletableFuture.java:1284) ~[?:1.8.0_361]
		at java.util.concurrent.CompletableFuture$CoCompletion.tryFire(CompletableFuture.java:1034) ~[?:1.8.0_361]
		at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_361]
		at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) ~[?:1.8.0_361]
		at com.hazelcast.spi.impl.AbstractInvocationFuture.onComplete(AbstractInvocationFuture.java:1243) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
		at com.hazelcast.spi.impl.AbstractInvocationFuture.complete0(AbstractInvocationFuture.java:1234) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
		at com.hazelcast.spi.impl.AbstractInvocationFuture.completeExceptionallyInternal(AbstractInvocationFuture.java:1223) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
		at com.hazelcast.spi.impl.operationservice.impl.Invocation.completeExceptionally(Invocation.java:680) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
		at com.hazelcast.spi.impl.operationservice.impl.Invocation.notifyThrowable(Invocation.java:386) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
		at com.hazelcast.spi.impl.operationservice.impl.Invocation.notifyError(Invocation.java:330) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
		at com.hazelcast.spi.impl.operationservice.impl.Invocation.sendResponse(Invocation.java:230) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
		at com.hazelcast.spi.impl.operationservice.Operation.sendResponse(Operation.java:483) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
		at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.sendResponseAfterOperationError(OperationRunnerImpl.java:426) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
		at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.handleOperationError(OperationRunnerImpl.java:420) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
		at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:253) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
		at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
		at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:175) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
		at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:139) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
		at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
		at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
	Caused by: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: org.apache.kafka.common.errors.InvalidTxnStateException: The producer attempted a transactional operation in an invalid state.
	
		at org.apache.seatunnel.engine.server.checkpoint.operation.CheckpointFinishedOperation.lambda$run$0(CheckpointFinishedOperation.java:97) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
		at org.apache.seatunnel.common.utils.RetryUtils.retryWithException(RetryUtils.java:48) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
		at org.apache.seatunnel.engine.server.checkpoint.operation.CheckpointFinishedOperation.run(CheckpointFinishedOperation.java:81) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
		at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
		at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:273) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
		at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
		... 5 more
```

### Java or Scala Version

java version "1.8.0_361"

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
Provide the topic information of Kafka, including partitions, etc.

**Comment by k8slight** [comment]
> Provide the topic information of Kafka, including partitions, etc.

The topic does not exist before the command is executed.
kafka config：
broker.id=1
num.network.threads=3
num.io.threads=8
socket.send.buffer.bytes=102400
socket.receive.buffer.bytes=102400
socket.request.max.bytes=104857600
log.dirs=/data/kafka
num.partitions=1
num.recovery.threads.per.data.dir=1
offsets.topic.replication.factor=3
transaction.state.log.replication.factor=3
transaction.state.log.min.isr=1
log.retention.hours=168
log.segment.bytes=1073741824
log.retention.check.interval.ms=300000
zookeeper.connection.timeout.ms=18000
group.initial.rebalance.delay.ms=0

**Comment by liugddx** [comment]
> ```shell
> ```shell
> ./bin/seatunnel.sh -c /data/config/zeta-mysql-to-kafka-batch.conf -m local
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

Great! Please put the complete configuration here.

**Comment by k8slight** [comment]
> > ```shell
> > ```shell
> > ./bin/seatunnel.sh -c /data/config/zeta-mysql-to-kafka-batch.conf -m local
> > ```
> 
> Great! Please put the complete configuration here.

env {
    execution.parallelism = 1
    job.mode = "BATCH"
}

source {

Jdbc {
        driver = "com.mysql.cj.jdbc.Driver"
        url = "jdbc:mysql://node5:3306/seatunnel?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false"
        user = "********"
        password = "********"
        query = "select * from mysql_user"
    }

}

transform {
 
}

sink {

  kafka {
      topic = "mysql_user"
      bootstrap.servers = "node2:9092,node3:9092,node4:9092"
      format = json
      kafka.request.timeout.ms = 60000
      semantics = EXACTLY_ONCE
      kafka.config = {
        acks = "all"
        request.timeout.ms = 60000
        buffer.memory = 33554432
      }
  }

}

**Comment by k8slight** [comment]
@liugddx is it bug?

**Comment by liugddx** [comment]
> transactional

Mybe. This looks like an issue with the kafka connector.

**Comment by lightzhao** [comment]
#4469 This pr has been discussed and resolved, waiting for merge.

**Comment by k8slight** [comment]
THX
