### ISSUE TITLE
[Bug] [Zeta] Local tasks are not allowed to run concurrently; only one can be running at a time.

### ISSUE THREAD

**Issue by hanyouyou13** [apache/seatunnel#4986]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I would like to run the seatunnel locally multiple times （-e local）where only the first run is successful, and all subsequent runs fail.

### SeaTunnel Version

2.3.2

### SeaTunnel Config

```conf
env {
  execution.parallelism = 2
  job.mode = "STREAMING"
  checkpoint.interval = 2000
  #execution.checkpoint.interval = 10000
  #execution.checkpoint.data-uri = "hdfs://localhost:9000/checkpoint"
}
source {
  FakeSource {
    parallelism = 2
    result_table_name = "fake"
    row.num = 16
    schema = {
      fields {
        name = "string"
        age = "int"
      }
    }
  }
}

sink {
  Console {
  }
}
```

### Running Command

```shell
sh bin/seatunnel.sh -c config/v2.streaming.conf.template -e local
```

### Error Exception

```log
2023-06-28 12:53:09,962 INFO  com.hazelcast.client.impl.clientside.ClientLoggingService$DefaultLogger.log(ClientLoggingService.java:104) - hz.client_1 [seatunnel-551475] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is STARTING
2023-06-28 12:53:09,963 WARN  com.hazelcast.logging.impl.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:263) - [localhost]:5802 [seatunnel-551475] [5.1] Received an invalid join request from [localhost]:5801, cause: members part of different cluster
2023-06-28 12:53:09,965 INFO  com.hazelcast.client.impl.clientside.ClientLoggingService$DefaultLogger.log(ClientLoggingService.java:104) - hz.client_1 [seatunnel-551475] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is STARTED
2023-06-28 12:53:09,970 INFO  com.hazelcast.logging.impl.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:263) - [localhost]:5802 [seatunnel-551475] [5.1] Connection[id=5, /127.0.0.1:5802->/127.0.0.1:46982, qualifier=null, endpoint=[localhost]:5801, remoteUuid=e02c61f2-6c78-45f1-abd1-07b0b03b6e3b, alive=false, connectionType=MEMBER, planeIndex=0] closed. Reason: Connection closed by the other side
2023-06-28 12:53:09,991 INFO  com.hazelcast.client.impl.clientside.ClientLoggingService$DefaultLogger.log(ClientLoggingService.java:104) - hz.client_1 [seatunnel-551475] [5.1] Trying to connect to cluster: seatunnel-551475
2023-06-28 12:53:09,993 INFO  com.hazelcast.client.impl.clientside.ClientLoggingService$DefaultLogger.log(ClientLoggingService.java:104) - hz.client_1 [seatunnel-551475] [5.1] Trying to connect to [localhost]:5801
2023-06-28 12:53:10,013 WARN  com.hazelcast.client.impl.clientside.ClientLoggingService$DefaultLogger.log(ClientLoggingService.java:104) - hz.client_1 [seatunnel-551475] [5.1] ClientConnection{alive=false, connectionId=1, channel=NioChannel{/127.0.0.1:43672->localhost/127.0.0.1:5801}, remoteAddress=null, lastReadTime=2023-06-28 12:53:10.008, lastWriteTime=2023-06-28 12:53:10.007, closedTime=2023-06-28 12:53:10.010, connected server version=null} closed. Reason: Failed to authenticate connection
com.hazelcast.client.AuthenticationException: Authentication failed. The configured cluster name on the client (see ClientConfig.setClusterName()) does not match the one configured in the cluster or the credentials set in the Client security config could not be authenticated
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.checkAuthenticationResponse(TcpClientConnectionManager.java:995) ~[seatunnel-starter.jar:2.3.2]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.onAuthenticated(TcpClientConnectionManager.java:898) ~[seatunnel-starter.jar:2.3.2]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.getOrConnectToAddress(TcpClientConnectionManager.java:615) ~[seatunnel-starter.jar:2.3.2]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.lambda$doConnectToCandidateCluster$3(TcpClientConnectionManager.java:505) ~[seatunnel-starter.jar:2.3.2]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.connect(TcpClientConnectionManager.java:459) [seatunnel-starter.jar:2.3.2]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.doConnectToCandidateCluster(TcpClientConnectionManager.java:505) [seatunnel-starter.jar:2.3.2]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.doConnectToCluster(TcpClientConnectionManager.java:411) [seatunnel-starter.jar:2.3.2]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.connectToCluster(TcpClientConnectionManager.java:372) [seatunnel-starter.jar:2.3.2]
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:381) [seatunnel-starter.jar:2.3.2]
	at com.hazelcast.client.HazelcastClient.constructHazelcastClient(HazelcastClient.java:460) [seatunnel-starter.jar:2.3.2]
	at com.hazelcast.client.HazelcastClient.newHazelcastClientInternal(HazelcastClient.java:416) [seatunnel-starter.jar:2.3.2]
	at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:136) [seatunnel-starter.jar:2.3.2]
	at org.apache.seatunnel.engine.client.SeaTunnelHazelcastClient.<init>(SeaTunnelHazelcastClient.java:53) [seatunnel-starter.jar:2.3.2]
	at org.apache.seatunnel.engine.client.SeaTunnelClient.<init>(SeaTunnelClient.java:46) [seatunnel-starter.jar:2.3.2]
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:111) [seatunnel-starter.jar:2.3.2]
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40) [seatunnel-starter.jar:2.3.2]
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34) [seatunnel-starter.jar:2.3.2]
2023-06-28 12:53:10,020 WARN  com.hazelcast.client.impl.clientside.ClientLoggingService$DefaultLogger.log(ClientLoggingService.java:104) - hz.client_1 [seatunnel-551475] [5.1] Exception during initial connection to [localhost]:5801: com.hazelcast.client.AuthenticationException: Authentication failed. The configured cluster name on the client (see ClientConfig.setClusterName()) does not match the one configured in the cluster or the credentials set in the Client security config could not be authenticated
2023-06-28 12:53:10,021 WARN  com.hazelcast.client.impl.clientside.ClientLoggingService$DefaultLogger.log(ClientLoggingService.java:104) - hz.client_1 [seatunnel-551475] [5.1] Unable to get live cluster connection, retry in 1000 ms, attempt: 1, cluster connect timeout: 3000 ms, max backoff: 30000 ms
2023-06-28 12:53:10,426 INFO  com.hazelcast.logging.impl.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:263) - [localhost]:5802 [seatunnel-551475] [5.1] This node become a new active master node, begin init coordinator service
2023-06-28 12:53:10,658 INFO  com.hazelcast.logging.impl.LoggingServiceImpl$DefaultLogger.log(LoggingServiceImpl.java:263) - [localhost]:5802 [seatunnel-551475] [5.1] Initializing cluster partition table arrangement...
2023-06-28 12:53:11,021 INFO  com.hazelcast.client.impl.clientside.ClientLoggingService$DefaultLogger.log(ClientLoggingService.java:104) - hz.client_1 [seatunnel-551475] [5.1] Trying to connect to [localhost]:5801
2023-06-28 12:53:11,032 WARN  com.hazelcast.client.impl.clientside.ClientLoggingService$DefaultLogger.log(ClientLoggingService.java:104) - hz.client_1 [seatunnel-551475] [5.1] ClientConnection{alive=false, connectionId=2, channel=NioChannel{/127.0.0.1:54643->localhost/127.0.0.1:5801}, remoteAddress=null, lastReadTime=2023-06-28 12:53:11.028, lastWriteTime=2023-06-28 12:53:11.025, closedTime=2023-06-28 12:53:11.029, connected server version=null} closed. Reason: Failed to authenticate connection
com.hazelcast.client.AuthenticationException: Authentication failed. The configured cluster name on the client (see ClientConfig.setClusterName()) does not match the one configured in the cluster or the credentials set in the Client security config could not be authenticated
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.checkAuthenticationResponse(TcpClientConnectionManager.java:995) ~[seatunnel-starter.jar:2.3.2]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.onAuthenticated(TcpClientConnectionManager.java:898) ~[seatunnel-starter.jar:2.3.2]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.getOrConnectToAddress(TcpClientConnectionManager.java:615) ~[seatunnel-starter.jar:2.3.2]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.lambda$doConnectToCandidateCluster$3(TcpClientConnectionManager.java:505) ~[seatunnel-starter.jar:2.3.2]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.connect(TcpClientConnectionManager.java:459) [seatunnel-starter.jar:2.3.2]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.doConnectToCandidateCluster(TcpClientConnectionManager.java:505) [seatunnel-starter.jar:2.3.2]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.doConnectToCluster(TcpClientConnectionManager.java:411) [seatunnel-starter.jar:2.3.2]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.connectToCluster(TcpClientConnectionManager.java:372) [seatunnel-starter.jar:2.3.2]
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:381) [seatunnel-starter.jar:2.3.2]
	at com.hazelcast.client.HazelcastClient.constructHazelcastClient(HazelcastClient.java:460) [seatunnel-starter.jar:2.3.2]
	at com.hazelcast.client.HazelcastClient.newHazelcastClientInternal(HazelcastClient.java:416) [seatunnel-starter.jar:2.3.2]
	at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:136) [seatunnel-starter.jar:2.3.2]
	at org.apache.seatunnel.engine.client.SeaTunnelHazelcastClient.<init>(SeaTunnelHazelcastClient.java:53) [seatunnel-starter.jar:2.3.2]
	at org.apache.seatunnel.engine.client.SeaTunnelClient.<init>(SeaTunnelClient.java:46) [seatunnel-starter.jar:2.3.2]
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:111) [seatunnel-starter.jar:2.3.2]
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40) [seatunnel-starter.jar:2.3.2]
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34) [seatunnel-starter.jar:2.3.2]
2023-06-28 12:53:11,035 WARN  com.hazelcast.client.impl.clientside.ClientLoggingService$DefaultLogger.log(ClientLoggingService.java:104) - hz.client_1 [seatunnel-551475] [5.1] Exception during initial connection to [localhost]:5801: com.hazelcast.client.AuthenticationException: Authentication failed. The configured cluster name on the client (see ClientConfig.setClusterName()) does not match the one configured in the cluster or the credentials set in the Client security config could not be authenticated
2023-06-28 12:53:11,036 WARN  com.hazelcast.client.impl.clientside.ClientLoggingService$DefaultLogger.log(ClientLoggingService.java:104) - hz.client_1 [seatunnel-551475] [5.1] Unable to get live cluster connection, retry in 1050 ms, attempt: 2, cluster connect timeout: 3000 ms, max backoff: 30000 ms
2023-06-28 12:53:12,087 INFO  com.hazelcast.client.impl.clientside.ClientLoggingService$DefaultLogger.log(ClientLoggingService.java:104) - hz.client_1 [seatunnel-551475] [5.1] Trying to connect to [localhost]:5801
2023-06-28 12:53:12,096 WARN  com.hazelcast.client.impl.clientside.ClientLoggingService$DefaultLogger.log(ClientLoggingService.java:104) - hz.client_1 [seatunnel-551475] [5.1] ClientConnection{alive=false, connectionId=3, channel=NioChannel{/127.0.0.1:35959->localhost/127.0.0.1:5801}, remoteAddress=null, lastReadTime=2023-06-28 12:53:12.094, lastWriteTime=2023-06-28 12:53:12.091, closedTime=2023-06-28 12:53:12.095, connected server version=null} closed. Reason: Failed to authenticate connection
com.hazelcast.client.AuthenticationException: Authentication failed. The configured cluster name on the client (see ClientConfig.setClusterName()) does not match the one configured in the cluster or the credentials set in the Client security config could not be authenticated
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.checkAuthenticationResponse(TcpClientConnectionManager.java:995) ~[seatunnel-starter.jar:2.3.2]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.onAuthenticated(TcpClientConnectionManager.java:898) ~[seatunnel-starter.jar:2.3.2]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.getOrConnectToAddress(TcpClientConnectionManager.java:615) ~[seatunnel-starter.jar:2.3.2]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.lambda$doConnectToCandidateCluster$3(TcpClientConnectionManager.java:505) ~[seatunnel-starter.jar:2.3.2]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.connect(TcpClientConnectionManager.java:459) [seatunnel-starter.jar:2.3.2]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.doConnectToCandidateCluster(TcpClientConnectionManager.java:505) [seatunnel-starter.jar:2.3.2]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.doConnectToCluster(TcpClientConnectionManager.java:411) [seatunnel-starter.jar:2.3.2]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.connectToCluster(TcpClientConnectionManager.java:372) [seatunnel-starter.jar:2.3.2]
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:381) [seatunnel-starter.jar:2.3.2]
	at com.hazelcast.client.HazelcastClient.constructHazelcastClient(HazelcastClient.java:460) [seatunnel-starter.jar:2.3.2]
	at com.hazelcast.client.HazelcastClient.newHazelcastClientInternal(HazelcastClient.java:416) [seatunnel-starter.jar:2.3.2]
	at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:136) [seatunnel-starter.jar:2.3.2]
	at org.apache.seatunnel.engine.client.SeaTunnelHazelcastClient.<init>(SeaTunnelHazelcastClient.java:53) [seatunnel-starter.jar:2.3.2]
	at org.apache.seatunnel.engine.client.SeaTunnelClient.<init>(SeaTunnelClient.java:46) [seatunnel-starter.jar:2.3.2]
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:111) [seatunnel-starter.jar:2.3.2]
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40) [seatunnel-starter.jar:2.3.2]
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34) [seatunnel-starter.jar:2.3.2]
2023-06-28 12:53:12,099 WARN  com.hazelcast.client.impl.clientside.ClientLoggingService$DefaultLogger.log(ClientLoggingService.java:104) - hz.client_1 [seatunnel-551475] [5.1] Exception during initial connection to [localhost]:5801: com.hazelcast.client.AuthenticationException: Authentication failed. The configured cluster name on the client (see ClientConfig.setClusterName()) does not match the one configured in the cluster or the credentials set in the Client security config could not be authenticated
2023-06-28 12:53:12,100 WARN  com.hazelcast.client.impl.clientside.ClientLoggingService$DefaultLogger.log(ClientLoggingService.java:104) - hz.client_1 [seatunnel-551475] [5.1] Unable to get live cluster connection, retry in 892 ms, attempt: 3, cluster connect timeout: 3000 ms, max backoff: 30000 ms
2023-06-28 12:53:12,994 INFO  com.hazelcast.client.impl.clientside.ClientLoggingService$DefaultLogger.log(ClientLoggingService.java:104) - hz.client_1 [seatunnel-551475] [5.1] Trying to connect to [localhost]:5801
```

### Java or Scala Version

1.8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ic4y** [comment]
Currently, we can run multiple tasks in local mode using separate JVM instances. The issue likely stems from the hazelcast-client.yaml where cluster-members doesn't include multiple ports. I suggest configuring it like the image shown below:
<img width="240" alt="image" src="https://github.com/apache/seatunnel/assets/83933160/746bf90b-5fbb-4c23-afc4-177c15063c65">
With this, we can run up to 9 jobs simultaneously

**Comment by notAprogrammer-0** [comment]
> Currently, we can run multiple tasks in local mode using separate JVM instances. The issue likely stems from the hazelcast-client.yaml where cluster-members doesn't include multiple ports. I suggest configuring it like the image shown below: <img alt="image" width="240" src="https://private-user-images.githubusercontent.com/83933160/258575480-746bf90b-5fbb-4c23-afc4-177c15063c65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNjAyNjQsIm5iZiI6MTcwNDE1OTk2NCwicGF0aCI6Ii84MzkzMzE2MC8yNTg1NzU0ODAtNzQ2YmY5MGItNWZiYi00YzIzLWFmYzQtMTc3YzE1MDYzYzY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDAxNDYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNDJkMjBkM2I0YzUwYjA0YWUyMTFmOWQ3NDY2ZjkzY2RlNDU1MjAzNDQ3NGI5ZjM1YWZkOGY3Mzc3ZmNiMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pij2uQ2A5ACDWlATd_LkC-DUdmyOAAv_pR1knlV3QUE"> With this, we can run up to 9 jobs simultaneously

I also encountered this problem, but after I configured it according to the picture, it still didn’t work and I reported this error:

2024-01-02 10:04:01,964 WARN  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-503037] [5.1] Exception during initial connection to [localhost]:5809: com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address localhost/127.0.0.1:5809
2024-01-02 10:04:01,964 WARN  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-503037] [5.1] Exception during initial connection to [localhost]:5804: com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address localhost/127.0.0.1:5804
2024-01-02 10:04:01,965 WARN  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-503037] [5.1] Exception during initial connection to [localhost]:5803: com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address localhost/127.0.0.1:5803
2024-01-02 10:04:01,965 WARN  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-503037] [5.1] Exception during initial connection to [localhost]:5815: com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address localhost/127.0.0.1:5815
2024-01-02 10:04:01,965 WARN  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-503037] [5.1] Exception during initial connection to [localhost]:5818: com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address localhost/127.0.0.1:5818
2024-01-02 10:04:01,966 WARN  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-503037] [5.1] Exception during initial connection to [localhost]:5802: com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address localhost/127.0.0.1:5802
2024-01-02 10:04:01,966 WARN  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-503037] [5.1] Exception during initial connection to [localhost]:5810: com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address localhost/127.0.0.1:5810
2024-01-02 10:04:01,966 WARN  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-503037] [5.1] Exception during initial connection to [localhost]:5814: com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address localhost/127.0.0.1:5814
2024-01-02 10:04:01,966 WARN  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-503037] [5.1] Exception during initial connection to [localhost]:5806: com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address localhost/127.0.0.1:5806
2024-01-02 10:04:01,967 WARN  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-503037] [5.1] Exception during initial connection to [localhost]:5817: com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address localhost/127.0.0.1:5817
2024-01-02 10:04:01,967 WARN  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-503037] [5.1] Exception during initial connection to [localhost]:5813: com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address localhost/127.0.0.1:5813

**Comment by notAprogrammer-0** [comment]
And i change hazelcast-client.yaml like this:

hazelcast-client:
  cluster-name: seatunnel
  properties:
    hazelcast.logging.type: log4j2
  network:
    cluster-members:
- localhost:5801
- localhost:5805
- localhost:5812

It reported this error:
2024-01-02 10:51:01,422 WARN  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5802 [seatunnel-995578] [5.1] The Node is not ready yet, Node state STARTING,looking forward to the next scheduling
2024-01-02 10:51:01,436 WARN  org.apache.seatunnel.engine.server.service.slot.DefaultSlotService - failed send heartbeat to resource manager, will retry later. this address: [localhost]:5802
2024-01-02 10:51:01,716 WARN  com.hazelcast.cluster - [localhost]:5802 [seatunnel-995578] [5.1] Node could not join cluster at node: [localhost]:5801 Cause: the target cluster has a different cluster-name
2024-01-02 10:51:02,609 WARN  com.hazelcast.instance.impl.Node - [localhost]:5802 [seatunnel-995578] [5.1] Config seed port is 5801 and cluster size is 1. Some of the ports seem occupied!
Jan 02, 2024 10:51:02 AM com.hazelcast.internal.config.AbstractConfigLocator
INFO: Loading configuration '/opt/seatunnel/seatunnel-2.3.3/config/hazelcast-client.yaml' from System property 'hazelcast.client.config'
Jan 02, 2024 10:51:02 AM com.hazelcast.internal.config.AbstractConfigLocator
INFO: Using configuration file at /opt/seatunnel/seatunnel-2.3.3/config/hazelcast-client.yaml
2024-01-02 10:51:02,700 WARN  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-995578] [5.1] Exception during initial connection to [localhost]:5812: com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address localhost/127.0.0.1:5812
2024-01-02 10:51:02,700 WARN  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-995578] [5.1] Exception during initial connection to [localhost]:5805: com.hazelcast.core.HazelcastException: java.io.IOException: Connection refused to address localhost/127.0.0.1:5805
