### ISSUE TITLE
[Bug] [kafka source] 无法设置max.poll.records参数

### ISSUE THREAD

**Issue by ocean-zhc** [apache/seatunnel#5006]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

source kafka  kafka.config 无法设置  `max.poll.records` 参数，取消则正常！

### SeaTunnel Version

2.3.2 
2.3.2-SNAPSHOT

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
  job.mode = "STREAMING"
  execution.planner = blink
  job.name = "kafka_console_test"
  execution.checkpoint.interval = 60000
}

source {

  Kafka {
    result_table_name = "kafka_table"
    schema = {
      fields {
        name = "string"
        age = "int"
      }
    }
    topic = "topic1"
    bootstrap.servers = "local:19092"
    kafka.config = {
      client.id = client_1
      max.poll.records = 10000
      auto.offset.reset = "earliest"
      enable.auto.commit = "false"
    }
  }
  
}

transform {
  
}

sink {
  Hive {
    table_name = "default.user1"
    metastore_uri = "thrift://centos4:9083"
  }
}
```

### Running Command

```shell
./bin/start-seatunnel-flink-15-connector-v2.sh --config ./config/kafka2hive.conf
```

### Error Exception

```log
java.lang.NullPointerException: null value in entry: max.poll.records=null
	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:32) ~[?:?]
	at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:176) ~[guava-11.0.2.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:285) ~[guava-11.0.2.jar:?]
	at com.google.common.collect.Maps.fromProperties(Maps.java:1362) ~[guava-11.0.2.jar:?]
	at org.apache.seatunnel.connectors.seatunnel.kafka.source.KafkaSourceReader.lambda$null$3(KafkaSourceReader.java:134) ~[?:?]
	at org.apache.seatunnel.connectors.seatunnel.kafka.source.KafkaConsumerThread.run(KafkaConsumerThread.java:58) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_172]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_172]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_172]
```

### Flink or Spark Version

1.16.2

### Java or Scala Version

1.8.0_172

### Screenshots

![image](https://github.com/apache/seatunnel/assets/46189785/0efddddb-9ac3-49f9-ba11-4d3dc504bf0d)

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liugddx** [comment]
I tried it and found no problem, can you try it with `jdk1.8.351` or later.

**Comment by ocean-zhc** [comment]
tks！I'm OK!

**Comment by ocean-zhc** [comment]
> I tried it and found no problem, can you try it with jdk1.8.351 or later.

jdk1.8.351 、jdk1.8.361 我都试了，好像不行

<img width="1183" alt="企业微信截图_d0f14283-94d8-4022-84dc-b353a1aa0cba" src="https://github.com/apache/seatunnel/assets/46189785/4e387cab-1851-405f-8b82-64b006329350">

<img width="1267" alt="image" src="https://github.com/apache/seatunnel/assets/46189785/21901a63-b394-4bc1-bb73-0ea0240e32f0">

**Comment by ocean-zhc** [comment]
max.poll.records = "10000"  can solved!
