### ISSUE TITLE
[Feature][JDBC] Oracle to Oracle , can bind a LONG value only for insert into a LONG column

### ISSUE THREAD

**Issue by yfrhz** [apache/seatunnel#5029]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

从Oracle同步数据到Oracle不支持大字段。不知道这个算feature还是bug
同步大字段时会出现如下报错：

Caused by: org.apache.seatunnel.connectors.seatunnel.jdbc.exception.JdbcConnectorException: ErrorCode:[COMMON-10], ErrorDescription:[Flush data operation that in sink connector failed] - Writing records to JDBC failed.
        at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.JdbcOutputFormat.checkFlushException(JdbcOutputFormat.java:132)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.JdbcOutputFormat.writeRecord(JdbcOutputFormat.java:140)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.sink.JdbcSinkWriter.write(JdbcSinkWriter.java:81)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.sink.JdbcSinkWriter.write(JdbcSinkWriter.java:44)
        at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:202)
        ... 15 more
Caused by: org.apache.seatunnel.connectors.seatunnel.jdbc.exception.JdbcConnectorException: ErrorCode:[COMMON-10], ErrorDescription:[Flush data operation that in sink connector failed] - java.sql.BatchUpdateException: ORA-01461: can bind a LONG value only for insert into a LONG column

配置为（隐藏了敏感信息）：

env {
  execution.parallelism = 1
  job.mode = "STREAMING"
  checkpoint.interval = 15000
}
source{
    Jdbc {
        url = "jdbc:oracle:thin:@//*.*.*.*:1521/*"
        driver = "oracle.jdbc.OracleDriver"
        connection_check_timeout_sec = 100
        user = "***"
        password = "***"
        query = "select * from *** where updt_dt>sysdate-1/1440 and rownum<=1000"
    }
}
sink {
    jdbc {
        url = "jdbc:oracle:thin:@//*.*.*.*:1521/*"
        driver = "oracle.jdbc.OracleDriver"
        user = "***"
        password = "***"
        database="***"
        table = "***"
        primary_keys = ["***"]
        generate_sink_sql ="true"
}
}

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by addyming** [comment]
我也从Oracle同步数据到Oracle，现在也遇到这个问题，有对应好的方法了吗？

**Comment by Japson0** [comment]
https://github.com/apache/seatunnel/issues/6097
你们可以看下这篇

**Comment by Japson0** [comment]
https://github.com/apache/seatunnel/issues/6097
你们可以看下这篇

**Comment by Ivan-gfan** [comment]
> https://github.com/apache/seatunnel/issues/6097
> 你们可以看下这篇

我字段长度很短啊，我就插5个汉字都会报错，只要是clob字段就有问题
