### ISSUE TITLE
why v232 udf  report error?

### ISSUE THREAD

**Issue by hustxjs** [apache/seatunnel#5059]
I follow official document  test udf :
[https://seatunnel.apache.org/zh-CN/docs/2.3.2/transform-v2/sql-udf/](url)

get blow error
```shell
Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:188)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.shade.com.typesafe.config.ConfigException$WrongType: hardcoded value: transform has type list of STRING rather than list of OBJECT
        at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.getHomogeneousWrappedList(SimpleConfig.java:452)
        at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.getObjectList(SimpleConfig.java:460)
        at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.getConfigList(SimpleConfig.java:465)
        at org.apache.seatunnel.common.config.TypesafeConfigUtils.getConfigList(TypesafeConfigUtils.java:115)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:134)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.getLogicalDag(JobExecutionEnvironment.java:155)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:147)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:140)
        ... 2 more
```
All according to the official document, why ?

**Comment by liunaijie** [comment]
pls provide the config

**Comment by hustxjs** [comment]
here is java code:
```java
@AutoService(ZetaUDF.class)
public class qdmxUDF implements ZetaUDF {

    @Override
    public String functionName() {
        return "qdmx";
    }

    @Override
    public SeaTunnelDataType<?> resultType(List<SeaTunnelDataType<?>> list) {
        return BasicType.STRING_TYPE;
    }

    @Override
    public Object evaluate(List<Object> list) {
        String str = list.get(0).toString();
        return "b:"+list.get(0).toString();
    }

}
```

and config is :
```xml
env {
  execution.parallelism = 1
  job.mode = "BATCH"
}

source {
  Clickhouse {
    host = "192.168.9.103:8123"
    database = "default"
    username = "root"
    password = "1234567"
	sql = "select id, name from default.tt1 "
    result_table_name = "fake"
  }
  
}


transform {
    source_table_name = "fake"
    result_table_name = "fake1"
   udf {
        function.example = "com.dscomm.web.qdmxUDF"
    }
    
  Sql {
    
    query = "select id, qdmx(name) as name2  from fake"
  }
}

sink {
  Console {
    source_table_name = "fake1"
  }

}
```

@liunaijie

**Comment by liunaijie** [comment]
1. package and move lib to ${SEATUNNEL_HOME}/lib
2. update config to this
```
transform {
  Sql {
    source_table_name = "fake"
    result_table_name = "fake1"   
    query = "select id, qdmx(name) as name2  from fake"
  }
}
```

**Comment by hustxjs** [comment]
yes, jar pack already put into lib dir.
conf change to blow and run, it say 
```shell
Caused by: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: java.util.ServiceConfigurationError: org.apache.seatunnel.transform.sql.zeta.ZetaUDF: Provider com.dscomm.web.qdmxUDF not found
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1219)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
        at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
        at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
        at java.base/java.lang.Iterable.forEach(Iterable.java:74)
        at org.apache.seatunnel.transform.sql.zeta.ZetaSQLEngine.init(ZetaSQLEngine.java:67)
        at org.apache.seatunnel.transform.sql.SQLTransform.open(SQLTransform.java:118)
        at org.apache.seatunnel.engine.server.task.flow.TransformFlowLifeCycle.open(TransformFlowLifeCycle.java:63)
        at org.apache.seatunnel.engine.server.task.SeaTunnelTask.stateProcess(SeaTunnelTask.java:146)
        at org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask.call(SourceSeaTunnelTask.java:89)
        at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:613)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

        at org.apache.seatunnel.engine.client.job.ClientJobProxy.waitForJobComplete(ClientJobProxy.java:122)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:181)
        ... 2 more
```

> 1. package and move lib to ${SEATUNNEL_HOME}/lib
> 2. update config to this
> 
> ```
> transform {
>   Sql {
>     source_table_name = "fake"
>     result_table_name = "fake1"   
>     query = "select id, qdmx(name) as name2  from fake"
>   }
> }
> ```

**Comment by liunaijie** [comment]
this error is can't find your udf. 
pls check: is your udf lib is real pack and put to the ${SEATUNNEL_HOME}/lib. 

and yesterday i test your code with version 2.3.2. it can run successful.

**Comment by hustxjs** [comment]
> this error is can't find your udf. pls check: is your udf lib is real pack and put to the ${SEATUNNEL_HOME}/lib.
> 
> and yesterday i test your code with version 2.3.2. it can run successful.

weather need setup env vari in /etc/profile ?

**Comment by liunaijie** [comment]
> > this error is can't find your udf. pls check: is your udf lib is real pack and put to the ${SEATUNNEL_HOME}/lib.
> > and yesterday i test your code with version 2.3.2. it can run successful.
> 
> weather need setup env vari in /etc/profile ?

no, i download the seatunnel lib from [download page](https://seatunnel.apache.org/download), unpack and copy the udf lib to unpacked dir's lib folder

**Comment by hustxjs** [comment]
> > > this error is can't find your udf. pls check: is your udf lib is real pack and put to the ${SEATUNNEL_HOME}/lib.
> > > and yesterday i test your code with version 2.3.2. it can run successful.
> > 
> > 
> > weather need setup env vari in /etc/profile ?
> 
> no, i download the seatunnel lib from [download page](https://seatunnel.apache.org/download), unpack and copy the udf lib to unpacked dir's lib folder

here is my seatunnel folder tree:
```
seatunnel-2.3.2/
├── bin
│   ├── install-plugin.sh
│   ├── seatunnel-cluster.sh
│   ├── seatunnel.sh
│   ├── start-seatunnel-flink-13-connector-v2.sh
│   ├── start-seatunnel-flink-15-connector-v2.sh
│   ├── start-seatunnel-spark-2-connector-v2.sh
│   ├── start-seatunnel-spark-3-connector-v2.sh
│   └── stop-seatunnel-cluster.sh
├── config
│   ├── hazelcast-client.yaml
│   ├── hazelcast.yaml
│   ├── jvm_client_options
│   ├── jvm_options
│   ├── log4j2_client.properties
│   ├── log4j2.properties
│   ├── plugin_config
│   ├── seatunnel-env.sh
│   ├── seatunnel.yaml
│   ├── v2.batch.config.template
│   └── v2.streaming.conf.template
├── connectors
│   ├── plugin-mapping.properties
│   └── seatunnel
│       ├── connector-cdc-mysql-2.3.2.jar
│       ├── connector-clickhouse-2.3.2.jar
│       ├── connector-console-2.3.2.jar
│       ├── connector-doris-2.3.2.jar
│       ├── connector-fake-2.3.2.jar
│       └── connector-jdbc-2.3.2.jar
├── DISCLAIMER
├── job
│   └── ck1.conf
├── lib
│   ├── seatunnel-transforms-v2.jar
│   └── seatunnel-udf-0.0.1-SNAPSHOT.jar  <===== my udf jar
├── LICENSE
├── licenses
│   ├── LICENSE-asm.txt
│   ├── LICENSE-avro.txt
│   ├── LICENSE-connons-math.txt
│   ├── LICENSE-javax-annootation-api.txt
│   ├── LICENSE-orc.txt
│   ├── LICENSE-parquet-format.txt
│   ├── LICENSE-parquet-mr.txt
│   ├── LICENSE-protobuf.txt
│   ├── LICENSE-scala.txt
│   ├── LICENSE-sjf4j.txt
│   ├── LICENSE-xz.txt
│   └── LICENSE-yetus.txt
├── mvnw
├── mvnw.cmd
├── NOTICE
├── plugins
│   └── README.md
├── README.md
└── starter
    ├── logging
    │   ├── jcl-over-slf4j-1.7.25.jar
    │   ├── log4j-api-2.17.1.jar
    │   ├── log4j-core-2.17.1.jar
    │   ├── log4j-slf4j-impl-2.17.1.jar
    │   └── slf4j-api-1.7.25.jar
    ├── seatunnel-flink-13-starter.jar
    ├── seatunnel-flink-15-starter.jar
    ├── seatunnel-spark-2-starter.jar
    ├── seatunnel-spark-3-starter.jar
    └── seatunnel-starter.jar
```
always say  "Provider com.dscomm.web.qdmxUDF not found", can u provide your seatunnel folder to me ?

**Comment by liunaijie** [comment]
FYI:
```
.
├── DISCLAIMER
├── LICENSE
├── NOTICE
├── README.md
├── bin
│   ├── install-plugin.sh
│   ├── seatunnel-cluster.sh
│   ├── seatunnel.sh
│   ├── start-seatunnel-flink-13-connector-v2.sh
│   ├── start-seatunnel-flink-15-connector-v2.sh
│   ├── start-seatunnel-spark-2-connector-v2.sh
│   ├── start-seatunnel-spark-3-connector-v2.sh
│   └── stop-seatunnel-cluster.sh
├── config
│   ├── hazelcast-client.yaml
│   ├── hazelcast.yaml
│   ├── jvm_client_options
│   ├── jvm_options
│   ├── log4j2.properties
│   ├── log4j2_client.properties
│   ├── plugin_config
│   ├── plugin_config.bak
│   ├── seatunnel-env.sh
│   ├── seatunnel.yaml
│   ├── v2.batch.config.template
│   └── v2.streaming.conf.template
├── connectors
│   ├── plugin-mapping.properties
│   └── seatunnel
│       ├── connector-console-2.3.2.jar
│       └── connector-fake-2.3.2.jar
├── example_udf.config
├── lib
│   ├── seatunnel-hadoop3-3.1.4-uber-2.3.2-optional.jar
│   ├── seatunnel-transforms-v2.jar
│   └── udf-1.0-SNAPSHOT.jar
├── licenses
│   ├── LICENSE-asm.txt
│   ├── LICENSE-avro.txt
│   ├── LICENSE-connons-math.txt
│   ├── LICENSE-javax-annootation-api.txt
│   ├── LICENSE-orc.txt
│   ├── LICENSE-parquet-format.txt
│   ├── LICENSE-parquet-mr.txt
│   ├── LICENSE-protobuf.txt
│   ├── LICENSE-scala.txt
│   ├── LICENSE-sjf4j.txt
│   ├── LICENSE-xz.txt
│   └── LICENSE-yetus.txt
├── mvnw
├── mvnw.cmd
├── plugins
│   └── README.md
└── starter
    ├── logging
    │   ├── jcl-over-slf4j-1.7.25.jar
    │   ├── log4j-api-2.17.1.jar
    │   ├── log4j-core-2.17.1.jar
    │   ├── log4j-slf4j-impl-2.17.1.jar
    │   └── slf4j-api-1.7.25.jar
    ├── seatunnel-flink-13-starter.jar
    ├── seatunnel-flink-15-starter.jar
    ├── seatunnel-spark-2-starter.jar
    ├── seatunnel-spark-3-starter.jar
    └── seatunnel-starter.jar
```




this is my udf lib pom file:
```xml
    <dependencies>
        <dependency>
            <groupId>org.apache.seatunnel</groupId>
            <artifactId>seatunnel-transforms-v2</artifactId>
            <version>2.3.2</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.seatunnel</groupId>
            <artifactId>seatunnel-api</artifactId>
            <version>2.3.2</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.google.auto.service</groupId>
            <artifactId>auto-service</artifactId>
            <version>1.0.1</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
```

**Comment by hustxjs** [comment]
> 

i need your java demo proj, can provide?

**Comment by hustxjs** [comment]
i need your java demo proj, can provide?  @liunaijie

**Comment by liunaijie** [comment]
can you share your demo project

**Comment by hustxjs** [comment]
> can you share your demo project

https://github.com/hustxjs/seatunnel-udf.git[https://github.com/hustxjs/seatunnel-udf.git](url)

**Comment by hustxjs** [comment]
> can you share your demo project

https://github.com/hustxjs/seatunnel-udf.git

**Comment by liunaijie** [comment]
why this project is base on sringboot? 
pls create an empty maven project and just import the dependency i mentioned. 
this project should only have 1 class if you don't have any other udf implement.

**Comment by hustxjs** [comment]
yes, u are right!
thank u!
