### ISSUE TITLE
[Feature][Jdbc] support duckdb

### ISSUE THREAD

**Issue by codering** [apache/seatunnel#5115]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

I put duckdb jdbc driver into `plugins/jdbc/lib`, and the batch config like this:
```
...
source {
  # This is a example source plugin **only for test and demonstrate the feature source plugin**
  Jdbc {
    url = "jdbc:duckdb:/Users/xxx/workplace/duckdb/seatunnel.db"
    driver = "org.duckdb.DuckDBDriver"
    connection_check_timeout_sec = 100
    user = ""
    password = ""
    query = "select name, age from demo limit 16"
  }

  # If you would like to get more information about how to configure Seatunnel and see full list of source plugins,
  # please go to https://seatunnel.apache.org/docs/category/source-v2
}

sink {
  console {

  }
}

```

then  run seatunnel with local
```sh
./bin/seatunnel.sh --config ./config/v2.batch.config.template -e local
```

Failed error meaage :
```
Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:188)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.connectors.seatunnel.jdbc.exception.JdbcConnectorException: ErrorCode:[JDBC-06], ErrorDescription:[No suitable dialect factory found] - Could not find any jdbc dialect factory that can handle url 'jdbc:duckdb:/Users/zhao/workplace/duckdb/seatunnel.db' that implements 'org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.JdbcDialectFactory' in the classpath.

Available factories are:

org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.db2.DB2DialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.dm.DmdbDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.gbase8a.Gbase8aDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.greenplum.GreenplumDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.mysql.MySqlDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.oracle.OracleDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.phoenix.PhoenixDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.psql.PostgresDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.redshift.RedshiftDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.saphana.SapHanaDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.snowflake.SnowflakeDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.sqlite.SqliteDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.sqlserver.SqlServerDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.tablestore.TablestoreDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.teradata.TeradataDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.vertica.VerticaDialectFactory
        at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.JdbcDialectLoader.load(JdbcDialectLoader.java:65)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.source.JdbcSource.prepare(JdbcSource.java:102)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSource(JobConfigParser.java:81)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:298)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:159)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.getLogicalDag(JobExecutionEnvironment.java:155)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:147)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:140)
        ... 2 more

```

### Usage Scenario

load mysql data to duckdb .

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
Is there anybody who'd like to implement this feature? Please leave a message and then submit a PR

**Comment by HaoXuAI** [comment]
@davidzollo I can take on this

**Comment by davidzollo** [comment]
@HaoXuAI  Please keep up the good work and complete the deltalake connector. Come on! Currently, I'm nearly done with duckdb.

**Comment by HuangZL-github** [comment]
你可以自己扩展在jdbc模块，和sqlite类似

**Comment by HuangZL-github** [comment]
You can extend it yourself in the jdbc module, similar to SQLite

**Comment by davidzollo** [comment]
I'm doing this feature

**Comment by HuangZL-github** [comment]
> I'm doing this feature

You have tested how to use Sqlite to specify database parameters and automatically generate sink sql. I have tested that the error has been reported. What should the database parameters be set in sqlite?

**Comment by davidzollo** [comment]
https://github.com/apache/seatunnel/pull/9659

**Comment by davidzollo** [comment]
> > I'm doing this feature
> 
> You have tested how to use Sqlite to specify database parameters and automatically generate sink sql. I have tested that the error has been reported. What should the database parameters be set in sqlite?

I didn't test Sqllite

**Comment by davidzollo** [comment]
https://github.com/apache/seatunnel/pull/10285

**Comment by chl-wxp** [comment]
https://github.com/apache/seatunnel/pull/10285 already merged, close this issue.
