### ISSUE TITLE
[Bug] [restore job] seatunnel 任务从保存点恢复时空指针

### ISSUE THREAD

**Issue by Xuzhengz** [apache/seatunnel#5122]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

seatunnel 任务从保存点恢复时空指针

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
env {
  execution.parallelism = 2
  job.mode = "STREAMING"
  checkpoint.interval = 2000
  #execution.checkpoint.interval = 10000
  #execution.checkpoint.data-uri = "hdfs://localhost:9000/checkpoint"
}

source {
  MySQL-CDC {
    result_table_name = "ods_test_data1_1min"
    parallelism = 1
    username = "mysql"
    password = "******"
    table-names = ["test1mysql.data3_1min"]
    base-url = "jdbc:mysql://172.16.11.131:3306/test1mysql"
  }
}

sink {
    Jdbc {
        url = "jdbc:postgresql://172.16.8.31:5432/cdc?currentSchema=mysqlcdc"
        driver = "org.postgresql.Driver"
        user = "superadmin"
        source_table_name = "ods_test_data1_1min"
        password = "******"
        database = "mysqlcdc"
        table = "ods_test_data1_1min"
        generate_sink_sql = true
        primary_keys = ["id"]
        batch_size = 5000
        support_upsert_by_query_primary_key_exist = true
        batch_interval_ms = 3000
        compatible_mode= "postgresLow"
    }
}
```

### Running Command

```shell
bin/seatunnel.sh -c job.conf
```

### Error Exception

```log
Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:194)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: java.lang.NullPointerException
        at sun.nio.fs.UnixPath.normalizeAndCheck(UnixPath.java:77)
        at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
        at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
        at java.nio.file.Paths.get(Paths.java:84)
        at org.apache.seatunnel.core.starter.utils.FileUtils.getConfigPath(FileUtils.java:50)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:127)
        ... 2 more
```

### Java or Scala Version

1.8

### Screenshots

<img width="1453" alt="image" src="https://github.com/apache/seatunnel/assets/90698333/3f808744-6902-4772-9ba1-e768426c50a6">

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Xuzhengz** [comment]
shell command： bin/seatunnel.sh -r  jobId

**Comment by liugddx** [comment]
> jobId

Refer to https://seatunnel.apache.org/docs/seatunnel-engine/savepoint#use-restore-with-savepoint

**Comment by Xuzhengz** [comment]
> > jobId
> 
> Refer to https://seatunnel.apache.org/docs/seatunnel-engine/savepoint#use-restore-with-savepoint

ok,thanks,resolved
