### ISSUE TITLE
[Bug] [SQL UDF] Using SQL UDF to prompt Unsupported function

### ISSUE THREAD

**Issue by luojinjiang2** [apache/seatunnel#5131]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I have read the documentation on the official website and developed according to the SQL UDF documentation, but there was an Unsupported function error during the runtime,SQL UDF's address is https://seatunnel.apache.org/docs/2.3.2/transform-v2/sql-udf.
my code:
```
@AutoService(ZetaUDF.class)
public class ExampleUDF implements ZetaUDF {
    @Override
    public String functionName() {
        return "EXAMPLE";
    }

    @Override
    public org.apache.seatunnel.api.table.type.SeaTunnelDataType<?> resultType(List<org.apache.seatunnel.api.table.type.SeaTunnelDataType<?>> list) {
        return BasicType.STRING_TYPE;
    }

    @Override
    public Object evaluate(List<Object> list) {
        String arg = (String) list.get(0);
        if (arg == null) {
            return null;
        }
        return "UDF: " + arg;
    }
}
```

Then I package it and put it in the lib directory

### SeaTunnel Version

dev分支

### SeaTunnel Config

```conf
mysql_to_doris_heartbeat:
{
    "env" : {
        "execution.parallelism" : 2,
        "job.mode" : "BATCH",
        "checkpoint.interval" : 10000
    },
    "source" : [
        {
            "password" : "xxxx",
            "driver" : "com.mysql.cj.jdbc.Driver",
            "query" : "SELECT * FROM t_device_heartbeat",
            "connection_check_timeout_sec" : 100,
            "result_table_name" : "table01",
            "plugin_name" : "Jdbc",
            "user" : "xxxxx",
            "url" : "jdbc:mysql://xxxxx?serverTimezone=GMT%2b8"
        }
    ],
    "transform" : [
        {
            "query" : "select id, EXAMPLE(ip) as city  from table01",
            "source_table_name" : "table01",
            "result_table_name" : "table01_1",
            "plugin_name" : "Sql"
        }
    ],
    "sink" : [
        {
            "password" : "xxxx",
            "fenodes" : "xxx:8030",
            "sink.enable-2pc" : "true",
            "doris.config" : {
                "format" : "json",
                "read_json_by_line" : "true"
            },
            "table.identifier" : "yst_manager.t_device_heartbeat",
            "source_table_name" : "table01_1",
            "plugin_name" : "Doris",
            "sink.label-prefix" : "test_json",
            "username" : "root"
        }
    ]
}
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/mysql_to_doris_heartbeat -e local
```

### Error Exception

```log
2023-07-21 10:11:41,713 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Fatal Error, 

2023-07-21 10:11:41,713 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Please submit bug report in https://github.com/apache/seatunnel/issues

2023-07-21 10:11:41,713 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Reason:SeaTunnel job executed failed 

2023-07-21 10:11:41,714 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:191)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.transform.exception.TransformException: ErrorCode:[COMMON-05], ErrorDescription:[Unsupported operation] - Unsupported function: EXAMPLE 
        at org.apache.seatunnel.transform.sql.zeta.ZetaSQLType.getFunctionType(ZetaSQLType.java:325)
        at org.apache.seatunnel.transform.sql.zeta.ZetaSQLType.getExpressionType(ZetaSQLType.java:94)
        at org.apache.seatunnel.transform.sql.zeta.ZetaSQLEngine.typeMapping(ZetaSQLEngine.java:197)
        at org.apache.seatunnel.transform.sql.SQLTransform.transformTableSchema(SQLTransform.java:143)
        at org.apache.seatunnel.transform.common.AbstractCatalogSupportTransform.transformCatalogTable(AbstractCatalogSupportTransform.java:56)
        at org.apache.seatunnel.transform.common.AbstractCatalogSupportTransform.getProducedCatalogTable(AbstractCatalogSupportTransform.java:46)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseTransform(MultipleTableJobConfigParser.java:444)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseTransforms(MultipleTableJobConfigParser.java:355)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:164)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.getLogicalDag(JobExecutionEnvironment.java:155)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:147)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:143)
        ... 2 more
```

### Java or Scala Version

java 1.8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Lifu12** [comment]
The official website provides a dev SQL UDF example

**Comment by luojinjiang2** [comment]
> The official website provides a dev SQL UDF example

I followed the documentation, but the above error occurred

**Comment by Lifu12** [comment]
![image](https://github.com/apache/seatunnel/assets/66303359/994f3adf-602e-44ca-b712-b4c6324bc9ac)
No problem

**Comment by luojinjiang2** [comment]
> ![image](https://user-images.githubusercontent.com/66303359/255080360-994f3adf-602e-44ca-b712-b4c6324bc9ac.png) No problem

Yes, I see,I need to configure services,Thank You very mach!
FYI: https://github.com/google/auto/tree/main/service
