### ISSUE TITLE
hive 同步 doris ，hive读取异常

### ISSUE THREAD

**Issue by HL2807** [apache/seatunnel#5140]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Caused by: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: org.apache.seatunnel.connectors.seatunnel.file.exception.FileConnectorException: ErrorCode:[COMMON-01], ErrorDescription:[File operation failed, such as (read,list,write,move,copy,sync) etc...] - Read data from this file [hdfs://HAservice1/hive/warehouse/tpch/ods/ods_lineitem_full/pt=1992/T_726614519014490113_9aa8d1e345_0_1_48.txt] failed
	at org.apache.seatunnel.connectors.seatunnel.file.source.BaseFileSourceReader.pollNext(BaseFileSourceReader.java:70)
	at org.apache.seatunnel.engine.server.task.flow.SourceFlowLifeCycle.collect(SourceFlowLifeCycle.java:135)
	at org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask.collect(SourceSeaTunnelTask.java:84)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTask.stateProcess(SeaTunnelTask.java:165)
	at org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask.call(SourceSeaTunnelTask.java:89)
	at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:613)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.time.format.DateTimeParseException: Text '1' could not be parsed at index 0
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
	at java.time.LocalDate.parse(LocalDate.java:400)
	at org.apache.seatunnel.common.utils.DateUtils.parse(DateUtils.java:40)
	at org.apache.seatunnel.format.text.TextDeserializationSchema.convert(TextDeserializationSchema.java:218)
	at org.apache.seatunnel.format.text.TextDeserializationSchema.deserialize(TextDeserializationSchema.java:120)
	at org.apache.seatunnel.format.text.TextDeserializationSchema.deserialize(TextDeserializationSchema.java:44)
	at org.apache.seatunnel.connectors.seatunnel.file.source.reader.TextReadStrategy.lambda$read$0(TextReadStrategy.java:73)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at org.apache.seatunnel.connectors.seatunnel.file.source.reader.TextReadStrategy.read(TextReadStrategy.java:69)
	at org.apache.seatunnel.connectors.seatunnel.file.source.BaseFileSourceReader.pollNext(BaseFileSourceReader.java:66)
	... 10 more

### SeaTunnel Version

2.3.2

### SeaTunnel Config

```conf
{
    "env" : {
        "execution.parallelism" : 12,
        "job.mode" : "BATCH"
    },
    "source" : [
        {
            "read_partitions" : [
                1992
            ],
            "delimiter" : "|",
            "metastore_uri" : "thrift://10.1x.x.x:9083",
            "plugin_name" : "hive",
            "table_name" : "tpch.ods_lineitem_full"
        }
    ],
    "transform" : [],
    "sink" : [
        {
            "password" : "xxx.",
            "fenodes" : "10.10.x.7:8030",
            "sink.enable-2pc" : "true",
            "doris.config" : {
                "format" : "json",
                "read_json_by_line" : "true"
            },
            "table.identifier" : "test.lineitem",
            "plugin_name" : "Doris",
            "sink.label-prefix" : "test_json",
            "username" : "root"
        }
    ]
}
```

### Running Command

```shell
./bin/seatunnel.sh --config ./jobs/htodoris.conf -e local
```

### Error Exception

```log
Caused by: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: org.apache.seatunnel.connectors.seatunnel.file.exception.FileConnectorException: ErrorCode:[COMMON-01], ErrorDescription:[File operation failed, such as (read,list,write,move,copy,sync) etc...] - Read data from this file [hdfs://HAservice1/hive/warehouse/tpch/ods/ods_lineitem_full/pt=1992/T_726614519014490113_9aa8d1e345_0_1_48.txt] failed
	at org.apache.seatunnel.connectors.seatunnel.file.source.BaseFileSourceReader.pollNext(BaseFileSourceReader.java:70)
	at org.apache.seatunnel.engine.server.task.flow.SourceFlowLifeCycle.collect(SourceFlowLifeCycle.java:135)
	at org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask.collect(SourceSeaTunnelTask.java:84)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTask.stateProcess(SeaTunnelTask.java:165)
	at org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask.call(SourceSeaTunnelTask.java:89)
	at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:613)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.time.format.DateTimeParseException: Text '1' could not be parsed at index 0
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
	at java.time.LocalDate.parse(LocalDate.java:400)
	at org.apache.seatunnel.common.utils.DateUtils.parse(DateUtils.java:40)
	at org.apache.seatunnel.format.text.TextDeserializationSchema.convert(TextDeserializationSchema.java:218)
	at org.apache.seatunnel.format.text.TextDeserializationSchema.deserialize(TextDeserializationSchema.java:120)
	at org.apache.seatunnel.format.text.TextDeserializationSchema.deserialize(TextDeserializationSchema.java:44)
	at org.apache.seatunnel.connectors.seatunnel.file.source.reader.TextReadStrategy.lambda$read$0(TextReadStrategy.java:73)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at org.apache.seatunnel.connectors.seatunnel.file.source.reader.TextReadStrategy.read(TextReadStrategy.java:69)
	at org.apache.seatunnel.connectors.seatunnel.file.source.BaseFileSourceReader.pollNext(BaseFileSourceReader.java:66)
	... 10 more
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by HL2807** [comment]
补充：hive版本是：2.1.1-cdh6.3.2

**Comment by Carl-Zhou-CN** [comment]
Could it be because of the delimiter?

**Comment by HL2807** [comment]
no！！！



***@***.***
 
发件人： Carl-Zhou-CN
发送时间： 2023-08-03 16:24
收件人： apache/seatunnel
抄送： lqs; Author
主题： Re: [apache/seatunnel] hive 同步 doris ，hive读取异常 (Issue #5140)
Could it be because of the delimiter?

**Comment by liugddx** [comment]
Can you post the schema and data of hive table? It seems that the parsing data is abnormal.

**Comment by codeDing18** [comment]
hi @HL2807 .I hava the same problem.How do you solve this problem.
