### ISSUE TITLE
[Bug] [Sink Bug] multiple Sink

### ISSUE THREAD

**Issue by Japson0** [apache/seatunnel#5329]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

```
env {

  job.mode = "BATCH"
}
source{
	Jdbc {
	    url = "jdbc:postgresql://***"
	    driver = "org.postgresql.Driver"
	    connection_check_timeout_sec = 10000
	    user = "****"
	    password = "****"
	    query = "SELECT * FROM kgp_data_dataset_file"
	    result_table_name= "temp_kgp_data_dataset_file"
	}
}
transform {
  Filter {
    source_table_name = "temp_kgp_data_dataset_file"
    result_table_name = "temp_kgp_data_dataset_file1"
    fields = [file_name, file_id]
  }
    FieldMapper {
      source_table_name = "temp_kgp_data_dataset_file1"
      result_table_name = "temp_kgp_data_dataset_file2"
      field_mapper = {
          file_id = file_id1
          file_name = file_name1
      }
    }
      Filter {
        source_table_name = "temp_kgp_data_dataset_file2"
        result_table_name = "temp_kgp_data_dataset_file3"
        fields = [file_name1]
      }
}

sink {
    jdbc {
	    url = "jdbc:postgresql://***"
	    driver = "org.postgresql.Driver"
	    user = "***"
	    password = "***"
	    source_table_name="temp_kgp_data_dataset_file2"
	    query = "insert into kgp_data_dataset_file1(file_name,file_id) values(?)"
	}
	jdbc {
    	    url = "jdbc:postgresql://****"
    	    driver = "org.postgresql.Driver"
    	    user = "****"
    	    password = "****"
    	    source_table_name="temp_kgp_data_dataset_file3"
    	    query = "insert into kgp_data_dataset_file2(file_name) values(?)"
    	}
}
```
I am running with the above configuration, assuming that the table temp_kgp_data_dataset_file has 22 entries, inserts into the second jdbc kgp_data_dataset_file2, and for the second insert uses the first jdbc configuration so that too many parameters are thrown

### SeaTunnel Version

2.3.2-release

### SeaTunnel Config

```conf
"quack-start" in docs
```

### Running Command

```shell
local mode
```

### Error Exception

```log
org.postgresql.util.PSQLException: 栏位索引超过许可范围：2，栏位数：1。
	at org.postgresql.core.v3.SimpleParameterList.bind(SimpleParameterList.java:70) ~[postgresql-42.4.3.jar:42.4.3]
	at org.postgresql.core.v3.SimpleParameterList.setStringParameter(SimpleParameterList.java:133) ~[postgresql-42.4.3.jar:42.4.3]
	at org.postgresql.jdbc.PgPreparedStatement.bindString(PgPreparedStatement.java:1099) ~[postgresql-42.4.3.jar:42.4.3]
	at org.postgresql.jdbc.PgPreparedStatement.setString(PgPreparedStatement.java:387) ~[postgresql-42.4.3.jar:42.4.3]
	at org.postgresql.jdbc.PgPreparedStatement.setString(PgPreparedStatement.java:373) ~[postgresql-42.4.3.jar:42.4.3]
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.executor.FieldNamedPreparedStatement.setString(FieldNamedPreparedStatement.java:125) ~[classes/:?]
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.converter.AbstractJdbcRowConverter.toExternal(AbstractJdbcRowConverter.java:130) ~[classes/:?]
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.executor.SimpleBatchStatementExecutor.addToBatch(SimpleBatchStatementExecutor.java:45) ~[classes/:?]
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.executor.SimpleBatchStatementExecutor.addToBatch(SimpleBatchStatementExecutor.java:31) ~[classes/:?]
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.executor.BufferedBatchStatementExecutor.executeBatch(BufferedBatchStatementExecutor.java:51) ~[classes/:?]
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.JdbcOutputFormat.attemptFlush(JdbcOutputFormat.java:165) ~[classes/:?]
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.JdbcOutputFormat.flush(JdbcOutputFormat.java:130) ~[classes/:?]
	at org.apache.seatunnel.connectors.seatunnel.jdbc.sink.JdbcSinkWriter.close(JdbcSinkWriter.java:108) ~[classes/:?]
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.close(SinkFlowLifeCycle.java:140) ~[classes/:?]
	at org.apache.seatunnel.engine.server.task.SeaTunnelTask.lambda$close$4(SeaTunnelTask.java:325) ~[classes/:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_202]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) [?:1.8.0_202]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) [?:1.8.0_202]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) [?:1.8.0_202]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) [?:1.8.0_202]
	at java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:289) [?:1.8.0_202]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java) [?:1.8.0_202]
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1870) [?:1.8.0_202]
	at java.util.concurrent.ForkJoinPool.externalHelpComplete(ForkJoinPool.java:2467) [?:1.8.0_202]
	at java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:324) [?:1.8.0_202]
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:405) [?:1.8.0_202]
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734) [?:1.8.0_202]
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160) [?:1.8.0_202]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174) [?:1.8.0_202]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) [?:1.8.0_202]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) [?:1.8.0_202]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583) [?:1.8.0_202]
	at org.apache.seatunnel.engine.server.task.SeaTunnelTask.close(SeaTunnelTask.java:322) [classes/:?]
	at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:629) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_202]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_202]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
2023-08-17 17:37:24,041 ERROR org.apache.seatunnel.engine.server.dag.physical.PhysicalVertex - Job pg2pg.conf (744489631080251393), Pipeline: [(1/1)], task: [pipeline-1 [Source[0]-Jdbc-temp_kgp_data_dataset_file]-SourceTask (1/1)], taskGroupLocation: [TaskGroupLocation{jobId=744489631080251393, pipelineId=1, taskGroupId=30000}] end with state FAILED and Exception: java.lang.RuntimeException: org.apache.seatunnel.connectors.seatunnel.jdbc.exception.JdbcConnectorException: ErrorCode:[COMMON-10], ErrorDescription:[Flush data operation that in sink connector failed]
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:232)
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:61)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:39)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:27)
	at org.apache.seatunnel.engine.server.task.group.queue.IntermediateBlockingQueue.handleRecord(IntermediateBlockingQueue.java:71)
	at org.apache.seatunnel.engine.server.task.group.queue.IntermediateBlockingQueue.collect(IntermediateBlockingQueue.java:51)
	at org.apache.seatunnel.engine.server.task.flow.IntermediateQueueFlowLifeCycle.collect(IntermediateQueueFlowLifeCycle.java:52)
	at org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask.collect(TransformSeaTunnelTask.java:73)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTask.stateProcess(SeaTunnelTask.java:168)
	at org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask.call(TransformSeaTunnelTask.java:78)
	at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:613)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.seatunnel.connectors.seatunnel.jdbc.exception.JdbcConnectorException: ErrorCode:[COMMON-10], ErrorDescription:[Flush data operation that in sink connector failed]
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.JdbcOutputFormat.flush(JdbcOutputFormat.java:136)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.sink.JdbcSinkWriter.prepareCommit(JdbcSinkWriter.java:88)
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:166)
	... 16 more
Caused by: org.postgresql.util.PSQLException: 栏位索引超过许可范围：2，栏位数：1。
	at org.postgresql.core.v3.SimpleParameterList.bind(SimpleParameterList.java:70)
	at org.postgresql.core.v3.SimpleParameterList.setStringParameter(SimpleParameterList.java:133)
	at org.postgresql.jdbc.PgPreparedStatement.bindString(PgPreparedStatement.java:1099)
	at org.postgresql.jdbc.PgPreparedStatement.setString(PgPreparedStatement.java:387)
	at org.postgresql.jdbc.PgPreparedStatement.setString(PgPreparedStatement.java:373)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.executor.FieldNamedPreparedStatement.setString(FieldNamedPreparedStatement.java:125)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.converter.AbstractJdbcRowConverter.toExternal(AbstractJdbcRowConverter.java:130)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.executor.SimpleBatchStatementExecutor.addToBatch(SimpleBatchStatementExecutor.java:45)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.executor.SimpleBatchStatementExecutor.addToBatch(SimpleBatchStatementExecutor.java:31)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.executor.BufferedBatchStatementExecutor.executeBatch(BufferedBatchStatementExecutor.java:51)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.JdbcOutputFormat.attemptFlush(JdbcOutputFormat.java:165)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.JdbcOutputFormat.flush(JdbcOutputFormat.java:130)
	... 18 more
```

### Zeta or Flink or Spark Version

Zata 2.3.2-release

### Java or Scala Version

8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Japson0** [comment]
Sorry,I misread.
