### ISSUE TITLE
[Bug] [Mysql CDC] seatunnel 基于 Flink 执行， source 指定mysql CDC ，无法加载到类

### ISSUE THREAD

**Issue by homjay666** [apache/seatunnel#5354]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

FLink 无法找到类

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
env {
  # You can set engine configuration here
  execution.parallelism = 1
  job.mode = "STREAMING"
  execution.checkpoint.interval = 5000
  #execution.checkpoint.data-uri = "hdfs://localhost:9000/checkpoint"
}

source {
  # This is a example source plugin **only for test and demonstrate the feature source plugin**
  MySQL-CDC {
    result_table_name = "fake"
    parallelism = 1
    server-id = 5656
    username = "root"
    password = "123456"
    table-names = "project_manager_mock.yt_tz_message"
    base-url = "jdbc:mysql:/localhost:3307/project_manager_mock"
  }
}

transform {
}

sink {
  console {
    source_table_name="fake"
  }
}
```

### Running Command

```shell
$SEATUNNEL_HOME/bin/start-seatunnel-flink-15-connector-v2.sh  \
    --name "seatunnel-ods_user_message" \
    --config $YT_PROJECT_REALTIME/ods_user_message_test.conf
```

### Error Exception

```log
2023-08-23 09:50:15
java.util.concurrent.ExecutionException: java.lang.RuntimeException: SourceSplitEnumerator run failed.
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.apache.seatunnel.translation.source.ParallelSource.run(ParallelSource.java:134)
	at org.apache.seatunnel.translation.flink.source.BaseSeaTunnelSourceFunction.run(BaseSeaTunnelSourceFunction.java:86)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:67)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:333)
Caused by: java.lang.RuntimeException: SourceSplitEnumerator run failed.
	at org.apache.seatunnel.translation.source.ParallelSource.lambda$run$0(ParallelSource.java:128)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Generate Splits for table project_manager_mock.yt_tz_message error
	at org.apache.seatunnel.connectors.cdc.base.source.enumerator.splitter.AbstractJdbcSourceChunkSplitter.generateSplits(AbstractJdbcSourceChunkSplitter.java:97)
	at org.apache.seatunnel.connectors.cdc.base.source.enumerator.SnapshotSplitAssigner.getNext(SnapshotSplitAssigner.java:165)
	at org.apache.seatunnel.connectors.cdc.base.source.enumerator.HybridSplitAssigner.getNext(HybridSplitAssigner.java:94)
	at org.apache.seatunnel.connectors.cdc.base.source.enumerator.IncrementalSourceEnumerator.assignSplits(IncrementalSourceEnumerator.java:160)
	at org.apache.seatunnel.connectors.cdc.base.source.enumerator.IncrementalSourceEnumerator.run(IncrementalSourceEnumerator.java:69)
	at org.apache.seatunnel.translation.source.ParallelSource.lambda$run$0(ParallelSource.java:126)
	... 6 more
Caused by: java.lang.IllegalArgumentException: Unable to find class org.apache.seatunnel.connectors.cdc.debezium.EmbeddedDatabaseHistory
	at io.debezium.config.Instantiator.getInstanceWithProvidedConstructorType(Instantiator.java:55)
	at io.debezium.config.Instantiator.getInstance(Instantiator.java:28)
	at io.debezium.config.Configuration.getInstance(Configuration.java:1465)
	at io.debezium.config.Configuration.getInstance(Configuration.java:1451)
	at io.debezium.relational.HistorizedRelationalDatabaseConnectorConfig.getDatabaseHistory(HistorizedRelationalDatabaseConnectorConfig.java:90)
	at io.debezium.relational.HistorizedRelationalDatabaseSchema.<init>(HistorizedRelationalDatabaseSchema.java:39)
	at io.debezium.connector.mysql.MySqlDatabaseSchema.<init>(MySqlDatabaseSchema.java:92)
	at org.apache.seatunnel.connectors.seatunnel.cdc.mysql.utils.MySqlConnectionUtils.createMySqlDatabaseSchema(MySqlConnectionUtils.java:67)
	at org.apache.seatunnel.connectors.seatunnel.cdc.mysql.utils.MySqlSchema.<init>(MySqlSchema.java:48)
	at org.apache.seatunnel.connectors.seatunnel.cdc.mysql.source.MySqlDialect.queryTableSchema(MySqlDialect.java:95)
	at org.apache.seatunnel.connectors.cdc.base.source.enumerator.splitter.AbstractJdbcSourceChunkSplitter.getSplitColumn(AbstractJdbcSourceChunkSplitter.java:362)
	at org.apache.seatunnel.connectors.cdc.base.source.enumerator.splitter.AbstractJdbcSourceChunkSplitter.generateSplits(AbstractJdbcSourceChunkSplitter.java:64)
	... 11 more
Caused by: java.lang.ClassNotFoundException: org.apache.seatunnel.connectors.cdc.debezium.EmbeddedDatabaseHistory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at io.debezium.config.Instantiator.getInstanceWithProvidedConstructorType(Instantiator.java:50)
	... 22 more
```

### Zeta or Flink or Spark Version

FLINK 1.16.1

### Java or Scala Version

JAVA 1.8

### Screenshots

opt/apps/seatunnel/connectors/seatunnel 

-rw-r--r-- 1 bigdata dev  29532610 8月  22 17:03 connector-cdc-mongodb-2.3.3.jar
-rw-r--r-- 1 bigdata dev  29508120 8月  22 17:03 connector-cdc-mysql-2.3.3.jar
-rw-r--r-- 1 bigdata dev  25871278 8月  22 17:11 connector-cdc-sqlserver-2.3.3.jar

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by homjay666** [comment]
Caused by: java.lang.RuntimeException: Generate Splits for table project_manager_mock.yt_tz_message error
