### ISSUE TITLE
[Bug] [Jdbc] how to use DataSaveMode

### ISSUE THREAD

**Issue by samgang** [apache/seatunnel#5366]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

it does not run well when i use [fake to mysql](https://seatunnel.apache.org/docs/2.3.3/connector-v2/sink/Mysql) .

the info 
```
Exception in thread "main" java.lang.AbstractMethodError: Method org/apache/seatunnel/connectors/seatunnel/jdbc/sink/JdbcSink.getUserConfigSaveMode()Lorg/apache/seatunnel/api/sink/DataSaveMode; is abstract
```
How to operate it，thanks.

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
  job.mode = "BATCH"
}

source {
  FakeSource {
    parallelism = 1
    result_table_name = "fake"
    row.num = 16
    schema = {
      fields {
        name = "string"
        age = "int"
      }
    }
  }
}

transform {
}

sink {
    jdbc {
        url = "jdbc:mysql://localhost:3306/test"
        driver = "com.mysql.cj.jdbc.Driver"
        user = "root"
        password = "123456"
        query = "insert into test_table(name,age) values(?,?)"
        }
}
```
```


### Running Command

```shell
$SEATUNNEL_HOME/bin/seatunnel.sh --config fake2mysql.conf -m local
```

### Error Exception

```log
org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand - Closed HazelcastInstance ......
Exception in thread "main" java.lang.AbstractMethodError: Method org/apache/seatunnel/connectors/seatunnel/jdbc/sink/JdbcSink.getUserConfigSaveMode()Lorg/apache/seatunnel/api/sink/DataSaveMode; is abstract
        at org.apache.seatunnel.connectors.seatunnel.jdbc.sink.JdbcSink.getUserConfigSaveMode(JdbcSink.java)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.handleSaveMode(MultipleTableJobConfigParser.java:640)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.createSinkAction(MultipleTableJobConfigParser.java:631)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSink(MultipleTableJobConfigParser.java:576)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:190)
        at org.apache.seatunnel.engine.core.job.AbstractJobEnvironment.getLogicalDag(AbstractJobEnvironment.java:109)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:73)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:143)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Japson0** [comment]
It happened to me too！

**Comment by samgang** [comment]
yes

**Comment by ArtistRuan** [comment]
me too!!how to solve it ?

**Comment by misi1987107** [comment]
Issue Cannot Reproduce
