### ISSUE TITLE
[Bug] [connector-kudu]  Column (name: rid, index: 0) is of type string but was requested as a type [Type: int32]

### ISSUE THREAD

**Issue by zzzhiyu** [apache/seatunnel#5375]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

execute kudu source:java.lang.IllegalArgumentException: Column (name: rid, index: 0) is of type string but was requested as a type [Type: int32]
![image](https://github.com/apache/seatunnel/assets/28888024/9abd4cc1-158f-4391-9a49-2b76f93afcf2)
![image](https://github.com/apache/seatunnel/assets/28888024/b938ece7-796c-475d-b3f5-4276741af0a5)

### SeaTunnel Version

version: 2.3.3

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
  job.mode="BATCH"
}

source {
  kudu {
    kudu_master="xxxxxxx:7051,xxxxx:7051,xxxxxx:7051"
    kudu_table="test01"  The pk column of table test01 is of type string
    columnsList="column1,column2"
  }
}

sink {
  console {

  }
}
```

### Running Command

```shell
seatunnel.sh --config kudu_test.config -e local
```

### Error Exception

```log
2023-08-25 14:15:50,778 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:191)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: java.lang.IllegalArgumentException: Column (name: rid, index: 0) is of type string but was requested as a type [Type: int32]
	at org.apache.kudu.client.RowResult.checkType(RowResult.java:679)
	at org.apache.kudu.client.RowResult.getInt(RowResult.java:135)
	at org.apache.kudu.client.RowResult.getInt(RowResult.java:121)
	at org.apache.seatunnel.connectors.seatunnel.kudu.source.KuduSource.initPartitionParameter(KuduSource.java:175)
	at org.apache.seatunnel.connectors.seatunnel.kudu.source.KuduSource.prepare(KuduSource.java:142)
	at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSource(JobConfigParser.java:85)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:317)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:179)
	at org.apache.seatunnel.engine.core.job.AbstractJobEnvironment.getLogicalDag(AbstractJobEnvironment.java:109)
	at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:73)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:143)
	... 2 more
 
2023-08-25 14:15:50,778 ERROR org.apache.seatunnel.core.starter.SeaTunnel -
```

### Java or Scala Version

java version "11.0.17" 2022-10-18 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.17+10-LTS-269)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.17+10-LTS-269, mixed mode)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhilinli123** [comment]
If convenient please provide your table DDL and I will try to fix it

**Comment by zzzhiyu** [comment]
CREATE TABLE ods2.xgamezh_cdb_rolerename (
  uuid STRING NOT NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION COMMENT 'uuid',
  byconfirm STRING NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION COMMENT '',
  dwroleid STRING NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION COMMENT '',
  dwtime STRING NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION COMMENT '',
  sznewname STRING NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION COMMENT '',
  szoldname STRING NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION COMMENT '',
  loadtime STRING NULL ENCODING AUTO_ENCODING COMPRESSION DEFAULT_COMPRESSION COMMENT '',
  PRIMARY KEY (uuid)
)
PARTITION BY HASH (uuid) PARTITIONS 3
STORED AS KUDU
TBLPROPERTIES ('kudu.master_addresses'='xxxxxxxxxxxxxxxxx', 'kudu.num_tablet_replicas'='1')

**Comment by zzzhiyu** [comment]
> If convenient please provide your table DDL and I will try to fix it

Is this a bug? Or it's already been solved. If not, can I participate in modifying part of the code (modifying the code of splite part)?

**Comment by zhilinli123** [comment]
> > If convenient please provide your table DDL and I will try to fix it
> 
> Is this a bug? Or it's already been solved. If not, can I participate in modifying part of the code (modifying the code of splite part)?

Looking forward to your contribution

**Comment by HoganEdwardChu** [comment]
Is this task done? Or not a bug?
Thanks you
@Hisoka-X
