### ISSUE TITLE
[Bug] [connector-file-s3] Timeout waiting for connection from pool

### ISSUE THREAD

**Issue by lizhitao0923** [apache/seatunnel#5408]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I use connector-file-s3 as the source to read data from S3. After several days of continuous running, the offline scheduled task encounters an error 'Timeout waiting for connection from pool'.

### SeaTunnel Version

seatunnel-2.3.2

### SeaTunnel Config

```conf
source {

  S3File {
    path = "/XXXXXX"
    bucket = "s3a://XXXXX"
    fs.s3a.endpoint = "XXX.XXXXX"
    access_key = "XXXX"
    secret_key = "XXX"
    fs.s3a.aws.credentials.provider = "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
    file_format_type = "orc"
    hadoop_s3_properties {
      fs.s3a.connection.maximum = 256
    }
  }

}

-----------------------------------------------
seatunnel:
  engine:
    backup-count: 1
    queue-type: blockingqueue
    print-execution-info-interval: 30
    print-job-metrics-info-interval: 60
    slot-service:
      dynamic-slot: true
    checkpoint:
      interval: 120000
      timeout: 120000
      max-concurrent: 1
      tolerable-failure: 2
      storage:
        type: hdfs
        max-retained: 3
        plugin-config:
            storage.type: s3
            s3.bucket: s3a://XXXX
            fs.s3a.endpoint: xxxx
            fs.s3a.access.key: XXXX
            fs.s3a.secret.key: XXX
            fs.s3a.aws.credentials.provider: org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
            fs.s3a.connection.maximum: 256
```

### Running Command

```shell
sh ${workDir}/seatunnel.sh --config $SCRIPT_FILE -m cluster
```

### Error Exception

```log
2023-08-31 06:12:42,255 ERROR org.apache.seatunnel.core.starter.SeaTunnel - 
	
	===============================================================================
	
	
	2023-08-31 06:12:42,255 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Fatal Error, 
	
	2023-08-31 06:12:42,255 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Please submit bug report in https://github.com/apache/seatunnel/issues
	
	2023-08-31 06:12:42,256 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Reason:SeaTunnel job executed failed 
	
	2023-08-31 06:12:42,257 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
		at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:188)
		at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
		at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
	Caused by: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: org.apache.seatunnel.connectors.seatunnel.file.exception.FileConnectorException: ErrorCode:[COMMON-01], ErrorDescription:[File operation failed, such as (read,list,write,move,copy,sync) etc...] - Read data from this file [s3a://XXXX/ylz_dim.db/dim_pub_truck_tenant/dt=2023-08-30/000000_0] failed
		at org.apache.seatunnel.connectors.seatunnel.file.source.BaseFileSourceReader.pollNext(BaseFileSourceReader.java:70)
		at org.apache.seatunnel.engine.server.task.flow.SourceFlowLifeCycle.collect(SourceFlowLifeCycle.java:135)
		at org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask.collect(SourceSeaTunnelTask.java:84)
		at org.apache.seatunnel.engine.server.task.SeaTunnelTask.stateProcess(SeaTunnelTask.java:165)
		at org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask.call(SourceSeaTunnelTask.java:89)
		at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:613)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:750)
	Caused by: org.apache.seatunnel.connectors.seatunnel.file.exception.FileConnectorException: ErrorCode:[FILE-01], ErrorDescription:[File type is invalid] - Check orc file [s3a://XXXXX/ylz_dim.db/dim_pub_truck_tenant/dt=2023-08-30/000000_0] failed
		at org.apache.seatunnel.connectors.seatunnel.file.source.reader.OrcReadStrategy.checkFileType(OrcReadStrategy.java:204)
		at org.apache.seatunnel.connectors.seatunnel.file.source.reader.OrcReadStrategy.read(OrcReadStrategy.java:79)
		at org.apache.seatunnel.connectors.seatunnel.file.source.BaseFileSourceReader.pollNext(BaseFileSourceReader.java:66)
		... 10 more
	Caused by: java.io.InterruptedIOException: getFileStatus on s3a://XXXXX/ylz_dim.db/dim_pub_truck_tenant/dt=2023-08-30/000000_0: com.amazonaws.SdkClientException: Unable to execute HTTP request: Timeout waiting for connection from pool
		at org.apache.hadoop.fs.s3a.S3AUtils.translateInterruptedException(S3AUtils.java:352)
		at org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:177)
		at org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:151)
		at org.apache.hadoop.fs.s3a.S3AFileSystem.s3GetFileStatus(S3AFileSystem.java:2242)
		at org.apache.hadoop.fs.s3a.S3AFileSystem.innerGetFileStatus(S3AFileSystem.java:2204)
		at org.apache.hadoop.fs.s3a.S3AFileSystem.getFileStatus(S3AFileSystem.java:2143)
		at org.apache.hadoop.fs.s3a.S3AFileSystem.open(S3AFileSystem.java:716)
		at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:899)
		at org.apache.seatunnel.connectors.seatunnel.file.source.reader.OrcReadStrategy.checkFileType(OrcReadStrategy.java:173)
		... 12 more
	Caused by: com.amazonaws.SdkClientException: Unable to execute HTTP request: Timeout waiting for connection from pool
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1216)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1162)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:811)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:779)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:753)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:713)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:695)
		at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:559)
		at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:539)
		at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5437)
		at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5384)
		at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1367)
		at org.apache.hadoop.fs.s3a.S3AFileSystem.lambda$getObjectMetadata$4(S3AFileSystem.java:1290)
		at org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:322)
		at org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:285)
		at org.apache.hadoop.fs.s3a.S3AFileSystem.getObjectMetadata(S3AFileSystem.java:1287)
		at org.apache.hadoop.fs.s3a.S3AFileSystem.s3GetFileStatus(S3AFileSystem.java:2224)
		... 17 more
	Caused by: com.amazonaws.thirdparty.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
		at com.amazonaws.thirdparty.apache.http.impl.conn.PoolingHttpClientConnectionManager.leaseConnection(PoolingHttpClientConnectionManager.java:314)
		at com.amazonaws.thirdparty.apache.http.impl.conn.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:280)
		at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at com.amazonaws.http.conn.ClientConnectionRequestFactory$Handler.invoke(ClientConnectionRequestFactory.java:70)
		at com.amazonaws.http.conn.$Proxy36.get(Unknown Source)
		at com.amazonaws.thirdparty.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:190)
		at com.amazonaws.thirdparty.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
		at com.amazonaws.thirdparty.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
		at com.amazonaws.thirdparty.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
		at com.amazonaws.thirdparty.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
		at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1343)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1154)
		... 32 more
	
		at org.apache.seatunnel.engine.client.job.ClientJobProxy.waitForJobComplete(ClientJobProxy.java:122)
		at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:181)
		... 2 more
	 
	2023-08-31 06:12:42,257 ERROR org.apache.seatunnel.core.starter.SeaTunnel - 
	===============================================================================
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CallMeKingsley97** [comment]
😂Brother Jian, good to see you

**Comment by hailin0** [comment]
Does anyone want to claim it?
