### ISSUE TITLE
[Bug] [mongodb source] mongodb source JsonUtils.parseObject error

### ISSUE THREAD

**Issue by zck573693104** [apache/seatunnel#5413]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

mongodb source -> console print

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
# Set the basic configuration of the task to be performed
env {
  execution.parallelism = 1
  job.mode = "BATCH"
}

# Create a source to connect to Mongodb
source {
  MongoDB {
    uri = "mongodb://user:password@ip:port?authSource=admin"
    database = "ecp-alarm-test"
    collection = "common_alarm_log"
    schema = {
      fields {
        _id = string
        alarm_code = string
        alarm_count = int
        alarm_first_time = Date
        alarm_level = string
        alarm_name = string
        alarm_status = int
        alarm_type = int
        connector_id = string
        equipment_id = string
        recovery_condition = string
        solution = string
        station_id = string
        trigger_condition = string
        operator_id = string
        operator_name = string
        station_name = string
        busine_type = int
        manufacturer_name = string
        recovery_time = Date
       
        }
      }
    }
  }


# Console printing of the read Mongodb data
sink {
  Console {
    parallelism = 1
  }
}
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/v2.batch.config -e local
```

### Error Exception

```log
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.seatunnel.common.utils.JsonUtils.parseObject(Ljava/lang/String;)Lcom/fasterxml/jackson/databind/node/ObjectNode;
	at org.apache.seatunnel.connectors.seatunnel.common.schema.SeaTunnelSchema.convertJsonToMap(SeaTunnelSchema.java:218)
	at org.apache.seatunnel.connectors.seatunnel.common.schema.SeaTunnelSchema.convertConfigToMap(SeaTunnelSchema.java:214)
	at org.apache.seatunnel.connectors.seatunnel.common.schema.SeaTunnelSchema.buildWithConfig(SeaTunnelSchema.java:255)
	at org.apache.seatunnel.connectors.seatunnel.mongodb.source.MongodbSource.prepare(MongodbSource.java:71)
	at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSource(JobConfigParser.java:85)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:317)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:179)
	at org.apache.seatunnel.engine.core.job.AbstractJobEnvironment.getLogicalDag(AbstractJobEnvironment.java:109)
	at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:73)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:143)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by TyrantLucifer** [comment]
@MonsterChenzhuo PTAL.

**Comment by zck573693104** [comment]
> @MonsterChenzhuo PTAL.

May I ask when the modification will be completed and submitted

**Comment by Zhouwen-CN** [comment]
I tested without any issues
I think it's due to the environment
Your version seems incorrect
`ConvertJsonToMap`,`convertConfigToMap`,`buildWithConfig`, these three methods are now in the `CatalogTableUtil` class

**Comment by zck573693104** [comment]
use 2.3.0 mongodb jar,use 2.3.3 is ok.
The jar package version is incorrect。
