### ISSUE TITLE
[Bug] [connector-rocketmq-2.3.3] RemotingTimeoutException: invokeSync call the addr[null] timeout

### ISSUE THREAD

**Issue by lmntnb** [apache/seatunnel#5436]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

连接rocketmq拉数报错，rocketmq版本尝试过4.9.3，4.9.4，5.1.3都无法解决

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
env {
  # You can set SeaTunnel environment configuration here
  execution.parallelism = 2
  job.mode = "BATCH"
  checkpoint.interval = 10000
  #execution.checkpoint.interval = 10000
  #execution.checkpoint.data-uri = "hdfs://localhost:9000/checkpoint"
}

source {
  # This is a example source plugin **only for test and demonstrate the feature source plugin**
  Rocketmq {
	name.srv.addr = "172.22.26.216:9876"
	topics = "MilesightTopic"
	consumer.group = "milesight-consumer-group"
	parallelism = 1
	batch.size = 20
	start.mode = "CONSUME_FROM_LAST_OFFSET"
	start.mode.offsets = {
	  MilesightTopic = 20
	}
  }

  # If you would like to get more information about how to configure SeaTunnel and see full list of source plugins,
  # please go to https://seatunnel.apache.org/docs/category/source-v2
}

sink {
  Console {
  }
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/mqtt.batch.config -m local
```

### Error Exception

```log
2023-09-06 16:34:22,936 INFO  com.hazelcast.instance.impl.Node - [localhost]:5801 [seatunnel-307813] [5.1] Shutting down connection manager...
2023-09-06 16:34:22,940 INFO  com.hazelcast.instance.impl.Node - [localhost]:5801 [seatunnel-307813] [5.1] Shutting down node engine...
2023-09-06 16:34:22,967 INFO  org.apache.seatunnel.engine.server.SeaTunnelServer - master node check interrupted
2023-09-06 16:34:22,967 INFO  org.apache.seatunnel.engine.server.CoordinatorService - [localhost]:5801 [seatunnel-307813] [5.1] This node become leave active master node, begin clear coordinator service
2023-09-06 16:34:22,988 INFO  com.hazelcast.instance.impl.NodeExtension - [localhost]:5801 [seatunnel-307813] [5.1] Destroying node NodeExtension.
2023-09-06 16:34:22,989 INFO  com.hazelcast.instance.impl.Node - [localhost]:5801 [seatunnel-307813] [5.1] Hazelcast Shutdown is completed in 63 ms.
2023-09-06 16:34:22,989 INFO  com.hazelcast.core.LifecycleService - [localhost]:5801 [seatunnel-307813] [5.1] [localhost]:5801 is SHUTDOWN
2023-09-06 16:34:22,989 INFO  org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand - Closed HazelcastInstance ......
2023-09-06 16:34:22,990 INFO  org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand - Closed metrics executor service ......
2023-09-06 16:34:22,990 ERROR org.apache.seatunnel.core.starter.SeaTunnel - 

===============================================================================


2023-09-06 16:34:22,990 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Fatal Error, 

2023-09-06 16:34:22,990 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Please submit bug report in https://github.com/apache/seatunnel/issues

2023-09-06 16:34:22,990 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Reason:SeaTunnel job executed failed 

2023-09-06 16:34:22,992 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:191)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: org.apache.seatunnel.connectors.seatunnel.rocketmq.exception.RocketMqConnectorException: ErrorCode:[ROCKETMQ-11], ErrorDescription:[Failed to get topic min and max topic]
	at org.apache.seatunnel.connectors.seatunnel.rocketmq.common.RocketMqAdminUtil.offsetTopics(RocketMqAdminUtil.java:231)
	at org.apache.seatunnel.connectors.seatunnel.rocketmq.source.RocketMqSourceSplitEnumerator.getTopicInfo(RocketMqSourceSplitEnumerator.java:211)
	at org.apache.seatunnel.connectors.seatunnel.rocketmq.source.RocketMqSourceSplitEnumerator.fetchPendingPartitionSplit(RocketMqSourceSplitEnumerator.java:197)
	at org.apache.seatunnel.connectors.seatunnel.rocketmq.source.RocketMqSourceSplitEnumerator.run(RocketMqSourceSplitEnumerator.java:119)
	at org.apache.seatunnel.engine.server.task.SourceSplitEnumeratorTask.stateProcess(SourceSplitEnumeratorTask.java:303)
	at org.apache.seatunnel.engine.server.task.SourceSplitEnumeratorTask.call(SourceSplitEnumeratorTask.java:134)
	at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:613)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.apache.rocketmq.remoting.exception.RemotingTimeoutException: invokeSync call the addr[null] timeout
	at org.apache.rocketmq.remoting.netty.NettyRemotingClient.invokeSync(NettyRemotingClient.java:388)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:1394)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:1384)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.examineTopicRouteInfo(DefaultMQAdminExtImpl.java:339)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.examineTopicStats(DefaultMQAdminExtImpl.java:260)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExt.examineTopicStats(DefaultMQAdminExt.java:226)
	at org.apache.seatunnel.connectors.seatunnel.rocketmq.common.RocketMqAdminUtil.offsetTopics(RocketMqAdminUtil.java:223)
	... 11 more

	at org.apache.seatunnel.engine.client.job.ClientJobProxy.waitForJobComplete(ClientJobProxy.java:122)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:184)
	... 2 more
 
2023-09-06 16:34:22,993 ERROR org.apache.seatunnel.core.starter.SeaTunnel - 
===============================================================================



Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:191)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: org.apache.seatunnel.connectors.seatunnel.rocketmq.exception.RocketMqConnectorException: ErrorCode:[ROCKETMQ-11], ErrorDescription:[Failed to get topic min and max topic]
	at org.apache.seatunnel.connectors.seatunnel.rocketmq.common.RocketMqAdminUtil.offsetTopics(RocketMqAdminUtil.java:231)
	at org.apache.seatunnel.connectors.seatunnel.rocketmq.source.RocketMqSourceSplitEnumerator.getTopicInfo(RocketMqSourceSplitEnumerator.java:211)
	at org.apache.seatunnel.connectors.seatunnel.rocketmq.source.RocketMqSourceSplitEnumerator.fetchPendingPartitionSplit(RocketMqSourceSplitEnumerator.java:197)
	at org.apache.seatunnel.connectors.seatunnel.rocketmq.source.RocketMqSourceSplitEnumerator.run(RocketMqSourceSplitEnumerator.java:119)
	at org.apache.seatunnel.engine.server.task.SourceSplitEnumeratorTask.stateProcess(SourceSplitEnumeratorTask.java:303)
	at org.apache.seatunnel.engine.server.task.SourceSplitEnumeratorTask.call(SourceSplitEnumeratorTask.java:134)
	at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:613)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.apache.rocketmq.remoting.exception.RemotingTimeoutException: invokeSync call the addr[null] timeout
	at org.apache.rocketmq.remoting.netty.NettyRemotingClient.invokeSync(NettyRemotingClient.java:388)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:1394)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:1384)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.examineTopicRouteInfo(DefaultMQAdminExtImpl.java:339)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.examineTopicStats(DefaultMQAdminExtImpl.java:260)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExt.examineTopicStats(DefaultMQAdminExt.java:226)
	at org.apache.seatunnel.connectors.seatunnel.rocketmq.common.RocketMqAdminUtil.offsetTopics(RocketMqAdminUtil.java:223)
	... 11 more

	at org.apache.seatunnel.engine.client.job.ClientJobProxy.waitForJobComplete(ClientJobProxy.java:122)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:184)
	... 2 more
2023-09-06 16:34:25,815 INFO  org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand - run shutdown hook because get close signal
```

### Zeta or Flink or Spark Version

zeta

### Java or Scala Version

jdk1.8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CallMeKingsley97** [comment]
It seems like RocketMQ can't be connected, check the network between the seatunnel and RocketMQ

**Comment by lmntnb** [comment]
> It seems like RocketMQ can't be connected, check the network between the seatunnel and RocketMQ

网络没有问题，seatunnel 同一台服务器还部署了其他业务应用，应用正常访问RocketMQ

**Comment by CallMeKingsley97** [comment]
> > It seems like RocketMQ can't be connected, check the network between the seatunnel and RocketMQ
> 
> 网络没有问题，seatunnel 同一台服务器还部署了其他业务应用，应用正常访问RocketMQ

I don't have a Rockemq service and cannot reproduce it. You can run seatunnel locally by idea with your config file  and take a look

**Comment by hailin0** [comment]
@sunxiaojian hello can you help him

**Comment by jackyyyyyssss** [comment]
@hailin0  please assign me

**Comment by jackyyyyyssss** [comment]
![image](https://github.com/apache/seatunnel/assets/127465317/6b79905c-dd45-4ade-a5e1-d22b8f366d72)
  I used your configuration to connect to Rocketmq and it seems that it is possible. However, your error stack did not read the address of the nameserver. You can try modifying your configuration to try again @lmntnb
