### ISSUE TITLE
[Bug] [Module Name] Caused by: java.io.InvalidClassException: org.apache.seatunnel.api.table.catalog.PhysicalColumn

### ISSUE THREAD

**Issue by ClamJohn** [apache/seatunnel#5444]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Caused by: java.util.concurrent.CompletionException: com.hazelcast.nio.serialization.HazelcastSerializationException: java.io.InvalidClassException: org.apache.seatunnel.api.table.catalog.PhysicalColumn; local class incompatible: stream classdesc serialVersionUID = -2391929401738236418, local class serialVersionUID = -1833990926984508516

we update seatunnel version 2.3.2 to 2.3.3 ,then get this exception，

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
seatunnel:
  engine:
    backup-count: 1
    queue-type: blockingqueue
    print-execution-info-interval: 60
    print-job-metrics-info-interval: 60
    slot-service:
      dynamic-slot: true
    checkpoint:
      interval: 10000
      timeout: 60000
      max-concurrent: 1
      tolerable-failure: 2
      storage:
        type: hdfs
        max-retained: 3
        plugin-config:
          namespace: /tmp/seatunnel/checkpoint_snapshot
          storage.type: hdfs
          fs.defaultFS: hdfs://10.1.2.106:8020 # Ensure that the directory has written permission
```

### Running Command

```shell
"env" : {
	        "execution.parallelism" : 10,
	        "job.mode" : "BATCH",
	        "job.name" : "ads.ads_doc_inc_sms_d",
	        "checkpoint.interval" : 60000
	    },
	    "source" : [
	        {
	            "password" : "xxx",
	            "driver" : "com.mysql.cj.jdbc.Driver",
	            "query" : " select doctor_id from ads.ads_doc_inc_sms_d",
	            "connection_check_timeout_sec" : 100,
	            "fetch_size" : 10000,
	            "partition_column" : "doctor_id",
	            "plugin_name" : "Jdbc",
	            "user" : "ads",
	            "url" : "jdbc:mysql://xxx:3306?serverTimezone=GMT%2b8",
	            "partition_num" : 10
	        }
	    ],
	    "transform" : [],
	    "sink" : [
	        {
	            "password" : "xxx",
	            "database" : "ads",
	            "primary_keys" : [
	                "doctor_id"
	            ],
	            "batch_size" : 10000,
	            "driver" : "com.mysql.cj.jdbc.Driver",
	            "max_retries" : 1,
	            "connection_check_timeout_sec" : 100,
	            "generate_sink_sql" : true,
	            "plugin_name" : "Jdbc",
	            "user" : "DolphinScheduler",
	            "url" : "jdbc:mysql://xxx:3306?serverTimezone=GMT%2b8&rewriteBatchedStatements=true",
	            "table" : "ads_doc_inc_sms_d"
	        }
	    ]
	}
```

### Error Exception

```log
Caused by: java.io.InvalidClassException: org.apache.seatunnel.api.table.catalog.PhysicalColumn; local class incompatible: stream classdesc serialVersionUID = -2391929401738236418, local class serialVersionUID = -1833990926984508516
		at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:699)
		at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1885)
		at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1751)
		at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2042)
		at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
		at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
		at java.util.ArrayList.readObject(ArrayList.java:797)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1170)
		at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2178)
		at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
		at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
		at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
		at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
		at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
		at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
		at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
		at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
		at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
		at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
		at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
		at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
		at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
		at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
		at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
		at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
		at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
		at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
		at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
		at com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:92)
		at com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:85)
		at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
		at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:349)
		... 22 more
	Run SeaTunnel Application error return 200
```

### Java or Scala Version

1.8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dingyan2394** [comment]
I also have this  problem

**Comment by dingyan2394** [comment]
I had solved this problem ,the reason： the job still use 2.3.2 seatunnel，but the cluster had upgrade to 2.3.3.  check the log like this   :
Sep 11,  PM com.hazelcast.internal.config.AbstractConfigLocator
INFO: Loading configuration '/opt/apache-seatunnel-2.3.2/config/seatunnel.yaml' from System property 'seatunnel.config'

**Comment by EricJoy2048** [comment]
> I had solved this problem ,the reason： the job still use 2.3.2 seatunnel，but the cluster had upgrade to 2.3.3. check the log like this : Sep 11, PM com.hazelcast.internal.config.AbstractConfigLocator INFO: Loading configuration '/opt/apache-seatunnel-2.3.2/config/seatunnel.yaml' from System property 'seatunnel.config'

Yes, you are right.
