### ISSUE TITLE
[Bug] [mongodb-cdc] seatunnel-2.3.3 [Unsupported operation] - Unable to convert to <STRING> from nullable value null

### ISSUE THREAD

**Issue by xhh0168** [apache/seatunnel#5471]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Caused by: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: org.apache.seatunnel.connectors.seatunnel.cdc.mongodb.exception.MongodbConnectorException: ErrorCode:[COMMON-05], ErrorDescription:[Unsupported operation] - Unable to convert to <STRING> from nullable value null

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
seatunnel:
  engine:
    history-job-expire-minutes: 1440
    backup-count: 1
    queue-type: blockingqueue
    print-execution-info-interval: 60
    print-job-metrics-info-interval: 60
    slot-service:
      dynamic-slot: true
    checkpoint:
      interval: 10000
      timeout: 600000
      storage:
        type: hdfs
        max-retained: 3
        plugin-config:
          namespace: /tmp/seatunnel/checkpoint_snapshot
          storage.type: hdfs
          fs.defaultFS: file:///tmp/ # Ensure that the directory has written permission
```

### Running Command

```shell
seatunnel.sh -c job.conf
```

### Error Exception

```log
ERROR org.apache.seatunnel.core.starter.SeaTunnel - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:191)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: org.apache.seatunnel.connectors.seatunnel.cdc.mongodb.exception.MongodbConnectorException: ErrorCode:[COMMON-05], ErrorDescription:[Unsupported operation] - Unable to convert to <STRING> from nullable value null
        at org.apache.seatunnel.connectors.seatunnel.cdc.mongodb.sender.MongoDBConnectorDeserializationSchema$2.apply(MongoDBConnectorDeserializationSchema.java:193)
        at org.apache.seatunnel.connectors.seatunnel.cdc.mongodb.sender.MongoDBConnectorDeserializationSchema$2.apply(MongoDBConnectorDeserializationSchema.java:187)
        at org.apache.seatunnel.connectors.seatunnel.cdc.mongodb.sender.MongoDBConnectorDeserializationSchema$13.apply(MongoDBConnectorDeserializationSchema.java:371)
        at org.apache.seatunnel.connectors.seatunnel.cdc.mongodb.sender.MongoDBConnectorDeserializationSchema$13.apply(MongoDBConnectorDeserializationSchema.java:352)
        at org.apache.seatunnel.connectors.seatunnel.cdc.mongodb.sender.MongoDBConnectorDeserializationSchema$2.apply(MongoDBConnectorDeserializationSchema.java:197)
        at org.apache.seatunnel.connectors.seatunnel.cdc.mongodb.sender.MongoDBConnectorDeserializationSchema$2.apply(MongoDBConnectorDeserializationSchema.java:187)
        at org.apache.seatunnel.connectors.seatunnel.cdc.mongodb.sender.MongoDBConnectorDeserializationSchema$1.convert(MongoDBConnectorDeserializationSchema.java:175)
        at org.apache.seatunnel.connectors.seatunnel.cdc.mongodb.sender.MongoDBConnectorDeserializationSchema.extractRowData(MongoDBConnectorDeserializationSchema.java:155)
        at org.apache.seatunnel.connectors.seatunnel.cdc.mongodb.sender.MongoDBConnectorDeserializationSchema.deserialize(MongoDBConnectorDeserializationSchema.java:99)
        at org.apache.seatunnel.connectors.cdc.base.source.reader.IncrementalSourceRecordEmitter.emitElement(IncrementalSourceRecordEmitter.java:155)
        at org.apache.seatunnel.connectors.cdc.base.source.reader.IncrementalSourceRecordEmitter.processElement(IncrementalSourceRecordEmitter.java:132)
        at org.apache.seatunnel.connectors.cdc.base.source.reader.IncrementalSourceRecordEmitter.emitRecord(IncrementalSourceRecordEmitter.java:89)
        at org.apache.seatunnel.connectors.cdc.base.source.reader.IncrementalSourceRecordEmitter.emitRecord(IncrementalSourceRecordEmitter.java:55)
        at org.apache.seatunnel.connectors.seatunnel.common.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:108)
        at org.apache.seatunnel.connectors.cdc.base.source.reader.IncrementalSourceReader.pollNext(IncrementalSourceReader.java:98)
        at org.apache.seatunnel.engine.server.task.flow.SourceFlowLifeCycle.collect(SourceFlowLifeCycle.java:150)
        at org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask.collect(SourceSeaTunnelTask.java:95)
        at org.apache.seatunnel.engine.server.task.SeaTunnelTask.stateProcess(SeaTunnelTask.java:168)
        at org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask.call(SourceSeaTunnelTask.java:100)
        at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:613)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

        at org.apache.seatunnel.engine.client.job.ClientJobProxy.waitForJobComplete(ClientJobProxy.java:122)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:184)
        ... 2 more
```

### Zeta or Flink or Spark Version

zeta

### Java or Scala Version

openjdk version "1.8.0_372"

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xhh0168** [comment]
allow.null = true    this parameter does not take effect. How to solve？

**Comment by Carl-Zhou-CN** [comment]
> allow.null = true this parameter does not take effect. How to solve？

What is the parameter? Can you provide the source

**Comment by xhh0168** [comment]
> > allow.null = true this parameter does not take effect. How to solve？
> 
> What is the parameter? Can you provide the source

See the parameter in this reply

https://github.com/apache/seatunnel/pull/4972/files/5514928cc4aab3e2031dcb43c593f87677a6e43d#diff-0373bc329ca47400f03abf6766ac649d1e649947a7b189fe77c9c69cc9aa4213

**Comment by Carl-Zhou-CN** [comment]
> > > allow.null = true this parameter does not take effect. How to solve？
> > 
> > 
> > What is the parameter? Can you provide the source
> 
> See the parameter in this reply
> 
> https://github.com/apache/seatunnel/pull/4972/files/5514928cc4aab3e2031dcb43c593f87677a6e43d#diff-0373bc329ca47400f03abf6766ac649d1e649947a7b189fe77c9c69cc9aa4213

#4972 It is not merged, you need to wait for it to merge, if you need to try ahead, you need to compile and pull the corresponding branch compilation

**Comment by xhh0168** [comment]
> > > > allow.null = true this parameter does not take effect. How to solve？
> > > 
> > > 
> > > What is the parameter? Can you provide the source
> > 
> > 
> > See the parameter in this reply
> > https:github.com/apache/seatunnel/pull/4972/files/5514928cc4aab3e2031dcb43c593f87677a6e43d#diff-0373bc329ca47400f03abf6766ac649d1e649947a7b189fe77c9c69cc9aa4213
> 
> #4972 It is not merged, you need to wait for it to merge, if you need to try ahead, you need to compile and pull the corresponding branch compilation

thanks , try later.   

Another error message


 ERROR org.apache.seatunnel.connectors.seatunnel.common.source.reader.fetcher.SplitFetcherManager - Received uncaught exception.
java.lang.RuntimeException: SplitFetcher thread 0 received unexpected exception while polling the records
        at org.apache.seatunnel.connectors.seatunnel.common.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:165) ~[?:?]
        at org.apache.seatunnel.connectors.seatunnel.common.source.reader.fetcher.SplitFetcher.run(SplitFetcher.java:81) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_372]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_372]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_372]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_372]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_372]
Caused by: java.lang.NullPointerException
        at org.apache.seatunnel.connectors.seatunnel.cdc.mongodb.source.fetch.MongodbFetchTaskContext.isRecordBetween(MongodbFetchTaskContext.java:156) ~[?:?]
        at org.apache.seatunnel.connectors.cdc.base.source.reader.external.IncrementalSourceScanFetcher.isChangeRecordInChunkRange(IncrementalSourceScanFetcher.java:227) ~[?:?]
        at org.apache.seatunnel.connectors.cdc.base.source.reader.external.IncrementalSourceScanFetcher.pollSplitRecords(IncrementalSourceScanFetcher.java:158) ~[?:?]
        at org.apache.seatunnel.connectors.cdc.base.source.reader.IncrementalSourceSplitReader.fetch(IncrementalSourceSplitReader.java:75) ~[?:?]
        at org.apache.seatunnel.connectors.seatunnel.common.source.reader.fetcher.FetchTask.run(FetchTask.java:54) ~[?:?]
        at org.apache.seatunnel.connectors.seatunnel.common.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:162) ~[?:?]
        ... 6 more

**Comment by Carl-Zhou-CN** [comment]
@xhh0168 Can you share the config of your mission?

**Comment by bulolo** [comment]
any process?

**Comment by bulolo** [comment]
i think it should open again
