### ISSUE TITLE
[Bug] [Phoenix] Phoenix2doirs-batch

### ISSUE THREAD

**Issue by zq0757** [apache/seatunnel#5472]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Phoenix Failed to synchronize data in batches from hbase to doirs

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
"env" : {
        "job.name" : "hbase2doris-batch",
        "job.mode" : "BATCH"
    },
    "source" : [
        {
            "driver" : "org.apache.phoenix.queryserver.client.Driver",
            "query" : "select * from us_population",
            "plugin_name" : "Jdbc",
            "url" : "jdbc:phoenix:thin:url=http://spark_e2e_phoenix_sink:8765;serialization=PROTOBUF"
        }
    ],
    "sink" : [
        {
            "password" : "pwd",
            "fenodes" : "ip:18030",
            "sink.enable-2pc" : "true",
            "doris.config" : {
                "format" : "json",
                "read_json_by_line" : "true"
            },
            "table.identifier" : "test_kafka.us_population",
            "plugin_name" : "Doris",
            "sink.label-prefix" : "test_json",
            "username" : "root"
        }
    ]
}
```

### Running Command

```shell
$SEATUNNEL_HOME/bin/seatunnel.sh --config $SEATUNNEL_HOME/config/v2.batch.config-01.template
```

### Error Exception

```log
2023-09-13 15:19:26,828 INFO  org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand - Closed SeaTunnel client......
2023-09-13 15:19:26,828 ERROR org.apache.seatunnel.core.starter.SeaTunnel - 

===============================================================================


2023-09-13 15:19:26,828 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Fatal Error, 

2023-09-13 15:19:26,828 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Please submit bug report in https://github.com/apache/seatunnel/issues

2023-09-13 15:19:26,828 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Reason:SeaTunnel job executed failed 

2023-09-13 15:19:26,830 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:191)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.api.common.PrepareFailException: ErrorCode:[API-01], ErrorDescription:[Configuration item validate failed] - PluginName: jdbc, PluginType: source, Message: java.lang.RuntimeException: java.lang.IllegalStateException: retries (7) exceeded maximum allowed (6)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.source.JdbcSource.prepare(JdbcSource.java:112)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSource(JobConfigParser.java:85)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:317)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:179)
        at org.apache.seatunnel.engine.core.job.AbstractJobEnvironment.getLogicalDag(AbstractJobEnvironment.java:109)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:73)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:143)
        ... 2 more
 
2023-09-13 15:19:26,830 ERROR org.apache.seatunnel.core.starter.SeaTunnel - 
===============================================================================



Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:191)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.api.common.PrepareFailException: ErrorCode:[API-01], ErrorDescription:[Configuration item validate failed] - PluginName: jdbc, PluginType: source, Message: java.lang.RuntimeException: java.lang.IllegalStateException: retries (7) exceeded maximum allowed (6)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.source.JdbcSource.prepare(JdbcSource.java:112)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSource(JobConfigParser.java:85)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:317)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:179)
        at org.apache.seatunnel.engine.core.job.AbstractJobEnvironment.getLogicalDag(AbstractJobEnvironment.java:109)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:73)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:143)
        ... 2 more
```

### Zeta or Flink or Spark Version

Zeta

### Java or Scala Version

jdk8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Zhouwen-CN** [comment]
I tested it and it's okay
The lowercase table name of phoenix needs to be enclosed in double quotes
You try again
```
env {
  execution.parallelism = 1
  job.mode = "BATCH"
}

source {
  Jdbc {
      result_table_name = "t1"
      driver = org.apache.phoenix.queryserver.client.Driver
      url = "jdbc:phoenix:thin:url=http://localhost:8765;serialization=PROTOBUF"
      query = "select * from \"test\""
  }
}

transform {
}

sink {
  Console {
    source_table_name = "t1"
  }
}
```

**Comment by zq0757** [comment]
Try your same configuration, the error is the same

**Comment by zq0757** [comment]
![image](https://github.com/apache/seatunnel/assets/27143080/60891c5e-5f68-416c-a361-a9187854fe69)

**Comment by zq0757** [comment]
![image](https://github.com/apache/seatunnel/assets/27143080/68571129-0b9a-4a24-9434-57dc62064dcc)

**Comment by zq0757** [comment]
Using the driver: "driver", "org. Apache. Phoenix. JDBC. PhoenixDriver" test, not reported as errors

**Comment by Zhouwen-CN** [comment]
Is it possible that you did not start the `queryserver` for `phoenix`
`Jdbc source` will obtain connections during the preparation phase
If `queryserver` is not started, it is not possible to connect with `thin`

**Comment by zq0757** [comment]
Possibly, the query server was not enabled during the test

**Comment by zq0757** [comment]
When the hbase table data is read by phoenix and doris is written, all field names are converted to uppercase
![image](https://github.com/apache/seatunnel/assets/27143080/2610708a-f624-4957-9c77-94872ec9a79f)

**Comment by Zhouwen-CN** [comment]
`Phoenix` When creating a table, although it is in lowercase
But it will be resolved to uppercase unless enclosed in double quotes
You can log in to the `phoenix client`
Use command to view
```shell
!describe table_name
```
If the table name is lowercase, it should also be enclosed in double quotes

**Comment by zq0757** [comment]
60 million data volumes are synchronized, and the ckp timeout period is set to 1 hour
![image](https://github.com/apache/seatunnel/assets/27143080/28b64103-d00e-4c99-98da-403fbd02e98b)

**Comment by zq0757** [comment]
Task monitoring data
![1695627936343](https://github.com/apache/seatunnel/assets/27143080/b0fc1b75-357d-4e77-92a9-86b79b263dd3)
