### ISSUE TITLE
[Bug] [connector-file-sftp] run on flink cannot assign instance of java.lang.invoke.SerializedLambda

### ISSUE THREAD

**Issue by aokunsang** [apache/seatunnel#5473]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Submitting via the command line is fine，the command is :
`
bin/start-seatunnel-flink-15-connector-v2.sh --config config/test.conf
`
，but Failed to submit the task using java code。

### SeaTunnel Version

2.3.2

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
  job.mode = "BATCH"
}

source {
  FakeSource {
    parallelism = 1
    result_table_name = "fake"
    row.num = 20
    schema = {
      fields {
        name = "string"
        age = "int"
        card = "int"
      }
    }
  }

}

transform { }

sink {
  SftpFile {
    host = "xxx.xx.x.x"
    port = 22
    user = "root"
    password = "root"
    path = "/opt/bigdata/upload"
    file_format_type = "excel"
    custom_filename = true
    file_name_expression = "test_${now}"
    filename_time_format = "yyyy_MM_dd"
    is_enable_transaction = false
    max_rows_in_memory = 500
    sink_columns = ["name", "age", "card"]
  }
}
```

### Running Command

```shell
push job to flink1.15.4 from javacode.
```

### Error Exception

```log
Caused by: org.apache.flink.streaming.runtime.tasks.StreamTaskException: Cannot instantiate user function.
	at org.apache.flink.streaming.api.graph.StreamConfig.getStreamOperatorFactory(StreamConfig.java:340)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.<init>(OperatorChain.java:158)
	at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.<init>(RegularOperatorChain.java:60)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreInternal(StreamTask.java:658)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restore(StreamTask.java:646)
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:948)
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:917)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:741)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:563)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: cannot assign instance of java.lang.invoke.SerializedLambda to field org.apache.flink.streaming.api.connector.sink2.GlobalCommitterOperator.committableSerializerFactory of type org.apache.flink.util.function.SerializableSupplier in instance of org.apache.flink.streaming.api.connector.sink2.GlobalCommitterOperator
	at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2287)
	at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1417)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2293)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:617)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:602)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:589)
	at org.apache.flink.util.InstantiationUtil.readObjectFromConfig(InstantiationUtil.java:543)
	at org.apache.flink.streaming.api.graph.StreamConfig.getStreamOperatorFactory(StreamConfig.java:324)
	... 9 more
```

### Zeta or Flink or Spark Version

flink1.15.4

### Java or Scala Version

java1.8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ruanwenjun** [comment]
Could you please provide sample code, how you submit the job by code.

**Comment by aokunsang** [comment]
1、structure PackageJarJob object

PackageJarJob packageJarJob = new PackageJarJob();  
Path starterJarPath = SeaTunnelKit.getStarterJarPath(seatunnelHomePath);  
packageJarJob.setJarFilePath(starterJarPath.toFile().toURI().toString());  
packageJarJob.setEntryPointClass(SeaTunnelKit.SEATUNNEL_MAIN_CLASS);  
packageJarJob.setProgramArgs(new String[] { "--config", configPath.toString() });  
Set<URL> jars = new HashSet<>();  
jars.add(configPath.toUri().toURL());  
.... other dependent jars
ConfigUtils.encodeCollectionToConfig(configuration, PipelineOptions.JARS, jars, Object::toString);

2、structure JobGraph object and submit flink

RestClusterClient<StandaloneClusterId> client = new RestClusterClient<>(configuration,StandaloneClusterId.getInstance());  
PackagedProgram program = FlinkKit.buildProgram(configuration, job);
JobGraph jobGraph = PackagedProgramUtils.createJobGraph(program, configuration, job.getParallelism(), false);
JobID jobID = client.submitJob(jobGraph).get();

**Comment by ruanwenjun** [comment]
> 1、structure PackageJarJob object
> 
> PackageJarJob packageJarJob = new PackageJarJob(); Path starterJarPath = SeaTunnelKit.getStarterJarPath(seatunnelHomePath); packageJarJob.setJarFilePath(starterJarPath.toFile().toURI().toString()); packageJarJob.setEntryPointClass(SeaTunnelKit.SEATUNNEL_MAIN_CLASS); packageJarJob.setProgramArgs(new String[] { "--config", configPath.toString() }); Set jars = new HashSet<>(); jars.add(configPath.toUri().toURL()); .... other dependent jars ConfigUtils.encodeCollectionToConfig(configuration, PipelineOptions.JARS, jars, Object::toString);
> 
> 2、structure JobGraph object and submit flink
> 
> RestClusterClient client = new RestClusterClient<>(configuration,StandaloneClusterId.getInstance()); PackagedProgram program = FlinkKit.buildProgram(configuration, job); JobGraph jobGraph = PackagedProgramUtils.createJobGraph(program, configuration, job.getParallelism(), false); JobID jobID = client.submitJob(jobGraph).get();

I am not sure if this is the correct way to use seatunnel jar. @Hisoka-X

**Comment by aokunsang** [comment]
> > 1、structure PackageJarJob object
> > PackageJarJob packageJarJob = new PackageJarJob(); Path starterJarPath = SeaTunnelKit.getStarterJarPath(seatunnelHomePath); packageJarJob.setJarFilePath(starterJarPath.toFile().toURI().toString()); packageJarJob.setEntryPointClass(SeaTunnelKit.SEATUNNEL_MAIN_CLASS); packageJarJob.setProgramArgs(new String[] { "--config", configPath.toString() }); Set jars = new HashSet<>(); jars.add(configPath.toUri().toURL()); .... other dependent jars ConfigUtils.encodeCollectionToConfig(configuration, PipelineOptions.JARS, jars, Object::toString);
> > 2、structure JobGraph object and submit flink
> > RestClusterClient client = new RestClusterClient<>(configuration,StandaloneClusterId.getInstance()); PackagedProgram program = FlinkKit.buildProgram(configuration, job); JobGraph jobGraph = PackagedProgramUtils.createJobGraph(program, configuration, job.getParallelism(), false); JobID jobID = client.submitJob(jobGraph).get();
> 
> I am not sure if this is the correct way to use seatunnel jar. @Hisoka-X

I use other sources/transforms/sinks all right， only this sink[connector-file-sftp] is fail。 but, the source[connector-file-sftp] is ok， so, I'm surprised.

**Comment by aokunsang** [comment]
This may involve the content of flink, but I do not have a deep understanding of the core of flink. Could you please give me some opinions
