### ISSUE TITLE
[Bug] [rest-api]/hazelcast/rest/maps/submit-job java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by luzongzhu** [apache/seatunnel#5474]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

执行 /hazelcast/rest/maps/submit-job 日志报错空指针，这里的sink iceberg是我自己从issue下载的源码调整了后重新打了一个connector的jar包上传到2.3.3的，使用 -local 执行是可以执行成功的。

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
{
    "env": {
        "execution.parallelism": 2,
        "job.mode": "BATCH"
    },
    "source": [
        {
            "url": "jdbc:oracle:thin:@******:1521/WFLDBDEV",
            "driver": "oracle.jdbc.OracleDriver",
            "user": "biods", 
            "password": "biods2020",
            "query": "SELECT  MANDT, EBELN, EBELP, ZEKKN, LOEKZ, AEDAT, KFLAG, MENGE, VPROZ, NETWR, SAKTO, GSBER, KOSTL, PROJN, VBELN, VBELP, VETEN, KZBRB, ANLN1, ANLN2, AUFNR, WEMPF, ABLAD, KOKRS, XBKST, XBAUF, XBPRO, EREKZ, KSTRG, PAOBJNR, PRCTR, PS_PSP_PNR, NPLNR, AUFPL, IMKEY, APLZL, VPTNR, FIPOS, RECID, ZZFZH, ZZPTH, ZZICP, ZZBRAN1, FISTL, GEBER, FKBER, DABRZ, AUFPL_ORD, APLZL_ORD, MWSKZ, TXJCD, NAVNW, KBLNR, KBLPOS, LSTAR, PRZNR, GRANT_NBR, BUDGET_PD, FM_SPLIT_BATCH, FM_SPLIT_BEGRU, AA_FINAL_IND, AA_FINAL_REASON, AA_FINAL_QTY, EGRUP, VNAME, TCOBJNR, DATEOFSERVICE, NOTAXCORR, DIFFOPTRATE, HASDIFFOPTRATE, FMFGUS_KEY, AA_FINAL_QTY_F, MENGE_F,'2023-09-09 13:53:00' AS fdop_import_time FROM BIODS.EKKN"
        }
    ],
    "sink": [
        {
            "catalog_name": "iceberg",
            "catalog_type": "hive",
            "uri": "thrift://*****:9083",
            "warehouse": "/user/hive/warehouse",
            "namespace": "ods",
            "table": "EKKN"
        }
    ]
}
```

### Running Command

```shell
/hazelcast/rest/maps/submit-job
```

### Error Exception

```log
2023-09-13 16:11:38,620 WARN  org.apache.seatunnel.engine.server.log.Log4j2HttpPostCommandProcessor - [ddp2]:5801 [seatunnel] [5.1] An error occurred while handling request HttpCommand [HTTP_POST]{uri='/hazelcast/rest/maps/submit-job?jobId=1234&jobName=testJob&isStartWithSavePoint=false'}AbstractTextCommand[HTTP_POST]{requestId=0}
java.lang.NullPointerException: null
        at org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery.findPluginJarPath(AbstractPluginDiscovery.java:341) ~[seatunnel-starter.jar:2.3.3]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[?:1.8.0_221]
        at org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery.getPluginJarPath(AbstractPluginDiscovery.java:319) ~[seatunnel-starter.jar:2.3.3]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_221]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_221]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_221]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_221]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_221]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_221]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_221]
        at org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery.getPluginJarPaths(AbstractPluginDiscovery.java:131) ~[seatunnel-starter.jar:2.3.3]
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.getConnectorJarList(MultipleTableJobConfigParser.java:227) ~[seatunnel-starter.jar:2.3.3]
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:160) ~[seatunnel-starter.jar:2.3.3]
        at org.apache.seatunnel.engine.core.job.AbstractJobEnvironment.getLogicalDag(AbstractJobEnvironment.java:109) ~[seatunnel-starter.jar:2.3.3]
        at org.apache.seatunnel.engine.server.job.JobImmutableInformationEnv.build(JobImmutableInformationEnv.java:76) ~[seatunnel-starter.jar:2.3.3]
        at org.apache.seatunnel.engine.server.rest.RestHttpPostCommandProcessor.handleSubmitJob(RestHttpPostCommandProcessor.java:112) ~[seatunnel-starter.jar:2.3.3]
        at org.apache.seatunnel.engine.server.rest.RestHttpPostCommandProcessor.handle(RestHttpPostCommandProcessor.java:68) ~[seatunnel-starter.jar:2.3.3]
        at org.apache.seatunnel.engine.server.rest.RestHttpPostCommandProcessor.handle(RestHttpPostCommandProcessor.java:47) ~[seatunnel-starter.jar:2.3.3]
        at com.hazelcast.internal.ascii.TextCommandServiceImpl$CommandExecutor.run(TextCommandServiceImpl.java:402) ~[seatunnel-starter.jar:2.3.3]
        at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217) ~[seatunnel-starter.jar:2.3.3]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_221]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[seatunnel-starter.jar:2.3.3]
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[seatunnel-starter.jar:2.3.3]
2023-09-13 16:12:07,487 INFO  org.apache.seatunnel.engine.server.CoordinatorService - [ddp2]:5801 [seatunnel] [5.1]
```

### Java or Scala Version

1.8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by luzongzhu** [comment]
@zhibinF 大佬可以帮忙看下吗?

**Comment by zhibinF** [comment]
> @zhibinF 大佬可以帮忙看下吗?

Let me check.

**Comment by zhibinF** [comment]
Would you like to give more logs about this job run, it looks like it's about PluginJarPaths. Could you provide a log of successful local runs and a log of failed restAPI.

**Comment by luzongzhu** [comment]
@zhibinF 首先非常感谢你这么晚还能回复我的问题，
rest-api.log 是我执行调用的时候后台打的日志内容，就只看到这么些内容。
seatunnel-cluster.log 是使用执行 $SEATUNNEL_HOME/bin/seatunnel.sh --config $SEATUNNEL_HOME/config/v2.batch.config.template 启动打印的日志，是成功的。 
[seatunnel-cluster.log](https://github.com/apache/seatunnel/files/12599484/seatunnel-cluster.log)
[rest-api.log](https://github.com/apache/seatunnel/files/12599485/rest-api.log)

**Comment by ruanwenjun** [comment]
@luzongzhu Have you put your plugin under `/opt/apache-seatunnel-2.3.3/connectors/seatunnel`

the exception occur in line 341 this is strange, is there any other exception?


<img width="1002" alt="image" src="https://github.com/apache/seatunnel/assets/22415594/c2d0116d-c748-4d63-9258-6e1df2ea6cc4">

**Comment by zhibinF** [comment]
Really need more information, because in ST 2.3.3 version 341 lines is 
**final String pluginName = pluginIdentifier. GetPluginName () toLowerCase ();**
But it works in local mode. In the future I also plan to print message like Parsed config file in local to restAPI logs.

**Comment by luzongzhu** [comment]
> 确实需要更多信息，因为在 ST 2.3.3 版本中，第 341 行是 **Final StringpluginName =pluginIdentifier。GetPluginName() toLowerCase(); ** 但它在本地模式下工作。将来我还计划将本地解析配置文件之类的消息打印到restAPI日志中。

@zhibinF 那会是因为我是在postman中直接访问的restapi接口的原因吗？我直接访问的是某一台节点上的5801端口，然后调用的 /hazelcast/rest/maps/submit-job接口。
@ruanwenjun /opt/apache-seatunnel-2.3.3/connectors/seatunnel下是有这些包的，因为我使用命令执行是可以成功执行的，并没有任何异常，具体内容也在日志里面了，如果需要补充其他什么信息我可以提供。

**Comment by zhibinF** [comment]
I also am testing with the postman, found no problem, all of your server deployment/opt/apache - seatunnel - 2.3.3 / connectors/seatunnel is consistent? What is line 341 in your code that gives an error.

**Comment by luzongzhu** [comment]
> I also am testing with the postman, found no problem, all of your server deployment/opt/apache - seatunnel - 2.3.3 / connectors/seatunnel is consistent? What is line 341 in your code that gives an error.

@zhibinF 服务端用的代码就是我们2.3.3的发行版，我只是做了connector的改动，但是我觉得这跟我使用什么connector没有太大关系，因为我使用文档给的DEMO去请求 /hazelcast/rest/maps/submit-job 也是同样的错误。
{
    "env": {
        "job.mode": "batch"
    },
    "source": [
        {
            "plugin_name": "FakeSource",
            "result_table_name": "fake",
            "row.num": 100,
            "schema": {
                "fields": {
                    "name": "string",
                    "age": "int",
                    "card": "int"
                }
            }
        }
    ],
    "transform": [
    ],
    "sink": [
        {
            "plugin_name": "Console",
            "source_table_name": ["fake"]
        }
    ]
}

**Comment by zhibinF** [comment]
Could you add this code to MultipleTableJobConfigParser.java line 143, then check at the log.
log.info("Parsed config file: {}", seaTunnelJobConfig.root().render(ConfigBuilder.CONFIG_RENDER_OPTIONS)); 
![image](https://github.com/apache/seatunnel/assets/56808812/5b40a3e6-547e-481a-a2be-ec720ccfe7b1)
