### ISSUE TITLE
Cannot read a specific partition data in hive

### ISSUE THREAD

**Issue by liushuaihang** [apache/seatunnel#5484]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

配置文件应该没有问题，但是跑不通

### SeaTunnel Version

seatunnel版本2.3.3
hive版本2.3.9

### SeaTunnel Config

```conf
source {
    Hive {
table_name = "default.test3"
metastore_uri = "thrift://xxx:9083"
hdfs_site_path = "/home/hadoop/hadoop-3.2.2/etc/hadoop/hdfs-site.xml"
hive_site_path = "/home/hadoop/hive-2.3.9/conf/hive-site.xml"
read_partitions = ["dt=2023-09-13"]
    }
}
```

### Running Command

```shell
./bin/seatunnel.sh --config config/hive_partition_test.config -e local
```

### Error Exception

```log
Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:191)
at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.connectors.seatunnel.file.exception.FileConnectorException: ErrorCode:[FILE-04], ErrorDescript
ion:[File list is empty] - The target file list is empty,SeaTunnel will not be able to sync empty table, please check the conf
iguration parameters such as: [file_filter_pattern]
at org.apache.seatunnel.connectors.seatunnel.file.source.reader.AbstractReadStrategy.getFileNamesByPath(AbstractReadSt
rategy.java:158)
at org.apache.seatunnel.connectors.seatunnel.file.source.reader.AbstractReadStrategy.getFileNamesByPath(AbstractReadSt
rategy.java:133)
at org.apache.seatunnel.connectors.seatunnel.file.hdfs.source.BaseHdfsFileSource.prepare(BaseHdfsFileSource.java:76)
at org.apache.seatunnel.connectors.seatunnel.hive.source.HiveSource.prepare(HiveSource.java:176)
at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSource(JobConfigParser.java:85)
at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:3
17)
at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:179)
at org.apache.seatunnel.engine.core.job.AbstractJobEnvironment.getLogicalDag(AbstractJobEnvironment.java:109)
at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:73)
at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:143)
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liushuaihang** [comment]
hive的dt是string类型

**Comment by ruanwenjun** [comment]
Could you please check if your table exist and hive config is correct.

**Comment by liunaijie** [comment]
this is an issue, if some path,subpath doesn't have any file will get this error.
fixed at https://github.com/apache/seatunnel/pull/5427

**Comment by liunaijie** [comment]
@liushuaihang  you can use seatunnel 2.3.2.

**Comment by ruanwenjun** [comment]
I closed this issue if there is no more thing.

**Comment by liushuaihang** [comment]
Hi，关于这个BUG，同样的配置，seatunnel2.3.3不能跑成功，seatunnel2.3.1可以跑成功

**Comment by liushuaihang** [comment]
> @liushuaihang you can use seatunnel 2.3.2.

Hi，关于这个BUG，同样的配置，seatunnel2.3.3不能跑成功，seatunnel2.3.1可以跑成功

**Comment by liunaijie** [comment]
> > @liushuaihang you can use seatunnel 2.3.2.
> 
> Hi，关于这个BUG，同样的配置，seatunnel2.3.3不能跑成功，seatunnel2.3.1可以跑成功

Yes, as i said, this bug was introduced in 2.3.3, and will be fix in next version. So you need use another version.
