### ISSUE TITLE
[Request query Plan failed] - query failed with empty response

### ISSUE THREAD

**Issue by zexin5** [apache/seatunnel#5520]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

使用starrocks source connector获取不到查询计划，starrocks版本是3.0.5

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
env {
    job.mode="BATCH"
    job.name="SeaTunnel_Job"
    checkpoint.interval=10000
}
source {
  StarRocks {
    nodeUrls = ["xxx.xxx.xxx.xxx:8030"]
    username = xxxx
    password = "xxxx"
    database = "test"
    table = "log_task"
    request_tablet_size = 5
    scan_batch_rows = 500000
    max_retries = 3
    schema {
        fields {
            role_id = BIGINT
            channel_id = BIGINT
            task_id = BIGINT
            game_id = BIGINT
            sf_id = BIGINT
            topic = STRING
            partition = BIGINT
            offset = BIGINT
            kafka_timestamp = TIMESTAMP
            update_time = TIMESTAMP
            delete_time = TIMESTAMP
        }
    }
  }
}
transform {

}
sink {
    LocalFile {
        path = "/opt/data/seatunnel/demo"
        file_format_type = "parquet"
        sink_columns = ["`role_id`","`channel_id`","`task_id`","`game_id`","`sf_id`","`topic`","`partition`","`offset`","`kafka_timestamp`","`update_time`","`delete_time`"]
        compress_codec = lz4
    }
}
```

### Running Command

```shell
./bin/seatunnel.sh --config /opt/job/seatunnel/demo/sr_to_local_file.config -e local
```

### Error Exception

```log
2023-09-19 15:58:01,092 INFO  org.apache.seatunnel.engine.server.task.SourceSplitEnumeratorTask - received enough reader, starting enumerator...
2023-09-19 15:58:01,095 INFO  org.apache.seatunnel.connectors.seatunnel.starrocks.client.HttpHelper - Executing POST from http://xxx.xxx.xxx.28:8030/api/test/log_task/_query_plan.
2023-09-19 15:58:01,159 WARN  org.apache.seatunnel.connectors.seatunnel.starrocks.client.HttpHelper - Request failed with code:500
2023-09-19 15:58:01,162 WARN  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-643173] [5.1] Exception in org.apache.seatunnel.engine.server.task.SourceSplitEnumeratorTask@1d490c21
org.apache.seatunnel.connectors.seatunnel.starrocks.exception.StarRocksConnectorException: ErrorCode:[STARROCKS-06], ErrorDescription:[Request query Plan failed] - query failed with empty response
        at org.apache.seatunnel.connectors.seatunnel.starrocks.client.source.StarRocksQueryPlanReadClient.getQueryPlan(StarRocksQueryPlanReadClient.java:165) ~[connector-starrocks-2.3.3.jar:2.3.3]
        at org.apache.seatunnel.connectors.seatunnel.starrocks.client.source.StarRocksQueryPlanReadClient.findPartitions(StarRocksQueryPlanReadClient.java:68) ~[connector-starrocks-2.3.3.jar:2.3.3]
        at org.apache.seatunnel.connectors.seatunnel.starrocks.source.StartRocksSourceSplitEnumerator.getStarRocksSourceSplit(StartRocksSourceSplitEnumerator.java:184) ~[connector-starrocks-2.3.3.jar:2.3.3]
        at org.apache.seatunnel.connectors.seatunnel.starrocks.source.StartRocksSourceSplitEnumerator.run(StartRocksSourceSplitEnumerator.java:79) ~[connector-starrocks-2.3.3.jar:2.3.3]
        at org.apache.seatunnel.engine.server.task.SourceSplitEnumeratorTask.stateProcess(SourceSplitEnumeratorTask.java:303) ~[seatunnel-starter.jar:2.3.3]
        at org.apache.seatunnel.engine.server.task.SourceSplitEnumeratorTask.call(SourceSplitEnumeratorTask.java:134) ~[seatunnel-starter.jar:2.3.3]
        at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:613) [seatunnel-starter.jar:2.3.3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by adarshjhaa100** [comment]
@hailin0 could help out with debugging and fixing this issue if its up for grabs
