### ISSUE TITLE
SeaTunnel job executed failed

### ISSUE THREAD

**Issue by SmileCv** [apache/seatunnel#5556]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I reported an error when starting the seatunnel engine using my own configuration file

### SeaTunnel Version

apche-seatunnel-2.3.2

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
  job.mode = "BATCH"
}

source {
   jdbc {
        url = "jdbc:mysql://localhost:14306/student"
        driver = "com.mysql.cj.jdbc.Driver"
        user = "root"
        password = "mile123456"
        query = "select * from seatunnel_test"
	}
}

transform {

}

sink {
   jdbc {
        url = "jdbc:mysql://localhost:7306/student"
        driver = "com.mysql.cj.jdbc.Driver"
        user = "root"
        password = "mile123456"
        query = "insert into seatunnel_test(id,name) values(?,?)"
	}
}
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/mysql_to_mysql_temp.conf -e local
```

### Error Exception

```log
Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:188)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: java.lang.RuntimeException: Plugin PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='jdbc'} not found.
        at org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery.createPluginInstance(AbstractPluginDiscovery.java:223)
        at org.apache.seatunnel.engine.core.parse.ConnectorInstanceLoader.loadSourceInstance(ConnectorInstanceLoader.java:61)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSource(JobConfigParser.java:77)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:298)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:159)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.getLogicalDag(JobExecutionEnvironment.java:155)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:147)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:140)
        ... 2 more
```

### Zeta or Flink or Spark Version

Zeta version

### Java or Scala Version

java8

### Screenshots

![image](https://github.com/apache/seatunnel/assets/128438130/610c1c08-3ebd-4e69-890a-5b5908edfc7b)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhibinF** [comment]
Please according to the deployment document to install connectors plugin.
https://seatunnel.apache.org/docs/2.3.3/start-v2/locally/deployment
