### ISSUE TITLE
[Bug] [connector-v2] jdbc source postgresql Doesn't support Postgres type 'unknown' yet

### ISSUE THREAD

**Issue by luzongzhu** [apache/seatunnel#5603]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

jdbc source postgresql  不支持伪列

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
{
"env" : {
"job.name" : "1711314029275344897",
"job.mode" : "BATCH",
"checkpoint.interval" : 10000,
"execution.parallelism" : 1
},
"source" : [
{
"password" : "****",
"driver" : "org.postgresql.Driver",
"query" : "SELECT sid,machine_id,edc_id,edc_name,point_type,point_area,point_start,point_count,data_mode,key_point,curr_data,insert_time,update_time,special_formula,group_id,real_machine,ext_1,ext_2,second_edc_id,special_edc_handler,is_send_mes,'2023-10-09 17:33:53' as fdop_import_time FROM public.tb_dc_machine_edc_status",
"plugin_name" : "Jdbc",
"user" : "*****",
"url" : "jdbc:postgresql://******:5432/EDC_MANAGER"
}
],
"transform" : [],
"sink" : [
{
"password" : "******",
"driver" : "org.postgresql.Driver",
"query" : "INSERT INTO ods.tb_dc_machine_edc_status(sid,machine_id,edc_id,edc_name,point_type,point_area,point_start,point_count,data_mode,key_point,curr_data,insert_time,update_time,special_formula,group_id,real_machine,ext_1,ext_2,second_edc_id,special_edc_handler,is_send_mes,fdop_import_time) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
"plugin_name" : "Jdbc",
"user" : "*****",
"url" : "jdbc:postgresql://******:4567/dev"
}
]
}
```

### Running Command

```shell
./seatunnel.sh
```

### Error Exception

```log
[INFO] 2023-10-09 17:33:57.983 +0800 - -> 2023-10-09 17:33:57,225 WARN org.apache.seatunnel.connectors.seatunnel.jdbc.source.JdbcSource - get row type info exception
org.apache.seatunnel.connectors.seatunnel.jdbc.exception.JdbcConnectorException: ErrorCode:[COMMON-05], ErrorDescription:[Unsupported operation] - Doesn't support Postgres type 'unknown' yet
at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.psql.PostgresTypeMapper.mapping(PostgresTypeMapper.java:168) ~[connector-jdbc-2.3.3.jar:2.3.3]
at org.apache.seatunnel.connectors.seatunnel.jdbc.source.JdbcSource.initTableField(JdbcSource.java:178) [connector-jdbc-2.3.3.jar:2.3.3]
at org.apache.seatunnel.connectors.seatunnel.jdbc.source.JdbcSource.prepare(JdbcSource.java:108) [connector-jdbc-2.3.3.jar:2.3.3]
at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSource(JobConfigParser.java:85) [seatunnel-starter.jar:2.3.3]
at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:317) [seatunnel-starter.jar:2.3.3]
at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:179) [seatunnel-starter.jar:2.3.3]
at org.apache.seatunnel.engine.core.job.AbstractJobEnvironment.getLogicalDag(AbstractJobEnvironment.java:109) [seatunnel-starter.jar:2.3.3]
at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:73) [seatunnel-starter.jar:2.3.3]
at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:143) [seatunnel-starter.jar:2.3.3]
at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40) [seatunnel-starter.jar:2.3.3]
at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34) [seatunnel-starter.jar:2.3.3]
2023-10-09 17:33:57,232 INFO com.hazelcast.core.LifecycleService - hz.client_1 [seatunnel] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is SHUTTING_DOWN
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wangzhiwei61** [comment]
Friend, how did you solve this problem?
