### ISSUE TITLE
[Bug] [Connector-Hive] SeaTunnel job execute failed with cos_file source and hive sink

### ISSUE THREAD

**Issue by kangta123** [apache/seatunnel#5608]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

i was started seatunnel in local mode and some error message showed up”.

### SeaTunnel Version

seatunnel v2.3.3

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
  job.mode = "BATCH"
}
source {
  CosFile {
    schema {
      fields {
     
      }
    }
    path = "path to file"
    skip_header_row_number = 1
    file_format_type = "excel"
    result_table_name = "take"
    bucket = "cosn://bucket"
    secret_id = "secret_id"
    secret_key = "secret_key"
    region = "ap-region"
  }
}
sink {
  Hive {
    source_table_name = "take"
    table_name = "hive table"
    metastore_uri= "thrift://hive:9300"
    fields=  ["some fields"]
  }
}
```

### Running Command

```shell
./bin/seatunnel.sh  -c seatunnel-cos-to-hive.conf
```

### Error Exception

```log
2023-10-10 18:06:10,577 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Fatal Error, 

2023-10-10 18:06:10,577 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Please submit bug report in https://github.com/apache/seatunnel/issues

2023-10-10 18:06:10,577 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Reason:SeaTunnel job executed failed 

2023-10-10 18:06:10,578 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
 at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:191)
 at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
 at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: com.hazelcast.nio.serialization.HazelcastSerializationException: java.io.InvalidClassException: org.apache.seatunnel.connectors.seatunnel.file.sink.writer.OrcWriteStrategy; local class incompatible: stream classdesc serialVersionUID = -2616292181490356595, local class serialVersionUID = -2381822822589695958
 at com.hazelcast.internal.serialization.impl.SerializationUtil.handleException(SerializationUtil.java:111)
 at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:274)
 at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject.deserializeWithCustomClassLoader(CustomClassLoadedObject.java:66)
 at org.apache.seatunnel.engine.server.TaskExecutionService.deployTask(TaskExecutionService.java:260)
 at org.apache.seatunnel.engine.server.dag.physical.PhysicalVertex.lambda$deployOnLocal$0(PhysicalVertex.java:264)
 at org.apache.seatunnel.engine.server.dag.physical.PhysicalVertex.deployInternal(PhysicalVertex.java:319)
 at org.apache.seatunnel.engine.server.dag.physical.PhysicalVertex.deployOnLocal(PhysicalVertex.java:258)
```

### Zeta or Flink or Spark Version

SeaTunnel Engine Version: 2.3.3

### Java or Scala Version

1.8.0_352

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kangta123** [comment]
hive encoder is orc, but it is worked with encoder textfile

**Comment by FlechazoW** [comment]
Did you replace the JAR file but didn't restart the Seatunnel server?

**Comment by kangta123** [comment]
Should i replace some jar files? i start seatunnel in local mode. 

ps:
hive version v3.1.3
hadoop version v3.2.4
