### ISSUE TITLE
抽取hive分区数据 read_partitions 不支持变量方式传入值

### ISSUE THREAD

**Issue by liushuaihang** [apache/seatunnel#5640]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

我的目的是想通过传变量的方式，将hive指定分区的数据抽取到MySQL，但是就目前来看只能在read_partitions=[]将分区信息提前写好，如果使用变量传入则会抛出异常。，我感觉我的变量声明方式并没有问题

### SeaTunnel Version

seatunnel-2.3.1

### SeaTunnel Config

```conf
env {
  execution.parallelism = 20
  job.mode = "BATCH"
}

source {
 Hive {
table_name = "dws.xxxx"
metastore_uri = "thrift://ip:xxxx"
#result_table_name = "Table_test"
hdfs_site_path = "xxxx/hdfs-site.xml"
hive_site_path = "xxxx/hive-site.xml"
read_partitions = ["dt='"${dt}"'"]
    }
}

#transform {
#}

sink {
    Jdbc {
url = "jdbc:mysql://ip:xxxx/xxx?rewriteBatchedStatements=true"
driver = "xxx"
user = "xxxxxx"
password = "xxxxxx"
database = "xxxxx"
table = "xxx"
query = "insert into xxx values(?,?,?,?,?,?)"
    }
}
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/test.config -i dt=new_partition  -e local
```

### Error Exception

```log
Caused by: org.apache.seatunnel.shade.com.fasterxml.jackson.core.JsonParseException: Unexpected character ('$' (code 36)): was expecting comma to separate Array entri
es
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment]
@liugddx  PTAL

**Comment by XiaoJiang521** [comment]
read_partitions =  ["dt="${dt}""] ;Change the configuration of read_partitions to this mode and try whether it is successful

**Comment by liushuaihang** [comment]
> read_partitions = ["dt="${dt}""] ;Change the configuration of read_partitions to this mode and try whether it is successful

This still fails, and the error reported is the same as above.

**Comment by XiaoJiang521** [comment]
I've had some success with another form before, read_partitions=${dt},You can also try
 Can the error information be more, to see where the execution of the code to report the error，I need to judge why there is such a problem here

**Comment by liushuaihang** [comment]
> I've had some success with another form before, read_partitions=${dt},You can also try Can the error information be more, to see where the execution of the code to report the error，I need to judge why there is such a problem here

Hello, here is more detailed exception information

Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:181)
at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: java.lang.RuntimeException: String json deserialization exception.
at org.apache.seatunnel.common.utils.JsonUtils.parseObject(JsonUtils.java:243)
at org.apache.seatunnel.core.starter.utils.ConfigShadeUtils.processConfig(ConfigShadeUtils.java:139)
at org.apache.seatunnel.core.starter.utils.ConfigShadeUtils.decryptConfig(ConfigShadeUtils.java:118)
at org.apache.seatunnel.core.starter.utils.ConfigShadeUtils.decryptConfig(ConfigShadeUtils.java:103)
at org.apache.seatunnel.core.starter.utils.ConfigBuilder.ofInner(ConfigBuilder.java:53)
at org.apache.seatunnel.core.starter.utils.ConfigBuilder.lambda$of$1(ConfigBuilder.java:67)
at java.util.Optional.orElseGet(Optional.java:267)
at org.apache.seatunnel.core.starter.utils.ConfigBuilder.of(ConfigBuilder.java:67)
at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.<init>(MultipleTableJobConfigParser.java:103)
at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.getJobConfigParser(JobExecutionEnvironment.java:133)
at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.getLogicalDag(JobExecutionEnvironment.java:155)
at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:147)
at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:140)
... 2 more
Caused by: org.apache.seatunnel.shade.com.fasterxml.jackson.core.JsonParseException: Unexpected character ('$' (code 36)): was expecting comma to separate Array entri
es
 at [Source: (String)"{"env":{"execution.parallelism":20,"job.mode":"BATCH"},"source":[{"hive_site_path":"/home/hadoop/hive-2.3.9/conf/hive-site.xml","hdfs_site_path"
:"/home/hadoop/hadoop-3.2.2/etc/hadoop/hdfs-site.xml","read_partitions":["partition_version='"${partition}"'"],"metastore_uri":"thrift://xxx:xxxx","plugin_
name":"Hive","table_name":"dws.xxxxx"}],"sink":[{"password":"xxxxxx","database":"xxxxx","driver":"com.mysql.cj.jdbc
.Driver","query":"insert"[truncated 320 chars]; line: 1, column: 240]
at org.apache.seatunnel.shade.com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2337)
at org.apache.seatunnel.shade.com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:710)
at org.apache.seatunnel.shade.com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:635)
at org.apache.seatunnel.shade.com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipComma(ReaderBasedJsonParser.java:2328)
at org.apache.seatunnel.shade.com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:695)
at org.apache.seatunnel.shade.com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeArray(JsonNodeDeserializer.java:466)
at org.apache.seatunnel.shade.com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:280)
at org.apache.seatunnel.shade.com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeArray(JsonNodeDeserializer.java:469)
at org.apache.seatunnel.shade.com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:280)
at org.apache.seatunnel.shade.com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:69)
at org.apache.seatunnel.shade.com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:16)
at org.apache.seatunnel.shade.com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
at org.apache.seatunnel.shade.com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4635)
at org.apache.seatunnel.shade.com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3042)
at org.apache.seatunnel.common.utils.JsonUtils.parseObject(JsonUtils.java:240)
... 14 more

**Comment by XiaoJiang521** [comment]
Hive {
   ……
    "read_partitions"=${sea}
    ……
}
-i sea=[event_month=09/event_day=28,event_month=09/event_day=29]

- I am now testing that this is OK, you can use this first

**Comment by liushuaihang** [comment]
> Hive { …… "read_partitions"=${sea} …… } -i sea=[event_month=09/event_day=28,event_month=09/event_day=29]
> 
> * I am now testing that this is OK, you can use this first

May I ask what version of seatunnel you are using.
My version is 2.3.1.
Referring to your template, still reporting the same error as before.

My configuration is as follows：
Hive {
......
"read_partitions" =${partition}
......
}

./bin/seatunnel.sh --config ./config/test.config -i partition=[dt=first_day] -e local

**Comment by XiaoJiang521** [comment]
2.3.1 version does report errors, this problem should be in the code has not been released, perhaps the next version of this can be used;  In 2.3.1, "read_partitions" =${partition}.  partition=[dt=first_day] This error occurs because [dt=first_day] is a list type, and 2.3.1 was not converted to list after the replacement

**Comment by liushuaihang** [comment]
> 2.3.1 version does report errors, this problem should be in the code has not been released, perhaps the next version of this can be used; In 2.3.1, "read_partitions" =${partition}. partition=[dt=first_day] This error occurs because [dt=first_day] is a list type, and 2.3.1 was not converted to list after the replacement

Thank you for your reply. Will this BUG be fixed in future versions? According to my research, version 2.3.3 also has bugs. Use version 2.3.3 to read hive partition data, but it cannot be read successfully even without using variables.

**Comment by XiaoJiang521** [comment]
1.  The currently replaced bug will be fixed in the next version, i.e. 2.3.4.
2.  You can send the error message that you use hive to read the partition
3.  The current hive does have all the problems in reading partitions.  To read partitions correctly, all partitions must be written down.  
ex: you have partition is "month" ,value is 3,4,5 . conf should be "read_partitions = [month=3,month=4,month=5]"  This is also a problem and someone is fixing it

**Comment by liugddx** [comment]
use 2.3.4
