### ISSUE TITLE
[Bug] [Module Name] Bug title

### ISSUE THREAD

**Issue by yjm12333** [apache/seatunnel#5696]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

sqlserver to clickhouse

### SeaTunnel Version

Apache SeaTunnel2.3.3

### SeaTunnel Config

```conf
--connectors-v2--
connector-fake
connector-console
connector-cdc-sqlserver
connector-clickhouse
connector-cdc-mysql
connector-jdbc
--end--
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/v2.batch.config.template -e local
```

### Error Exception

```log
2023-10-24 17:31:52,464 INFO  com.hazelcast.core.LifecycleService - hz.client_1 [seatunnel-877026] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is SHUTDOWN
2023-10-24 17:31:52,464 INFO  org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand - Closed SeaTunnel client......
2023-10-24 17:31:52,464 INFO  com.hazelcast.core.LifecycleService - [localhost]:5801 [seatunnel-877026] [5.1] [localhost]:5801 is SHUTTING_DOWN
2023-10-24 17:31:52,467 INFO  com.hazelcast.instance.impl.Node - [localhost]:5801 [seatunnel-877026] [5.1] Shutting down connection manager...
2023-10-24 17:31:52,468 INFO  com.hazelcast.instance.impl.Node - [localhost]:5801 [seatunnel-877026] [5.1] Shutting down node engine...
2023-10-24 17:31:52,473 INFO  org.apache.seatunnel.engine.server.SeaTunnelServer - master node check interrupted
2023-10-24 17:31:55,502 INFO  com.hazelcast.instance.impl.NodeExtension - [localhost]:5801 [seatunnel-877026] [5.1] Destroying node NodeExtension.
2023-10-24 17:31:55,503 INFO  com.hazelcast.instance.impl.Node - [localhost]:5801 [seatunnel-877026] [5.1] Hazelcast Shutdown is completed in 3037 ms.
2023-10-24 17:31:55,504 INFO  com.hazelcast.core.LifecycleService - [localhost]:5801 [seatunnel-877026] [5.1] [localhost]:5801 is SHUTDOWN
2023-10-24 17:31:55,504 INFO  org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand - Closed HazelcastInstance ......
2023-10-24 17:31:55,505 ERROR org.apache.seatunnel.core.starter.SeaTunnel -

===============================================================================


2023-10-24 17:31:55,505 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Fatal Error,

2023-10-24 17:31:55,505 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Please submit bug report in https://github.com/apache/seatunnel/issues

2023-10-24 17:31:55,505 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Reason:SeaTunnel job executed failed

2023-10-24 17:31:55,509 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:191)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:659)
        at java.util.ArrayList.get(ArrayList.java:435)
        at org.apache.seatunnel.connectors.seatunnel.cdc.sqlserver.source.source.SqlServerIncrementalSource.createDebeziumDeserializationSchema(SqlServerIncrementalSource.java:114)
        at org.apache.seatunnel.connectors.cdc.base.source.IncrementalSource.prepare(IncrementalSource.java:119)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSource(JobConfigParser.java:85)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:317)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:179)
        at org.apache.seatunnel.engine.core.job.AbstractJobEnvironment.getLogicalDag(AbstractJobEnvironment.java:109)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:73)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:143)
        ... 2 more

2023-10-24 17:31:55,509 ERROR org.apache.seatunnel.core.starter.SeaTunnel -
===============================================================================



Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:191)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:659)
        at java.util.ArrayList.get(ArrayList.java:435)
        at org.apache.seatunnel.connectors.seatunnel.cdc.sqlserver.source.source.SqlServerIncrementalSource.createDebeziumDeserializationSchema(SqlServerIncrementalSource.java:114)
        at org.apache.seatunnel.connectors.cdc.base.source.IncrementalSource.prepare(IncrementalSource.java:119)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSource(JobConfigParser.java:85)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:317)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:179)
        at org.apache.seatunnel.engine.core.job.AbstractJobEnvironment.getLogicalDag(AbstractJobEnvironment.java:109)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:73)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:143)
        ... 2 more
```

### Java or Scala Version

java1.8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhilinli123** [comment]
Please provide SqlServer& Click house DDL along with your.conf configuration file, which needs to be supplemented in more detail to facilitate problem locating

**Comment by yjm12333** [comment]
tky，I mistakenly used job.mode = "BATCH" ,Modify to job.mode = "STREAMING" solve the problem
