### ISSUE TITLE
java.util.concurrent.TimeoutException: Idle timeout expired: 30001/30000 ms

### ISSUE THREAD

**Issue by wachoo** [apache/seatunnel#5701]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

[Server.handle():519] - handled=true async=false committed=true on HttpChannelOverHttp@1ec3c3f0{s=HttpChannelState@1afc44f0{s=HANDLING rs=BLOCKING os=COMMITTED is=IDLE awp=false se=false i=true al=0},r=11,c=false/false,a=HANDLING,uri=//172.17.2.30:8801/seatunnel/api/v1/job/executor/execute?jobDefineId=11220675447904,age=270}

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
seatunnel:
  engine:
    history-job-expire-minutes: 1440
    backup-count: 1
    queue-type: blockingqueue
    print-execution-info-interval: 60
    print-job-metrics-info-interval: 60
    slot-service:
      dynamic-slot: true
    checkpoint:
      interval: 10000
      timeout: 60000
      storage:
        type: hdfs
        max-retained: 3
        plugin-config:
          namespace: /tmp/seatunnel/checkpoint_snapshot
          storage.type: hdfs
          fs.defaultFS: file:///tmp/ # Ensure that the directory has written permission
```

### Running Command

```shell
cd ${SEATUNNEL_HOME} && sh ./bin/seatunnel-cluster.sh -d
```

### Error Exception

```log
onFail FillInterest@3b39e3d{AC.ReadCB@1aec7caf{HttpConnection@1aec7caf::SocketChannelEndPoint@55169246{l=/172.17.2.30:8801,r=/10.2.6.172:50500,OPEN,fill=FI,flush=-,to=30002/30000}{io=1/1,kio=1,kro=0}->HttpConnection@1aec7caf[p=HttpParser{s=START,0 of -1},g=HttpGenerator@2bbce535{s=START}]=>HttpChannelOverHttp@5bd17694{s=HttpChannelState@5feef936{s=IDLE rs=BLOCKING os=OPEN is=IDLE awp=false se=false i=true al=0},r=0,c=false/false,a=IDLE,uri=null,age=0}}}
java.util.concurrent.TimeoutException: Idle timeout expired: 30001/30000 ms
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:171)
	at org.eclipse.jetty.io.IdleTimeout.idleCheck(IdleTimeout.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Zeta or Flink or Spark Version

Zeta 2.3.3

### Java or Scala Version

openjdk version "1.8.0_372"

### Screenshots

![image](https://github.com/apache/seatunnel/assets/13916787/60be13ee-744f-44b8-9847-6a7da35aee3c)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wachoo** [comment]
is there a config parameter for this error
