### ISSUE TITLE
[help][local develop environment] Plugin PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='connector-fake'} not found

### ISSUE THREAD

**Issue by QiuZiXian** [apache/seatunnel#5738]
idea env, seatunel dev branch
I has successfully run seatunnel-examples/seatunnel-engine-examples/src/main/java/org/apache/seatunnel/example/engine/SeaTunnelEngineServerExample.java
with the postman to test.
/hazelcast/rest/maps/submit-job
![image](https://github.com/apache/seatunnel/assets/28780269/3a9dc200-f66b-4cad-a085-949ccab40644)
throw fail:
`
2023-10-27 15:50:32,781 INFO  org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery - Load SeaTunnelSource Plugin from E:\e\project\shida\work\master-data\data-collect\seatunnel\seatunnel-common\connectors
2023-10-27 15:50:32,792 WARN  org.apache.seatunnel.engine.server.log.Log4j2HttpPostCommandProcessor - [localhost]:5801 [seatunnel] [5.1] An error occurred while handling request HttpCommand [HTTP_POST]{uri='/hazelcast/rest/maps/submit-job'}AbstractTextCommand[HTTP_POST]{requestId=0}
java.lang.RuntimeException: Plugin PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='connector-fake'} not found.
	at org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery.createPluginInstance(AbstractPluginDiscovery.java:231) ~[classes/:?]
	at org.apache.seatunnel.engine.core.parse.ConnectorInstanceLoader.loadSourceInstance(ConnectorInstanceLoader.java:61) ~[classes/:?]
	at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSource(JobConfigParser.java:81) ~[classes/:?]
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:305) ~[classes/:?]
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:176) ~[classes/:?]
	at org.apache.seatunnel.engine.core.job.AbstractJobEnvironment.getLogicalDag(AbstractJobEnvironment.java:109) ~[classes/:?]
	at org.apache.seatunnel.engine.server.job.RestJobExecutionEnvironment.build(RestJobExecutionEnvironment.java:76) ~[classes/:?]
	at org.apache.seatunnel.engine.server.rest.RestHttpPostCommandProcessor.handleSubmitJob(RestHttpPostCommandProcessor.java:118) ~[classes/:?]
	at org.apache.seatunnel.engine.server.rest.RestHttpPostCommandProcessor.handle(RestHttpPostCommandProcessor.java:72) [classes/:?]
	at org.apache.seatunnel.engine.server.rest.RestHttpPostCommandProcessor.handle(RestHttpPostCommandProcessor.java:51) [classes/:?]
	at com.hazelcast.internal.ascii.TextCommandServiceImpl$CommandExecutor.run(TextCommandServiceImpl.java:402) [hazelcast-5.1.jar:5.1]
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217) [hazelcast-5.1.jar:5.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) [hazelcast-5.1.jar:5.1]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [hazelcast-5.1.jar:5.1]
`

I try put connectors as below,but no effect.
![image](https://github.com/apache/seatunnel/assets/28780269/67b959f0-c283-489f-a5ab-f10ce265cb60)

![image](https://github.com/apache/seatunnel/assets/28780269/dbb3eaa5-ddc1-47d9-b004-4b018aba2c48)
so where I need to put those connectors?

**Comment by liunaijie** [comment]
if you started from `seatunnel-engine-examples` module, you should import connector in pom.xml.

**Comment by QiuZiXian** [comment]
fake and console already exist in pom.xml
![Uploading image.png…]()

**Comment by codeDing18** [comment]
You can check if seatunnel_home/connectors/plugin-mapping.properties has connector-fake and console
