### ISSUE TITLE
[Bug] [MongoDB-CDC/MongoDb] 二进制数据无法写入达梦/oracle

### ISSUE THREAD

**Issue by Xuzhengz** [apache/seatunnel#5748]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

读取mongodb二进制数据，仅仅30kb的图片数据，就已经超出达梦/oracle的二进制最大长度

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
{
  "env": {
    "execution.parallelism": "1",
    "job.mode": "STREAMING",
    "checkpoint.interval": "5000"
  },
  "source": [
    {
      "hosts": "172.16.8.205:37017,172.16.8.205:37018,172.16.8.205:37019",
      "password": "******",
      "connection.options": "authSource=cdc",
      "collection": [
        "cdc.test"
      ],
      "result_table_name": "test",
      "database": [
        "cdc"
      ],
      "plugin_name": "MongoDB-CDC",
      "username": "stuser",
      "schema": {
        "fields": {
          "_id": "STRING",
          "name": "STRING",
          "age": "DOUBLE",
          "sex": "STRING",
          "image": "BYTES"
        }
      }
    }
  ],
  "transform": [],
  "sink": [
    {
      "password": "******",
      "database": "CDC",
      "batch_size": 2000,
      "primary_keys": [
        "_id"
      ],
      "driver": "dm.jdbc.driver.DmDriver",
      "source_table_name": "test",
      "plugin_name": "Jdbc",
      "enable_upsert": true,
      "generate_sink_sql": true,
      "user": "SYSDBA",
      "url": "jdbc:dm://172.16.11.202:5236/CDC",
      "table": "mongo_cdc_demo_sink",
      "batch_interval_ms": 1000
    }
  ]
}
```

### Running Command

```shell
bin/seatunnel.sh -c demo.json
```

### Error Exception

```log
Caused by: java.sql.BatchUpdateException: 数据大小已超过可支持范围
	at dm.jdbc.driver.DBError.throwBatchUpdateException(DBError.java:713)
	at dm.jdbc.b.a.a(DBAccess.java:874)
	at dm.jdbc.driver.DmdbPreparedStatement.do_executeLargeBatch(DmdbPreparedStatement.java:567)
	at dm.jdbc.driver.DmdbPreparedStatement.do_executeBatch(DmdbPreparedStatement.java:514)
	at dm.jdbc.driver.DmdbPreparedStatement.executeBatch(DmdbPreparedStatement.java:1518)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.executor.FieldNamedPreparedStatement.executeBatch(FieldNamedPreparedStatement.java:533)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.executor.SimpleBatchStatementExecutor.executeBatch(SimpleBatchStatementExecutor.java:51)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.executor.BufferReducedBatchStatementExecutor.executeBatch(BufferReducedBatchStatementExecutor.java:89)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.JdbcOutputFormat.attemptFlush(JdbcOutputFormat.java:165)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.JdbcOutputFormat.flush(JdbcOutputFormat.java:130)
	... 18 more

	at org.apache.seatunnel.engine.client.job.ClientJobProxy.waitForJobComplete(ClientJobProxy.java:122)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:183)
	... 2 more
```

### Java or Scala Version

1.8

### Screenshots

<img width="1243" alt="image" src="https://github.com/apache/seatunnel/assets/90698333/edc84ecf-bc36-4285-9cd8-8b0716618742">
<img width="677" alt="image" src="https://github.com/apache/seatunnel/assets/90698333/ef328bd3-9b79-4415-9bdf-33e8714f6797">
<img width="535" alt="image" src="https://github.com/apache/seatunnel/assets/90698333/a6efc63d-e186-4d3a-a10c-2b87cd5bfed2">

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Carl-Zhou-CN** [comment]
hi, @Xuzhengz Has there been any progress on this issue?
