### ISSUE TITLE
[connector-v2] [jdbc] sqlserver don't support UNIQUEIDENTIFIER type

### ISSUE THREAD

**Issue by zhenhb** [apache/seatunnel#5759]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

syn mysqlserver data to doris error,i see in SqlserverTypeMapper  UNIQUEIDENTIFIER type not considered

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
{
    "env" : {
        "parallelism" : 5,
        "job.mode" : "BATCH"
    },
    "source" : [
        {
            "password" : "xxxxx",
            "driver" : "com.microsoft.sqlserver.jdbc.SQLServerDriver",
            "query" : "SELECT * FROM xxx",
            "result_table_name" : "xxx",
            "plugin_name" : "Jdbc",
            "user" : "sa",
            "url" : "jdbc:sqlserver://xxxx;databasename=xxx"
        }
    ],
    "sink" : [
        {
            "database" : "sinoma",
            "password" : "",
            "primary_keys" : [
                "Id"
            ],
            "driver" : "com.mysql.jdbc.Driver",
            "schema_save_mode" : "RECREATE_SCHEMA",
            "source_table_name" : "xxx",
            "generate_sink_sql" : true,
            "plugin_name" : "jdbc",
            "user" : "root",
            "url" : "jdbc:mysql://xxxx/sinoma?rewriteBatchedStatements=true",
            "table" : "xxxx"
        }
    ]
}
```

### Running Command

```shell
seatunnel.sh --config sqlserver2doris.config -e local
```

### Error Exception

```log
Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:190)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.api.table.factory.FactoryException: ErrorCode:[API-06], ErrorDescription:[Factory initialize failed] - Unable to create a source for identifier 'Jdbc'.
        at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:107)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:311)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:176)
        at org.apache.seatunnel.engine.core.job.AbstractJobEnvironment.getLogicalDag(AbstractJobEnvironment.java:109)
        at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.execute(ClientJobExecutionEnvironment.java:73)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:142)
        ... 2 more
Caused by: org.apache.seatunnel.connectors.seatunnel.jdbc.exception.JdbcConnectorException: ErrorCode:[COMMON-05], ErrorDescription:[Unsupported operation] - Doesn't support SQLSERVER type 'UNIQUEIDENTIFIER' on column 'Id'  yet.
        at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.sqlserver.SqlserverTypeMapper.mapping(SqlserverTypeMapper.java:132)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.JdbcDialectTypeMapper.mappingColumn(JdbcDialectTypeMapper.java:49)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.utils.CatalogUtils.lambda$getCatalogTable$2(CatalogUtils.java:225)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.utils.CatalogUtils.getCatalogTable(CatalogUtils.java:238)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.utils.CatalogUtils.getCatalogTable(CatalogUtils.java:220)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.utils.CatalogUtils.getCatalogTable(CatalogUtils.java:255)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.sqlserver.SqlServerCatalog.getTable(SqlServerCatalog.java:237)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.utils.JdbcCatalogUtils.getCatalogTable(JdbcCatalogUtils.java:173)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.utils.JdbcCatalogUtils.getTables(JdbcCatalogUtils.java:78)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.source.JdbcSource.<init>(JdbcSource.java:58)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.source.JdbcSourceFactory.lambda$createSource$0(JdbcSourceFactory.java:78)
        at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:119)
        at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:79)
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment]
Yes, It's a bug, Are you interested in submitting a PR to fix it?
