### ISSUE TITLE
[Bug] [Module Name] install plugins prompt "Exception in thread "main" java.util.zip.ZipException: error in opening zip file"

### ISSUE THREAD

**Issue by charnet1019** [apache/seatunnel#5775]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

plugin install failed.

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
--connectors-v2--
connector-assert
connector-cdc-mysql
connector-cdc-mongodb
connector-cdc-sqlserver
connector-clickhouse
connector-doris
connector-jdbc
connector-kafka
connector-mongodb
connector-socket
--end--
```

### Running Command

```shell
./bin/install-plugin.sh
```

### Error Exception

```log
[root@datasophon07 apache-seatunnel-2.3.3]# ./bin/install-plugin.sh 
Install hadoop shade jar, usage version is 2.3.3
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:226)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.apache.maven.wrapper.Installer.unzip(Installer.java:209)
	at org.apache.maven.wrapper.Installer.createDist(Installer.java:102)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:155)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:72)
Install SeaTunnel connectors plugins, usage version is 2.3.3
install connector :  connector-assert
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:226)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.apache.maven.wrapper.Installer.unzip(Installer.java:209)
	at org.apache.maven.wrapper.Installer.createDist(Installer.java:102)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:155)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:72)
install connector :  connector-cdc-mysql
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:226)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.apache.maven.wrapper.Installer.unzip(Installer.java:209)
	at org.apache.maven.wrapper.Installer.createDist(Installer.java:102)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:155)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:72)
install connector :  connector-cdc-mongodb
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:226)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.apache.maven.wrapper.Installer.unzip(Installer.java:209)
	at org.apache.maven.wrapper.Installer.createDist(Installer.java:102)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:155)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:72)
install connector :  connector-cdc-sqlserver
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:226)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.apache.maven.wrapper.Installer.unzip(Installer.java:209)
	at org.apache.maven.wrapper.Installer.createDist(Installer.java:102)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:155)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:72)
install connector :  connector-clickhouse
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:226)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.apache.maven.wrapper.Installer.unzip(Installer.java:209)
	at org.apache.maven.wrapper.Installer.createDist(Installer.java:102)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:155)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:72)
install connector :  connector-doris
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:226)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.apache.maven.wrapper.Installer.unzip(Installer.java:209)
	at org.apache.maven.wrapper.Installer.createDist(Installer.java:102)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:155)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:72)
install connector :  connector-jdbc
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:226)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.apache.maven.wrapper.Installer.unzip(Installer.java:209)
	at org.apache.maven.wrapper.Installer.createDist(Installer.java:102)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:155)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:72)
install connector :  connector-kafka
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:226)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.apache.maven.wrapper.Installer.unzip(Installer.java:209)
	at org.apache.maven.wrapper.Installer.createDist(Installer.java:102)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:155)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:72)
install connector :  connector-mongodb
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:226)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.apache.maven.wrapper.Installer.unzip(Installer.java:209)
	at org.apache.maven.wrapper.Installer.createDist(Installer.java:102)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:155)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:72)
install connector :  connector-socket
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:226)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.apache.maven.wrapper.Installer.unzip(Installer.java:209)
	at org.apache.maven.wrapper.Installer.createDist(Installer.java:102)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:155)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:72)
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
I meet this issue before, I reminbere this is because jar package broken, you can try delete the `maven-wrapper.jar`.

**Comment by szx1** [comment]
> I meet this issue before, I reminbere this is because jar package broken, you can try delete the `maven-wrapper.jar`.

not working

**Comment by lidongfu005** [comment]
Install SeaTunnel connectors plugins, usage version is 2.3.4
install connector :  connector-cdc-mysql
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.apache.maven.wrapper.Installer.unzip(Installer.java:209)
	at org.apache.maven.wrapper.Installer.createDist(Installer.java:102)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:155)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:72)
install connector :  connector-doris
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)

一样的问题。。。。官方文档这么差吗，解压第二步运行就不行。。。。

**Comment by buxiuzhang** [comment]
I still encounter this problem in seatunnel 2.3.7
<img width="632" alt="image" src="https://github.com/user-attachments/assets/d438faa0-0d4c-43ce-963c-50b26ae0654f">
