### ISSUE TITLE
[Feature][seatunnel-web] web端几乎不可用，什么时候提供完整的web界面，非常期待

### ISSUE THREAD

**Issue by huguiqi** [apache/seatunnel#5794]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

https://github.com/apache/seatunnel-web

<img width="1035" alt="image" src="https://github.com/apache/seatunnel/assets/490617/2a3d75ad-86fa-4a7e-a2dc-88637543a074">

### Usage Scenario

希望将来可以提供一个完整可用的产品，加油。。。。。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by coding-now** [comment]
补充 测试过程中发现的问题：
1、任务列表-服务端没有集成分页插件，无法分页
2、同步任务 无法删除，服务端没有接口实现，任务定义缺失操作状态控制
3、表结构定义 粗糙，无相关索引定义，唯一性索引缺失

**Comment by QiuZiXian** [comment]
![image](https://github.com/apache/seatunnel/assets/28780269/4340ee40-f47d-4776-a9ed-e36e1b2376e9)
拖拉试一下

**Comment by huguiqi** [comment]
> ![image](https://user-images.githubusercontent.com/28780269/280887706-4340ee40-f47d-4776-a9ed-e36e1b2376e9.png) 拖拉试一下

拖拉过了，里面的配置很多也不知道怎么配置，不知道怎么使用

**Comment by wangkun723** [comment]
请问，web怎么部署，我按照提供的文档部署没有成功

**Comment by jianchengwang** [comment]
datasource/list alert `Unknown exception`, log here 
```
Caused by: java.lang.ClassNotFoundException: org.apache.seatunnel.datasource.plugin.oracle.jdbc.OracleJdbcDataSourceFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.apache.seatunnel.datasource.classloader.DatasourceClassLoader.loadClass(DatasourceClassLoader.java:56)
	... 69 more

2023-11-13 14:23:39.373 seatunnel seatunnel-web ERROR [tr:,sp:] [qtp32749970-18] [GlobalExceptionHandler.logError():83] - No supported data source found
org.apache.seatunnel.datasource.exception.DataSourceSDKException: No supported data source found
	at org.apache.seatunnel.datasource.AbstractDataSourceClient.<init>(AbstractDataSourceClient.java:107)
	at org.apache.seatunnel.datasource.DataSourceClient.<init>(DataSourceClient.java:26)
	at org.apache.seatunnel.app.thirdparty.datasource.DataSourceClientFactory.getDataSourceClient(DataSourceClientFactory.java:32)
	at org.apache.seatunnel.app.service.impl.DatasourceServiceImpl.queryAllDatasourcesGroupByType(DatasourceServiceImpl.java:478)
	at org.apache.seatunnel.app.controller.SeatunnelDatasourceController.getSupportDatasources(SeatunnelDatasourceController.java:304)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)

```

**Comment by supercena** [comment]
是的 同问 不可用

**Comment by qinzhenlong** [comment]
同问
![image](https://github.com/apache/seatunnel/assets/18487533/b0ad442a-083b-45c9-938b-5190d1d830e2)

**Comment by jianchengwang** [comment]
It may be seatunnel-web needs to import some lib jar,  i suggest like airbyte, when I choose a source and it tests and auto download jar will be better

**Comment by codeDing18** [comment]
> datasource/list alert `Unknown exception`, log here
> 
> ```
> Caused by: java.lang.ClassNotFoundException: org.apache.seatunnel.datasource.plugin.oracle.jdbc.OracleJdbcDataSourceFactory
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
> 	at org.apache.seatunnel.datasource.classloader.DatasourceClassLoader.loadClass(DatasourceClassLoader.java:56)
> 	... 69 more
> 
> 2023-11-13 14:23:39.373 seatunnel seatunnel-web ERROR [tr:,sp:] [qtp32749970-18] [GlobalExceptionHandler.logError():83] - No supported data source found
> org.apache.seatunnel.datasource.exception.DataSourceSDKException: No supported data source found
> 	at org.apache.seatunnel.datasource.AbstractDataSourceClient.<init>(AbstractDataSourceClient.java:107)
> 	at org.apache.seatunnel.datasource.DataSourceClient.<init>(DataSourceClient.java:26)
> 	at org.apache.seatunnel.app.thirdparty.datasource.DataSourceClientFactory.getDataSourceClient(DataSourceClientFactory.java:32)
> 	at org.apache.seatunnel.app.service.impl.DatasourceServiceImpl.queryAllDatasourcesGroupByType(DatasourceServiceImpl.java:478)
> 	at org.apache.seatunnel.app.controller.SeatunnelDatasourceController.getSupportDatasources(SeatunnelDatasourceController.java:304)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
> 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
> 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
> 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
> 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
> 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
> 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
> ```

you can download datasource jar from [seatunnel](https://repo.maven.apache.org/maven2/org/apache/seatunnel/).For example,datasource-hive.Then put the jar to the `seatunnel-web/libs`dir. restart your server.

**Comment by KangTomwk** [comment]
使用前先自行研究下内部源码，会好一点

**Comment by wilsonfu88** [comment]
感觉目前还是个半成品，期待新版本发布

**Comment by liutianyuan** [comment]
官方文档就是个摆设，跑不起来。。。。
