### ISSUE TITLE
[Bug] [mysql-cdc] mysql cdc 任务提交异常退出不会自动断开连接 

### ISSUE THREAD

**Issue by chase-cai-huan** [apache/seatunnel#5817]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

![image](https://github.com/apache/seatunnel/assets/145539087/03a95e6c-6494-42cd-99fb-c8580b1d5796)

 mysql cdc 任务提交异常退出不会自动断开连接，重新提交任务又会创建新的连接 导致出现  Too many connections

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
2.3.3
```

### Running Command

```shell
./../bin/seatunnel.sh --config cdc.config
```

### Error Exception

```log
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Data source rejected establishment of connection,  message from server: "Too many connections"
	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at org.apache.seatunnel.connectors.cdc.base.relational.connection.JdbcConnectionPoolFactory.createPooledDataSource(JdbcConnectionPoolFactory.java:53)
	at org.apache.seatunnel.connectors.cdc.base.relational.connection.JdbcConnectionPools.getOrCreateConnectionPool(JdbcConnectionPools.java:56)
	at org.apache.seatunnel.connectors.cdc.base.relational.connection.JdbcConnectionFactory.connect(JdbcConnectionFactory.java:60)
	at io.debezium.jdbc.JdbcConnection.connection(JdbcConnection.java:890)
	at io.debezium.jdbc.JdbcConnection.connection(JdbcConnection.java:885)
	at io.debezium.jdbc.JdbcConnection.connect(JdbcConnection.java:418)
	at org.apache.seatunnel.connectors.cdc.base.dialect.JdbcDataSourceDialect.openJdbcConnection(JdbcDataSourceDialect.java:66)
```

### Zeta or Flink or Spark Version

Zeta

### Java or Scala Version

java 1.8

### Screenshots

  
![1699498765407](https://github.com/apache/seatunnel/assets/145539087/f56e40a0-98d4-4241-8c2f-fd931afbac03)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EricJoy2048** [comment]
@hailin0  PTAL

**Comment by chase-cai-huan** [comment]
> @hailin0 PTAL

Is there a solution to this problem？

**Comment by happyboy1024** [comment]
> > @hailin0 PTAL
> 
> Is there a solution to this problem？

Can you provide the server side log when the task fails to start, as detailed as possible
