### ISSUE TITLE
[Bug] [starrocks]配置文件参数问题

### ISSUE THREAD

**Issue by corgier** [apache/seatunnel#5827]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

mysql迁移starrocks一直提示参数不正确，从mysql sink到console是正确的。

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
sink {
    StarRocks {
        batch_max_rows=10240 #
        source_table_name="Table9210050164000"
        table="test2"
        database="sr_test"
        base-url="jdbc:mysql://datasource01:9030"
        password="root"
        username="root"
        nodeUrls=[
            "datasource01:8030" #写入数据是通过StarRocks的Http接口
        ]
    }
}
```

### Running Command

```shell
sh bin/seatunnel.sh --config config/mysql_to_sr.config
```

### Error Exception

```log
023-11-10 16:10:08,683 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:191)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: java.lang.IllegalArgumentException
	at org.apache.seatunnel.shade.com.google.common.base.Preconditions.checkArgument(Preconditions.java:127)
	at org.apache.seatunnel.connectors.seatunnel.starrocks.catalog.StarRocksCatalog.<init>(StarRocksCatalog.java:86)
	at org.apache.seatunnel.connectors.seatunnel.starrocks.catalog.StarRocksCatalogFactory.createCatalog(StarRocksCatalogFactory.java:39)
	at org.apache.seatunnel.api.table.factory.FactoryUtil.lambda$createOptionalCatalog$0(FactoryUtil.java:153)
	at java.util.Optional.map(Optional.java:215)
	at org.apache.seatunnel.api.table.factory.FactoryUtil.createOptionalCatalog(FactoryUtil.java:152)
	at org.apache.seatunnel.api.table.catalog.CatalogTableUtil.getCatalogTables(CatalogTableUtil.java:113)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSink(MultipleTableJobConfigParser.java:538)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:190)
	at org.apache.seatunnel.engine.core.job.AbstractJobEnvironment.getLogicalDag(AbstractJobEnvironment.java:109)
	at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:73)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:143)
	... 2 more

2023-11-10 16:10:08,683 ERROR org.apache.seatunnel.core.starter.SeaTunnel -
===============================================================================



Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:191)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: java.lang.IllegalArgumentException
	at org.apache.seatunnel.shade.com.google.common.base.Preconditions.checkArgument(Preconditions.java:127)
	at org.apache.seatunnel.connectors.seatunnel.starrocks.catalog.StarRocksCatalog.<init>(StarRocksCatalog.java:86)
	at org.apache.seatunnel.connectors.seatunnel.starrocks.catalog.StarRocksCatalogFactory.createCatalog(StarRocksCatalogFactory.java:39)
	at org.apache.seatunnel.api.table.factory.FactoryUtil.lambda$createOptionalCatalog$0(FactoryUtil.java:153)
	at java.util.Optional.map(Optional.java:215)
	at org.apache.seatunnel.api.table.factory.FactoryUtil.createOptionalCatalog(FactoryUtil.java:152)
	at org.apache.seatunnel.api.table.catalog.CatalogTableUtil.getCatalogTables(CatalogTableUtil.java:113)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSink(MultipleTableJobConfigParser.java:538)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:190)
	at org.apache.seatunnel.engine.core.job.AbstractJobEnvironment.getLogicalDag(AbstractJobEnvironment.java:109)
	at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:73)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:143)
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by corgier** [comment]
和版本有关系吗，starrocks是3.1.4

**Comment by corgier** [comment]
成功了。。。。之前没设置密码，导致有个check参数的校验没过。。。。

**Comment by bulolo** [comment]
我也是一直报错
```
2024-02-11 22:38:54,217 INFO  [.s.p.d.AbstractPluginDiscovery] [main] - Load SeaTunnelSink Plugin from /Users/junyao/Desktop/apache-seatunnel-2.3.4-SNAPSHOT/connectors
2024-02-11 22:38:54,219 INFO  [.s.p.d.AbstractPluginDiscovery] [main] - Discovery plugin jar for: PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='MongoDB-CDC'} at: file:/Users/junyao/Desktop/apache-seatunnel-2.3.4-SNAPSHOT/connectors/connector-cdc-mongodb-2.3.4-SNAPSHOT.jar
2024-02-11 22:38:54,220 INFO  [.s.p.d.AbstractPluginDiscovery] [main] - Discovery plugin jar for: PluginIdentifier{engineType='seatunnel', pluginType='sink', pluginName='StarRocks'} at: file:/Users/junyao/Desktop/apache-seatunnel-2.3.4-SNAPSHOT/connectors/connector-starrocks-2.3.4-SNAPSHOT.jar
2024-02-11 22:38:54,221 WARN  [o.a.s.a.c.u.ConfigUtil        ] [main] - Option 'source_table_name' is a List, and it is recommended to configure it as ["string1","string2"]; we will only use ',' to split the String into a list.
2024-02-11 22:38:54,221 WARN  [o.a.s.a.c.u.ConfigUtil        ] [main] - Option 'source_table_name' is a List, and it is recommended to configure it as ["string1","string2"]; we will only use ',' to split the String into a list.
2024-02-11 22:38:54,223 INFO  [p.MultipleTableJobConfigParser] [main] - start generating all sources.
2024-02-11 22:38:54,246 INFO  [o.a.s.a.t.f.FactoryUtil       ] [main] - get the CatalogTable from source MongoDB-CDC: MongoDB.null.fake
2024-02-11 22:38:54,250 INFO  [.s.p.d.AbstractPluginDiscovery] [main] - Load SeaTunnelSource Plugin from /Users/junyao/Desktop/apache-seatunnel-2.3.4-SNAPSHOT/connectors
2024-02-11 22:38:54,252 INFO  [.s.p.d.AbstractPluginDiscovery] [main] - Discovery plugin jar for: PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='MongoDB-CDC'} at: file:/Users/junyao/Desktop/apache-seatunnel-2.3.4-SNAPSHOT/connectors/connector-cdc-mongodb-2.3.4-SNAPSHOT.jar
2024-02-11 22:38:54,252 INFO  [c.h.c.LifecycleService        ] [main] - hz.client_1 [seatunnel-674766] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is SHUTTING_DOWN
2024-02-11 22:38:54,253 INFO  [c.h.i.s.t.TcpServerConnection ] [hz.main.IO.thread-in-1] - [localhost]:5801 [seatunnel-674766] [5.1] Connection[id=1, /127.0.0.1:5801->/127.0.0.1:62313, qualifier=null, endpoint=[127.0.0.1]:62313, remoteUuid=eee02313-51dc-4192-ae44-c46913653562, alive=false, connectionType=JVM, planeIndex=-1] closed. Reason: Connection closed by the other side
2024-02-11 22:38:54,254 INFO  [.c.i.c.ClientConnectionManager] [main] - hz.client_1 [seatunnel-674766] [5.1] Removed connection to endpoint: [localhost]:5801:e4163ecd-3cf3-4db2-9757-3f5f1470af0c, connection: ClientConnection{alive=false, connectionId=1, channel=NioChannel{/127.0.0.1:62313->localhost/127.0.0.1:5801}, remoteAddress=[localhost]:5801, lastReadTime=2024-02-11 22:38:54.158, lastWriteTime=2024-02-11 22:38:54.157, closedTime=2024-02-11 22:38:54.253, connected server version=5.1}
2024-02-11 22:38:54,254 INFO  [c.h.c.LifecycleService        ] [main] - hz.client_1 [seatunnel-674766] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is CLIENT_DISCONNECTED
2024-02-11 22:38:54,254 INFO  [c.h.c.i.ClientEndpointManager ] [hz.main.event-4] - [localhost]:5801 [seatunnel-674766] [5.1] Destroying ClientEndpoint{connection=Connection[id=1, /127.0.0.1:5801->/127.0.0.1:62313, qualifier=null, endpoint=[127.0.0.1]:62313, remoteUuid=eee02313-51dc-4192-ae44-c46913653562, alive=false, connectionType=JVM, planeIndex=-1], clientUuid=eee02313-51dc-4192-ae44-c46913653562, clientName=hz.client_1, authenticated=true, clientVersion=5.1, creationTime=1707662334085, latest clientAttributes=lastStatisticsCollectionTime=1707662334097,enterprise=false,clientType=JVM,clientVersion=5.1,clusterConnectionTimestamp=1707662334081,clientAddress=127.0.0.1,clientName=hz.client_1,credentials.principal=null,os.committedVirtualMemorySize=421959991296,os.freePhysicalMemorySize=620003328,os.freeSwapSpaceSize=0,os.maxFileDescriptorCount=10240,os.openFileDescriptorCount=72,os.processCpuTime=2889502000,os.systemLoadAverage=1.76806640625,os.totalPhysicalMemorySize=34359738368,os.totalSwapSpaceSize=0,runtime.availableProcessors=12,runtime.freeMemory=293768104,runtime.maxMemory=477626368,runtime.totalMemory=333447168,runtime.uptime=1861,runtime.usedMemory=39679064, labels=[]}
2024-02-11 22:38:54,255 INFO  [c.h.c.LifecycleService        ] [main] - hz.client_1 [seatunnel-674766] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is SHUTDOWN
2024-02-11 22:38:54,255 INFO  [s.c.s.s.c.ClientExecuteCommand] [main] - Closed SeaTunnel client......
2024-02-11 22:38:54,255 INFO  [c.h.c.LifecycleService        ] [main] - [localhost]:5801 [seatunnel-674766] [5.1] [localhost]:5801 is SHUTTING_DOWN
2024-02-11 22:38:54,256 INFO  [c.h.i.p.i.MigrationManager    ] [hz.main.cached.thread-9] - [localhost]:5801 [seatunnel-674766] [5.1] Shutdown request of Member [localhost]:5801 - e4163ecd-3cf3-4db2-9757-3f5f1470af0c this is handled
2024-02-11 22:38:54,258 INFO  [c.h.i.i.Node                  ] [main] - [localhost]:5801 [seatunnel-674766] [5.1] Shutting down connection manager...
2024-02-11 22:38:54,259 INFO  [c.h.i.i.Node                  ] [main] - [localhost]:5801 [seatunnel-674766] [5.1] Shutting down node engine...
2024-02-11 22:38:57,273 INFO  [c.h.i.i.NodeExtension         ] [main] - [localhost]:5801 [seatunnel-674766] [5.1] Destroying node NodeExtension.
2024-02-11 22:38:57,274 INFO  [c.h.i.i.Node                  ] [main] - [localhost]:5801 [seatunnel-674766] [5.1] Hazelcast Shutdown is completed in 3018 ms.
2024-02-11 22:38:57,275 INFO  [c.h.c.LifecycleService        ] [main] - [localhost]:5801 [seatunnel-674766] [5.1] [localhost]:5801 is SHUTDOWN
2024-02-11 22:38:57,275 INFO  [s.c.s.s.c.ClientExecuteCommand] [main] - Closed HazelcastInstance ......
2024-02-11 22:38:57,275 ERROR [o.a.s.c.s.SeaTunnel           ] [main] -

===============================================================================


2024-02-11 22:38:57,276 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Fatal Error,

2024-02-11 22:38:57,276 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Please submit bug report in https://github.com/apache/seatunnel/issues

2024-02-11 22:38:57,276 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Reason:SeaTunnel job executed failed

2024-02-11 22:38:57,279 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:199)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: java.lang.UnsupportedOperationException: 'MongoDB-CDC' source don't support off-line job.
	at org.apache.seatunnel.core.starter.execution.PluginUtil.ensureJobModeMatch(PluginUtil.java:171)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:330)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:181)
	at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.getLogicalDag(ClientJobExecutionEnvironment.java:88)
	at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.execute(ClientJobExecutionEnvironment.java:161)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:146)
	... 2 more

2024-02-11 22:38:57,279 ERROR [o.a.s.c.s.SeaTunnel           ] [main] -
===============================================================================



Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:199)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: java.lang.UnsupportedOperationException: 'MongoDB-CDC' source don't support off-line job.
	at org.apache.seatunnel.core.starter.execution.PluginUtil.ensureJobModeMatch(PluginUtil.java:171)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:330)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:181)
	at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.getLogicalDag(ClientJobExecutionEnvironment.java:88)
	at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.execute(ClientJobExecutionEnvironment.java:161)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:146)
	... 2 more
```
