### ISSUE TITLE
unable to connect seatunnel with JDBC -Presto connector 

### ISSUE THREAD

**Issue by sanjaychitransh** [apache/seatunnel#5844]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Hi,
 I am trying to connect Presto using mysql catalog as source and sink mysql . I added all the necessary jar files under path /opt/apache-seatunnel-2.3.2/lib. 
 I added  certificate under path /opt/apache-seatunnel-2.3.2/certs/keystore.jks.
But when i am trying run , 
i am getting this error :

2023-11-14 00:18:55,590 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Reason:SeaTunnel job executed failed

2023-11-14 00:18:55,592 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:188)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.connectors.seatunnel.jdbc.exception.JdbcConnectorException: ErrorCode:[JDBC-06], ErrorDescription:[No suitable dialect factory found] - Could not find any jdbc dialect factory that can handle url 'jdbc:presto://xxxxxx.xxx.xxxxxxx.com:8443/mysql.seatunnel?SSL=true&SSLTrustStorePath=/opt/apache-seatunnel-2.3.2/certs/keystore.jks&SSLTrustStorePassword=123456#' that implements 'org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.JdbcDialectFactory' in the classpath.

Available factories are:

org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.db2.DB2DialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.dm.DmdbDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.gbase8a.Gbase8aDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.greenplum.GreenplumDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.mysql.MySqlDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.oracle.OracleDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.phoenix.PhoenixDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.psql.PostgresDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.redshift.RedshiftDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.saphana.SapHanaDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.snowflake.SnowflakeDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.sqlite.SqliteDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.sqlserver.SqlServerDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.tablestore.TablestoreDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.teradata.TeradataDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.vertica.VerticaDialectFactory
        at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.JdbcDialectLoader.load(JdbcDialectLoader.java:65)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.source.JdbcSource.prepare(JdbcSource.java:102)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSource(JobConfigParser.java:81)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:298)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:159)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.getLogicalDag(JobExecutionEnvironment.java:155)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:147)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:140)
        ... 2 more

### SeaTunnel Version

seatunnel-2.3.2

### SeaTunnel Config

```conf
# Defining the runtime environment
env {
  # You can set flink configuration here
  execution.parallelism = 1
  job.mode = "BATCH"
}
source {
  # This is a example source plugin **only for test and demonstrate the feature source plugin**
  jdbc {
        url = "jdbc:presto://xxx.xx.xx.com:8443/mysql.seatunnel?SSL=true&SSLTrustStorePath=/opt/apache-seatunnel-2.3.2/certs/keystore.jks&SSLTrustStorePassword=123456#"
        driver = "com.facebook.presto.jdbc.PrestoDriver"
        user = "padmin"
        password = "Adm1n##"
        query = " SELECT * FROM pet"
        }
  # If you would like to get more information about how to configure seatunnel and see full list of source plugins,
  # please go to https://seatunnel.apache.org/docs/category/source-v2
}

transform {
  # If you would like to get more information about how to configure seatunnel and see full list of transform plugins,
    # please go to https://seatunnel.apache.org/docs/category/transform-v2
}
sink {
    jdbc {
        url = "jdbc:mysql://xxxxxxxxx.xxxx.xx:3306/seasink"
        driver = "com.mysql.cj.jdbc.Driver"
        user = "sanjay"
        password = "password"
        generate_sink_sql = true
        table = pet
        database = seasink

        }
  # If you would like to get more information about how to configure seatunnel and see full list of sink plugins,
  # please go to https://seatunnel.apache.org/docs/category/sink-v2
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/prestojdbc-to-mysqljdbc.conf  -e local
```

### Error Exception

```log
Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:188)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.connectors.seatunnel.jdbc.exception.JdbcConnectorException: ErrorCode:[JDBC-06], ErrorDescription:[No suitable dialect factory found] - Could not find any jdbc dialect factory that can handle url 'jdbc:presto://xxxx.xxx.xxx.com:8443/mysql/seatunnel?SSL=true&SSLTrustStorePath=/opt/apache-seatunnel-2.3.2/certs/keystore.jks&SSLTrustStorePassword=123456#' that implements 'org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.JdbcDialectFactory' in the classpath.
```

### Zeta or Flink or Spark Version

na

### Java or Scala Version

na

### Screenshots

na

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hailin0** [comment]
The current version does not support presto yet

waiting for this pr merge
https://github.com/apache/seatunnel/pull/3774

Are you willing to continue completing this PR?

**Comment by sanjaychitransh** [comment]
Thanks for reply
 > when presto connector is available for v3.2.4? 
>  is there source we backport into v3.2.3?
> please let me know how to completing this PR?

**Comment by Carl-Zhou-CN** [comment]
> Thanks for reply
> 
> > when presto connector is available for v3.2.4?
> > is there source we backport into v3.2.3?
> > please let me know how to completing this PR?

hi，The version differences between them will not have a significant impact on your completion of this PR

**Comment by davidzollo** [comment]
If there is anybody who'd like to implement this feature, please leave a message and then you can submit your PR within four weeks. 

Kind reminder: Other guys can pick it up if the PR is not submitted within four weeks.

Here are some helpful resources to get started:  
- [Contribution Setup Guide](https://seatunnel.apache.org/docs/contribution/setup)  
- [Code Submission Guide](https://seatunnel.apache.org/community/submit_guide/submit-code)  

By the way, since this might be your first contribution, I think we can have a more in-depth communication to help you get familiar with SeaTunnel. Feel free to contact me on LinkedIn ([David Zollo](https://www.linkedin.com/in/davidzollo)) or WeChat ID(davidzollo). When adding me, please let me know your GitHub ID. I'd be happy to assist you!
