### ISSUE TITLE
[Bug] [Zeta] java.lang.NumberFormatException: For input string

### ISSUE THREAD

**Issue by codeDing18** [apache/seatunnel#5881]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When reading and deserializing a data file, it can’t  split based on the delimiter.

### SeaTunnel Version

seatunnel 2.3.3
hive 2.3.9
hadoop3

### SeaTunnel Config

```conf
source {
  
  Hive {
    table_name = "tpch.test2"
    metastore_uri = "thrift://xxx:9083"
    hdfs_site_path = "/usr/local/apache-seatunnel-2.3.3/hadoop_config/hdfs-site.xml"
    hive_site_path = "/usr/local/apache-seatunnel-2.3.3/hadoop_config/hive-site.xml"
    kerberos_principal = "hdfs/xx@TEST"
    kerberos_keytab_path = "/etc/security/keytabs/hdfs.keytab"
  }

sink {

  Doris {
    fenodes = "localhost:8031"
    username = root
    password = "xxx"
    table.identifier = "seatunnel.test2"
    sink.label-prefix = "hive-doris"
    #sink.enable-2pc = "true"
    sink.enable-delete = "true"
    doris.config {
      format = "csv"
      column_separator = ","
    }
  }
```

### Running Command

```shell
bin/seatunnel.sh -c config/hive2doris.config -e local
```

### Error Exception

```log
Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:191)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: org.apache.seatunnel.connectors.seatunnel.file.exception.FileConnectorException: ErrorCode:[COMMON-01], ErrorDescription:[File operation failed, such as (read,list,write,move,copy,sync) etc...] - Read data from this file [hdfs://managed/hiveseatunnel/tpch.db/test2/testcsv.csv] failed
	at org.apache.seatunnel.connectors.seatunnel.file.source.BaseFileSourceReader.pollNext(BaseFileSourceReader.java:70)
	at org.apache.seatunnel.engine.server.task.flow.SourceFlowLifeCycle.collect(SourceFlowLifeCycle.java:150)
	at org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask.collect(SourceSeaTunnelTask.java:95)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTask.stateProcess(SeaTunnelTask.java:168)
	at org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask.call(SourceSeaTunnelTask.java:100)
	at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:613)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.NumberFormatException: For input string: "1,ding"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.apache.seatunnel.format.text.TextDeserializationSchema.convert(TextDeserializationSchema.java:204)
```

### Java or Scala Version

java1.8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Carl-Zhou-CN** [comment]
hi @codeDing18   Can you provide more information, such as ddl of hive table

**Comment by codeDing18** [comment]
> hi @codeDing18 Can you provide more information, such as ddl of hive table



thx for reply.I have solved the problem. Just need add `delimiter="\\|"` to Hive.

**Comment by Carl-Zhou-CN** [comment]
> > hi @codeDing18 Can you provide more information, such as ddl of hive table
> 
> thx for reply.I have solved the problem. Just need add `delimiter="\\|"` to Hive.

Can you elaborate? Because we had a similar problem before

**Comment by Carl-Zhou-CN** [comment]
link #5140

**Comment by codeDing18** [comment]
> > > hi @codeDing18 Can you provide more information, such as ddl of hive table
> > 
> > 
> > thx for reply.I have solved the problem. Just need add `delimiter="\\|"` to Hive.
> 
> Can you elaborate? Because we had a similar problem before

the ddl of hive table is below:
```bash
create table lineitem (
  l_orderkey int,
  l_partkey int,
  l_suppkey int,
  l_linenumber int,
  l_quantity double,
  l_extendedprice double,
  l_discount double,
  l_tax double,
  l_returnflag string,
  l_linestatus string,
  l_shipdate string,
  l_commitdate string,
  l_receiptdate string,
  l_shipinstruct string,
  l_shipmode string,
  l_comment string)
row format delimited
fields terminated by '|'
stored as textfile;
```
the delimiter of the table's data is '|'.So I need to specify the delimiiter in the config.
the seatunnel config is below:
```
source {
  
  Hive {
    table_name = "tpch.linetem"
    metastore_uri = "thrift://xxx:9083"
    hdfs_site_path = "/usr/local/apache-seatunnel-2.3.3/hadoop_config/hdfs-site.xml"
    hive_site_path = "/usr/local/apache-seatunnel-2.3.3/hadoop_config/hive-site.xml"
    kerberos_principal = "hdfs/xx@TEST"
    kerberos_keytab_path = "/etc/security/keytabs/hdfs.keytab"
    delimiter="\\|"
  }

sink {

  Doris {
    fenodes = "localhost:8031"
    username = root
    password = "xxx"
    table.identifier = "seatunnel.test2"
    sink.label-prefix = "hive-doris"
    sink.enable-delete = "true"
    doris.config {
      format="json"
      read_json_by_line="true"
    }
  }
```

**Comment by Carl-Zhou-CN** [comment]
Thank you for your feedback. It seems to be missing the ability to automatically detect the delimiter.

> > > > hi @codeDing18 Can you provide more information, such as ddl of hive table
> > > 
> > > 
> > > thx for reply.I have solved the problem. Just need add `delimiter="\\|"` to Hive.
> > 
> > 
> > Can you elaborate? Because we had a similar problem before
> 
> the ddl of hive table is below:
> 
> ```shell
> create table lineitem (
>   l_orderkey int,
>   l_partkey int,
>   l_suppkey int,
>   l_linenumber int,
>   l_quantity double,
>   l_extendedprice double,
>   l_discount double,
>   l_tax double,
>   l_returnflag string,
>   l_linestatus string,
>   l_shipdate string,
>   l_commitdate string,
>   l_receiptdate string,
>   l_shipinstruct string,
>   l_shipmode string,
>   l_comment string)
> row format delimited
> fields terminated by '|'
> stored as textfile;
> ```
> 
> the delimiter of the table's data is '|'.So I need to specify the delimiiter in the config. the seatunnel config is below:
> 
> ```
> source {
>   
>   Hive {
>     table_name = "tpch.linetem"
>     metastore_uri = "thrift://xxx:9083"
>     hdfs_site_path = "/usr/local/apache-seatunnel-2.3.3/hadoop_config/hdfs-site.xml"
>     hive_site_path = "/usr/local/apache-seatunnel-2.3.3/hadoop_config/hive-site.xml"
>     kerberos_principal = "hdfs/xx@TEST"
>     kerberos_keytab_path = "/etc/security/keytabs/hdfs.keytab"
>     delimiter="\\|"
>   }
> 
> sink {
> 
>   Doris {
>     fenodes = "localhost:8031"
>     username = root
>     password = "xxx"
>     table.identifier = "seatunnel.test2"
>     sink.label-prefix = "hive-doris"
>     sink.enable-delete = "true"
>     doris.config {
>       format="json"
>       read_json_by_line="true"
>     }
>   }
> ```
