### ISSUE TITLE
[Bug] [engine-server] Failed to detect a valid hadoop home directory

### ISSUE THREAD

**Issue by SleeperZLX** [apache/seatunnel#5892]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I followed https://seatunnel.apache.org/docs/2.3.3/contribution/setup to download seatunnel and run it on local machine. Meanwhile, I utilized mongo connector in seatunnel-examples/seatunnel-engine-examples to read mongo data and sink to another mongo collection. However, it showed me error: java.io.FileNotFoundException: java.io.FileNotFoundException: HADOOP_HOME and hadoop.home.dir are unset, while in the setup document hadoop was not necessary. So I want to know how to fix this bug? Install hadoop in my machine(Windows 11)? 

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
just download source code of seatunnel 2.3.3-release from github
```

### Running Command

```shell
Just use IDEA 2022.2 and press "Run" button in the main function of seatunnel-examples\seatunnel-engine-examples\src\main\java\org\apache\seatunnel\example\engine\SeaTunnelEngineExample.java
```

### Error Exception

```log
2023-11-21 21:07:39,433 DEBUG org.apache.hadoop.util.Shell - Failed to find winutils.exe
java.io.FileNotFoundException: java.io.FileNotFoundException: HADOOP_HOME and hadoop.home.dir are unset. -see https://wiki.apache.org/hadoop/WindowsProblems
	at org.apache.hadoop.util.Shell.fileNotFoundException(Shell.java:549) ~[hadoop-common-3.1.4.jar:?]
	at org.apache.hadoop.util.Shell.getHadoopHomeDir(Shell.java:570) ~[hadoop-common-3.1.4.jar:?]
	at org.apache.hadoop.util.Shell.getQualifiedBin(Shell.java:593) ~[hadoop-common-3.1.4.jar:?]
	at org.apache.hadoop.util.Shell.<clinit>(Shell.java:690) ~[hadoop-common-3.1.4.jar:?]
	at org.apache.hadoop.util.StringUtils.<clinit>(StringUtils.java:78) ~[hadoop-common-3.1.4.jar:?]
	at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:3487) ~[hadoop-common-3.1.4.jar:?]
	at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:3482) ~[hadoop-common-3.1.4.jar:?]
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3319) ~[hadoop-common-3.1.4.jar:?]
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:479) ~[hadoop-common-3.1.4.jar:?]
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:227) ~[hadoop-common-3.1.4.jar:?]
	at org.apache.seatunnel.engine.checkpoint.storage.hdfs.HdfsStorage.initStorage(HdfsStorage.java:68) ~[classes/:?]
	at org.apache.seatunnel.engine.checkpoint.storage.hdfs.HdfsStorage.<init>(HdfsStorage.java:57) ~[classes/:?]
	at org.apache.seatunnel.engine.checkpoint.storage.hdfs.common.HdfsFileStorageInstance.getOrCreateStorage(HdfsFileStorageInstance.java:53) ~[classes/:?]
	at org.apache.seatunnel.engine.checkpoint.storage.hdfs.HdfsStorageFactory.create(HdfsStorageFactory.java:75) ~[classes/:?]
	at org.apache.seatunnel.engine.server.checkpoint.CheckpointManager.<init>(CheckpointManager.java:103) ~[classes/:?]
	at org.apache.seatunnel.engine.server.master.JobMaster.initCheckPointManager(JobMaster.java:251) ~[classes/:?]
	at org.apache.seatunnel.engine.server.master.JobMaster.init(JobMaster.java:234) ~[classes/:?]
	at org.apache.seatunnel.engine.server.CoordinatorService.lambda$submitJob$5(CoordinatorService.java:461) ~[classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_341]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_341]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_341]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_341]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_341]
Caused by: java.io.FileNotFoundException: HADOOP_HOME and hadoop.home.dir are unset.
	at org.apache.hadoop.util.Shell.checkHadoopHomeInner(Shell.java:469) ~[hadoop-common-3.1.4.jar:?]
	at org.apache.hadoop.util.Shell.checkHadoopHome(Shell.java:440) ~[hadoop-common-3.1.4.jar:?]
	at org.apache.hadoop.util.Shell.<clinit>(Shell.java:517) ~[hadoop-common-3.1.4.jar:?]
	... 19 more
```

### Java or Scala Version

Java: 1.8.0_341
Scala: 2.11.12

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hu-WF** [comment]
same problem：
![image](https://github.com/apache/seatunnel/assets/30825060/f516616e-adba-4e17-b650-7fdf260adddd)

**Comment by FengSq** [comment]
所以，这个问题修复了吗

**Comment by davidzollo** [comment]
The same issue with https://github.com/apache/seatunnel/issues/8365
