### ISSUE TITLE
Unable to create a source for identifier 'MySQL-CDC'

### ISSUE THREAD

**Issue by hophiya** [apache/seatunnel#5893]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found similar issues:https://github.com/apache/seatunnel/issues/5158. but have no answer.

### What happened

this issue happened when sync data from MySQL to StarRocks,get the error:
org.apache.seatunnel.api.table.factory.FactoryException: ErrorCode:[API-06], ErrorDescription:[Factory initialize failed] - Unable to create a source for identifier 'MySQL-CDC'.
    at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:99)
    at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:329)
    at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:179)
    at org.apache.seatunnel.engine.core.job.AbstractJobEnvironment.getLogicalDag(AbstractJobEnvironment.java:109)
    at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:73)
    at org.apache.seatunnel.app.service.impl.JobExecutorServiceImpl.executeJobBySeaTunnel(JobExecutorServiceImpl.java:109)
    at org.apache.seatunnel.app.service.impl.JobExecutorServiceImpl.jobExecute(JobExecutorServiceImpl.java:74)
    at org.apache.seatunnel.app.controller.JobExecutorController.jobExecutor(JobExecutorController.java:55)
    at sun.reflect.GeneratedMethodAccessor269.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:497)
    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:584)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
    at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1631)
    at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
Parsed config file: {
    "env" : {
        "job.mode" : "STREAMING",
        "job.name" : "SeaTunnel_Job_test"
    },
    "source" : [
        {
            "schema" : {
                "fields" : {
                    "topic" : "string",
                    "key" : "string",
                    "value" : "string"
                }
            },
            "inverse-sampling.rate" : 1000,
            "catalog" : {
                "factory" : "Mysql"
            },
            "parallelism" : 1,
            "table-names" : [
                "db.t1",
                "db.t2"
            ],
            "chunk-key.even-distribution.factor.lower-bound" : 0.05,
            "database-names" : [
                "db"
            ],
            "password" : "xxxxxx",
            "sample-sharding.threshold" : 1000,
            "incremental.parallelism" : 1,
            "snapshot.fetch.size" : 1024,
            "connect.max-retries" : 3,
            "base-url" : "jdbc:mysql://192.169.10:13306",
            "startup.mode" : "INITIAL",
            "format" : "COMPATIBLE_DEBEZIUM_JSON",
            "result_table_name" : "Table11665712358336",
            "server-time-zone" : "CST",
            "plugin_name" : "MySQL-CDC",
            "exactly_once" : "true",
            "connection.pool.size" : 20,
            "snapshot.split.size" : 8096,
            "stop.mode" : "NEVER",
            "chunk-key.even-distribution.factor.upper-bound" : 100,
            "connect.timeout.ms" : 30000,
            "dag-parsing.mode" : "MULTIPLEX",
            "username" : "user1"
        }
    ],
    "transform" : [],
    "sink" : [
        {
            "savemode" : "KEEP_SCHEMA_AND_DATA",
            "base-url" : "jdbc:mysql:loadbalance://192.169.4:9030,192.169.5:9030,192.169.6:9030",
            "source_table_name" : "Table11665712358336",
            "plugin_name" : "StarRocks",
            "enable_upsert_delete" : "false",
            "database" : "db",
            "password" : "xxxxxx",
            "batch_max_rows" : 1024,
            "save_mode_create_template" : "CREATE TABLE IF NOT EXISTS `${database}`.`${table_name}` (\n${rowtype_fields}\n) ENGINE=OLAP\n PRIMARY KEY (${rowtype_primary_key})\nDISTRIBUTED BY HASH (${rowtype_primary_key})PROPERTIES (\n    \"replication_num\" = \"1\" \n)",
            "labelPrefix" : "test",
            "batch_max_bytes" : 5242880,
            "nodeUrls" : [
                "192.169.1:8030",
                "192.169.2:8030",
                "192.169.3:8030"
            ],
            "username" : "syncer"
        }
    ]
}
```

### Running Command

```shell
on web
```

### Error Exception

```log
this issue happened when sync data from MySQL to StarRocks,get the error:
org.apache.seatunnel.api.table.factory.FactoryException: ErrorCode:[API-06], ErrorDescription:[Factory initialize failed] - Unable to create a source for identifier 'MySQL-CDC'.
```

### Zeta or Flink or Spark Version

no

### Java or Scala Version

1.8.0_212

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
@hophiya do you solve this issue? i meet same issue
