### ISSUE TITLE
Read Mongodb Data To Console report bug

### ISSUE THREAD

**Issue by maqw666** [apache/seatunnel#5935]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Read Mongodb Data To Console, first not report bug, 20 mins later begin to report bug.

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
env {
  # You can set SeaTunnel environment configuration here
  execution.parallelism = 2
  job.mode = "BATCH"
}

source {
  MongoDB {
    uri = "mongodb://user:pwd@ip:27017/admin?connectTimeoutMS=10000&authSource=admin"
    database = "**"
    collection = "***"
    partition.split-key = "ID"
    partition.split-size = 1024
    schema = {
      fields {
        ID = string
        publicDate = string
        province = string
        URL = string
        WEBNAME = string
        title = string
        tenderType = string
      }
    }
  }
}

transform {
}

sink {
  Console {
  }
}
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/mongo2console -e local
```

### Error Exception

```log
2023-11-29 14:11:37,648 WARN  org.apache.seatunnel.engine.server.dag.physical.SubPlan - start cancel job Job SeaTunnel_Job (782122236919152641), Pipeline: [(1/1)] count = 9
2023-11-29 14:11:39,648 WARN  org.apache.seatunnel.engine.server.dag.physical.SubPlan - Job SeaTunnel_Job (782122236919152641), Pipeline: [(1/1)] cancel error will retry
com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
	at com.hazelcast.instance.impl.DefaultNodeExtension$1.get(DefaultNodeExtension.java:374) ~[seatunnel-starter.jar:2.3.3]
	at com.hazelcast.instance.impl.DefaultNodeExtension$1.get(DefaultNodeExtension.java:371) ~[seatunnel-starter.jar:2.3.3]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.serializerFor(AbstractSerializationService.java:545) ~[seatunnel-starter.jar:2.3.3]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:227) ~[seatunnel-starter.jar:2.3.3]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:214) ~[seatunnel-starter.jar:2.3.3]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:199) ~[seatunnel-starter.jar:2.3.3]
	at com.hazelcast.map.impl.proxy.MapProxySupport.toDataWithStrategy(MapProxySupport.java:1321) ~[seatunnel-starter.jar:2.3.3]
	at com.hazelcast.map.impl.proxy.MapProxySupport.getInternal(MapProxySupport.java:362) ~[seatunnel-starter.jar:2.3.3]
	at com.hazelcast.map.impl.proxy.MapProxyImpl.get(MapProxyImpl.java:123) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.server.dag.physical.SubPlan.cancelPipeline(SubPlan.java:413) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.server.dag.physical.SubPlan.handleCheckpointError(SubPlan.java:659) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.server.master.JobMaster.lambda$handleCheckpointError$2(JobMaster.java:341) ~[seatunnel-starter.jar:2.3.3]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_181]
	at org.apache.seatunnel.engine.server.master.JobMaster.handleCheckpointError(JobMaster.java:338) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.server.checkpoint.CheckpointManager.handleCheckpointError(CheckpointManager.java:180) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator.handleCoordinatorError(CheckpointCoordinator.java:266) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator.lambda$null$9(CheckpointCoordinator.java:532) ~[seatunnel-starter.jar:2.3.3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
2023-11-29 14:12:39,658 ERROR org.apache.seatunnel.engine.server.dag.physical.SubPlan - Never come here. handle TaskGroupLocation{jobId=782122236919152641, pipelineId=1, taskGroupId=1} FAILED error
java.lang.RuntimeException: Execute given execution failed after retry 30 times
	at org.apache.seatunnel.common.utils.RetryUtils.retryWithException(RetryUtils.java:75) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.server.dag.physical.SubPlan.turnToEndState(SubPlan.java:323) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.server.dag.physical.SubPlan.lambda$addPhysicalVertexCallBack$2(SubPlan.java:206) ~[seatunnel-starter.jar:2.3.3]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) [?:1.8.0_181]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) [?:1.8.0_181]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
	at com.hazelcast.instance.impl.DefaultNodeExtension$1.get(DefaultNodeExtension.java:374) ~[seatunnel-starter.jar:2.3.3]
	at com.hazelcast.instance.impl.DefaultNodeExtension$1.get(DefaultNodeExtension.java:371) ~[seatunnel-starter.jar:2.3.3]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.serializerFor(AbstractSerializationService.java:545) ~[seatunnel-starter.jar:2.3.3]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:227) ~[seatunnel-starter.jar:2.3.3]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:214) ~[seatunnel-starter.jar:2.3.3]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:199) ~[seatunnel-starter.jar:2.3.3]
	at com.hazelcast.map.impl.proxy.MapProxySupport.toDataWithStrategy(MapProxySupport.java:1321) ~[seatunnel-starter.jar:2.3.3]
	at com.hazelcast.map.impl.proxy.MapProxySupport.getInternal(MapProxySupport.java:362) ~[seatunnel-starter.jar:2.3.3]
	at com.hazelcast.map.impl.proxy.MapProxyImpl.get(MapProxyImpl.java:123) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.server.dag.physical.SubPlan.updateStateTimestamps(SubPlan.java:500) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.server.dag.physical.SubPlan.lambda$turnToEndState$5(SubPlan.java:325) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.common.utils.RetryUtils.retryWithException(RetryUtils.java:48) ~[seatunnel-starter.jar:2.3.3]
	... 8 more
2023-11-29 14:12:39,660 INFO  org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand - run shutdown hook because get close signal
2023-11-29 14:12:39,660 WARN  org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand - Task will be closed due to client shutdown.
2023-11-29 14:12:39,662 ERROR org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand - Cancel job failed.
java.util.concurrent.ExecutionException: com.hazelcast.client.HazelcastClientNotActiveException: Client is shutting down
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_181]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915) ~[?:1.8.0_181]
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.lambda$execute$1(ClientExecuteCommand.java:164) ~[seatunnel-starter.jar:2.3.3]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: com.hazelcast.client.HazelcastClientNotActiveException: Client is shutting down
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.notifyExceptionWithOwnedPermission(ClientInvocation.java:316) ~[seatunnel-starter.jar:2.3.3]
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:209) ~[seatunnel-starter.jar:2.3.3]
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.invoke(ClientInvocation.java:156) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.client.SeaTunnelHazelcastClient.requestAndGetCompletableFuture(SeaTunnelHazelcastClient.java:123) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.client.SeaTunnelHazelcastClient.requestOnMasterAndGetCompletableFuture(SeaTunnelHazelcastClient.java:132) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.client.job.ClientJobProxy.cancelJob(ClientJobProxy.java:148) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.shutdownHook(ClientExecuteCommand.java:254) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.lambda$null$0(ClientExecuteCommand.java:161) ~[seatunnel-starter.jar:2.3.3]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[?:1.8.0_181]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618) ~[?:1.8.0_181]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_181]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_181]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_181]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_181]
Caused by: java.io.IOException: No connection found to cluster.
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.checkInvocationAllowed(TcpClientConnectionManager.java:548) ~[seatunnel-starter.jar:2.3.3]
	at com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl.checkInvocationAllowed(ClientInvocationServiceImpl.java:294) ~[seatunnel-starter.jar:2.3.3]
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:178) ~[seatunnel-starter.jar:2.3.3]
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.invoke(ClientInvocation.java:156) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.client.SeaTunnelHazelcastClient.requestAndGetCompletableFuture(SeaTunnelHazelcastClient.java:123) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.client.SeaTunnelHazelcastClient.requestOnMasterAndGetCompletableFuture(SeaTunnelHazelcastClient.java:132) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.client.job.ClientJobProxy.cancelJob(ClientJobProxy.java:148) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.shutdownHook(ClientExecuteCommand.java:254) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.lambda$null$0(ClientExecuteCommand.java:161) ~[seatunnel-starter.jar:2.3.3]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[?:1.8.0_181]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618) ~[?:1.8.0_181]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_181]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_181]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_181]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_181]
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hailin0** [comment]
reference

https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-cdc-mongodb-e2e
