### ISSUE TITLE
[help]  windows quick start 

### ISSUE THREAD

**Issue by jyh129143** [apache/seatunnel#5958]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

开发大大们好，我从官网下载的bin包，版本是2-3-3.由于我用的是windows系统，我下载了Cygwin64运行sh命令。Cgywin和java环境变量都配了，依赖安装的命令：sh bin/install-plugin.sh 2.3.3也运行了。但是运行启动命令的时候报错了，麻烦帮看下原因呢，辛苦各位开发大大

### SeaTunnel Version

2-3-3

### SeaTunnel Config

```conf
env {
  # You can set SeaTunnel environment configuration here
  execution.parallelism = 2
  job.mode = "BATCH"
  checkpoint.interval = 10000
  #execution.checkpoint.interval = 10000
  #execution.checkpoint.data-uri = "hdfs://localhost:9000/checkpoint"
}

source {
  # This is a example source plugin **only for test and demonstrate the feature source plugin**
  FakeSource {
    parallelism = 2
    result_table_name = "fake"
    row.num = 16
    schema = {
      fields {
        name = "string"
        age = "int"
      }
    }
  }

  # If you would like to get more information about how to configure SeaTunnel and see full list of source plugins,
  # please go to https://seatunnel.apache.org/docs/category/source-v2
}

transform {
  FieldMapper {
    source_table_name = "fake"
    result_table_name = "fake1"
    field_mapper = {
      age = age
      name = new_name
    }
  }
}

sink {
  Console {
    source_table_name = "fake1"
  }

  # If you would like to get more information about how to configure SeaTunnel and see full list of sink plugins,
  # please go to https://seatunnel.apache.org/docs/category/sink-v2
}
```

### Running Command

```shell
sh bin/install-plugin.sh 2.3.3

./bin/seatunnel.sh --config ./config/v2.batch.config.template -e local
```

### Error Exception

```log
找不到或无法加载主类 org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
for windows, you can try to use `seatunnel.cmd`

**Comment by jyh129143** [comment]
sorry,could you tell me where to get file:seatunnel.cmd?Or how can I generate it?

**Comment by liunaijie** [comment]
> sorry,could you tell me where to get file:seatunnel.cmd?Or how can I generate it?

oh, sorry. i just realize the `cmd` file is not in release package. 
For your issue, you can modify the `seatunnel.sh`  file, change the final command from `java xxx` to `echo "java xxx"` and verify by yourself. check is the jar location and the jar name is correct.

the correct command shoule like:
```
java ....
-cp ... 
..../starter/seatunnel-starter.jar org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient
-c ...
-e local

```

**Comment by jyh129143** [comment]
I changed the last command to "echo java ${JAVA_OPTS} -cp ${CLASS_PATH} ${APP_MAIN} ${args}"，and the console print:

java -Dhazelcast.client.config=/cygdrive/e/file/apache-seatunnel-2.3.3/config/hazelcast-client.yaml -Dseatunnel.config=/cygdrive/e/file/apache-seatunnel-2.3.3/config/seatunnel.yaml -Dhazelcast.config=/cygdrive/e/file/apache-seatunne
l-2.3.3/config/hazelcast.yaml -Dlog4j2.configurationFile=/cygdrive/e/file/apache-seatunnel-2.3.3/config/log4j2_client.properties -Dseatunnel.logs.path=/cygdrive/e/file/apache-seatunnel-2.3.3/logs -Dseatunnel.logs.file_name=seatunnel
-starter-client-1701681188161 -Xms1g -Xmx1g -XX:+HeapDumpOnOutOfMemoryError -cp /cygdrive/e/file/apache-seatunnel-2.3.3/lib/*:/cygdrive/e/file/apache-seatunnel-2.3.3/starter/seatunnel-starter.jar org.apache.seatunnel.core.starter.se
atunnel.SeaTunnelClient --config ./config/v2.batch.config.template -e local

I think the server dosen't run success,but there is no error message

**Comment by yanhan-chan** [comment]
> > sorry,could you tell me where to get file:seatunnel.cmd?Or how can I generate it?
> 
> oh, sorry. i just realize the `cmd` file is not in release package. For your issue, you can modify the `seatunnel.sh` file, change the final command from `java xxx` to `echo "java xxx"` and verify by yourself. check is the jar location and the jar name is correct.
> 
> the correct command shoule like:
> 
> ```
> java ....
> -cp ... 
> ..../starter/seatunnel-starter.jar org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient
> -c ...
> -e local
> ```

Hi i got the same error as the author of this issue, and followed your steps to echo, and this is what i got:

java  -Dhazelcast.client.config=/c/Users/User/Learn-Apache-SeaTunnel/apache-seatunnel-2.3.3/config/hazelcast-client.yaml -Dseatunnel.config=/c/Users/User/Learn-Apache-SeaTunnel/apache-seatunnel-2.3.3/config/seatunnel.yaml -Dhazelcast.config=/c/Users/User/Learn-Apache-SeaTunnel/apache-seatunnel-2.3.3/config/hazelcast.yaml -Dlog4j2.configurationFile=/c/Users/User/Learn-Apache-SeaTunnel/apache-seatunnel-2.3.3/config/log4j2_client.properties -Dseatunnel.logs.path=/c/Users/User/Learn-Apache-SeaTunnel/apache-seatunnel-2.3.3/logs -Dseatunnel.logs.file_name=seatunnel-starter-client-1702522666344 -Xms1g -Xmx1g -XX:+HeapDumpOnOutOfMemoryError -cp /c/Users/User/Learn-Apache-SeaTunnel/apache-seatunnel-2.3.3/lib/*:/c/Users/User/Learn-Apache-SeaTunnel/apache-seatunnel-2.3.3/starter/seatunnel-starter.jar org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient --config ./config/v2.batch.config.template -e local

This was the error i encountered for your reference:
<img width="582" alt="Screenshot 2023-12-14 111303" src="https://github.com/apache/seatunnel/assets/112475120/f5d3528b-61d6-48c8-b433-d2f64fb38461">

**Comment by jyh129143** [comment]
The key word "echo" just show you the entire command to judge if there are some error with command param,it doesn't help to run the code.Actually I find another way to run the project.First,git clone the project code (not bin.tar.gz),and then follow this:
https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/setup.md

**Comment by yanhan-chan** [comment]
> The key word "echo" just show you the entire command to judge if there are some error with command param,it doesn't help to run the code.Actually I find another way to run the project.First,git clone the project code (not bin.tar.gz),and then follow this: https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/setup.md

Thank you for the quick response and the help, will try it soon.

**Comment by yanhan-chan** [comment]
Hi, does this example only runs for FakeSource and Console as sink, I was trying to use the LocalFile connector as sink, but it is not working, below is the code for the fake_to_console.conf file, a screenshot of the directories and lastly the console output when i run SeaTunnelApiExample.java file

`
env {
  job.mode = "BATCH"
  execution.parallelism = 2
}

source {
  LocalFile {
    path = "/local_csv.csv"
    file_format_type = "csv"
  }

}

transform {

}

sink {
  Console {

  }
}
`

Directory:
<img width="304" alt="image" src="https://github.com/apache/seatunnel/assets/112475120/f368140c-e6a5-4b3d-9407-ae983ac36ac9">


Console Output:
2023-12-18 11:43:47,590 ERROR org.apache.seatunnel.core.starter.SeaTunnel - 

===============================================================================


2023-12-18 11:43:47,590 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Fatal Error, 

2023-12-18 11:43:47,590 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Please submit bug report in https://github.com/apache/seatunnel/issues

2023-12-18 11:43:47,590 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Reason:Plugin PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='LocalFile'} not found. 

2023-12-18 11:43:47,592 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Exception StackTrace:java.lang.RuntimeException: Plugin PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='LocalFile'} not found.
	at org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery.createPluginInstance(AbstractPluginDiscovery.java:231)
	at org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery.createPluginInstance(AbstractPluginDiscovery.java:171)
	at org.apache.seatunnel.core.starter.execution.PluginUtil.fallbackCreate(PluginUtil.java:128)
	at org.apache.seatunnel.core.starter.execution.PluginUtil.createSource(PluginUtil.java:77)
	at org.apache.seatunnel.core.starter.flink.execution.SourceExecuteProcessor.initializePlugins(SourceExecuteProcessor.java:118)
	at org.apache.seatunnel.core.starter.flink.execution.FlinkAbstractPluginExecuteProcessor.<init>(FlinkAbstractPluginExecuteProcessor.java:76)
	at org.apache.seatunnel.core.starter.flink.execution.SourceExecuteProcessor.<init>(SourceExecuteProcessor.java:61)
	at org.apache.seatunnel.core.starter.flink.execution.FlinkExecution.<init>(FlinkExecution.java:86)
	at org.apache.seatunnel.core.starter.flink.command.FlinkTaskExecuteCommand.execute(FlinkTaskExecuteCommand.java:59)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.example.flink.v2.SeaTunnelApiExample.main(SeaTunnelApiExample.java:39)
 
2023-12-18 11:43:47,592 ERROR org.apache.seatunnel.core.starter.SeaTunnel - 

===============================================================================



Exception in thread "main" java.lang.RuntimeException: Plugin PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='LocalFile'} not found.
	at org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery.createPluginInstance(AbstractPluginDiscovery.java:231)
	at org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery.createPluginInstance(AbstractPluginDiscovery.java:171)
	at org.apache.seatunnel.core.starter.execution.PluginUtil.fallbackCreate(PluginUtil.java:128)
	at org.apache.seatunnel.core.starter.execution.PluginUtil.createSource(PluginUtil.java:77)
	at org.apache.seatunnel.core.starter.flink.execution.SourceExecuteProcessor.initializePlugins(SourceExecuteProcessor.java:118)
	at org.apache.seatunnel.core.starter.flink.execution.FlinkAbstractPluginExecuteProcessor.<init>(FlinkAbstractPluginExecuteProcessor.java:76)
	at org.apache.seatunnel.core.starter.flink.execution.SourceExecuteProcessor.<init>(SourceExecuteProcessor.java:61)
	at org.apache.seatunnel.core.starter.flink.execution.FlinkExecution.<init>(FlinkExecution.java:86)
	at org.apache.seatunnel.core.starter.flink.command.FlinkTaskExecuteCommand.execute(FlinkTaskExecuteCommand.java:59)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.example.flink.v2.SeaTunnelApiExample.main(SeaTunnelApiExample.java:39)

**Comment by Carl-Zhou-CN** [comment]
<dependency>
            <groupId>org.apache.seatunnel</groupId>
            <artifactId>connector-file-local</artifactId>
            <version>${project.version}</version>
        </dependency>
@yanhan-chan  hi, you need to add this dependency in the pom

**Comment by yanhan-chan** [comment]
<img width="899" alt="image" src="https://github.com/apache/seatunnel/assets/112475120/af95b1f8-c0ab-46c4-97ff-7cbd0afb9981">
@Carl-Zhou-CN  Hi, I have added it in the pom.xml, however this time i got this error: 

I have also added this as i saw a similar error on the other post:
<img width="303" alt="image" src="https://github.com/apache/seatunnel/assets/112475120/430f6a80-f1aa-462f-ab97-9e395bddc0d7">


org.apache.seatunnel.example.flink.v2.SeaTunnelApiExample

2024-01-03 12:39:20,203 INFO  org.apache.seatunnel.core.starter.utils.ConfigBuilder - Loading config file from path: /home/yanhan/SeaTunnel-Dev/seatunnel-dev/seatunnel-examples/seatunnel-flink-connector-v2-example/target/classes/examples/local_csv_to_console.conf
2024-01-03 12:39:20,242 INFO  org.apache.seatunnel.core.starter.utils.ConfigShadeUtils - Load config shade spi: [base64]
2024-01-03 12:39:20,569 INFO  org.apache.seatunnel.core.starter.utils.ConfigBuilder - Parsed config file: 
{
    "env" : {
        "execution.parallelism" : 2,
        "job.mode" : "BATCH",
        "checkpoint.interval" : 10000
    },
    "source" : [
        {
            "schema" : {
                "fields" : {
                    "name" : "string",
                    "age" : "int"
                }
            },
            "path" : "src/main/resources/sample_local_resources/local_csv.csv",
            "file_format_type" : "csv",
            "plugin_name" : "LocalFile"
        }
    ],
    "sink" : [
        {
            "plugin_name" : "Console"
        }
    ]
}

2024-01-03 12:39:20,619 INFO  org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery - Load SeaTunnelSource Plugin from /home/yanhan/SeaTunnel-Dev/seatunnel-dev/seatunnel-common/connectors
2024-01-03 12:39:20,620 INFO  org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery - Load Factory Plugin from /home/yanhan/SeaTunnel-Dev/seatunnel-dev/seatunnel-common/connectors
2024-01-03 12:39:20,645 INFO  org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery - Load plugin: PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='LocalFile'} from classpath
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/fs/FSDataInputStream
	at org.apache.seatunnel.connectors.seatunnel.file.config.FileFormat$1.getReadStrategy(FileFormat.java:46)
	at org.apache.seatunnel.connectors.seatunnel.file.source.reader.ReadStrategyFactory.of(ReadStrategyFactory.java:45)
	at org.apache.seatunnel.connectors.seatunnel.file.source.reader.ReadStrategyFactory.of(ReadStrategyFactory.java:36)
	at org.apache.seatunnel.connectors.seatunnel.file.config.BaseFileSourceConfig.<init>(BaseFileSourceConfig.java:63)
	at org.apache.seatunnel.connectors.seatunnel.file.local.source.config.LocalFileSourceConfig.<init>(LocalFileSourceConfig.java:44)
	at org.apache.seatunnel.connectors.seatunnel.file.local.source.config.MultipleTableLocalFileSourceConfig.getBaseSourceConfig(MultipleTableLocalFileSourceConfig.java:32)
	at org.apache.seatunnel.connectors.seatunnel.file.config.BaseMultipleTableFileSourceConfig.parseFromFileSourceConfig(BaseMultipleTableFileSourceConfig.java:54)
	at org.apache.seatunnel.connectors.seatunnel.file.config.BaseMultipleTableFileSourceConfig.<init>(BaseMultipleTableFileSourceConfig.java:39)
	at org.apache.seatunnel.connectors.seatunnel.file.local.source.config.MultipleTableLocalFileSourceConfig.<init>(MultipleTableLocalFileSourceConfig.java:27)
	at org.apache.seatunnel.connectors.seatunnel.file.local.source.LocalFileSource.<init>(LocalFileSource.java:28)
	at org.apache.seatunnel.connectors.seatunnel.file.local.source.LocalFileSourceFactory.lambda$createSource$0(LocalFileSourceFactory.java:47)
	at org.apache.seatunnel.core.starter.execution.PluginUtil.createSource(PluginUtil.java:85)
	at org.apache.seatunnel.core.starter.flink.execution.SourceExecuteProcessor.initializePlugins(SourceExecuteProcessor.java:118)
	at org.apache.seatunnel.core.starter.flink.execution.FlinkAbstractPluginExecuteProcessor.<init>(FlinkAbstractPluginExecuteProcessor.java:76)
	at org.apache.seatunnel.core.starter.flink.execution.SourceExecuteProcessor.<init>(SourceExecuteProcessor.java:61)
	at org.apache.seatunnel.core.starter.flink.execution.FlinkExecution.<init>(FlinkExecution.java:91)
	at org.apache.seatunnel.core.starter.flink.command.FlinkTaskExecuteCommand.execute(FlinkTaskExecuteCommand.java:59)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.example.flink.v2.SeaTunnelApiExample.main(SeaTunnelApiExample.java:39)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.fs.FSDataInputStream
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 19 more

Process finished with exit code 1

<img width="865" alt="image" src="https://github.com/apache/seatunnel/assets/112475120/56ab5537-3f7d-47d3-9134-744d90ad99a6">

**Comment by Carl-Zhou-CN** [comment]
<dependency>
            <groupId>org.apache.seatunnel</groupId>
            <artifactId>seatunnel-hadoop3-3.1.4-uber</artifactId>
            <version>${project.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.avro</groupId>
                    <artifactId>avro</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by yanhan-chan** [comment]
@Carl-Zhou-CN Thank you so much, it worked now.

**Comment by yanhan-chan** [comment]
@Carl-Zhou-CN Hi, I am trying to read data from my local mysql database using the jdbc connector. Here is the .conf file:
<img width="365" alt="image" src="https://github.com/apache/seatunnel/assets/112475120/f695c166-1692-46e7-8f3f-d1a1a311c910">

Then i got this error:
2024-01-15 11:10:46,070 INFO  org.apache.seatunnel.core.starter.utils.ConfigBuilder - Loading config file from path: /home/yanhan/SeaTunnel-Dev/seatunnel-dev/seatunnel-examples/seatunnel-flink-connector-v2-example/target/classes/examples/mysql_to_local.conf
2024-01-15 11:10:46,128 INFO  org.apache.seatunnel.core.starter.utils.ConfigShadeUtils - Load config shade spi: [base64]
2024-01-15 11:10:46,251 INFO  org.apache.seatunnel.core.starter.utils.ConfigBuilder - Parsed config file: 
{
    "env" : {
        "execution.parallelism" : 1,
        "job.mode" : "BATCH",
        "checkpoint.interval" : 10000
    },
    "source" : [
        {
            "password" : "yanhan123#",
            "driver" : "com.mysql.cj.jdbc.Driver",
            "query" : "select * from test_seatunnel",
            "connection_check_timeout_sec" : 100,
            "plugin_name" : "jdbc",
            "user" : "root",
            "url" : "jdbc:mysql://localhost:3306/?user=root"
        }
    ],
    "sink" : [
        {
            "plugin_name" : "Console"
        }
    ]
}

2024-01-15 11:10:46,281 INFO  org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery - Load SeaTunnelSource Plugin from /home/yanhan/SeaTunnel-Dev/seatunnel-dev/seatunnel-common/connectors
2024-01-15 11:10:46,282 INFO  org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery - Load Factory Plugin from /home/yanhan/SeaTunnel-Dev/seatunnel-dev/seatunnel-common/connectors
2024-01-15 11:10:46,309 INFO  org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery - Load plugin: PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='jdbc'} from classpath
2024-01-15 11:10:46,360 INFO  org.apache.seatunnel.connectors.seatunnel.jdbc.utils.JdbcCatalogUtils - Loading catalog tables for catalog : class org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.mysql.MySqlCatalog
2024-01-15 11:10:46,366 INFO  org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.AbstractJdbcCatalog - Catalog MySQL closing
2024-01-15 11:10:46,367 ERROR org.apache.seatunnel.core.starter.SeaTunnel - 

===============================================================================


2024-01-15 11:10:46,368 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Fatal Error, 

2024-01-15 11:10:46,368 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Please submit bug report in https://github.com/apache/seatunnel/issues

2024-01-15 11:10:46,368 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Reason:ErrorCode:[API-03], ErrorDescription:[Catalog initialize failed] - Failed connecting to jdbc:mysql://localhost:3306/?user=root via JDBC. 

2024-01-15 11:10:46,370 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Exception StackTrace:org.apache.seatunnel.api.table.catalog.exception.CatalogException: ErrorCode:[API-03], ErrorDescription:[Catalog initialize failed] - Failed connecting to jdbc:mysql://localhost:3306/?user=root via JDBC.
	at org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.AbstractJdbcCatalog.getConnection(AbstractJdbcCatalog.java:121)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.AbstractJdbcCatalog.open(AbstractJdbcCatalog.java:127)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.utils.JdbcCatalogUtils.getTables(JdbcCatalogUtils.java:78)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.source.JdbcSource.<init>(JdbcSource.java:57)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.source.JdbcSourceFactory.lambda$createSource$0(JdbcSourceFactory.java:78)
	at org.apache.seatunnel.core.starter.execution.PluginUtil.createSource(PluginUtil.java:85)
	at org.apache.seatunnel.core.starter.flink.execution.SourceExecuteProcessor.initializePlugins(SourceExecuteProcessor.java:118)
	at org.apache.seatunnel.core.starter.flink.execution.FlinkAbstractPluginExecuteProcessor.<init>(FlinkAbstractPluginExecuteProcessor.java:76)
	at org.apache.seatunnel.core.starter.flink.execution.SourceExecuteProcessor.<init>(SourceExecuteProcessor.java:61)
	at org.apache.seatunnel.core.starter.flink.execution.FlinkExecution.<init>(FlinkExecution.java:91)
	at org.apache.seatunnel.core.starter.flink.command.FlinkTaskExecuteCommand.execute(FlinkTaskExecuteCommand.java:59)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.example.flink.v2.SeaTunnelApiExample.main(SeaTunnelApiExample.java:39)
Caused by: java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306/?user=root
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:708)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.AbstractJdbcCatalog.getConnection(AbstractJdbcCatalog.java:117)
	... 12 more
 
2024-01-15 11:10:46,370 ERROR org.apache.seatunnel.core.starter.SeaTunnel - 
===============================================================================



Exception in thread "main" org.apache.seatunnel.api.table.catalog.exception.CatalogException: ErrorCode:[API-03], ErrorDescription:[Catalog initialize failed] - Failed connecting to jdbc:mysql://localhost:3306/?user=root via JDBC.
	at org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.AbstractJdbcCatalog.getConnection(AbstractJdbcCatalog.java:121)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.AbstractJdbcCatalog.open(AbstractJdbcCatalog.java:127)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.utils.JdbcCatalogUtils.getTables(JdbcCatalogUtils.java:78)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.source.JdbcSource.<init>(JdbcSource.java:57)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.source.JdbcSourceFactory.lambda$createSource$0(JdbcSourceFactory.java:78)
	at org.apache.seatunnel.core.starter.execution.PluginUtil.createSource(PluginUtil.java:85)
	at org.apache.seatunnel.core.starter.flink.execution.SourceExecuteProcessor.initializePlugins(SourceExecuteProcessor.java:118)
	at org.apache.seatunnel.core.starter.flink.execution.FlinkAbstractPluginExecuteProcessor.<init>(FlinkAbstractPluginExecuteProcessor.java:76)
	at org.apache.seatunnel.core.starter.flink.execution.SourceExecuteProcessor.<init>(SourceExecuteProcessor.java:61)
	at org.apache.seatunnel.core.starter.flink.execution.FlinkExecution.<init>(FlinkExecution.java:91)
	at org.apache.seatunnel.core.starter.flink.command.FlinkTaskExecuteCommand.execute(FlinkTaskExecuteCommand.java:59)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.example.flink.v2.SeaTunnelApiExample.main(SeaTunnelApiExample.java:39)
Caused by: java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306/?user=root
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:708)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.AbstractJdbcCatalog.getConnection(AbstractJdbcCatalog.java:117)
	... 12 more


I went to this link: https://mvnrepository.com/artifact/mysql/mysql-connector-java/8.0.27 and downloaded the respective jar file, and place it into this directory: 
<img width="354" alt="image" src="https://github.com/apache/seatunnel/assets/112475120/4a30bb79-6203-4483-8e6f-badf1cd0c286">

Then I have also added the dependency in the pom.xml this way: 
<img width="732" alt="image" src="https://github.com/apache/seatunnel/assets/112475120/450035d2-1dad-49a8-80b7-db689779c321">

I am not sure if i am doing all of this right or not. Can you provide some help? Thank you.

**Comment by sheng-jie** [comment]
Just add mysql dependency in pom 
```

        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.27</version>
        </dependency>
```
