### ISSUE TITLE
hdfs to elasticsearch report error

### ISSUE THREAD

**Issue by maqw666** [apache/seatunnel#6001]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Error in exporting data from HDFS to Elasticsearch: One of the fields in Hive is array<double>, which was imported into ES. Previously, there was an issue with the type, but now there is an issue with reading files. It's really strange. Who can help solve this problem.

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
env {
  # You can set SeaTunnel environment configuration here
  execution.parallelism = 50
  job.mode = "BATCH"
  checkpoint.interval = 3000000
  #execution.checkpoint.interval = 10000
  #execution.checkpoint.data-uri = "hdfs://localhost:9000/checkpoint"
}



source {
  HdfsFile {
  read_columns = ["nameid","uncid","ent_lon_lat"]
  path = "/***/dt=2023-12-11"
  file_format_type = "orc"
  fs.defaultFS = "hdfs://***:8020"
  result_table_name = "t1"
  }
}

transform {
  Sql {
   source_table_name = "t1"
   query = "select nameid,uncid,ent_lon_lat from t1"
  }
}

sink {
    Elasticsearch {
        hosts = ["http://***:9200"]
        index = "seatunnel_test2"
        primary_keys = ["nameid"]
        username = "elastic"
        password = "***"
    }
}
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/hdfs2es3 -e local
```

### Error Exception

```log
2023-12-13 11:14:01,899 INFO  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-319543] [5.1] taskDone, taskId = 50000, taskGroup = TaskGroupLocation{jobId=787155202393243649, pipelineId=1, taskGroupId=30000}
2023-12-13 11:14:01,901 WARN  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5801 [seatunnel-319543] [5.1] Exception in org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask@77a9178d
org.apache.seatunnel.connectors.seatunnel.file.exception.FileConnectorException: ErrorCode:[COMMON-01], ErrorDescription:[File operation failed, such as (read,list,write,move,copy,sync) etc...] - Read data from this file [hdfs://master03:8020/user/hive/warehouse/dw/mid_enterprise_info_new/dt=2023-12-11/000050_0] failed
	at org.apache.seatunnel.connectors.seatunnel.file.source.BaseFileSourceReader.pollNext(BaseFileSourceReader.java:70) ~[connector-file-hadoop-2.3.3.jar:2.3.3]
	at org.apache.seatunnel.engine.server.task.flow.SourceFlowLifeCycle.collect(SourceFlowLifeCycle.java:150) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask.collect(SourceSeaTunnelTask.java:95) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.server.task.SeaTunnelTask.stateProcess(SeaTunnelTask.java:168) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask.call(SourceSeaTunnelTask.java:100) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:613) [seatunnel-starter.jar:2.3.3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.seatunnel.engine.server.task.group.queue.IntermediateBlockingQueue.received(IntermediateBlockingQueue.java:41) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.server.task.flow.IntermediateQueueFlowLifeCycle.received(IntermediateQueueFlowLifeCycle.java:46) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.server.task.flow.IntermediateQueueFlowLifeCycle.received(IntermediateQueueFlowLifeCycle.java:28) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:39) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:27) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.server.task.flow.TransformFlowLifeCycle.received(TransformFlowLifeCycle.java:105) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.server.task.flow.TransformFlowLifeCycle.received(TransformFlowLifeCycle.java:37) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.server.task.SeaTunnelSourceCollector.sendRecordToNext(SeaTunnelSourceCollector.java:139) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.server.task.SeaTunnelSourceCollector.collect(SeaTunnelSourceCollector.java:67) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.connectors.seatunnel.file.source.reader.OrcReadStrategy.read(OrcReadStrategy.java:123) ~[connector-file-hadoop-2.3.3.jar:2.3.3]
	at org.apache.seatunnel.connectors.seatunnel.file.source.BaseFileSourceReader.pollNext(BaseFileSourceReader.java:66) ~[connector-file-hadoop-2.3.3.jar:2.3.3]
	... 10 more
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_181]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_181]
	at java.util.concurrent.ArrayBlockingQueue.put(ArrayBlockingQueue.java:353) ~[?:1.8.0_181]
	at org.apache.seatunnel.engine.server.task.group.queue.IntermediateBlockingQueue.handleRecord(IntermediateBlockingQueue.java:76) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.server.task.group.queue.IntermediateBlockingQueue.received(IntermediateBlockingQueue.java:39) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.server.task.flow.IntermediateQueueFlowLifeCycle.received(IntermediateQueueFlowLifeCycle.java:46) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.server.task.flow.IntermediateQueueFlowLifeCycle.received(IntermediateQueueFlowLifeCycle.java:28) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:39) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:27) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.server.task.flow.TransformFlowLifeCycle.received(TransformFlowLifeCycle.java:105) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.server.task.flow.TransformFlowLifeCycle.received(TransformFlowLifeCycle.java:37) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.server.task.SeaTunnelSourceCollector.sendRecordToNext(SeaTunnelSourceCollector.java:139) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.server.task.SeaTunnelSourceCollector.collect(SeaTunnelSourceCollector.java:67) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.connectors.seatunnel.file.source.reader.OrcReadStrategy.read(OrcReadStrategy.java:123) ~[connector-file-hadoop-2.3.3.jar:2.3.3]
	at org.apache.seatunnel.connectors.seatunnel.file.source.BaseFileSourceReader.pollNext(BaseFileSourceReader.java:66) ~[connector-file-hadoop-2.3.3.jar:2.3.3]
	... 10 more
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Carl-Zhou-CN** [comment]
@maqw666 You can try the dev branch because it may have been fixed?
