### ISSUE TITLE
[Bug] [SQL Server CDC] db name include point startup err

### ISSUE THREAD

**Issue by liuxinwang** [apache/seatunnel#6045]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

sqlserver cdc startup failed

sql server driver version: mssql-jdbc-7.4.1.jre8.jar

### SeaTunnel Version

apache-seatunnel-2.3.3

### SeaTunnel Config

```conf
env {
  # You can set flink configuration here
  execution.parallelism = 2
  job.mode = "STREAMING"
  #checkpoint.interval = 2000
  execution.checkpoint.interval = 10000
  #execution.checkpoint.data-uri = "hdfs://localhost:9000/checkpoint"
}

source {
  SqlServer-CDC {
    exactly_once=true
    startup.mode="latest"
    result_table_name = "tb1" 
    username = "test"
    password = "test"
    database-names = ["test.test.test"]
    table-names = ["test.test.test.dbo.tb1"]
    base-url="jdbc:sqlserver://127.0.0.1:1433;databaseName=test.test.test;trustServerCertificate=false"
  }
}

sink {
  Console {
  }
}
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/v2.streaming.conf2 -e local
```

### Error Exception

```log
2023-12-20 16:58:32,574 WARN  org.apache.seatunnel.connectors.seatunnel.cdc.sqlserver.source.utils.TableDiscoveryUtils -         skipping database 'test.test.test' due to error reading tables: 对象 名称 'test.test.test.INFORMATION_SCHEMA.TABLES' 包含的前缀超出了最大限值。最多只能有 3 个。
2023-12-20 16:58:32,595 INFO  io.debezium.jdbc.JdbcConnection - Connection gracefully closed
2023-12-20 16:58:32,595 INFO  com.hazelcast.core.LifecycleService - hz.client_1 [seatunnel-374530] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is SHUTTING_DOWN
2023-12-20 16:58:32,598 INFO  com.hazelcast.internal.server.tcp.TcpServerConnection - [localhost]:5801 [seatunnel-374530] [5.1] Connection[id=1, /127.0.0.1:5801->/127.0.0.1:43511, qualifier=null, endpoint=[127.0.0.1]:43511, remoteUuid=b1ce735b-fcd0-4e71-92d8-cbef947062db, alive=false, connectionType=JVM, planeIndex=-1] closed. Reason: Connection closed by the other side
2023-12-20 16:58:32,598 INFO  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-374530] [5.1] Removed connection to endpoint: [localhost]:5801:5ad51840-aa03-47d3-89d8-a4a50a2cf761, connection: ClientConnection{alive=false, connectionId=1, channel=NioChannel{/127.0.0.1:43511->localhost/127.0.0.1:5801}, remoteAddress=[localhost]:5801, lastReadTime=2023-12-20 16:58:32.308, lastWriteTime=2023-12-20 16:58:31.590, closedTime=2023-12-20 16:58:32.596, connected server version=5.1}
2023-12-20 16:58:32,599 INFO  com.hazelcast.core.LifecycleService - hz.client_1 [seatunnel-374530] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is CLIENT_DISCONNECTED
2023-12-20 16:58:32,600 INFO  com.hazelcast.client.impl.ClientEndpointManager - [localhost]:5801 [seatunnel-374530] [5.1] Destroying ClientEndpoint{connection=Connection[id=1, /127.0.0.1:5801->/127.0.0.1:43511, qualifier=null, endpoint=[127.0.0.1]:43511, remoteUuid=b1ce735b-fcd0-4e71-92d8-cbef947062db, alive=false, connectionType=JVM, planeIndex=-1], clientUuid=b1ce735b-fcd0-4e71-92d8-cbef947062db, clientName=hz.client_1, authenticated=true, clientVersion=5.1, creationTime=1703062711432, latest clientAttributes=lastStatisticsCollectionTime=1703062711460,enterprise=false,clientType=JVM,clientVersion=5.1,clusterConnectionTimestamp=1703062711376,clientAddress=127.0.0.1,clientName=hz.client_1,credentials.principal=null,os.committedVirtualMemorySize=4987117568,os.freePhysicalMemorySize=3768573952,os.freeSwapSpaceSize=0,os.maxFileDescriptorCount=65536,os.openFileDescriptorCount=52,os.processCpuTime=6500000000,os.systemLoadAverage=0.84,os.totalPhysicalMemorySize=16221048832,os.totalSwapSpaceSize=0,runtime.availableProcessors=4,runtime.freeMemory=977334240,runtime.maxMemory=1029177344,runtime.totalMemory=1029177344,runtime.uptime=3066,runtime.usedMemory=51843104, labels=[]}
2023-12-20 16:58:32,601 INFO  com.hazelcast.core.LifecycleService - hz.client_1 [seatunnel-374530] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is SHUTDOWN
2023-12-20 16:58:32,601 INFO  org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand - Closed SeaTunnel client......
2023-12-20 16:58:32,602 INFO  com.hazelcast.core.LifecycleService - [localhost]:5801 [seatunnel-374530] [5.1] [localhost]:5801 is SHUTTING_DOWN
2023-12-20 16:58:32,605 INFO  com.hazelcast.internal.partition.impl.MigrationManager - [localhost]:5801 [seatunnel-374530] [5.1] Shutdown request of Member [localhost]:5801 - 5ad51840-aa03-47d3-89d8-a4a50a2cf761 this is handled
2023-12-20 16:58:32,610 INFO  com.hazelcast.instance.impl.Node - [localhost]:5801 [seatunnel-374530] [5.1] Shutting down connection manager...
2023-12-20 16:58:32,611 INFO  com.hazelcast.instance.impl.Node - [localhost]:5801 [seatunnel-374530] [5.1] Shutting down node engine...
2023-12-20 16:58:35,637 INFO  com.hazelcast.instance.impl.NodeExtension - [localhost]:5801 [seatunnel-374530] [5.1] Destroying node NodeExtension.
2023-12-20 16:58:35,637 INFO  com.hazelcast.instance.impl.Node - [localhost]:5801 [seatunnel-374530] [5.1] Hazelcast Shutdown is completed in 3033 ms.
2023-12-20 16:58:35,637 INFO  com.hazelcast.core.LifecycleService - [localhost]:5801 [seatunnel-374530] [5.1] [localhost]:5801 is SHUTDOWN
2023-12-20 16:58:35,637 INFO  org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand - Closed HazelcastInstance ......
2023-12-20 16:58:35,637 ERROR org.apache.seatunnel.core.starter.SeaTunnel - 

===============================================================================


2023-12-20 16:58:35,637 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Fatal Error, 

2023-12-20 16:58:35,637 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Please submit bug report in https://github.com/apache/seatunnel/issues

2023-12-20 16:58:35,637 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Reason:SeaTunnel job executed failed 

2023-12-20 16:58:35,639 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:191)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:659)
        at java.util.ArrayList.get(ArrayList.java:435)
        at org.apache.seatunnel.connectors.seatunnel.cdc.sqlserver.source.source.SqlServerIncrementalSource.createDebeziumDeserializationSchema(SqlServerIncrementalSource.java:114)
        at org.apache.seatunnel.connectors.cdc.base.source.IncrementalSource.prepare(IncrementalSource.java:119)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSource(JobConfigParser.java:85)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:317)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:179)
        at org.apache.seatunnel.engine.core.job.AbstractJobEnvironment.getLogicalDag(AbstractJobEnvironment.java:109)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:73)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:143)
        ... 2 more
 
2023-12-20 16:58:35,639 ERROR org.apache.seatunnel.core.starter.SeaTunnel - 
===============================================================================



Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:191)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:659)
        at java.util.ArrayList.get(ArrayList.java:435)
        at org.apache.seatunnel.connectors.seatunnel.cdc.sqlserver.source.source.SqlServerIncrementalSource.createDebeziumDeserializationSchema(SqlServerIncrementalSource.java:114)
        at org.apache.seatunnel.connectors.cdc.base.source.IncrementalSource.prepare(IncrementalSource.java:119)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSource(JobConfigParser.java:85)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:317)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:179)
        at org.apache.seatunnel.engine.core.job.AbstractJobEnvironment.getLogicalDag(AbstractJobEnvironment.java:109)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:73)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:143)
        ... 2 more
```

### Java or Scala Version

java version "1.8.0_341"
Java(TM) SE Runtime Environment (build 1.8.0_341-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.341-b10, mixed mode)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Carl-Zhou-CN** [comment]
@ic4y Please look at this issue
