### ISSUE TITLE
[Bug] [Hbase Type Error] Hbase connector does not support this column type [ARRAY].

### ISSUE THREAD

**Issue by notAprogrammer-0** [apache/seatunnel#6052]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When i use seatunnel to do 'kafka to hbase' task.I met the problem of 'Hbase connector does not support this column type [ARRAY]'.
I want to know how can i achieve this purpose?

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
source{
	Kafka {
		schema = {
			fields {
				dataType = "string"
				hasSignal = "int"
				kpiId = "string"
				rows = "array<string>"
				state = "int"
				step = "double"
			}
		}
		format = json
		field_delimiter = ","
		topic = "BGTA_SACC2_IHD_KAFKA"
		bootstrap.servers = "xxx:**"
		kafka.config = {
			client.id = "5"
			max.pool.records = "500"
			auto.offset.reset = "earliest"
			enable.auto.commit = "false"
		}
		result_table_name = "t_kafka"
	}
}
transform{
	Copy {
		source_table_name = "t_kafka"
		result_table_name = "t_copy"
		fields {
			kpiId_row = kpiId
		}
	}
}
sink{
	Hbase{
		source_table_name = "t_trans"
		zookeeper_quorum = "xxx:**"
		table = "bigdata:seatunnel1"
		rowkey_column = ["kpiId_row"]
		family_name {
			all_columns = info
		}
	}
}
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/kafka.to.hbase -e local
```

### Error Exception

```log
Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:191)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: java.lang.RuntimeException: org.apache.seatunnel.connectors.seatunnel
.hbase.exception.HbaseConnectorException: ErrorCode:[COMMON-07], ErrorDescription:[Unsupported data type] - Hbase connector does not support this colum
n type [ARRAY]
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:232)
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:61)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:39)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:27)
	at org.apache.seatunnel.engine.server.task.group.queue.IntermediateBlockingQueue.handleRecord(IntermediateBlockingQueue.java:76)
	at org.apache.seatunnel.engine.server.task.group.queue.IntermediateBlockingQueue.collect(IntermediateBlockingQueue.java:51)
	at org.apache.seatunnel.engine.server.task.flow.IntermediateQueueFlowLifeCycle.collect(IntermediateQueueFlowLifeCycle.java:52)
	at org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask.collect(TransformSeaTunnelTask.java:73)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTask.stateProcess(SeaTunnelTask.java:168)
	at org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask.call(TransformSeaTunnelTask.java:78)
	at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:613)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.seatunnel.connectors.seatunnel.hbase.exception.HbaseConnectorException: ErrorCode:[COMMON-07], ErrorDescription:[Unsupported data
 type] - Hbase connector does not support this column type [ARRAY]
	at org.apache.seatunnel.connectors.seatunnel.hbase.sink.HbaseSinkWriter.convertColumnToBytes(HbaseSinkWriter.java:190)
	at org.apache.seatunnel.connectors.seatunnel.hbase.sink.HbaseSinkWriter.convertRowToPut(HbaseSinkWriter.java:133)
	at org.apache.seatunnel.connectors.seatunnel.hbase.sink.HbaseSinkWriter.write(HbaseSinkWriter.java:99)
	at org.apache.seatunnel.connectors.seatunnel.hbase.sink.HbaseSinkWriter.write(HbaseSinkWriter.java:47)
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:227)
	... 15 more

	at org.apache.seatunnel.engine.client.job.ClientJobProxy.waitForJobComplete(ClientJobProxy.java:122)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:184)
```

### Java or Scala Version

java version "1.8.0_202"

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lightzhao** [comment]
This is not a bug. The hbase sink does not support the array data type. I will try to support it.

**Comment by notAprogrammer-0** [comment]
> This is not a bug. The hbase sink does not support the array data type. I will try to support it.

Thank you very much for your reply and I look forward to adding support for arrays! My current solution is to write a UDF function to parse the array in my data.
