### ISSUE TITLE
[Bug] [flink on yarn]  Provider org.apache.seatunnel.connectors.seatunnel.fake.source.FakeSource not a subtype

### ISSUE THREAD

**Issue by amapleleaf** [apache/seatunnel#6068]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

evn: fllink yarn-application model
hdfs://hadoop101:9820/dlink/flink117 dir：
lib
--flink-dist-1.17.0.jar
…… all flink dependencies 
seatunnel
--connector-fake-2.3.3.jar
--connector-jdbc-2.3.3.jar
--connector-console-2.3.3.jar
问题如下：
1、yarn-application 模式下 --config的配置脚本不支持从hdfs上获取
2、将connetors包放入hdfs上，通过-Dyarn.provided.lib.dirs参数指定后启动，任务运行报错：org.apache.seatunnel.api.source.SeaTunnelSource: Provider org.apache.seatunnel.connectors.seatunnel.fake.source.FakeSource not a subtype

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
  job.mode = "BATCH"
}

source {
  FakeSource {
    parallelism = 1
    result_table_name = "fake"
    row.num = 16
    schema = {
      fields {
        name = "string"
        age = "int"
      }
    }
  }
}

sink {
  jdbc {
        url = "jdbc:mysql://xx.xx.xx.xx:3306/flinksql"
        driver = "com.mysql.cj.jdbc.Driver"
        user = "xx"
        password = "xx"
        query = "insert into test_fake(name,age) values(?,?)"
     }
}
```

### Running Command

```shell
./bin/start-seatunnel-flink-15-connector-v2.sh -e run-application --master yarn-application --config /opt/module/seatunnel/taskconf/v2.streaming.conf.template -Dyarn.provided.lib.dirs="hdfs://hadoop101:9820/dlink/flink117"
```

### Error Exception

```log
2023-12-24 11:40:50,339 INFO  org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery [] - Load SeaTunnelSource Plugin from /opt/module/hadoop-3.3.1/data/nm-local-dir/usercache/root/appcache/application_1703247082192_0012/connectors/seatunnel
2023-12-24 11:40:50,344 WARN  org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap [] - Application failed unexpectedly: 
java.util.concurrent.CompletionException: org.apache.flink.client.deployment.application.ApplicationExecutionException: Could not execute application.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[?:1.8.0_301]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[?:1.8.0_301]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:957) ~[?:1.8.0_301]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940) ~[?:1.8.0_301]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_301]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) ~[?:1.8.0_301]
	at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.runApplicationEntryPoint(ApplicationDispatcherBootstrap.java:337) ~[flink-dist-1.17.0.jar:1.17.0]
	at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.lambda$runApplicationAsync$2(ApplicationDispatcherBootstrap.java:254) ~[flink-dist-1.17.0.jar:1.17.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_301]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_301]
	at org.apache.flink.runtime.concurrent.akka.ActorSystemScheduledExecutorAdapter$ScheduledFutureTask.run(ActorSystemScheduledExecutorAdapter.java:171) ~[flink-rpc-akka_bfb78933-03f1-4e44-9261-62e341d0e3a0.jar:1.17.0]
	at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.runWithContextClassLoader(ClassLoadingUtils.java:68) ~[flink-rpc-akka_bfb78933-03f1-4e44-9261-62e341d0e3a0.jar:1.17.0]
	at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.lambda$withContextClassLoader$0(ClassLoadingUtils.java:41) ~[flink-rpc-akka_bfb78933-03f1-4e44-9261-62e341d0e3a0.jar:1.17.0]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49) [flink-rpc-akka_bfb78933-03f1-4e44-9261-62e341d0e3a0.jar:1.17.0]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48) [flink-rpc-akka_bfb78933-03f1-4e44-9261-62e341d0e3a0.jar:1.17.0]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_301]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067) [?:1.8.0_301]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703) [?:1.8.0_301]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172) [?:1.8.0_301]
Caused by: org.apache.flink.client.deployment.application.ApplicationExecutionException: Could not execute application.
	... 13 more
Caused by: java.util.ServiceConfigurationError: org.apache.seatunnel.api.source.SeaTunnelSource: Provider org.apache.seatunnel.connectors.seatunnel.fake.source.FakeSource not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:239) ~[?:1.8.0_301]
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185) ~[?:1.8.0_301]
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376) ~[?:1.8.0_301]
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) ~[?:1.8.0_301]
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480) ~[?:1.8.0_301]
	at org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery.loadPluginInstance(AbstractPluginDiscovery.java:295) ~[seatunnel-flink-15-starter.jar:2.3.3]
	at org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery.createPluginInstance(AbstractPluginDiscovery.java:184) ~[seatunnel-flink-15-starter.jar:2.3.3]
	at org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery.createPluginInstance(AbstractPluginDiscovery.java:178) ~[seatunnel-flink-15-starter.jar:2.3.3]
	at org.apache.seatunnel.core.starter.flink.execution.SourceExecuteProcessor.initializePlugins(SourceExecuteProcessor.java:133) ~[seatunnel-flink-15-starter.jar:2.3.3]
	at org.apache.seatunnel.core.starter.flink.execution.FlinkAbstractPluginExecuteProcessor.<init>(FlinkAbstractPluginExecuteProcessor.java:67) ~[seatunnel-flink-15-starter.jar:2.3.3]
	at org.apache.seatunnel.core.starter.flink.execution.SourceExecuteProcessor.<init>(SourceExecuteProcessor.java:58) ~[seatunnel-flink-15-starter.jar:2.3.3]
	at org.apache.seatunnel.core.starter.flink.execution.FlinkExecution.<init>(FlinkExecution.java:87) ~[seatunnel-flink-15-starter.jar:2.3.3]
	at org.apache.seatunnel.core.starter.flink.command.FlinkTaskExecuteCommand.execute(FlinkTaskExecuteCommand.java:59) ~[seatunnel-flink-15-starter.jar:2.3.3]
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40) ~[seatunnel-flink-15-starter.jar:2.3.3]
	at org.apache.seatunnel.core.starter.flink.SeaTunnelFlink.main(SeaTunnelFlink.java:34) ~[seatunnel-flink-15-starter.jar:2.3.3]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_301]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_301]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_301]
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355) ~[flink-dist-1.17.0.jar:1.17.0]
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222) ~[flink-dist-1.17.0.jar:1.17.0]
	at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:105) ~[flink-dist-1.17.0.jar:1.17.0]
	at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.runApplicationEntryPoint(ApplicationDispatcherBootstrap.java:301) ~[flink-dist-1.17.0.jar:1.17.0]
	... 12 more
2023-12-24 11:40:50,354 ERROR org.apache.flink.runtime.entrypoint.ClusterEntrypoint        [] - Fatal error occurred in the cluster entrypoint.
```

### Zeta or Flink or Spark Version

Flink1.17

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by qinlz-1** [comment]
@amapleleaf 
你这个问题解了吗？

**Comment by zhaoli2333** [comment]
here is my solution:
```
/usr/local/flink-1.14.4/bin/flink run-application --target yarn-application 
-Dyarn.ship-files=/usr/local/seatunnel-2.3.3/lib/seatunnel-transforms-v2.jar;/usr/local/seatunnel-2.3.3/connectors/seatunnel/connector-jdbc-2.3.3.jar;/usr/local/seatunnel-2.3.3/connectors/seatunnel/connector-file-hadoop-2.3.3.jar; 
-Dyarn.application.name=test-seatunnel-job 
-Djobmanager.memory.process.size=1024m 
-Dtaskmanager.memory.process.size=2048m 
-Dtaskmanager.numberOfTaskSlots=1 
-Dcontainerized.master.env.ELKLOG_JOBID=1248 
-Dstate.checkpoints.dir=hdfs:///data/flink/flink-checkpoints/1248 
-Dstate.savepoints.dir=hdfs:///data/flink/flink-savepoints/1248 
-Dexecution.checkpointing.interval=30s 
-Dexecution.checkpointing.timeout=10min 
-c org.apache.seatunnel.core.starter.flink.SeaTunnelFlink /usr/local/seatunnel-2.3.3/starter/seatunnel-flink-13-starter.jar 
--config hdfs:///seatunnel/config/1248
```

1. use ```yarn.ship-files``` to specify your dependence jars
2. modify seatunnel source code to support read config from hdfs.

**Comment by ljl568419709** [comment]
@amapleleaf 你这个问题解了吗？
