### ISSUE TITLE
[Bug] [FTP SOURCE] FTP SOURCE Unable to return file list under FTP path in the code & FTP SINK NOT CONFIG ROOT PATH

### ISSUE THREAD

**Issue by WilliamTan778** [apache/seatunnel#6070]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

FTP SOURCE, PATH IS NOT FOUND

### SeaTunnel Version

dev version

### SeaTunnel Config

```conf
{
  "env": {
    "execution.parallelism": 2,
    //仅支持BATCH 批处理操作
    "job.mode": "BATCH",
    "checkpoint.interval": 10000
  },

  "source": [
    {
 			 "plugin_name": "FtpFile",
      // 这个作为流程中的别名
      "result_table_name": "tableA",
      "host":"172.30.13.179",
      "port":"2121",
      "user":"firewolf",
      "password":"P@ssw0rd01!",
      // 数据格式类型
      "file_format_type":"csv",
      // 字段分隔符
      "delimiter":",",
      "path":"/data.csv",
      "schema":{
                "fields":{
                    "id":"int",
                    "job_id":"int",
                  "node_id":"string",
                  "name":"string"
                }
            }
    }
  ],

"sink": [
    {   
      "plugin_name": "FtpFile",
      // 写入格式json
			"file_format_type": "csv",
  		"host":"172.30.13.179",
      "port":"2121",
      "user":"firewolf",
      "password":"P@ssw0rd01!",
      // 写入文件路径地址
      "path":"/",
      // 列分隔符
      "field_delimiter":",",
      // 行分隔符
      "row_delimiter":"\n",
      // 指定源头是transform中的虚拟表
      "source_table_name": "tableC"
    }
  ]
}




```

### Running Command

```shell
curl --location 'http://172.30.13.177:5801/hazelcast/rest/maps/submit-job' \
--header 'Content-Type: application/json' \
--data-raw '{
  "env": {
    "execution.parallelism": 2,
    //仅支持BATCH 批处理操作
    "job.mode": "BATCH",
    "checkpoint.interval": 10000
  },

  "source": [
    {
 			 "plugin_name": "FtpFile",
      // 这个作为流程中的别名
      "result_table_name": "tableA",
      "host":"172.30.13.179",
      "port":"2121",
      "user":"firewolf",
      "password":"P@ssw0rd01!",
      // 数据格式类型
      "file_format_type":"csv",
      // 字段分隔符
      "delimiter":",",
      "path":"/data.csv",
      "schema":{
                "fields":{
                    "id":"int",
                    "job_id":"int",
                  "node_id":"string",
                  "name":"string"
                }
            }
    }
  ],

"sink": [
    {   
      "plugin_name": "FtpFile",
      // 写入格式json
			"file_format_type": "csv",
  		"host":"172.30.13.179",
      "port":"2121",
      "user":"firewolf",
      "password":"P@ssw0rd01!",
      // 写入文件路径地址
      "path":"/",
      // 列分隔符
      "field_delimiter":",",
      // 行分隔符
      "row_delimiter":"\n",
      // 指定源头是transform中的虚拟表
      "source_table_name": "tableC"
    }
  ]
}'
```

### Error Exception

FTP SOURCE Unable to return file list under FTP path in the code:

```log
org.apache.seatunnel.connectors.seatunnel.file.exception.FileConnectorException: ErrorCode:[FILE-03], ErrorDescription:[Get file list failed] - Get file list from this path [/data.csv] failed
        at org.apache.seatunnel.connectors.seatunnel.file.ftp.source.FtpFileSource.prepare(FtpFileSource.java:88) ~[?:?]
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSource(JobConfigParser.java:84) ~[seatunnel-starter.jar:2.3.4-SNAPSHOT]
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:309) ~[seatunnel-starter.jar:2.3.4-SNAPSHOT]
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:182) ~[seatunnel-starter.jar:2.3.4-SNAPSHOT]
        at org.apache.seatunnel.engine.server.rest.RestJobExecutionEnvironment.getLogicalDag(RestJobExecutionEnvironment.java:76) ~[seatunnel-starter.jar:2.3.4-SNAPSHOT]
        at org.apache.seatunnel.engine.server.rest.RestJobExecutionEnvironment.build(RestJobExecutionEnvironment.java:99) ~[seatunnel-starter.jar:2.3.4-SNAPSHOT]
        at org.apache.seatunnel.engine.server.rest.RestHttpPostCommandProcessor.handleSubmitJob(RestHttpPostCommandProcessor.java:138) ~[seatunnel-starter.jar:2.3.4-SNAPSHOT]
        at org.apache.seatunnel.engine.server.rest.RestHttpPostCommandProcessor.handle(RestHttpPostCommandProcessor.java:77) ~[seatunnel-starter.jar:2.3.4-SNAPSHOT]
        at org.apache.seatunnel.engine.server.rest.RestHttpPostCommandProcessor.handle(RestHttpPostCommandProcessor.java:55) ~[seatunnel-starter.jar:2.3.4-SNAPSHOT]
        at com.hazelcast.internal.ascii.TextCommandServiceImpl$CommandExecutor.run(TextCommandServiceImpl.java:402) ~[seatunnel-starter.jar:2.3.4-SNAPSHOT]
        at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217) ~[seatunnel-starter.jar:2.3.4-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_312]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_312]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[seatunnel-starter.jar:2.3.4-SNAPSHOT]
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[seatunnel-starter.jar:2.3.4-SNAPSHOT]
Caused by: java.io.FileNotFoundException: File /data.csv does not exist.
        at org.apache.seatunnel.connectors.seatunnel.file.ftp.system.SeaTunnelFTPFileSystem.getFileStatus(SeaTunnelFTPFileSystem.java:459) ~[?:?]
        at org.apache.seatunnel.connectors.seatunnel.file.ftp.system.SeaTunnelFTPFileSystem.listStatus(SeaTunnelFTPFileSystem.java:406) ~[?:?]
        at org.apache.seatunnel.connectors.seatunnel.file.ftp.system.SeaTunnelFTPFileSystem.listStatus(SeaTunnelFTPFileSystem.java:391) ~[?:?]
        at org.apache.seatunnel.connectors.seatunnel.file.hadoop.HadoopFileSystemProxy.listStatus(HadoopFileSystemProxy.java:175) ~[?:?]
        at org.apache.seatunnel.connectors.seatunnel.file.source.reader.AbstractReadStrategy.getFileNamesByPath(AbstractReadStrategy.java:93) ~[?:?]
        at org.apache.seatunnel.connectors.seatunnel.file.ftp.source.FtpFileSource.prepare(FtpFileSource.java:85) ~[?:?]
        ... 15 more


FTP SINK NOT ROOT PATH:

java.lang.NullPointerException: null
        at org.apache.seatunnel.transform.sql.SQLTransform.close(SQLTransform.java:188) ~[seatunnel-transforms-v2.jar:2.3.4-SNAPSHOT]
        at org.apache.seatunnel.engine.server.task.flow.TransformFlowLifeCycle.close(TransformFlowLifeCycle.java:119) ~[seatunnel-starter.jar:2.3.4-SNAPSHOT]
        at org.apache.seatunnel.engine.server.task.SeaTunnelTask.lambda$close$5(SeaTunnelTask.java:330) ~[seatunnel-starter.jar:2.3.4-SNAPSHOT]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) ~[?:?]
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408) ~[?:?]
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661) ~[?:?]
        at org.apache.seatunnel.engine.server.task.SeaTunnelTask.close(SeaTunnelTask.java:327) ~[seatunnel-starter.jar:2.3.4-SNAPSHOT]
        at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:651) ~[seatunnel-starter.jar:2.3.4-SNAPSHOT]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]







```

### Zeta or Flink or Spark Version

Zeta

### Java or Scala Version

1.8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xiaominyan88** [comment]
Hello, I meet the same issue when I use ftp source in seatunnel v2.3.3, but when I rewrite the source code according to ftp source connector code in seatunnel v2.3.8 or seatunnel dev branch, it still show the error as "file not exist", but when I add the code "client.enterLocalPassiveMode()" in getFileStatus method，it seems it can detect the source file, but it can not finish the job，can you give me some suggestions?
