### ISSUE TITLE
[Bug] [cluster have no master node] failed send heartbeat to resource manager, will retry later

### ISSUE THREAD

**Issue by notAprogrammer-0** [apache/seatunnel#6096]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

There is already a seatunnel client running in my seatunnel local mode. When I try to start a second seatunnel client in local mode, the following problem is reported:

2023-12-27 12:32:00,510 WARN  org.apache.seatunnel.engine.server.TaskExecutionService - [localhost]:5802 [seatunnel-536734] [5.1] The Node is not ready yet, Node state STARTING,looking forward to the next scheduling
2023-12-27 12:32:00,521 WARN  org.apache.seatunnel.engine.server.service.slot.DefaultSlotService - failed send heartbeat to resource manager, will retry later. this address: [localhost]:5802

2023-12-27 12:33:00,539 ERROR org.apache.seatunnel.engine.server.CoordinatorService - [localhost]:5802 [seatunnel-536734] [5.1] org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: cluster have no master node

btw：
Is the problem caused by my port being occupied by the first client program? If so, how should I change it? I have just started to contact seatunnel, so I am not very clear about many things, please give me more advice, thank you！

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
env{
    execution.parallelism = 1
    job.mode = "STREAMING"
}
source{
    Kafka {
        schema = {
            fields {
                dataType = "string"
                hasSignal = "string"
                kpiId = "string"
                rows = "string"
                state = "string"
                step = "string"
            }
        }
        format = json
        field_delimiter = ","
        topic = "BGTA_***_***_KAFKA"
        bootstrap.servers = "xxx:**,xxx:**,xxx:**"
        kafka.config = {
            client.id = "kafka_test"
            max.pool.records = "500"
            auto.offset.reset = "earliest"
            enable.auto.commit = "false"
        }
        result_table_name = "t_kafka100"
    }
}
transform{
    Sql {
        source_table_name = "t_kafka100"
        result_table_name = "t_sql100"
        query = "select dataType, hasSignal, kpiId, ARRAYTRANS(rows, 1) as value, ARRAYTRANS(rows, 2) as dTime, state, step from t_kafka"
    }
    Copy {
        source_table_name = "t_sql100"
        result_table_name = "t_copy100"
        fields {
            kpiId_row = kpiId
            timestamp_row = dTime
        }
    }
}
sink{
    Hbase{
        source_table_name = "t_copy100"
        zookeeper_quorum = "xxx:**,xxx:**,xxx:**"
        table = "bigdata:seatunnel1"
        rowkey_column = ["kpiId_row","timestamp_row"]
        family_name {
            all_columns = message
        }
    }
}

**and the hazelcast.yaml config is:**

hazelcast:
  cluster-name: seatunnel
  network:
    rest-api:
      enabled: true
      endpoint-groups:
        CLUSTER_WRITE:
          enabled: true
        DATA:
          enabled: true
    join:
      tcp-ip:
        enabled: true
        member-list:
          - localhost
    port:
      auto-increment: true
      port-count: 100
      port: 5801
  properties:
    hazelcast.invocation.max.retry.count: 20
    hazelcast.tcp.join.port.try.count: 30
    hazelcast.logging.type: log4j2
    hazelcast.operation.generic.thread.count: 50


**and the hazelcast-client.yaml config is:**

hazelcast-client:
  cluster-name: seatunnel
  properties:
    hazelcast.logging.type: log4j2
  network:
    cluster-members:- localhost:5801
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/kafka.new.to.hbase.config -e local
```

### Error Exception

```log
2023-12-27 12:33:00,539 ERROR org.apache.seatunnel.engine.server.CoordinatorService - [localhost]:5802 [seatunnel-536734] [5.1] org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: cluster have no master node
	at org.apache.seatunnel.engine.server.SeaTunnelServer.isMasterNode(SeaTunnelServer.java:246)
	at org.apache.seatunnel.engine.server.CoordinatorService.checkNewActiveMaster(CoordinatorService.java:369)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Execute given execution failed after retry 30 times
	at org.apache.seatunnel.common.utils.RetryUtils.retryWithException(RetryUtils.java:75)
	at org.apache.seatunnel.engine.server.SeaTunnelServer.isMasterNode(SeaTunnelServer.java:235)
	... 8 more
Caused by: java.lang.NullPointerException
	at org.apache.seatunnel.engine.server.SeaTunnelServer.lambda$isMasterNode$0(SeaTunnelServer.java:236)
	at org.apache.seatunnel.common.utils.RetryUtils.retryWithException(RetryUtils.java:48)
	... 9 more

2023-12-27 12:33:05,517 WARN  org.apache.seatunnel.engine.server.service.slot.DefaultSlotService - failed send heartbeat to resource manager, will retry later. this address: [localhost]:5802
2023-12-27 12:33:10,517 WARN  org.apache.seatunnel.engine.server.service.slot.DefaultSlotService - failed send heartbeat to resource manager, will retry later. this address: [localhost]:5802
2023-12-27 12:33:15,517 WARN  org.apache.seatunnel.engine.server.service.slot.DefaultSlotService - failed send heartbeat to resource manager, will retry later. this address: [localhost]:5802
```

### Zeta or Flink or Spark Version

Zeta

### Java or Scala Version

java version "1.8.0_202"

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by inthejim** [comment]
I had the same problem as you, and I killed the port where the situnnel server was running. then I tried to run server and I solved the problem.
