### ISSUE TITLE
[Bug] [seatunnel-api] SeaTunnelRowType不支持数据库字段转义

### ISSUE THREAD

**Issue by zkyong** [apache/seatunnel#6155]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

1、如题，ZetaSQLEngine引擎底层解析sql使用到了jsqlparser（net.sf.jsqlparser.parser.CCJSqlParserUtil#parse(java.lang.String)），但该工具类不不支持列名work关键字的同步。报错信息如下：
```text
Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:191)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.transform.exception.TransformException: ErrorCode:[COMMON-05], ErrorDescription:[Unsupported operation] - SQL parse failed: select id,device_no,version,type,model,work,create_time,update_time,deleted from gkzyzb_device, cause: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "," ","
    at line 1, column 39.

Was expecting one of:

    "&"
    "::"
    ";"
    "<<"
    ">>"
    "COLLATE"
    "CONNECT"
    "EMIT"
    "GROUP"
    "HAVING"
    "INTO"
    "START"
    "WINDOW"
    "["
    "^"
    "|"
    <EOF>

        at org.apache.seatunnel.transform.sql.zeta.ZetaSQLEngine.parseSQL(ZetaSQLEngine.java:95)
        at org.apache.seatunnel.transform.sql.zeta.ZetaSQLEngine.init(ZetaSQLEngine.java:83)
        at org.apache.seatunnel.transform.sql.SQLTransform.open(SQLTransform.java:118)
        at org.apache.seatunnel.transform.sql.SQLTransform.tryOpen(SQLTransform.java:127)
        at org.apache.seatunnel.transform.sql.SQLTransform.transformTableSchema(SQLTransform.java:145)
        at org.apache.seatunnel.transform.common.AbstractCatalogSupportTransform.transformCatalogTable(AbstractCatalogSupportTransform.java:56)
        at org.apache.seatunnel.transform.common.AbstractCatalogSupportTransform.getProducedCatalogTable(AbstractCatalogSupportTransform.java:46)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseTransform(MultipleTableJobConfigParser.java:463)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseTransforms(MultipleTableJobConfigParser.java:374)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:184)
        at org.apache.seatunnel.engine.core.job.AbstractJobEnvironment.getLogicalDag(AbstractJobEnvironment.java:109)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:73)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:143)
        ... 2 more
```

2、我打算使用转义符绕过关键字问题，但却发现SeaTunnelRowType类不支持字段转义。
```text
2024-01-08 11:23:22,140 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:191)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: java.lang.IllegalArgumentException: can't find field [`work`]
        at org.apache.seatunnel.api.table.type.SeaTunnelRowType.indexOf(SeaTunnelRowType.java:82)
        at org.apache.seatunnel.transform.sql.zeta.ZetaSQLType.getExpressionType(ZetaSQLType.java:91)
        at org.apache.seatunnel.transform.sql.zeta.ZetaSQLEngine.typeMapping(ZetaSQLEngine.java:206)
        at org.apache.seatunnel.transform.sql.SQLTransform.transformTableSchema(SQLTransform.java:147)
        at org.apache.seatunnel.transform.common.AbstractCatalogSupportTransform.transformCatalogTable(AbstractCatalogSupportTransform.java:56)
        at org.apache.seatunnel.transform.common.AbstractCatalogSupportTransform.getProducedCatalogTable(AbstractCatalogSupportTransform.java:46)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseTransform(MultipleTableJobConfigParser.java:463)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseTransforms(MultipleTableJobConfigParser.java:374)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:184)
        at org.apache.seatunnel.engine.core.job.AbstractJobEnvironment.getLogicalDag(AbstractJobEnvironment.java:109)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:73)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:143)
        ... 2 more

2024-01-08 11:23:22,140 ERROR org.apache.seatunnel.core.starter.SeaTunnel -
```

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
数据同步脚本中部分配置如下：
    "transform" : [
      {
        "plugin_name":"Sql",
        "source_table_name" : "tb_device",
        "result_table_name" : "tb_device_ck",
        "query" : "select id,device_no,version,type,model,work,create_time,update_time,deleted from tb_device"
      }
    ],
```

### Running Command

```shell
nohup sh $SEATUNNEL_HOME/bin/seatunnel.sh -s "20232000" > ./logs/20232000.log 2>&1 &
```

### Error Exception

```log
nohup sh $SEATUNNEL_HOME/bin/seatunnel.sh -s "20232000" > ./logs/20232000.log 2>&1 &
```

### Java or Scala Version

1.8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by luzongzhu** [comment]
+1 
`   Caused by: org.apache.seatunnel.transform.exception.TransformException: ErrorCode:[COMMON-05], ErrorDescription:[Unsupported operation] - SQL parse failed: SELECT PURCHASEORDERID as purchaseorderid,HISTORY.CREATEDBY.EMPLOYEEID as history.createdby.employeeid,HISTORY.CREATEDAT as history.createdat,HISTORY.CHANGEDBY.EMPLOYEEID as history.changedby.employeeid,HISTORY.CHANGEDAT as history.changedat,NOTEID as noteid,PARTNER.PARTNERID as partner.partnerid,CURRENCY as currency,GROSSAMOUNT as grossamount,NETAMOUNT as netamount,TAXAMOUNT as taxamount,LIFECYCLESTATUS as lifecyclestatus,APPROVALSTATUS as approvalstatus,CONFIRMSTATUS as confirmstatus,ORDERINGSTATUS as orderingstatus,INVOICINGSTATUS as invoicingstatus FROM ST_GLOBAL_VIEW_NAME, cause: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "." "."`

**Comment by swk998741** [comment]
+1 
Caused by: org.apache.seatunnel.transform.exception.TransformException: ErrorCode:[COMMON-05], ErrorDescription:[Unsupported operation] - SQL parse failed:   select  id , bigint , BIGINTUNSIGNED , BIT , BOOL , CHAR , DATE , DATETIME , DECIMAL , DOUBLE , DOUBLEPRECISION , FLOAT , INT , INTUNSIGNED , INTEGER , INTEGERUNSIGNED , LONGTEXT , ENUM , LONGVARCHAR , MEDIUMINT , MEDIUMINTUNSIGNED , MEDIUMTEXT , NUMERIC , REAL , SET , SMALLINT , SMALLINTUNSIGNED , TEXT , TIME_TO_TIMESTAMP(TIME) as TIME , TIMESTAMP , TINYINT , TINYINTUNSIGNED , TINYTEXT , VARCHAR , YEAR , json   from fake, cause: Time out occurred.
	at org.apache.seatunnel.transform.sql.zeta.ZetaSQLEngine.parseSQL(ZetaSQLEngine.java:95)
	at org.apache.seatunnel.transform.sql.zeta.ZetaSQLEngine.init(ZetaSQLEngine.java:83)
	at org.apache.seatunnel.transform.sql.SQLTransform.open(SQLTransform.java:99)
	at org.apache.seatunnel.transform.sql.SQLTransform.tryOpen(SQLTransform.java:108)
	at org.apache.seatunnel.transform.sql.SQLTransform.transformTableSchema(SQLTransform.java:120)
	at org.apache.seatunnel.transform.common.AbstractCatalogSupportTransform.transformCatalogTable(AbstractCatalogSupportTransform.java:52)
	at org.apache.seatunnel.transform.common.AbstractCatalogSupportTransform.getProducedCatalogTable(AbstractCatalogSupportTransform.java:42)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseTransform(MultipleTableJobConfigParser.java:443)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseTransforms(MultipleTableJobConfigParser.java:350)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:186)
	at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.getLogicalDag(ClientJobExecutionEnvironment.java:88)
	at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.execute(ClientJobExecutionEnvironment.java:161)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:146)
	... 2 more

**Comment by heheyo** [comment]
+1

**Comment by heheyo** [comment]
我改了源码兼容了一下，现在可以解析了
