### ISSUE TITLE
[Bug] [jdbc source] source context is null,when init

### ISSUE THREAD

**Issue by Xuzhengz** [apache/seatunnel#6174]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

DEBUG org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser - java.lang.NullPointerException

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
{
  "env": {
    "execution.parallelism": "1",
    "job.mode": "BATCH"
  },
  "source": [
    {
      "plugin_name": "jdbc",
      "url": "jdbc:mysql://172.16.11.183:3306/ocean_intelligence?remarks=true&useInformationSchema=true&useCursorFetch=true&defaultFetchSize=2048",
      "password": "****",
      "user": "****",
      "driver": "com.mysql.cj.jdbc.Driver",
      "query": "SELECT `id`,`name`,`age`,`sex`,`habitation` FROM `test`",
      "result_table_name": "fake"
    }
  ],
  "transform": [
  ],
  "sink": [
    {
      "source_table_name": "fake",
      "plugin_name": "Console"
    }
  ]
}
```

### Running Command

```shell
bin/seatunnel.sh -c demo.json
```

### Error Exception

```log
2024-01-10 14:34:17,244 DEBUG org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser - java.lang.NullPointerException
	at org.apache.seatunnel.connectors.seatunnel.console.sink.ConsoleSinkFactory.createSink(ConsoleSinkFactory.java:60)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.lambda$parseSink$7(MultipleTableJobConfigParser.java:527)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.isFallback(MultipleTableJobConfigParser.java:274)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSink(MultipleTableJobConfigParser.java:523)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:194)
	at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.getLogicalDag(ClientJobExecutionEnvironment.java:88)
	at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.execute(ClientJobExecutionEnvironment.java:161)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:146)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.example.engine.SeaTunnelEngineExample.main(SeaTunnelEngineExample.java:48)
```

### Java or Scala Version

1.8

### Screenshots

<img width="1206" alt="image" src="https://github.com/apache/seatunnel/assets/90698333/2648e3f5-16b6-4c83-99f9-b0193d94580f">

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Xuzhengz** [comment]
source 和 sink 一样都会报

**Comment by Xuzhengz** [comment]
2024-01-10 14:34:16,349 DEBUG org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser - java.lang.NullPointerException
	at org.apache.seatunnel.connectors.seatunnel.jdbc.source.JdbcSourceFactory.createSource(JdbcSourceFactory.java:69)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.lambda$parseSource$4(MultipleTableJobConfigParser.java:309)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.isFallback(MultipleTableJobConfigParser.java:274)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:305)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:183)
	at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.getLogicalDag(ClientJobExecutionEnvironment.java:88)
	at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.execute(ClientJobExecutionEnvironment.java:161)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:146)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.example.engine.SeaTunnelEngineExample.main(SeaTunnelEngineExample.java:48)

**Comment by liugddx** [comment]
This is just a warning and does not affect the use.
