### ISSUE TITLE
[Bug] [seatunnel-engine-server] when using rest-api hazelcast/rest/maps/running-job/:job-id，return exception：java.lang.ClassNotFoundException: org.apache.seatunnel.connectors.seatunnel.kafka.source.KafkaSource 

### ISSUE THREAD

**Issue by NighterCoder** [apache/seatunnel#6192]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

when using rest-api hazelcast/rest/maps/running-job/:job-id，
the task ran normally，but monitor http command
return exception：java.lang.ClassNotFoundException: org.apache.seatunnel.connectors.seatunnel.kafka.source.KafkaSource 

### SeaTunnel Version

 <groupId>org.apache.seatunnel</groupId>
 <artifactId>seatunnel</artifactId>
<version>2.3.3-SNAPSHOT</version>

### SeaTunnel Config

```conf
env {
"job.mode"=streaming
"execution.parallelism"=1
}
source {
kafka {
    format=json
    "start_mode"=latest
    "kafka.config" {
        "max.poll.records"="500"
        "client.id"="client_1"
    }
    "result_table_name"=task1SourceTable
    topic=testst00
    schema {
        fields {
            name=string
            age=int
        }
    }
    "bootstrap.servers"="xxxx"
}
}
transform {
}
sink {
kafka {
    format=text
    "source_table_name"=task1SinkTable
    topic=testst01
    "bootstrap.servers"="xxxx"
}
}
```

### Running Command

```shell
$seatunnel_home/bin/seatunnel.sh --config seatunnel_kafka.conf
```

### Error Exception

```log
An error occurred while handling request HttpCommand [HTTP_GET]{uri='/hazelcast/rest/maps/running-jobs'}AbstractTextCommand[HTTP_GET]{requestId=0}
com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: org.apache.seatunnel.connectors.seatunnel.kafka.source.KafkaSource
        at com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:96) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:85) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:349) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:600) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at org.apache.seatunnel.engine.core.dag.logical.LogicalVertex.readData(LogicalVertex.java:99) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:160) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:106) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:51) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.readObject(AbstractSerializationService.java:349) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readObject(ByteArrayObjectDataInput.java:600) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at org.apache.seatunnel.engine.core.dag.logical.LogicalDag.readData(LogicalDag.java:154) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:160) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:106) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:51) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:268) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_372]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_372]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:577) ~[?:1.8.0_372]
        at org.apache.seatunnel.engine.server.rest.RestHttpGetCommandProcessor.handleRunningJobsInfo(RestHttpGetCommandProcessor.java:162) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at org.apache.seatunnel.engine.server.rest.RestHttpGetCommandProcessor.handle(RestHttpGetCommandProcessor.java:89) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at org.apache.seatunnel.engine.server.rest.RestHttpGetCommandProcessor.handle(RestHttpGetCommandProcessor.java:61) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at com.hazelcast.internal.ascii.TextCommandServiceImpl$CommandExecutor.run(TextCommandServiceImpl.java:402) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_372]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_372]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_372]
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
Caused by: java.lang.ClassNotFoundException: org.apache.seatunnel.connectors.seatunnel.kafka.source.KafkaSource
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[?:1.8.0_372]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_372]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_372]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_372]
        at com.hazelcast.internal.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:301) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at com.hazelcast.internal.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:259) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at com.hazelcast.internal.nio.IOUtil$ClassLoaderAwareObjectInputStream.resolveClass(IOUtil.java:867) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1987) ~[?:1.8.0_372]
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1851) ~[?:1.8.0_372]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2185) ~[?:1.8.0_372]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1668) ~[?:1.8.0_372]
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2430) ~[?:1.8.0_372]
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2354) ~[?:1.8.0_372]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2212) ~[?:1.8.0_372]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1668) ~[?:1.8.0_372]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:502) ~[?:1.8.0_372]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:460) ~[?:1.8.0_372]
        at com.hazelcast.internal.serialization.impl.defaultserializers.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:92) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        ... 37 more
```

### Zeta or Flink or Spark Version

Zeta

### Java or Scala Version

Java 1.8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by joswlv** [comment]
Most likely, you didn't install the libs.

Before packaging the source code, run `{seatunnel_source_code}/bin/install-plugin.sh` (this will download the relevant lib jars under a dir called connectors) and then run `mvn clean package -DskipTests -T 1C` to deploy the results.

The packaged result can be used by deploying the tar under the `seatunnel-dist/target` dir to your server.

**Comment by NighterCoder** [comment]
![WechatIMG513](https://github.com/apache/seatunnel/assets/26673766/7a32b2a9-121f-4ed1-8980-503940771f5e)
![WechatIMG514](https://github.com/apache/seatunnel/assets/26673766/a6fb2c51-00cb-4230-a841-6a30491b400c)
I installed the libs， above are lib dir and seatunnel dir，is any package missing？

**Comment by NighterCoder** [comment]
upgrade seatunnel version to latest version 2.3.4-SNAPSHOT，this problem has solved

**Comment by liugddx** [comment]
use 2.3.4 and try again.
