### ISSUE TITLE
[Bug] [Module Name] SAPHANA JDBC query error

### ISSUE THREAD

**Issue by zuzuou** [apache/seatunnel#6203]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I used JDBC source to connect to SAPHANA, but got error. I had specify the schema name "SAPABAP1" upper case in the config file, but got an error "invalid schema name: sapabap1". The schema name had been changed into lower case.

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
env {
    execution.parallelism = 1
    job.mode = "BATCH"
    checkpoint.interval = 10000
}
source {
    Jdbc{
        url = "jdbc:sap://10.30.12.192:30015?currentschema=sapabap1"
        driver = "com.sap.db.jdbc.Driver"
        connection_check_timeout_sec = 100
        user = "biuser"
        password = "xxxx"
        query = "select \n     REPLACE(REPLACE(REPLACE(REPLACE(\"SPRSL\", CHAR(9), ' '), CHAR(10), ' '), CHAR(13), ' '), CHAR(15), ' ') AS \"SPRSL\" \n    , REPLACE(REPLACE(REPLACE(REPLACE(\"MANDT\", CHAR(9), ' '), CHAR(10), ' '), CHAR(13), ' '), CHAR(15), ' ') AS \"MANDT\" \n    , REPLACE(REPLACE(REPLACE(REPLACE(\"PERSG\", CHAR(9), ' '), CHAR(10), ' '), CHAR(13), ' '), CHAR(15), ' ') AS \"PERSG\" \n    , REPLACE(REPLACE(REPLACE(REPLACE(\"PTEXT\", CHAR(9), ' '), CHAR(10), ' '), CHAR(13), ' '), CHAR(15), ' ') AS \"PTEXT\" \n    , CURRENT_TIMESTAMP AS \"_LOAD_TIME_\" \n from \"SAPABAP1\".\"T501T\" "
    }
}
sink {
    Doris{
        fenodes = "10.128.6.17:8030"
        username = "etl"
        password = "xxx"
        table.identifier = "ods.sap_t501t_tmp"
        sink.enable-2pc = true
        sink.label-prefix = "ods_sap_t501t_tmp_20240115_104206"
        doris.config = {
            format = "csv"
            column_separator = "\t"
        }
    }
}
```

### Running Command

```shell
/app/seatunnel/bin/seatunnel.sh --config /app/ods_new/conf/sap/tmp/ods_sap_t501t -e local
```

### Error Exception

```log
2024-01-15 11:02:09,623 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Fatal Error,

2024-01-15 11:02:09,623 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Please submit bug report in https://github.com/apache/seatunnel/issues

2024-01-15 11:02:09,623 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Reason:SeaTunnel job executed failed

2024-01-15 11:02:09,624 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:191)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.api.common.PrepareFailException: ErrorCode:[API-01], ErrorDescription:[Configuration item validate failed] - PluginName: jdbc, PluginType: source, Message: com.sap.db.jdbc.exceptions.JDBCDriverException: SAP DBTech JDBC: [362] (at 11): invalid schema name: sapabap1: line 1 col 12 (at pos 11)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.source.JdbcSource.prepare(JdbcSource.java:112)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSource(JobConfigParser.java:85)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:317)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:179)
        at org.apache.seatunnel.engine.core.job.AbstractJobEnvironment.getLogicalDag(AbstractJobEnvironment.java:109)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:73)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:143)
        ... 2 more

2024-01-15 11:02:09,625 ERROR org.apache.seatunnel.core.starter.SeaTunnel -
===============================================================================



Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:191)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.api.common.PrepareFailException: ErrorCode:[API-01], ErrorDescription:[Configuration item validate failed] - PluginName: jdbc, PluginType: source, Message: com.sap.db.jdbc.exceptions.JDBCDriverException: SAP DBTech JDBC: [362] (at 11): invalid schema name: sapabap1: line 1 col 12 (at pos 11)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.source.JdbcSource.prepare(JdbcSource.java:112)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSource(JobConfigParser.java:85)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:317)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:179)
        at org.apache.seatunnel.engine.core.job.AbstractJobEnvironment.getLogicalDag(AbstractJobEnvironment.java:109)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:73)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:143)
        ... 2 more
```

### Zeta or Flink or Spark Version

Zeta

### Java or Scala Version

jdk version 1.8
saphana jdbc driver: 2.16.11

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zuzuou** [comment]
The schema name in the jdbc url "jdbc:sap://10.30.12.192:30015?currentschema=sapabap1" is not correct
