### ISSUE TITLE
[Bug] [Zeta RestApi ] Submit or Stop job from an inactive master node

### ISSUE THREAD

**Issue by VincentSleepless** [apache/seatunnel#6208]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

error when submit or stop job with error message " Please don't get coordinator service from an inactive master node" 

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
nothiong related
```

### Running Command

```shell
rest api to submit job
```

### Error Exception

```log
2024-01-15 16:55:32,395 INFO  [Log4j2HttpPostCommandProcessor] [hz.main.cached.thread-1] - [172.20.216.3]:5801 [seatunnel] [5.1] cluster master is :[172.20.216.1]:5801
2024-01-15 16:55:32,395 INFO  [Log4j2HttpPostCommandProcessor] [hz.main.cached.thread-1] - [172.20.216.3]:5801 [seatunnel] [5.1] [172.20.216.3]:5801 is :false
2024-01-15 16:55:32,396 INFO  [Log4j2HttpPostCommandProcessor] [hz.main.cached.thread-1] - [172.20.216.3]:5801 [seatunnel] [5.1] [172.20.216.3]:5801 is :false
2024-01-15 16:55:32,396 WARN  [Log4j2HttpPostCommandProcessor] [hz.main.cached.thread-1] - [172.20.216.3]:5801 [seatunnel] [5.1] An error occurred while handling request HttpCommand [HTTP_POST]{uri='/hazelcast/rest/maps/submit-job'}AbstractTextCommand[HTTP_POST]{requestId=2}
org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: Please don't get coordinator service from an inactive master node
        at org.apache.seatunnel.engine.server.SeaTunnelServer.getCoordinatorService(SeaTunnelServer.java:211) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at org.apache.seatunnel.engine.server.rest.RestHttpPostCommandProcessor.submitJob(RestHttpPostCommandProcessor.java:383) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at org.apache.seatunnel.engine.server.rest.RestHttpPostCommandProcessor.handleSubmitJob(RestHttpPostCommandProcessor.java:180) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at org.apache.seatunnel.engine.server.rest.RestHttpPostCommandProcessor.handle(RestHttpPostCommandProcessor.java:91) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at org.apache.seatunnel.engine.server.rest.RestHttpPostCommandProcessor.handle(RestHttpPostCommandProcessor.java:70) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at com.hazelcast.internal.ascii.TextCommandServiceImpl$CommandExecutor.run(TextCommandServiceImpl.java:402) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_60]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[seatunnel-starter.jar:2.3.3-SNAPSHOT]
2024-01-15 16:55:51,128 INFO  [o.a.s.e.s.CoordinatorService  ] [pool-5-thread-1] - [172.20.216.3]:5801 [seatunnel] [5.1]
```

### Zeta or Flink or Spark Version

nothing

### Java or Scala Version

java 1.8 191

### Screenshots

i try to add some debug logs!
![5b30e229611c13b27608d80be3ea1f2](https://github.com/apache/seatunnel/assets/15063109/59c98e0d-c652-47a2-a9b1-bef6465132d3)

Hazelcast.getAllHazelcastInstances() has only one instance(the current node)
![5638414a27860a19f4bc5422abc4019](https://github.com/apache/seatunnel/assets/15063109/31b67e88-3578-4f28-82ce-fd6d897e7b14)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by VincentSleepless** [comment]
@liugddx  hello, plz check
