### ISSUE TITLE
[Bug] [JDBC] jdbc sink to oracle Failed creating database YDDB in catalog Oracle

### ISSUE THREAD

**Issue by zengqinchris** [apache/seatunnel#6311]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

source from doris and sink to oracle error 

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
env {
parallelism = 1
job.mode = "BATCH" 
checkpoint.interval = 900000 
}
source {
Jdbc { 
url = "jdbc:mysql://0.0.0.0:16930/yddb" 
 driver = "com.mysql.cj.jdbc.Driver" 
 connection_check_timeout_sec = 1000 
 user = "doris" 
 password = "" 
 query = " select id as int_a,name as string_a,age as bigint_a,prices as double_a,floats as float_a,diagtals as decimal_a,dts as date_time_a,ds as date_a,dts as r_update_ts from yddb_data_type001 where 1=1 and 1=1 " 
 result_table_name = "yundee_source0"  
 } 
}
transform {
Sql { 
source_table_name = "yundee_source0"  
 result_table_name = "yundee_sink0"  
 query = " select int_a,string_a,bigint_a,double_a,float_a,decimal_a,date_time_a,date_a,r_update_ts from yundee_source0 " 
 } 
}
sink {
jdbc { 
source_table_name = "yundee_sink0"   
url = "jdbc:oracle:thin:@0.0.0.0:1521/helowin" 
 driver = "oracle.jdbc.OracleDriver" 
 user = "0" 
 password = "0" 
 max_retries = 3 
 generate_sink_sql = "true" 
 database = "YDDB" 
 table = "YDDB_DATA_TYPE011" 
 primary_keys = ["int_a"] 
 } 
}
```

### Running Command

```shell
bin/seatunnel.sh --config ./config/aa.conf
```

### Error Exception

```log
===============================================================================


2024-01-30 15:14:41,217 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Fatal Error, 

2024-01-30 15:14:41,217 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Please submit bug report in https://github.com/apache/seatunnel/issues

2024-01-30 15:14:41,217 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Reason:SeaTunnel job executed failed 

2024-01-30 15:14:41,218 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:199)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.common.exception.SeaTunnelRuntimeException: ErrorCode:[API-09], ErrorDescription:[Handle save mode failed]
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.handleSaveMode(MultipleTableJobConfigParser.java:667)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.createSinkAction(MultipleTableJobConfigParser.java:653)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSink(MultipleTableJobConfigParser.java:565)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:194)
        at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.getLogicalDag(ClientJobExecutionEnvironment.java:88)
        at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.execute(ClientJobExecutionEnvironment.java:161)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:146)
        ... 2 more
Caused by: org.apache.seatunnel.api.table.catalog.exception.CatalogException: ErrorCode:[API-03], ErrorDescription:[Catalog initialize failed] - Failed creating database YDDB in catalog Oracle
        at org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.AbstractJdbcCatalog.createDatabaseInternal(AbstractJdbcCatalog.java:422)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.AbstractJdbcCatalog.createDatabase(AbstractJdbcCatalog.java:410)
        at org.apache.seatunnel.api.sink.DefaultSaveModeHandler.createTable(DefaultSaveModeHandler.java:140)
        at org.apache.seatunnel.api.sink.DefaultSaveModeHandler.createSchemaWhenNotExist(DefaultSaveModeHandler.java:101)
        at org.apache.seatunnel.api.sink.DefaultSaveModeHandler.handleSchemaSaveMode(DefaultSaveModeHandler.java:62)
        at org.apache.seatunnel.api.sink.SaveModeHandler.handleSaveMode(SaveModeHandler.java:27)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.handleSaveMode(MultipleTableJobConfigParser.java:665)
        ... 8 more
Caused by: java.lang.UnsupportedOperationException
        at org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.AbstractJdbcCatalog.getCreateDatabaseSql(AbstractJdbcCatalog.java:414)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.AbstractJdbcCatalog.createDatabaseInternal(AbstractJdbcCatalog.java:419)
        ... 14 more
 
2024-01-30 15:14:41,218 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - 
===============================================================================



Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:199)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.common.exception.SeaTunnelRuntimeException: ErrorCode:[API-09], ErrorDescription:[Handle save mode failed]
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.handleSaveMode(MultipleTableJobConfigParser.java:667)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.createSinkAction(MultipleTableJobConfigParser.java:653)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSink(MultipleTableJobConfigParser.java:565)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:194)
        at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.getLogicalDag(ClientJobExecutionEnvironment.java:88)
        at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.execute(ClientJobExecutionEnvironment.java:161)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:146)
        ... 2 more
Caused by: org.apache.seatunnel.api.table.catalog.exception.CatalogException: ErrorCode:[API-03], ErrorDescription:[Catalog initialize failed] - Failed creating database YDDB in catalog Oracle
        at org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.AbstractJdbcCatalog.createDatabaseInternal(AbstractJdbcCatalog.java:422)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.AbstractJdbcCatalog.createDatabase(AbstractJdbcCatalog.java:410)
        at org.apache.seatunnel.api.sink.DefaultSaveModeHandler.createTable(DefaultSaveModeHandler.java:140)
        at org.apache.seatunnel.api.sink.DefaultSaveModeHandler.createSchemaWhenNotExist(DefaultSaveModeHandler.java:101)
        at org.apache.seatunnel.api.sink.DefaultSaveModeHandler.handleSchemaSaveMode(DefaultSaveModeHandler.java:62)
        at org.apache.seatunnel.api.sink.SaveModeHandler.handleSaveMode(SaveModeHandler.java:27)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.handleSaveMode(MultipleTableJobConfigParser.java:665)
        ... 8 more
Caused by: java.lang.UnsupportedOperationException
        at org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.AbstractJdbcCatalog.getCreateDatabaseSql(AbstractJdbcCatalog.java:414)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.AbstractJdbcCatalog.createDatabaseInternal(AbstractJdbcCatalog.java:419)
        ... 14 more
```

### Zeta or Flink or Spark Version

Zeta 

### Java or Scala Version

jdk8

### Screenshots

![image](https://github.com/apache/seatunnel/assets/44901627/6bb0ac2b-446e-41ca-9aa5-a7a6191b7674)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zengqinchris** [comment]
已经解决了，

**Comment by zengqinchris** [comment]
@Override
    protected String getListDatabaseSql() {
//        return "SELECT name FROM v$database";
        return "SELECT USERNAME as name FROM DBA_USERS";
    }
