### ISSUE TITLE
 java.lang.NoSuchMethodError: org.apache.hadoop.conf.Configuration.getTimeDuration

### ISSUE THREAD

**Issue by acshmily** [apache/seatunnel#6317]
I am trying to test the latest version of Seatunnel. When I attempt to perform HDFS file extraction using the Seatunnel Engine directly, I encounter the following error: "Exception in thread 'main' java.lang.NoSuchMethodError: org.apache.hadoop.conf.Configuration.getTimeDuration(Ljava/lang/String;JLjava/util/concurrent/TimeUnit;Ljava/util/concurrent/TimeUnit;)J". My Hadoop version is 2.6, and this issue only occurs when using the Seatunnel Engine; there are no problems when using Spark. Below is the configuration of my job logs.

(base) [root@collect1581049 apache-seatunnel-2.3.3]# ./bin/seatunnel.sh --config ./config/hdfs2obCompress2_copy_lzo_para.config
Jan 31, 2024 10:55:55 AM com.hazelcast.internal.config.AbstractConfigLocator
INFO: Loading configuration '/root/apache-seatunnel-2.3.3/config/seatunnel.yaml' from System property 'seatunnel.config'
Jan 31, 2024 10:55:55 AM com.hazelcast.internal.config.AbstractConfigLocator
INFO: Using configuration file at /root/apache-seatunnel-2.3.3/config/seatunnel.yaml
Jan 31, 2024 10:55:55 AM org.apache.seatunnel.engine.common.config.SeaTunnelConfig
INFO: seatunnel.home is /root/apache-seatunnel-2.3.3
Jan 31, 2024 10:55:55 AM com.hazelcast.internal.config.AbstractConfigLocator
INFO: Loading configuration '/root/apache-seatunnel-2.3.3/config/hazelcast.yaml' from System property 'hazelcast.config'
Jan 31, 2024 10:55:55 AM com.hazelcast.internal.config.AbstractConfigLocator
INFO: Using configuration file at /root/apache-seatunnel-2.3.3/config/hazelcast.yaml
Jan 31, 2024 10:55:56 AM com.hazelcast.internal.config.AbstractConfigLocator
INFO: Loading configuration '/root/apache-seatunnel-2.3.3/config/hazelcast-client.yaml' from System property 'hazelcast.client.config'
Jan 31, 2024 10:55:56 AM com.hazelcast.internal.config.AbstractConfigLocator
INFO: Using configuration file at /root/apache-seatunnel-2.3.3/config/hazelcast-client.yaml
2024-01-31 10:55:56,779 INFO  com.hazelcast.client.impl.spi.ClientInvocationService - hz.client_1 [seatunnel] [5.1] Running with 2 response threads, dynamic=true
2024-01-31 10:55:57,004 INFO  com.hazelcast.core.LifecycleService - hz.client_1 [seatunnel] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is STARTING
2024-01-31 10:55:57,006 INFO  com.hazelcast.core.LifecycleService - hz.client_1 [seatunnel] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is STARTED
2024-01-31 10:55:57,076 INFO  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel] [5.1] Trying to connect to cluster: seatunnel
2024-01-31 10:55:57,086 INFO  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel] [5.1] Trying to connect to [192.168.158.124]:5801
2024-01-31 10:55:57,187 INFO  com.hazelcast.core.LifecycleService - hz.client_1 [seatunnel] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is CLIENT_CONNECTED
2024-01-31 10:55:57,188 INFO  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel] [5.1] Authenticated with server [localhost]:5801:a86ec83c-a86f-41a3-bb28-dc1153f4ecc0, server version: 5.1, local address: /192.168.158.49:42948
2024-01-31 10:55:57,192 INFO  com.hazelcast.internal.diagnostics.Diagnostics - hz.client_1 [seatunnel] [5.1] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
2024-01-31 10:55:57,230 INFO  com.hazelcast.client.impl.spi.ClientClusterService - hz.client_1 [seatunnel] [5.1]

Members [1] {
        Member [localhost]:5801 - a86ec83c-a86f-41a3-bb28-dc1153f4ecc0
}

2024-01-31 10:55:57,312 INFO  com.hazelcast.client.impl.statistics.ClientStatisticsService - Client statistics is enabled with period 5 seconds.
2024-01-31 10:55:57,787 INFO  org.apache.seatunnel.engine.client.job.JobExecutionEnvironment - add common jar in plugins :[file:/root/apache-seatunnel-2.3.3/plugins/jdbc/lib/hive-jdbc-3.1.2.jar, file:/root/apache-seatunnel-2.3.3/plugins/jdbc/lib/oceanbase-client-2.4.3.jar]
2024-01-31 10:55:57,819 INFO  org.apache.seatunnel.core.starter.utils.ConfigBuilder - Loading config file from path: ./config/hdfs2obCompress2_copy_lzo_para.config
2024-01-31 10:55:57,918 INFO  org.apache.seatunnel.core.starter.utils.ConfigShadeUtils - Load config shade spi: [base64]
2024-01-31 10:55:57,990 INFO  org.apache.seatunnel.core.starter.utils.ConfigBuilder - Parsed config file: {
    "env" : {
        "job.name" : "hdfs2obCompress",
        "execution.parallelism" : 10,
        "job.mode" : "BATCH"
    },
    "source" : [
        {
            "fs.defaultFS" : "hdfs://ns1",
            "path" : "/user/data_test1/private/dws/dw_master_parquet_lzo",
            "file_format_type" : "parquet",
            "read_columns" : [
                "id",
                "account",
                "cust_name",
                "product_type",
                "province_code",
                "user_name",
                "user_phone",
                "create_time"
            ],
            "datetime_format" : "yyyy-MM-dd HH:mm:ss",
            "result_table_name" : "dw_master_parquet_lzo",
            "plugin_name" : "HdfsFile"
        }
    ],
    "transform" : [
        {
            "source_table_name" : "dw_master_parquet_lzo",
            "result_table_name" : "dw_master_parquet_Snappy",
            "fields" : {
                "id" : "id",
                "account" : "account",
                "cust_name" : "cust_name",
                "product_type" : "product_type",
                "province_code" : "province_code",
                "user_name" : "user_name",
                "user_phone" : "user_phone",
                "create_time" : "create_time"
            },
            "plugin_name" : "Copy"
        }
    ],
    "sink" : [
        {
            "password" : "123456",
            "database" : "data_test1",
            "driver" : "com.oceanbase.jdbc.Driver",
            "source_table_name" : "dw_master_parquet_Snappy",
            "compatible_mode" : "mysql",
            "generate_sink_sql" : true,
            "plugin_name" : "jdbc",
            "user" : "root",
            "url" : "jdbc:oceanbase://192.168.158.49:2881/data_test1",
            "table" : "dw_master_parquet_Snappy"
        }
    ]
}

2024-01-31 10:55:58,030 INFO  org.apache.seatunnel.api.configuration.ReadonlyConfig - Config uses fallback configuration key 'plugin_name' instead of key 'factory'
2024-01-31 10:55:58,032 INFO  org.apache.seatunnel.api.configuration.ReadonlyConfig - Config uses fallback configuration key 'plugin_name' instead of key 'factory'
2024-01-31 10:55:58,041 INFO  org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery - Load SeaTunnelSink Plugin from /root/apache-seatunnel-2.3.3/connectors/seatunnel
2024-01-31 10:55:58,053 INFO  org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery - Discovery plugin jar: HdfsFile at: file:/root/apache-seatunnel-2.3.3/connectors/seatunnel/connector-file-hadoop-2.3.3.jar
2024-01-31 10:55:58,054 INFO  org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery - Discovery plugin jar: jdbc at: file:/root/apache-seatunnel-2.3.3/connectors/seatunnel/connector-jdbc-2.3.3.jar
2024-01-31 10:55:58,062 WARN  org.apache.seatunnel.api.configuration.util.ConfigUtil - Option 'source_table_name' is a List, and it is recommended to configure it as ["string1","string2"]; we will only use ',' to split the String into a list.
2024-01-31 10:55:58,063 WARN  org.apache.seatunnel.api.configuration.util.ConfigUtil - Option 'source_table_name' is a List, and it is recommended to configure it as ["string1","string2"]; we will only use ',' to split the String into a list.
2024-01-31 10:55:58,065 INFO  org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser - start generating all sources.
2024-01-31 10:55:58,066 INFO  org.apache.seatunnel.api.configuration.ReadonlyConfig - Config uses fallback configuration key 'plugin_name' instead of key 'factory'
2024-01-31 10:55:58,163 INFO  org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery - Load SeaTunnelSource Plugin from /root/apache-seatunnel-2.3.3/connectors/seatunnel
2024-01-31 10:55:58,171 INFO  org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery - Discovery plugin jar: HdfsFile at: file:/root/apache-seatunnel-2.3.3/connectors/seatunnel/connector-file-hadoop-2.3.3.jar
2024-01-31 10:55:58,176 INFO  org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery - Load plugin: PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='HdfsFile'} from classpath
2024-01-31 10:55:58,299 WARN  org.apache.seatunnel.connectors.seatunnel.file.sink.util.FileSystemUtils - Principal [null] or keytabPath [null] is empty, it will skip kerberos authentication
2024-01-31 10:55:58,546 WARN  org.apache.hadoop.util.NativeCodeLoader - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2024-01-31 10:55:58,800 WARN  org.apache.hadoop.fs.FileSystem - Cannot load filesystem: java.util.ServiceConfigurationError: org.apache.hadoop.fs.FileSystem: Provider org.apache.hadoop.fs.s3native.NativeS3FileSystem not found
2024-01-31 10:55:58,828 WARN  org.apache.hadoop.fs.FileSystem - Cannot load filesystem: java.util.ServiceConfigurationError: org.apache.hadoop.fs.FileSystem: Provider org.apache.hadoop.fs.s3native.NativeS3FileSystem not found
2024-01-31 10:55:58,878 INFO  com.hazelcast.core.LifecycleService - hz.client_1 [seatunnel] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is SHUTTING_DOWN
2024-01-31 10:55:58,887 INFO  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel] [5.1] Removed connection to endpoint: [localhost]:5801:a86ec83c-a86f-41a3-bb28-dc1153f4ecc0, connection: ClientConnection{alive=false, connectionId=1, channel=NioChannel{/192.168.158.49:42948->/192.168.158.124:5801}, remoteAddress=[localhost]:5801, lastReadTime=2024-01-31 10:55:57.807, lastWriteTime=2024-01-31 10:55:57.805, closedTime=2024-01-31 10:55:58.881, connected server version=5.1}
2024-01-31 10:55:58,888 INFO  com.hazelcast.core.LifecycleService - hz.client_1 [seatunnel] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is CLIENT_DISCONNECTED
2024-01-31 10:55:58,895 INFO  com.hazelcast.core.LifecycleService - hz.client_1 [seatunnel] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is SHUTDOWN
2024-01-31 10:55:58,896 INFO  org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand - Closed SeaTunnel client......
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.hadoop.conf.Configuration.getTimeDuration(Ljava/lang/String;JLjava/util/concurrent/TimeUnit;Ljava/util/concurrent/TimeUnit;)J
        at org.apache.hadoop.hdfs.client.impl.DfsClientConf.<init>(DfsClientConf.java:248)
        at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:306)
        at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:290)
        at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:172)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3242)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:121)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3291)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3259)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:470)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:223)
        at org.apache.seatunnel.connectors.seatunnel.file.source.reader.AbstractReadStrategy.getFileNamesByPath(AbstractReadStrategy.java:127)
        at org.apache.seatunnel.connectors.seatunnel.file.hdfs.source.BaseHdfsFileSource.prepare(BaseHdfsFileSource.java:76)
        at org.apache.seatunnel.connectors.seatunnel.file.hdfs.source.HdfsFileSource.prepare(HdfsFileSource.java:38)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSource(JobConfigParser.java:85)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:317)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:179)
        at org.apache.seatunnel.engine.core.job.AbstractJobEnvironment.getLogicalDag(AbstractJobEnvironment.java:109)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:73)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:143)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)

**Comment by WuJiY** [comment]
same too

**Comment by USTB-JXY** [comment]
do you solve it ,please help me ,thank you @acshmily

**Comment by acshmily** [comment]
> do you solve it ,please help me ,thank you @acshmily

nope,  give it up ,and change other tools

**Comment by acshmily** [comment]
no answer
