### ISSUE TITLE
[Bug] [JDBC] sftp to jdbc doris 

### ISSUE THREAD

**Issue by zengqinchris** [apache/seatunnel#6318]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

sftp to jdbc doris error 
Caused by: java.sql.SQLException: errCode = 2, detailMessage = Unexpected exception: null
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1098)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:832)
        ... 28 more

        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:191)

sftp 数据

id,Name,age,address,Remark,d,t,digital
1,m_sdt_1,21,sdt111,x11111,2023-05-23,2023-05-23 17:29:32,88.001
8,m_sdt_1,21,sdt111,x11111,2023-05-23,2023-05-23 17:32:29,88.002
13,m_sdt_1,21,sdt111,x11111,2023-05-23,2023-05-23 17:33:31,88.003
14,m_sdt_2,22,sdt222,x22222,2023-05-23,2023-05-23 17:33:31,82.004
15,m_sdt_1,21,sdt111,x11111,2023-05-23,2023-05-23 17:33:35,88.005
16,m_sdt_2,22,sdt222,x22222,2023-05-23,2023-05-23 17:33:35,82.006
17,m_sdt_3,23,sdt333,x33333,2023-05-23,2023-05-23 17:33:35,83.007
18,m_sdt_4,24,sdt444,x44444,2023-05-23,2023-05-23 17:33:35,84.008
19,m_sdt_5,25,sdt555,x55555,2023-05-23,2023-05-23 17:33:35,85.009
20,m_sdt_6,26,sdt666,x66666,2023-05-23,2023-05-23 17:33:35,86.010

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
env {
parallelism = 1
job.mode = "BATCH" 
checkpoint.interval = 900000 
}
source {
SftpFile { 
path = "/upload/sftp_datatype.csv" 
 host = "172.21.129.219" 
 port = 10022 
 user = "test" 
 password = "sftptest" 
 file_format_type = "csv" 
 skip_header_row_number = 1 
 delimiter = "," 
 schema = {  
 fields  { 
 column0=string
column1=string
column2=string
column3=string
column4=string
column5=string
column6=string
column7=string  
 } 
} 
result_table_name = "yundee_source0"  
} 
}
transform {
Sql { 
source_table_name = "yundee_source0"  
 result_table_name = "yundee_sink0"  
 query = " select column0 as id,column1 as name,column2 as age,column3 as address,column4 as remark,column5 as ds,column6 as dts,column7 as diagtals from yundee_source0 "  
 } 
}
sink {
jdbc { 
source_table_name = "yundee_sink0"   
url = "jdbc:mysql://172.21.129.213:16930/yddb" 
 driver = "com.mysql.cj.jdbc.Driver" 
 user = "1" 
 password = "1" 
 max_retries = 3 
 generate_sink_sql = "true" 
 database = "yddb" 
 table = "sftp_yddb_data_type" 
 primary_keys = [] 
 } 
}
```

### Running Command

```shell
./bin/seatunnel.sh -c ./config/aa.conf
```

### Error Exception

```log
==============================================================================


2024-01-31 15:34:14,886 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Fatal Error, 

2024-01-31 15:34:14,886 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Please submit bug report in https://github.com/apache/seatunnel/issues

2024-01-31 15:34:14,886 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Reason:SeaTunnel job executed failed 

2024-01-31 15:34:14,888 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:199)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: java.lang.RuntimeException: org.apache.seatunnel.connectors.seatunnel.jdbc.exception.JdbcConnectorException: ErrorCode:[COMMON-10], ErrorDescription:[Flush data operation that in sink connector failed]
        at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:246)
        at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:64)
        at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:39)
        at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:27)
        at org.apache.seatunnel.engine.server.task.group.queue.IntermediateBlockingQueue.handleRecord(IntermediateBlockingQueue.java:70)
        at org.apache.seatunnel.engine.server.task.group.queue.IntermediateBlockingQueue.collect(IntermediateBlockingQueue.java:50)
        at org.apache.seatunnel.engine.server.task.flow.IntermediateQueueFlowLifeCycle.collect(IntermediateQueueFlowLifeCycle.java:51)
        at org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask.collect(TransformSeaTunnelTask.java:73)
        at org.apache.seatunnel.engine.server.task.SeaTunnelTask.stateProcess(SeaTunnelTask.java:168)
        at org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask.call(TransformSeaTunnelTask.java:78)
        at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:641)
        at org.apache.seatunnel.engine.server.TaskExecutionService$NamedTaskWrapper.run(TaskExecutionService.java:937)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.seatunnel.connectors.seatunnel.jdbc.exception.JdbcConnectorException: ErrorCode:[COMMON-10], ErrorDescription:[Flush data operation that in sink connector failed]
        at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.JdbcOutputFormat.flush(JdbcOutputFormat.java:137)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.sink.JdbcSinkWriter.prepareCommit(JdbcSinkWriter.java:137)
        at org.apache.seatunnel.connectors.seatunnel.common.multitablesink.MultiTableSinkWriter.prepareCommit(MultiTableSinkWriter.java:185)
        at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:175)
        ... 16 more
Caused by: java.sql.BatchUpdateException: errCode = 2, detailMessage = Unexpected exception: null
        at sun.reflect.GeneratedConstructorAccessor117.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.cj.util.Util.handleNewInstance(Util.java:192)
        at com.mysql.cj.util.Util.getInstance(Util.java:167)
        at com.mysql.cj.util.Util.getInstance(Util.java:174)
        at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:224)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:853)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:435)
        at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:800)
        at org.apache.seatunnel.shade.com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:127)
        at org.apache.seatunnel.shade.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.executor.FieldNamedPreparedStatement.executeBatch(FieldNamedPreparedStatement.java:533)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.executor.SimpleBatchStatementExecutor.executeBatch(SimpleBatchStatementExecutor.java:51)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.executor.BufferedBatchStatementExecutor.executeBatch(BufferedBatchStatementExecutor.java:53)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.JdbcOutputFormat.attemptFlush(JdbcOutputFormat.java:167)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.JdbcOutputFormat.flush(JdbcOutputFormat.java:131)
        ... 19 more
Caused by: java.sql.SQLException: errCode = 2, detailMessage = Unexpected exception: null
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1098)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:832)
        ... 28 more

        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:191)
        ... 2 more
 
2024-01-31 15:34:14,889 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - 
===============================================================================
```

### Zeta or Flink or Spark Version

Zeta

### Java or Scala Version

jdk8

### Screenshots

![image](https://github.com/apache/seatunnel/assets/44901627/8bd0d9cd-6649-4730-8e08-f11510b21ec3)
![image](https://github.com/apache/seatunnel/assets/44901627/96f09d87-4907-4cd2-9189-c12d6b8bb308)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zengqinchris** [comment]
已经解决。表的字段类型不匹配导致的

**Comment by HT-cyber** [comment]
你好，我也遇到了类似问题，似乎seatunnel读取excel文件是无法自动类型转换的，想请问是否有进一步解决？
