### ISSUE TITLE
[Bug] [rest-api] /hazelcast/rest/maps/running-jobs Request failed java.lang.NullPointerException

### ISSUE THREAD

**Issue by W-dragan** [apache/seatunnel#6325]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When I deploy in cluster mode, roll up seatunel, and access runtime tasks using restApi, this error is reported
Due to some reasons, the image cannot be uploaded, and its null pointer occurs on line 344 of RestHttpGetCommandProcessor.java

      
![image](https://github.com/apache/seatunnel/assets/69575498/b79dd98d-9a3f-4847-9526-237af78dc57d)

When I completely stop the cluster and restart it, this problem will not occur. Once I roll restart, this problem will occur

### SeaTunnel Version

2.3.4

### SeaTunnel Config

```conf
pass
```

### Running Command

```shell
pass
```

### Error Exception

```log
{"status":"fail","message":"java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException"}
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by W-dragan** [comment]
And only the handleRunningJobsInfo method will have this issue, handleFinishedJobsInfo will not have this issue.
If this problem occurs again online in the future, the log will be filled in

**Comment by W-dragan** [comment]
@liugddx Can you help me take a look，滚动升级重启以后访问运行时任务就会发生这个错误

**Comment by W-dragan** [comment]
I speculate that some task information was lost during the rolling restart, but jobId was still present, resulting in a null pointer when querying through jobId. Of course, this is just speculation. Should we make a fault tolerance for the situation where jobId exists but specific jobMetrics do not exist

**Comment by liugddx** [comment]
Is there any detailed  log?

**Comment by ezra-sullivan** [comment]
在滚动重启的时候，遇到了同样的问题，版本 2.3.4

以下为详细日志
```
2024-04-21 14:10:51,604 ERROR [s.e.s.o.GetJobMetricsOperation] [hz.main.generic-operation.thread-20] - [seatunnel-0.seatunnel.seatunnel.svc.cluster.local]:5801 [seatunnel] [5.1] java.util.concurrent.ExecutionException: java.lang.NullPointerException
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at org.apache.seatunnel.engine.server.operation.GetJobMetricsOperation.run(GetJobMetricsOperation.java:87) ~[seatunnel-starter.jar:2.3.4]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) ~[seatunnel-starter.jar:2.3.4]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:273) ~[seatunnel-starter.jar:2.3.4]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) ~[seatunnel-starter.jar:2.3.4]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:471) ~[seatunnel-starter.jar:2.3.4]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197) ~[seatunnel-starter.jar:2.3.4]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137) ~[seatunnel-starter.jar:2.3.4]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) ~[seatunnel-starter.jar:2.3.4]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[seatunnel-starter.jar:2.3.4]
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_312]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908) ~[?:1.8.0_312]
	at org.apache.seatunnel.engine.server.operation.GetJobMetricsOperation.run(GetJobMetricsOperation.java:85) ~[seatunnel-starter.jar:2.3.4]
	... 8 more
Caused by: java.lang.NullPointerException
	at org.apache.seatunnel.engine.server.operation.GetJobMetricsOperation.lambda$run$0(GetJobMetricsOperation.java:78) ~[seatunnel-starter.jar:2.3.4]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[?:1.8.0_312]
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217) ~[seatunnel-starter.jar:2.3.4]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_312]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[seatunnel-starter.jar:2.3.4]
	... 1 more
2024-04-21 14:10:51,618 WARN  [.Log4j2HttpGetCommandProcessor] [hz.main.cached.thread-6] - [seatunnel-2.seatunnel.seatunnel.svc.cluster.local]:5801 [seatunnel] [5.1] An error occurred while handling request HttpCommand [HTTP_GET]{uri='/hazelcast/rest/maps/running-jobs'}AbstractTextCommand[HTTP_GET]{requestId=0}
java.util.concurrent.CompletionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at com.hazelcast.spi.impl.AbstractInvocationFuture.returnOrThrowWithJoinConventions(AbstractInvocationFuture.java:819) ~[seatunnel-starter.jar:2.3.4]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.resolveAndThrowWithJoinConvention(AbstractInvocationFuture.java:835) ~[seatunnel-starter.jar:2.3.4]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.join(AbstractInvocationFuture.java:553) ~[seatunnel-starter.jar:2.3.4]
	at org.apache.seatunnel.engine.server.rest.RestHttpGetCommandProcessor.convertToJson(RestHttpGetCommandProcessor.java:365) ~[seatunnel-starter.jar:2.3.4]
	at org.apache.seatunnel.engine.server.rest.RestHttpGetCommandProcessor.lambda$handleRunningJobsInfo$2(RestHttpGetCommandProcessor.java:175) ~[seatunnel-starter.jar:2.3.4]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_312]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_312]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_312]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_312]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_312]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_312]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_312]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:577) ~[?:1.8.0_312]
	at org.apache.seatunnel.engine.server.rest.RestHttpGetCommandProcessor.handleRunningJobsInfo(RestHttpGetCommandProcessor.java:177) ~[seatunnel-starter.jar:2.3.4]
	at org.apache.seatunnel.engine.server.rest.RestHttpGetCommandProcessor.handle(RestHttpGetCommandProcessor.java:101) ~[seatunnel-starter.jar:2.3.4]
	at org.apache.seatunnel.engine.server.rest.RestHttpGetCommandProcessor.handle(RestHttpGetCommandProcessor.java:73) ~[seatunnel-starter.jar:2.3.4]
	at com.hazelcast.internal.ascii.TextCommandServiceImpl$CommandExecutor.run(TextCommandServiceImpl.java:402) ~[seatunnel-starter.jar:2.3.4]
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217) ~[seatunnel-starter.jar:2.3.4]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_312]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[seatunnel-starter.jar:2.3.4]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[seatunnel-starter.jar:2.3.4]
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at org.apache.seatunnel.engine.server.operation.GetJobMetricsOperation.run(GetJobMetricsOperation.java:87) ~[seatunnel-starter.jar:2.3.4]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) ~[seatunnel-starter.jar:2.3.4]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:273) ~[seatunnel-starter.jar:2.3.4]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) ~[seatunnel-starter.jar:2.3.4]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:471) ~[seatunnel-starter.jar:2.3.4]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197) ~[seatunnel-starter.jar:2.3.4]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137) ~[seatunnel-starter.jar:2.3.4]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) ~[seatunnel-starter.jar:2.3.4]
	... 1 more
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_312]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908) ~[?:1.8.0_312]
	at org.apache.seatunnel.engine.server.operation.GetJobMetricsOperation.run(GetJobMetricsOperation.java:85) ~[seatunnel-starter.jar:2.3.4]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) ~[seatunnel-starter.jar:2.3.4]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:273) ~[seatunnel-starter.jar:2.3.4]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) ~[seatunnel-starter.jar:2.3.4]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:471) ~[seatunnel-starter.jar:2.3.4]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197) ~[seatunnel-starter.jar:2.3.4]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137) ~[seatunnel-starter.jar:2.3.4]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) ~[seatunnel-starter.jar:2.3.4]
	... 1 more
Caused by: java.lang.NullPointerException
	at org.apache.seatunnel.engine.server.operation.GetJobMetricsOperation.lambda$run$0(GetJobMetricsOperation.java:78) ~[seatunnel-starter.jar:2.3.4]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[?:1.8.0_312]
	... 6 more
2024-04-21 14:11:00,319 INFO  [o.a.s.e.s.CoordinatorService  ] [pool-5-thread-1] - [seatunnel-1.seatunnel.seatunnel.svc.cluster.local]:5801 [seatunnel] [5.1] 
***********************************************
```

**Comment by W-dragan** [comment]
@liugddx cc

**Comment by W-dragan** [comment]
This problem occurred again today, and it has nothing to do with the rolling restart. We suspect that the metadata of a certain task cannot be obtained, or there is a problem with writing, causing an error when obtaining the running task list directly. Regardless of what caused the metadata of a certain task to not be obtained, should we consider the robustness of the code and not let the metadata error of a certain task affect the viewing of the entire running task list

**Comment by W-dragan** [comment]
@liugddx @Hisoka-X @hailin0 help cc

**Comment by liugddx** [comment]
> @liugddx @Hisoka-X @hailin0 help cc

What version are you using?

**Comment by W-dragan** [comment]
> > @liugddx @Hisoka-X @hailin0 help cc
> 
> What version are you using?

2.3.5
