### ISSUE TITLE
Cannot detect ES version

### ISSUE THREAD

**Issue by x956606865** [apache/seatunnel#633]
我这里使用的是2.0.4版本的waterdrop，elasticsearch模块似乎依旧不支持7以上的版本。我使用6.8版本的ES时，能够正常连接使用，但是使用7.5版本的ES时，就会报错，说“Cannot detect ES version”。
请问是不是改的时候忘了更新2.0版本的插件了Orz
**Waterdrop Version(Waterdrop版本)**
2.0.4

**Flink or Spark Version(Flink 或者 Spark 版本)**

Spark 2.4.8

**Java or Scala Version(Java或者Scala版本)**

openjdk version "1.8.0_292"

**Waterdrop Config(Waterdrop配置文件)**

Please delete sensitive information(请注意删除敏感信息)

```
env {
  # Waterdrop defined streaming batch duration in seconds
  spark.streaming.batchDuration = 5

  spark.app.name = "Waterdrop"
  spark.ui.port = 13000
}

source {
 elasticsearch {
        hosts = ["http://192.168.1.201:9200"]
        index = "test"
        result_table_name = "my_dataset"
    }
}

transform {}

sink {
  console {}
}
```

**Running Command(启动命令)**

waterdrop-spark.sh --master local --deploy-mode client --config ../config/application.conf

**Error Exception**
Fatal Error, 

Please contact garygaowork@gmail.com or issue a bug in https://github.com/InterestingLab/waterdrop/issues

Reason: Cannot detect ES version - typically this happens if the network/Elasticsearch cluster is not accessible or when targeting a WAN/Cloud instance without the proper setting 'es.nodes.wan.only'

Exception StackTrace: org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Cannot detect ES version - typically this happens if the network/Elasticsearch cluster is not accessible or when targeting a WAN/Cloud instance without the proper setting 'es.nodes.wan.only'
	at org.elasticsearch.hadoop.rest.InitializationUtils.discoverClusterInfo(InitializationUtils.java:344)
	at org.elasticsearch.spark.sql.ElasticsearchRelation.cfg$lzycompute(DefaultSource.scala:225)
	at org.elasticsearch.spark.sql.ElasticsearchRelation.cfg(DefaultSource.scala:223)
	at org.elasticsearch.spark.sql.ElasticsearchRelation.lazySchema$lzycompute(DefaultSource.scala:229)
	at org.elasticsearch.spark.sql.ElasticsearchRelation.lazySchema(DefaultSource.scala:229)
	at org.elasticsearch.spark.sql.ElasticsearchRelation$$anonfun$schema$1.apply(DefaultSource.scala:233)
	at org.elasticsearch.spark.sql.ElasticsearchRelation$$anonfun$schema$1.apply(DefaultSource.scala:233)
	at scala.Option.getOrElse(Option.scala:121)
	at org.elasticsearch.spark.sql.ElasticsearchRelation.schema(DefaultSource.scala:233)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:417)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:242)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:230)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:197)
	at io.github.interestinglab.waterdrop.spark.source.Elasticsearch.getData(Elasticsearch.scala:42)
	at io.github.interestinglab.waterdrop.spark.source.Elasticsearch.getData(Elasticsearch.scala:10)
	at io.github.interestinglab.waterdrop.spark.batch.SparkBatchExecution$.registerInputTempView(SparkBatchExecution.scala:68)
	at io.github.interestinglab.waterdrop.spark.batch.SparkBatchExecution$$anonfun$start$1.apply(SparkBatchExecution.scala:31)
	at io.github.interestinglab.waterdrop.spark.batch.SparkBatchExecution$$anonfun$start$1.apply(SparkBatchExecution.scala:30)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at io.github.interestinglab.waterdrop.spark.batch.SparkBatchExecution.start(SparkBatchExecution.scala:30)
	at io.github.interestinglab.waterdrop.Waterdrop.entryPoint(Waterdrop.java:91)
	at io.github.interestinglab.waterdrop.Waterdrop.run(Waterdrop.java:50)
	at io.github.interestinglab.waterdrop.Waterdrop.main(Waterdrop.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:855)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:930)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:939)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Unsupported/Unknown Elasticsearch version 7.5.1
	at org.elasticsearch.hadoop.util.EsMajorVersion.parse(EsMajorVersion.java:87)
	at org.elasticsearch.hadoop.rest.RestClient.mainInfo(RestClient.java:703)
	at org.elasticsearch.hadoop.rest.InitializationUtils.discoverClusterInfo(InitializationUtils.java:334)
	... 37 more

**Screenshots**
If applicable, add screenshots to help explain your problem.（您可以将相关截图放在此处）

我这里使用的是2.0.4版本的waterdrop，elasticsearch模块似乎依旧不支持7以上的版本。我使用6.8版本的ES时，能够正常连接使用，但是使用7.5版本的ES时，就会报错，说“Cannot detect ES version”。
请问是不是现在依旧不能支持7以上版本的ES？

**Comment by garyelephant** [comment]
@x956606865 你好，目前需要自行在代码pom依赖中升级支持一下

**Comment by x956606865** [comment]
> @x956606865 你好，目前需要自行在代码pom依赖中升级支持一下

非常不好意思，因为我不是java相关的开发者，请问能具体说一下要怎么做吗？
