### ISSUE TITLE
[Bug] [apache-seatunnel-web-1.0.0-bin]  sh bin/seatunnel-backend-daemon.sh start  faild log is  Unable to start web server; nested exception is java.lang.IllegalArgumentException: No selectors

### ISSUE THREAD

**Issue by liuhaichaogithub** [apache/seatunnel#6334]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

when  I  sh bin/seatunnel-backend-daemon.sh start   ==》 faild   ， log is 
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2024-02-04 15:10:35.275 seatunnel liuhaichao ERROR [tr:,sp:] [main] [SpringApplication.reportFailure():835] - Application run failed
org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is java.lang.IllegalArgumentException: No selectors
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:163)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:577)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:745)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:420)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
        at org.apache.seatunnel.app.SeatunnelApplication.main(SeatunnelApplication.java:36)
Caused by: java.lang.IllegalArgumentException: No selectors
        at org.eclipse.jetty.io.SelectorManager.<init>(SelectorManager.java:63)
        at org.eclipse.jetty.server.ServerConnector$ServerConnectorManager.<init>(ServerConnector.java:600)
        at org.eclipse.jetty.server.ServerConnector.newSelectorManager(ServerConnector.java:223)
        at org.eclipse.jetty.server.ServerConnector.<init>(ServerConnector.java:216)
        at org.eclipse.jetty.server.ServerConnector.<init>(ServerConnector.java:132)
        at org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory.createConnector(JettyServletWebServerFactory.java:200)
        at org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory.createServer(JettyServletWebServerFactory.java:186)
        at org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory.getWebServer(JettyServletWebServerFactory.java:163)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:182)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:160)
        ... 8 common frames omitted

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
...
```

### Running Command

```shell
sh bin/seatunnel-backend-daemon.sh start
```

### Error Exception

```log
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2024-02-04 15:10:35.275 seatunnel liuhaichao ERROR [tr:,sp:] [main] [SpringApplication.reportFailure():835] - Application run failed
org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is java.lang.IllegalArgumentException: No selectors
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:163)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:577)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:745)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:420)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
        at org.apache.seatunnel.app.SeatunnelApplication.main(SeatunnelApplication.java:36)
Caused by: java.lang.IllegalArgumentException: No selectors
        at org.eclipse.jetty.io.SelectorManager.<init>(SelectorManager.java:63)
        at org.eclipse.jetty.server.ServerConnector$ServerConnectorManager.<init>(ServerConnector.java:600)
        at org.eclipse.jetty.server.ServerConnector.newSelectorManager(ServerConnector.java:223)
        at org.eclipse.jetty.server.ServerConnector.<init>(ServerConnector.java:216)
        at org.eclipse.jetty.server.ServerConnector.<init>(ServerConnector.java:132)
        at org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory.createConnector(JettyServletWebServerFactory.java:200)
        at org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory.createServer(JettyServletWebServerFactory.java:186)
        at org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory.getWebServer(JettyServletWebServerFactory.java:163)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:182)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:160)
        ... 8 common frames omitted
```

### Java or Scala Version

java version "1.8.0_401"

### Screenshots

![image](https://github.com/apache/seatunnel/assets/40063899/d51d749d-07ee-476a-8a93-142038dac052)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by COCONUTYA1** [comment]
cd apache-seatunnel-web-1.0.0-bin/libs
rm -rf datasource-hive-1.0.0.jar

**Comment by GangLiCN** [comment]
The similar exception listed below is also caused by this "problematic" hive jar file:

> An attempt was made to call a method that does not exist. The attempt was made from the following location:
    org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory.configureSession(JettyServletWebServerFactory.java:267)

The following method did not exist:

    org.eclipse.jetty.server.session.SessionHandler.setMaxInactiveInterval(I)V

The calling method's class, org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory, was loaded from the following location:

    jar:file:/G:/Apache/apache-seatunnel-web-1.0.0-bin/libs/spring-boot-2.6.8.jar!/org/springframework/boot/web/embedded/jetty/JettyServletWebServerFactory.class

The called method's class, org.eclipse.jetty.server.session.SessionHandler, is available from the following locations:

    jar:file:/G:/Apache/apache-seatunnel-web-1.0.0-bin/libs/datasource-hive-1.0.0.jar!/org/eclipse/jetty/server/session/SessionHandler.class
    jar:file:/G:/Apache/apache-seatunnel-web-1.0.0-bin/libs/jetty-server-9.4.46.v20220331.jar!/org/eclipse/jetty/server/session/SessionHandler.class

The called method's class hierarchy was loaded from the following locations:

    org.eclipse.jetty.server.session.SessionHandler: file:/G:/Apache/apache-seatunnel-web-1.0.0-bin/libs/datasource-hive-1.0.0.jar
    org.eclipse.jetty.server.handler.ScopedHandler: file:/G:/Apache/apache-seatunnel-web-1.0.0-bin/libs/datasource-hive-1.0.0.jar
    org.eclipse.jetty.server.handler.HandlerWrapper: file:/G:/Apache/apache-seatunnel-web-1.0.0-bin/libs/datasource-hive-1.0.0.jar
    org.eclipse.jetty.server.handler.AbstractHandlerContainer: file:/G:/Apache/apache-seatunnel-web-1.0.0-bin/libs/datasource-hive-1.0.0.jar
    org.eclipse.jetty.server.handler.AbstractHandler: file:/G:/Apache/apache-seatunnel-web-1.0.0-bin/libs/datasource-hive-1.0.0.jar
    org.eclipse.jetty.util.component.ContainerLifeCycle: file:/G:/Apache/apache-seatunnel-web-1.0.0-bin/libs/datasource-hive-1.0.0.jar
    org.eclipse.jetty.util.component.AbstractLifeCycle: file:/G:/Apache/apache-seatunnel-web-1.0.0-bin/libs/datasource-hive-1.0.0.jar


Action:
Correct the classpath of your application so that it contains compatible versions of the classes org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory and org.eclipse.jetty.server.session.SessionHandler

**Comment by GangLiCN** [comment]
The similar exception listed as below is also caused by this "problematic" hive jar file:, the issue was triggered when starting seatunner server.

> 
An attempt was made to call a method that does not exist. The attempt was made from the following location:
    org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory.configureSession(JettyServletWebServerFactory.java:267)

The following method did not exist:

    org.eclipse.jetty.server.session.SessionHandler.setMaxInactiveInterval(I)V

The calling method's class, org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory, was loaded from the following location:

    jar:file:/G:/Apache/apache-seatunnel-web-1.0.0-bin/libs/spring-boot-2.6.8.jar!/org/springframework/boot/web/embedded/jetty/JettyServletWebServerFactory.class

The called method's class, org.eclipse.jetty.server.session.SessionHandler, is available from the following locations:

    jar:file:/G:/Apache/apache-seatunnel-web-1.0.0-bin/libs/datasource-hive-1.0.0.jar!/org/eclipse/jetty/server/session/SessionHandler.class
    jar:file:/G:/Apache/apache-seatunnel-web-1.0.0-bin/libs/jetty-server-9.4.46.v20220331.jar!/org/eclipse/jetty/server/session/SessionHandler.class

The called method's class hierarchy was loaded from the following locations:

    org.eclipse.jetty.server.session.SessionHandler: file:/G:/Apache/apache-seatunnel-web-1.0.0-bin/libs/datasource-hive-1.0.0.jar
    org.eclipse.jetty.server.handler.ScopedHandler: file:/G:/Apache/apache-seatunnel-web-1.0.0-bin/libs/datasource-hive-1.0.0.jar
    org.eclipse.jetty.server.handler.HandlerWrapper: file:/G:/Apache/apache-seatunnel-web-1.0.0-bin/libs/datasource-hive-1.0.0.jar
    org.eclipse.jetty.server.handler.AbstractHandlerContainer: file:/G:/Apache/apache-seatunnel-web-1.0.0-bin/libs/datasource-hive-1.0.0.jar
    org.eclipse.jetty.server.handler.AbstractHandler: file:/G:/Apache/apache-seatunnel-web-1.0.0-bin/libs/datasource-hive-1.0.0.jar
    org.eclipse.jetty.util.component.ContainerLifeCycle: file:/G:/Apache/apache-seatunnel-web-1.0.0-bin/libs/datasource-hive-1.0.0.jar
    org.eclipse.jetty.util.component.AbstractLifeCycle: file:/G:/Apache/apache-seatunnel-web-1.0.0-bin/libs/datasource-hive-1.0.0.jar


Action:
Correct the classpath of your application so that it contains compatible versions of the classes org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory and org.eclipse.jetty.server.session.SessionHandler
>

**Comment by Wudadada** [comment]
> rm -rf datasource-hive-1.0.0.jar

same problem

**Comment by Wudadada** [comment]
> The similar exception listed as below is also caused by this "problematic" hive jar file:, the issue was triggered when starting seatunner server.
> 
> > 
> 
> An attempt was made to call a method that does not exist. The attempt was made from the following location: org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory.configureSession(JettyServletWebServerFactory.java:267)
> 
> The following method did not exist:
> 
> ```
> org.eclipse.jetty.server.session.SessionHandler.setMaxInactiveInterval(I)V
> ```
> 
> The calling method's class, org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory, was loaded from the following location:
> 
> ```
> jar:file:/G:/Apache/apache-seatunnel-web-1.0.0-bin/libs/spring-boot-2.6.8.jar!/org/springframework/boot/web/embedded/jetty/JettyServletWebServerFactory.class
> ```
> 
> The called method's class, org.eclipse.jetty.server.session.SessionHandler, is available from the following locations:
> 
> ```
> jar:file:/G:/Apache/apache-seatunnel-web-1.0.0-bin/libs/datasource-hive-1.0.0.jar!/org/eclipse/jetty/server/session/SessionHandler.class
> jar:file:/G:/Apache/apache-seatunnel-web-1.0.0-bin/libs/jetty-server-9.4.46.v20220331.jar!/org/eclipse/jetty/server/session/SessionHandler.class
> ```
> 
> The called method's class hierarchy was loaded from the following locations:
> 
> ```
> org.eclipse.jetty.server.session.SessionHandler: file:/G:/Apache/apache-seatunnel-web-1.0.0-bin/libs/datasource-hive-1.0.0.jar
> org.eclipse.jetty.server.handler.ScopedHandler: file:/G:/Apache/apache-seatunnel-web-1.0.0-bin/libs/datasource-hive-1.0.0.jar
> org.eclipse.jetty.server.handler.HandlerWrapper: file:/G:/Apache/apache-seatunnel-web-1.0.0-bin/libs/datasource-hive-1.0.0.jar
> org.eclipse.jetty.server.handler.AbstractHandlerContainer: file:/G:/Apache/apache-seatunnel-web-1.0.0-bin/libs/datasource-hive-1.0.0.jar
> org.eclipse.jetty.server.handler.AbstractHandler: file:/G:/Apache/apache-seatunnel-web-1.0.0-bin/libs/datasource-hive-1.0.0.jar
> org.eclipse.jetty.util.component.ContainerLifeCycle: file:/G:/Apache/apache-seatunnel-web-1.0.0-bin/libs/datasource-hive-1.0.0.jar
> org.eclipse.jetty.util.component.AbstractLifeCycle: file:/G:/Apache/apache-seatunnel-web-1.0.0-bin/libs/datasource-hive-1.0.0.jar
> ```
> 
> Action: Correct the classpath of your application so that it contains compatible versions of the classes org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory and org.eclipse.jetty.server.session.SessionHandler
> 
> >

same problem

**Comment by channingwen** [comment]
> cd apache-seatunnel-web-1.0.0-bin/libs rm -rf datasource-hive-1.0.0.jar

yes， I got same problem，delete this jar is ok。
