### ISSUE TITLE
com.hazelcast.client.AuthenticationException: Authentication failed

### ISSUE THREAD

**Issue by avatarTaier** [apache/seatunnel#6400]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Failed on Oracle JDK 11

### SeaTunnel Version

2.3.4

### SeaTunnel Config

```conf
config/v2.batch.config.template
```

### Running Command

```shell
sudo bin/seatunnel.sh --config config/v2.batch.config.template -e local
```

### Error Exception

```log
2024-02-28 03:46:28,599 INFO  com.hazelcast.client.impl.connection.ClientConnectionManager - hz.client_1 [seatunnel-81304] [5.1] Trying to connect to [localhos
t]:5801
2024-02-28 03:46:28,616 WARN  com.hazelcast.client.impl.connection.tcp.TcpClientConnection - hz.client_1 [seatunnel-81304] [5.1] ClientConnection{alive=false, 
connectionId=1, channel=NioChannel{/127.0.0.1:46967->localhost/127.0.0.1:5801}, remoteAddress=null, lastReadTime=2024-02-28 03:46:28.613, lastWriteTime=2024-02
-28 03:46:28.612, closedTime=2024-02-28 03:46:28.615, connected server version=null} closed. Reason: Failed to authenticate connection
com.hazelcast.client.AuthenticationException: Authentication failed. The configured cluster name on the client (see ClientConfig.setClusterName()) does not mat
ch the one configured in the cluster or the credentials set in the Client security config could not be authenticated
        at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.checkAuthenticationResponse(TcpClientConnectionManager.java:995) ~[seatunnel-sta
rter.jar:2.3.4]
        at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.onAuthenticated(TcpClientConnectionManager.java:898) ~[seatunnel-starter.jar:2.3
.4]
        at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.getOrConnectToAddress(TcpClientConnectionManager.java:615) ~[seatunnel-starter.j
ar:2.3.4]
        at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.lambda$doConnectToCandidateCluster$3(TcpClientConnectionManager.java:505) ~[seat
unnel-starter.jar:2.3.4]
        at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.connect(TcpClientConnectionManager.java:459) [seatunnel-starter.jar:2.3.4]      
        at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.doConnectToCandidateCluster(TcpClientConnectionManager.java:505) [seatunnel-star
ter.jar:2.3.4]
        at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.doConnectToCluster(TcpClientConnectionManager.java:411) [seatunnel-starter.jar:2
.3.4]
        at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.connectToCluster(TcpClientConnectionManager.java:372) [seatunnel-starter.jar:2.3
.4]
        at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:381) [seatunnel-starter.jar:2.3.4]
        at com.hazelcast.client.HazelcastClient.constructHazelcastClient(HazelcastClient.java:460) [seatunnel-starter.jar:2.3.4]
        at com.hazelcast.client.HazelcastClient.newHazelcastClientInternal(HazelcastClient.java:416) [seatunnel-starter.jar:2.3.4]
        at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:136) [seatunnel-starter.jar:2.3.4]
        at org.apache.seatunnel.engine.client.SeaTunnelHazelcastClient.<init>(SeaTunnelHazelcastClient.java:47) [seatunnel-starter.jar:2.3.4]
        at org.apache.seatunnel.engine.client.SeaTunnelClient.<init>(SeaTunnelClient.java:47) [seatunnel-starter.jar:2.3.4]
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:97) [seatunnel-starter.jar:2.3.4]        
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40) [seatunnel-starter.jar:2.3.4]
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34) [seatunnel-starter.jar:2.3.4]
```

### Zeta or Flink or Spark Version

1.15

### Java or Scala Version

2.12

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by avatarTaier** [comment]
https://github.com/hazelcast/hazelcast/issues/18847

**Comment by liunaijie** [comment]
@avatarTaier do you have run `seatunnel-cluster.sh` to start seatunnel server? your command with `-e local` will start the hazelcast server locally, so if you has run `seatunnel-cluster.sh` already, you will got this error. please run `stop-seatunnel-cluster.sh` to close the server first then re-submit the job.
