### ISSUE TITLE
2.3.4版本为什么运行demo都无法成功

### ISSUE THREAD

**Issue by Seapein** [apache/seatunnel#6440]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

2.3.4版本无法运行demo

### SeaTunnel Version

2.3.4

### SeaTunnel Config

```conf
tar -xzvf apache-seatunnel-2.3.4-bin.tar.gz
```

### Running Command

```shell
./bin/seatunnel.sh --config $SEATUNNEL_HOME/config/v2.batch.config.template -e local
```

### Error Exception

```log
Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:199)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: java.lang.RuntimeException: Plugin PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='FakeSource'} not found.
        at org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery.createPluginInstance(AbstractPluginDiscovery.java:231)
        at org.apache.seatunnel.engine.core.parse.ConnectorInstanceLoader.loadSourceInstance(ConnectorInstanceLoader.java:61)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSource(JobConfigParser.java:80)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:315)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:181)
        at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.getLogicalDag(ClientJobExecutionEnvironment.java:88)
        at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.execute(ClientJobExecutionEnvironment.java:161)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:146)
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Seapein** [comment]
./bin/seatunnel.sh --config ./config/v2.batch.config.template -e local

**Comment by Lvbm** [comment]
删除掉有问题的包，重新手动下载上传上去就可以了

**Comment by liunaijie** [comment]
what's your SETUNNEL_HOME? if you set it to another version's folder, it will got this error. please unset it first then try run this.

**Comment by Seapein** [comment]
> what's your SETUNNEL_HOME? if you set it to another version's folder, it will got this error. please unset it first then try run this.

thanks a lot
