### ISSUE TITLE
从hdfs向clickhouse导入数据是出错

### ISSUE THREAD

**Issue by Szzzzzzzzzzzz** [apache/seatunnel#645]
**Waterdrop Version(Waterdrop版本)**

waterdrop-1.4.2

**Flink or Spark Version(Flink 或者 Spark 版本)**

spark 2.4.0.7.1.5.0-257

**Java or Scala Version(Java或者Scala版本)**

Java version 1.8.0_232

**Waterdrop Config(Waterdrop配置文件)**

Please delete sensitive information(请注意删除敏感信息)

```
spark {
 spark.sql.catalogImplementation = "hive"
 spark.app.name = "Waterdrop"
 spark.executor.instances =  2
 spark.executor.cores =  1
 spark.executor.memory =  "1g"
}
input {
    hive{
        pre_sql = SQL
        table_name = tabel
    }
}
filter {
}
output {
    clickhouse(
        host = host
        database = database
        table = tablename
        fields = fields
        username = user
        password = pwd
    }
}
```

**Running Command(启动命令)**
./bin/start-waterdrop.sh --master yarn --deploy-mode client --config /home/public/test/config.conf

**Error Exception**
INFO metastore.RetryingMetaStoreClient:  RetryingMetaStoreClient proxy=class org.apache.hadoop.hive.q1.metadata.SessionHiveMetaStoreClient ugi=xxxx(auth:KERBEROS) retries=1 delay=1 lifetime=0
Exception in thread "main" java.lang.Exception: jave.lang.NullPointException
	at io.github.interestinglab.waterdrop.Waterdrop$.main(Waterdrop.scala:42)
	at io.github.interestinglab.waterdrop.Waterdrop.main(Waterdrop.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apavhe.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apavhe.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:847)
	at org.apavhe.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
	at org.apavhe.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
	at org.apavhe.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apavhe.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:922)
	at org.apavhe.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:931)
	at org.apavhe.spark.deploy.SparkSubmit.main(SparkSubmit.scala:922)
caused by: java.lang.NullPointException
	at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)
	at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219)
	at sun.awt.FontConfiguration.init(FontConfiguration.java:107)
	at sun.awt.xllFontManager.createFontConfiguration(xllFontManager.java:774)
	at sun.font.SunFontManager$2.run(SunFontManager.java:431)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.SunFontManager.<init>(SunFontManager.java:376)
	at sun.awt.FcFontManager.<init>(FcFontManager.java:35)
	at sun.awt.xllFontManager.<init>(xllFontManager.java:57)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
	at java.awt.Font.getFont2D(Font.java:491)
	at java.awt.Font.access$000(Font.java:224)
	at java.awt.Font$FontAccessImpl.getFont2D(Font.java:228)
	at sun.font.FontUtilities.getFont2D(FontUtilities.java:180)
	at sun.java2d.SunGraphics2D.checkFontInfo(SunGraphics2D.java:669)
	at sun.java2d.SunGraphics2D.getFontInfo(SunGraphics2D.java:830)
	at sun.java2d.pipe.GlyphListPipe.drawString(GlyphListPipe.java:50)
	at sun.java2d.pipe.ValidatePipe.drawString(ValidatePipe.java:165)
	at sun.java2d.SunGraphics2D.drawString(SunGraphics2D.java:2928)
	at io.github.interestinglab.waterdrop.utils.AsciiArt.printAsciiArt(AsciiArt.scala:22)
	at io.github.interestinglab.waterdrop.Waterdrop$.showWaterdropAsciiLogo(Waterdrop.scala:69)
	at io.github.interestinglab.waterdrop.Waterdrop$.batchProcessing(Waterdrop.scala:200)
	at io.github.interestinglab.waterdrop.Waterdrop$.io$github$interestinglab$waterdrop$Waterdrop$$entrypoint(Waterdrop.scala:119)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply$mcV$sp(Waterdrop.scala:37)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply(Waterdrop.scala:37)
	at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply(Waterdrop.scala:37)
	at scala.util.Try$.apply(Try.scala:192)
	at io.github.interestinglab.waterdrop.Waterdrop$.main(Waterdrop.scala:37)
	...13 more

**Comment by Szzzzzzzzzzzz** [comment]
@garyelephant 你好，我在hive2.1的环境中测试成功了，但是hive3.1的环境下会出现这个问题，有可能是hive版本的问题吗？

**Comment by Szzzzzzzzzzzz** [comment]
> @Szzzzzzzzzzzz 你好，请使用最新版waterdrop-1.5.x试试。另外如果开启了kerberos的话，请参照这篇操作一下。#590

@garyelephant 你好，我在hive2.1的环境中测试成功了，但是hive3.1的环境下会出现这个问题，有可能是hive版本的问题吗？
