### ISSUE TITLE
[Bug] [seatunnel-engine-storage] org.apache.seatunnel.engine.checkpoint.storage.exception.CheckpointStorageException

### ISSUE THREAD

**Issue by hengzi52125** [apache/seatunnel#6467]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I intend to use MinIO as a replacement for S3 for checkpoint storage. 
However, I believe this issue should not be related to MinIO. It should also occur even if S3 is used. Of course, I do not have S3 and have not tried it.

### SeaTunnel Version

2.3.4

### SeaTunnel Config

```conf
.yaml
seatunnel:
  engine:
    history-job-expire-minutes: 1440
    backup-count: 1
    queue-type: blockingqueue
    print-execution-info-interval: 60
    print-job-metrics-info-interval: 60
    slot-service:
      dynamic-slot: true
    checkpoint:
      interval: 10000
      timeout: 60000
      storage:
        type: hdfs
        max-retained: 3
        plugin-config:
          storage.type: s3
          s3.bucket: s3a://192.168.3.226:9000/seatunnel-checkpoint/
          fs.s3a.access.key: xxx
          fs.s3a.access.secret: xxx
          fs.s3a.endpoint: http://192.168.3.226:9000
          fs.s3a.aws.credentials.provider: org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
```

### Running Command

```shell
./bin/seatunnel-cluster.sh -d

./bin/seatunnel.sh --config config/v2.streaming.conf.template
```

### Error Exception

```log
2024-03-07 15:40:20,856 WARN  [c.h.i.AddressPicker           ] [main] - [LOCAL] [seatunnel] [5.1] You configured your member address as host name. Please be aware of that your dns can be spoofed. Make sure that your dns configurations are correct.
2024-03-07 15:40:20,857 INFO  [c.h.i.AddressPicker           ] [main] - [LOCAL] [seatunnel] [5.1] Resolving domain name 'localhost' to address(es): [127.0.0.1]
2024-03-07 15:40:20,857 INFO  [c.h.i.AddressPicker           ] [main] - [LOCAL] [seatunnel] [5.1] Interfaces is disabled, trying to pick one address from TCP-IP config addresses: [localhost/127.0.0.1]
2024-03-07 15:40:20,883 INFO  [o.a.s.e.s.SeaTunnelServer     ] [main] - SeaTunnel server start...
2024-03-07 15:40:20,885 INFO  [c.h.system                    ] [main] - [localhost]:5801 [seatunnel] [5.1] Based on Hazelcast IMDG version: 5.1.0 (20220228 - 21f20e7)
2024-03-07 15:40:20,885 INFO  [c.h.system                    ] [main] - [localhost]:5801 [seatunnel] [5.1] Cluster name: seatunnel
2024-03-07 15:40:20,885 INFO  [c.h.system                    ] [main] - [localhost]:5801 [seatunnel] [5.1]

 _____               _____                             _
/  ___|             |_   _|                           | |
\ `--.   ___   __ _   | |   _   _  _ __   _ __    ___ | |
 `--. \ / _ \ / _` |  | |  | | | || '_ \ | '_ \  / _ \| |
/\__/ /|  __/| (_| |  | |  | |_| || | | || | | ||  __/| |
\____/  \___| \__,_|  \_/   \__,_||_| |_||_| |_| \___||_|


2024-03-07 15:40:20,885 INFO  [c.h.system                    ] [main] - [localhost]:5801 [seatunnel] [5.1] Copyright © 2021-2022 The Apache Software Foundation. Apache SeaTunnel, SeaTunnel, and its feather logo are trademarks of The Apache Software Foundation.
2024-03-07 15:40:20,885 INFO  [c.h.system                    ] [main] - [localhost]:5801 [seatunnel] [5.1] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed.
To enable integrity checker do one of the following:
  - Change member config using Java API: config.setIntegrityCheckerEnabled(true);
  - Change XML/YAML configuration property: Set hazelcast.integrity-checker.enabled to true
  - Add system property: -Dhz.integritychecker.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
  - Add environment variable: HZ_INTEGRITYCHECKER_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)
2024-03-07 15:40:20,887 INFO  [c.h.system                    ] [main] - [localhost]:5801 [seatunnel] [5.1] The Jet engine is disabled.
To enable the Jet engine on the members, do one of the following:
  - Change member config using Java API: config.getJetConfig().setEnabled(true)
  - Change XML/YAML configuration property: Set hazelcast.jet.enabled to true
  - Add system property: -Dhz.jet.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
  - Add environment variable: HZ_JET_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)
2024-03-07 15:40:21,326 INFO  [c.h.s.security                ] [main] - [localhost]:5801 [seatunnel] [5.1] Enable DEBUG/FINE log level for log category com.hazelcast.system.security  or use -Dhazelcast.security.recommendations system property to see 🔒 security recommendations and the status of current config.
2024-03-07 15:40:21,390 INFO  [c.h.i.i.Node                  ] [main] - [localhost]:5801 [seatunnel] [5.1] Using TCP/IP discovery
2024-03-07 15:40:21,391 WARN  [c.h.c.CPSubsystem             ] [main] - [localhost]:5801 [seatunnel] [5.1] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
2024-03-07 15:40:21,573 WARN  [o.a.s.e.s.TaskExecutionService] [pool-2-thread-1] - [localhost]:5801 [seatunnel] [5.1] The Node is not ready yet, Node state STARTING,looking forward to the next scheduling
2024-03-07 15:40:21,573 INFO  [o.a.s.e.s.TaskExecutionService] [main] - [localhost]:5801 [seatunnel] [5.1] Created new BusWork : 521985523
2024-03-07 15:40:21,590 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [localhost]:5801
2024-03-07 15:40:21,592 INFO  [o.a.s.e.s.CoordinatorService  ] [pool-5-thread-1] - [localhost]:5801 [seatunnel] [5.1]
***********************************************
     CoordinatorService Thread Pool Status
***********************************************
activeCount               :                   0
corePoolSize              :                   0
maximumPoolSize           :          2147483647
poolSize                  :                   0
completedTaskCount        :                   0
taskCount                 :                   0
***********************************************

2024-03-07 15:40:21,655 INFO  [c.h.i.d.Diagnostics           ] [main] - [localhost]:5801 [seatunnel] [5.1] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
2024-03-07 15:40:21,661 INFO  [c.h.c.LifecycleService        ] [main] - [localhost]:5801 [seatunnel] [5.1] [localhost]:5801 is STARTING
2024-03-07 15:40:21,683 INFO  [c.h.i.c.ClusterService        ] [main] - [localhost]:5801 [seatunnel] [5.1]

Members {size:1, ver:1} [
	Member [localhost]:5801 - ee4c3a82-e269-482c-8f61-1ada4f3844a9 this
]

2024-03-07 15:40:21,689 INFO  [o.a.s.e.s.CoordinatorService  ] [pool-4-thread-1] - [localhost]:5801 [seatunnel] [5.1] This node become a new active master node, begin init coordinator service
2024-03-07 15:40:21,693 INFO  [c.h.c.LifecycleService        ] [main] - [localhost]:5801 [seatunnel] [5.1] [localhost]:5801 is STARTED
2024-03-07 15:40:21,902 INFO  [.h.i.p.i.PartitionStateManager] [pool-4-thread-1] - [localhost]:5801 [seatunnel] [5.1] Initializing cluster partition table arrangement...
2024-03-07 15:40:26,594 INFO  [.e.s.r.AbstractResourceManager] [hz.main.generic-operation.thread-0] - Init ResourceManager
2024-03-07 15:40:26,594 INFO  [.e.s.r.AbstractResourceManager] [hz.main.generic-operation.thread-0] - initWorker...
2024-03-07 15:40:26,595 INFO  [.e.s.r.AbstractResourceManager] [hz.main.generic-operation.thread-0] - initWorker live nodes: [[localhost]:5801]
2024-03-07 15:40:26,600 INFO  [.e.s.r.AbstractResourceManager] [hz.main.generic-operation.thread-0] - registerWorker: {[localhost]:5801=WorkerProfile(address=[localhost]:5801, profile=ResourceProfile{cpu=CPU{core=0}, heapMemory=Memory{bytes=2147483648}}, unassignedResource=ResourceProfile{cpu=CPU{core=0}, heapMemory=Memory{bytes=2147483648}}, assignedSlots=[], unassignedSlots=[])}
2024-03-07 15:40:40,323 INFO  [.p.t.AuthenticationMessageTask] [hz.main.priority-generic-operation.thread-0] - [localhost]:5801 [seatunnel] [5.1] Received auth from Connection[id=1, /127.0.0.1:5801->/127.0.0.1:37619, qualifier=null, endpoint=[127.0.0.1]:37619, remoteUuid=3c5b5526-796f-4622-85ca-67d55cdaf792, alive=true, connectionType=JVM, planeIndex=-1], successfully authenticated, clientUuid: 3c5b5526-796f-4622-85ca-67d55cdaf792, client name: hz.client_1, client version: 5.1
2024-03-07 15:40:40,959 INFO  [o.a.s.e.s.m.JobMaster         ] [seatunnel-coordinator-service-0] - Init JobMaster for Job SeaTunnel_Job (818025345830617089)
2024-03-07 15:40:40,959 INFO  [o.a.s.e.s.m.JobMaster         ] [seatunnel-coordinator-service-0] - Job SeaTunnel_Job (818025345830617089) needed jar urls [file:/root/zhf/seatunnel/apache-seatunnel-2.3.4/connectors/connector-console-2.3.4.jar, file:/root/zhf/seatunnel/apache-seatunnel-2.3.4/connectors/connector-fake-2.3.4.jar]
2024-03-07 15:40:41,018 INFO  [o.a.s.e.c.l.ClassLoaderUtil   ] [seatunnel-coordinator-service-0] - recycle classloader org.apache.seatunnel.engine.common.loader.SeaTunnelChildFirstClassLoader@55fe4967
2024-03-07 15:40:41,541 WARN  [o.a.h.u.NativeCodeLoader      ] [seatunnel-coordinator-service-0] - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2024-03-07 15:40:41,842 WARN  [o.a.h.m.i.MetricsConfig       ] [seatunnel-coordinator-service-0] - Cannot locate configuration: tried hadoop-metrics2-s3a-file-system.properties,hadoop-metrics2.properties
2024-03-07 15:40:41,860 INFO  [o.a.h.m.i.MetricsSystemImpl   ] [seatunnel-coordinator-service-0] - Scheduled Metric snapshot period at 10 second(s).
2024-03-07 15:40:41,860 INFO  [o.a.h.m.i.MetricsSystemImpl   ] [seatunnel-coordinator-service-0] - s3a-file-system metrics system started
2024-03-07 15:40:41,889 INFO  [o.a.s.e.s.d.p.PhysicalVertex  ] [seatunnel-coordinator-service-0] - The task Job SeaTunnel_Job (818025345830617089), Pipeline: [(1/1)], task: [pipeline-1 [Source[0]-FakeSource]-SourceTask (1/2)] is in state CREATED when init state future
2024-03-07 15:40:41,890 INFO  [o.a.s.e.s.d.p.PhysicalVertex  ] [seatunnel-coordinator-service-0] - The task Job SeaTunnel_Job (818025345830617089), Pipeline: [(1/1)], task: [pipeline-1 [Source[0]-FakeSource]-SourceTask (2/2)] is in state CREATED when init state future
2024-03-07 15:40:41,891 INFO  [o.a.s.e.s.d.p.PhysicalVertex  ] [seatunnel-coordinator-service-0] - The task Job SeaTunnel_Job (818025345830617089), Pipeline: [(1/1)], task: [pipeline-1 [Source[0]-FakeSource]-SplitEnumerator (1/1)] is in state CREATED when init state future
2024-03-07 15:40:41,895 ERROR [o.a.s.e.s.CoordinatorService  ] [seatunnel-coordinator-service-0] - [localhost]:5801 [seatunnel] [5.1] submit job 818025345830617089 error org.apache.seatunnel.engine.checkpoint.storage.exception.CheckpointStorageException: Failed to get file system
	at org.apache.seatunnel.engine.checkpoint.storage.hdfs.HdfsStorage.initStorage(HdfsStorage.java:70)
	at org.apache.seatunnel.engine.checkpoint.storage.hdfs.HdfsStorage.<init>(HdfsStorage.java:57)
	at org.apache.seatunnel.engine.checkpoint.storage.hdfs.common.HdfsFileStorageInstance.getOrCreateStorage(HdfsFileStorageInstance.java:53)
	at org.apache.seatunnel.engine.checkpoint.storage.hdfs.HdfsStorageFactory.create(HdfsStorageFactory.java:75)
	at org.apache.seatunnel.engine.server.checkpoint.CheckpointManager.<init>(CheckpointManager.java:104)
	at org.apache.seatunnel.engine.server.master.JobMaster.initCheckPointManager(JobMaster.java:247)
	at org.apache.seatunnel.engine.server.master.JobMaster.init(JobMaster.java:230)
	at org.apache.seatunnel.engine.server.CoordinatorService.lambda$submitJob$3(CoordinatorService.java:419)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider instantiation exception: java.lang.NoSuchMethodError: 'void com.google.common.base.Preconditions.checkArgument(boolean, java.lang.String, java.lang.Object, java.lang.Object)'
	at org.apache.hadoop.fs.s3a.S3AUtils.createAWSCredentialProvider(S3AUtils.java:678)
	at org.apache.hadoop.fs.s3a.S3AUtils.createAWSCredentialProviderSet(S3AUtils.java:566)
	at org.apache.hadoop.fs.s3a.DefaultS3ClientFactory.createS3Client(DefaultS3ClientFactory.java:52)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.initialize(S3AFileSystem.java:256)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3303)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:124)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3352)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3320)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:479)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:227)
	at org.apache.seatunnel.engine.checkpoint.storage.hdfs.HdfsStorage.initStorage(HdfsStorage.java:68)
	... 12 more
Caused by: java.lang.NoSuchMethodError: 'void com.google.common.base.Preconditions.checkArgument(boolean, java.lang.String, java.lang.Object, java.lang.Object)'
	at org.apache.hadoop.fs.s3a.S3AUtils.lookupPassword(S3AUtils.java:742)
	at org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider.<init>(SimpleAWSCredentialsProvider.java:59)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.apache.hadoop.fs.s3a.S3AUtils.createAWSCredentialProvider(S3AUtils.java:635)
	... 22 more
```

### Java or Scala Version

openjdk 11.0.22

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hengzi52125** [comment]
The configuration "fs.s3a.access.secret" was misspelled above. It should be "fs.s3a.secret.key". However, this is unrelated to the error reported. I re-pulled the source code, checked out 2.3.4, and compiled it. After trying again, the previous error disappeared, but a new problem appeared.

2024-03-07 17:29:30,266 WARN  [c.h.i.AddressPicker           ] [main] - [LOCAL] [seatunnel] [5.1] You configured your member address as host name. Please be aware of that your dns can be spoofed. Make sure that your dns configurations are correct.
2024-03-07 17:29:30,267 INFO  [c.h.i.AddressPicker           ] [main] - [LOCAL] [seatunnel] [5.1] Resolving domain name 'localhost' to address(es): [127.0.0.1]
2024-03-07 17:29:30,267 INFO  [c.h.i.AddressPicker           ] [main] - [LOCAL] [seatunnel] [5.1] Interfaces is disabled, trying to pick one address from TCP-IP config addresses: [localhost/127.0.0.1]
2024-03-07 17:29:30,300 INFO  [o.a.s.e.s.SeaTunnelServer     ] [main] - SeaTunnel server start...
2024-03-07 17:29:30,302 INFO  [c.h.system                    ] [main] - [localhost]:5801 [seatunnel] [5.1] Based on Hazelcast IMDG version: 5.1.0 (20220228 - 21f20e7)
2024-03-07 17:29:30,302 INFO  [c.h.system                    ] [main] - [localhost]:5801 [seatunnel] [5.1] Cluster name: seatunnel
2024-03-07 17:29:30,302 INFO  [c.h.system                    ] [main] - [localhost]:5801 [seatunnel] [5.1]

 _____               _____                             _
/  ___|             |_   _|                           | |
\ `--.   ___   __ _   | |   _   _  _ __   _ __    ___ | |
 `--. \ / _ \ / _` |  | |  | | | || '_ \ | '_ \  / _ \| |
/\__/ /|  __/| (_| |  | |  | |_| || | | || | | ||  __/| |
\____/  \___| \__,_|  \_/   \__,_||_| |_||_| |_| \___||_|


2024-03-07 17:29:30,302 INFO  [c.h.system                    ] [main] - [localhost]:5801 [seatunnel] [5.1] Copyright © 2021-2022 The Apache Software Foundation. Apache SeaTunnel, SeaTunnel, and its feather logo are trademarks of The Apache Software Foundation.
2024-03-07 17:29:30,302 INFO  [c.h.system                    ] [main] - [localhost]:5801 [seatunnel] [5.1] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed.
To enable integrity checker do one of the following:
  - Change member config using Java API: config.setIntegrityCheckerEnabled(true);
  - Change XML/YAML configuration property: Set hazelcast.integrity-checker.enabled to true
  - Add system property: -Dhz.integritychecker.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
  - Add environment variable: HZ_INTEGRITYCHECKER_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)
2024-03-07 17:29:30,304 INFO  [c.h.system                    ] [main] - [localhost]:5801 [seatunnel] [5.1] The Jet engine is disabled.
To enable the Jet engine on the members, do one of the following:
  - Change member config using Java API: config.getJetConfig().setEnabled(true)
  - Change XML/YAML configuration property: Set hazelcast.jet.enabled to true
  - Add system property: -Dhz.jet.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
  - Add environment variable: HZ_JET_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)
2024-03-07 17:29:30,817 INFO  [c.h.s.security                ] [main] - [localhost]:5801 [seatunnel] [5.1] Enable DEBUG/FINE log level for log category com.hazelcast.system.security  or use -Dhazelcast.security.recommendations system property to see 🔒 security recommendations and the status of current config.
2024-03-07 17:29:30,888 INFO  [c.h.i.i.Node                  ] [main] - [localhost]:5801 [seatunnel] [5.1] Using TCP/IP discovery
2024-03-07 17:29:30,889 WARN  [c.h.c.CPSubsystem             ] [main] - [localhost]:5801 [seatunnel] [5.1] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
2024-03-07 17:29:31,115 WARN  [o.a.s.e.s.TaskExecutionService] [pool-2-thread-1] - [localhost]:5801 [seatunnel] [5.1] The Node is not ready yet, Node state STARTING,looking forward to the next scheduling
2024-03-07 17:29:31,115 INFO  [o.a.s.e.s.TaskExecutionService] [main] - [localhost]:5801 [seatunnel] [5.1] Created new BusWork : 1692066743
2024-03-07 17:29:31,137 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [localhost]:5801
2024-03-07 17:29:31,143 INFO  [o.a.s.e.s.CoordinatorService  ] [pool-5-thread-1] - [localhost]:5801 [seatunnel] [5.1]
***********************************************
     CoordinatorService Thread Pool Status
***********************************************
activeCount               :                   0
corePoolSize              :                   0
maximumPoolSize           :          2147483647
poolSize                  :                   0
completedTaskCount        :                   0
taskCount                 :                   0
***********************************************

2024-03-07 17:29:31,264 INFO  [c.h.i.d.Diagnostics           ] [main] - [localhost]:5801 [seatunnel] [5.1] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
2024-03-07 17:29:31,270 INFO  [c.h.c.LifecycleService        ] [main] - [localhost]:5801 [seatunnel] [5.1] [localhost]:5801 is STARTING
2024-03-07 17:29:31,309 INFO  [c.h.i.c.ClusterService        ] [main] - [localhost]:5801 [seatunnel] [5.1]

Members {size:1, ver:1} [
	Member [localhost]:5801 - 78650516-6079-4790-b54e-5e46ed4590fc this
]

2024-03-07 17:29:31,323 INFO  [c.h.c.LifecycleService        ] [main] - [localhost]:5801 [seatunnel] [5.1] [localhost]:5801 is STARTED
2024-03-07 17:29:31,336 INFO  [o.a.s.e.s.CoordinatorService  ] [pool-4-thread-1] - [localhost]:5801 [seatunnel] [5.1] This node become a new active master node, begin init coordinator service
2024-03-07 17:29:31,526 INFO  [.h.i.p.i.PartitionStateManager] [pool-4-thread-1] - [localhost]:5801 [seatunnel] [5.1] Initializing cluster partition table arrangement...
2024-03-07 17:29:36,137 INFO  [.e.s.r.AbstractResourceManager] [hz.main.generic-operation.thread-0] - Init ResourceManager
2024-03-07 17:29:36,137 INFO  [.e.s.r.AbstractResourceManager] [hz.main.generic-operation.thread-0] - initWorker...
2024-03-07 17:29:36,138 INFO  [.e.s.r.AbstractResourceManager] [hz.main.generic-operation.thread-0] - initWorker live nodes: [[localhost]:5801]
2024-03-07 17:29:36,143 INFO  [.e.s.r.AbstractResourceManager] [hz.main.generic-operation.thread-0] - registerWorker: {[localhost]:5801=WorkerProfile(address=[localhost]:5801, profile=ResourceProfile{cpu=CPU{core=0}, heapMemory=Memory{bytes=2147483648}}, unassignedResource=ResourceProfile{cpu=CPU{core=0}, heapMemory=Memory{bytes=2147483648}}, assignedSlots=[], unassignedSlots=[])}
2024-03-07 17:29:48,023 INFO  [.p.t.AuthenticationMessageTask] [hz.main.priority-generic-operation.thread-0] - [localhost]:5801 [seatunnel] [5.1] Received auth from Connection[id=1, /127.0.0.1:5801->/127.0.0.1:46219, qualifier=null, endpoint=[127.0.0.1]:46219, remoteUuid=0da26f23-b30f-48f4-a255-6ef023f00896, alive=true, connectionType=JVM, planeIndex=-1], successfully authenticated, clientUuid: 0da26f23-b30f-48f4-a255-6ef023f00896, client name: hz.client_1, client version: 5.1
2024-03-07 17:29:48,814 INFO  [o.a.s.e.s.m.JobMaster         ] [seatunnel-coordinator-service-0] - Init JobMaster for Job SeaTunnel_Job (818052809160130561)
2024-03-07 17:29:48,814 INFO  [o.a.s.e.s.m.JobMaster         ] [seatunnel-coordinator-service-0] - Job SeaTunnel_Job (818052809160130561) needed jar urls [file:/root/zhf/seatunnel2/seatunnel/seatunnel-dist/target/apache-seatunnel-2.3.4/connectors/connector-console-2.3.4.jar, file:/root/zhf/seatunnel2/seatunnel/seatunnel-dist/target/apache-seatunnel-2.3.4/connectors/connector-fake-2.3.4.jar]
2024-03-07 17:29:48,876 INFO  [o.a.s.e.c.l.ClassLoaderUtil   ] [seatunnel-coordinator-service-0] - recycle classloader org.apache.seatunnel.engine.common.loader.SeaTunnelChildFirstClassLoader@c563b2b
2024-03-07 17:29:49,320 WARN  [o.a.h.u.NativeCodeLoader      ] [seatunnel-coordinator-service-0] - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2024-03-07 17:29:49,572 WARN  [o.a.h.m.i.MetricsConfig       ] [seatunnel-coordinator-service-0] - Cannot locate configuration: tried hadoop-metrics2-s3a-file-system.properties,hadoop-metrics2.properties
2024-03-07 17:29:49,591 INFO  [o.a.h.m.i.MetricsSystemImpl   ] [seatunnel-coordinator-service-0] - Scheduled Metric snapshot period at 10 second(s).
2024-03-07 17:29:49,591 INFO  [o.a.h.m.i.MetricsSystemImpl   ] [seatunnel-coordinator-service-0] - s3a-file-system metrics system started
2024-03-07 17:29:50,243 INFO  [o.a.s.e.s.d.p.PhysicalVertex  ] [seatunnel-coordinator-service-0] - The task Job SeaTunnel_Job (818052809160130561), Pipeline: [(1/1)], task: [pipeline-1 [Source[0]-FakeSource]-SourceTask (1/2)] is in state CREATED when init state future
2024-03-07 17:29:50,244 INFO  [o.a.s.e.s.d.p.PhysicalVertex  ] [seatunnel-coordinator-service-0] - The task Job SeaTunnel_Job (818052809160130561), Pipeline: [(1/1)], task: [pipeline-1 [Source[0]-FakeSource]-SourceTask (2/2)] is in state CREATED when init state future
2024-03-07 17:29:50,245 INFO  [o.a.s.e.s.d.p.PhysicalVertex  ] [seatunnel-coordinator-service-0] - The task Job SeaTunnel_Job (818052809160130561), Pipeline: [(1/1)], task: [pipeline-1 [Source[0]-FakeSource]-SplitEnumerator (1/1)] is in state CREATED when init state future
2024-03-07 17:29:50,248 ERROR [o.a.s.e.s.CoordinatorService  ] [seatunnel-coordinator-service-0] - [localhost]:5801 [seatunnel] [5.1] submit job 818052809160130561 error org.apache.seatunnel.engine.checkpoint.storage.exception.CheckpointStorageException: Failed to get file system
	at org.apache.seatunnel.engine.checkpoint.storage.hdfs.HdfsStorage.initStorage(HdfsStorage.java:70)
	at org.apache.seatunnel.engine.checkpoint.storage.hdfs.HdfsStorage.<init>(HdfsStorage.java:57)
	at org.apache.seatunnel.engine.checkpoint.storage.hdfs.common.HdfsFileStorageInstance.getOrCreateStorage(HdfsFileStorageInstance.java:53)
	at org.apache.seatunnel.engine.checkpoint.storage.hdfs.HdfsStorageFactory.create(HdfsStorageFactory.java:75)
	at org.apache.seatunnel.engine.server.checkpoint.CheckpointManager.<init>(CheckpointManager.java:104)
	at org.apache.seatunnel.engine.server.master.JobMaster.initCheckPointManager(JobMaster.java:247)
	at org.apache.seatunnel.engine.server.master.JobMaster.init(JobMaster.java:230)
	at org.apache.seatunnel.engine.server.CoordinatorService.lambda$submitJob$3(CoordinatorService.java:419)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.hadoop.fs.s3a.AWSBadRequestException: doesBucketExist on 192.168.3.226: com.amazonaws.services.s3.model.AmazonS3Exception: Bad Request (Service: Amazon S3; Status Code: 400; Error Code: 400 Bad Request; Request ID: 17BA717CFF59DF8F; S3 Extended Request ID: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8), S3 Extended Request ID: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8:400 Bad Request: Bad Request (Service: Amazon S3; Status Code: 400; Error Code: 400 Bad Request; Request ID: 17BA717CFF59DF8F; S3 Extended Request ID: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8)
	at org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:212)
	at org.apache.hadoop.fs.s3a.Invoker.once(Invoker.java:111)
	at org.apache.hadoop.fs.s3a.Invoker.lambda$retry$3(Invoker.java:265)
	at org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:322)
	at org.apache.hadoop.fs.s3a.Invoker.retry(Invoker.java:261)
	at org.apache.hadoop.fs.s3a.Invoker.retry(Invoker.java:236)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.verifyBucketExists(S3AFileSystem.java:372)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.initialize(S3AFileSystem.java:308)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3303)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:124)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3352)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3320)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:479)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:227)
	at org.apache.seatunnel.engine.checkpoint.storage.hdfs.HdfsStorage.initStorage(HdfsStorage.java:68)
	... 12 more
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Bad Request (Service: Amazon S3; Status Code: 400; Error Code: 400 Bad Request; Request ID: 17BA717CFF59DF8F; S3 Extended Request ID: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8), S3 Extended Request ID: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1639)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4325)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4272)
	at com.amazonaws.services.s3.AmazonS3Client.headBucket(AmazonS3Client.java:1337)
	at com.amazonaws.services.s3.AmazonS3Client.doesBucketExist(AmazonS3Client.java:1277)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.lambda$verifyBucketExists$1(S3AFileSystem.java:373)
	at org.apache.hadoop.fs.s3a.Invoker.once(Invoker.java:109)
	... 25 more

**Comment by hengzi52125** [comment]
So, can MinIO be used as a replacement for S3?

**Comment by hengzi52125** [comment]
Changing "s3.bucket: s3a://192.168.3.226:9000/seatunnel-checkpoint/" to "s3.bucket: s3a://seatunnel-checkpoint" worked.
