### ISSUE TITLE
[Bug] [RestAPI] java.lang.ClassNotFoundException: com.mysql.cj.jdbc.Driver

### ISSUE THREAD

**Issue by liunaijie** [apache/seatunnel#6481]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

when i use RestAPI to submit job. the job is mysql to console.
when the server cluster startup, the first time run is ok, but the next round will failed and got 
`java.lang.ClassNotFoundException: com.mysql.cj.jdbc.Driver` error.

### SeaTunnel Version

2.3.4

### SeaTunnel Config

```conf
{
    "env": {
        "execution.parallelism": 2,
        "job.mode": "BATCH",
        "checkpoint.interval": 15000
    },
    "source": [
        {
            "url" : "jdbc:mysql://127.0.0.1:3306/st_poc?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&useSSL=false",
            "driver" : "com.mysql.cj.jdbc.Driver",
            "connection_check_timeout_sec" :  100,
            "user" : "root",
            "password" : "123456",
            "query" : "select * FROM topic_01",
            "plugin_name" : "Jdbc"
        }
    ],
    "sink": [
        {
            "plugin_name": "Console"
        }
    ]
}
```
```


### Running Command

```shell
call `/hazelcast/rest/maps/submit-job` api to submit the job
```

### Error Exception

```log
java.lang.RuntimeException: java.lang.ClassNotFoundException: com.mysql.cj.jdbc.Driver
        at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:71) ~[seatunnel-starter.jar:2.3.4]
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:320) ~[seatunnel-starter.jar:2.3.4]
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:181) ~[seatunnel-starter.jar:2.3.4]
        at org.apache.seatunnel.engine.server.rest.RestJobExecutionEnvironment.getLogicalDag(RestJobExecutionEnvironment.java:76) ~[seatunnel-starter.jar:2.3.4]
        at org.apache.seatunnel.engine.server.rest.RestJobExecutionEnvironment.build(RestJobExecutionEnvironment.java:99) ~[seatunnel-starter.jar:2.3.4]
        at org.apache.seatunnel.engine.server.rest.RestHttpPostCommandProcessor.handleSubmitJob(RestHttpPostCommandProcessor.java:136) ~[seatunnel-starter.jar:2.3.4]
        at org.apache.seatunnel.engine.server.rest.RestHttpPostCommandProcessor.handle(RestHttpPostCommandProcessor.java:82) ~[seatunnel-starter.jar:2.3.4]
        at org.apache.seatunnel.engine.server.rest.RestHttpPostCommandProcessor.handle(RestHttpPostCommandProcessor.java:60) ~[seatunnel-starter.jar:2.3.4]
        at com.hazelcast.internal.ascii.TextCommandServiceImpl$CommandExecutor.run(TextCommandServiceImpl.java:402) ~[seatunnel-starter.jar:2.3.4]
        at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217) ~[seatunnel-starter.jar:2.3.4]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[seatunnel-starter.jar:2.3.4]
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[seatunnel-starter.jar:2.3.4]
Caused by: java.lang.ClassNotFoundException: com.mysql.cj.jdbc.Driver
``
```

### Zeta or Flink or Spark Version

zeta

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
#6477 can solve this issue
