### ISSUE TITLE
在 dev 版本中source 是 iceberg 却报错sink could not be instantiated

### ISSUE THREAD

**Issue by WuJiY** [apache/seatunnel#6485]
版本 **dev**

从iceberg读取 写入clickhouse 报错 

```
env {
    job.mode="BATCH"
    parallelism=1
}

source {
 Iceberg {
    schema {
      fields {
        age = "int"
        name = "string"
        email = "string"
      }
    }
    catalog_name = "iceberg"
    iceberg.catalog.config={
      type = "hadoop"
      warehouse = "hdfs://master/iceberg/"
    }
    namespace = "st"
    table = "iceberg"
  }
}
sink {
   Clickhouse {
      host="localhost:8123"
      database="st"
      table="iceberg"
      username="default"
      password="123456"
   }
}
```

报错信息
```
Exception in thread "main" java.util.ServiceConfigurationError: org.apache.seatunnel.api.sink.SeaTunnelSink: Provider org.apache.seatunnel.connectors.seatunnel.iceberg.sink.IcebergSink could not be instantiated
        at java.util.ServiceLoader.fail(ServiceLoader.java:232)
        at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery.loadPluginInstance(AbstractPluginDiscovery.java:302)
        at org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery.createOptionalPluginInstance(AbstractPluginDiscovery.java:183)
        at org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery.createPluginInstance(AbstractPluginDiscovery.java:227)
        at org.apache.seatunnel.engine.core.parse.ConnectorInstanceLoader.loadSinkInstance(ConnectorInstanceLoader.java:77)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSink(JobConfigParser.java:194)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSinks(JobConfigParser.java:170)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSink(MultipleTableJobConfigParser.java:531)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:193)
        at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.getLogicalDag(ClientJobExecutionEnvironment.java:88)
        at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.execute(ClientJobExecutionEnvironment.java:161)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:146)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: java.lang.InstantiationException: org.apache.seatunnel.connectors.seatunnel.iceberg.sink.IcebergSink
        at java.lang.Class.newInstance(Class.java:427)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
        ... 15 more
Caused by: java.lang.NoSuchMethodException: org.apache.seatunnel.connectors.seatunnel.iceberg.sink.IcebergSink.<init>()
        at java.lang.Class.getConstructor0(Class.java:3082)
        at java.lang.Class.newInstance(Class.java:412)
        ... 16 more
[2]+  Done                    clear
```

另外
pg->clickhouse 正常
iceberg->pg也是正常

**Comment by mosence** [comment]
Are you sure it's the current dev branch? The error code lines do not match.

**Comment by WuJiY** [comment]
> Are you sure it's the current dev branch? The error code lines do not match.

**Dev** version on March 7th

**Comment by WuJiY** [comment]
The latest compiled version at 12:00 on March 12

**Dev** version 

```
Mar 12, 2024 2:09:32 PM com.hazelcast.internal.config.AbstractConfigLocator
INFO: Loading configuration '/opt/seatunnel/apache-seatunnel-2.3.5-SNAPSHOT/config/seatunnel.yaml' from System property 'seatunnel.config'
Mar 12, 2024 2:09:32 PM com.hazelcast.internal.config.AbstractConfigLocator
INFO: Using configuration file at /opt/seatunnel/apache-seatunnel-2.3.5-SNAPSHOT/config/seatunnel.yaml
Mar 12, 2024 2:09:32 PM org.apache.seatunnel.engine.common.config.SeaTunnelConfig
INFO: seatunnel.home is /opt/seatunnel/apache-seatunnel-2.3.5-SNAPSHOT
Mar 12, 2024 2:09:32 PM com.hazelcast.internal.config.AbstractConfigLocator
INFO: Loading configuration '/opt/seatunnel/apache-seatunnel-2.3.5-SNAPSHOT/config/hazelcast.yaml' from System property 'hazelcast.config'
Mar 12, 2024 2:09:32 PM com.hazelcast.internal.config.AbstractConfigLocator
INFO: Using configuration file at /opt/seatunnel/apache-seatunnel-2.3.5-SNAPSHOT/config/hazelcast.yaml
Mar 12, 2024 2:09:32 PM com.hazelcast.internal.config.AbstractConfigLocator
INFO: Loading configuration '/opt/seatunnel/apache-seatunnel-2.3.5-SNAPSHOT/config/hazelcast-client.yaml' from System property 'hazelcast.client.config'
Mar 12, 2024 2:09:32 PM com.hazelcast.internal.config.AbstractConfigLocator
INFO: Using configuration file at /opt/seatunnel/apache-seatunnel-2.3.5-SNAPSHOT/config/hazelcast-client.yaml
2024-03-12 14:09:32,863 INFO  [.c.i.s.ClientInvocationService] [main] - hz.client_1 [seatunnel] [5.1] Running with 2 response threads, dynamic=true
2024-03-12 14:09:32,911 INFO  [c.h.c.LifecycleService        ] [main] - hz.client_1 [seatunnel] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is STARTING
2024-03-12 14:09:32,912 INFO  [c.h.c.LifecycleService        ] [main] - hz.client_1 [seatunnel] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is STARTED
2024-03-12 14:09:32,935 INFO  [.c.i.c.ClientConnectionManager] [main] - hz.client_1 [seatunnel] [5.1] Trying to connect to cluster: seatunnel
2024-03-12 14:09:32,937 INFO  [.c.i.c.ClientConnectionManager] [main] - hz.client_1 [seatunnel] [5.1] Trying to connect to [localhost]:5801
2024-03-12 14:09:32,985 INFO  [c.h.c.LifecycleService        ] [main] - hz.client_1 [seatunnel] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is CLIENT_CONNECTED
2024-03-12 14:09:32,986 INFO  [.c.i.c.ClientConnectionManager] [main] - hz.client_1 [seatunnel] [5.1] Authenticated with server [localhost]:5801:2b17fe09-e44b-4b8a-9355-722d46cba6a1, server version: 5.1, local address: /127.0.0.1:44631
2024-03-12 14:09:32,987 INFO  [c.h.i.d.Diagnostics           ] [main] - hz.client_1 [seatunnel] [5.1] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
2024-03-12 14:09:33,006 INFO  [c.h.c.i.s.ClientClusterService] [hz.client_1.event-2] - hz.client_1 [seatunnel] [5.1] 

Members [1] {
        Member [localhost]:5801 - 2b17fe09-e44b-4b8a-9355-722d46cba6a1
}

2024-03-12 14:09:33,035 INFO  [.c.i.s.ClientStatisticsService] [main] - Client statistics is enabled with period 5 seconds.
2024-03-12 14:09:33,187 INFO  [.ClientJobExecutionEnvironment] [main] - add common jar in plugins :[]
2024-03-12 14:09:33,226 INFO  [o.a.s.c.s.u.ConfigBuilder     ] [main] - Loading config file from path: ./config/ck/lake.template
2024-03-12 14:09:33,278 INFO  [o.a.s.c.s.u.ConfigShadeUtils  ] [main] - Load config shade spi: [base64]
2024-03-12 14:09:33,328 INFO  [o.a.s.c.s.u.ConfigBuilder     ] [main] - Parsed config file: 
{
    "env" : {
        "job.mode" : "BATCH"
    },
    "source" : [
        {
            "schema" : {
                "fields" : {
                    "age" : "int",
                    "name" : "string",
                    "email" : "string"
                }
            },
            "catalog_name" : "aaa",
            "iceberg.catalog.config" : {
                "type" : "hadoop",
                "warehouse" : "hdfs://testserver1:8020/iceberg/"
            },
            "namespace" : "st",
            "plugin_name" : "Iceberg",
            "table" : "bbb"
        }
    ],
    "sink" : [
        {
            "database" : "st",
            "password" : "123456",
            "host" : "testserver2:8123",
            "plugin_name" : "Clickhouse",
            "table" : "bbb",
            "username" : "default"
        }
    ]
}

2024-03-12 14:09:33,343 INFO  [.s.p.d.AbstractPluginDiscovery] [main] - Load SeaTunnelSink Plugin from /opt/seatunnel/apache-seatunnel-2.3.5-SNAPSHOT/connectors
2024-03-12 14:09:33,349 INFO  [.s.p.d.AbstractPluginDiscovery] [main] - Discovery plugin jar for: PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='Iceberg'} at: file:/opt/seatunnel/apache-seatunnel-2.3.5-SNAPSHOT/connectors/connector-iceberg-2.3.5-SNAPSHOT.jar
2024-03-12 14:09:33,350 INFO  [.s.p.d.AbstractPluginDiscovery] [main] - Discovery plugin jar for: PluginIdentifier{engineType='seatunnel', pluginType='sink', pluginName='Clickhouse'} at: file:/opt/seatunnel/apache-seatunnel-2.3.5-SNAPSHOT/connectors/connector-clickhouse-2.3.5-SNAPSHOT.jar
2024-03-12 14:09:33,352 INFO  [p.MultipleTableJobConfigParser] [main] - start generating all sources.
2024-03-12 14:09:33,424 INFO  [a.s.c.s.i.IcebergCatalogLoader] [main] - Hadoop config initialized: org.apache.hadoop.hdfs.HdfsConfiguration
2024-03-12 14:09:33,556 WARN  [o.a.h.u.NativeCodeLoader      ] [main] - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2024-03-12 14:09:34,273 INFO  [o.a.i.BaseMetastoreCatalog    ] [main] - Table loaded by catalog: aaa.st.bbb
2024-03-12 14:09:34,283 INFO  [o.a.s.a.t.f.FactoryUtil       ] [main] - get the CatalogTable from source Iceberg: Iceberg.st.bbb
2024-03-12 14:09:34,293 INFO  [.s.p.d.AbstractPluginDiscovery] [main] - Load SeaTunnelSource Plugin from /opt/seatunnel/apache-seatunnel-2.3.5-SNAPSHOT/connectors
2024-03-12 14:09:34,298 INFO  [.s.p.d.AbstractPluginDiscovery] [main] - Discovery plugin jar for: PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='Iceberg'} at: file:/opt/seatunnel/apache-seatunnel-2.3.5-SNAPSHOT/connectors/connector-iceberg-2.3.5-SNAPSHOT.jar
2024-03-12 14:09:34,299 INFO  [p.MultipleTableJobConfigParser] [main] - start generating all transforms.
2024-03-12 14:09:34,299 INFO  [p.MultipleTableJobConfigParser] [main] - start generating all sinks.
2024-03-12 14:09:34,301 WARN  [p.MultipleTableJobConfigParser] [main] - The Factory has not been implemented and the deprecated Plugin will be used.
2024-03-12 14:09:34,302 INFO  [.s.p.d.AbstractPluginDiscovery] [main] - Load SeaTunnelSink Plugin from /opt/seatunnel/apache-seatunnel-2.3.5-SNAPSHOT/connectors
2024-03-12 14:09:34,304 INFO  [.s.p.d.AbstractPluginDiscovery] [main] - Discovery plugin jar for: PluginIdentifier{engineType='seatunnel', pluginType='sink', pluginName='Clickhouse'} at: file:/opt/seatunnel/apache-seatunnel-2.3.5-SNAPSHOT/connectors/connector-clickhouse-2.3.5-SNAPSHOT.jar
2024-03-12 14:09:34,306 INFO  [c.h.c.LifecycleService        ] [main] - hz.client_1 [seatunnel] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is SHUTTING_DOWN
2024-03-12 14:09:34,308 INFO  [.c.i.c.ClientConnectionManager] [main] - hz.client_1 [seatunnel] [5.1] Removed connection to endpoint: [localhost]:5801:2b17fe09-e44b-4b8a-9355-722d46cba6a1, connection: ClientConnection{alive=false, connectionId=1, channel=NioChannel{/127.0.0.1:44631->localhost/127.0.0.1:5801}, remoteAddress=[localhost]:5801, lastReadTime=2024-03-12 14:09:33.221, lastWriteTime=2024-03-12 14:09:33.213, closedTime=2024-03-12 14:09:34.306, connected server version=5.1}
2024-03-12 14:09:34,308 INFO  [c.h.c.LifecycleService        ] [main] - hz.client_1 [seatunnel] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is CLIENT_DISCONNECTED
2024-03-12 14:09:34,310 INFO  [c.h.c.LifecycleService        ] [main] - hz.client_1 [seatunnel] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is SHUTDOWN
2024-03-12 14:09:34,311 INFO  [s.c.s.s.c.ClientExecuteCommand] [main] - Closed SeaTunnel client......
Exception in thread "main" java.util.ServiceConfigurationError: org.apache.seatunnel.api.sink.SeaTunnelSink: Provider org.apache.seatunnel.connectors.seatunnel.iceberg.sink.IcebergSink could not be instantiated
        at java.util.ServiceLoader.fail(ServiceLoader.java:232)
        at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery.loadPluginInstance(AbstractPluginDiscovery.java:302)
        at org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery.createOptionalPluginInstance(AbstractPluginDiscovery.java:183)
        at org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery.createPluginInstance(AbstractPluginDiscovery.java:227)
        at org.apache.seatunnel.engine.core.parse.ConnectorInstanceLoader.loadSinkInstance(ConnectorInstanceLoader.java:77)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSink(JobConfigParser.java:194)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSinks(JobConfigParser.java:170)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSink(MultipleTableJobConfigParser.java:532)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:193)
        at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.getLogicalDag(ClientJobExecutionEnvironment.java:88)
        at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.execute(ClientJobExecutionEnvironment.java:156)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:146)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: java.lang.InstantiationException: org.apache.seatunnel.connectors.seatunnel.iceberg.sink.IcebergSink
        at java.lang.Class.newInstance(Class.java:427)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
        ... 15 more
Caused by: java.lang.NoSuchMethodException: org.apache.seatunnel.connectors.seatunnel.iceberg.sink.IcebergSink.<init>()
        at java.lang.Class.getConstructor0(Class.java:3082)
        at java.lang.Class.newInstance(Class.java:412)
        ... 16 more
[2]+  Done                    clear
```

**Comment by syyangs799** [comment]
I encountered the same problem，es->console and fake->hive is success,but es->hive is faild ,The reason for the error is also essink error。 This error occurred in both the dev and 2.3.4 branches


![image](https://github.com/apache/seatunnel/assets/55483518/3fe1db50-d45d-4ff9-b7bd-f6c3bdf6a5d9)

**Comment by LeonYoah** [comment]
我也遇到了 s3file-hive报错：
![1d690fb4a19d65acf4e406390533d49](https://github.com/apache/seatunnel/assets/95527066/3aabcc6c-adbf-4523-a5fd-c77fde033a1f)

**Comment by LeonYoah** [comment]
2.3.4 zeta引擎
