### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/flink/table/api/java/StreamTableEnvironment

### ISSUE THREAD

**Issue by x956606865** [apache/seatunnel#650]
使用spark的模式就可以正常使用，但是使用flink的模式，就会直接报错，不知道怎么处理Orz

**Waterdrop Version(Waterdrop版本)**

2.0.4

**Flink or Spark Version(Flink 或者 Spark 版本)**

1.13.2

**Java or Scala Version(Java或者Scala版本)**

1.8.0

**Waterdrop Config(Waterdrop配置文件)**

Please delete sensitive information(请注意删除敏感信息)

```
env {
  # Waterdrop defined streaming batch duration in seconds
#   spark.streaming.batchDuration = 5

#   spark.app.name = "cnb"
#   spark.ui.port = 13000
}

source {
     FakeSourceStream {
      result_table_name = "fake"
      field_name = "name,age"
    }
}

transform {
}

sink {
  ConsoleSink {}
}
```

**Running Command(启动命令)**

./bin/start-waterdrop-flink.sh  --config ./companies.conf

**Error Exception**

java.lang.NoClassDefFoundError: org/apache/flink/table/api/java/StreamTableEnvironment
        at io.github.interestinglab.waterdrop.flink.FlinkEnvironment.createStreamTableEnvironment(FlinkEnvironment.java:90)
        at io.github.interestinglab.waterdrop.flink.FlinkEnvironment.prepare(FlinkEnvironment.java:63)
        at io.github.interestinglab.waterdrop.flink.FlinkEnvironment.prepare(FlinkEnvironment.java:24)
        at io.github.interestinglab.waterdrop.config.ConfigBuilder.createEnv(ConfigBuilder.java:173)
        at io.github.interestinglab.waterdrop.config.ConfigBuilder.<init>(ConfigBuilder.java:38)
        at io.github.interestinglab.waterdrop.Waterdrop.entryPoint(Waterdrop.java:82)
        at io.github.interestinglab.waterdrop.Waterdrop.run(Waterdrop.java:50)
        at io.github.interestinglab.waterdrop.WaterdropFlink.main(WaterdropFlink.java:14)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:355)
        at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222)
        at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114)
        at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:812)
        at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:246)
        at org.apache.flink.client.cli.CliFrontend.parseAndRun(CliFrontend.java:1054)
        at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1132)
        at org.apache.flink.runtime.security.contexts.NoOpSecurityContext.runSecured(NoOpSecurityContext.java:28)
        at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1132)
Caused by: java.lang.ClassNotFoundException: org.apache.flink.table.api.java.StreamTableEnvironment
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at org.apache.flink.util.FlinkUserCodeClassLoader.loadClassWithoutExceptionHandling(FlinkUserCodeClassLoader.java:64)
        at org.apache.flink.util.ChildFirstClassLoader.loadClassWithoutExceptionHandling(ChildFirstClassLoader.java:65)
        at org.apache.flink.util.FlinkUserCodeClassLoader.loadClass(FlinkUserCodeClassLoader.java:48)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 21 more

**Screenshots**
If applicable, add screenshots to help explain your problem.（您可以将相关截图放在此处）

**Comment by ljw870202** [comment]
请问你问题解决了吗?

**Comment by ljw870202** [comment]
退回到flink1.9.1，可以运行

**Comment by x956606865** [comment]
> 退回到flink1.9.1，可以运行

真的吗？我试试呢，多谢
