### ISSUE TITLE
waterdrop 从hive到clickhouse 报错 clickHouse data type [(Map(String,String),false)] not support in current version

### ISSUE THREAD

**Issue by BarrelWhisky** [apache/seatunnel#652]
Waterdrop Version(Waterdrop版本)

waterdrop-1.5.3

clickhouse  Version

21.6.5.37

**clickhouse  Config 已经开启map支持**

<?xml version="1.0"?>
<yandex>
    <profiles>
        <default>
             <allow_experimental_map_type>1</allow_experimental_map_type>
         </default>
    </profiles>
</yandex>

clickhouse client 测试了，Map(String,String)类型能添加数据
┌─status─┬─app_key─┬─event_key─┬─user_key─┬─device_key─┬─start_time─┬─end_time─┬─report_time─┬─client_ip─────┬─uri──────────────────┬─refer───────────────┬─source─┬─target─┬─data──────────────────┬─day──────┬─hour─┐
│      0 │ 123     │ _VIEW     │ 22222    │ 1290       │         12 │       15 │          16 │ 129.168.1.111 │ http://www.baidu.com │ http://www.home.com │        │        │ {'s1':'a1','s2':'a2'} │ 20210831 │ 15   │
└────────┴─────────┴───────────┴──────────┴────────────┴────────────┴──────────┴─────────────┴───────────────┴──────────────────────┴─────────────────────┴────────┴────────┴───────────────────────┴──────────┴──────┘

data 是map类型

Please delete sensitive information(请注意删除敏感信息)

```
spark {
  spark.app.name = "Waterdrop"
  spark.executor.instances = 2
  spark.executor.cores = 1
  spark.executor.memory = "1g"
}
input {
    hive {
        pre_sql = "select * from log_system.log"
        table_name = "log"
    }
}
filter {
#    remove {
#        source_field = ["data"]
#    }
}
output {
    clickhouse {
        host = "hostname:8123"
        database = "test"
        table = "log2"
        fields = ["status", "app_key", "event_key", "user_key", "device_key", "start_time", "end_time", "report_time","client_ip","uri","refer","source","target","data","day","hour"]
        username = "..."
        password = "..."
    }
}
```

**Running Command(启动命令)**
请在这里添加完整的waterdrop启动命令及其参数。

bash start-waterdrop.sh --master yarn --deploy-mode client --config /opt/module/waterdrop-1.5.3/config/test_log2.conf

Error Exception

Add exception about the problem here.(您可以将程序报错信息粘贴在此处)

Exception in thread "main" io.github.interestinglab.waterdrop.config.ConfigRuntimeException: io.github.interestinglab.waterdrop.config.ConfigRuntimeException: clickHouse data type [(Map(String,String),false)] not support in current version.
        at io.github.interestinglab.waterdrop.Waterdrop$.showConfigError(Waterdrop.scala:79)
        at io.github.interestinglab.waterdrop.Waterdrop$.main(Waterdrop.scala:42)
        at io.github.interestinglab.waterdrop.Waterdrop.main(Waterdrop.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:851)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:926)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:935)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: io.github.interestinglab.waterdrop.config.ConfigRuntimeException: clickHouse data type [(Map(String,String),false)] not support in current version.
        at io.github.interestinglab.waterdrop.output.batch.Clickhouse.prepare(Clickhouse.scala:120)
        at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$basePrepare$1$$anonfun$apply$3.apply(Waterdrop.scala:257)
        at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$basePrepare$1$$anonfun$apply$3.apply(Waterdrop.scala:256)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$basePrepare$1.apply(Waterdrop.scala:256)
        at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$basePrepare$1.apply(Waterdrop.scala:255)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
        at io.github.interestinglab.waterdrop.Waterdrop$.basePrepare(Waterdrop.scala:255)
        at io.github.interestinglab.waterdrop.Waterdrop$.batchProcessing(Waterdrop.scala:190)
        at io.github.interestinglab.waterdrop.Waterdrop$.io$github$interestinglab$waterdrop$Waterdrop$$entrypoint(Waterdrop.scala:120)
        at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply$mcV$sp(Waterdrop.scala:38)
        at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply(Waterdrop.scala:38)
        at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply(Waterdrop.scala:38)
        at scala.util.Try$.apply(Try.scala:192)
        at io.github.interestinglab.waterdrop.Waterdrop$.main(Waterdrop.scala:38)

Screenshots
If applicable, add screenshots to help explain your problem.（您可以将相关截图放在此处）

**Comment by garyelephant** [comment]
@RickyHuo 帮忙看看

**Comment by ShawshankLin** [comment]
@garyelephant 这个可以支持吗，也有同样问题

**Comment by ruxtain** [comment]
现在貌似仍然不支持map类型？

**Comment by ruxtain** [comment]
Clickhouse version: 21.8.12
Seatunnel 1.5.7

User class threw exception: io.github.interestinglab.waterdrop.config.ConfigRuntimeException: io.github.interestinglab.waterdrop.config.ConfigRuntimeException: clickHouse data type [(Map(String,String),false)] not support in current version. at io.github.interestinglab.waterdrop.Waterdrop$.showConfigError(Waterdrop.scala:98) at io.github.interestinglab.waterdrop.Waterdrop$.main(Waterdrop.scala:61) at io.github.interestinglab.waterdrop.Waterdrop.main(Waterdrop.scala) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:684) Caused by: io.github.interestinglab.waterdrop.config.ConfigRuntimeException: clickHouse data type [(Map(String,String),false)] not support in current version. at io.github.interestinglab.waterdrop.output.batch.Clickhouse.prepare(Clickhouse.scala:139) at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$basePrepare$1$$anonfun$apply$3.apply(Waterdrop.scala:284) at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$basePrepare$1$$anonfun$apply$3.apply(Waterdrop.scala:283) at scala.collection.immutable.List.foreach(List.scala:392) at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$basePrepare$1.apply(Waterdrop.scala:283) at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$basePrepare$1.apply(Waterdrop.scala:282) at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35) at io.github.interestinglab.waterdrop.Waterdrop$.basePrepare(Waterdrop.scala:282) at io.github.interestinglab.waterdrop.Waterdrop$.batchProcessing(Waterdrop.scala:217) at io.github.interestinglab.waterdrop.Waterdrop$.io$github$interestinglab$waterdrop$Waterdrop$$entrypoint(Waterdrop.scala:144) at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply$mcV$sp(Waterdrop.scala:57) at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply(Waterdrop.scala:57) at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply(Waterdrop.scala:57) at scala.util.Try$.apply(Try.scala:192) at io.github.interestinglab.waterdrop.Waterdrop$.main(Waterdrop.scala:57) ... 6 more
