### ISSUE TITLE
[Bug] [rest-api]/hazelcast/rest/maps/submit-job java.lang.NullPointerException: null 

### ISSUE THREAD

**Issue by sandyustc** [apache/seatunnel#6530]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

/hazelcast/rest/maps/submit-job   ,  It‘s  error  when It is running on Postman .  

An error occurred while handling request HttpCommand [HTTP_POST]{uri='/hazelcast/rest/maps/submit-job?jobId=2&jobName=job006&isStartWithSavePoint=false'}AbstractTextCommand[HTTP_POST]{requestId=12}
java.lang.NullPointerException: null

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
{
	"env": {
		"parallelism": 4,
		"job.mode": "batch",
		"checkpoint.interval": 10000
	},
	"source": [{
		"jdbc": {
			"url": "jdbc:oracle:thin:@*.*.*.*:1521:orcl",
			"driver": "oracle.jdbc.OracleDriver",
			"connection_check_timeout_sec": 100,
			"user": "xtgg",
			"password": "xtgg",
			"query": "select * from  user",
			"partition_column": "id",
			"split.size": 10000
		}
	}],
	"sink": [{
		"jdbc": {
			"url": "jdbc:postgresql://*.*.*.*:5432/testDb",
			"driver": "org.postgresql.Driver",
			"user": "test",
			"password": "test",
			"generate_sink_sql": true,
			"database": "testDb",
			"table": "public.user",
			"schema_save_mode": "CREATE_SCHEMA_WHEN_NOT_EXIST",
			"data_save_mode": "APPEND_DATA",
			"primary_keys": "id"

		}
	}]
}
```

### Running Command

```shell
/hazelcast/rest/maps/submit-job
```

### Error Exception

```log
2024-03-18 18:11:43,946 INFO  org.apache.seatunnel.core.starter.utils.ConfigBuilder - Loading config file from objectMap
2024-03-18 18:11:43,947 INFO  org.apache.seatunnel.engine.server.job.JobImmutableInformationEnv - add common jar in plugins :[file:/opt/seatunnel-2.3.3/backend/apache-seatunnel-2.3.3/plugins/postgresql-42.7.2.jar, file:/opt/seatunnel-2.3.3/backend/apache-seatunnel-2.3.3/plugins/ojdbc8-23.3.0.23.09.jar, file:/opt/seatunnel-2.3.3/backend/apache-seatunnel-2.3.3/plugins/jdbc/lib/postgresql-42.7.2.jar]
2024-03-18 18:11:43,948 INFO  org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery - Load SeaTunnelSink Plugin from /opt/seatunnel-2.3.3/backend/apache-seatunnel-2.3.3/connectors/seatunnel
2024-03-18 18:11:43,948 WARN  org.apache.seatunnel.engine.server.log.Log4j2HttpPostCommandProcessor - [localhost]:5801 [seatunnel] [5.1] An error occurred while handling request HttpCommand [HTTP_POST]{uri='/hazelcast/rest/maps/submit-job?jobId=2&jobName=job006&isStartWithSavePoint=false'}AbstractTextCommand[HTTP_POST]{requestId=12}
java.lang.NullPointerException: null
	at org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery.findPluginJarPath(AbstractPluginDiscovery.java:341) ~[seatunnel-starter.jar:2.3.3]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[?:1.8.0_401]
	at org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery.getPluginJarPath(AbstractPluginDiscovery.java:319) ~[seatunnel-starter.jar:2.3.3]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_401]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[?:1.8.0_401]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_401]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_401]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_401]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_401]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_401]
	at org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery.getPluginJarPaths(AbstractPluginDiscovery.java:131) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.getConnectorJarList(MultipleTableJobConfigParser.java:227) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:160) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.core.job.AbstractJobEnvironment.getLogicalDag(AbstractJobEnvironment.java:109) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.server.job.JobImmutableInformationEnv.build(JobImmutableInformationEnv.java:76) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.server.rest.RestHttpPostCommandProcessor.handleSubmitJob(RestHttpPostCommandProcessor.java:112) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.server.rest.RestHttpPostCommandProcessor.handle(RestHttpPostCommandProcessor.java:68) ~[seatunnel-starter.jar:2.3.3]
	at org.apache.seatunnel.engine.server.rest.RestHttpPostCommandProcessor.handle(RestHttpPostCommandProcessor.java:47) ~[seatunnel-starter.jar:2.3.3]
	at com.hazelcast.internal.ascii.TextCommandServiceImpl$CommandExecutor.run(TextCommandServiceImpl.java:402) ~[seatunnel-starter.jar:2.3.3]
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217) ~[seatunnel-starter.jar:2.3.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_401]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_401]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_401]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[seatunnel-starter.jar:2.3.3]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[seatunnel-starter.jar:2.3.3]
```

### Java or Scala Version

java 1.8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
hi, when you use api to submit job, the config shoule be json format. can you provide the json config you posted, thx.

**Comment by sandyustc** [comment]
> hi, when you use api to submit job, the config shoule be json format. can you provide the json config you posted, thx.

@ liunaijie  thanks.

 I've submitted it as json. 


{
	"env": {
		"parallelism": 4,
		"job.mode": "batch",
		"checkpoint.interval": 10000
	},
	"source": [{
		"jdbc": {
			"url": "jdbc:oracle:thin:@*.*.*.*:1521:orcl",
			"driver": "oracle.jdbc.OracleDriver",
			"connection_check_timeout_sec": 100,
			"user": "xtgg",
			"password": "xtgg",
			"query": "select * from  user",
			"partition_column": "id",
			"split.size": 10000
		}
	}],
	"sink": [{
		"jdbc": {
			"url": "jdbc:postgresql://*.*.*.*:5432/testDb",
			"driver": "org.postgresql.Driver",
			"user": "test",
			"password": "test",
			"generate_sink_sql": true,
			"database": "testDb",
			"table": "public.user",
			"schema_save_mode": "CREATE_SCHEMA_WHEN_NOT_EXIST",
			"data_save_mode": "APPEND_DATA",
			"primary_keys": "id"

		}
	}]
}

**Comment by liunaijie** [comment]
@sandyustc the config format is not correct, please refer https://seatunnel.apache.org/docs/2.3.4/seatunnel-engine/rest-api#submit-job.
if you use api, the config is not like 
```
source {
  jdbc
}
```
it should be 
```
source [{
  "plugin_name" : "jdbc"
}]
```

You can update the config and retry.

**Comment by sandyustc** [comment]
> @sandyustc the config format is not correct, please refer https://seatunnel.apache.org/docs/2.3.4/seatunnel-engine/rest-api#submit-job. if you use api, the config is not like
> 
> ```
> source {
>   jdbc
> }
> ```
> 
> it should be
> 
> ```
> source [{
>   "plugin_name" : "jdbc"
> }]
> ```
> 
> You can update the config and retry.
  @liunaijie    
  I'll  try it ,  It is running Ok ,thanks!
