### ISSUE TITLE
mysql-CDC

### ISSUE THREAD

**Issue by Diamonddest** [apache/seatunnel#6566]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

execute mysql-cdc job，when ts_ms run at latest and will fetch incremental row，then job failed.

### SeaTunnel Version

2.3.4

### SeaTunnel Config

```conf
{
    "env" : {
        "parallelism" : 5,
        "job.mode" : "STREAMING",
        "checkpoint.interval" : 10000
    },
    "source" : [
        {
            "base-url" : "jdbc:mysql://sourceip:3306/test",
            "password" : "xxxxx",
            "primary_keys" : [
                "id"
            ],
            "start_mode" : "initial",
            "table-names" : [
                "test.veh"
            ],
            "stop.mode" : "never",
            "debeizum.snapshot.mode" : "when_needed",
            "plugin_name" : "MySQL-CDC",
            "server-id" : "40006-40010",
            "username" : "query_binlog"
        }
    ],
    "sink" : [
        {
            "password" : "xxxx",
            "database" : "after",
            "primary_keys" : [
                "id"
            ],
            "driver" : "com.mysql.cj.jdbc.Driver",
            "generate_sink_sql" : true,
            "plugin_name" : "jdbc",
            "user" : "as",
            "url" : "jdbc:mysql://targetip:3306/after",
            "table" : "after.test_cdc"
        }
    ]
}
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/10/test_cdc
```

### Error Exception

```log
The connector is trying to read binlog starting at Struct{version=1.6.4.Final,connector=mysql,name=mysql_binlog_source,ts_ms=1711351945553,db=,server_id=0,file=mysql-bin.113282,pos=43000053,row=0}, but this is no longer available on the server. Reconfigure the connector to use a snapshot when needed.
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Diamonddest** [comment]
more exceptions:

Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:199)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: java.lang.RuntimeException: One or more fetchers have encountered exception
        at org.apache.seatunnel.connectors.seatunnel.common.source.reader.fetcher.SplitFetcherManager.checkErrors(SplitFetcherManager.java:147)
        at org.apache.seatunnel.connectors.seatunnel.common.source.reader.SourceReaderBase.getNextFetch(SourceReaderBase.java:159)
        at org.apache.seatunnel.connectors.seatunnel.common.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:92)
        at org.apache.seatunnel.connectors.cdc.base.source.reader.IncrementalSourceReader.pollNext(IncrementalSourceReader.java:110)
        at org.apache.seatunnel.engine.server.task.flow.SourceFlowLifeCycle.collect(SourceFlowLifeCycle.java:150)
        at org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask.collect(SourceSeaTunnelTask.java:116)
        at org.apache.seatunnel.engine.server.task.SeaTunnelTask.stateProcess(SeaTunnelTask.java:168)
        at org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask.call(SourceSeaTunnelTask.java:121)
        at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:643)
        at org.apache.seatunnel.engine.server.TaskExecutionService$NamedTaskWrapper.run(TaskExecutionService.java:944)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: SplitFetcher thread 0 received unexpected exception while polling the records
        at org.apache.seatunnel.connectors.seatunnel.common.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:165)
        at org.apache.seatunnel.connectors.seatunnel.common.source.reader.fetcher.SplitFetcher.run(SplitFetcher.java:81)
        ... 5 more
Caused by: java.lang.IllegalStateException: The connector is trying to read binlog starting at Struct{version=1.6.4.Final,connector=mysql,name=mysql_binlog_source,ts_ms=1711351945553,db=,server_id=0,file=mysql-bin.113282,pos=43000053,row=0}, but this is no longer available on the server. Reconfigure the connector to use a snapshot when needed.
        at org.apache.seatunnel.connectors.seatunnel.cdc.mysql.source.reader.fetch.MySqlSourceFetchTaskContext.loadStartingOffsetState(MySqlSourceFetchTaskContext.java:262)
        at org.apache.seatunnel.connectors.seatunnel.cdc.mysql.source.reader.fetch.MySqlSourceFetchTaskContext.configure(MySqlSourceFetchTaskContext.java:119)
        at org.apache.seatunnel.connectors.cdc.base.source.reader.external.IncrementalSourceStreamFetcher.submitTask(IncrementalSourceStreamFetcher.java:97)
        at org.apache.seatunnel.connectors.cdc.base.source.reader.IncrementalSourceSplitReader.checkSplitOrStartNext(IncrementalSourceSplitReader.java:147)
        at org.apache.seatunnel.connectors.cdc.base.source.reader.IncrementalSourceSplitReader.fetch(IncrementalSourceSplitReader.java:71)
        at org.apache.seatunnel.connectors.seatunnel.common.source.reader.fetcher.FetchTask.run(FetchTask.java:54)
        at org.apache.seatunnel.connectors.seatunnel.common.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:162)
        ... 6 more

        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:191)
        ... 2 more

**Comment by hailin0** [comment]
The reason for this problem is that the mysql binlog location recorded when seatunnel started has been deleted.

https://github.com/apache/seatunnel/blob/dev/docs/en/connector-v2/source/MySQL-CDC.md#enabling-the-mysql-binlog

You should check:
1. Is `expire_logs_days` set large enough?

**Comment by huchao-hu** [comment]
@hailin0 It has been set up for 7 days but this problem still occurs

**Comment by huchao-hu** [comment]
@Diamonddest Have you solved the problem so far?
