### ISSUE TITLE
mysql_to_hive出现ClassNotFoundException：hive

### ISSUE THREAD

**Issue by zuoliansheng** [apache/seatunnel#657]
**Waterdrop Version(Waterdrop版本)**

1.5.3

**Flink or Spark Version(Flink 或者 Spark 版本)**

spark2.4.0

**Java or Scala Version(Java或者Scala版本)**

1.8.0

**Waterdrop Config(Waterdrop配置文件)**

Please delete sensitive information(请注意删除敏感信息)

```

  
spark {
    spark.app.name = "waterdrop_mysql_to_hive"
    spark.executor.instances = 2
    spark.executor.cores = 1
    spark.executor.memory = "1g"
}
input {
     mysql{
        url = "jdbc:mysql://localhost:3306/bigdata_app"
        table = "dim_geo_province_yf"
        result_table_name = "dim_geo_province_yf_log"
        user = "root"
        password = ""
   }
}
filter {
}
output {
    hive {
        source_table_name = "dim_geo_province_yf_log"
        result_table_name = "dim.dim_geo_province_yf"
        save_mode = "overwrite"
        sink_columns = "id,province,forshort,create_time,update_time"
        partition_by = ["create_time"]
  }
}
```

**Running Command(启动命令)**

./bin/start-waterdrop.sh  --master yarn --deploy-mode cluster  --config config/mysql_to_hive.conf

**Error Exception**
21/09/14 20:23:54 INFO yarn.Client: 
         client token: N/A
         diagnostics: User class threw exception: java.lang.Exception: java.lang.ClassNotFoundException: hive
        at io.github.interestinglab.waterdrop.Waterdrop$.main(Waterdrop.scala:43)
        at io.github.interestinglab.waterdrop.Waterdrop.main(Waterdrop.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:673)
Caused by: java.lang.ClassNotFoundException: hive
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at io.github.interestinglab.waterdrop.config.ConfigBuilder$$anonfun$createOutputs$1.apply(ConfigBuilder.scala:174)
        at io.github.interestinglab.waterdrop.config.ConfigBuilder$$anonfun$createOutputs$1.apply(ConfigBuilder.scala:163)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at io.github.interestinglab.waterdrop.config.ConfigBuilder.createOutputs(ConfigBuilder.scala:163)
        at io.github.interestinglab.waterdrop.Waterdrop$.io$github$interestinglab$waterdrop$Waterdrop$$entrypoint(Waterdrop.scala:113)
        at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply$mcV$sp(Waterdrop.scala:38)
        at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply(Waterdrop.scala:38)
        at io.github.interestinglab.waterdrop.Waterdrop$$anonfun$1.apply(Waterdrop.scala:38)
        at scala.util.Try$.apply(Try.scala:192)
        at io.github.interestinglab.waterdrop.Waterdrop$.main(Waterdrop.scala:38)
        ... 6 more

**Screenshots**
![Uploading image.png…]()

**Comment by garyelephant** [comment]
@zuoliansheng 你好，我定位一下问题

**Comment by chenhu** [comment]
我也遇到过同样的问题，不过跟他的场景有所不同。
1. WaterDrop版本 v1.5.3
2.  hive->clickhouse
3.  hive表为外部表，数据是通过nifi从外部数据源接入到hdfs，数据是orc，snappy压缩

解决办法：
-----------------------------探索过程----------------------------------
1. 当时实在定位不了问题，就把外部表里面的数据，导出到一个非外部表里面，并且也为orc格式。
重新执行后，成功hive->clickhouse。
2. 然后仍然用外部表，数据为orc无snappy压缩，重新执行，成功

还没有深入再重现问题，最近会再试试。

@zuoliansheng 希望对你有所帮助
