### ISSUE TITLE
[Bug] [REST API] call submit job API resulted in an error

### ISSUE THREAD

**Issue by ilsl1007** [apache/seatunnel#6581]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

The second call to the submit job API resulted in an error, The error occurred during the second call, which only modified the query's time range.

### SeaTunnel Version

2.3.4

### SeaTunnel Config

```conf
# first call:
{
    "env": {
        "execution.parallelism": 1,
        "job.mode": "BATCH"
    },
    "source": [
        {
            "plugin_name": "TDengine",
            "url": "jdbc:TAOS-RS://192.168.100.1:6041/",
            "username": "root",
            "password": "taosdata",
            "database": "test",
            "stable": "meters",
            "lower_bound": "2017-07-14 02:40:00.000",
            "upper_bound": "2017-07-14 02:40:00.006",
            "result_table_name": "tdengine_result"
        }
    ],
    "sink": [
        {
            "plugin_name": "TDengine",
            "url": "jdbc:TAOS-RS://192.168.100.2:6041/",
            "username": "root",
            "password": "taosdata",
            "database": "test",
            "stable": "meters",
            "timezone": "UTC"
        }
    ]
}

# second call:
{
    "env": {
        "execution.parallelism": 1,
        "job.mode": "BATCH"
    },
    "source": [
        {
            "plugin_name": "TDengine",
            "url": "jdbc:TAOS-RS://192.168.100.1:6041/",
            "username": "root",
            "password": "taosdata",
            "database": "test",
            "stable": "meters",
            "lower_bound": "2017-07-14 02:40:00.006",
            "upper_bound": "2017-07-14 02:40:00.010",
            "result_table_name": "tdengine_result"
        }
    ],
    "sink": [
        {
            "plugin_name": "TDengine",
            "url": "jdbc:TAOS-RS://192.168.100.2:6041/",
            "username": "root",
            "password": "taosdata",
            "database": "test",
            "stable": "meters",
            "timezone": "UTC"
        }
    ]
}
```

### Running Command

```shell
call the rest api
url is /hazelcast/rest/maps/submit-job
```

### Error Exception

```log
2024-03-26 17:45:37,052 INFO  [o.a.s.c.s.u.ConfigBuilder     ] [hz.main.cached.thread-1] - Loading config file from objectMap
2024-03-26 17:45:37,054 INFO  [o.a.s.c.s.u.ConfigBuilder     ] [hz.main.cached.thread-1] - Parsed config file: 
{
    "env" : {
        "execution.parallelism" : 1,
        "job.mode" : "BATCH"
    },
    "source" : [
        {
            "plugin_name" : "TDengine",
            "url" : "jdbc:TAOS-RS://192.168.100.1:6041/",
            "username" : "root",
            "password" : "taosdata",
            "database" : "test",
            "stable" : "meters",
            "lower_bound" : "2017-07-14 02:40:00.006",
            "upper_bound" : "2017-07-14 02:40:00.010",
            "result_table_name" : "tdengine_result"
        }
    ],
    "sink" : [
        {
            "plugin_name" : "TDengine",
            "url" : "jdbc:TAOS-RS://192.168.100.2:6041/",
            "username" : "root",
            "password" : "taosdata",
            "database" : "test",
            "stable" : "meters",
            "timezone" : "UTC"
        }
    ]
}

2024-03-26 17:45:37,055 INFO  [.r.RestJobExecutionEnvironment] [hz.main.cached.thread-1] - add common jar in plugins :[]
2024-03-26 17:45:37,057 INFO  [.s.p.d.AbstractPluginDiscovery] [hz.main.cached.thread-1] - Load SeaTunnelSink Plugin from /dataext/apache-seatunnel-2.3.4/connectors
2024-03-26 17:45:37,057 INFO  [.s.p.d.AbstractPluginDiscovery] [hz.main.cached.thread-1] - Discovery plugin jar for: PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='TDengine'} at: file:/dataext/apache-seatunnel-2.3.4/connectors/connector-tdengine-2.3.4.jar
2024-03-26 17:45:37,058 INFO  [.s.p.d.AbstractPluginDiscovery] [hz.main.cached.thread-1] - Discovery plugin jar for: PluginIdentifier{engineType='seatunnel', pluginType='sink', pluginName='TDengine'} at: file:/dataext/apache-seatunnel-2.3.4/connectors/connector-tdengine-2.3.4.jar
2024-03-26 17:45:37,058 INFO  [o.a.s.e.c.p.ConfigParserUtil  ] [hz.main.cached.thread-1] - Currently, incorrect configuration of source_table_name and result_table_name options don't affect job running. In the future we will ban incorrect configurations.
2024-03-26 17:45:37,058 WARN  [o.a.s.e.c.p.ConfigParserUtil  ] [hz.main.cached.thread-1] - This configuration is not recommended. A source/transform(TDengine) is configured with 'result_table_name' option value of 'tdengine_result', but subsequent transform/sink(TDengine) is not configured with 'source_table_name' option.
2024-03-26 17:45:37,059 INFO  [p.MultipleTableJobConfigParser] [hz.main.cached.thread-1] - start generating all sources.
2024-03-26 17:45:37,066 INFO  [.s.p.d.AbstractPluginDiscovery] [hz.main.cached.thread-1] - Load SeaTunnelSource Plugin from /dataext/apache-seatunnel-2.3.4/connectors
2024-03-26 17:45:37,066 INFO  [.s.p.d.AbstractPluginDiscovery] [hz.main.cached.thread-1] - Discovery plugin jar for: PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='TDengine'} at: file:/dataext/apache-seatunnel-2.3.4/connectors/connector-tdengine-2.3.4.jar
2024-03-26 17:45:37,068 INFO  [.s.p.d.AbstractPluginDiscovery] [hz.main.cached.thread-1] - Load plugin: PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='TDengine'} from classpath
2024-03-26 17:45:37,071 WARN  [Log4j2HttpPostCommandProcessor] [hz.main.cached.thread-1] - [localhost]:5801 [seatunnel] [5.1] An error occurred while handling request HttpCommand [HTTP_POST]{uri='/hazelcast/rest/maps/submit-job'}AbstractTextCommand[HTTP_POST]{requestId=1}
java.sql.SQLException: No suitable driver found for jdbc:TAOS-RS://192.168.100.1:6041/test?user=root&password=taosdata
        at java.sql.DriverManager.getConnection(DriverManager.java:689) ~[?:1.8.0_311]
        at java.sql.DriverManager.getConnection(DriverManager.java:270) ~[?:1.8.0_311]
        at org.apache.seatunnel.connectors.seatunnel.tdengine.source.TDengineSource.getStableMetadata(TDengineSource.java:138) ~[?:?]
        at org.apache.seatunnel.connectors.seatunnel.tdengine.source.TDengineSource.prepare(TDengineSource.java:90) ~[?:?]
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSource(JobConfigParser.java:84) ~[seatunnel-starter.jar:2.3.4]
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:315) ~[seatunnel-starter.jar:2.3.4]
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:181) ~[seatunnel-starter.jar:2.3.4]
        at org.apache.seatunnel.engine.server.rest.RestJobExecutionEnvironment.getLogicalDag(RestJobExecutionEnvironment.java:76) ~[seatunnel-starter.jar:2.3.4]
        at org.apache.seatunnel.engine.server.rest.RestJobExecutionEnvironment.build(RestJobExecutionEnvironment.java:99) ~[seatunnel-starter.jar:2.3.4]
        at org.apache.seatunnel.engine.server.rest.RestHttpPostCommandProcessor.handleSubmitJob(RestHttpPostCommandProcessor.java:136) ~[seatunnel-starter.jar:2.3.4]
        at org.apache.seatunnel.engine.server.rest.RestHttpPostCommandProcessor.handle(RestHttpPostCommandProcessor.java:82) ~[seatunnel-starter.jar:2.3.4]
        at org.apache.seatunnel.engine.server.rest.RestHttpPostCommandProcessor.handle(RestHttpPostCommandProcessor.java:60) ~[seatunnel-starter.jar:2.3.4]
        at com.hazelcast.internal.ascii.TextCommandServiceImpl$CommandExecutor.run(TextCommandServiceImpl.java:402) ~[seatunnel-starter.jar:2.3.4]
        at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217) ~[seatunnel-starter.jar:2.3.4]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_311]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_311]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_311]
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[seatunnel-starter.jar:2.3.4]
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[seatunnel-starter.jar:2.3.4]
```

### Zeta or Flink or Spark Version

Zeta

### Java or Scala Version

java version "1.8.0_311"
Java(TM) SE Runtime Environment (build 1.8.0_311-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.311-b11, mixed mode)

### Screenshots

first call:
![first call](https://github.com/apache/seatunnel/assets/26399744/71e10773-8668-42a8-86aa-4169585e37f8)

second call:
![second call](https://github.com/apache/seatunnel/assets/26399744/b2613799-1946-464d-89ac-b27eef884329)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
@ilsl1007  you need manually put the driver lib to `/lib` folder

**Comment by liunaijie** [comment]
I also meet same issue, and this pr https://github.com/apache/seatunnel/pull/6477 fixed this issue, you can try with this.

**Comment by ilsl1007** [comment]
> I also meet same issue, and this pr #6477 fixed this issue, you can try with this.

@liunaijie hello，I built the installation package based on the latest code from the dev branch, and after testing, the same issue persists. Testing with MySQL was successful.

![image](https://github.com/apache/seatunnel/assets/26399744/93be50f0-2608-4eda-88bf-110e11e49666)

**Comment by liunaijie** [comment]
hi @ilsl1007 Is your first submit can success, then all failed? Before this pr my temporary solution is load the driver every time.

**Comment by ilsl1007** [comment]
> hi @ilsl1007 Is your first submit can success, then all failed? Before this pr my temporary solution is load the driver every time.

@liunaijie Yes, only the first subit success. What modifications do I need to make for the temporary solution you mentioned about reloading the driver every time?

**Comment by liunaijie** [comment]
> > hi @ilsl1007 Is your first submit can success, then all failed? Before this pr my temporary solution is load the driver every time.
> 
> @liunaijie Yes, only the first subit success. What modifications do I need to make for the temporary solution you mentioned about reloading the driver every time?

you can update the `TDengineSource` class, add this code `Class.forName("your driver class");`
maybe you also need update `TDengineSourceReader` class.
load the driver before you use it

**Comment by liunaijie** [comment]
and maybe i know why this pr is not work for your case.
You use `TDengineSource`, this is different with JdbcSource.  JdbcSource is create by JdbcSourceFactory. maybe this is not why this  fix is not work for you.

**Comment by ilsl1007** [comment]
> and maybe i know why this pr is not work for your case. You use `TDengineSource`, this is different with JdbcSource. JdbcSource is create by JdbcSourceFactory. maybe this is not why this fix is not work for you.

@liunaijie Thank you. After using the temporary solution you mentioned, I'm now able to call the API successfully.

**Comment by liunaijie** [comment]
> > and maybe i know why this pr is not work for your case. You use `TDengineSource`, this is different with JdbcSource. JdbcSource is create by JdbcSourceFactory. maybe this is not why this fix is not work for you.
> 
> @liunaijie Thank you. After using the temporary solution you mentioned, I'm now able to call the API successfully.

np~
