### ISSUE TITLE
同步ES到HDFS时，在Yarn运行失败，但是Local运行没问题

### ISSUE THREAD

**Issue by 97wufei** [apache/seatunnel#663]
**seatunnel Version(seatunnel版本)**

waterdrop-core-2.0.0-alpha-2.11.8

**Flink or Spark Version(Flink 或者 Spark 版本)**

Spark 2.4.0

**Java or Scala Version(Java或者Scala版本)**

Java 1.8.0_u111 

**seatunnel Config(seatunnel配置文件)**

Please delete sensitive information(请注意删除敏感信息)

```
  env {
    spark.app.name = "ES2HDFS"
    spark.executor.instances = 1
    spark.executor.cores = 1
    spark.executor.memory = "1g"
  }

  source{
    elasticsearch {
      hosts = ["xx.xx.xx.xx:9200"]
      index = "test"
      es.read.field.include = "timestamp,ip,proto"
      result_table_name = "tmp"
    }
  }

  transform {
  
  }

  sink {
    hdfs {
      path = "hdfs://xx.xx.xx.xx:8020//user/hive/warehouse/xx"
      save_mode = append
      serializer = csv
    }
  }
```

**Running Command(启动命令)**

/opt/module/waterdrop/bin/start-waterdrop-spark.sh --master yarn --deploy-mode client --config /opt/module/waterdrop/job/conf/es2hdfs.conf

**Error Exception**
Job aborted due to stage failure: 
Aborting TaskSet 0.0 because task 0 (partition 0)
cannot run anywhere due to node and executor blacklist.
Most recent failure:
Lost task 0.1 in stage 0.0 (TID 1, cdh01, executor 2): java.lang.IllegalAccessError: class org.apache.hadoop.hdfs.web.HftpFileSystem cannot access its superinterface org.apache.hadoop.hdfs.web.TokenAspect$TokenManagementDelegator
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.apache.hadoop.fs.FileSystem.loadFileSystems(FileSystem.java:3151)
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3196)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3235)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:123)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3286)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3254)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:478)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:361)
	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.<init>(FileOutputCommitter.java:149)
	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.<init>(FileOutputCommitter.java:105)
	at org.apache.hadoop.mapreduce.lib.output.PathOutputCommitterFactory.createFileOutputCommitter(PathOutputCommitterFactory.java:134)
	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitterFactory.createOutputCommitter(FileOutputCommitterFactory.java:35)
	at org.apache.hadoop.mapreduce.lib.output.FileOutputFormat.getOutputCommitter(FileOutputFormat.java:338)
	at org.apache.spark.internal.io.HadoopMapReduceCommitProtocol.setupCommitter(HadoopMapReduceCommitProtocol.scala:100)
	at org.apache.spark.sql.execution.datasources.SQLHadoopMapReduceCommitProtocol.setupCommitter(SQLHadoopMapReduceCommitProtocol.scala:40)
	at org.apache.spark.internal.io.HadoopMapReduceCommitProtocol.setupTask(HadoopMapReduceCommitProtocol.scala:217)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:229)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:170)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:169)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$11.apply(Executor.scala:407)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1408)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:413)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Blacklisting behavior can be configured via spark.blacklist.*.

**Screenshots**
![image2021-11-5_14-48-38](https://user-images.githubusercontent.com/70624523/140602488-9c7112fd-13ec-4555-9cd8-5806aec39576.png)

**Comment by 97wufei** [comment]
我看其他 issue下看到回答说 waterdrop v2.x 不支持hadoop3.0.0 ；那么为什么在local模式下会运行成功呢？

**Comment by RickyHuo** [comment]
@97wufei Local mode doesn't use hadoop cluster.
