### ISSUE TITLE
[Bug] [connector-rabbitmq] Failed to trigger checkpoint and job cannot work

### ISSUE THREAD

**Issue by alextinng** [apache/seatunnel#6671]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I create a pipeline to ingest data from rabbitmq and then write them into mysql which is submited to flink on yarn. During testing, I found no incremental data in mysql, so I checked flink job, found so many failed checkpoint(throw npes)

exception stack: 
```
2024-04-09 14:23:04,883 WARN  org.apache.flink.runtime.checkpoint.CheckpointCoordinator    [] - Failed to trigger checkpoint 1 for job 1703a972f2085a42b23fedf120147d4e. (1 consecutive failed attempts so far)
java.lang.NullPointerException: null
        at org.apache.flink.runtime.source.coordinator.SourceCoordinator.writeCheckpointBytes(SourceCoordinator.java:388) ~[flink-dist_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.runtime.source.coordinator.SourceCoordinator.toBytes(SourceCoordinator.java:372) ~[flink-dist_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$checkpointCoordinator$5(SourceCoordinator.java:246) ~[flink-dist_2.11-1.14.2.jar:1.14.2]
        at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:331) ~[flink-dist_2.11-1.14.2.jar:1.14.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_311]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_311]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_311]
```

### SeaTunnel Version

2.3.4

### SeaTunnel Config

```conf
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
######
###### This config file is a demonstration of streaming processing in SeaTunnel config
######

env {
  # You can set SeaTunnel environment configuration here
  parallelism = 1
  job.mode = "STREAMING"
  checkpoint.interval = 3000
}

source {
  # This is a example source plugin **only for test and demonstrate the feature source plugin**
  RabbitMQ {
    host = "localhost"
    port = 23333
    virtual_host = "/"
    username = "user"
    password = "passwd"
    queue_name = "queue-name"
    schema = {
        fields {
            userReviews = string
            negativeFeedback = boolean
            phone = string
            response = string
            tenantId = long
            prompt = string
        }
    }
  }

  # If you would like to get more information about how to configure SeaTunnel and see full list of source plugins,
  # please go to https://seatunnel.apache.org/docs/category/source-v2
}

sink {
#  Console {
#  }
jdbc {
    url = "jdbc:mysql://localhost:3306/db"
    driver = "com.mysql.cj.jdbc.Driver"
    user = "user"
    password = "passwd"
    query = "insert into user_feedback(user_reviews,negative_feedback,phone,response,tenant_id,prompt) values(?,?,?,?,?,?)"
}

  # If you would like to get more information about how to configure SeaTunnel and see full list of sink plugins,
  # please go to https://seatunnel.apache.org/docs/category/sink-v2
}
```

### Running Command

```shell
flink run -d -m yarn-cluster -ynm seatunnel-streaming-template -c org.apache.seatunnel.core.starter.flink.SeaTunnelFlink /opt/apache-seatunnel-2.3.4/starter/seatunnel-flink-13-starter.jar --config s1.conf --name SeaTunnel
```

### Error Exception

```log
see above
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
can you attach more detail log, those are flink class error log, if there has seatunnel class log would be better.

**Comment by alextinng** [comment]
@liunaijie this is detailed yarn application log

[t.log](https://github.com/apache/seatunnel/files/14956792/t.log)

**Comment by alextinng** [comment]
possible cause:

return null when create snapshot
![image](https://github.com/apache/seatunnel/assets/17078980/e1adddc9-c165-4581-972e-7c8c0ebbab08)

**Comment by alextinng** [comment]
@liunaijie also found in zeta!!!
