### ISSUE TITLE
[Bug] [JDBC] JDBC SQLSERVER  use table_path reports  error when filedname is  KEY WORD

### ISSUE THREAD

**Issue by bjdaijun** [apache/seatunnel#6675]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I use JDBC to sync SQLSERVER, but reports error. 
And after testing, I found that it's about my field name , it's called [index], and it's conflict with SQLSERVER KEY WORD.
As it's report, I should use [index] in my sql.

But I am using table_path to select table, and there is no place to write SQL like: select [index] ...

So what should I do to solve this?

### SeaTunnel Version

2.3.4

### SeaTunnel Config

```conf
"source" : [
        {
            "plugin_name" : "Jdbc",
            "url" : "jdbc:sqlserver://10.0.0.10:1433;databaseName=WD_3219;encrypt=false;",
            "driver" : "com.microsoft.sqlserver.jdbc.SQLServerDriver",
            "connection_check_timeout_sec" : 100,
            "user" : "sa",
            "password" : "123456",
            "result_table_name" : "t1",
            "table_path" : "WD_3219.dbo.RawData",
            "where_condition" : "where 1 = 1"
        }
    ],
```

### Running Command

```shell
no
```

### Error Exception

```log
org.apache.seatunnel.connectors.seatunnel.jdbc.exception.JdbcConnectorException: ErrorCode:[JDBC-04], ErrorDescription:[Connector database failed] - open() failed.“index”附近有语法错误。如果它要作为表提示的一部分，则必须有 WITH 关键字和圆括号。有关正确的语法，请参阅 SQL Server 联机丛书。
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.JdbcInputFormat.open(JdbcInputFormat.java:104) ~[?:?]
	at org.apache.seatunnel.connectors.seatunnel.jdbc.source.JdbcSourceReader.pollNext(JdbcSourceReader.java:67) ~[?:?]
	at org.apache.seatunnel.engine.server.task.flow.SourceFlowLifeCycle.collect(SourceFlowLifeCycle.java:150) ~[seatunnel-starter.jar:2.3.4]
	at org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask.collect(SourceSeaTunnelTask.java:116) ~[seatunnel-starter.jar:2.3.4]
	at org.apache.seatunnel.engine.server.task.SeaTunnelTask.stateProcess(SeaTunnelTask.java:168) ~[seatunnel-starter.jar:2.3.4]
	at org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask.call(SourceSeaTunnelTask.java:121) ~[seatunnel-starter.jar:2.3.4]
	at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:643) ~[seatunnel-starter.jar:2.3.4]
	at org.apache.seatunnel.engine.server.TaskExecutionService$NamedTaskWrapper.run(TaskExecutionService.java:944) ~[seatunnel-starter.jar:2.3.4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_342]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_342]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_342]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_342]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_342]
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by chenshu612** [comment]
You can try add "query = "select [index]  as index_1 from WD_3219.dbo.RawData"" in jdbc{} , because the example in JDBC use  table_path as table name too.

env {
  parallelism = 10
  job.mode = "BATCH"
}
source {
    Jdbc {
        url = "jdbc:mysql://localhost/test?serverTimezone=GMT%2b8"
        driver = "com.mysql.cj.jdbc.Driver"
        connection_check_timeout_sec = 100
        user = "root"
        password = "123456"
        table_path = "testdb.table1"
        query = "select * from testdb.table1"
        split.size = 10000
    }
}
sink {
  Console {}
}

I didn't find the [index] in the config you provided，perhaps you can provide a complete config for a better explanation.

**Comment by bjdaijun** [comment]
> You can try add "query = "select [index] as index_1 from WD_3219.dbo.RawData"" in jdbc{} , because the example in JDBC use table_path as table name too.
> 
> env { parallelism = 10 job.mode = "BATCH" } source { Jdbc { url = "jdbc:mysql://localhost/test?serverTimezone=GMT%2b8" driver = "com.mysql.cj.jdbc.Driver" connection_check_timeout_sec = 100 user = "root" password = "123456" table_path = "testdb.table1" query = "select * from testdb.table1" split.size = 10000 } } sink { Console {} }
> 
> I didn't find the [index] in the config you provided，perhaps you can provide a complete config for a better explanation.


Yes, I know I can use query="select [index] ...", I wrote this because I had test it.

But in this case, I want use table_path="dbo.table", and not use the query to supply some sql, (user of my software may not good at write SQL).

**Comment by bjdaijun** [comment]
Also Tested with SQLServer CDC, It's also reports some error about the field "index".  That it's can not deal with field name or table name that is SQLSERVER KEY WORD

**Comment by dailai** [comment]
This is indeed a bug and I intend to fix it.

**Comment by dailai** [comment]
Refer: https://github.com/apache/seatunnel/pull/6669

**Comment by Hisoka-X** [comment]
Closed by https://github.com/apache/seatunnel/pull/6669
