### ISSUE TITLE
[Bug] [S3File] [zeta-local] Error writing to S3File in version 2.3.4:: Java lang. An IllegalStateException: Connection pool shut down

### ISSUE THREAD

**Issue by LeonYoah** [apache/seatunnel#6678]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When jdbc- > s3File is executed using the local mode, it occurs sporadically, good and bad in most cases, but there is no problem with using the cluster mode: 
![image](https://github.com/apache/seatunnel/assets/95527066/f65fe0eb-ee49-4e61-a2e1-af19c609b326)

I probably searched for this error about using aws-sdk: Connection pool shut down, the related issues is https://github.com/awslabs/amazon-sqs-java-messaging-lib/issues/96. 
It mentions the problem of multithreaded connection pooling, so I initially guess whether it is possible that there is a [aggregate commit] operation after [S3file] executes the [sink] operation, but the [sink] operation executes the close method, which causes the [rename] of [commit] to report an error, indicating that the connection pool is closed, but why the lcoal mode is good and bad, the cluster mode is not a problem. 
And I've tried the 2.3.3 local mode, and that's not the case.
[error.txt](https://github.com/apache/seatunnel/files/14928339/error.txt)

### SeaTunnel Version

2.3.4

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
  job.mode = "BATCH"
}

source {
	Jdbc {
		result_table_name = "TEST_100W"
		query = "select * from SYSDBA.TEST_100W limit 10"
		fetch_size = 5000
		table_path = "SYSDBA.TEST_100W"
		driver = "com.mysql.cj.jdbc.Driver"
		url = "jdbc:mysql://10.28.23.xxx:3306/test"
		user = "test"
		password ="xxx"
	} 
}
sink {
  S3File {
    source_table_name = "aa"
    path = "/xugurtp/seatunnel/tmp/6af80b38f3434aceb573cc65b9cd12216a/3918"
    bucket = "s3a://xugurtp"
    fs.s3a.endpoint = "http://10.28.23.xxx:9010"
    fs.s3a.aws.credentials.provider = "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
    access_key = "xxxx"
    secret_key = "xxxxxxx"
    custom_filename = true
    file_name_expression = "output_params"
    file_format_type = "json"
    is_enable_transaction = false
    ##sink_columns = ["ID"]
  }
}
```

### Running Command

```shell
./bin/seatunnel.sh  -e local --config job/s3_sink.conf
```

### Error Exception

```log
2024-04-10 14:02:28,387 ERROR [.c.FileSinkAggregatedCommitter] [hz.main.generic-operation.thread-43] - commit aggregatedCommitInfo error, aggregatedCommitInfo = FileAggregatedCommitInfo(transactionMap={/tmp/seatunnel/seatunnel/830321799827816449/3eff006528/T_830321799827816449_3eff006528_0_1={/tmp/seatunnel/seatunnel/830321799827816449/3eff006528/T_830321799827816449_3eff006528_0_1/NON_PARTITION/output_params_0.json=/xugurtp/seatunnel/tmp/6af80b38f3434aceb573cc65b9cd12216a/3918/output_params_0.json}}, partitionDirAndValuesMap={}) 
java.lang.IllegalStateException: Connection pool shut down
        at com.amazonaws.thirdparty.apache.http.util.Asserts.check(Asserts.java:34) ~[aws-java-sdk-bundle-1.11.271.jar:?]
        at com.amazonaws.thirdparty.apache.http.pool.AbstractConnPool.lease(AbstractConnPool.java:184) ~[aws-java-sdk-bundle-1.11.271.jar:?]
        at com.amazonaws.thirdparty.apache.http.impl.conn.PoolingHttpClientConnectionManager.requestConnection(PoolingHttpClientConnectionManager.java:251) ~[aws-java-sdk-bundle-1.11.271.jar:?]
```

### Zeta or Flink or Spark Version

local模式

### Java or Scala Version

1.8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by LeonYoah** [comment]
In addition, there's nothing wrong with debugging with idea, but that's what happens on the server.

**Comment by LeonYoah** [comment]
@ruanwenjun may have something to do with your issue #5903, which is whether checkpoint uses hdfs or cache. I saw that you submitted #6039 and noticed the cache problem, but checkpoint did not: 在这个类；org.apache.seatunnel.engine.checkpoint.storage.hdfs.common.HdfsConfiguration
![image](https://github.com/apache/seatunnel/assets/95527066/41fa908c-8775-4267-a392-a98cab46180f)

**Comment by LeonYoah** [comment]
And this code:
![f69f6109842ad735b032077b37310df](https://github.com/apache/seatunnel/assets/95527066/ddf8d6c7-bfa2-44af-afc2-2c3f1c186bd3)
![d9e9d4eb54ab346be53e7b1dadb6e56](https://github.com/apache/seatunnel/assets/95527066/a46883bb-48e0-4483-837e-86eabd428900)
Sometimes hadoopConf's getSchema method returns s3n instead of s3a, resulting in the s3 connector actually being cached

**Comment by LeonYoah** [comment]
## s3n is because the S3Conf obtained from AggregatedCommit does not use this buildWithConfig method, but uses DEFAULT_SCHEMA. debug finds that it seems to be related to dag:


### buildWithConfig method screenshot：
![image](https://github.com/apache/seatunnel/assets/95527066/020d7ed9-c0da-4c33-9e7d-47d8b9352203)

### DAG initialization S3conf screenshot：
![image](https://github.com/apache/seatunnel/assets/95527066/d2f52d04-3c2b-4a53-981d-7e13e192361e)

![image](https://github.com/apache/seatunnel/assets/95527066/921bc56c-1dec-4655-afbc-cc76c9adbcf7)
### AggregatedCommit获取的hadoopconf和shema截图：
![image](https://github.com/apache/seatunnel/assets/95527066/7d6fe287-f3ff-4145-af0d-6f3b9cbe22b2)

## So far I have found two solutions:
### 1. Change DEFAULT_SCHEMA to s3a：
![image](https://github.com/apache/seatunnel/assets/95527066/c2c2b714-db70-4d09-b620-e86060f62e8c)

### 2. Set up the profile：
![image](https://github.com/apache/seatunnel/assets/95527066/80438746-fdae-45a8-90bf-9ef36ee44a5d)


_ But I am not familiar with the code of dag and AggregatedCommint, I need to ask my teacher to help me look at the root cause! _

**Comment by LeonYoah** [comment]
@EricJoy2048 I see that you have been working on the mutli table feature #6698  of S3file connector recently. Have you ever encountered that the schema in hadoop conf obtained by mutli table is the default s3n instead of the s3a specified in the configuration file

**Comment by EricJoy2048** [comment]
I'll look at that as soon as I can

**Comment by EricJoy2048** [comment]
1. SeaTunnel Engine(Zeta) will use hdfs api to write checkpoint to FileSystem, The config is at `$SEATUNNEL_HOME/conf/seatunnel.yaml`, And the codes are in `seatunnel-engine/seatunnel-engine-storage/checkpoint-storage-plugins/checkpoint-storage-hdfs/src/main/java/org/apache/seatunnel/engine/checkpoint/storage/hdfs/common` package . I do not know the content about this config file in your environment, But I think we need disable the cache in checkpoint storage too.

**Comment by EricJoy2048** [comment]
2. I can show you how the `FileSinkAggregatedCommitter` init.
<img width="1437" alt="image" src="https://github.com/apache/seatunnel/assets/32193458/154d51d3-fc7d-4629-b501-b5e81dc88ef7">

<img width="1370" alt="image" src="https://github.com/apache/seatunnel/assets/32193458/b58d1ed0-8522-478e-b11f-8ed732337f8b">


<img width="1447" alt="image" src="https://github.com/apache/seatunnel/assets/32193458/e323e48f-65ad-4523-8364-572a980fad0e">

**Comment by EricJoy2048** [comment]
<img width="1418" alt="image" src="https://github.com/apache/seatunnel/assets/32193458/dc9a0c53-0812-49d3-a53b-61ec6547f27d">

**Comment by EricJoy2048** [comment]
`Sometimes hadoopConf's getSchema method returns s3n instead of s3a, resulting in the s3 connector actually being cached` Is this reproducible?

**Comment by LeonYoah** [comment]
Yes, I am now 100% repeat, I officially downloaded a seatunnel2.3.4 package and plug-in, deployed on the server and executed in local mode, there will be such a problem, but local idea debugging is not possible, it cannot appear

**Comment by LeonYoah** [comment]
> `Sometimes hadoopConf's getSchema method returns s3n instead of s3a, resulting in the s3 connector actually being cached` Is this reproducible?#00000;是可复制的？

Yes, I am now 100% repeat, I officially downloaded a seatunnel2.3.4 package and plug-in, deployed on the server and executed in local mode, there will be such a problem, but local idea debugging is not possible, it cannot appear

**Comment by EricJoy2048** [comment]
> `Sometimes hadoopConf's getSchema method returns s3n instead of s3a, resulting in the s3 connector actually being cached` Is this reproducible?

Can you try use remote debug?

**Comment by LeonYoah** [comment]
> > `Sometimes hadoopConf's getSchema method returns s3n instead of s3a, resulting in the s3 connector actually being cached` Is this reproducible?#00000;是可复制的？
> 
> Can you try use remote debug?你能尝试使用远程调试吗？

 Yes, I discovered through remote debugging that s3n was actually being passed
![image](https://github.com/apache/seatunnel/assets/95527066/f0edc7a4-25a3-42d6-86ed-c06332b8fd86)

**Comment by EricJoy2048** [comment]
> 我注意到这块代码其实是没问题的，通过执行buildwith方法会赋值shema为s3a，但是关键在于整个sink往下游传递给mutiltable sink时，会执行反序列化操作
> 
> > > `Sometimes hadoopConf's getSchema method returns s3n instead of s3a, resulting in the s3 connector actually being cached` Is this reproducible?#00000;是可复制的？
> > 
> > 
> > Can you try use remote debug?你能尝试使用远程调试吗？
> 
> Yes, I discovered through remote debugging that s3n was actually being passed ![image](https://private-user-images.githubusercontent.com/95527066/322695614-f0edc7a4-25a3-42d6-86ed-c06332b8fd86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMzk5MjMsIm5iZiI6MTcxMzIzOTYyMywicGF0aCI6Ii85NTUyNzA2Ni8zMjI2OTU2MTQtZjBlZGM3YTQtMjVhMy00MmQ2LTg2ZWQtYzA2MzMyYjhmZDg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDAzNTM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwMWE1MWI3YTVkMmE0ZTQxNGY5ODIyY2I3ZmE3MTkzMTk0OTQ3ZDIyODAxODIyMzlkZGJkYWNhYzlmZDU4NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TtE9gCN9ND-N2d65OutPW5v1iLjo8arHHa4dOCZ9nvI)

I understand now. It's really a matter of serialization and deserialization of `static variables`. I don't think we should define `static variables` for classes that need to be serialized and deserialized. Can you put up a pr to fix this?

**Comment by LeonYoah** [comment]
> > `Sometimes hadoopConf's getSchema method returns s3n instead of s3a, resulting in the s3 connector actually being cached` Is this reproducible?#00000;是可复制的？
> 
> Can you try use remote debug?你能尝试使用远程调试吗？

I seem to have spotted the problem, noting that this code is actually fine, by executing the buildWithConfig method it assigns [SCHEMA] to "s3a", but the key is that when the whole [sink] is passed downstream to [multiTableSink], it is de-serialized, The deserialization process re-instantiates the static variables, and the member variables of the entire S3CONF class are [stastic] modified, including [SCHEMA], resulting in [mutiltable sink] getting the default value of [SCHEMA], which is "s3n".

![image](https://github.com/apache/seatunnel/assets/95527066/1c293cd0-9fb9-4a9f-b41f-406fb3197a53)

**Comment by LeonYoah** [comment]
> > 我注意到这块代码其实是没问题的，通过执行buildwith方法会赋值shema为s3a，但是关键在于整个sink往下游传递给mutiltable sink时，会执行反序列化操作
> > > > `Sometimes hadoopConf's getSchema method returns s3n instead of s3a, resulting in the s3 connector actually being cached` Is this reproducible?#00000;是可复制的？
> > > 
> > > 
> > > Can you try use remote debug?你能尝试使用远程调试吗？
> > 
> > 
> > Yes, I discovered through remote debugging that s3n was actually being passed <img alt="image" width="54.140625" height="21" src="https://private-user-images.githubusercontent.com/95527066/322695614-f0edc7a4-25a3-42d6-86ed-c06332b8fd86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMzk5MjMsIm5iZiI6MTcxMzIzOTYyMywicGF0aCI6Ii85NTUyNzA2Ni8zMjI2OTU2MTQtZjBlZGM3YTQtMjVhMy00MmQ2LTg2ZWQtYzA2MzMyYjhmZDg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDAzNTM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwMWE1MWI3YTVkMmE0ZTQxNGY5ODIyY2I3ZmE3MTkzMTk0OTQ3ZDIyODAxODIyMzlkZGJkYWNhYzlmZDU4NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TtE9gCN9ND-N2d65OutPW5v1iLjo8arHHa4dOCZ9nvI">是的，我通过远程调试发现s3n实际上正在传递 <img alt="image" width="54.140625" height="21" src="https://private-user-images.githubusercontent.com/95527066/322695614-f0edc7a4-25a3-42d6-86ed-c06332b8fd86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMzk5MjMsIm5iZiI6MTcxMzIzOTYyMywicGF0aCI6Ii85NTUyNzA2Ni8zMjI2OTU2MTQtZjBlZGM3YTQtMjVhMy00MmQ2LTg2ZWQtYzA2MzMyYjhmZDg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDAzNTM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwMWE1MWI3YTVkMmE0ZTQxNGY5ODIyY2I3ZmE3MTkzMTk0OTQ3ZDIyODAxODIyMzlkZGJkYWNhYzlmZDU4NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TtE9gCN9ND-N2d65OutPW5v1iLjo8arHHa4dOCZ9nvI">
> 
> I understand now. It's really a matter of serialization and deserialization of `static variables`. I don't think we should define `static variables` for classes that need to be serialized and deserialized. Can you put up a pr to fix this?我现在明白了这实际上是 `static variables` 的序列化和重复化的问题。我不认为我们应该为需要序列化和非序列化的类定义 `static variables` 。你能做个公关来解决这个问题吗？

Ok, I am willing to submit the PR, I have modified the first version to try to remove the [static] changes, but I see that you submitted a change to the s3 connector, maybe my submission caused a conflict

**Comment by EricJoy2048** [comment]
> > > 我注意到这块代码其实是没问题的，通过执行buildwith方法会赋值shema为s3a，但是关键在于整个sink往下游传递给mutiltable sink时，会执行反序列化操作
> > > > > `Sometimes hadoopConf's getSchema method returns s3n instead of s3a, resulting in the s3 connector actually being cached` Is this reproducible?#00000;是可复制的？
> > > > 
> > > > 
> > > > Can you try use remote debug?你能尝试使用远程调试吗？
> > > 
> > > 
> > > Yes, I discovered through remote debugging that s3n was actually being passed <img alt="image" width="54.140625" height="21" src="https://private-user-images.githubusercontent.com/95527066/322695614-f0edc7a4-25a3-42d6-86ed-c06332b8fd86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMzk5MjMsIm5iZiI6MTcxMzIzOTYyMywicGF0aCI6Ii85NTUyNzA2Ni8zMjI2OTU2MTQtZjBlZGM3YTQtMjVhMy00MmQ2LTg2ZWQtYzA2MzMyYjhmZDg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDAzNTM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwMWE1MWI3YTVkMmE0ZTQxNGY5ODIyY2I3ZmE3MTkzMTk0OTQ3ZDIyODAxODIyMzlkZGJkYWNhYzlmZDU4NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TtE9gCN9ND-N2d65OutPW5v1iLjo8arHHa4dOCZ9nvI">是的，我通过远程调试发现s3n实际上正在传递 <img alt="image" width="54.140625" height="21" src="https://private-user-images.githubusercontent.com/95527066/322695614-f0edc7a4-25a3-42d6-86ed-c06332b8fd86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMzk5MjMsIm5iZiI6MTcxMzIzOTYyMywicGF0aCI6Ii85NTUyNzA2Ni8zMjI2OTU2MTQtZjBlZGM3YTQtMjVhMy00MmQ2LTg2ZWQtYzA2MzMyYjhmZDg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDAzNTM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwMWE1MWI3YTVkMmE0ZTQxNGY5ODIyY2I3ZmE3MTkzMTk0OTQ3ZDIyODAxODIyMzlkZGJkYWNhYzlmZDU4NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TtE9gCN9ND-N2d65OutPW5v1iLjo8arHHa4dOCZ9nvI">
> > 
> > 
> > I understand now. It's really a matter of serialization and deserialization of `static variables`. I don't think we should define `static variables` for classes that need to be serialized and deserialized. Can you put up a pr to fix this?我现在明白了这实际上是 `static variables` 的序列化和重复化的问题。我不认为我们应该为需要序列化和非序列化的类定义 `static variables` 。你能做个公关来解决这个问题吗？
> 
> Ok, I am willing to submit the PR, I have modified the first version to try to remove the [static] changes, but I see that you submitted a change to the s3 connector, maybe my submission caused a conflict

Don't worry, I will resolve the conflict after your pr merge.

**Comment by EricJoy2048** [comment]
Related PR: https://github.com/apache/seatunnel/pull/6698

**Comment by EricJoy2048** [comment]
You can add `close #6678` to the description of pr in pr to ensure that the issue is automatically closed when pr merges

**Comment by LeonYoah** [comment]
> You can add `close #6678` to the description of pr in pr to ensure that the issue is automatically closed when pr merges
Ok
