### ISSUE TITLE
创建postgresql数据源测试连接失败,报错No suitable driver found     

### ISSUE THREAD

**Issue by feiyuthomas** [apache/seatunnel#6778]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

创建postgresql数据源测试连接失败,报错No suitable driver found     

### SeaTunnel Version

创建postgresql数据源测试连接失败,报错No suitable driver found     

### SeaTunnel Config

```conf
创建postgresql数据源测试连接失败,报错No suitable driver found
```

### Running Command

```shell
创建postgresql数据源测试连接失败,报错No suitable driver found
```

### Error Exception

```log
Caused by: java.sql.SQLException: No suitable driver found for jdbc:postgresql://152.168.162.9:15432/testmsg
        at java.sql.DriverManager.getConnection(DriverManager.java:689)
        at java.sql.DriverManager.getConnection(DriverManager.java:247)
        at org.apache.seatunnel.datasource.plugin.postgresql.jdbc.PostgresqlDataSourceChannel.getConnection(PostgresqlDataSourceChannel.java:224)
        at org.apache.seatunnel.datasource.plugin.postgresql.jdbc.PostgresqlDataSourceChannel.getConnection(PostgresqlDataSourceChannel.java:211)
        at org.apache.seatunnel.datasource.plugin.postgresql.jdbc.PostgresqlDataSourceChannel.checkDataSourceConnectivity(PostgresqlDataSourceChannel.java:143)
        ... 65 common frames omitted
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by feiyuthomas** [comment]
测试后需要添加postgresql驱动包      apache-seatunnel-web-1.0.0-bin/libs
