### ISSUE TITLE
[Bug] [mysql to hive 2.3.5] Exception in thread "main" java.lang.NoSuchMethodError: org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(Lorg/apache/hadoop/hive/conf/HiveConf;)V

### ISSUE THREAD

**Issue by zhaoruosong** [apache/seatunnel#6846]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I updated version 2.3.5 of seatunnel. In this version of sink-hive doc, the description supports version 3.1.3 of hive. But after the experiment according to the description, the error was reported all the time.
`Exception in thread "main" java.lang.NoSuchMethodError: org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(Lorg/apache/hadoop/hive/conf/HiveConf;)V
        at org.apache.seatunnel.connectors.seatunnel.hive.utils.HiveMetaStoreProxy.<init>(HiveMetaStoreProxy.java:84)
        at org.apache.seatunnel.connectors.seatunnel.hive.utils.HiveMetaStoreProxy.getInstance(HiveMetaStoreProxy.java:113)
        at org.apache.seatunnel.connectors.seatunnel.hive.config.HiveConfig.getTableInfo(HiveConfig.java:73)
        at org.apache.seatunnel.connectors.seatunnel.hive.sink.HiveSink.prepare(HiveSink.java:122)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSink(JobConfigParser.java:165)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSinks(JobConfigParser.java:135)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSink(MultipleTableJobConfigParser.java:517)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:200)
        at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.getLogicalDag(ClientJobExecutionEnvironment.java:88)
        at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.execute(ClientJobExecutionEnvironment.java:156)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:149)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)`

### SeaTunnel Version

2.3.5

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
  job.mode = "BATCH"
}
source{
    Jdbc {
        url = "jdbc:mysql://192.168.**.***:3306/test"
        driver = "com.mysql.cj.jdbc.Driver"
        connection_check_timeout_sec = 10000
        user = "****"
        password = "****"
        query = "select id,name from test_seatunnel"
    }
}
sink {
  Hive {
      table_name = "test.test_seatunnel"
      metastore_uri = "thrift://name192.168.***.**:9083"
  }

}
```

### Running Command

```shell
seatunnel.sh --config /data/apache-seatunnel-2.3.5/job/test_seatunnel -m local
```

### Error Exception

```log
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(Lorg/apache/hadoop/hive/conf/HiveConf;)V
        at org.apache.seatunnel.connectors.seatunnel.hive.utils.HiveMetaStoreProxy.<init>(HiveMetaStoreProxy.java:84)
        at org.apache.seatunnel.connectors.seatunnel.hive.utils.HiveMetaStoreProxy.getInstance(HiveMetaStoreProxy.java:113)
        at org.apache.seatunnel.connectors.seatunnel.hive.config.HiveConfig.getTableInfo(HiveConfig.java:73)
        at org.apache.seatunnel.connectors.seatunnel.hive.sink.HiveSink.prepare(HiveSink.java:122)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSink(JobConfigParser.java:165)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSinks(JobConfigParser.java:135)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSink(MultipleTableJobConfigParser.java:517)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:200)
        at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.getLogicalDag(ClientJobExecutionEnvironment.java:88)
        at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.execute(ClientJobExecutionEnvironment.java:156)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:149)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
```

### Zeta or Flink or Spark Version

zeta

### Java or Scala Version

java1.8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
You need put seatunnel-hadoop3-3.1.4-uber.jar and hive-exec-3.1.3.jar and libfb303-0.9.3.jar in $SEATUNNEL_HOME/lib/ dir. Please check those jar are exist.

**Comment by NoPr** [comment]
Modify the pom file for connection live. Modify the hive. exec. version version to 3.1.3, recompile and replace the jar package under connections

**Comment by zhaoruosong** [comment]
> You need put seatunnel-hadoop3-3.1.4-uber.jar and hive-exec-3.1.3.jar and libfb303-0.9.3.jar in $SEATUNNEL_HOME/lib/ dir. Please check those jar are exist.

There are all these.
![1715665617451](https://github.com/apache/seatunnel/assets/167179759/dedc9d1c-27d3-4644-ae0a-e9021609f48b)
![1715665628009](https://github.com/apache/seatunnel/assets/167179759/2386e75e-1b65-4cd4-8cc2-6af9a33207ba)

**Comment by zhaoruosong** [comment]
> Modify the pom file for connection live. Modify the hive. exec. version version to 3.1.3, recompile and replace the jar package under connections修改pom文件以进行实时连接。改造母舰。执行版本版本到3.1.3，重新编译并替换连接下的jar包

I'm sorry. I don't quite understand what you mean. Do you want to change the jar package version of hive.exec to 3.1.3? My hive.exec in lib is 3.1.3 now.

**Comment by NoPr** [comment]
![image](https://github.com/apache/seatunnel/assets/73467479/1e8df6d8-b3d9-48f9-9a4e-5a95980d9a03)

**Comment by NoPr** [comment]
> > 修改 pom 文件以进行实时连接。修改蜂巢。执行。 version版本到3.1.3，重新编译并替换connections下的jar包修改pom文件以进行实时连接。改造母舰。执行版本版本到3.1.3，重新编译并替换连接下的jar包
> 
> 对不起。我不太明白你的意思。是否要将hive.exec的jar包版本更改为3.1.3？我的 lib 中的 hive.exec 现在是 3.1.3。

![image](https://github.com/apache/seatunnel/assets/73467479/34dc5aca-76bf-4436-b96a-063bb5f47663)
修改源码connection-hive

**Comment by zhaoruosong** [comment]
> ![image](https://private-user-images.githubusercontent.com/73467479/330297841-34dc5aca-76bf-4436-b96a-063bb5f47663.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NTMxNTAsIm5iZiI6MTcxNTc1Mjg1MCwicGF0aCI6Ii83MzQ2NzQ3OS8zMzAyOTc4NDEtMzRkYzVhY2EtNzZiZi00NDM2LWI5NmEtMDYzYmI1ZjQ3NjYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDA2MDA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1ZDlkYTM3ODNmMzcyNDQ0NTJmNGY2ZWE0ODRiMWExZDAyYWQ0MTMxYzEwNzVjYTIyOGQwZDZlZTkwZDE3MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E42g1LPMThUcxbEx0T-b7pBLbjstYihcvcY9t2dxpYo) 修改源码connection-hive

@NoPr Thank you. After modifying the source code and recompiling, the problem is solved.

**Comment by Toroidals** [comment]
> > ![image](https://private-user-images.githubusercontent.com/73467479/330297841-34dc5aca-76bf-4436-b96a-063bb5f47663.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NTMxNTAsIm5iZiI6MTcxNTc1Mjg1MCwicGF0aCI6Ii83MzQ2NzQ3OS8zMzAyOTc4NDEtMzRkYzVhY2EtNzZiZi00NDM2LWI5NmEtMDYzYmI1ZjQ3NjYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDA2MDA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1ZDlkYTM3ODNmMzcyNDQ0NTJmNGY2ZWE0ODRiMWExZDAyYWQ0MTMxYzEwNzVjYTIyOGQwZDZlZTkwZDE3MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E42g1LPMThUcxbEx0T-b7pBLbjstYihcvcY9t2dxpYo) 修改源码connection-hive
> 
> @NoPr Thank you. After modifying the source code and recompiling, the problem is solved.
I also repackaged and changed to version 3.1.3, but the issue still hasn't been resolved. Could you please specify what exactly was changed?
SeaTunnel Version 2.3.8
Hive: 3.1.3
Spark: 3.3.0
