### ISSUE TITLE
[Bug] [serializer-protobuf] exception with compiling seatunnel

### ISSUE THREAD

**Issue by dbmove** [apache/seatunnel#6849]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

env:
jdk 11
maven 3.8.6
windows 11 professional

when build seatunnel master version from source, meeting next compile error:
[INFO] SeaTunnel : Engine : Serializer : Protobuf ......... FAILURE [  2.777 s]

### SeaTunnel Version

seatunnel master (2024.05.14)

### SeaTunnel Config

```conf
default config
```

### Running Command

```shell
mvnw install -Dmaven.test.skip
mvnw spotless:apply
mvn clean package -pl seatunnel-dist -am -Dmaven.test.skip=true
```

### Error Exception

```log
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project serializer-protobuf: Compilation failure -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project serializer-protobuf: Compilation failure
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:375)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
```

### Zeta or Flink or Spark Version

zeta

### Java or Scala Version

jdk 11

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by NoPr** [comment]
mvn clean install "-DskipTests" "-Dmaven.wagon.http.ssl.insecure=true" "-Dmaven.wagon.http.ssl.allowall=true -U" try again

**Comment by dbmove** [comment]
Tks! This methods works

**Comment by dbmove** [comment]
new build problem：
[INFO] SeaTunnel : Core : Flink Starter : 1.5 ............. FAILURE [  6.120 s]

All method cannot skip Tests(-Dmaven.test.skip=true， or -DskipTests).
When build and excecute model  "seatunnel-flink-15-starter" Tests， meeting exception.

Exception：
2024-05-14 15:31:19,714 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Exception StackTrace:java.lang.RuntimeException: Unsupported classloader: jdk.internal.loader.ClassLoaders$AppClassLoader
	at org.apache.seatunnel.core.starter.flink.execution.FlinkAbstractPluginExecuteProcessor.lambda$static$0(FlinkAbstractPluginExecuteProcessor.java:58)
	at org.apache.seatunnel.core.starter.flink.execution.FlinkExecution.lambda$registerPlugin$1(FlinkExecution.java:172)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.apache.seatunnel.core.starter.flink.execution.FlinkExecution.registerPlugin(FlinkExecution.java:170)
	at org.apache.seatunnel.core.starter.flink.execution.FlinkExecution.<init>(FlinkExecution.java:85)
	at org.apache.seatunnel.core.starter.flink.command.FlinkTaskExecuteCommand.execute(FlinkTaskExecuteCommand.java:59)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)

Test set: org.apache.seatunnel.core.starter.flink.FlinkCommandArgsTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.014 s <<< FAILURE! - in org.apache.seatunnel.core.starter.flink.FlinkCommandArgsTest
testExecuteClientCommandArgsWithoutPluginName  Time elapsed: 0.006 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected exception type thrown, expected: <org.apache.seatunnel.shade.com.typesafe.config.ConfigException> but was: <java.lang.RuntimeException>
	at org.apache.seatunnel.core.starter.flink.FlinkCommandArgsTest.testExecuteClientCommandArgsWithoutPluginName(FlinkCommandArgsTest.java:51)
Caused by: java.lang.RuntimeException: Unsupported classloader: jdk.internal.loader.ClassLoaders$AppClassLoader
	at org.apache.seatunnel.core.starter.flink.FlinkCommandArgsTest.lambda$testExecuteClientCommandArgsWithoutPluginName$1(FlinkCommandArgsTest.java:53)
	at org.apache.seatunnel.core.starter.flink.FlinkCommandArgsTest.testExecuteClientCommandArgsWithoutPluginName(FlinkCommandArgsTest.java:51)

testExecuteClientCommandArgsWithPluginName  Time elapsed: 0.007 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected exception thrown: java.lang.RuntimeException: Unsupported classloader: jdk.internal.loader.ClassLoaders$AppClassLoader
	at org.apache.seatunnel.core.starter.flink.FlinkCommandArgsTest.testExecuteClientCommandArgsWithPluginName(FlinkCommandArgsTest.java:41)
Caused by: java.lang.RuntimeException: Unsupported classloader: jdk.internal.loader.ClassLoaders$AppClassLoader
	at org.apache.seatunnel.core.starter.flink.FlinkCommandArgsTest.lambda$testExecuteClientCommandArgsWithPluginName$0(FlinkCommandArgsTest.java:41)
	at org.apache.seatunnel.core.starter.flink.FlinkCommandArgsTest.testExecuteClientCommandArgsWithPluginName(FlinkCommandArgsTest.java:41)

**Comment by dbmove** [comment]
Because no way to skip TESTs, I deleted  directory "seatunnel-core\seatunnel-flink-starter\seatunnel-flink-15-starter\src\test "and lastly the build passed.
