### ISSUE TITLE
ErrorCode:[API-06], ErrorDescription:[Factory initialize failed] - Unable to create a sink for identifier 'StarRocks'

### ISSUE THREAD

**Issue by asdj07** [apache/seatunnel#6862]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

mysql-cdc  sink to starrocks，work  error

### SeaTunnel Version

2.3.5

### SeaTunnel Config

```conf
env {
  parallelism = 1
  job.mode = "STREAMING"
  checkpoint.interval = 10000
}

source {
  MySQL-CDC {
    base-url = "jdbc:mysql://112.108.1.60:3306/test"
    username = "xx"
    password = "xx"
    table-names = ["test.test"]
    startup.mode = "initial"
  }
}


sink {
  StarRocks {
    nodeUrls = ["192.168.66.243:8030"]
    username = xx
    password = "xx"
    database = "test"
    table = "test1"
    #enable_upsert_delete = true
  }
}
```

### Running Command

```shell
../bin/seatunnel.sh --config ./source_mysql_cdc_sr.conf -e local
```

### Error Exception

```log
Caused by: org.apache.seatunnel.api.table.factory.FactoryException: ErrorCode:[API-06], ErrorDescription:[Factory initialize failed] - Unable to create a sink for identifier 'StarRocks'.
        at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSink(FactoryUtil.java:130)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.createSinkAction(MultipleTableJobConfigParser.java:622)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSink(MultipleTableJobConfigParser.java:553)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:200)
        at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.getLogicalDag(ClientJobExecutionEnvironment.java:88)
        at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.execute(ClientJobExecutionEnvironment.java:156)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:149)
        ... 2 more
Caused by: org.apache.seatunnel.api.configuration.util.OptionValidationException: ErrorCode:[API-02], ErrorDescription:[Option item validate failed] - There are unconfigured options, the options('base-url') are required.
        at org.apache.seatunnel.api.configuration.util.ConfigValidator.validate(ConfigValidator.java:134)
        at org.apache.seatunnel.api.configuration.util.ConfigValidator.validate(ConfigValidator.java:95)
        at org.apache.seatunnel.api.configuration.util.ConfigValidator.validate(ConfigValidator.java:47)
        at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSink(FactoryUtil.java:126)
        ... 8 more
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
ErrorDescription:[Option item validate failed] - There are unconfigured options, the options('base-url') are required.
