### ISSUE TITLE
[Bug] [Mongo] The column type is <STRING>, but a null value is being written into it

### ISSUE THREAD

**Issue by Light-Towers** [apache/seatunnel#6884]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

The column ’exhibit_desc ‘  type is string in hive,  exist Null , sink mongo error

### SeaTunnel Version

2.3.5

### SeaTunnel Config

```conf
env {
  execution.parallelism = 2
  job.mode = "BATCH"
}

source {
  Hive {
    table_name = "dw.app_test"
    metastore_uri = "thrift://master02:9083"
    hdfs_site_path = "/etc/hadoop/conf/hdfs-site.xml"
    read_partitions = ["dt=2024-05-21"]
    read_columns = ["journal_name","exhibit_desc"]
  }
}

sink {
  MongoDB{
    uri = "mongodb://root:root@master01:27017/admin?connectTimeoutMS=10000&authSource=admin"
    database = "test"
    collection = "app_exhibition"
    schema = {
      fields {
        _id = string
        journal_name = STRING
        exhibit_desc = STRING
      }
    }
  }
}
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/sync_conf/hive2mongo -e local
```

### Error Exception

```log
2024-05-22 18:01:30,065 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:202)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: java.lang.RuntimeException: org.apache.seatunnel.connectors.seatunnel.mongodb.exception.MongodbConnectorException: ErrorCode:[COMMON-07], ErrorDescription:[Unsupported data type] - The column type is <STRING>, but a null value is being written into it
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:262)
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:68)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:39)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:27)
	at org.apache.seatunnel.engine.server.task.group.queue.IntermediateBlockingQueue.handleRecord(IntermediateBlockingQueue.java:75)
	at org.apache.seatunnel.engine.server.task.group.queue.IntermediateBlockingQueue.collect(IntermediateBlockingQueue.java:50)
	at org.apache.seatunnel.engine.server.task.flow.IntermediateQueueFlowLifeCycle.collect(IntermediateQueueFlowLifeCycle.java:51)
	at org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask.collect(TransformSeaTunnelTask.java:73)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTask.stateProcess(SeaTunnelTask.java:168)
	at org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask.call(TransformSeaTunnelTask.java:78)
	at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:703)
	at org.apache.seatunnel.engine.server.TaskExecutionService$NamedTaskWrapper.run(TaskExecutionService.java:1004)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.seatunnel.connectors.seatunnel.mongodb.exception.MongodbConnectorException: ErrorCode:[COMMON-07], ErrorDescription:[Unsupported data type] - The column type is <STRING>, but a null value is being written into it
	at org.apache.seatunnel.connectors.seatunnel.mongodb.serde.RowDataToBsonConverters$2.apply(RowDataToBsonConverters.java:95)
	at org.apache.seatunnel.connectors.seatunnel.mongodb.serde.RowDataToBsonConverters$2.apply(RowDataToBsonConverters.java:89)
	at org.apache.seatunnel.connectors.seatunnel.mongodb.serde.RowDataToBsonConverters$15.apply(RowDataToBsonConverters.java:326)
	at org.apache.seatunnel.connectors.seatunnel.mongodb.serde.RowDataToBsonConverters$15.apply(RowDataToBsonConverters.java:318)
	at org.apache.seatunnel.connectors.seatunnel.mongodb.serde.RowDataToBsonConverters$2.apply(RowDataToBsonConverters.java:101)
	at org.apache.seatunnel.connectors.seatunnel.mongodb.serde.RowDataToBsonConverters$2.apply(RowDataToBsonConverters.java:89)
	at org.apache.seatunnel.connectors.seatunnel.mongodb.serde.RowDataToBsonConverters$1.convert(RowDataToBsonConverters.java:77)
	at org.apache.seatunnel.connectors.seatunnel.mongodb.serde.RowDataDocumentSerializer.lambda$createWriteModelSuppliers$2(RowDataDocumentSerializer.java:94)
	at org.apache.seatunnel.connectors.seatunnel.mongodb.serde.RowDataDocumentSerializer.serializeToWriteModel(RowDataDocumentSerializer.java:68)
	at org.apache.seatunnel.connectors.seatunnel.mongodb.serde.RowDataDocumentSerializer.serializeToWriteModel(RowDataDocumentSerializer.java:43)
	at org.apache.seatunnel.connectors.seatunnel.mongodb.sink.MongodbWriter.write(MongodbWriter.java:100)
	at org.apache.seatunnel.connectors.seatunnel.mongodb.sink.MongodbWriter.write(MongodbWriter.java:49)
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:252)
	... 16 more

	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:194)
	... 2 more
 
2024-05-22 18:01:30,066 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - 
===============================================================================



Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:202)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: java.lang.RuntimeException: org.apache.seatunnel.connectors.seatunnel.mongodb.exception.MongodbConnectorException: ErrorCode:[COMMON-07], ErrorDescription:[Unsupported data type] - The column type is <STRING>, but a null value is being written into it
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:262)
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:68)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:39)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:27)
	at org.apache.seatunnel.engine.server.task.group.queue.IntermediateBlockingQueue.handleRecord(IntermediateBlockingQueue.java:75)
	at org.apache.seatunnel.engine.server.task.group.queue.IntermediateBlockingQueue.collect(IntermediateBlockingQueue.java:50)
	at org.apache.seatunnel.engine.server.task.flow.IntermediateQueueFlowLifeCycle.collect(IntermediateQueueFlowLifeCycle.java:51)
	at org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask.collect(TransformSeaTunnelTask.java:73)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTask.stateProcess(SeaTunnelTask.java:168)
	at org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask.call(TransformSeaTunnelTask.java:78)
	at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:703)
	at org.apache.seatunnel.engine.server.TaskExecutionService$NamedTaskWrapper.run(TaskExecutionService.java:1004)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.seatunnel.connectors.seatunnel.mongodb.exception.MongodbConnectorException: ErrorCode:[COMMON-07], ErrorDescription:[Unsupported data type] - The column type is <STRING>, but a null value is being written into it
	at org.apache.seatunnel.connectors.seatunnel.mongodb.serde.RowDataToBsonConverters$2.apply(RowDataToBsonConverters.java:95)
	at org.apache.seatunnel.connectors.seatunnel.mongodb.serde.RowDataToBsonConverters$2.apply(RowDataToBsonConverters.java:89)
	at org.apache.seatunnel.connectors.seatunnel.mongodb.serde.RowDataToBsonConverters$15.apply(RowDataToBsonConverters.java:326)
	at org.apache.seatunnel.connectors.seatunnel.mongodb.serde.RowDataToBsonConverters$15.apply(RowDataToBsonConverters.java:318)
	at org.apache.seatunnel.connectors.seatunnel.mongodb.serde.RowDataToBsonConverters$2.apply(RowDataToBsonConverters.java:101)
	at org.apache.seatunnel.connectors.seatunnel.mongodb.serde.RowDataToBsonConverters$2.apply(RowDataToBsonConverters.java:89)
	at org.apache.seatunnel.connectors.seatunnel.mongodb.serde.RowDataToBsonConverters$1.convert(RowDataToBsonConverters.java:77)
	at org.apache.seatunnel.connectors.seatunnel.mongodb.serde.RowDataDocumentSerializer.lambda$createWriteModelSuppliers$2(RowDataDocumentSerializer.java:94)
	at org.apache.seatunnel.connectors.seatunnel.mongodb.serde.RowDataDocumentSerializer.serializeToWriteModel(RowDataDocumentSerializer.java:68)
	at org.apache.seatunnel.connectors.seatunnel.mongodb.serde.RowDataDocumentSerializer.serializeToWriteModel(RowDataDocumentSerializer.java:43)
	at org.apache.seatunnel.connectors.seatunnel.mongodb.sink.MongodbWriter.write(MongodbWriter.java:100)
	at org.apache.seatunnel.connectors.seatunnel.mongodb.sink.MongodbWriter.write(MongodbWriter.java:49)
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:252)
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Light-Towers** [comment]
Why closed?  It is very common for mongo data to be empty and fields to not exist。Is this question has been abandoned ?

**Comment by WilliaJing** [comment]
hello,I also encountered this problem. When the mongodb field data is null, do you have a solution? @Light-Towers

**Comment by Light-Towers** [comment]
> hello,I also encountered this problem. When the mongodb field data is null, do you have a solution? @Light-Towers

I used datax to sync mongo data.  Maybe you can try the latest version of seatunnel . #6967

**Comment by WilliaJing** [comment]
yes,I have also found it. The official new version has been fixed. Thank you for your reply😄 @Light-Towers
