### ISSUE TITLE
[Bug] [Seatunnel Transform] FieldMapper是否支持对象.属性的映射关系

### ISSUE THREAD

**Issue by oldwolf1984** [apache/seatunnel#6888]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

![微信图片_20240523104338](https://github.com/apache/seatunnel/assets/170589378/57e26a8f-73a8-4590-929b-2e54cd14dc95)
Seatunnel 脚本 Source中有个data类型的对象，其中有个属性A，在transform fieldMapper中是否可以映射到目标表中的一个字段B中，还是说目前seatunnel中暂时不支持这种对象.属性的映射关系，还是说我的写法有问题。求助大神解答

### SeaTunnel Version

2.3.5

### SeaTunnel Config

```conf
无
```

### Running Command

```shell
运行脚本
```

### Error Exception

```log
ErrorDescription:[The input fields 'data.MATNR' of 'FieldMapper' transform not found in upstream schema]
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
you can use sql transform and inner query feature.
the query like `select id, data.MANTER as new_col  ...`

**Comment by oldwolf1984** [comment]
我的源库和目标库都是MongoDB，也可以使用sql么？

**Comment by oldwolf1984** [comment]
使用sql 确实可以解决了，但是又有了一个新的问题
![QQ截图20240523141109](https://github.com/apache/seatunnel/assets/170589378/d9398768-3997-4f6e-bba5-1e54b119ca93)
![QQ截图20240523141254](https://github.com/apache/seatunnel/assets/170589378/5af51dd0-cc89-4f33-9834-5675749925e7)

**Comment by liunaijie** [comment]
> 使用sql 确实可以解决了，但是又有了一个新的问题 ![QQ截图20240523141109](https://private-user-images.githubusercontent.com/170589378/333060107-d9398768-3997-4f6e-bba5-1e54b119ca93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NDc5MzAsIm5iZiI6MTcxNjQ0NzYzMCwicGF0aCI6Ii8xNzA1ODkzNzgvMzMzMDYwMTA3LWQ5Mzk4NzY4LTM5OTctNGY2ZS1iYmE1LTFlNTRiMTE5Y2E5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QwNzAwMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00N2FhNWM2Y2E2ZDRmOWZmNjkxNDZiMjlkYWEyYTU1YzQ2YTcxNThmYWJiZGIwNjc2YmQ4ZDRkNWJhMzQ1MGU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Mhvup4Zw6pmyTYDlnnenj63_nTUDzTqwPwzVYO7T8uM) ![QQ截图20240523141254](https://private-user-images.githubusercontent.com/170589378/333060139-5af51dd0-cc89-4f33-9834-5675749925e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NDc5MzAsIm5iZiI6MTcxNjQ0NzYzMCwicGF0aCI6Ii8xNzA1ODkzNzgvMzMzMDYwMTM5LTVhZjUxZGQwLWNjODktNGYzMy05ODM0LTU2NzU3NDk5MjVlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QwNzAwMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MWRkNTI2NzA5NjcwODk0MTU4MDg5ZTQ1ZWRjYmIxMDIxMTg1OTUxYTJlYzhkNmVlM2EyZmVjZWZlY2NmNWY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KBvvJruoGL4soOtW5JyB-xopd7cSgLaCwBvTka0i_jY)


when you use sql tranfrom.
the `field_mapper` will ignore. the transform result will same with you query result.

You can change to console sink to verify the result struct.



And you can use multiple tranfroms to generate the result you wanted,
like 
```
transform {
  sql {
       query = ""
       result_table_name = "sql_res1"
   }

   sql {
      query = ""
       source_table_name = "sql_res1"
   }

}


```

**Comment by oldwolf1984** [comment]
你好 我按照上面发的写了两个sql标签，执行的时候后台有报错了
024-05-23 15:35:06,093 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:202)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.engine.common.exception.JobDefineCheckException: The source/transform(MongoDB) is not configured with 'result_table_name' option
	at org.apache.seatunnel.engine.core.parse.ConfigParserUtil.checkExistTableId(ConfigParserUtil.java:237)
	at org.apache.seatunnel.engine.core.parse.ConfigParserUtil.checkComplexGraph(ConfigParserUtil.java:155)
	at org.apache.seatunnel.engine.core.parse.ConfigParserUtil.checkGraph(ConfigParserUtil.java:75)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:179)
	at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.getLogicalDag(ClientJobExecutionEnvironment.java:88)
	at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.execute(ClientJobExecutionEnvironment.java:156)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:149)
	... 2 more
Caused by: org.apache.seatunnel.api.configuration.util.OptionValidationException: ErrorCode:[API-02], ErrorDescription:[Option item validate failed] - The option("result_table_name")  is incorrectly configured, please refer to the doc: When result_table_name is not specified, the data processed by this plugin will not be registered as a data set (dataStream/dataset) that can be directly accessed by other plugins, or called a temporary table (table)When result_table_name is specified, the data processed by this plugin will be registered as a data set (dataStream/dataset) that can be directly accessed by other plugins, or called a temporary table (table) . The data set (dataStream/dataset) registered here can be directly accessed by other plugins by specifying source_table_name .
	... 9 more

![QQ截图20240523153840](https://github.com/apache/seatunnel/assets/170589378/0f86b00a-1949-47d2-9056-f6f063ab0970)
![QQ截图20240523151259](https://github.com/apache/seatunnel/assets/170589378/35bb652a-4834-4459-948a-78c2ea01b3dc)

**Comment by oldwolf1984** [comment]
![QQ截图20240523153947](https://github.com/apache/seatunnel/assets/170589378/c56f887f-de1b-4699-a0ea-fa08f12171b3)

**Comment by liunaijie** [comment]
1. the gived config is not complete
it should be ( still ignore som config) :
```
source  {
   xxx {
       result_table_name = "source_result"
       ....
   }
}

transform {
  sql {
       query = ""
       source_table_name = "source_result"
       result_table_name = "sql_res1"    
   }

   sql {
      query = ""
       source_table_name = "sql_res1"
       result_table_name = "sql_res2"  // your exception is this config missing parameters
   }

}

sink {

   xxx {
      source_table_name = "sql_res2"
      ......
   }

}

```


2. in your second query, *you want query from sink table, this is not right. you can only query from the source table.*

data flow is `source -> transform -> sink`

and also not support query with multiple table using like `join`

3.  for your case, your can try (i am not sure it can work, just suggestion)
    a.  `select data.A as data.B from source` 
    b. using json tranform
