### ISSUE TITLE
[Bug] [mysql-cdc] dump mysql history data to console error：java.lang.UnsatisfiedLinkError and java.lang.Exception are in module java.base of loader 'bootstrap'

### ISSUE THREAD

**Issue by dbmove** [apache/seatunnel#6908]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When use mysql-cdc to dump one table data to Console，I met the following Exception：
2024-05-27 09:24:37,777 ERROR org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator - store checkpoint states failed.
java.lang.UnsatisfiedLinkError: org.apache.hadoop.io.nativeio.NativeIO$Windows.access0(Ljava/lang/String;I)Z
        at org.apache.hadoop.io.nativeio.NativeIO$Windows.access0(Native Method) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.5]
        at org.apache.hadoop.io.nativeio.NativeIO$Windows.access(NativeIO.java:788) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.5]
        at org.apache.hadoop.fs.FileUtil.canRead(FileUtil.java:1223) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.5]
        at org.apache.hadoop.fs.FileUtil.list(FileUtil.java:1428) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.5]
        at org.apache.hadoop.fs.RawLocalFileSystem.listStatus(RawLocalFileSystem.java:468) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.5]
.........
2024-05-27 09:24:37,777 ERROR org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator - complete checkpoint failed
java.lang.ClassCastException: class java.lang.UnsatisfiedLinkError cannot be cast to class java.lang.Exception (java.lang.UnsatisfiedLinkError and java.lang.Exception are in module java.base of loader 'bootstrap')
        at org.apache.seatunnel.engine.common.utils.ExceptionUtil.sneakyThrow(ExceptionUtil.java:120) ~[seatunnel-starter.jar:2.3.5]
      

### SeaTunnel Version

seatunnel 2.3.5 zeta cluster

### SeaTunnel Config

```conf
seatunnel.yaml:
seatunnel:
  engine:
    history-job-expire-minutes: 1440
    backup-count: 1
    queue-type: blockingqueue
    print-execution-info-interval: 60
    print-job-metrics-info-interval: 60
    event-report-http:
      url: http://localhost:8080/event/report
      headers:
        Content-Type: application/json
    slot-service:
      dynamic-slot: true
    checkpoint:
      interval: 10000
      timeout: 60000
      storage:
        type: hdfs
        max-retained: 3
        plugin-config:
          namespace: /tmp/seatunnel/checkpoint_snapshot
          storage.type: hdfs
          fs.defaultFS: file:///tmp/ # Ensure that the directory has written permission

job config(mysql_cdc-console.template):
env {
  parallelism = 1
  job.mode = "STREAMING"
  checkpoint.interval = 10000
}

source {
  MySQL-CDC {
    base-url = "jdbc:mysql://localhost:3306/sakila"
    username = "root"
    password = "root"
    table-names = ["sakila.country"]
    
    startup.mode = "initial"
  }
}

sink {
  Console {
  }
}
```

### Running Command

```shell
>bin\seatunnel.cmd --config config\mysql_cdc-console.template
```

### Error Exception

```log
2024-05-27 09:24:37,777 ERROR org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator - store checkpoint states failed.
java.lang.UnsatisfiedLinkError: org.apache.hadoop.io.nativeio.NativeIO$Windows.access0(Ljava/lang/String;I)Z
        at org.apache.hadoop.io.nativeio.NativeIO$Windows.access0(Native Method) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.5]
        at org.apache.hadoop.io.nativeio.NativeIO$Windows.access(NativeIO.java:788) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.5]
        at org.apache.hadoop.fs.FileUtil.canRead(FileUtil.java:1223) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.5]
        at org.apache.hadoop.fs.FileUtil.list(FileUtil.java:1428) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.5]
        at org.apache.hadoop.fs.RawLocalFileSystem.listStatus(RawLocalFileSystem.java:468) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.5]
        at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1868) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.5]
        at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1910) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.5]
        at org.apache.hadoop.fs.ChecksumFileSystem.listStatus(ChecksumFileSystem.java:678) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.5]
        at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1868) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.5]
        at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1910) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.5]
        at org.apache.seatunnel.engine.checkpoint.storage.hdfs.HdfsStorage.getFileNames(HdfsStorage.java:342) ~[seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.engine.checkpoint.storage.hdfs.HdfsStorage.deleteCheckpoint(HdfsStorage.java:308) ~[seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator.completePendingCheckpoint(CheckpointCoordinator.java:790) ~[seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator.lambda$null$7(CheckpointCoordinator.java:533) ~[seatunnel-starter.jar:2.3.5]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2024-05-27 09:24:37,777 ERROR org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator - complete checkpoint failed
java.lang.ClassCastException: class java.lang.UnsatisfiedLinkError cannot be cast to class java.lang.Exception (java.lang.UnsatisfiedLinkError and java.lang.Exception are in module java.base of loader 'bootstrap')
        at org.apache.seatunnel.engine.common.utils.ExceptionUtil.sneakyThrow(ExceptionUtil.java:120) ~[seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator.completePendingCheckpoint(CheckpointCoordinator.java:797) ~[seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator.lambda$null$7(CheckpointCoordinator.java:533) ~[seatunnel-starter.jar:2.3.5]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2024-05-27 09:24:37,777 INFO  org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator - start clean pending checkpoint cause CheckpointCoordinator inside have error.
2024-05-27 09:24:37,778 INFO  org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator - Turn checkpoint_state_847283482131431425_1 state from RUNNING to FAILED
2024-05-27 09:24:37,778 WARN  org.apache.seatunnel.engine.server.dag.physical.SubPlan - Job SeaTunnel_Job (847283482131431425), Pipeline: [(1/1)] checkpoint have error, cancel the pipeline
```

### Zeta or Flink or Spark Version

Zeta 2.3.5

### Java or Scala Version
JDK 11
_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by bugesoft** [comment]
Sorry, I forgot to fill in the jdk version。
My JDK is：
java version "11.0.23" 2024-04-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.23+7-LTS-222)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.23+7-LTS-222, mixed mode)
