### ISSUE TITLE
[Bug] [Sink] java.net.UnknownHostException

### ISSUE THREAD

**Issue by HSLife1991** [apache/seatunnel#6927]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

when i use seatunnel to export hive data to mysql table, it met this error:
org.apache.seatunnel.connectors.seatunnel.file.source.reader.AbstractReadStrategy.getFileNamesByPath(AbstractReadStrategy.java:127)
		at org.apache.seatunnel.connectors.seatunnel.file.hdfs.source.BaseHdfsFileSource.prepare(BaseHdfsFileSource.java:76)
		at org.apache.seatunnel.connectors.seatunnel.hive.source.HiveSource.prepare(HiveSource.java:176)
		at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSource(JobConfigParser.java:85)
		at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:317)
		at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:179)
		at org.apache.seatunnel.engine.core.job.AbstractJobEnvironment.getLogicalDag(AbstractJobEnvironment.java:109)
		at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:73)
		at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:143)
		... 2 more
	Caused by: java.net.UnknownHostException: fmxprod

it's weird that i have not used fmxprod for the parameter "fs.defaultFS" in seatunnel.yaml.

my hdfs core-site.xml config for fs.defaultFS: hdfs://fmxprod.

seatunnel.yaml config is like this:
seatunnel:
  engine:
    history-job-expire-minutes: 1440
    backup-count: 1
    queue-type: blockingqueue
    print-execution-info-interval: 60
    print-job-metrics-info-interval: 60
    slot-service:
      dynamic-slot: true
    checkpoint:
      interval: 10000
      timeout: 60000
      storage:
        type: hdfs
        max-retained: 3
        plugin-config:
          namespace: /tmp/seatunnel/checkpoint_snapshot
          storage.type: hdfs
          fs.defaultFS: hdfs://bc-gcp-sg-node01.c.internal:8020

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
seatunnel:
  engine:
    history-job-expire-minutes: 1440
    backup-count: 1
    queue-type: blockingqueue
    print-execution-info-interval: 60
    print-job-metrics-info-interval: 60
    slot-service:
      dynamic-slot: true
    checkpoint:
      interval: 10000
      timeout: 60000
      storage:
        type: hdfs
        max-retained: 3
        plugin-config:
          namespace: /tmp/seatunnel/checkpoint_snapshot
          storage.type: hdfs
          fs.defaultFS: hdfs://bc-gcp-sg-node01.c.internal:8020
```

### Running Command

```shell
env {
  execution.parallelism = 2
  job.mode = "BATCH"
  checkpoint.interval = 10000
}

source {
  Hive {
    table_name = "prod_test.user_login"
    metastore_uri = "thrift://bc-gcp-sg-node01.c.internal:9083"
  }

}

sink {
  Jdbc {
    url = "jdbc:mysql://x.x.x.x:3306/prod_test"
    driver = "com.mysql.cj.jdbc.Driver"
    connection_check_timeout_sec = 100
    user = ""
    password = ""
    query = "insert into user_login(id, user_name, count, dt) values(?,?,?,?)"
  }
}
```

### Error Exception

```log
java.net.UnknownHostException

2024-05-30 15:14:24,606 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Reason:SeaTunnel job executed failed 
	
	2024-05-30 15:14:24,608 ERROR org.apache.seatunnel.core.starter.SeaTunnel - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
		at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:191)
		at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
		at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
	Caused by: java.lang.IllegalArgumentException: java.net.UnknownHostException: fmxprod
		at org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:445)
		at org.apache.hadoop.hdfs.NameNodeProxiesClient.createProxyWithClientProtocol(NameNodeProxiesClient.java:140)
		at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:356)
		at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:290)
		at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:172)
		at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3303)
		at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:124)
		at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3352)
		at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3320)
		at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:479)
		at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:227)
		at org.apache.seatunnel.connectors.seatunnel.file.source.reader.AbstractReadStrategy.getFileNamesByPath(AbstractReadStrategy.java:127)
		at org.apache.seatunnel.connectors.seatunnel.file.hdfs.source.BaseHdfsFileSource.prepare(BaseHdfsFileSource.java:76)
		at org.apache.seatunnel.connectors.seatunnel.hive.source.HiveSource.prepare(HiveSource.java:176)
		at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSource(JobConfigParser.java:85)
		at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:317)
		at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:179)
		at org.apache.seatunnel.engine.core.job.AbstractJobEnvironment.getLogicalDag(AbstractJobEnvironment.java:109)
		at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:73)
		at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:143)
		... 2 more
	Caused by: java.net.UnknownHostException: fmxprod
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
add `hdfs_site_path` to Hive source

**Comment by HSLife1991** [comment]
it works when add hdfs_site_path.
another issue, does map have hdfs ha configuration in hazelcast.yaml?
my config is like this and it does not work:
hazelcast:
  cluster-name: seatunnel
  network:
    rest-api:
      enabled: true
      endpoint-groups:
        CLUSTER_WRITE:
          enabled: true
        DATA:
          enabled: true
    join:
      tcp-ip:
        enabled: true
        member-list:
          - bc-gcp-sg-node03.c.proj.internal
          - bc-gcp-sg-node04.c.proj.internal
          - bc-gcp-sg-node05.c.proj.internal
    port:
      auto-increment: false
      port: 5801
  properties:
    hazelcast.invocation.max.retry.count: 20
    hazelcast.tcp.join.port.try.count: 30
    hazelcast.logging.type: log4j2
    hazelcast.operation.generic.thread.count: 50
  map:
    engine*:
       map-store:
         enabled: true
         initial-mode: EAGER
         factory-class-name: org.apache.seatunnel.engine.server.persistence.FileMapStoreFactory
         properties:
           type: hdfs
           namespace: /tmp/seatunnel/imap
           clusterName: seatunnel
           storage.type: hdfs
           #fs.defaultFS: hdfs://bc-gcp-sg-node02.c.proj.internal:8020 # it works when use this active namenode
           fs.defaultFS: hdfs://prod # Ensure that the directory has written permission
           seatunnel.hadoop.dfs.nameservices: prod
           seatunnel.hadoop.dfs.ha.namenodes.prod: nn1,nn2
           seatunnel.hadoop.dfs.namenode.rpc-address.prod.nn1: bc-gcp-sg-node01.c.proj.internal:8020
           seatunnel.hadoop.dfs.namenode.rpc-address.prod.nn2: bc-gcp-sg-node02.c.proj.internal:8020
           seatunnel.hadoop.dfs.client.failover.proxy.provider.prod: org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider
           
report error when config with hdfs ha:
StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
		at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:191)
		at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
		at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
	Caused by: java.util.concurrent.CompletionException: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: Can not get coordinator service from an active master node.
		at com.hazelcast.spi.impl.AbstractInvocationFuture.wrapInCompletionException(AbstractInvocationFuture.java:1347)
		at com.hazelcast.spi.impl.AbstractInvocationFuture.cascadeException(AbstractInvocationFuture.java:1340)
		at com.hazelcast.spi.impl.AbstractInvocationFuture.access$200(AbstractInvocationFuture.java:65)

**Comment by liunaijie** [comment]
> it works when add hdfs_site_path. another issue, does map have hdfs ha configuration in hazelcast.yaml? my config is like this and it does not work: hazelcast: cluster-name: seatunnel network: rest-api: enabled: true endpoint-groups: CLUSTER_WRITE: enabled: true DATA: enabled: true join: tcp-ip: enabled: true member-list: - bc-gcp-sg-node03.c.proj.internal - bc-gcp-sg-node04.c.proj.internal - bc-gcp-sg-node05.c.proj.internal port: auto-increment: false port: 5801 properties: hazelcast.invocation.max.retry.count: 20 hazelcast.tcp.join.port.try.count: 30 hazelcast.logging.type: log4j2 hazelcast.operation.generic.thread.count: 50 map: engine*: map-store: enabled: true initial-mode: EAGER factory-class-name: org.apache.seatunnel.engine.server.persistence.FileMapStoreFactory properties: type: hdfs namespace: /tmp/seatunnel/imap clusterName: seatunnel storage.type: hdfs #fs.defaultFS: hdfs://bc-gcp-sg-node02.c.proj.internal:8020 # it works when use this active namenode fs.defaultFS: hdfs://prod # Ensure that the directory has written permission seatunnel.hadoop.dfs.nameservices: prod seatunnel.hadoop.dfs.ha.namenodes.prod: nn1,nn2 seatunnel.hadoop.dfs.namenode.rpc-address.prod.nn1: bc-gcp-sg-node01.c.proj.internal:8020 seatunnel.hadoop.dfs.namenode.rpc-address.prod.nn2: bc-gcp-sg-node02.c.proj.internal:8020 seatunnel.hadoop.dfs.client.failover.proxy.provider.prod: org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider
> 
> report error when config with hdfs ha: StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:191) at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40) at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34) Caused by: java.util.concurrent.CompletionException: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: Can not get coordinator service from an active master node. at com.hazelcast.spi.impl.AbstractInvocationFuture.wrapInCompletionException(AbstractInvocationFuture.java:1347) at com.hazelcast.spi.impl.AbstractInvocationFuture.cascadeException(AbstractInvocationFuture.java:1340) at com.hazelcast.spi.impl.AbstractInvocationFuture.access$200(AbstractInvocationFuture.java:65)


Yes. it supported. 

you error log has `# Ensure that the directory has written permission`. please check this.

**Comment by liunaijie** [comment]
and checkpoint also support config `hdfs_site_path` after 2.3.5. or you can cherry-pick this commit https://github.com/apache/seatunnel/pull/6547
```
seatunnel:
  engine:
    checkpoint:
      storage:
        type: hdfs
        max-retained: 3
        plugin-config:
          storage.type: hdfs
          fs.defaultFS: hdfs://localhost:9000
          // if you used kerberos, you can config like this:
          kerberosPrincipal: your-kerberos-principal
          kerberosKeytabFilePath: your-kerberos-keytab
          // if you need hdfs-site config, you can config like this:
          hdfs_site_path: /path/to/your/hdfs_site_path
```

**Comment by HSLife1991** [comment]
yep, i configured checkpoint ha and it's fine, but it does not work for map.
the permission is fine, it worked when i used single active namenode.

**Comment by liunaijie** [comment]
> yep, i configured checkpoint ha and it's fine, but it does not work for map. the permission is fine, it worked when i used single active namenode.

oh, i mixed them.  you version is 2.3.3. in this version it's not supported ha config on MAP.
it supported after version 2.3.5. or you can apply the update commit to 2.3.3

**Comment by HSLife1991** [comment]
ok, understood.
thx!
