### ISSUE TITLE
[Bug] [mysql cdc] org.apache.seatunnel.connectors.seatunnel.cdc.mysql.source.MySqlDialect.getPrimaryKey< Error NullPointerException>

### ISSUE THREAD

**Issue by wuchang945** [apache/seatunnel#6934]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Caused by: java.lang.NullPointerException
        at org.apache.seatunnel.connectors.seatunnel.cdc.mysql.source.MySqlDialect.getPrimaryKey(MySqlDialect.java:127)
        at org.apache.seatunnel.connectors.cdc.base.source.enumerator.splitter.AbstractJdbcSourceChunkSplitter.getSplitColumn(AbstractJdbcSourceChunkSplitter.java:384)
        at org.apache.seatunnel.connectors.cdc.base.source.enumerator.splitter.AbstractJdbcSourceChunkSplitter.generateSplits(AbstractJdbcSourceChunkSplitter.java:64)

### SeaTunnel Version

2.3.5

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
  job.mode = "STREAMING"
}

source {
  MySQL-CDC {
    base-url = "jdbc:mysql://192.168.204.1:3306/seatunnel-test1?serverTimezone=UTC"
    username = "seatunnel"
    password = "wuchang945"
    table-names = ["seatunnel-test1.helloworld_operlog","seatunnel-test1.oper_log","seatunnel-test1.test"]
table-names-config = [
      {
        table = "seatunnel-test1.helloworld_operlog"
        primaryKeys = ["id"]
      }

        {
        table = "seatunnel-test1.oper_log"
        primaryKeys = ["id"]
      }

{
        table = "seatunnel-test1.test"
        primaryKeys = ["id"]
      }
    ]
}
}

sink {

 Console {
  }
}
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/mysqlconsle.config.template -e local
```

### Error Exception

```log
Caused by: java.lang.NullPointerException
        at org.apache.seatunnel.connectors.seatunnel.cdc.mysql.source.MySqlDialect.getPrimaryKey(MySqlDialect.java:127)
        at org.apache.seatunnel.connectors.cdc.base.source.enumerator.splitter.AbstractJdbcSourceChunkSplitter.getSplitColumn(AbstractJdbcSourceChunkSplitter.java:384)
        at org.apache.seatunnel.connectors.cdc.base.source.enumerator.splitter.AbstractJdbcSourceChunkSplitter.generateSplits(AbstractJdbcSourceChunkSplitter.java:64)
        at org.apache.seatunnel.connectors.cdc.base.source.enumerator.SnapshotSplitAssigner.getNext(SnapshotSplitAssigner.java:185)
        at org.apache.seatunnel.connectors.cdc.base.source.enumerator.HybridSplitAssigner.getNext(HybridSplitAssigner.java:98)
        at org.apache.seatunnel.connectors.cdc.base.source.enumerator.IncrementalSourceEnumerator.assignSplits(IncrementalSourceEnumerator.java:172)
        at org.apache.seatunnel.connectors.cdc.base.source.enumerator.IncrementalSourceEnumerator.handleSplitRequest(IncrementalSourceEnumerator.java:82)
        at org.apache.seatunnel.engine.server.task.SourceSplitEnumeratorTask.requestSplit(SourceSplitEnumeratorTask.java:236)
        at org.apache.seatunnel.engine.server.task.operation.source.RequestSplitOperation.lambda$run$0(RequestSplitOperation.java:62)
        at org.apache.seatunnel.common.utils.RetryUtils.retryWithException(RetryUtils.java:48)
        at org.apache.seatunnel.engine.server.task.operation.source.RequestSplitOperation.run(RequestSplitOperation.java:52)
        at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:273)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:175)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:139)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)

        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:194)
```

### Zeta or Flink or Spark Version

zeta

### Java or Scala Version

jdk 1.8.0_262

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wuchang945** [comment]
Caused by: java.lang.NullPointerException
        at org.apache.seatunnel.connectors.seatunnel.cdc.mysql.source.MySqlDialect.getPrimaryKey(MySqlDialect.java:127) ~[connector-cdc-mysql-2.3.5.jar:2.3.5]
        at org.apache.seatunnel.connectors.cdc.base.source.enumerator.splitter.AbstractJdbcSourceChunkSplitter.getSplitColumn(AbstractJdbcSourceChunkSplitter.java:384) ~[connector-cdc-mysql-2.3.5.jar:2.3.5]
        at org.apache.seatunnel.connectors.cdc.base.source.enumerator.splitter.AbstractJdbcSourceChunkSplitter.generateSplits(AbstractJdbcSourceChunkSplitter.java:64) ~[connector-cdc-mysql-2.3.5.jar:2.3.5]

**Comment by haiwang2517** [comment]
I have the same problem.
![image](https://github.com/apache/seatunnel/assets/20762595/8eb854e0-f2d6-47cf-bed0-d8e2fe7467be)


## SeaTunnel Version
2.3.5

## SeaTunnel Config
``` {
    "env" : { 
        "parallelism" : 1,
        "job.mode" : "STREAMING"
    },
    "source" : [
        {
            "base-url" : "jdbc:mysql://ken-local:3306/ads_test",
            "password" : "root",
            "startup.mode" : "initial",
            "table-names" : [
                "ads_test.user_info"
            ],
            "plugin_name" : "MySQL-CDC",
            "username" : "root"
        }
    ],
    "sink" : [
        {
            "password" : "root",
            "database" : "ads_test",
            "driver" : "com.mysql.cj.jdbc.Driver",
            "data_save_mode" : "APPEND_DATA",
            "schema_save_mode" : "CREATE_SCHEMA_WHEN_NOT_EXIST",
            "generate_sink_sql" : true,
            "plugin_name" : "jdbc",
            "user" : "root",
            "url" : "jdbc:mysql://ken-local:3306/ads_test?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true",
            "table" : "user_info_seatunnel2"
        }
    ]
}
```

## Zeta or Flink or Spark Version
zeta

## Java or Scala Version
jdk: jdk1.8.0_401

**Comment by haiwang2517** [comment]
@wuchang945 Here's how I solved it.
1. Ensure that all connector dependencies are stored in the `lib` directory
2. Remove `mv connectors/ connectors-bak/`  and create an empty connectors `mkdir connectors`
3. Restart the seatunnel

I think this should be caused by problems with dependencies in the connectors directory.

![image](https://github.com/apache/seatunnel/assets/20762595/eabe87da-831c-423f-a812-ca23acefacde)

**Comment by hswlxc** [comment]
I  have the same problem.
Has the problem been solved  @haiwang2517

**Comment by hailin0** [comment]
Stop placing connectors in the `lib` directory, this causes errors, connectors should only be placed in the `connectors` directory

**Comment by yaoquanxin** [comment]
I also meet the problem use seatunnel async data from pg to sr,now I know it。

**Comment by nihaobienao** [comment]
> I also meet the problem use seatunnel async data from pg to sr,now I know it。

How to solve it

**Comment by luocheng819** [comment]
> > I also meet the problem use seatunnel async data from pg to sr,now I know it。
> 
> How to solve it

as hailin0 said, remove connector-*.jar in the lib directory, this solved the problem.
