### ISSUE TITLE
[Bug] [S3AFile Sink] s3aFile as sink，SeaTunnel rename file

### ISSUE THREAD

**Issue by NoPr** [apache/seatunnel#6952]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When using s3aFile as the sink and the actual storage target is Minio, seatunnel encounters an error related to renaming a file.

### SeaTunnel Version

2.3.5

### SeaTunnel Config

```conf
env {
  parallelism = 1
  job.mode = "BATCH"
}

# Create a source to connect to sftp
source {
  SftpFile {
    host = "192.168.4.53"
    port = 22
    user = "root"
    password = "btrc20191018,,"
    path = "/opt/module/seatunnel_1.txt"
    file_format_type = "text"
    result_table_name = "sftp"
        }
}

transform{
}
sink{
  S3File {
    bucket = "s3a://data"
    path = "/seatunnel"
    tmp_path = "/tmp"
    fs.s3a.endpoint="http://192.168.4.52:9002"
    fs.s3a.aws.credentials.provider="org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
    access_key = "admin"
    secret_key = "admin123"
    custom_filename = true
    file_name_expression = "seatunnel_${transactionId}"
    file_format_type = "text"
    schema_save_mode = "CREATE_SCHEMA_WHEN_NOT_EXIST"
    data_save_mode = "APPEND_DATA"
    }
  }
```

### Running Command

```shell
./../../bin/seatunnel.sh --config sftp2minio.conf -e local
```

### Error Exception

```log
2024-06-04 14:31:47,843 ERROR [.c.FileSinkAggregatedCommitter] [hz.main.seaTunnel.task.thread-6] - commit aggregatedCommitInfo error, aggregatedCommitInfo = FileAggregatedCommitInfo(transactionMap={/tmp/seatunnel/850260510937972737/da7a43c067/T_850260510937972737_da7a43c067_0_1={/tmp/seatunnel/850260510937972737/da7a43c067/T_850260510937972737_da7a43c067_0_1/NON_PARTITION/T_850260510937972737_da7a43c067_0_1_0.txt=/seatunnel/T_850260510937972737_da7a43c067_0_1_0.txt}}, partitionDirAndValuesMap={})
org.apache.seatunnel.common.exception.SeaTunnelRuntimeException: ErrorCode:[COMMON-01], ErrorDescription:[SeaTunnel rename file '/tmp/seatunnel/850260510937972737/da7a43c067/T_850260510937972737_da7a43c067_0_1/NON_PARTITION/T_850260510937972737_da7a43c067_0_1_0.txt -> /seatunnel/T_850260510937972737_da7a43c067_0_1_0.txt' failed.]
        at org.apache.seatunnel.common.exception.CommonError.fileOperationFailed(CommonError.java:69) ~[seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.connectors.seatunnel.file.hadoop.HadoopFileSystemProxy.renameFile(HadoopFileSystemProxy.java:110) ~[connector-file-sftp-2.3.5.jar:2.3.5]
        at org.apache.seatunnel.connectors.seatunnel.file.sink.commit.FileSinkAggregatedCommitter.lambda$commit$0(FileSinkAggregatedCommitter.java:53) ~[connector-file-sftp-2.3.5.jar:2.3.5]
        at java.util.Collections$SingletonList.forEach(Collections.java:4824) ~[?:1.8.0_391]
        at org.apache.seatunnel.connectors.seatunnel.file.sink.commit.FileSinkAggregatedCommitter.commit(FileSinkAggregatedCommitter.java:45) ~[connector-file-sftp-2.3.5.jar:2.3.5]
        at org.apache.seatunnel.connectors.seatunnel.file.sink.BaseFileSinkWriter.<init>(BaseFileSinkWriter.java:91) ~[connector-file-sftp-2.3.5.jar:2.3.5]
        at org.apache.seatunnel.connectors.seatunnel.file.sink.BaseMultipleTableFileSink.restoreWriter(BaseMultipleTableFileSink.java:70) ~[connector-file-sftp-2.3.5.jar:2.3.5]
        at org.apache.seatunnel.connectors.seatunnel.common.multitablesink.MultiTableSink.restoreWriter(MultiTableSink.java:100) ~[seatunnel-transforms-v2.jar:2.3.5]
        at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.restoreState(SinkFlowLifeCycle.java:308) ~[seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.engine.server.task.SeaTunnelTask.lambda$restoreState$16(SeaTunnelTask.java:425) ~[seatunnel-starter.jar:2.3.5]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_391]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_391]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_391]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[?:1.8.0_391]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_391]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_391]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_391]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_391]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_391]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_391]
        at org.apache.seatunnel.engine.server.task.SeaTunnelTask.restoreState(SeaTunnelTask.java:422) ~[seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.engine.server.checkpoint.operation.NotifyTaskRestoreOperation.lambda$null$0(NotifyTaskRestoreOperation.java:106) ~[seatunnel-starter.jar:2.3.5]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) [?:1.8.0_391]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_391]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_391]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_391]
```

### Zeta or Flink or Spark Version

2.3.5

### Java or Scala Version

1.8

### Screenshots

![1717643163637](https://github.com/apache/seatunnel/assets/73467479/b96bf928-b03e-45bf-bb6f-7ac87b174d3a)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by NoPr** [comment]
solve：

1. 使用dev版的connection-file替换2.3.5-release的connection-file部分的代码。
2. 修改connection-file的hadoop-aws的版本。
3. 修改seatunnel-connectors-v2/connector-s3-redshift/src/main/java/org/apache/seatunnel/connectors/seatunnel/redshift/sink/S3RedshiftSink.java的内容至dev版本，重新打包就可以解决。

**Comment by NoPr** [comment]
solve：

1. 使用dev版的connection-file替换2.3.5-release的connection-file部分的代码。
2. 修改connection-file的hadoop-aws的版本。
3. 修改seatunnel-connectors-v2/connector-s3-redshift/src/main/java/org/apache/seatunnel/connectors/seatunnel/redshift/sink/S3RedshiftSink.java的内容至dev版本，重新打包就可以解决。
