### ISSUE TITLE
[Bug] [Kingbase] Why 2.3.4 support Kingbase, but  could not find any jdbc dialect factory

### ISSUE THREAD

**Issue by turnglight** [apache/seatunnel#7005]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

support Kingbase?

run : /app/apache-seatunnel-2.3.4-SNAPSHOT/bin/seatunnel.sh  --config /app/application/XXXXX.conf -e local

throw exception:
        24/06/18 10:47:12 ERROR SeaTunnel: Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:191)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.connectors.seatunnel.jdbc.exception.JdbcConnectorException: ErrorCode:[JDBC-06], ErrorDescription:[No suitable dialect factory found] - Could not find any jdbc dialect factory that can handle url 'jdbc:kingbase8://10.233.32.93:54321/kingbase' that implements 'org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.JdbcDialectFactory' in the classpath.

### SeaTunnel Version

2.3.4

### SeaTunnel Config

```conf
env {
  job.mode = "BATCH"
}

source {
    jdbc {
    driver = "com.kingbase8.Driver"
    url = "jdbc:kingbase8://xxxxxx:xxx/kingbase"
    user = "xxx"
    password = "xxxx"
    table = "dm_label"
    query = "SELECT id AS id, parent_id AS parent_id, name AS name, code AS code, root_id AS root_id FROM dm_label "
  }
}

transform {
  sql {
    query = "SELECT id AS id, parent_id AS parent_id, name AS name, code AS code, root_id AS root_id FROM dm_label "
    source_table_name = "dm_label"
    result_table_name = "dm_label_bak"
  }
}

sink {
  jdbc {
    driver = "com.kingbase8.Driver"
    url = "jdbc:kingbase8://xxxx:xxx/kingbase"
    user = "xxxx"
    password = "xxxx"
    table = "dm_label_bak"
    database = "kingbase"
    generate_sink_sql = true
    support_upsert_by_query_primary_key_exist = true
    primary_keys = ["id"]
    data_save_mode = "DROP_DATA"
    saveMode = "overwrite"
    truncate = "true"
  }
}
```

### Running Command

```shell
/app/apache-seatunnel-2.3.4-SNAPSHOT/bin/seatunnel.sh  --config /app/application/XXXXX.conf -e local
```

### Error Exception

```log
2024-06-18 10:47:10,583 INFO  org.apache.seatunnel.engine.server.SeaTunnelServer - master node check interrupted
2024-06-18 10:47:12,633 INFO  com.hazelcast.instance.impl.NodeExtension - [172.18.0.1]:5801 [seatunnel-696116] [5.1] Destroying node NodeExtension.
2024-06-18 10:47:12,634 INFO  com.hazelcast.instance.impl.Node - [172.18.0.1]:5801 [seatunnel-696116] [5.1] Hazelcast Shutdown is completed in 2057 ms.
2024-06-18 10:47:12,634 INFO  com.hazelcast.core.LifecycleService - [172.18.0.1]:5801 [seatunnel-696116] [5.1] [172.18.0.1]:5801 is SHUTDOWN
24/06/18 10:47:12 INFO ClientExecuteCommand: Closed HazelcastInstance ......
24/06/18 10:47:12 ERROR SeaTunnel: 

===============================================================================


24/06/18 10:47:12 ERROR SeaTunnel: Fatal Error, 

24/06/18 10:47:12 ERROR SeaTunnel: Please submit bug report in https://github.com/apache/seatunnel/issues

24/06/18 10:47:12 ERROR SeaTunnel: Reason:SeaTunnel job executed failed 

24/06/18 10:47:12 ERROR SeaTunnel: Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:191)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.connectors.seatunnel.jdbc.exception.JdbcConnectorException: ErrorCode:[JDBC-06], ErrorDescription:[No suitable dialect factory found] - Could not find any jdbc dialect factory that can handle url 'jdbc:kingbase8://10.233.32.93:54321/kingbase' that implements 'org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.JdbcDialectFactory' in the classpath.

Available factories are:

org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.db2.DB2DialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.dm.DmdbDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.gbase8a.Gbase8aDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.greenplum.GreenplumDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.mysql.MySqlDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.oceanbase.OceanBaseDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.oracle.OracleDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.phoenix.PhoenixDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.psql.PostgresDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.redshift.RedshiftDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.saphana.SapHanaDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.snowflake.SnowflakeDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.sqlite.SqliteDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.sqlserver.SqlServerDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.tablestore.TablestoreDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.teradata.TeradataDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.vertica.VerticaDialectFactory
        at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.JdbcDialectLoader.load(JdbcDialectLoader.java:66)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.source.JdbcSource.prepare(JdbcSource.java:104)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSource(JobConfigParser.java:85)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:317)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:179)
        at org.apache.seatunnel.engine.core.job.AbstractJobEnvironment.getLogicalDag(AbstractJobEnvironment.java:109)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:73)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:143)
        ... 2 more
 
24/06/18 10:47:12 ERROR SeaTunnel: 
===============================================================================



Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:191)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.connectors.seatunnel.jdbc.exception.JdbcConnectorException: ErrorCode:[JDBC-06], ErrorDescription:[No suitable dialect factory found] - Could not find any jdbc dialect factory that can handle url 'jdbc:kingbase8://10.233.32.93:54321/kingbase' that implements 'org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.JdbcDialectFactory' in the classpath.

Available factories are:

org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.db2.DB2DialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.dm.DmdbDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.gbase8a.Gbase8aDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.greenplum.GreenplumDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.mysql.MySqlDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.oceanbase.OceanBaseDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.oracle.OracleDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.phoenix.PhoenixDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.psql.PostgresDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.redshift.RedshiftDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.saphana.SapHanaDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.snowflake.SnowflakeDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.sqlite.SqliteDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.sqlserver.SqlServerDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.tablestore.TablestoreDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.teradata.TeradataDialectFactory
org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.vertica.VerticaDialectFactory
        at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.dialect.JdbcDialectLoader.load(JdbcDialectLoader.java:66)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.source.JdbcSource.prepare(JdbcSource.java:104)
        at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSource(JobConfigParser.java:85)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:317)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:179)
        at org.apache.seatunnel.engine.core.job.AbstractJobEnvironment.getLogicalDag(AbstractJobEnvironment.java:109)
        at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:73)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:143)
        ... 2 more
```

### Zeta or Flink or Spark Version

Zeta

### Java or Scala Version

Java

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by turnglight** [comment]
done it to replace the latest connect-jdbc-2.3.4.jar
