### ISSUE TITLE
[Bug] [Module Name] Bug title [Factory initialize failed] - Unable to create a source for identifier 'MySQL-CDC'

### ISSUE THREAD

**Issue by LeoWoon** [apache/seatunnel#7072]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

**i  run a job in seatunnel 2.3.5, which was deployed according to https://seatunnel.apache.org/zh-CN/docs/2.3.5/start-v2/locally/deployment step by step 
then comes the FATAL ERROR：**

2024-06-27 14:20:28,664 INFO  [.s.p.d.AbstractPluginDiscovery] [main] - Load SeaTunnelSink Plugin from /root/apache-seatunnel-2.3.5/connectors
2024-06-27 14:20:28,674 INFO  [.s.p.d.AbstractPluginDiscovery] [main] - Discovery plugin jar for: PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='MySQL-CDC'} at: file:/root/apache-seatunnel-2.3.5/connectors/connector-cdc-mysql-2.3.5.jar
2024-06-27 14:20:28,676 INFO  [.s.p.d.AbstractPluginDiscovery] [main] - Discovery plugin jar for: PluginIdentifier{engineType='seatunnel', pluginType='sink', pluginName='jdbc'} at: file:/root/apache-seatunnel-2.3.5/connectors/connector-jdbc-2.3.5.jar
2024-06-27 14:20:28,686 INFO  [p.MultipleTableJobConfigParser] [main] - start generating all sources.
2024-06-27 14:20:28,755 INFO  [.s.c.s.j.c.AbstractJdbcCatalog] [main] - Catalog MySQL closing
2024-06-27 14:20:28,755 INFO  [c.h.c.LifecycleService        ] [main] - hz.client_1 [seatunnel] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is SHUTTING_DOWN
2024-06-27 14:20:28,760 INFO  [.c.i.c.ClientConnectionManager] [main] - hz.client_1 [seatunnel] [5.1] Removed connection to endpoint: [localhost]:5801:bc2fc57c-f575-4d24-a38a-73eb68d48625, connection: ClientConnection{alive=false, connectionId=1, channel=NioChannel{/127.0.0.1:37745->localhost/127.0.0.1:5801}, remoteAddress=[localhost]:5801, lastReadTime=2024-06-27 14:20:28.428, lastWriteTime=2024-06-27 14:20:28.427, closedTime=2024-06-27 14:20:28.757, connected server version=5.1}
2024-06-27 14:20:28,760 INFO  [c.h.c.LifecycleService        ] [main] - hz.client_1 [seatunnel] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is CLIENT_DISCONNECTED
2024-06-27 14:20:28,764 INFO  [c.h.c.LifecycleService        ] [main] - hz.client_1 [seatunnel] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is SHUTDOWN
2024-06-27 14:20:28,764 INFO  [s.c.s.s.c.ClientExecuteCommand] [main] - Closed SeaTunnel client......
2024-06-27 14:20:28,764 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - 

===============================================================================

2024-06-27 14:20:28,764 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Fatal Error, 

2024-06-27 14:20:28,764 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Please submit bug report in https://github.com/apache/seatunnel/issues

2024-06-27 14:20:28,765 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Reason:SeaTunnel job executed failed 

2024-06-27 14:20:28,767 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:202)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.api.table.factory.FactoryException: ErrorCode:[API-06], ErrorDescription:[Factory initialize failed] - Unable to create a source for identifier 'MySQL-CDC'.
        at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:100)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:332)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:188)
        at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.getLogicalDag(ClientJobExecutionEnvironment.java:88)
        at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.execute(ClientJobExecutionEnvironment.java:156)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:149)
        ... 2 more
Caused by: org.apache.seatunnel.api.table.catalog.exception.CatalogException: ErrorCode:[API-03], ErrorDescription:[Catalog initialize failed] - Failed connecting to jdbc:mysql://192.168.2.128:3306/seatunnel via JDBC.
        at org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.AbstractJdbcCatalog.getConnection(AbstractJdbcCatalog.java:123)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.AbstractJdbcCatalog.open(AbstractJdbcCatalog.java:129)
        at org.apache.seatunnel.api.table.catalog.CatalogTableUtil.lambda$getCatalogTables$0(CatalogTableUtil.java:120)
        at java.util.Optional.map(Optional.java:215)
        at org.apache.seatunnel.api.table.catalog.CatalogTableUtil.getCatalogTables(CatalogTableUtil.java:116)
        at org.apache.seatunnel.api.table.catalog.CatalogTableUtil.getCatalogTables(CatalogTableUtil.java:96)
        at org.apache.seatunnel.connectors.seatunnel.cdc.mysql.source.MySqlIncrementalSourceFactory.lambda$createSource$1(MySqlIncrementalSourceFactory.java:102)
        at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:112)
        at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:73)
        ... 7 more
Caused by: java.sql.SQLException: No suitable driver found for jdbc:mysql://192.168.2.128:3306/seatunnel
        at java.sql.DriverManager.getConnection(DriverManager.java:689)
        at java.sql.DriverManager.getConnection(DriverManager.java:247)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.AbstractJdbcCatalog.getConnection(AbstractJdbcCatalog.java:119)
        ... 15 more
 
2024-06-27 14:20:28,767 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - 

Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:202)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.api.table.factory.FactoryException: ErrorCode:[API-06], ErrorDescription:[Factory initialize failed] - Unable to create a source for identifier 'MySQL-CDC'.
        at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:100)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:332)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:188)
        at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.getLogicalDag(ClientJobExecutionEnvironment.java:88)
        at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.execute(ClientJobExecutionEnvironment.java:156)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:149)
        ... 2 more
Caused by: org.apache.seatunnel.api.table.catalog.exception.CatalogException: ErrorCode:[API-03], ErrorDescription:[Catalog initialize failed] - Failed connecting to jdbc:mysql://192.168.2.128:3306/seatunnel via JDBC.
        at org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.AbstractJdbcCatalog.getConnection(AbstractJdbcCatalog.java:123)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.AbstractJdbcCatalog.open(AbstractJdbcCatalog.java:129)
        at org.apache.seatunnel.api.table.catalog.CatalogTableUtil.lambda$getCatalogTables$0(CatalogTableUtil.java:120)
        at java.util.Optional.map(Optional.java:215)
        at org.apache.seatunnel.api.table.catalog.CatalogTableUtil.getCatalogTables(CatalogTableUtil.java:116)
        at org.apache.seatunnel.api.table.catalog.CatalogTableUtil.getCatalogTables(CatalogTableUtil.java:96)
        at org.apache.seatunnel.connectors.seatunnel.cdc.mysql.source.MySqlIncrementalSourceFactory.lambda$createSource$1(MySqlIncrementalSourceFactory.java:102)
        at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:112)
        at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:73)
        ... 7 more
Caused by: java.sql.SQLException: No suitable driver found for jdbc:mysql://192.168.2.128:3306/seatunnel
        at java.sql.DriverManager.getConnection(DriverManager.java:689)
        at java.sql.DriverManager.getConnection(DriverManager.java:247)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.AbstractJdbcCatalog.getConnection(AbstractJdbcCatalog.java:119)
        ... 15 more

**It looks like that i missed some connectors or i did wrong with my configure.
but i've run the install-plugin.sh successfully, and the connectors have been downloaded as following** 

[root@test3 apache-seatunnel-2.3.5]# ll ./connectors/
total 212992
-rw-r--r-- 1 root root 30257530 Jun 27 13:36 connector-cdc-mongodb-2.3.5.jar
-rw-r--r-- 1 root root 30540348 Jun 27 13:44 connector-cdc-mysql-2.3.5.jar
-rw-r--r-- 1 root root 26903195 Jun 27 13:36 connector-cdc-sqlserver-2.3.5.jar
-rw-r--r-- 1 root root 30830325 Jun 27 13:37 connector-clickhouse-2.3.5.jar
-rw-r--r-- 1 root root    77830 Jun 27 13:45 connector-console-2.3.5.jar
-rw-r--r-- 1 root root 11785663 Jun 27 13:37 connector-doris-2.3.5.jar
-rw-r--r-- 1 root root  5529299 Jun 27 13:37 connector-elasticsearch-2.3.5.jar
-rw-r--r-- 1 root root   199577 Jun 27 13:45 connector-fake-2.3.5.jar
-rw-r--r-- 1 root root 42318873 Jun 27 13:38 connector-hive-2.3.5.jar
-rw-r--r-- 1 root root   776369 Jun 27 13:39 connector-jdbc-2.3.5.jar
-rw-r--r-- 1 root root 17276586 Jun 27 13:41 connector-kafka-2.3.5.jar
-rw-r--r-- 1 root root  2480453 Jun 27 13:41 connector-mongodb-2.3.5.jar
-rw-r--r-- 1 root root  5100892 Jun 27 13:41 connector-neo4j-2.3.5.jar
-rw-r--r-- 1 root root   830795 Jun 27 13:41 connector-rabbitmq-2.3.5.jar
-rw-r--r-- 1 root root  1372145 Jun 27 13:41 connector-redis-2.3.5.jar
-rw-r--r-- 1 root root   455706 Jun 27 14:09 datasource-jdbc-mysql-1.0.0.jar
-rw-r--r-- 1 root root   456238 Jun 27 14:09 datasource-jdbc-postgresql-1.0.0.jar
-rw-r--r-- 1 root root   455327 Jun 27 14:09 datasource-mysql-cdc-1.0.0.jar
drwxr-xr-x 2 root root        6 Jun 27 13:47 flink
drwxr-xr-x 2 root root        6 Jun 27 13:47 flink-sql
-rw-r--r-- 1 root root  2476480 Jun 27 14:09 mysql-connector-java-8.0.28.jar
-rw-r--r-- 1 root root  6844991 Jun 27 14:09 ojdbc8-23.2.0.0.jar
-rw-r--r-- 1 root root     5803 Nov  9  2023 plugin-mapping.properties
-rw-r--r-- 1 root root  1082113 Jun 27 14:09 postgresql-42.6.2.jar
drwxr-xr-x 2 root root        6 Jun 27 13:47 seatunnel
drwxr-xr-x 2 root root        6 Jun 27 13:47 spark

**So, is there something wrong with my configure?**

### SeaTunnel Version

2.3.5

### SeaTunnel Config

```conf
env {
  parallelism = 1
  job.mode = "STREAMING"
  checkpoint.interval = 2000
}

source {
  MySQL-CDC {
    username = "seatunnel"
    password = "xxxx"
    table-names = ["seatunnel.bj_yt"]
    base-url = "jdbc:mysql://192.168.2.xxx:3306/seatunnel"
  }
}


sink {
  jdbc {
    url = "jdbc:mysql://192.168.2.xxx:3306/seatunnel2"
    driver = "com.mysql.cj.jdbc.Driver"
    username = "seatunnel"
    password = "xxxx"
    generate_sink_sql = true
    database = "seatunnel2"
    table = "bj_yt_from_mysql"
    primary_keys = ["itemcode"]
  }
}
```

### Running Command

```shell
sh bin/seatunnel.sh -c config/mysqlcdc_2_mysql.conf
```

### Error Exception

```log
2024-06-27 14:20:28,664 INFO  [.s.p.d.AbstractPluginDiscovery] [main] - Load SeaTunnelSink Plugin from /root/apache-seatunnel-2.3.5/connectors
2024-06-27 14:20:28,674 INFO  [.s.p.d.AbstractPluginDiscovery] [main] - Discovery plugin jar for: PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='MySQL-CDC'} at: file:/root/apache-seatunnel-2.3.5/connectors/connector-cdc-mysql-2.3.5.jar
2024-06-27 14:20:28,676 INFO  [.s.p.d.AbstractPluginDiscovery] [main] - Discovery plugin jar for: PluginIdentifier{engineType='seatunnel', pluginType='sink', pluginName='jdbc'} at: file:/root/apache-seatunnel-2.3.5/connectors/connector-jdbc-2.3.5.jar
2024-06-27 14:20:28,686 INFO  [p.MultipleTableJobConfigParser] [main] - start generating all sources.
2024-06-27 14:20:28,755 INFO  [.s.c.s.j.c.AbstractJdbcCatalog] [main] - Catalog MySQL closing
2024-06-27 14:20:28,755 INFO  [c.h.c.LifecycleService        ] [main] - hz.client_1 [seatunnel] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is SHUTTING_DOWN
2024-06-27 14:20:28,760 INFO  [.c.i.c.ClientConnectionManager] [main] - hz.client_1 [seatunnel] [5.1] Removed connection to endpoint: [localhost]:5801:bc2fc57c-f575-4d24-a38a-73eb68d48625, connection: ClientConnection{alive=false, connectionId=1, channel=NioChannel{/127.0.0.1:37745->localhost/127.0.0.1:5801}, remoteAddress=[localhost]:5801, lastReadTime=2024-06-27 14:20:28.428, lastWriteTime=2024-06-27 14:20:28.427, closedTime=2024-06-27 14:20:28.757, connected server version=5.1}
2024-06-27 14:20:28,760 INFO  [c.h.c.LifecycleService        ] [main] - hz.client_1 [seatunnel] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is CLIENT_DISCONNECTED
2024-06-27 14:20:28,764 INFO  [c.h.c.LifecycleService        ] [main] - hz.client_1 [seatunnel] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is SHUTDOWN
2024-06-27 14:20:28,764 INFO  [s.c.s.s.c.ClientExecuteCommand] [main] - Closed SeaTunnel client......
2024-06-27 14:20:28,764 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - 

===============================================================================


2024-06-27 14:20:28,764 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Fatal Error, 

2024-06-27 14:20:28,764 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Please submit bug report in https://github.com/apache/seatunnel/issues

2024-06-27 14:20:28,765 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Reason:SeaTunnel job executed failed 

2024-06-27 14:20:28,767 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:202)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.api.table.factory.FactoryException: ErrorCode:[API-06], ErrorDescription:[Factory initialize failed] - Unable to create a source for identifier 'MySQL-CDC'.
        at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:100)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:332)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:188)
        at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.getLogicalDag(ClientJobExecutionEnvironment.java:88)
        at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.execute(ClientJobExecutionEnvironment.java:156)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:149)
        ... 2 more
Caused by: org.apache.seatunnel.api.table.catalog.exception.CatalogException: ErrorCode:[API-03], ErrorDescription:[Catalog initialize failed] - Failed connecting to jdbc:mysql://192.168.2.128:3306/seatunnel via JDBC.
        at org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.AbstractJdbcCatalog.getConnection(AbstractJdbcCatalog.java:123)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.AbstractJdbcCatalog.open(AbstractJdbcCatalog.java:129)
        at org.apache.seatunnel.api.table.catalog.CatalogTableUtil.lambda$getCatalogTables$0(CatalogTableUtil.java:120)
        at java.util.Optional.map(Optional.java:215)
        at org.apache.seatunnel.api.table.catalog.CatalogTableUtil.getCatalogTables(CatalogTableUtil.java:116)
        at org.apache.seatunnel.api.table.catalog.CatalogTableUtil.getCatalogTables(CatalogTableUtil.java:96)
        at org.apache.seatunnel.connectors.seatunnel.cdc.mysql.source.MySqlIncrementalSourceFactory.lambda$createSource$1(MySqlIncrementalSourceFactory.java:102)
        at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:112)
        at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:73)
        ... 7 more
Caused by: java.sql.SQLException: No suitable driver found for jdbc:mysql://192.168.2.128:3306/seatunnel
        at java.sql.DriverManager.getConnection(DriverManager.java:689)
        at java.sql.DriverManager.getConnection(DriverManager.java:247)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.AbstractJdbcCatalog.getConnection(AbstractJdbcCatalog.java:119)
        ... 15 more
 
2024-06-27 14:20:28,767 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - 


Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:202)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.api.table.factory.FactoryException: ErrorCode:[API-06], ErrorDescription:[Factory initialize failed] - Unable to create a source for identifier 'MySQL-CDC'.
        at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:100)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:332)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:188)
        at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.getLogicalDag(ClientJobExecutionEnvironment.java:88)
        at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.execute(ClientJobExecutionEnvironment.java:156)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:149)
        ... 2 more
Caused by: org.apache.seatunnel.api.table.catalog.exception.CatalogException: ErrorCode:[API-03], ErrorDescription:[Catalog initialize failed] - Failed connecting to jdbc:mysql://192.168.2.128:3306/seatunnel via JDBC.
        at org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.AbstractJdbcCatalog.getConnection(AbstractJdbcCatalog.java:123)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.AbstractJdbcCatalog.open(AbstractJdbcCatalog.java:129)
        at org.apache.seatunnel.api.table.catalog.CatalogTableUtil.lambda$getCatalogTables$0(CatalogTableUtil.java:120)
        at java.util.Optional.map(Optional.java:215)
        at org.apache.seatunnel.api.table.catalog.CatalogTableUtil.getCatalogTables(CatalogTableUtil.java:116)
        at org.apache.seatunnel.api.table.catalog.CatalogTableUtil.getCatalogTables(CatalogTableUtil.java:96)
        at org.apache.seatunnel.connectors.seatunnel.cdc.mysql.source.MySqlIncrementalSourceFactory.lambda$createSource$1(MySqlIncrementalSourceFactory.java:102)
        at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:112)
        at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:73)
        ... 7 more
Caused by: java.sql.SQLException: No suitable driver found for jdbc:mysql://192.168.2.128:3306/seatunnel
        at java.sql.DriverManager.getConnection(DriverManager.java:689)
        at java.sql.DriverManager.getConnection(DriverManager.java:247)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.catalog.AbstractJdbcCatalog.getConnection(AbstractJdbcCatalog.java:119)
        ... 15 more
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liunaijie** [comment]
you need download mysql-connect-java.jar to `lib/` folder

![image](https://github.com/apache/seatunnel/assets/28497357/3be35570-4cee-4013-861b-18a6c57bcbd9)
