### ISSUE TITLE
Can not get coordinator service from an active master node

### ISSUE THREAD

**Issue by Jiangnanjiezi** [apache/seatunnel#7081]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When I use MySQL CDC to sync MySQL to Kafka, sometimes it works and sometimes it doesn't. The following error is reported. Now not only this task can not run, to the ordinary demo also reported this error.

### SeaTunnel Version

2.3.5

### SeaTunnel Config

```conf
env {
  parallelism = 1
  job.mode = "STREAMING"
  checkpoint.interval = 10000
}

source {
  MySQL-CDC {
    base-url = "jdbc:mysql://up01:3306/hive_data"
    username = "root"
    password = "123456"
    start.mode = "initial"
    server-time-zone = "Asia/Shanghai"
    exactly_once = "true"
    table-names = ["hive_data.shop_order"]
    table-names-config = [
      {
        table = "hive_data.shop_order"
        primaryKeys = ["id"]
      }
    ]
    
    format = compatible_debezium_json
    debezium = {
        # include schema into kafka message
        key.converter.schemas.enable = false
        value.converter.schemas.enable = false
        # include ddl
        include.schema.changes = true
        # topic prefix
        database.server.name =  "mysql_cdc_"
    }
  }
}

sink {
  kafka {
      topic = "test_topic"
      bootstrap.servers = "up01:9092"
      format = compatible_debezium_json
      kafka.request.timeout.ms = 60000
      semantics = EXACTLY_ONCE
      transaction_prefix = "sot"
      kafka.config = {
        acks = "all"
        request.timeout.ms = 60000
        buffer.memory = 33554432
      }
  }
}
```

### Running Command

```shell
cd /export/server/apache-seatunnel-2.3.5/
./bin/seatunnel.sh --config ./config/job/shop_order_to_kafka.config -e local
```

### Error Exception

```log
2024-06-28 19:33:23,767 INFO  [c.h.i.p.i.MigrationManager    ] [hz.main.cached.thread-6] - [localhost]:5801 [seatunnel-442264] [5.1] Shutdown request of Member [localhost]:5801 - cc5141e4-b514-4844-a92e-7d69511a4afb this is handled
2024-06-28 19:33:23,777 INFO  [c.h.i.i.Node                  ] [main] - [localhost]:5801 [seatunnel-442264] [5.1] Shutting down connection manager...
2024-06-28 19:33:23,797 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [localhost]:5801
2024-06-28 19:33:23,797 INFO  [c.h.i.i.Node                  ] [main] - [localhost]:5801 [seatunnel-442264] [5.1] Shutting down node engine...
2024-06-28 19:33:23,798 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [localhost]:5801
2024-06-28 19:33:23,798 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [localhost]:5801
2024-06-28 19:33:23,798 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [localhost]:5801
2024-06-28 19:33:23,799 WARN  [c.h.s.i.o.i.Invocation        ] [main] - [localhost]:5801 [seatunnel-442264] [5.1] Future.complete(Object) on completed future. Request: Invocation{op=com.hazelcast.map.impl.operation.GetOperation{serviceName='hz:impl:mapService', identityHash=679143692, partitionId=209, replicaIndex=0, callId=-4584, invocationTime=1719574403798 (2024-06-28 19:33:23.798), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0, name=engine_runningJobState}, tryCount=20, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1719574403798, firstInvocationTime='2024-06-28 19:33:23.798', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 08:00:00.000', target=[localhost]:5801, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=0, connection=null}, current value: HeapData{type=-100, hashCode=1907157633, partitionHash=1907157633, totalSize=127, dataSize=119, heapCost=159}, offered value: ExceptionalResult{cause=com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!}
java.lang.Exception: null
        at com.hazelcast.spi.impl.AbstractInvocationFuture.warnIfSuspiciousDoubleCompletion(AbstractInvocationFuture.java:1253) [seatunnel-starter.jar:2.3.5]
        at com.hazelcast.spi.impl.AbstractInvocationFuture.complete0(AbstractInvocationFuture.java:1230) [seatunnel-starter.jar:2.3.5]
        at com.hazelcast.spi.impl.AbstractInvocationFuture.completeExceptionallyInternal(AbstractInvocationFuture.java:1223) [seatunnel-starter.jar:2.3.5]
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.completeExceptionally(Invocation.java:680) [seatunnel-starter.jar:2.3.5]
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.notifyThrowable(Invocation.java:386) [seatunnel-starter.jar:2.3.5]
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.notifyError(Invocation.java:330) [seatunnel-starter.jar:2.3.5]
        at com.hazelcast.spi.impl.operationservice.impl.InvocationRegistry.shutdown(InvocationRegistry.java:229) [seatunnel-starter.jar:2.3.5]
        at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.shutdownInvocations(OperationServiceImpl.java:534) [seatunnel-starter.jar:2.3.5]
        at com.hazelcast.spi.impl.NodeEngineImpl.shutdown(NodeEngineImpl.java:543) [seatunnel-starter.jar:2.3.5]
        at com.hazelcast.instance.impl.Node.shutdownServices(Node.java:605) [seatunnel-starter.jar:2.3.5]
        at com.hazelcast.instance.impl.Node.shutdown(Node.java:544) [seatunnel-starter.jar:2.3.5]
        at com.hazelcast.instance.impl.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:101) [seatunnel-starter.jar:2.3.5]
        at com.hazelcast.instance.impl.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:84) [seatunnel-starter.jar:2.3.5]
        at com.hazelcast.instance.impl.HazelcastInstanceProxy.shutdown(HazelcastInstanceProxy.java:311) [seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.closeClient(ClientExecuteCommand.java:235) [seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:225) [seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40) [seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34) [seatunnel-starter.jar:2.3.5]
2024-06-28 19:33:23,805 ERROR [o.a.s.e.s.CoordinatorService  ] [seatunnel-coordinator-service-1] - [localhost]:5801 [seatunnel-442264] [5.1] Job id 859001764710449153 init failed
org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: Job id 859001764710449153 init failed
        at org.apache.seatunnel.engine.server.CoordinatorService.restoreJobFromMasterActiveSwitch(CoordinatorService.java:342) ~[seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.engine.server.CoordinatorService.lambda$null$0(CoordinatorService.java:295) ~[seatunnel-starter.jar:2.3.5]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) [?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_241]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
Caused by: com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
        at com.hazelcast.spi.impl.operationservice.impl.InvocationRegistry.register(InvocationRegistry.java:140) ~[seatunnel-starter.jar:2.3.5]
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:570) ~[seatunnel-starter.jar:2.3.5]
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:541) ~[seatunnel-starter.jar:2.3.5]
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:241) ~[seatunnel-starter.jar:2.3.5]
        at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:61) ~[seatunnel-starter.jar:2.3.5]
        at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:478) ~[seatunnel-starter.jar:2.3.5]
        at com.hazelcast.map.impl.proxy.MapProxySupport.getInternal(MapProxySupport.java:371) ~[seatunnel-starter.jar:2.3.5]
        at com.hazelcast.map.impl.proxy.MapProxyImpl.get(MapProxyImpl.java:123) ~[seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.engine.server.dag.physical.PhysicalVertex.<init>(PhysicalVertex.java:161) ~[seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.engine.server.dag.physical.PhysicalPlanGenerator.lambda$getEnumeratorTask$10(PhysicalPlanGenerator.java:494) ~[seatunnel-starter.jar:2.3.5]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_241]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_241]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_241]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_241]
        at org.apache.seatunnel.engine.server.dag.physical.PhysicalPlanGenerator.getEnumeratorTask(PhysicalPlanGenerator.java:501) ~[seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.engine.server.dag.physical.PhysicalPlanGenerator.lambda$generate$0(PhysicalPlanGenerator.java:173) ~[seatunnel-starter.jar:2.3.5]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_241]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_241]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_241]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_241]
        at org.apache.seatunnel.engine.server.dag.physical.PhysicalPlanGenerator.generate(PhysicalPlanGenerator.java:213) ~[seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.engine.server.dag.physical.PlanUtils.fromLogicalDAG(PlanUtils.java:61) ~[seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.engine.server.master.JobMaster.init(JobMaster.java:220) ~[seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.engine.server.CoordinatorService.restoreJobFromMasterActiveSwitch(CoordinatorService.java:340) ~[seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.engine.server.CoordinatorService.lambda$null$0(CoordinatorService.java:295) ~[seatunnel-starter.jar:2.3.5]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_241]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_241]
        at ------ submitted from ------.() ~[?:?]
        at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:336) ~[seatunnel-starter.jar:2.3.5]
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:112) ~[seatunnel-starter.jar:2.3.5]
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:100) ~[seatunnel-starter.jar:2.3.5]
        at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:609) ~[seatunnel-starter.jar:2.3.5]
        at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:479) ~[seatunnel-starter.jar:2.3.5]
        at com.hazelcast.map.impl.proxy.MapProxySupport.getInternal(MapProxySupport.java:371) ~[seatunnel-starter.jar:2.3.5]
        at com.hazelcast.map.impl.proxy.MapProxyImpl.get(MapProxyImpl.java:123) ~[seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.engine.server.dag.physical.PhysicalVertex.<init>(PhysicalVertex.java:161) ~[seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.engine.server.dag.physical.PhysicalPlanGenerator.lambda$getEnumeratorTask$10(PhysicalPlanGenerator.java:494) ~[seatunnel-starter.jar:2.3.5]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_241]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_241]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_241]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_241]
        at org.apache.seatunnel.engine.server.dag.physical.PhysicalPlanGenerator.getEnumeratorTask(PhysicalPlanGenerator.java:501) ~[seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.engine.server.dag.physical.PhysicalPlanGenerator.lambda$generate$0(PhysicalPlanGenerator.java:173) ~[seatunnel-starter.jar:2.3.5]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_241]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_241]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_241]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_241]
        at org.apache.seatunnel.engine.server.dag.physical.PhysicalPlanGenerator.generate(PhysicalPlanGenerator.java:213) ~[seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.engine.server.dag.physical.PlanUtils.fromLogicalDAG(PlanUtils.java:61) ~[seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.engine.server.master.JobMaster.init(JobMaster.java:220) ~[seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.engine.server.CoordinatorService.restoreJobFromMasterActiveSwitch(CoordinatorService.java:340) ~[seatunnel-starter.jar:2.3.5]
        ... 5 more
2024-06-28 19:33:23,806 INFO  [o.a.s.e.s.CoordinatorService  ] [seatunnel-coordinator-service-1] - [localhost]:5801 [seatunnel-442264] [5.1] restore job (859001764710449153) from master active switch finished
2024-06-28 19:33:23,806 ERROR [o.a.s.e.s.CoordinatorService  ] [seatunnel-coordinator-service-3] - [localhost]:5801 [seatunnel-442264] [5.1] Job id 858977206603350017 init failed
org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: Job id 858977206603350017 init failed
        at org.apache.seatunnel.engine.server.CoordinatorService.restoreJobFromMasterActiveSwitch(CoordinatorService.java:342) ~[seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.engine.server.CoordinatorService.lambda$null$0(CoordinatorService.java:295) ~[seatunnel-starter.jar:2.3.5]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) [?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_241]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
Caused by: com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
        at com.hazelcast.spi.impl.operationservice.impl.InvocationRegistry.register(InvocationRegistry.java:140) ~[seatunnel-starter.jar:2.3.5]
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:570) ~[seatunnel-starter.jar:2.3.5]
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:541) ~[seatunnel-starter.jar:2.3.5]
        at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:241) ~[seatunnel-starter.jar:2.3.5]
        at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:61) ~[seatunnel-starter.jar:2.3.5]
        at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:478) ~[seatunnel-starter.jar:2.3.5]
        at com.hazelcast.map.impl.proxy.MapProxySupport.getInternal(MapProxySupport.java:371) ~[seatunnel-starter.jar:2.3.5]
        at com.hazelcast.map.impl.proxy.MapProxyImpl.get(MapProxyImpl.java:123) ~[seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.engine.server.dag.physical.PhysicalVertex.<init>(PhysicalVertex.java:152) ~[seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.engine.server.dag.physical.PhysicalPlanGenerator.lambda$getEnumeratorTask$10(PhysicalPlanGenerator.java:494) ~[seatunnel-starter.jar:2.3.5]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_241]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_241]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_241]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_241]
        at org.apache.seatunnel.engine.server.dag.physical.PhysicalPlanGenerator.getEnumeratorTask(PhysicalPlanGenerator.java:501) ~[seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.engine.server.dag.physical.PhysicalPlanGenerator.lambda$generate$0(PhysicalPlanGenerator.java:173) ~[seatunnel-starter.jar:2.3.5]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_241]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_241]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_241]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_241]
        at org.apache.seatunnel.engine.server.dag.physical.PhysicalPlanGenerator.generate(PhysicalPlanGenerator.java:213) ~[seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.engine.server.dag.physical.PlanUtils.fromLogicalDAG(PlanUtils.java:61) ~[seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.engine.server.master.JobMaster.init(JobMaster.java:220) ~[seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.engine.server.CoordinatorService.restoreJobFromMasterActiveSwitch(CoordinatorService.java:340) ~[seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.engine.server.CoordinatorService.lambda$null$0(CoordinatorService.java:295) ~[seatunnel-starter.jar:2.3.5]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_241]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_241]
        at ------ submitted from ------.() ~[?:?]
        at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:336) ~[seatunnel-starter.jar:2.3.5]
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:112) ~[seatunnel-starter.jar:2.3.5]
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:100) ~[seatunnel-starter.jar:2.3.5]
        at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:609) ~[seatunnel-starter.jar:2.3.5]
        at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:479) ~[seatunnel-starter.jar:2.3.5]
        at com.hazelcast.map.impl.proxy.MapProxySupport.getInternal(MapProxySupport.java:371) ~[seatunnel-starter.jar:2.3.5]
        at com.hazelcast.map.impl.proxy.MapProxyImpl.get(MapProxyImpl.java:123) ~[seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.engine.server.dag.physical.PhysicalVertex.<init>(PhysicalVertex.java:152) ~[seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.engine.server.dag.physical.PhysicalPlanGenerator.lambda$getEnumeratorTask$10(PhysicalPlanGenerator.java:494) ~[seatunnel-starter.jar:2.3.5]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_241]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_241]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_241]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_241]
        at org.apache.seatunnel.engine.server.dag.physical.PhysicalPlanGenerator.getEnumeratorTask(PhysicalPlanGenerator.java:501) ~[seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.engine.server.dag.physical.PhysicalPlanGenerator.lambda$generate$0(PhysicalPlanGenerator.java:173) ~[seatunnel-starter.jar:2.3.5]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_241]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_241]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_241]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_241]
        at org.apache.seatunnel.engine.server.dag.physical.PhysicalPlanGenerator.generate(PhysicalPlanGenerator.java:213) ~[seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.engine.server.dag.physical.PlanUtils.fromLogicalDAG(PlanUtils.java:61) ~[seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.engine.server.master.JobMaster.init(JobMaster.java:220) ~[seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.engine.server.CoordinatorService.restoreJobFromMasterActiveSwitch(CoordinatorService.java:340) ~[seatunnel-starter.jar:2.3.5]
        ... 5 more
2024-06-28 19:33:23,807 INFO  [o.a.s.e.s.CoordinatorService  ] [seatunnel-coordinator-service-3] - [localhost]:5801 [seatunnel-442264] [5.1] restore job (858977206603350017) from master active switch finished
2024-06-28 19:33:23,807 INFO  [o.a.s.e.i.s.f.IMapFileStorage ] [main] - start destroy IMapFileStorage, businessName is engine_runningJobState, cluster name is 5979399814057
2024-06-28 19:33:23,805 ERROR [o.a.s.e.s.CoordinatorService  ] [seatunnel-coordinator-service-0] - [localhost]:5801 [seatunnel-442264] [5.1] Job id 858987809690615809 init failed
org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: Job id 858987809690615809 init failed
        at org.apache.seatunnel.engine.server.CoordinatorService.restoreJobFromMasterActiveSwitch(CoordinatorService.java:342) ~[seatunnel-starter.jar:2.3.5]
        at org.apache.seatunnel.engine.server.CoordinatorService.lambda$null$0(CoordinatorService.java:295) ~[seatunnel-starter.jar:2.3.5]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) [?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_241]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
Caused by: com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
```

### Zeta or Flink or Spark Version

Zeta 2.3.5

### Java or Scala Version

java 1.8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jyyfei** [comment]
一样的问题，引擎单台重启后会报这个错

**Comment by wangzhiwei61** [comment]
> 一样的问题，引擎单台重启后会报这个错

这是新加的机制吗，因为我看有数据库连接不上后，多次重试不成功后，然后就终止任务，后面就Hazelcast instance is not active!后面再rest请求就一直失败了
