### ISSUE TITLE
[Bug] [Elasticsearch]Configuration Bug

### ISSUE THREAD

**Issue by Wudadada** [apache/seatunnel#7094]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I encountered an error while trying to migrate an index from one Elasticsearch cluster to another.

### SeaTunnel Version

2.3.5

### SeaTunnel Config

```conf
env {
  parallelism = 1
  job.mode = "BATCH"
}

source {
    Elasticsearch {
        hosts = ["http://脱敏ip:9200"]
    	index = "xxx"
	username = "elastic"
	password = "xxx"
	tls_verify_certificate = false
	tls_verify_hostnames = false
    }
}

sink {
    Elasticsearch {
        hosts = ["http://脱敏ip:4099"]
	index = "xxx"
	username = "elastic"
	password = "xxx"
	tls_verify_certificate = false
	tls_verify_hostnames = false
        schema_save_mode = "CREATE_SCHEMA_WHEN_NOT_EXIST"
        data_save_mode = "APPEND_DATA"
    }
}
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/v2.batch.config.template -e local
```

### Error Exception

```log
2024-07-02 17:16:53,163 INFO  [c.h.system                    ] [main] - [localhost]:5801 [seatunnel-380174] [5.1] Copyright © 2021-2022 The Apache Software Foundation. Apache SeaTunnel, SeaTunnel, and its feather logo are trademarks of The Apache Software Foundation.
2024-07-02 17:16:53,163 INFO  [c.h.system                    ] [main] - [localhost]:5801 [seatunnel-380174] [5.1] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed.
To enable integrity checker do one of the following: 
  - Change member config using Java API: config.setIntegrityCheckerEnabled(true);
  - Change XML/YAML configuration property: Set hazelcast.integrity-checker.enabled to true
  - Add system property: -Dhz.integritychecker.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
  - Add environment variable: HZ_INTEGRITYCHECKER_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)
2024-07-02 17:16:53,164 INFO  [c.h.system                    ] [main] - [localhost]:5801 [seatunnel-380174] [5.1] The Jet engine is disabled.
To enable the Jet engine on the members, do one of the following:
  - Change member config using Java API: config.getJetConfig().setEnabled(true)
  - Change XML/YAML configuration property: Set hazelcast.jet.enabled to true
  - Add system property: -Dhz.jet.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
  - Add environment variable: HZ_JET_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)
2024-07-02 17:16:53,292 INFO  [c.h.s.security                ] [main] - [localhost]:5801 [seatunnel-380174] [5.1] Enable DEBUG/FINE log level for log category com.hazelcast.system.security  or use -Dhazelcast.security.recommendations system property to see 🔒 security recommendations and the status of current config.
2024-07-02 17:16:53,313 INFO  [c.h.i.i.Node                  ] [main] - [localhost]:5801 [seatunnel-380174] [5.1] Using TCP/IP discovery
2024-07-02 17:16:53,313 WARN  [c.h.c.CPSubsystem             ] [main] - [localhost]:5801 [seatunnel-380174] [5.1] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
2024-07-02 17:16:53,375 INFO  [.c.c.DefaultClassLoaderService] [main] - start classloader service
7月 02, 2024 5:16:53 下午 com.hazelcast.internal.config.AbstractConfigLocator
信息: Loading configuration '/Users/wqd/Downloads/apache-seatunnel-2.3.5/config/seatunnel.yaml' from System property 'seatunnel.config'
7月 02, 2024 5:16:53 下午 com.hazelcast.internal.config.AbstractConfigLocator
信息: Using configuration file at /Users/wqd/Downloads/apache-seatunnel-2.3.5/config/seatunnel.yaml
7月 02, 2024 5:16:53 下午 com.hazelcast.internal.config.AbstractConfigLocator
信息: Loading configuration '/Users/wqd/Downloads/apache-seatunnel-2.3.5/config/hazelcast.yaml' from System property 'hazelcast.config'
7月 02, 2024 5:16:53 下午 com.hazelcast.internal.config.AbstractConfigLocator
信息: Using configuration file at /Users/wqd/Downloads/apache-seatunnel-2.3.5/config/hazelcast.yaml
2024-07-02 17:16:53,381 WARN  [o.a.s.e.s.TaskExecutionService] [pool-2-thread-1] - [localhost]:5801 [seatunnel-380174] [5.1] The Node is not ready yet, Node state STARTING,looking forward to the next scheduling
2024-07-02 17:16:53,382 INFO  [o.a.s.e.s.TaskExecutionService] [main] - [localhost]:5801 [seatunnel-380174] [5.1] Created new BusWork : 1388280822
2024-07-02 17:16:53,390 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [localhost]:5801
2024-07-02 17:16:53,391 INFO  [o.a.s.e.s.CoordinatorService  ] [pool-6-thread-1] - [localhost]:5801 [seatunnel-380174] [5.1] 
***********************************************
     CoordinatorService Thread Pool Status
***********************************************
activeCount               :                   0
corePoolSize              :                   0
maximumPoolSize           :          2147483647
poolSize                  :                   0
completedTaskCount        :                   0
taskCount                 :                   0
***********************************************

2024-07-02 17:16:53,400 INFO  [c.h.i.d.Diagnostics           ] [main] - [localhost]:5801 [seatunnel-380174] [5.1] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
2024-07-02 17:16:53,402 INFO  [c.h.c.LifecycleService        ] [main] - [localhost]:5801 [seatunnel-380174] [5.1] [localhost]:5801 is STARTING
2024-07-02 17:16:53,418 INFO  [c.h.i.c.i.TcpIpJoiner         ] [hz.main.cached.thread-7] - [localhost]:5801 [seatunnel-380174] [5.1] [localhost]:5819 is added to the blacklist.
2024-07-02 17:16:53,418 INFO  [c.h.i.c.i.TcpIpJoiner         ] [hz.main.cached.thread-5] - [localhost]:5801 [seatunnel-380174] [5.1] [localhost]:5815 is added to the blacklist.
2024-07-02 17:16:53,418 INFO  [c.h.i.c.i.TcpIpJoiner         ] [hz.main.cached.thread-14] - [localhost]:5801 [seatunnel-380174] [5.1] [localhost]:5802 is added to the blacklist.
2024-07-02 17:16:53,418 INFO  [c.h.i.c.i.TcpIpJoiner         ] [hz.main.cached.thread-11] - [localhost]:5801 [seatunnel-380174] [5.1] [localhost]:5810 is added to the blacklist.
2024-07-02 17:16:53,418 INFO  [c.h.i.c.i.TcpIpJoiner         ] [hz.main.cached.thread-16] - [localhost]:5801 [seatunnel-380174] [5.1] [localhost]:5820 is added to the blacklist.
2024-07-02 17:16:53,418 INFO  [c.h.i.c.i.TcpIpJoiner         ] [hz.main.cached.thread-15] - [localhost]:5801 [seatunnel-380174] [5.1] [localhost]:5822 is added to the blacklist.
2024-07-02 17:16:53,418 INFO  [c.h.i.c.i.TcpIpJoiner         ] [hz.main.cached.thread-13] - [localhost]:5801 [seatunnel-380174] [5.1] [localhost]:5829 is added to the blacklist.
2024-07-02 17:16:53,418 INFO  [c.h.i.c.i.TcpIpJoiner         ] [hz.main.cached.thread-10] - [localhost]:5801 [seatunnel-380174] [5.1] [localhost]:5804 is added to the blacklist.
2024-07-02 17:16:53,418 INFO  [c.h.i.c.i.TcpIpJoiner         ] [hz.main.cached.thread-2] - [localhost]:5801 [seatunnel-380174] [5.1] [localhost]:5821 is added to the blacklist.
2024-07-02 17:16:53,418 INFO  [c.h.i.c.i.TcpIpJoiner         ] [hz.main.cached.thread-3] - [localhost]:5801 [seatunnel-380174] [5.1] [localhost]:5823 is added to the blacklist.
2024-07-02 17:16:53,418 INFO  [c.h.i.c.i.TcpIpJoiner         ] [hz.main.cached.thread-9] - [localhost]:5801 [seatunnel-380174] [5.1] [localhost]:5806 is added to the blacklist.
2024-07-02 17:16:53,418 INFO  [c.h.i.c.i.TcpIpJoiner         ] [hz.main.cached.thread-12] - [localhost]:5801 [seatunnel-380174] [5.1] [localhost]:5808 is added to the blacklist.
2024-07-02 17:16:53,418 INFO  [c.h.i.c.i.TcpIpJoiner         ] [hz.main.cached.thread-11] - [localhost]:5801 [seatunnel-380174] [5.1] [localhost]:5814 is added to the blacklist.
2024-07-02 17:16:53,418 INFO  [c.h.i.c.i.TcpIpJoiner         ] [hz.main.cached.thread-16] - [localhost]:5801 [seatunnel-380174] [5.1] [localhost]:5812 is added to the blacklist.
2024-07-02 17:16:53,418 INFO  [c.h.i.c.i.TcpIpJoiner         ] [hz.main.cached.thread-14] - [localhost]:5801 [seatunnel-380174] [5.1] [localhost]:5824 is added to the blacklist.
2024-07-02 17:16:53,418 INFO  [c.h.i.c.i.TcpIpJoiner         ] [hz.main.cached.thread-8] - [localhost]:5801 [seatunnel-380174] [5.1] [localhost]:5817 is added to the blacklist.
2024-07-02 17:16:53,418 INFO  [c.h.i.c.i.TcpIpJoiner         ] [hz.main.cached.thread-7] - [localhost]:5801 [seatunnel-380174] [5.1] [localhost]:5826 is added to the blacklist.
2024-07-02 17:16:53,419 INFO  [c.h.i.c.i.TcpIpJoiner         ] [hz.main.cached.thread-10] - [localhost]:5801 [seatunnel-380174] [5.1] [localhost]:5807 is added to the blacklist.
2024-07-02 17:16:53,418 INFO  [c.h.i.c.i.TcpIpJoiner         ] [hz.main.cached.thread-6] - [localhost]:5801 [seatunnel-380174] [5.1] [localhost]:5813 is added to the blacklist.
2024-07-02 17:16:53,419 INFO  [c.h.i.c.i.TcpIpJoiner         ] [hz.main.cached.thread-3] - [localhost]:5801 [seatunnel-380174] [5.1] [localhost]:5811 is added to the blacklist.
2024-07-02 17:16:53,418 INFO  [c.h.i.c.i.TcpIpJoiner         ] [hz.main.cached.thread-1] - [localhost]:5801 [seatunnel-380174] [5.1] [localhost]:5827 is added to the blacklist.
2024-07-02 17:16:53,419 INFO  [c.h.i.c.i.TcpIpJoiner         ] [hz.main.cached.thread-12] - [localhost]:5801 [seatunnel-380174] [5.1] [localhost]:5830 is added to the blacklist.
2024-07-02 17:16:53,418 INFO  [c.h.i.c.i.TcpIpJoiner         ] [hz.main.cached.thread-4] - [localhost]:5801 [seatunnel-380174] [5.1] [localhost]:5825 is added to the blacklist.
2024-07-02 17:16:53,419 INFO  [c.h.i.c.i.TcpIpJoiner         ] [hz.main.cached.thread-9] - [localhost]:5801 [seatunnel-380174] [5.1] [localhost]:5809 is added to the blacklist.
2024-07-02 17:16:53,419 INFO  [c.h.i.c.i.TcpIpJoiner         ] [hz.main.cached.thread-16] - [localhost]:5801 [seatunnel-380174] [5.1] [localhost]:5803 is added to the blacklist.
2024-07-02 17:16:53,419 INFO  [c.h.i.c.i.TcpIpJoiner         ] [hz.main.cached.thread-13] - [localhost]:5801 [seatunnel-380174] [5.1] [localhost]:5816 is added to the blacklist.
2024-07-02 17:16:53,419 INFO  [c.h.i.c.i.TcpIpJoiner         ] [hz.main.cached.thread-2] - [localhost]:5801 [seatunnel-380174] [5.1] [localhost]:5805 is added to the blacklist.
2024-07-02 17:16:53,419 INFO  [c.h.i.c.i.TcpIpJoiner         ] [hz.main.cached.thread-11] - [localhost]:5801 [seatunnel-380174] [5.1] [localhost]:5828 is added to the blacklist.
2024-07-02 17:16:53,418 INFO  [c.h.i.c.i.TcpIpJoiner         ] [hz.main.cached.thread-15] - [localhost]:5801 [seatunnel-380174] [5.1] [localhost]:5818 is added to the blacklist.
2024-07-02 17:16:54,420 INFO  [c.h.i.c.ClusterService        ] [main] - [localhost]:5801 [seatunnel-380174] [5.1] 

Members {size:1, ver:1} [
	Member [localhost]:5801 - 4da0e1bd-d8c1-4ed5-b4c4-d8b13faedb72 this
]

2024-07-02 17:16:54,425 INFO  [c.h.c.LifecycleService        ] [main] - [localhost]:5801 [seatunnel-380174] [5.1] [localhost]:5801 is STARTED
2024-07-02 17:16:54,440 INFO  [.c.i.s.ClientInvocationService] [main] - hz.client_1 [seatunnel-380174] [5.1] Running with 2 response threads, dynamic=true
2024-07-02 17:16:54,444 INFO  [c.h.c.LifecycleService        ] [main] - hz.client_1 [seatunnel-380174] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is STARTING
2024-07-02 17:16:54,445 INFO  [c.h.c.LifecycleService        ] [main] - hz.client_1 [seatunnel-380174] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is STARTED
2024-07-02 17:16:54,447 INFO  [.c.i.c.ClientConnectionManager] [main] - hz.client_1 [seatunnel-380174] [5.1] Trying to connect to cluster: seatunnel-380174
2024-07-02 17:16:54,448 INFO  [.c.i.c.ClientConnectionManager] [main] - hz.client_1 [seatunnel-380174] [5.1] Trying to connect to [localhost]:5801
2024-07-02 17:16:54,454 INFO  [.p.t.AuthenticationMessageTask] [hz.main.priority-generic-operation.thread-0] - [localhost]:5801 [seatunnel-380174] [5.1] Received auth from Connection[id=1, /127.0.0.1:5801->/127.0.0.1:65109, qualifier=null, endpoint=[127.0.0.1]:65109, remoteUuid=b417ab45-4fc0-4101-856d-b69775a9035b, alive=true, connectionType=JVM, planeIndex=-1], successfully authenticated, clientUuid: b417ab45-4fc0-4101-856d-b69775a9035b, client name: hz.client_1, client version: 5.1
2024-07-02 17:16:54,455 INFO  [c.h.c.LifecycleService        ] [main] - hz.client_1 [seatunnel-380174] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is CLIENT_CONNECTED
2024-07-02 17:16:54,455 INFO  [.c.i.c.ClientConnectionManager] [main] - hz.client_1 [seatunnel-380174] [5.1] Authenticated with server [localhost]:5801:4da0e1bd-d8c1-4ed5-b4c4-d8b13faedb72, server version: 5.1, local address: /127.0.0.1:65109
2024-07-02 17:16:54,455 INFO  [c.h.i.d.Diagnostics           ] [main] - hz.client_1 [seatunnel-380174] [5.1] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
2024-07-02 17:16:54,458 INFO  [c.h.c.i.s.ClientClusterService] [hz.client_1.event-10] - hz.client_1 [seatunnel-380174] [5.1] 

Members [1] {
	Member [localhost]:5801 - 4da0e1bd-d8c1-4ed5-b4c4-d8b13faedb72
}

2024-07-02 17:16:54,465 INFO  [.c.i.s.ClientStatisticsService] [main] - Client statistics is enabled with period 5 seconds.
2024-07-02 17:16:54,495 INFO  [o.a.s.e.s.CoordinatorService  ] [pool-5-thread-1] - [localhost]:5801 [seatunnel-380174] [5.1] This node become a new active master node, begin init coordinator service
2024-07-02 17:16:54,514 INFO  [o.a.s.e.s.CoordinatorService  ] [pool-5-thread-1] - [localhost]:5801 [seatunnel-380174] [5.1] Loaded event handlers: [org.apache.seatunnel.api.event.LoggingEventHandler@7f512880]
2024-07-02 17:16:54,516 INFO  [.ClientJobExecutionEnvironment] [main] - add common jar in plugins :[]
2024-07-02 17:16:54,519 INFO  [.h.i.p.i.PartitionStateManager] [pool-5-thread-1] - [localhost]:5801 [seatunnel-380174] [5.1] Initializing cluster partition table arrangement...
2024-07-02 17:16:54,521 INFO  [o.a.s.c.s.u.ConfigBuilder     ] [main] - Loading config file from path: ./config/v2.batch.config.template
2024-07-02 17:16:54,537 INFO  [o.a.s.c.s.u.ConfigShadeUtils  ] [main] - Load config shade spi: [base64]
2024-07-02 17:16:54,559 INFO  [o.a.s.c.s.u.ConfigBuilder     ] [main] - Parsed config file: 
{
    "env" : {
        "parallelism" : 1,
        "job.mode" : "BATCH"
    },
    "source" : [
        {
            "password" : "S_npm0zxIFr7fcfR6tUm",
            "hosts" : [
                "http://10.5.19.79:9200"
            ],
            "index" : "document_v6",
            "tls_verify_hostnames" : false,
            "plugin_name" : "Elasticsearch",
            "tls_verify_certificate" : false,
            "username" : "elastic"
        }
    ],
    "sink" : [
        {
            "password" : "a0a7acb2",
            "hosts" : [
                "http://10.30.10.116:4099"
            ],
            "data_save_mode" : "APPEND_DATA",
            "index" : "document_v6",
            "schema_save_mode" : "CREATE_SCHEMA_WHEN_NOT_EXIST",
            "tls_verify_hostnames" : false,
            "plugin_name" : "Elasticsearch",
            "tls_verify_certificate" : false,
            "username" : "elastic"
        }
    ]
}

2024-07-02 17:16:54,564 INFO  [.s.p.d.AbstractPluginDiscovery] [main] - Load SeaTunnelSink Plugin from /Users/wqd/Downloads/apache-seatunnel-2.3.5/connectors
2024-07-02 17:16:54,566 INFO  [.s.p.d.AbstractPluginDiscovery] [main] - Discovery plugin jar for: PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='Elasticsearch'} at: file:/Users/wqd/Downloads/apache-seatunnel-2.3.5/connectors/connector-elasticsearch-2.3.5.jar
2024-07-02 17:16:54,566 INFO  [.s.p.d.AbstractPluginDiscovery] [main] - Discovery plugin jar for: PluginIdentifier{engineType='seatunnel', pluginType='sink', pluginName='Elasticsearch'} at: file:/Users/wqd/Downloads/apache-seatunnel-2.3.5/connectors/connector-elasticsearch-2.3.5.jar
2024-07-02 17:16:54,568 INFO  [p.MultipleTableJobConfigParser] [main] - start generating all sources.
2024-07-02 17:16:54,581 INFO  [c.h.c.LifecycleService        ] [main] - hz.client_1 [seatunnel-380174] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is SHUTTING_DOWN
2024-07-02 17:16:54,582 INFO  [c.h.i.s.t.TcpServerConnection ] [hz.main.IO.thread-in-1] - [localhost]:5801 [seatunnel-380174] [5.1] Connection[id=1, /127.0.0.1:5801->/127.0.0.1:65109, qualifier=null, endpoint=[127.0.0.1]:65109, remoteUuid=b417ab45-4fc0-4101-856d-b69775a9035b, alive=false, connectionType=JVM, planeIndex=-1] closed. Reason: Connection closed by the other side
2024-07-02 17:16:54,582 INFO  [.c.i.c.ClientConnectionManager] [main] - hz.client_1 [seatunnel-380174] [5.1] Removed connection to endpoint: [localhost]:5801:4da0e1bd-d8c1-4ed5-b4c4-d8b13faedb72, connection: ClientConnection{alive=false, connectionId=1, channel=NioChannel{/127.0.0.1:65109->localhost/127.0.0.1:5801}, remoteAddress=[localhost]:5801, lastReadTime=2024-07-02 17:16:54.520, lastWriteTime=2024-07-02 17:16:54.519, closedTime=2024-07-02 17:16:54.582, connected server version=5.1}
2024-07-02 17:16:54,582 INFO  [c.h.c.LifecycleService        ] [main] - hz.client_1 [seatunnel-380174] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is CLIENT_DISCONNECTED
2024-07-02 17:16:54,583 INFO  [c.h.c.i.ClientEndpointManager ] [hz.main.event-5] - [localhost]:5801 [seatunnel-380174] [5.1] Destroying ClientEndpoint{connection=Connection[id=1, /127.0.0.1:5801->/127.0.0.1:65109, qualifier=null, endpoint=[127.0.0.1]:65109, remoteUuid=b417ab45-4fc0-4101-856d-b69775a9035b, alive=false, connectionType=JVM, planeIndex=-1], clientUuid=b417ab45-4fc0-4101-856d-b69775a9035b, clientName=hz.client_1, authenticated=true, clientVersion=5.1, creationTime=1719911814453, latest clientAttributes=lastStatisticsCollectionTime=1719911814465,enterprise=false,clientType=JVM,clientVersion=5.1,clusterConnectionTimestamp=1719911814449,clientAddress=127.0.0.1,clientName=hz.client_1,credentials.principal=null,os.committedVirtualMemorySize=0,os.freePhysicalMemorySize=124682240,os.freeSwapSpaceSize=0,os.maxFileDescriptorCount=0,os.openFileDescriptorCount=0,os.processCpuTime=0,os.systemLoadAverage=1.12060546875,os.totalPhysicalMemorySize=34359738368,os.totalSwapSpaceSize=0,runtime.availableProcessors=12,runtime.freeMemory=181247072,runtime.maxMemory=536870912,runtime.totalMemory=268435456,runtime.uptime=1701,runtime.usedMemory=87188384, labels=[]}
2024-07-02 17:16:54,583 INFO  [c.h.c.LifecycleService        ] [main] - hz.client_1 [seatunnel-380174] [5.1] HazelcastClient 5.1 (20220228 - 21f20e7) is SHUTDOWN
2024-07-02 17:16:54,584 INFO  [s.c.s.s.c.ClientExecuteCommand] [main] - Closed SeaTunnel client......
2024-07-02 17:16:54,584 INFO  [c.h.c.LifecycleService        ] [main] - [localhost]:5801 [seatunnel-380174] [5.1] [localhost]:5801 is SHUTTING_DOWN
2024-07-02 17:16:54,585 INFO  [c.h.i.p.i.MigrationManager    ] [hz.main.cached.thread-7] - [localhost]:5801 [seatunnel-380174] [5.1] Shutdown request of Member [localhost]:5801 - 4da0e1bd-d8c1-4ed5-b4c4-d8b13faedb72 this is handled
2024-07-02 17:16:54,586 INFO  [c.h.i.i.Node                  ] [main] - [localhost]:5801 [seatunnel-380174] [5.1] Shutting down connection manager...
2024-07-02 17:16:54,587 INFO  [c.h.i.i.Node                  ] [main] - [localhost]:5801 [seatunnel-380174] [5.1] Shutting down node engine...
2024-07-02 17:16:54,589 INFO  [.c.c.DefaultClassLoaderService] [main] - close classloader service
2024-07-02 17:16:54,589 INFO  [o.a.s.e.s.TaskExecutionService] [event-forwarder-0] - [localhost]:5801 [seatunnel-380174] [5.1] Event forward thread interrupted
2024-07-02 17:16:57,593 INFO  [c.h.i.i.NodeExtension         ] [main] - [localhost]:5801 [seatunnel-380174] [5.1] Destroying node NodeExtension.
2024-07-02 17:16:57,595 INFO  [c.h.i.i.Node                  ] [main] - [localhost]:5801 [seatunnel-380174] [5.1] Hazelcast Shutdown is completed in 3010 ms.
2024-07-02 17:16:57,596 INFO  [c.h.c.LifecycleService        ] [main] - [localhost]:5801 [seatunnel-380174] [5.1] [localhost]:5801 is SHUTDOWN
2024-07-02 17:16:57,596 INFO  [s.c.s.s.c.ClientExecuteCommand] [main] - Closed HazelcastInstance ......
2024-07-02 17:16:57,596 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - 

===============================================================================


2024-07-02 17:16:57,596 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Fatal Error, 

2024-07-02 17:16:57,596 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Please submit bug report in https://github.com/apache/seatunnel/issues

2024-07-02 17:16:57,596 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Reason:SeaTunnel job executed failed 

2024-07-02 17:16:57,600 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:202)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.api.table.factory.FactoryException: ErrorCode:[API-06], ErrorDescription:[Factory initialize failed] - Unable to create a source for identifier 'Elasticsearch'.
	at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:100)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:332)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:188)
	at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.getLogicalDag(ClientJobExecutionEnvironment.java:88)
	at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.execute(ClientJobExecutionEnvironment.java:156)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:149)
	... 2 more
Caused by: org.apache.seatunnel.api.configuration.util.OptionValidationException: ErrorCode:[API-02], ErrorDescription:[Option item validate failed] - There are unconfigured options, these options('source', 'schema') are mutually exclusive, allowing only one set("[] for a set") of options to be configured.
	at org.apache.seatunnel.api.configuration.util.ConfigValidator.validate(ConfigValidator.java:178)
	at org.apache.seatunnel.api.configuration.util.ConfigValidator.validate(ConfigValidator.java:103)
	at org.apache.seatunnel.api.configuration.util.ConfigValidator.validate(ConfigValidator.java:47)
	at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:110)
	at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:73)
	... 7 more
 
2024-07-02 17:16:57,600 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - 
===============================================================================



Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:202)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.api.table.factory.FactoryException: ErrorCode:[API-06], ErrorDescription:[Factory initialize failed] - Unable to create a source for identifier 'Elasticsearch'.
	at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:100)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:332)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:188)
	at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.getLogicalDag(ClientJobExecutionEnvironment.java:88)
	at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.execute(ClientJobExecutionEnvironment.java:156)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:149)
	... 2 more
Caused by: org.apache.seatunnel.api.configuration.util.OptionValidationException: ErrorCode:[API-02], ErrorDescription:[Option item validate failed] - There are unconfigured options, these options('source', 'schema') are mutually exclusive, allowing only one set("[] for a set") of options to be configured.
	at org.apache.seatunnel.api.configuration.util.ConfigValidator.validate(ConfigValidator.java:178)
	at org.apache.seatunnel.api.configuration.util.ConfigValidator.validate(ConfigValidator.java:103)
	at org.apache.seatunnel.api.configuration.util.ConfigValidator.validate(ConfigValidator.java:47)
	at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:110)
	at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:73)
	... 7 more
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Wudadada** [comment]
Sorry, I mistakenly thought the two configuration sources were the same, but they do look quite similar and can be easily confused.
