### ISSUE TITLE
程序运行抛出异常，ErrorCode:[COMMON-01]

### ISSUE THREAD

**Issue by xinjingqing** [apache/seatunnel#7300]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

程序运行抛出异常

### SeaTunnel Version

2.3.3.

### SeaTunnel Config

```conf
env {
"job.mode"=BATCH
"job.name"="SeaTunnel_Job"
}
source {
Jdbc {
    "connection_check_timeout_sec"=30
    "fetch_size"=0
    parallelism=1
    "result_table_name"=Table14481818964320
    query="SELECT `id`, `test`, `test1`, `test2` FROM `gdm_v1.1`.`test_dh`"
    password=password
    url="jdbc:mysql://192.168.0.143:3306/gdm_v1.1?enabledTLSProtocols=TLSv1.2&rewriteBatchedStatements=true"
    driver="com.mysql.cj.jdbc.Driver"
    user=root
}
}
transform {
}
sink {
FtpFile {
    host = "192.168.0.212"
    port = 21
    user="ftpuser1"
    password = "Ab123456"
    path="/home/ftpuser1"
    file_format_type="text"
    field_delimiter="#"
    row_delimiter = "\n"
    custom_filename = true
    file_name_expression = "${transactionId}_${now}"
    filename_time_format = "yyyy.MM.dd"
    sink_columns = ["id","test","test1","test2"]
}
}
```

### Running Command

```shell
./bin/seatunnel.sh --config ./conf/toftp.conf -e local
```

### Error Exception

```log
Caused by: org.apache.seatunnel.connectors.seatunnel.file.exception.FileConnectorException: ErrorCode:[COMMON-01], ErrorDescription:[File operation failed, such as (read,list,write,move,copy,sync) etc...] - Write this data [SeaTunnelRow{tableId=, kind=+I, fields=[1, 2werwerwer, AA, sdf]}] to file failed
        at org.apache.seatunnel.connectors.seatunnel.file.sink.BaseFileSinkWriter.write(BaseFileSinkWriter.java:129)
        at org.apache.seatunnel.connectors.seatunnel.file.sink.BaseFileSinkWriter.write(BaseFileSinkWriter.java:43)
        at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:227)
        ... 15 more
Caused by: org.apache.seatunnel.connectors.seatunnel.file.exception.FileConnectorException: ErrorCode:[COMMON-01], ErrorDescription:[File operation failed, such as (read,list,write,move,copy,sync) etc...] - Open file output stream [/tmp/seatunnel/seatunnel/871723633897111553/b180230a3e/T_871723633897111553_b180230a3e_0_1/NON_PARTITION/T_871723633897111553_b180230a3e_0_1_2024.08.02_0.txt] failed
        at org.apache.seatunnel.connectors.seatunnel.file.sink.writer.TextWriteStrategy.getOrCreateOutputStream(TextWriteStrategy.java:152)
        at org.apache.seatunnel.connectors.seatunnel.file.sink.writer.TextWriteStrategy.write(TextWriteStrategy.java:81)
        at org.apache.seatunnel.connectors.seatunnel.file.sink.BaseFileSinkWriter.write(BaseFileSinkWriter.java:126)
        ... 17 more
Caused by: java.io.IOException: create(): Mkdirs failed to create: /tmp/seatunnel/seatunnel/871723633897111553/b180230a3e/T_871723633897111553_b180230a3e_0_1/NON_PARTITION
        at org.apache.seatunnel.connectors.seatunnel.file.ftp.system.SeaTunnelFTPFileSystem.create(SeaTunnelFTPFileSystem.java:260)
        at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1118)
        at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1098)
        at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1057)
        at org.apache.seatunnel.connectors.seatunnel.file.sink.util.FileSystemUtils.getOutputStream(FileSystemUtils.java:108)
        at org.apache.seatunnel.connectors.seatunnel.file.sink.writer.TextWriteStrategy.getOrCreateOutputStream(TextWriteStrategy.java:138)
        ... 19 more

        at org.apache.seatunnel.engine.client.job.ClientJobProxy.waitForJobComplete(ClientJobProxy.java:122)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:184)
        ... 2 more
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FLOWFOX** [comment]
Is there any progress?
