### ISSUE TITLE
[Bug] Mysql bug

### ISSUE THREAD

**Issue by panmyuan** [apache/seatunnel#7317]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

when mysql datebase contains '.', it happens. 
![image](https://github.com/user-attachments/assets/2f8a3c41-5dab-43f0-819f-9fb2dd16b7e6)

### SeaTunnel Version

2.3.5

### SeaTunnel Config

```conf
env {
  # You can set SeaTunnel environment configuration here
  parallelism = 1
  job.mode = "STREAMING"
  checkpoint.interval = 10000
}

# 配置数据源
source {
   MySQL-CDC {
     result_table_name = "scdata"
     # 数据库账号
     username = "root"
     password = "sss123"
     # 源表，格式：数据库名.表名
     table-names = ["xx.t_um_rec"]
     base-url = "jdbc:mysql://192.168.69.x:3307/xx"
   }
 }
 
 transform {
  Sql {
    source_table_name = "t_um_rec"
    result_table_name = "t_um_rec"
    query = "select * from t_um_rec"
  }
}
 
 # 配置目标库
 sink {
 
   jdbc {
     url = "jdbc:mysql://10.33.13x.x:3306/smart_assistant_1.3.0"
     driver = "com.mysql.cj.jdbc.Driver"
     user = "root"
     password = "nsss"
 
     generate_sink_sql = true
             # 目标数据库名
     database = "smart_assistant_1.3.0"
     # 目标表名
     table = "t_um_rec"
     # 主键名称
     primary_keys = ["id"]
     source_table_name = "xx"
   }
 }
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/my.config --async -n new_smartjob
```

### Error Exception

```log
org.apache.seatunnel.common.utils.SeaTunnelException: java.lang.IllegalArgumentException: Cannot get split 'smart_assistant_1.3.0.t_um_rec' to get databaseName and tableName
	at org.apache.seatunnel.api.table.catalog.TablePath.of(TablePath.java:59)
	at org.apache.seatunnel.api.table.catalog.TablePath.of(TablePath.java:40)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.JdbcOutputFormatBuilder.build(JdbcOutputFormatBuilder.java:63)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.sink.JdbcSinkWriter.<init>(JdbcSinkWriter.java:73)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.sink.JdbcSink.createWriter(JdbcSink.java:118)
	at org.apache.seatunnel.connectors.seatunnel.common.multitablesink.MultiTableSink.createWriter(MultiTableSink.java:70)
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.restoreState(SinkFlowLifeCycle.java:302)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTask.lambda$restoreState$16(SeaTunnelTask.java:425)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTask.restoreState(SeaTunnelTask.java:422)
	at org.apache.seatunnel.engine.server.checkpoint.operation.NotifyTaskRestoreOperation.lambda$null$0(NotifyTaskRestoreOperation.java:106)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

	at org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator.reportCheckpointErrorFromTask(CheckpointCoordinator.java:376) ~[seatunnel-starter.jar:2.3.5]
	at org.apache.seatunnel.engine.server.checkpoint.CheckpointManager.reportCheckpointErrorFromTask(CheckpointManager.java:183) ~[seatunnel-starter.jar:2.3.5]
	at org.apache.seatunnel.engine.server.checkpoint.operation.CheckpointErrorReportOperation.run(CheckpointErrorReportOperation.java:48) ~[seatunnel-starter.jar:2.3.5]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) ~[seatunnel-starter.jar:2.3.5]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:273) ~[seatunnel-starter.jar:2.3.5]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) ~[seatunnel-starter.jar:2.3.5]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213) ~[seatunnel-starter.jar:2.3.5]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:175) ~[seatunnel-starter.jar:2.3.5]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:139) ~[seatunnel-starter.jar:2.3.5]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) ~[seatunnel-starter.jar:2.3.5]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[seatunnel-starter.jar:2.3.5]
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lightzhao** [comment]
The database name should not contain "."
