### ISSUE TITLE
[Bug] [Hive Source] Invalid method name: 'get_table_req'

### ISSUE THREAD

**Issue by matianhe3** [apache/seatunnel#7330]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

update to 2.3.6 , hive source error.
2.3.5 ok.

### SeaTunnel Version

2.3.6

### SeaTunnel Config

```conf
source {
  Hive {
    table_name = ""
    metastore_uri = ""
    hdfs_site_path = "/opt/apache-seatunnel/config/hdfs-site.xml"
    hive_site_path = "/opt/apache-seatunnel/config/hive-site.xml"
    result_table_name = source
    read_partitions = ["dt="${dt}]
    delimiter = ","
  }
}
```

### Running Command

```shell
seatunnel.sh -c test.conf -i dt=2024-08-06
```

### Error Exception

```log
2024-08-07 11:10:59,057 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:211)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.api.table.factory.FactoryException: ErrorCode:[API-06], ErrorDescription:[Factory initialize failed] - Unable to create a source for identifier 'Hive'.
	at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:101)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:361)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:209)
	at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.getLogicalDag(ClientJobExecutionEnvironment.java:114)
	at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.execute(ClientJobExecutionEnvironment.java:182)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:158)
	... 2 more
Caused by: java.lang.NoSuchMethodError: 'void org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(org.apache.hadoop.conf.Configuration)'
	at org.apache.seatunnel.connectors.seatunnel.hive.utils.HiveMetaStoreProxy.<init>(HiveMetaStoreProxy.java:110)
	at org.apache.seatunnel.connectors.seatunnel.hive.utils.HiveMetaStoreProxy.getInstance(HiveMetaStoreProxy.java:139)
	at org.apache.seatunnel.connectors.seatunnel.hive.utils.HiveTableUtils.getTableInfo(HiveTableUtils.java:41)
	at org.apache.seatunnel.connectors.seatunnel.hive.source.config.HiveSourceConfig.<init>(HiveSourceConfig.java:84)
	at org.apache.seatunnel.connectors.seatunnel.hive.source.config.MultipleTableHiveSourceConfig.parseFromLocalFileSourceConfig(MultipleTableHiveSourceConfig.java:52)
	at org.apache.seatunnel.connectors.seatunnel.hive.source.config.MultipleTableHiveSourceConfig.<init>(MultipleTableHiveSourceConfig.java:39)
	at org.apache.seatunnel.connectors.seatunnel.hive.source.HiveSource.<init>(HiveSource.java:43)
	at org.apache.seatunnel.connectors.seatunnel.hive.source.HiveSourceFactory.lambda$createSource$0(HiveSourceFactory.java:46)
	at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:113)
	at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:74)
	... 7 more

2024-08-07 11:10:59,058 ERROR [o.a.s.c.s.SeaTunnel           ] [main] -
===============================================================================



Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:211)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.api.table.factory.FactoryException: ErrorCode:[API-06], ErrorDescription:[Factory initialize failed] - Unable to create a source for identifier 'Hive'.
	at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:101)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:361)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:209)
	at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.getLogicalDag(ClientJobExecutionEnvironment.java:114)
	at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.execute(ClientJobExecutionEnvironment.java:182)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:158)
	... 2 more
Caused by: java.lang.NoSuchMethodError: 'void org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(org.apache.hadoop.conf.Configuration)'
	at org.apache.seatunnel.connectors.seatunnel.hive.utils.HiveMetaStoreProxy.<init>(HiveMetaStoreProxy.java:110)
	at org.apache.seatunnel.connectors.seatunnel.hive.utils.HiveMetaStoreProxy.getInstance(HiveMetaStoreProxy.java:139)
	at org.apache.seatunnel.connectors.seatunnel.hive.utils.HiveTableUtils.getTableInfo(HiveTableUtils.java:41)
	at org.apache.seatunnel.connectors.seatunnel.hive.source.config.HiveSourceConfig.<init>(HiveSourceConfig.java:84)
	at org.apache.seatunnel.connectors.seatunnel.hive.source.config.MultipleTableHiveSourceConfig.parseFromLocalFileSourceConfig(MultipleTableHiveSourceConfig.java:52)
	at org.apache.seatunnel.connectors.seatunnel.hive.source.config.MultipleTableHiveSourceConfig.<init>(MultipleTableHiveSourceConfig.java:39)
	at org.apache.seatunnel.connectors.seatunnel.hive.source.HiveSource.<init>(HiveSource.java:43)
	at org.apache.seatunnel.connectors.seatunnel.hive.source.HiveSourceFactory.lambda$createSource$0(HiveSourceFactory.java:46)
	at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:113)
	at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:74)
	... 7 more
```

### Zeta or Flink or Spark Version

Zeta 2.3.6

### Java or Scala Version

java 17

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 2416210017** [comment]
I also reported the same error, have you found the reason?

```shell
24/08/09 11:57:35 INFO utils.HiveMetaStoreProxy: hive client conf:Configuration: core-default.xml, core-site.xml, mapred-default.xml, mapred-site.xml, yarn-default.xml, yarn-site.xml, hdfs-default.xml, hdfs-site.xml, org.apache.hadoop.hive.conf.LoopingByteArrayInputStream@3e1897d, file:/etc/hive/conf.cloudera.hive/hive-site.xml, file:/etc/hive/conf/hive-site.xml
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(Lorg/apache/hadoop/conf/Configuration;)V
        at org.apache.seatunnel.connectors.seatunnel.hive.utils.HiveMetaStoreProxy.<init>(HiveMetaStoreProxy.java:110)
        at org.apache.seatunnel.connectors.seatunnel.hive.utils.HiveMetaStoreProxy.getInstance(HiveMetaStoreProxy.java:139)
        at org.apache.seatunnel.connectors.seatunnel.hive.utils.HiveTableUtils.getTableInfo(HiveTableUtils.java:41)
        at org.apache.seatunnel.connectors.seatunnel.hive.sink.HiveSink.getTableInformation(HiveSink.java:235)
        at org.apache.seatunnel.connectors.seatunnel.hive.sink.HiveSink.<init>(HiveSink.java:85)
        at org.apache.seatunnel.connectors.seatunnel.hive.sink.HiveSinkFactory.lambda$createSink$0(HiveSinkFactory.java:61)
        at org.apache.seatunnel.core.starter.spark.execution.SinkExecuteProcessor.execute(SinkExecuteProcessor.java:140)
        at org.apache.seatunnel.core.starter.spark.execution.SparkExecution.execute(SparkExecution.java:71)
        at org.apache.seatunnel.core.starter.spark.command.SparkTaskExecuteCommand.execute(SparkTaskExecuteCommand.java:60)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.spark.SeaTunnelSpark.main(SeaTunnelSpark.java:35)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:955)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1043)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1052)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
````

**Comment by liunaijie** [comment]
hive version conflict.

in 2.3.6. upgrade hive from 2.3.9 to 3.1.3.

**Comment by matianhe3** [comment]
> hive version conflict.
> 
> in 2.3.6. upgrade hive from 2.3.9 to 3.1.3.

i must upgrade my hive? 
or only change hive-exec.jar ?

**Comment by liunaijie** [comment]
> > hive version conflict.
> > in 2.3.6. upgrade hive from 2.3.9 to 3.1.3.
> 
> i must upgrade my hive? or only change hive-exec.jar ?

just replace the hive related jar.

**Comment by 2416210017** [comment]
> > > hive version conflict.
> > > in 2.3.6. upgrade hive from 2.3.9 to 3.1.3.
> > 
> > 
> > i must upgrade my hive? or only change hive-exec.jar ?
> 
> just replace the hive related jar.

May I ask which path I need to replace the hive.jar package under?

**Comment by matianhe3** [comment]
> If you use SeaTunnel Engine, You need put seatunnel-hadoop3-3.1.4-uber.jar and hive-exec-3.1.3.jar and libfb303-0.9.3.jar in $SEATUNNEL_HOME/lib/ dir.

i follow the doc, put hive-exec-3.1.3.jar and libfb303-0.9.3.jar to /opt/seatunnel/lib , but can not work.

```

Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:211)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.api.table.factory.FactoryException: ErrorCode:[API-06], ErrorDescription:[Factory initialize failed] - Unable to create a source for identifier 'Hive'.
	at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:101)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:361)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:209)
	at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.getLogicalDag(ClientJobExecutionEnvironment.java:114)
	at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.execute(ClientJobExecutionEnvironment.java:182)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:158)
	... 2 more
Caused by: org.apache.seatunnel.connectors.seatunnel.hive.exception.HiveConnectorException: ErrorCode:[HIVE-03], ErrorDescription:[Get hive table information from hive metastore service failed] - Get table [bdm.b_tianrun_ibs] information failed
	at org.apache.seatunnel.connectors.seatunnel.hive.utils.HiveMetaStoreProxy.getTable(HiveMetaStoreProxy.java:152)
	at org.apache.seatunnel.connectors.seatunnel.hive.utils.HiveTableUtils.getTableInfo(HiveTableUtils.java:43)
	at org.apache.seatunnel.connectors.seatunnel.hive.source.config.HiveSourceConfig.<init>(HiveSourceConfig.java:84)
	at org.apache.seatunnel.connectors.seatunnel.hive.source.config.MultipleTableHiveSourceConfig.parseFromLocalFileSourceConfig(MultipleTableHiveSourceConfig.java:52)
	at org.apache.seatunnel.connectors.seatunnel.hive.source.config.MultipleTableHiveSourceConfig.<init>(MultipleTableHiveSourceConfig.java:39)
	at org.apache.seatunnel.connectors.seatunnel.hive.source.HiveSource.<init>(HiveSource.java:43)
	at org.apache.seatunnel.connectors.seatunnel.hive.source.HiveSourceFactory.lambda$createSource$0(HiveSourceFactory.java:46)
	at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:113)
	at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:74)
	... 7 more
Caused by: org.apache.thrift.TApplicationException: Invalid method name: 'get_table_req'
	at org.apache.thrift.TApplicationException.read(TApplicationException.java:111)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:79)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_get_table_req(ThriftHiveMetastore.java:2079)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.get_table_req(ThriftHiveMetastore.java:2066)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.getTable(HiveMetaStoreClient.java:1578)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.getTable(HiveMetaStoreClient.java:1570)
	at org.apache.seatunnel.connectors.seatunnel.hive.utils.HiveMetaStoreProxy.getTable(HiveMetaStoreProxy.java:148)
```

**Comment by matianhe3** [comment]
> > > hive version conflict.
> > > in 2.3.6. upgrade hive from 2.3.9 to 3.1.3.
> > 
> > 
> > i must upgrade my hive? or only change hive-exec.jar ?
> 
> just replace the hive related jar. 

> If you use SeaTunnel Engine, You need put seatunnel-hadoop3-3.1.4-uber.jar and hive-exec-3.1.3.jar and libfb303-0.9.3.jar in $SEATUNNEL_HOME/lib/ dir.

i follow the doc, put hive-exec-3.1.3.jar and libfb303-0.9.3.jar to /opt/seatunnel/lib , but can not work.

```

Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:211)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.api.table.factory.FactoryException: ErrorCode:[API-06], ErrorDescription:[Factory initialize failed] - Unable to create a source for identifier 'Hive'.
	at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:101)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:361)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:209)
	at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.getLogicalDag(ClientJobExecutionEnvironment.java:114)
	at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.execute(ClientJobExecutionEnvironment.java:182)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:158)
	... 2 more
Caused by: org.apache.seatunnel.connectors.seatunnel.hive.exception.HiveConnectorException: ErrorCode:[HIVE-03], ErrorDescription:[Get hive table information from hive metastore service failed] - Get table [bdm.b_tianrun_ibs] information failed
	at org.apache.seatunnel.connectors.seatunnel.hive.utils.HiveMetaStoreProxy.getTable(HiveMetaStoreProxy.java:152)
	at org.apache.seatunnel.connectors.seatunnel.hive.utils.HiveTableUtils.getTableInfo(HiveTableUtils.java:43)
	at org.apache.seatunnel.connectors.seatunnel.hive.source.config.HiveSourceConfig.<init>(HiveSourceConfig.java:84)
	at org.apache.seatunnel.connectors.seatunnel.hive.source.config.MultipleTableHiveSourceConfig.parseFromLocalFileSourceConfig(MultipleTableHiveSourceConfig.java:52)
	at org.apache.seatunnel.connectors.seatunnel.hive.source.config.MultipleTableHiveSourceConfig.<init>(MultipleTableHiveSourceConfig.java:39)
	at org.apache.seatunnel.connectors.seatunnel.hive.source.HiveSource.<init>(HiveSource.java:43)
	at org.apache.seatunnel.connectors.seatunnel.hive.source.HiveSourceFactory.lambda$createSource$0(HiveSourceFactory.java:46)
	at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:113)
	at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:74)
	... 7 more
Caused by: org.apache.thrift.TApplicationException: Invalid method name: 'get_table_req'
	at org.apache.thrift.TApplicationException.read(TApplicationException.java:111)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:79)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_get_table_req(ThriftHiveMetastore.java:2079)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.get_table_req(ThriftHiveMetastore.java:2066)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.getTable(HiveMetaStoreClient.java:1578)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.getTable(HiveMetaStoreClient.java:1570)
	at org.apache.seatunnel.connectors.seatunnel.hive.utils.HiveMetaStoreProxy.getTable(HiveMetaStoreProxy.java:148)
```

**Comment by matianhe3** [comment]
> > > hive version conflict.
> > > in 2.3.6. upgrade hive from 2.3.9 to 3.1.3.
> > 
> > 
> > i must upgrade my hive? or only change hive-exec.jar ?
> 
> just replace the hive related jar.

Hive 2.1.1-cdh6.2.1
Subversion file:///container.redhat7/build/cdh/hive/2.1.1-cdh6.2.1/rpm/BUILD/hive-2.1.1-cdh6.2.1 -r fc0582dc4d2e2342d1eef8cb702bad68e1e2cdd2

**Comment by liunaijie** [comment]
> > > > hive version conflict.
> > > > in 2.3.6. upgrade hive from 2.3.9 to 3.1.3.
> > > 
> > > 
> > > i must upgrade my hive? or only change hive-exec.jar ?
> > 
> > 
> > just replace the hive related jar.
> 
> Hive 2.1.1-cdh6.2.1 Subversion file:///container.redhat7/build/cdh/hive/2.1.1-cdh6.2.1/rpm/BUILD/hive-2.1.1-cdh6.2.1 -r fc0582dc4d2e2342d1eef8cb702bad68e1e2cdd2


`org.apache.thrift.TApplicationException: Invalid method name: 'get_table_req' ` 
This error means that you are using incompatible version of Hive metastore client to connect the Hive metastore server.


base on your describe, you can work well with seatunnel v.2.35. so you can copy the related hive lib from 2.3.5 to 2.3.6, and tst again.

**Comment by matianhe3** [comment]
> > > > > hive version conflict.
> > > > > in 2.3.6. upgrade hive from 2.3.9 to 3.1.3.
> > > > 
> > > > 
> > > > i must upgrade my hive? or only change hive-exec.jar ?
> > > 
> > > 
> > > just replace the hive related jar.
> > 
> > 
> > Hive 2.1.1-cdh6.2.1 Subversion file:///container.redhat7/build/cdh/hive/2.1.1-cdh6.2.1/rpm/BUILD/hive-2.1.1-cdh6.2.1 -r fc0582dc4d2e2342d1eef8cb702bad68e1e2cdd2
> 
> `org.apache.thrift.TApplicationException: Invalid method name: 'get_table_req' ` This error means that you are using incompatible version of Hive metastore client to connect the Hive metastore server.
> 
> base on your describe, you can work well with seatunnel v.2.35. so you can copy the related hive lib from 2.3.5 to 2.3.6, and tst again.

Seatunnel v2.3.5 lib is hive-exec-2.3.9.jar,  i use this have the first error. `Unable to create a source for identifier 'Hive'.`

**Comment by tiansww** [comment]
maybe you can copy the hive connector from 2.3.5 to 2.3.6

**Comment by 2416210017** [comment]
> maybe you can copy the hive connector from 2.3.5 to 2.3.6

May I ask which directory to copy to?

**Comment by matianhe3** [comment]
> maybe you can copy the hive connector from 2.3.5 to 2.3.6

i copy connectors/connector-hive-2.3.5.jar to connectors/connector-hive-2.3.6.jar 
```
Exception in thread "main" java.lang.NoSuchMethodError: 'void org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(org.apache.hadoop.hive.conf.HiveConf)'
	at org.apache.seatunnel.connectors.seatunnel.hive.utils.HiveMetaStoreProxy.<init>(HiveMetaStoreProxy.java:84)
	at org.apache.seatunnel.connectors.seatunnel.hive.utils.HiveMetaStoreProxy.getInstance(HiveMetaStoreProxy.java:113)
	at org.apache.seatunnel.connectors.seatunnel.hive.config.HiveConfig.getTableInfo(HiveConfig.java:73)
	at org.apache.seatunnel.connectors.seatunnel.hive.source.HiveSource.prepare(HiveSource.java:124)
	at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSource(JobConfigParser.java:83)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:356)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:209)
	at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.getLogicalDag(ClientJobExecutionEnvironment.java:114)
	at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.execute(ClientJobExecutionEnvironment.java:182)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:158)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
```

**Comment by uniding** [comment]
I also encountered the same error, the Hive version is 2.3.7

**Comment by woozhijun** [comment]
I also encountered the same error for 2.3.7

**Comment by shangeyao** [comment]
I also encountered the same error for 2.3.8

**Comment by 408639605** [comment]
Download the source code of the corresponding version of seatunnel and modify the hive.exec.version of the connector live package pom.xml file to your own version, and then package it

**Comment by 408639605** [comment]
Download the source code of the corresponding version of seatunnel and modify the <hive.exec.version> of the connector-hive package pom file to your own version, and then package it

**Comment by matianhe3** [comment]
> Download the source code of the corresponding version of seatunnel and modify the <hive.exec.version> of the connector-hive package pom file to your own version, and then package it

`mvn clean package -pl seatunnel-connectors-v2/connector-hive -am -DskipTests -T 1C`
and replace `connectors/` jar file , same error.

**Comment by 408639605** [comment]
> > Download the source code of the corresponding version of seatunnel and modify the <hive.exec.version> of the connector-hive package pom file to your own version, and then package it
> 
> `mvn clean package -pl seatunnel-connectors-v2/connector-hive -am -DskipTests -T 1C` and replace `connectors/` jar file , same error.

my hive varsion is 2.1.1-cdh6.2.0 , in lib add hive-exec-2.1.1-cdh6.2.0.jar  libfb303-093.jar ibthrift-0.12.0.jar seatunnel-hadoop3-3.1.4-uber.jar,Try switching to your version.

**Comment by 408639605** [comment]
> > Download the source code of the corresponding version of seatunnel and modify the <hive.exec.version> of the connector-hive package pom file to your own version, and then package it
> 
> `mvn clean package -pl seatunnel-connectors-v2/connector-hive -am -DskipTests -T 1C` and replace `connectors/` jar file , same error.

my hive varsion is 2.1.1-cdh6.2.0 , in lib add hive-exec-2.1.1-cdh6.2.0.jar libfb303-093.jar ibthrift-0.12.0.jar seatunnel-hadoop3-3.1.4-uber.jar,Try to your version.

**Comment by matianhe3** [comment]
> > > Download the source code of the corresponding version of seatunnel and modify the <hive.exec.version> of the connector-hive package pom file to your own version, and then package it
> > 
> > 
> > `mvn clean package -pl seatunnel-connectors-v2/connector-hive -am -DskipTests -T 1C` and replace `connectors/` jar file , same error.
> 
> my hive varsion is 2.1.1-cdh6.2.0 , in lib add hive-exec-2.1.1-cdh6.2.0.jar libfb303-093.jar ibthrift-0.12.0.jar seatunnel-hadoop3-3.1.4-uber.jar,Try to your version.

seatunnel version is latest 2.3.8?

**Comment by 408639605** [comment]
> > > > Download the source code of the corresponding version of seatunnel and modify the <hive.exec.version> of the connector-hive package pom file to your own version, and then package it
> > > 
> > > 
> > > `mvn clean package -pl seatunnel-connectors-v2/connector-hive -am -DskipTests -T 1C` and replace `connectors/` jar file , same error.
> > 
> > 
> > my hive varsion is 2.1.1-cdh6.2.0 , in lib add hive-exec-2.1.1-cdh6.2.0.jar libfb303-093.jar ibthrift-0.12.0.jar seatunnel-hadoop3-3.1.4-uber.jar,Try to your version.
> 
> seatunnel version is latest 2.3.8?

2.2.7

**Comment by 408639605** [comment]
> > > > Download the source code of the corresponding version of seatunnel and modify the <hive.exec.version> of the connector-hive package pom file to your own version, and then package it
> > > 
> > > 
> > > `mvn clean package -pl seatunnel-connectors-v2/connector-hive -am -DskipTests -T 1C` and replace `connectors/` jar file , same error.
> > 
> > 
> > my hive varsion is 2.1.1-cdh6.2.0 , in lib add hive-exec-2.1.1-cdh6.2.0.jar libfb303-093.jar ibthrift-0.12.0.jar seatunnel-hadoop3-3.1.4-uber.jar,Try to your version.
> 
> seatunnel version is latest 2.3.8?

2.3.7

**Comment by YuriyGavrilov** [comment]
> > > > > Download the source code of the corresponding version of seatunnel and modify the <hive.exec.version> of the connector-hive package pom file to your own version, and then package it
> 
> > > > 
> 
> > > > 
> 
> > > > `mvn clean package -pl seatunnel-connectors-v2/connector-hive -am -DskipTests -T 1C` and replace `connectors/` jar file , same error.
> 
> > > 
> 
> > > 
> 
> > > my hive varsion is 2.1.1-cdh6.2.0 , in lib add hive-exec-2.1.1-cdh6.2.0.jar libfb303-093.jar ibthrift-0.12.0.jar seatunnel-hadoop3-3.1.4-uber.jar,Try to your version.
> 
> > 
> 
> > seatunnel version is latest 2.3.8?
> 
> 
> 
> 2.3.7

Try 2.3.8

**Comment by YuriyGavrilov** [comment]
@408639605 you also could try new docker version it should be 2.3.8

**Comment by JunjianS** [comment]
I also encountered the same error for 2.3.9

**Comment by YuriyGavrilov** [comment]
@JunjianS did you try official docker or make build by self?

**Comment by JunjianS** [comment]
> docker

thank you for your reply,  but why need to try official docker or make build by self?

**Comment by YuriyGavrilov** [comment]
> > docker
> 
> thank you for your reply,  but why need to try official docker or make build by self? 

Just to test and avoid correct hdfs libs. I remember I spent much time to choose and add it correctly.

**Comment by matianhe3** [comment]
SOLVED.  
Build SeaTunnel From Source Code.

download `hive-exec-2.1.1-cdh6.2.1.jar` file from maven website and put it to dir: `seatunnel/lib`

> ALTER

`${SEATUNNEL_HOME}/seatunnel-connectors-v2/connector-hive/pom.xml` hive-exec.version to your hive version.

> LIKE: 

```
    <repositories>
        <repository>
            <id>cloudera</id>
            <url>https://repository.cloudera.com/artifactory/cloudera-repos/</url>
        </repository>
    </repositories>
    <properties>
        <hive.exec.version>2.1.1-cdh6.2.1</hive.exec.version>
        <connector.name>connector.hive</connector.name>
    </properties>
```
