### ISSUE TITLE
Unable to execute jdbc json config in version 2.3.4 which can be run on old version 2.3.3...Getting Failed to get driver instance

### ISSUE THREAD

**Issue by shrikhaparul** [apache/seatunnel#7395]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Am getting below error message
<img width="933" alt="image" src="https://github.com/user-attachments/assets/28fe1856-707f-414e-80e1-0c31e9477afe">

### SeaTunnel Version

Using in 2.3.3 version works fine...
getting error in 2.3.4 version

### SeaTunnel Config

```conf
Below is the json we are passing to seatunnel 
{
  "env": {
    "job.name": "test_beverage_upsert_test",
    "execution.parallelism": 2,
    "job.mode": "BATCH"
  },
  "source": [
    {
      "plugin_name": "S3File",
      "path": "/Excel_folder/files/test/test_beverage.csv",
      "file_format_type": "csv",
      "bucket": "",
      "fs.s3a.endpoint": "",
      "fs.s3a.aws.credentials.provider": "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider",
      "access_key": "",
      "secret_key": "",
      "skip_header_row_number": "0",
      "schema": {
        "fields": {
          "region": "string",
          "country": "string",
          "item_type": "string",
          "sales_channel": "string",
          "order_priority": "string",
          "orderdate": "string",
          "orderid": "string",
          "shipdate": "string",
          "unitsold": "string",
          "unitprice": "string",
          "unitcost": "string",
          "totalrevenue": "string",
          "totalcost": "string",
          "totalprofit": "string",
          "id": "string"
        }
      },
      "batchsize": 10000
    }
  ],
  "sink": [
    {
      "plugin_name": "Jdbc",
      "url": "jdbc:postgresql://localhost:5432/postgres",
      "driver": "org.postgresql.Driver",
      "user": "postgres",
      "password": "root",
      "database": "postgres2",
      "table": "public.test_beverage_upsert_test",
      "batch_size": 100000,
      "support_upsert_by_query_primary_key_exist": "true",
      "primary_keys": "id",
      "generate_sink_sql": "true"
    }
  ]
}
```

### Running Command

```shell
/home/apache-seatunnel-2.3.4/bin/seatunnel.sh  --config /home/scripts/seatunnel//ora_test_beverage_upsert_test.json
```

### Error Exception

```log
Caused by: java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:postgresql://localhost:5432/postgres
        at org.apache.seatunnel.shade.com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:114)
        at org.apache.seatunnel.shade.com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:331)
        at org.apache.seatunnel.shade.com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:114)
        at org.apache.seatunnel.shade.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:108)
        at org.apache.seatunnel.shade.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.sink.ConnectionPoolManager.lambda$getConnection$0(ConnectionPoolManager.java:45)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.sink.ConnectionPoolManager.getConnection(ConnectionPoolManager.java:41)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.connection.SimpleJdbcConnectionPoolProviderProxy.getOrEstablishConnection(SimpleJdbcConnectionPoolProviderProxy.java:57)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.JdbcOutputFormat.open(JdbcOutputFormat.java:67)
        ... 9 more
Caused by: java.sql.SQLException: No suitable driver
        at java.sql/java.sql.DriverManager.getDriver(DriverManager.java:298)
        at org.apache.seatunnel.shade.com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:106)
        ... 18 more

        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:191)
        ... 2 more
2024-08-13 22:59:08,948 INFO  [s.c.s.s.c.ClientExecuteCommand] [ForkJoinPool.commonPool-worker-5] - run shutdown hook because get close signal
```

### Zeta or Flink or Spark Version

zeta version

### Java or Scala Version

java

### Screenshots

<img width="947" alt="image" src="https://github.com/user-attachments/assets/bd8f9a56-9e12-4d2d-95ac-23791ef5ed73">

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by shrikhaparul** [comment]
IS this a bug....or am I doing something wrong
