### ISSUE TITLE
[Bug] [Seatunnel-web] Validation messages are wrong

### ISSUE THREAD

**Issue by arshadmohammad** [apache/seatunnel#7408]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

In seatunnel-web input validation message are wrong. For example duplicate  datasoruce followign message is displayed.
"datasource [datasource [mysql_db-1] already exists] already exists"
Looks like message template is processed incorrectly. Same is the case with other input validaiton messages as well.

Also there is anothe problem for these known validation error message is logged. For duplicate name follwoing stack trace is getting logged.
`2024-08-15 00:38:21.284 seatunnel host1 ERROR [qtp1500821480-73] [GlobalExceptionHandler.logError():84] - datasource [mysql_db-1] already exists
org.apache.seatunnel.server.common.SeatunnelException: datasource [mysql_db-1] already exists
        at org.apache.seatunnel.app.service.impl.DatasourceServiceImpl.createDatasource(DatasourceServiceImpl.java:109)
        at org.apache.seatunnel.app.controller.SeatunnelDatasourceController.createDatasource(SeatunnelDatasourceController.java:121)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)`

### SeaTunnel Version

seatunnel-web version 1.0.1

### SeaTunnel Config

```conf
NA
```

### Running Command

```shell
NA
```

### Error Exception

```log
2024-08-15 00:38:21.284 seatunnel rocky1 ERROR [qtp1500821480-73] [GlobalExceptionHandler.logError():84] - datasource [mysql_db-1] already exists
org.apache.seatunnel.server.common.SeatunnelException: datasource [mysql_db-1] already exists
        at org.apache.seatunnel.app.service.impl.DatasourceServiceImpl.createDatasource(DatasourceServiceImpl.java:109)
        at org.apache.seatunnel.app.controller.SeatunnelDatasourceController.createDatasource(SeatunnelDatasourceController.java:121)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

### Screenshots

![Screenshot from 2024-08-15 00-34-15](https://github.com/user-attachments/assets/841f16df-3596-431e-8b9f-ea5cdf113dc4)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by arshadmohammad** [comment]
Raised PR https://github.com/apache/seatunnel-web/pull/186

**Comment by arshadmohammad** [comment]
PR is merged https://github.com/apache/seatunnel-web/commit/f987ff385d8fe8c00a3e7631c93823e13ebfbd82
