### ISSUE TITLE
MySQL8.4  SHOW MASTER STATUS无法使用

### ISSUE THREAD

**Issue by lilanlong** [apache/seatunnel#7416]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

MySQL8.4版本  SHOW MASTER STATUS  语句已经不能使用，换成了  SHOW BINARY LOGS  SHOW BINARY LOG STATUS

### SeaTunnel Version

2.3.6

### SeaTunnel Config

```conf
MySQL8.4版本  SHOW MASTER STATUS  语句已经不能使用，换成了  SHOW BINARY LOGS  SHOW BINARY LOG STATUS
```

### Running Command

```shell
MySQL8.4版本  SHOW MASTER STATUS  语句已经不能使用，换成了  SHOW BINARY LOGS  SHOW BINARY LOG STATUS
```

### Error Exception

```log
MySQL8.4版本  SHOW MASTER STATUS  语句已经不能使用，换成了  SHOW BINARY LOGS  SHOW BINARY LOG STATUS
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhilinli123** [comment]
It can be assigned to me for the time being!

**Comment by lihm659156** [comment]
I also encountered the same problem

**Comment by lihm659156** [comment]
org.apache.seatunnel.common.utils.SeaTunnelException: Cannot read the binlog filename and position via 'SHOW MASTER STATUS'. Make sure your server is correctly configured
        at org.apache.seatunnel.connectors.seatunnel.cdc.mysql.utils.MySqlConnectionUtils.getBinlogOffset(MySqlConnectionUtils.java:121)
        at org.apache.seatunnel.connectors.seatunnel.cdc.mysql.utils.MySqlConnectionUtils.currentBinlogOffset(MySqlConnectionUtils.java:100)
        at org.apache.seatunnel.connectors.seatunnel.cdc.mysql.source.reader.fetch.scan.MySqlSnapshotSplitReadTask.doExecute(MySqlSnapshotSplitReadTask.java:137)
        at org.apache.seatunnel.connectors.seatunnel.cdc.mysql.source.reader.fetch.scan.MySqlSnapshotSplitReadTask.execute(MySqlSnapshotSplitReadTask.java:117)
        ... 7 more
