### ISSUE TITLE
[Bug] [source elasticsearch] The 'source' field is mandatory

### ISSUE THREAD

**Issue by zhdech** [apache/seatunnel#7420]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When reading data from 'elasticsearch' and filling in the required fields according to the official documentation of seatunnel, it cannot run and prompts that the 'source' field cannot be found

<img width="784" alt="1" src="https://github.com/user-attachments/assets/e297289d-cbc2-4f48-bfa3-5b9fab1bac4d">
<img width="771" alt="2" src="https://github.com/user-attachments/assets/de587155-56fe-426b-9c2c-806c44cfa3ce">
![3](https://github.com/user-attachments/assets/85407459-1ec3-402c-ab93-6142c5bfda21)

### SeaTunnel Version

2.3.6

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
  job.mode = "BATCH"
  checkpoint.interval = 10000
}

source {
  Elasticsearch {
    hosts = ["localhost:9200"]
    index = "seatunnel-20230815"
    result_table_name = "es_qm_data"
  }
}

sink {
  Console {
    }
  }
}
```

### Running Command

```shell
./bin/seatunnel.sh --config ./config/es_2_console.conf -e local
```

### Error Exception

```log
Exception in thread "main"org.apache.seatunnel.core.starter.exception.CommandExecuteException:SeaTunnel job executed failed
at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(clientExecuteCommand.java:188)
at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelclient.main(SeaTunnelclient.java:34)
Caused by:org.apache.seatunnel.shade.com.typesafe.config.ConfigException$Missing:No configuration setting found for key 'source
at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.findKeyorNull(SimpleConfig.java:156)
at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.findorNull(SimpleConfig.java:174)
at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.getList(SimpleConfig.java:262)
at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.getHomogeneousUnwrappedList(SimpleConfig.java:348)
at org.apache.seatunnel.shade.com.typesafe.config.impl.SimpleConfig.getstringList(SimpleConfig.java:406)
at org.apache.seatunnel.connectors.seatunnel.elasticsearch.source.ElasticsearchSource.prepare(ElasticsearchSource.java:69)
at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSource(JobConfigParser.java:81)
at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:298)
at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:159)
at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.getLogicalDag(JobExecutionEnvironment.java:155)
at org.apache.seatunnel.engine.client.job.JobExecutionEnvironment.execute(JobExecutionEnvironment.java:147)
at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(clientExecuteCommand.java:140)
..2 more
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
I believe your connector version isn't 2.3.6. It already fixed in https://github.com/apache/seatunnel/pull/6181 which released in 2.3.4.
