### ISSUE TITLE
[Bug] [Seatunnel-web] GET /seatunnel/api/v1/job/definition fails when job mode is passed

### ISSUE THREAD

**Issue by arshadmohammad** [apache/seatunnel#7543]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

GET /seatunnel/api/v1/job/definition fails when job mode is passed
Seems query in org/apache/seatunnel/app/dal/mapper/JobMapper.xml is not formed correctly when mode is passed

### SeaTunnel Version

2.3.7

### SeaTunnel Config

```conf
NA
```

### Running Command

```shell
NA
```

### Error Exception

```log
2024-09-01 19:22:38.577 seatunnel vm1 ERROR [tr:,sp:] [qtp141601266-87] [GlobalExceptionHandler.logError():78] - 
### Error querying database.  Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'name' in where clause is ambiguous
### The error may exist in org/apache/seatunnel/app/dal/mapper/JobMapper.xml
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: select t.*     from t_st_job_definition t     join (select * from t_st_job_version where job_mode = ?) v on t.id = v.job_id      WHERE  name LIKE concat('%', ?, '%')      order by update_time desc
### Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'name' in where clause is ambiguous
; Column 'name' in where clause is ambiguous; nested exception is java.sql.SQLIntegrityConstraintViolationException: Column 'name' in where clause is ambiguous
org.springframework.dao.DataIntegrityViolationException: 
### Error querying database.  Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'name' in where clause is ambiguous
### The error may exist in org/apache/seatunnel/app/dal/mapper/JobMapper.xml
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: select t.*     from t_st_job_definition t     join (select * from t_st_job_version where job_mode = ?) v on t.id = v.job_id      WHERE  name LIKE concat('%', ?, '%')      order by update_time desc
### Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'name' in where clause is ambiguous
; Column 'name' in where clause is ambiguous; nested exception is java.sql.SQLIntegrityConstraintViolationException: Column 'name' in where clause is ambiguous
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:87)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:79)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:91)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
	at jdk.proxy2/jdk.proxy2.$Proxy92.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:224)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForIPage(MybatisMapperMethod.java:121)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:85)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:89)
	at jdk.proxy2/jdk.proxy2.$Proxy111.queryJobListPagingWithJobMode(Unknown Source)
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by arshadmohammad** [comment]
Raised PR https://github.com/apache/seatunnel-web/pull/201
