### ISSUE TITLE
[Bug] [Flink] Failed start flink task

### ISSUE THREAD

**Issue by hanhanzhang** [apache/seatunnel#7566]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When deploying flink task in run-application mode,  config file not found.

### SeaTunnel Version

2.3.7

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
  job.mode = "BATCH"
  checkpoint.interval = 10000
}

source {
  Jdbc {
        url = "jdbc:postgresql:/localhost/:5866/dolphinscheduler"
        driver = "org.postgresql.Driver"
        user = "root"
        password = "root"
        query = "select * from t_ds_process_instance"
    }
}

sink {
  Console {
  }
}
```

### Running Command

```shell
${FLINK_HOME}/bin/flink run-application --target yarn-application --yarnqueue root.users.datacube_test --yarnjobManagerMemory 1024 --yarntaskManagerMemory 1024 -c org.apache.seatunnel.core.starter.flink.SeaTunnelFlink /usr/seatunnel/2.3.7/starter/seatunnel-flink-15-starter.jar --config /data/dolphinScheduler/exec/process/video/118325094409344/118678805354560_9/47/83/seatunnel_47_83.conf --name SeaTunnel
```

### Error Exception

```log
2024-09-04 09:27:44,885 ERROR org.apache.seatunnel.core.starter.SeaTunnel                  [] - Fatal Error, 

2024-09-04 09:27:44,885 ERROR org.apache.seatunnel.core.starter.SeaTunnel                  [] - Please submit bug report in https://github.com/apache/seatunnel/issues

2024-09-04 09:27:44,885 ERROR org.apache.seatunnel.core.starter.SeaTunnel                  [] - Reason:ErrorCode:[COMMON-22], ErrorDescription:[SeaTunnel read file '/data/dolphinScheduler/exec/process/video/118325094409344/118678805354560_9/47/83/seatunnel_47_83.conf' failed, because it not existed.] 

2024-09-04 09:27:44,887 ERROR org.apache.seatunnel.core.starter.SeaTunnel                  [] - Exception StackTrace:org.apache.seatunnel.common.exception.SeaTunnelRuntimeException: ErrorCode:[COMMON-22], ErrorDescription:[SeaTunnel read file '/data/dolphinScheduler/exec/process/video/118325094409344/118678805354560_9/47/83/seatunnel_47_83.conf' failed, because it not existed.]
	at org.apache.seatunnel.common.exception.CommonError.fileNotExistFailed(CommonError.java:86)
	at org.apache.seatunnel.core.starter.utils.FileUtils.checkConfigExist(FileUtils.java:66)
	at org.apache.seatunnel.core.starter.flink.command.FlinkTaskExecuteCommand.execute(FlinkTaskExecuteCommand.java:50)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.flink.SeaTunnelFlink.main(SeaTunnelFlink.java:34)
```

### Zeta or Flink or Spark Version

flink 1.15.3

### Java or Scala Version

java 8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
duplicated with https://github.com/apache/seatunnel/issues/7321
