### ISSUE TITLE
[Bug] [seatunnel-hadoop3-3.1.4-uber] This jar package is not up to date

### ISSUE THREAD

**Issue by FLOWFOX** [apache/seatunnel#7588]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

The binary package I downloaded from the official website is not up to date [seatunnel-hadoop3-3.1.4-uber.jar]

### SeaTunnel Version

2.3.7

### SeaTunnel Config

```conf
# Defining the runtime environment
env {
  parallelism = 1
  job.mode = "BATCH"
}

source {
  # This is a example source plugin **only for test and demonstrate the feature source plugin**
   FtpFile {
   result_table_name = "fake"
    host = "172.17.0.2"
    port = 21
    user = "ftpuser"
    password = "ftpuser"
    path = "/data/ftp/2.json"
    file_format_type = "json"
    schema = {
      fields {
        name = string
        age = tinyint
      }
    }
  }
  # If you would like to get more information about how to configure seatunnel and see full list of source plugins,
  # please go to https://seatunnel.apache.org/docs/category/source-v2
}

transform {
  # If you would like to get more information about how to configure seatunnel and see full list of transform plugins,
    # please go to https://seatunnel.apache.org/docs/category/transform-v2
}

sink {
    console{
    source_table_name = "fake"
    }
     S3File {
     source_table_name = "fake"
    bucket = "s3a://test"
    tmp_path = "/seatunnel"
    path="/seatunnel"
    fs.s3a.endpoint="http://192.168.1.12:49000"
    fs.s3a.aws.credentials.provider="org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
    access_key = "minioadmin"
    secret_key = "minioadmin"
    file_format_type = "json"
    hadoop_s3_properties {
      "fs.s3a.buffer.dir" = "/home/hadoop"
      "fs.s3a.fast.upload.buffer" = "disk"
    }
  }
  # If you would like to get more information about how to configure seatunnel and see full list of sink plugins,
  # please go to https://seatunnel.apache.org/docs/category/sink-v2
}
```

### Running Command

```shell
../bin/seatunnel.sh -c s3.conf
```

### Error Exception

```log
Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:211)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NoSuchMethodError: org.apache.hadoop.util.SemaphoredDelegatingExecutor.<init>(Lcom/google/common/util/concurrent/ListeningExecutorService;IZ)V
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:292)
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:74)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:39)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:27)
	at org.apache.seatunnel.engine.server.task.group.queue.IntermediateBlockingQueue.handleRecord(IntermediateBlockingQueue.java:75)
	at org.apache.seatunnel.engine.server.task.group.queue.IntermediateBlockingQueue.collect(IntermediateBlockingQueue.java:50)
	at org.apache.seatunnel.engine.server.task.flow.IntermediateQueueFlowLifeCycle.collect(IntermediateQueueFlowLifeCycle.java:51)
	at org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask.collect(TransformSeaTunnelTask.java:73)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTask.stateProcess(SeaTunnelTask.java:168)
	at org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask.call(TransformSeaTunnelTask.java:78)
	at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:717)
	at org.apache.seatunnel.engine.server.TaskExecutionService$NamedTaskWrapper.run(TaskExecutionService.java:1039)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodError: org.apache.hadoop.util.SemaphoredDelegatingExecutor.<init>(Lcom/google/common/util/concurrent/ListeningExecutorService;IZ)V
	at org.apache.seatunnel.api.sink.multitablesink.MultiTableSinkWriter.subSinkErrorCheck(MultiTableSinkWriter.java:121)
	at org.apache.seatunnel.api.sink.multitablesink.MultiTableSinkWriter.write(MultiTableSinkWriter.java:158)
	at org.apache.seatunnel.api.sink.multitablesink.MultiTableSinkWriter.write(MultiTableSinkWriter.java:43)
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:269)
	... 16 more
Caused by: java.lang.NoSuchMethodError: org.apache.hadoop.util.SemaphoredDelegatingExecutor.<init>(Lcom/google/common/util/concurrent/ListeningExecutorService;IZ)V
	at org.apache.hadoop.fs.s3a.S3AFileSystem.create(S3AFileSystem.java:769)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1118)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1098)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:987)
	at org.apache.seatunnel.connectors.seatunnel.file.hadoop.HadoopFileSystemProxy.getOutputStream(HadoopFileSystemProxy.java:162)
	at org.apache.seatunnel.connectors.seatunnel.file.sink.writer.JsonWriteStrategy.getOrCreateOutputStream(JsonWriteStrategy.java:125)
	at org.apache.seatunnel.connectors.seatunnel.file.sink.writer.JsonWriteStrategy.write(JsonWriteStrategy.java:69)
	at org.apache.seatunnel.connectors.seatunnel.file.sink.BaseFileSinkWriter.write(BaseFileSinkWriter.java:134)
	at org.apache.seatunnel.connectors.seatunnel.file.sink.BaseFileSinkWriter.write(BaseFileSinkWriter.java:46)
	at org.apache.seatunnel.api.sink.multitablesink.MultiTableWriterRunnable.run(MultiTableWriterRunnable.java:62)
	... 5 more

	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:203)
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FLOWFOX** [comment]
downloading the source code and recompiling it will solve this problem

**Comment by YuriyGavrilov** [comment]
same issue with writing iceberg on s3. @FLOWFOX what should be recompiled? 


```

sink {
  iceberg {
    catalog_name = "iceberg"
    iceberg.catalog.config={
      "type"="hive"
      "uri" = "thrift://10.89.0.5:9083"
      "warehouse"="s3a://test/iceberg_p_listner5_podman/"
    }
    hadoop.config={
      "fs.s3a.aws.credentials.provider" = "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
      "fs.s3a.endpoint" = "gateway.XXXX.io"
      "fs.s3a.access.key" = "jv4gXXXXXyg22hqxq"
      "fs.s3a.secret.key" = "j324fXXXXuvjlm3nu"
      "fs.defaultFS" = "s3a://test/iceberg_p_listner5_podman/"
      "fs.s3a.impl"="org.apache.hadoop.fs.s3a.S3AFileSystem"
    }
    namespace = "my_schema_i"
    table = "test_table2"
    iceberg.table.write-props={
      write.format.default="parquet"
      write.target-file-size-bytes=536870
    }
    iceberg.table.primary-keys="id"
    iceberg.table.upsert-mode-enabled=true
    iceberg.table.schema-evolution-enabled=true
    result_table_name = "test_table"
 }
}

```


but this is working example for reading iceberg 

```
source {
  iceberg {
    catalog_name = "iceberg"
    iceberg.catalog.config={
      "type"="hive"
      "uri" = "thrift://10.89.0.5:9083"
      "warehouse"="s3a://test/iceberg_p_listner5_podman/"
    }
    hadoop.config={
      "fs.s3a.aws.credentials.provider" = "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
      "fs.s3a.endpoint" = "gateway.XXXXX.io"
      "fs.s3a.access.key" = "jv4XXXXX
      "fs.s3a.secret.key" = "j324XXXXX3nu"
      "fs.defaultFS" = "s3a://test/iceberg_p_listner5_podman/"
    }
    namespace = "my_schema_i"
    table = "orders"
   # result_table_name = "iceberg_test"
  }
}

```

error:
```

2024-09-09 22:53:10,082 INFO  [o.a.i.BaseMetastoreCatalog    ] [hz.main.seaTunnel.task.thread-5] - Table loaded by catalog: iceberg.my_schema_i.test_table4
2024-09-09 22:53:10,269 INFO  [o.a.h.i.c.CodecPool           ] [hz.main.seaTunnel.task.thread-5] - Got brand-new compressor [.snappy]
2024-09-09 22:53:10,537 INFO  [o.a.h.i.c.CodecPool           ] [hz.main.seaTunnel.task.thread-5] - Got brand-new compressor [.snappy]
2024-09-09 22:53:10,545 INFO  [a.s.a.s.m.MultiTableSinkWriter] [hz.main.seaTunnel.task.thread-5] - init multi table sink writer, queue size: 1
2024-09-09 22:53:10,604 INFO  [.s.e.s.c.CheckpointCoordinator] [seatunnel-coordinator-service-1] - checkpoint is enabled, start schedule trigger pending checkpoint.
2024-09-09 22:53:10,635 INFO  [o.a.s.c.s.f.s.FakeSourceReader] [BlockingWorker-TaskGroupLocation{jobId=885659105019035649, pipelineId=1, taskGroupId=50000}] - wait split!
2024-09-09 22:53:10,697 INFO  [.s.t.SourceSplitEnumeratorTask] [BlockingWorker-TaskGroupLocation{jobId=885659105019035649, pipelineId=1, taskGroupId=1}] - received enough reader, starting enumerator...
2024-09-09 22:53:10,697 INFO  [.f.s.FakeSourceSplitEnumerator] [BlockingWorker-TaskGroupLocation{jobId=885659105019035649, pipelineId=1, taskGroupId=1}] - Starting to calculate splits.
2024-09-09 22:53:10,697 INFO  [o.a.s.a.e.LoggingEventHandler ] [hz.main.generic-operation.thread-27] - log event: EnumeratorOpenEvent(createdTime=1725922390696, jobId=885659105019035649, eventType=LIFECYCLE_ENUMERATOR_OPEN)
2024-09-09 22:53:10,698 INFO  [.f.s.FakeSourceSplitEnumerator] [BlockingWorker-TaskGroupLocation{jobId=885659105019035649, pipelineId=1, taskGroupId=1}] - Calculated splits for table default.default.default successfully, the size of splits is 1.
2024-09-09 22:53:10,699 INFO  [.f.s.FakeSourceSplitEnumerator] [BlockingWorker-TaskGroupLocation{jobId=885659105019035649, pipelineId=1, taskGroupId=1}] - Assigned [FakeSourceSplit(tableId=default.default.default, splitId=0, rowNum=6)] to 1 readers.
2024-09-09 22:53:10,699 INFO  [.f.s.FakeSourceSplitEnumerator] [BlockingWorker-TaskGroupLocation{jobId=885659105019035649, pipelineId=1, taskGroupId=1}] - Calculated splits successfully, the size of splits is 1.
2024-09-09 22:53:10,700 INFO  [.f.s.FakeSourceSplitEnumerator] [BlockingWorker-TaskGroupLocation{jobId=885659105019035649, pipelineId=1, taskGroupId=1}] - Assigning splits to readers 0 [FakeSourceSplit(tableId=default.default.default, splitId=0, rowNum=6)]
2024-09-09 22:53:11,643 INFO  [o.a.s.c.s.f.s.FakeSourceReader] [BlockingWorker-TaskGroupLocation{jobId=885659105019035649, pipelineId=1, taskGroupId=50000}] - 6 rows of data have been generated in split(default.default.default_0) for table default.default.default. Generation time: 1725922391636
2024-09-09 22:53:15,629 INFO  [.s.e.s.c.CheckpointCoordinator] [seatunnel-coordinator-service-2] - wait checkpoint completed: 1
2024-09-09 22:53:16,086 WARN  [o.a.s.e.s.TaskExecutionService] [BlockingWorker-TaskGroupLocation{jobId=885659105019035649, pipelineId=1, taskGroupId=50000}] - [localhost]:5801 [seatunnel-307604] [5.1] Exception in org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask@36dbc0a
java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.apache.hadoop.util.SemaphoredDelegatingExecutor.<init>(Ljava/util/concurrent/ExecutorService;IZ)V
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:292) ~[seatunnel-starter.jar:2.3.7]
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:74) ~[seatunnel-starter.jar:2.3.7]
	at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:39) ~[seatunnel-starter.jar:2.3.7]
	at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:27) ~[seatunnel-starter.jar:2.3.7]
	at org.apache.seatunnel.engine.server.task.group.queue.IntermediateBlockingQueue.handleRecord(IntermediateBlockingQueue.java:70) ~[seatunnel-starter.jar:2.3.7]
	at org.apache.seatunnel.engine.server.task.group.queue.IntermediateBlockingQueue.collect(IntermediateBlockingQueue.java:50) ~[seatunnel-starter.jar:2.3.7]
	at org.apache.seatunnel.engine.server.task.flow.IntermediateQueueFlowLifeCycle.collect(IntermediateQueueFlowLifeCycle.java:51) ~[seatunnel-starter.jar:2.3.7]
	at org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask.collect(TransformSeaTunnelTask.java:73) ~[seatunnel-starter.jar:2.3.7]
	at org.apache.seatunnel.engine.server.task.SeaTunnelTask.stateProcess(SeaTunnelTask.java:168) ~[seatunnel-starter.jar:2.3.7]
	at org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask.call(TransformSeaTunnelTask.java:78) ~[seatunnel-starter.jar:2.3.7]
	at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:717) [seatunnel-starter.jar:2.3.7]
	at org.apache.seatunnel.engine.server.TaskExecutionService$NamedTaskWrapper.run(TaskExecutionService.java:1039) [seatunnel-starter.jar:2.3.7]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_422]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_422]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_422]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_422]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_422]
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.apache.hadoop.util.SemaphoredDelegatingExecutor.<init>(Ljava/util/concurrent/ExecutorService;IZ)V
	at org.apache.seatunnel.api.sink.multitablesink.MultiTableSinkWriter.prepareCommit(MultiTableSinkWriter.java:234) ~[seatunnel-starter.jar:2.3.7]
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:208) ~[seatunnel-starter.jar:2.3.7]
	... 16 more
Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.apache.hadoop.util.SemaphoredDelegatingExecutor.<init>(Ljava/util/concurrent/ExecutorService;IZ)V
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_422]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_422]
	at org.apache.seatunnel.api.sink.multitablesink.MultiTableSinkWriter.prepareCommit(MultiTableSinkWriter.java:232) ~[seatunnel-starter.jar:2.3.7]
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:208) ~[seatunnel-starter.jar:2.3.7]
	... 16 more
Caused by: java.lang.NoSuchMethodError: org.apache.hadoop.util.SemaphoredDelegatingExecutor.<init>(Ljava/util/concurrent/ExecutorService;IZ)V
	at org.apache.hadoop.fs.s3a.S3AFileSystem.create(S3AFileSystem.java:824) ~[hadoop-aws-3.2.4.jar:?]
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1118) ~[seatunnel-hadoop3-3.1.4-uber-2.3.1-optional.jar:2.3.1]
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:1098) ~[seatunnel-hadoop3-3.1.4-uber-2.3.1-optional.jar:2.3.1]
	at org.apache.seatunnel.shade.connector-iceberg.org.apache.parquet.hadoop.util.HadoopOutputFile.createOrOverwrite(HadoopOutputFile.java:81) ~[connector-iceberg-2.3.7.jar:2.3.7]
	at org.apache.seatunnel.shade.connector-iceberg.org.apache.parquet.hadoop.ParquetFileWriter.<init>(ParquetFileWriter.java:345) ~[connector-iceberg-2.3.7.jar:2.3.7]
	at org.apache.seatunnel.shade.connector-iceberg.org.apache.parquet.hadoop.ParquetFileWriter.<init>(ParquetFileWriter.java:323) ~[connector-iceberg-2.3.7.jar:2.3.7]
	at org.apache.iceberg.parquet.ParquetWriter.ensureWriterInitialized(ParquetWriter.java:111) ~[connector-iceberg-2.3.7.jar:2.3.7]
	at org.apache.iceberg.parquet.ParquetWriter.flushRowGroup(ParquetWriter.java:210) ~[connector-iceberg-2.3.7.jar:2.3.7]
	at org.apache.iceberg.parquet.ParquetWriter.close(ParquetWriter.java:254) ~[connector-iceberg-2.3.7.jar:2.3.7]
	at org.apache.iceberg.io.DataWriter.close(DataWriter.java:82) ~[connector-iceberg-2.3.7.jar:2.3.7]
	at org.apache.iceberg.io.BaseTaskWriter$BaseRollingWriter.closeCurrent(BaseTaskWriter.java:314) ~[connector-iceberg-2.3.7.jar:2.3.7]
	at org.apache.iceberg.io.BaseTaskWriter$BaseRollingWriter.close(BaseTaskWriter.java:341) ~[connector-iceberg-2.3.7.jar:2.3.7]
	at org.apache.iceberg.io.BaseTaskWriter$BaseEqualityDeltaWriter.close(BaseTaskWriter.java:196) ~[connector-iceberg-2.3.7.jar:2.3.7]
	at org.apache.seatunnel.connectors.seatunnel.iceberg.sink.writer.UnpartitionedDeltaWriter.close(UnpartitionedDeltaWriter.java:66) ~[connector-iceberg-2.3.7.jar:2.3.7]
	at org.apache.iceberg.io.BaseTaskWriter.complete(BaseTaskWriter.java:96) ~[connector-iceberg-2.3.7.jar:2.3.7]
	at org.apache.seatunnel.connectors.seatunnel.iceberg.sink.writer.IcebergRecordWriter.flush(IcebergRecordWriter.java:161) ~[connector-iceberg-2.3.7.jar:2.3.7]
	at org.apache.seatunnel.connectors.seatunnel.iceberg.sink.writer.IcebergRecordWriter.complete(IcebergRecordWriter.java:142) ~[connector-iceberg-2.3.7.jar:2.3.7]
	at org.apache.seatunnel.connectors.seatunnel.iceberg.sink.IcebergSinkWriter.prepareCommit(IcebergSinkWriter.java:120) ~[connector-iceberg-2.3.7.jar:2.3.7]
	at org.apache.seatunnel.api.sink.multitablesink.MultiTableSinkWriter.lambda$prepareCommit$4(MultiTableSinkWriter.java:217) ~[seatunnel-starter.jar:2.3.7]
	... 5 more
2024-09-09 22:53:16,094 INFO  [o.a.s.e.s.TaskExecutionService] [BlockingWorker-TaskGroupLocation{jobId=885659105019035649, pipelineId=1, taskGroupId=50000}] - [localhost]:5801 [seatunnel-307604] [5.1] taskDone, taskId = 70000, taskGroup = TaskGroupLocation{jobId=885659105019035649, pipelineId=1, taskGroupId=50000}
2024-09-09 22:53:16,094 INFO  [o.a.s.e.s.TaskExecutionService] [BlockingWorker-TaskGroupLocation{jobId=885659105019035649, pipelineId=1, taskGroupId=50000}] - [localhost]:5801 [seatunnel-307604] [5.1] task 70000 error with exception: [java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.apache.hadoop.util.SemaphoredDelegatingExecutor.<init>(Ljava/util/concurrent/ExecutorService;IZ)V], cancel other task in taskGroup TaskGroupLocation{jobId=885659105019035649, pipelineId=1, taskGroupId=50000}.
```

**Comment by FLOWFOX** [comment]
downloading the source code and recompiling `seatunnel-shade/seatunnel-hadoop3-3.1.4-uber` project @YuriyGavrilov

**Comment by YuriyGavrilov** [comment]
Yep it is working. good compile with java 17 Azul. thx @FLOWFOX

**Comment by Hisoka-X** [comment]
Hi @FLOWFOX @YuriyGavrilov , are you build on mac/linux?

**Comment by YuriyGavrilov** [comment]
@Hisoka-X yes, used Mac OS X on intel chip and latest maven.

First way was to use latest java but it didn't work fine with 22, 21 and so on till 17

**Comment by Hisoka-X** [comment]
> @Hisoka-X yes, used Mac OS X on intel chip and latest maven.
> 
> First way was to use latest java but it didn't work fine with 22, 21 and so on till 17

Thanks for share this information.
