### ISSUE TITLE
[Bug] [ JDBC-Class not found]ErrorDescription:[Class load operation failed] - JDBC-Class not found. - dm.jdbc.driver.DmDriver

### ISSUE THREAD

**Issue by kesoncc** [apache/seatunnel#7589]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

使用了达梦进行同步至mysql，mysql能正常创建表结构，但是不能同步数据

### SeaTunnel Version

2.3.7

### SeaTunnel Config

```conf
env {
  parallelism = 2
  job.mode = "BATCH"
  checkpoint.interval = 2000
}

source {
   jdbc  {
        url = "jdbc:dm://ip:5236?schema=TEST"
        driver = "dm.jdbc.driver.DmDriver"
        user = "TEST"
        password = "123456789"
        query = "select * from DM_INDEX_1"
       result_table_name = "sync_table_01_source"
      }

    jdbc  { 
        url = "jdbc:dm://ip:5236?schema=TEST"
        driver = "dm.jdbc.driver.DmDriver"
        user = "TEST"
        password = "123456789"
        query = "select * from TABLE_1"
        result_table_name = sync_table_02_source
      }

}


transform {
  Sql {
    source_table_name = "sync_table_01_source"
    result_table_name = "sync_table_01_target"
    query="SELECT *  FROM sync_table_01_source;"
  }
    

  Sql {
    source_table_name = "sync_table_02_source"
    result_table_name = "sync_table_02_target"
    query="SELECT *  FROM sync_table_02_source;"
  }
}
 

sink {
 
      jdbc {
        url = "jdbc:mysql://ip:3306/seatunnel_test"
        driver = "com.mysql.cj.jdbc.Driver"
        user = "root"
        password = "123456"
        database = seatunnel_test
        table = "dm_test_table_01"
        generate_sink_sql=true
        source_table_name= sync_table_01_target
      }

  jdbc {
        url = "jdbc:mysql://ip:3306/seatunnel_test"
        driver = "com.mysql.cj.jdbc.Driver"
        user = "root"
        password = "123456"
        database = seatunnel_test
        table = "dm_test_table_02"
        generate_sink_sql=true
        source_table_name=sync_table_02_target
      }

}
```

### Running Command

```shell
nohup ./bin/seatunnel.sh --config ./config/dm_batch_sync.config 2>&1 &
```

### Error Exception

```log
Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:211)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: org.apache.seatunnel.connectors.seatunnel.jdbc.exception.JdbcConnectorException: ErrorCode:[COMMON-15], ErrorDescription:[Class load operation failed] - JDBC-Class not found. - dm.jdbc.driver.DmDriver
        at org.apache.seatunnel.connectors.seatunnel.jdbc.source.ChunkSplitter.getOrEstablishConnection(ChunkSplitter.java:147)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.source.ChunkSplitter.createPreparedStatement(ChunkSplitter.java:128)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.source.ChunkSplitter.createSingleSplitStatement(ChunkSplitter.java:172)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.source.ChunkSplitter.generateSplitStatement(ChunkSplitter.java:119)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.JdbcInputFormat.open(JdbcInputFormat.java:98)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.source.JdbcSourceReader.pollNext(JdbcSourceReader.java:67)
        at org.apache.seatunnel.engine.server.task.flow.SourceFlowLifeCycle.collect(SourceFlowLifeCycle.java:156)
        at org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask.collect(SourceSeaTunnelTask.java:127)
        at org.apache.seatunnel.engine.server.task.SeaTunnelTask.stateProcess(SeaTunnelTask.java:168)
        at org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask.call(SourceSeaTunnelTask.java:132)
        at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:717)
        at org.apache.seatunnel.engine.server.TaskExecutionService$NamedTaskWrapper.run(TaskExecutionService.java:1039)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: dm.jdbc.driver.DmDriver
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at org.apache.seatunnel.engine.common.loader.SeaTunnelBaseClassLoader.loadClassWithoutExceptionHandling(SeaTunnelBaseClassLoader.java:56)
        at org.apache.seatunnel.engine.common.loader.SeaTunnelChildFirstClassLoader.loadClassWithoutExceptionHandling(SeaTunnelChildFirstClassLoader.java:97)
        at org.apache.seatunnel.engine.common.loader.SeaTunnelBaseClassLoader.loadClass(SeaTunnelBaseClassLoader.java:47)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.connection.SimpleJdbcConnectionProvider.loadDriver(SimpleJdbcConnectionProvider.java:80)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.connection.SimpleJdbcConnectionProvider.getLoadedDriver(SimpleJdbcConnectionProvider.java:93)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.connection.SimpleJdbcConnectionProvider.getOrEstablishConnection(SimpleJdbcConnectionProvider.java:103)
        at org.apache.seatunnel.connectors.seatunnel.jdbc.source.ChunkSplitter.getOrEstablishConnection(ChunkSplitter.java:143)
        ... 16 more

        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:203)
        ... 2 more
2024-09-05 15:21:21,988 INFO  [s.c.s.s.c.ClientExecuteCommand] [ForkJoinPool.commonPool-worker-9] - run shutdown hook because get close signal
```

### Java or Scala Version

java8

### Screenshots

![image](https://github.com/user-attachments/assets/0a99021f-51a4-4acc-9d69-2e64964907b5)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
Please put dm driver into seatunnel/lib

**Comment by kesoncc** [comment]
> Please put dm driver into seatunnel/lib

Thank you, also need to put it to the /plugins as well,I referred to the cases given in the official documents

**Comment by Hisoka-X** [comment]
> I referred to the cases given in the official documents

which one?

**Comment by kesoncc** [comment]
> > 我参考了官方文件中给出的案例
> 
> 哪一个？

https://seatunnel.incubator.apache.org/docs/2.3.7/connector-v2/source/Jdbc

**Comment by Hisoka-X** [comment]
![image](https://github.com/user-attachments/assets/ce6c539a-5266-4c30-9192-0130bb8ac325)
If you use zeta, only should put it into lib.
