### ISSUE TITLE
[Bug] [connector-file-base] Avro version casue java.lang.NoSuchFieldError: NULL_VALUE

### ISSUE THREAD

**Issue by legend91325** [apache/seatunnel#7629]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

when I run SeaTunnelEngineExample with config about streaming mysql cdc  sink to s3 . 
throw  java.lang.NoSuchFieldError: NULL_VALUE  Exception

first I found this project contains avro 1.7.7 that not conatins this NULL_VALUE field, when I exclude this avro version, and this problem still exist. I found when this program runtime , NULL_VALUE location at hive-exec 3.1.3 ,but this exception location at avro 1.10.2 . 
this exception still confuse me , anyone can help me fix it ?  

### SeaTunnel Version

2.3.7

### SeaTunnel Config

```conf
env {
  parallelism = 1
  job.mode = "STREAMING"
}

source {
  MySQL-CDC {
    base-url = "jdbc:mysql://xxxxx:3306/db?connectionTimeZone=Asia/Shanghai"
    username = "user"
    password = "password"
    table-names = ["db_name.table_name"]
    table-names-config = [
      {
        table = "db_name.table_name"
        primaryKeys = ["id"]
      }
    ]
    startup.mode = "initial"
    stop.mode="never"
  }
}

sink {
  S3File {
    bucket = "s3a://s3-bucket-name"
    path="/seatunnel_parquet/stream"
    fs.s3a.endpoint="s3.us-east-1.amazonaws.com"
    fs.s3a.aws.credentials.provider="org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
    access_key = "******"
    secret_key = "*******"
    file_format_type = "parquet"
    is_enable_transaction = false
    custom_filename = true
    file_name_expression = "${now}_${database_name}_${table_name}"
    filename_time_format = "yyyy_MM_dd"
  }
}
```

### Running Command

```shell
just run org.apache.seatunnel.example.engine.SeaTunnelEngineExample main method
```

### Error Exception

```log
ERROR org.apache.seatunnel.api.sink.multitablesink.MultiTableWriterRunnable - MultiTableWriterRunnable error
java.lang.NoSuchFieldError: NULL_VALUE
	at org.apache.parquet.avro.AvroSchemaConverter.convertFields(AvroSchemaConverter.java:295) ~[parquet-avro-1.12.3.jar:1.12.3]
	at org.apache.parquet.avro.AvroSchemaConverter.convert(AvroSchemaConverter.java:279) ~[parquet-avro-1.12.3.jar:1.12.3]
	at org.apache.seatunnel.connectors.seatunnel.file.sink.writer.ParquetWriteStrategy.buildAvroSchemaWithRowType(ParquetWriteStrategy.java:425) ~[classes/:?]
	at org.apache.seatunnel.connectors.seatunnel.file.sink.writer.ParquetWriteStrategy.getOrCreateWriter(ParquetWriteStrategy.java:160) ~[classes/:?]
	at org.apache.seatunnel.connectors.seatunnel.file.sink.writer.ParquetWriteStrategy.write(ParquetWriteStrategy.java:122) ~[classes/:?]
	at org.apache.seatunnel.connectors.seatunnel.file.sink.BaseFileSinkWriter.write(BaseFileSinkWriter.java:134) ~[classes/:?]
	at org.apache.seatunnel.connectors.seatunnel.file.sink.BaseFileSinkWriter.write(BaseFileSinkWriter.java:46) ~[classes/:?]
	at org.apache.seatunnel.api.sink.multitablesink.MultiTableWriterRunnable.run(MultiTableWriterRunnable.java:62) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_202]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
```

### Zeta or Flink or Spark Version

Zeta

### Java or Scala Version

Java 1.8 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by legend91325** [comment]
大家没有遇到这类问题吗？
