### ISSUE TITLE
[Bug][Seatunnel-web][Hive] An error occurred during the attempt to save a job using the Hive connector.

### ISSUE THREAD

**Issue by arshadmohammad** [apache/seatunnel#7635]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

An error occurred during the attempt to save a job using the Hive connector
Error message:
data source : HIVE is no implementation class for DataSourceConfigSwitcher

### SeaTunnel Version

2.3.7

### SeaTunnel Config

```conf
NA
```

### Running Command

```shell
NA
```

### Error Exception

```log
2024-09-11 13:45:26.510 seatunnel host1 ERROR [qtp1432599360-23] [GlobalExceptionHandler.logError():78] - data source : HIVE is no implementation class for DataSourceConfigSwitcher
org.apache.seatunnel.common.utils.SeaTunnelException: data source : HIVE is no implementation class for DataSourceConfigSwitcher
        at org.apache.seatunnel.app.thirdparty.datasource.DataSourceConfigSwitcherUtils.getDataSourceConfigSwitcher(DataSourceConfigSwitcherUtils.java:86)
        at org.apache.seatunnel.app.thirdparty.datasource.DataSourceConfigSwitcherUtils.filterOptionRule(DataSourceConfigSwitcherUtils.java:46)
        at org.apache.seatunnel.app.service.impl.ConnectorServiceImpl.getDatasourceFormStructure(ConnectorServiceImpl.java:237)
        at org.apache.seatunnel.app.controller.ConnectorDataSourceController.getDatasourceInstanceFormStructure(ConnectorDataSourceController.java:105)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by arshadmohammad** [comment]
issue is fixed
https://github.com/apache/seatunnel-web/commit/1b42b621c1bfdb9ca2c691bad903eb704e7781e9
