### ISSUE TITLE
[Bug] [seatunnel-connectors-v2] running the redisSource task, redis5.0.8-alpine reports a syntax error

### ISSUE THREAD

**Issue by youshaojun** [apache/seatunnel#7664]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I used redis 5.0.8-alpine  running the redisSource task, but reports a syntax error

### SeaTunnel Version

2.3.7

### SeaTunnel Config

```conf
{
  "env": {
    "job.mode": "BATCH",
    "execution.parallelism": 1
  },
  "source": [
    {
      "schema": {
        "columns": [
          {
            "name": "id",
            "type": "STRING"
          },
          {
            "name": "name",
            "type": "STRING"
          },
          {
            "name": "address",
            "type": "STRING"
          },
          {
            "name": "create_time",
            "type": "STRING"
          },
          {
            "name": "update_time",
            "type": "STRING"
          }
        ]
      },
      "db_num": 1,
      "port": "6379",
      "auth": "123456Abc#",
      "keys": "SeaTunnel:test",
      "host": "10.0.0.52",
      "data_type": "key",
      "format": "json",
      "plugin_name": "Redis"
    }
  ],
  "sink": [
    {
      "plugin_name": "Console"
    }
  ]
}
```

### Running Command

```shell
./bin/seatunnel.sh -c config/redis2Console.json -m local
```

### Error Exception

```log
2024-09-14 11:45:25,524 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - 
===============================================================================



Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:211)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: redis.clients.jedis.exceptions.JedisDataException: ERR syntax error
	at redis.clients.jedis.Protocol.processError(Protocol.java:96)
	at redis.clients.jedis.Protocol.process(Protocol.java:137)
	at redis.clients.jedis.Protocol.read(Protocol.java:192)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:316)
	at redis.clients.jedis.Connection.getOne(Connection.java:298)
	at redis.clients.jedis.Connection.executeCommand(Connection.java:123)
	at redis.clients.jedis.Jedis.scan(Jedis.java:8541)
	at org.apache.seatunnel.connectors.seatunnel.redis.client.RedisClient.scanKeys(RedisClient.java:50)
	at org.apache.seatunnel.connectors.seatunnel.redis.source.RedisSourceReader.internalPollNext(RedisSourceReader.java:80)
	at org.apache.seatunnel.connectors.seatunnel.common.source.AbstractSingleSplitReader.pollNext(AbstractSingleSplitReader.java:39)
	at org.apache.seatunnel.engine.server.task.flow.SourceFlowLifeCycle.collect(SourceFlowLifeCycle.java:156)
	at org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask.collect(SourceSeaTunnelTask.java:127)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTask.stateProcess(SeaTunnelTask.java:168)
	at org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask.call(SourceSeaTunnelTask.java:132)
	at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:717)
	at org.apache.seatunnel.engine.server.TaskExecutionService$NamedTaskWrapper.run(TaskExecutionService.java:1039)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:203)
	... 2 more
2024-09-14 11:45:25,528 INFO  [s.c.s.s.c.ClientExecuteCommand] [ForkJoinPool.commonPool-worker-2] - run shutdown hook because get close signal
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FuYouJ** [comment]
After my verification, redis5 does not support specifying types when scanning, today, I will fix this issue
![QQ_1726292384080](https://github.com/user-attachments/assets/4046e148-61e0-499c-85bc-553deac721df)
![QQ_1726292410304](https://github.com/user-attachments/assets/ef7ea885-5ada-4457-bbb0-68762f9807d7)
