### ISSUE TITLE
[Bug] [Module Name] seatunnel.core.starter.execution.PluginUtil.ensureJobModeMatch(PluginUtil.java:170)

### ISSUE THREAD

**Issue by lihm659156** [apache/seatunnel#7792]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

java.lang.UnsupportedOperationException: 'MySQL-CDC' source don't support off-line job.

### SeaTunnel Version

apache-seatunnel-2.3.7

mysql 8 
es 8.13

### SeaTunnel Config

```conf
env {
  parallelism = 1
  job.mode="BATCH"
  job.name="seatunnel_job"
  checkpoint.interval=10000
}

source {
  MySQL-CDC {
    result_table_name="users"
    base-url="jdbc:mysql://192.168.31.206:3306/nfturbo"
    username="root"
    password="123456"
    database-names=["nfturbo"]
    table-names=["nfturbo.users"]
    startup.mode=INITIAL
    catalog {
      factory=MySQL
    }
  }
}

transform {
  Sql {
    source_table_name="users"
    result_table_name="users1"
    query = "select id, nick_name as nickname, state, telephone from users"
  }
}

sink {
  Elasticsearch {
    hosts=["192.168.31.206:9200"]
    source_table_name="users1"
    index="nfturbo_users"
    primary_keys = ["id"]
    tls_verify_certificate=false
  }
}
```

### Running Command

```shell
sh bin/seatunnel.sh --config config/mysql2es.conf -e local &
```

### Error Exception

```log
Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:211)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: java.lang.UnsupportedOperationException: 'MySQL-CDC' source don't support off-line job.
        at org.apache.seatunnel.core.starter.execution.PluginUtil.ensureJobModeMatch(PluginUtil.java:170)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:385)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:209)
        at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.getLogicalDag(ClientJobExecutionEnvironment.java:114)
        at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.execute(ClientJobExecutionEnvironment.java:182)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:158)
        ... 2 more
```

### Screenshots

![image](https://github.com/user-attachments/assets/c9d0aaef-a61d-4d60-b84d-f29b89d4edd4)

![image](https://github.com/user-attachments/assets/b6567cd2-dfa5-4316-bbdc-abfacf2982c9)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lihm659156** [comment]
update title

**Comment by liunaijie** [comment]
```
env {
  parallelism = 1
  job.mode="BATCH"   ## cdc is not support batch mode, you need update it to `STREAMING`
  job.name="seatunnel_job"
  checkpoint.interval=10000
}
```

**Comment by lihm659156** [comment]
Thank you so much
