### ISSUE TITLE
Cannot read the binlog filename and position via 'SHOW MASTER STATUS'

### ISSUE THREAD

**Issue by lihm659156** [apache/seatunnel#7793]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Cannot read the binlog filename and position via 'SHOW MASTER STATUS'

### SeaTunnel Version

apache-seatunnel-2.3.7
mysql 8
es 8.13

### SeaTunnel Config

```conf
env {
  parallelism = 1
  job.mode="STREAMING"
  job.name="seatunnel_job"
  checkpoint.interval=10000
}

source {
  MySQL-CDC {
    result_table_name="users"
    base-url="jdbc:mysql://192.168.31.206:3306/nfturbo"
    username="root"
    password="123456"
    database-names=["nfturbo"]
    table-names=["nfturbo.users"]
    startup.mode=INITIAL
  }
}

transform {
  Sql {
    source_table_name="users"
    result_table_name="users1"
    query = "select id, nick_name as nickname, state, telephone from users"
  }
}

sink {
  Elasticsearch {
    hosts=["192.168.31.206:9200"]
    source_table_name="users1"
    index="nfturbo_users"
    primary_keys = ["id"]
    tls_verify_certificate=false
  }
}
```

### Running Command

```shell
sh bin/seatunnel.sh --config config/mysql2es.conf -e local &
```

### Error Exception

```log
)], task: [pipeline-1 [Source[0]-MySQL-CDC]-SourceTask (1/1)] end with state FAILED and Exception: java.lang.RuntimeException: One or more fetchers have encountered exception
        at org.apache.seatunnel.connectors.seatunnel.common.source.reader.fetcher.SplitFetcherManager.checkErrors(SplitFetcherManager.java:147)
        at org.apache.seatunnel.connectors.seatunnel.common.source.reader.SourceReaderBase.getNextFetch(SourceReaderBase.java:167)
        at org.apache.seatunnel.connectors.seatunnel.common.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:93)
        at org.apache.seatunnel.connectors.cdc.base.source.reader.IncrementalSourceReader.pollNext(IncrementalSourceReader.java:119)
        at org.apache.seatunnel.engine.server.task.flow.SourceFlowLifeCycle.collect(SourceFlowLifeCycle.java:156)
        at org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask.collect(SourceSeaTunnelTask.java:127)
        at org.apache.seatunnel.engine.server.task.SeaTunnelTask.stateProcess(SeaTunnelTask.java:168)
        at org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask.call(SourceSeaTunnelTask.java:132)
        at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:717)
        at org.apache.seatunnel.engine.server.TaskExecutionService$NamedTaskWrapper.run(TaskExecutionService.java:1039)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: SplitFetcher thread 0 received unexpected exception while polling the records
        at org.apache.seatunnel.connectors.seatunnel.common.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:165)
        at org.apache.seatunnel.connectors.seatunnel.common.source.reader.fetcher.SplitFetcher.run(SplitFetcher.java:81)
        ... 5 more
Caused by: java.io.IOException: Source fetch execution was fail
        at org.apache.seatunnel.connectors.seatunnel.common.source.reader.fetcher.FetchTask.run(FetchTask.java:73)
        at org.apache.seatunnel.connectors.seatunnel.common.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:162)
        ... 6 more
Caused by: java.io.IOException: org.apache.seatunnel.common.utils.SeaTunnelException: Read split org.apache.seatunnel.connectors.cdc.base.source.split.SnapshotSplit@ef87d0d5 error due to org.apache.seatunnel.common.utils.SeaTunnelException: Cannot read the binlog filename and position via 'SHOW MASTER STATUS'. Make sure your server is correctly configured.
        at org.apache.seatunnel.connectors.cdc.base.source.reader.IncrementalSourceSplitReader.fetch(IncrementalSourceSplitReader.java:78)
        at org.apache.seatunnel.connectors.seatunnel.common.source.reader.fetcher.FetchTask.run(FetchTask.java:54)
        ... 7 more
Caused by: org.apache.seatunnel.common.utils.SeaTunnelException: Read split org.apache.seatunnel.connectors.cdc.base.source.split.SnapshotSplit@ef87d0d5 error due to org.apache.seatunnel.common.utils.SeaTunnelException: Cannot read the binlog filename and position via 'SHOW MASTER STATUS'. Make sure your server is correctly configured.
        at org.apache.seatunnel.connectors.cdc.base.source.reader.external.IncrementalSourceScanFetcher.checkReadException(IncrementalSourceScanFetcher.java:215)
        at org.apache.seatunnel.connectors.cdc.base.source.reader.external.IncrementalSourceScanFetcher.pollSplitRecords(IncrementalSourceScanFetcher.java:116)
        at org.apache.seatunnel.connectors.cdc.base.source.reader.IncrementalSourceSplitReader.fetch(IncrementalSourceSplitReader.java:75)
        ... 8 more
Caused by: io.debezium.DebeziumException: org.apache.seatunnel.common.utils.SeaTunnelException: Cannot read the binlog filename and position via 'SHOW MASTER STATUS'. Make sure your server is correctly configured
        at org.apache.seatunnel.connectors.seatunnel.cdc.mysql.source.reader.fetch.scan.MySqlSnapshotSplitReadTask.execute(MySqlSnapshotSplitReadTask.java:122)
        at org.apache.seatunnel.connectors.seatunnel.cdc.mysql.source.reader.fetch.scan.MySqlSnapshotFetchTask.execute(MySqlSnapshotFetchTask.java:71)
        at org.apache.seatunnel.connectors.cdc.base.source.reader.external.IncrementalSourceScanFetcher.lambda$submitTask$0(IncrementalSourceScanFetcher.java:95)
        ... 5 more
Caused by: org.apache.seatunnel.common.utils.SeaTunnelException: Cannot read the binlog filename and position via 'SHOW MASTER STATUS'. Make sure your server is correctly configured
        at org.apache.seatunnel.connectors.seatunnel.cdc.mysql.utils.MySqlConnectionUtils.getBinlogOffset(MySqlConnectionUtils.java:121)
        at org.apache.seatunnel.connectors.seatunnel.cdc.mysql.utils.MySqlConnectionUtils.currentBinlogOffset(MySqlConnectionUtils.java:100)
        at org.apache.seatunnel.connectors.seatunnel.cdc.mysql.source.reader.fetch.scan.MySqlSnapshotSplitReadTask.doExecute(MySqlSnapshotSplitReadTask.java:137)
        at org.apache.seatunnel.connectors.seatunnel.cdc.mysql.source.reader.fetch.scan.MySqlSnapshotSplitReadTask.execute(MySqlSnapshotSplitReadTask.java:117)
        ... 7 more
Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'MASTER STATUS' at line 1
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1200)
        at io.debezium.jdbc.JdbcConnection.queryAndMap(JdbcConnection.java:641)
        at io.debezium.jdbc.JdbcConnection.queryAndMap(JdbcConnection.java:510)
        at org.apache.seatunnel.connectors.seatunnel.cdc.mysql.utils.MySqlConnectionUtils.getBinlogOffset(MySqlConnectionUtils.java:108)
```

### Zeta or Flink or Spark Version

not used flink or spark

### Java or Scala Version

openjdk 21

### Screenshots

![image](https://github.com/user-attachments/assets/f36fba03-37b0-481d-a5c7-61bd3f7cd0ba)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by cleverpig** [comment]
mark!! 
Please read the mysql8 manual: https://dev.mysql.com/doc/refman/8.4/en/show-master-status.html
> 15.7.7.24 SHOW MASTER STATUS Statement (no longer supported)
> This statement is no longer supported, and has been replaced by SHOW BINARY LOG STATUS.
With MySQL server 8.4 a number of syntax changes regarding replication have been made.

**Comment by en-hui** [comment]
English：
Can it be assigned to me?

Fix ideas：
Add a version field to the connector metadata maintenance, query the version when initializing the work, and use different SQL statements to complete the query according to the version

中文：
可以把这个问题分给我吗？

修复思路：
在连接器元数据对象中加一个版本字段，任务启动初始化工作时查询版本，并根据版本使用不同sql完成查询

**Comment by en-hui** [comment]
已有pr进行修复：https://github.com/apache/seatunnel/pull/7952
关闭issue

**Comment by hailin0** [comment]
> 已有pr进行修复：#7952 关闭issue

Thanks
