### ISSUE TITLE
Deploying SeaTunnel Engine in a separated mode cluster, encountering errors when starting worker nodes.

### ISSUE THREAD

**Issue by cmx-ops** [apache/seatunnel#7812]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Certainly! Here's the English translation of your statement:

I used two servers to deploy SeaTunnel, with 192.168.12.111 for the master and 192.168.12.196 for worker1. I successfully started the master using `./bin/seatunnel-cluster.sh -d -r master`. However, when I tried to start worker1 with `./bin/seatunnel-cluster.sh -d -r worker`, I encountered an error.
![image](https://github.com/user-attachments/assets/f58df726-48ce-4f11-94f8-ee4b42d0a5da)

Below are the contents of my hazelcast-master.yaml and hazelcast-worker.yaml files:
hazelcast-master.yaml :
![image](https://github.com/user-attachments/assets/95f18fbd-c930-4858-ab23-f2d0196a1b05)

hazelcast-worker.yaml:
![image](https://github.com/user-attachments/assets/5e8916f4-60da-42be-bab8-4871ebb99f32)

### SeaTunnel Version

2.3.7

### SeaTunnel Config

```conf
hazelcast-master.yaml:

hazelcast:
  cluster-name: seatunnel
  network:
    rest-api:
      enabled: true
      endpoint-groups:
        CLUSTER_WRITE:
          enabled: true
        DATA:
          enabled: true
    join:
      tcp-ip:
        enabled: true
        member-list:
          - 192.168.12.111:5801
          - 192.168.12.196:5802
    port:
      auto-increment: false
      port: 5801
  properties:
    hazelcast.invocation.max.retry.count: 20
    hazelcast.tcp.join.port.try.count: 30
    hazelcast.logging.type: log4j2
    hazelcast.operation.generic.thread.count: 50
    hazelcast.heartbeat.failuredetector.type: phi-accrual
    hazelcast.heartbeat.interval.seconds: 2
    hazelcast.max.no.heartbeat.seconds: 180
    hazelcast.heartbeat.phiaccrual.failuredetector.threshold: 10
    hazelcast.heartbeat.phiaccrual.failuredetector.sample.size: 200
    hazelcast.heartbeat.phiaccrual.failuredetector.min.std.dev.millis: 100


hazelcast-worker.yaml:
```yaml
hazelcast:
  cluster-name: seatunnel
  network:
    join:
      tcp-ip:
        enabled: true
        member-list:
          - 192.168.12.111:5801
          - 192.168.12.196:5802
    port:
      auto-increment: false
      port: 5802
  properties:
    hazelcast.invocation.max.retry.count: 20
    hazelcast.tcp.join.port.try.count: 30
    hazelcast.logging.type: log4j2
    hazelcast.operation.generic.thread.count: 50
    hazelcast.heartbeat.failuredetector.type: phi-accrual
    hazelcast.heartbeat.interval.seconds: 2
    hazelcast.max.no.heartbeat.seconds: 180
    hazelcast.heartbeat.phiaccrual.failuredetector.threshold: 10
    hazelcast.heartbeat.phiaccrual.failuredetector.sample.size: 200
    hazelcast.heartbeat.phiaccrual.failuredetector.min.std.dev.millis: 100

```
```


### Running Command

```shell
./bin/seatunnel-cluster.sh -d -r master
./bin/seatunnel-cluster.sh -d -r worker
```

### Error Exception

```log
2024-10-11 09:31:17,369 INFO  [c.h.i.c.AbstractConfigLocator ] [main] - Loading configuration '/opt/software/apache-seatunnel-2.3.7/config/seatunnel.yaml' from System property 'seatunnel.config'
2024-10-11 09:31:17,369 INFO  [c.h.i.c.AbstractConfigLocator ] [main] - Using configuration file at /opt/software/apache-seatunnel-2.3.7/config/seatunnel.yaml
2024-10-11 09:31:17,374 INFO  [o.a.s.e.c.c.SeaTunnelConfig   ] [main] - seatunnel.home is /opt/software/apache-seatunnel-2.3.7
2024-10-11 09:31:17,550 INFO  [c.h.i.c.AbstractConfigLocator ] [main] - Loading configuration '/opt/software/apache-seatunnel-2.3.7/config/hazelcast-worker.yaml' from System property 'hazelcast.config'
2024-10-11 09:31:17,550 INFO  [c.h.i.c.AbstractConfigLocator ] [main] - Using configuration file at /opt/software/apache-seatunnel-2.3.7/config/hazelcast-worker.yaml
2024-10-11 09:31:18,261 INFO  [c.h.i.AddressPicker           ] [main] - [LOCAL] [seatunnel] [5.1] Interfaces is disabled, trying to pick one address from TCP-IP config addresses: [192.168.12.196, 192.168.12.111]
2024-10-11 09:31:18,296 INFO  [o.a.s.e.s.SeaTunnelServer     ] [main] - SeaTunnel server start...
2024-10-11 09:31:18,297 INFO  [c.h.system                    ] [main] - [192.168.12.196]:5802 [seatunnel] [5.1] Based on Hazelcast IMDG version: 5.1.0 (20220228 - 21f20e7)
2024-10-11 09:31:18,297 INFO  [c.h.system                    ] [main] - [192.168.12.196]:5802 [seatunnel] [5.1] Cluster name: seatunnel
2024-10-11 09:31:18,297 INFO  [c.h.system                    ] [main] - [192.168.12.196]:5802 [seatunnel] [5.1] 
                                                         
 _____               _____                             _ 
/  ___|             |_   _|                           | |
\ `--.   ___   __ _   | |   _   _  _ __   _ __    ___ | |
 `--. \ / _ \ / _` |  | |  | | | || '_ \ | '_ \  / _ \| |
/\__/ /|  __/| (_| |  | |  | |_| || | | || | | ||  __/| |
\____/  \___| \__,_|  \_/   \__,_||_| |_||_| |_| \___||_|
                                                         

2024-10-11 09:31:18,297 INFO  [c.h.system                    ] [main] - [192.168.12.196]:5802 [seatunnel] [5.1] Copyright © 2021-2022 The Apache Software Foundation. Apache SeaTunnel, SeaTunnel, and its feather logo are trademarks of The Apache Software Foundation.
2024-10-11 09:31:18,297 INFO  [c.h.system                    ] [main] - [192.168.12.196]:5802 [seatunnel] [5.1] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed.
To enable integrity checker do one of the following: 
  - Change member config using Java API: config.setIntegrityCheckerEnabled(true);
  - Change XML/YAML configuration property: Set hazelcast.integrity-checker.enabled to true
  - Add system property: -Dhz.integritychecker.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
  - Add environment variable: HZ_INTEGRITYCHECKER_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)
2024-10-11 09:31:18,300 INFO  [c.h.system                    ] [main] - [192.168.12.196]:5802 [seatunnel] [5.1] The Jet engine is disabled.
To enable the Jet engine on the members, do one of the following:
  - Change member config using Java API: config.getJetConfig().setEnabled(true)
  - Change XML/YAML configuration property: Set hazelcast.jet.enabled to true
  - Add system property: -Dhz.jet.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
  - Add environment variable: HZ_JET_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)
2024-10-11 09:31:19,078 INFO  [c.h.s.security                ] [main] - [192.168.12.196]:5802 [seatunnel] [5.1] Enable DEBUG/FINE log level for log category com.hazelcast.system.security  or use -Dhazelcast.security.recommendations system property to see 🔒 security recommendations and the status of current config.
2024-10-11 09:31:19,170 INFO  [o.a.s.e.s.SeaTunnelNodeContext] [main] - Using LiteNodeDropOutTcpIpJoiner TCP/IP discovery
2024-10-11 09:31:19,172 WARN  [c.h.c.CPSubsystem             ] [main] - [192.168.12.196]:5802 [seatunnel] [5.1] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
2024-10-11 09:31:19,409 INFO  [.c.c.DefaultClassLoaderService] [main] - start classloader service
2024-10-11 09:31:19,413 INFO  [c.h.i.c.AbstractConfigLocator ] [main] - Loading configuration '/opt/software/apache-seatunnel-2.3.7/config/seatunnel.yaml' from System property 'seatunnel.config'
2024-10-11 09:31:19,413 INFO  [c.h.i.c.AbstractConfigLocator ] [main] - Using configuration file at /opt/software/apache-seatunnel-2.3.7/config/seatunnel.yaml
2024-10-11 09:31:19,418 INFO  [c.h.i.c.AbstractConfigLocator ] [main] - Loading configuration '/opt/software/apache-seatunnel-2.3.7/config/hazelcast-worker.yaml' from System property 'hazelcast.config'
2024-10-11 09:31:19,418 INFO  [c.h.i.c.AbstractConfigLocator ] [main] - Using configuration file at /opt/software/apache-seatunnel-2.3.7/config/hazelcast-worker.yaml
2024-10-11 09:31:19,431 WARN  [o.a.s.e.s.TaskExecutionService] [pool-2-thread-1] - [192.168.12.196]:5802 [seatunnel] [5.1] The Node is not ready yet, Node state STARTING,looking forward to the next scheduling
2024-10-11 09:31:19,434 INFO  [o.a.s.e.s.TaskExecutionService] [main] - [192.168.12.196]:5802 [seatunnel] [5.1] Created new BusWork : 1899609393
2024-10-11 09:31:19,464 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:31:19,523 INFO  [c.h.i.d.Diagnostics           ] [main] - [192.168.12.196]:5802 [seatunnel] [5.1] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
2024-10-11 09:31:19,530 INFO  [c.h.c.LifecycleService        ] [main] - [192.168.12.196]:5802 [seatunnel] [5.1] [192.168.12.196]:5802 is STARTING
2024-10-11 09:31:19,593 INFO  [e.s.LiteNodeDropOutTcpIpJoiner] [hz.main.cached.thread-3] - [192.168.12.196]:5802 [seatunnel] [5.1] [192.168.12.111]:5801 is added to the blacklist.
2024-10-11 09:31:24,460 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:31:29,461 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:31:34,460 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:31:39,459 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:31:44,472 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:31:49,461 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:31:54,459 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:31:59,459 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:32:04,460 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:32:09,460 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:32:14,460 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:32:19,459 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:32:24,460 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:32:29,459 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:32:34,459 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:32:39,460 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:32:44,460 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:32:49,459 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:32:54,460 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:32:59,459 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:33:04,460 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:33:09,462 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:33:14,460 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:33:19,462 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:33:24,464 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:33:29,460 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:33:34,459 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:33:39,460 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:33:44,460 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:33:49,459 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:33:54,459 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:33:59,460 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:34:04,459 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:34:09,472 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:34:14,470 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:34:19,460 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:34:24,461 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:34:29,460 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:34:34,459 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:34:39,460 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:34:44,459 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:34:49,459 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:34:54,459 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:34:59,466 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:35:04,459 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:35:09,460 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:35:14,461 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:35:19,459 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:35:24,459 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:35:29,459 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:35:34,460 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:35:39,460 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:35:44,460 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:35:49,460 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:35:54,460 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:35:59,460 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:36:04,460 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:36:09,460 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:36:14,460 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:36:19,464 WARN  [a.s.e.s.s.s.DefaultSlotService] [hz.main.seaTunnel.slotService.thread] - failed send heartbeat to resource manager, will retry later. this address: [192.168.12.196]:5802
2024-10-11 09:36:19,569 ERROR [c.h.i.i.Node                  ] [main] - [192.168.12.196]:5802 [seatunnel] [5.1] Could not join cluster. Shutting down now!
2024-10-11 09:36:19,569 INFO  [c.h.c.LifecycleService        ] [main] - [192.168.12.196]:5802 [seatunnel] [5.1] [192.168.12.196]:5802 is SHUTTING_DOWN
2024-10-11 09:36:19,573 WARN  [c.h.i.i.Node                  ] [main] - [192.168.12.196]:5802 [seatunnel] [5.1] Terminating forcefully...
2024-10-11 09:36:19,573 INFO  [c.h.i.i.Node                  ] [main] - [192.168.12.196]:5802 [seatunnel] [5.1] Shutting down connection manager...
2024-10-11 09:36:19,576 INFO  [c.h.i.i.Node                  ] [main] - [192.168.12.196]:5802 [seatunnel] [5.1] Shutting down node engine...
2024-10-11 09:36:19,587 INFO  [.c.c.DefaultClassLoaderService] [main] - close classloader service
2024-10-11 09:36:19,587 INFO  [o.a.s.e.s.TaskExecutionService] [event-forwarder-0] - [192.168.12.196]:5802 [seatunnel] [5.1] Event forward thread interrupted
2024-10-11 09:36:19,610 INFO  [c.h.i.i.NodeExtension         ] [main] - [192.168.12.196]:5802 [seatunnel] [5.1] Destroying node NodeExtension.
2024-10-11 09:36:19,610 INFO  [c.h.i.i.Node                  ] [main] - [192.168.12.196]:5802 [seatunnel] [5.1] Hazelcast Shutdown is completed in 38 ms.
2024-10-11 09:36:19,610 INFO  [c.h.c.LifecycleService        ] [main] - [192.168.12.196]:5802 [seatunnel] [5.1] [192.168.12.196]:5802 is SHUTDOWN
2024-10-11 09:36:19,622 WARN  [c.h.i.u.p.PhoneHome           ] [main] - [192.168.12.196]:5802 [seatunnel] [5.1] Could not schedule phone home task! Most probably Hazelcast failed to start.
2024-10-11 09:36:19,623 INFO  [c.h.i.i.Node                  ] [main] - [192.168.12.196]:5802 [seatunnel] [5.1] Node is already shutting down... Waiting for shutdown process to complete...
2024-10-11 09:36:19,624 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - 

===============================================================================


2024-10-11 09:36:19,624 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Fatal Error, 

2024-10-11 09:36:19,624 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Please submit bug report in https://github.com/apache/seatunnel/issues

2024-10-11 09:36:19,627 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Reason:Node failed to start! 

2024-10-11 09:36:19,633 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Exception StackTrace:java.lang.IllegalStateException: Node failed to start!
        at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:126)
        at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:217)
        at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:196)
        at org.apache.seatunnel.core.starter.seatunnel.command.ServerExecuteCommand.execute(ServerExecuteCommand.java:62)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelServer.main(SeaTunnelServer.java:34)
 
2024-10-11 09:36:19,633 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - 
===============================================================================
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CosmosNi** [comment]
Check whether port 5801 of the master stage is started. Or use telnet to check whether the network is accessible.

**Comment by cmx-ops** [comment]
Thank you. It was a network problem
