### ISSUE TITLE
[Bug] [Develop] 使用 IDEA 调试时总报 'Plugin PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='Postgres-CDC'} not found.'

### ISSUE THREAD

**Issue by cobolbaby** [apache/seatunnel#7900]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

在生产环境执行 `./bin/start-seatunnel-flink-15-connector-v2.sh --config /opt/tasks/examples/pgcdc2pg_dauth.conf` 则不报错，但如果使用 IDEA 调试，则总报 'Plugin PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='Postgres-CDC'} not found.'。之前的版本我都是将相关依赖写到 pom.xml 中来解决问题，但最新版还是会一直报错。

我逐层分析了一下，发现 findPluginJarPath 方法中 pluginMappingConfig 为空，这个在调试环境下能加载到吗？

### SeaTunnel Version

2.3.8

### SeaTunnel Config

```conf
env {
  # You can set engine configuration here
  execution.parallelism = 1
  job.mode = "STREAMING"
  checkpoint.interval = 5000
  read_limit.bytes_per_second=7000000
  read_limit.rows_per_second=400
}

source {
  Postgres-CDC {
    # 源端数据库 JDBC Url
    result_table_name = "ITC_PG_DAuth_CDC"
    username = "***"
    password = "***"
    database-names = ["ITCDAuth"]
    schema-names = ["public"]
    table-names = ["ITCDAuth.public.account_login_log", "ITCDAuth.public.ldap_sync_accout"]
    base-url = "jdbc:postgresql://****/ITCDAuth"
  }
}

transform {

}

sink {
  jdbc {
    # https://seatunnel.apache.org/docs/2.3.8/connector-v2/sink/Jdbc
    source_table_name = "ITC_PG_DAuth_CDC"
    url = "jdbc:postgresql://***/ITCDAuth"
    driver = "org.postgresql.Driver"
    user = "***"
    password = "***"

    # You need to configure both database and table
    database = "ITCDAuth"
    table = "${schema_name}.${table_name}"
    primary_keys = ["${primary_key}"]
    schema_save_mode = "IGNORE"
  }
}
```

### Running Command

![seatunnel-debug](https://github.com/user-attachments/assets/3c4c7df3-586f-4a50-ad6f-66aff5940757)

### Error Exception

```log
Exception in thread "main" java.lang.RuntimeException: Plugin PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='Postgres-CDC'} not found.
	at org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery.createPluginInstance(AbstractPluginDiscovery.java:237)
	at org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery.createPluginInstance(AbstractPluginDiscovery.java:177)
	at org.apache.seatunnel.core.starter.execution.PluginUtil.fallbackCreate(PluginUtil.java:128)
	at org.apache.seatunnel.core.starter.execution.PluginUtil.createSource(PluginUtil.java:82)
	at org.apache.seatunnel.core.starter.flink.execution.SourceExecuteProcessor.initializePlugins(SourceExecuteProcessor.java:114)
	at org.apache.seatunnel.core.starter.flink.execution.FlinkAbstractPluginExecuteProcessor.<init>(FlinkAbstractPluginExecuteProcessor.java:67)
	at org.apache.seatunnel.core.starter.flink.execution.SourceExecuteProcessor.<init>(SourceExecuteProcessor.java:61)
	at org.apache.seatunnel.core.starter.flink.execution.FlinkExecution.<init>(FlinkExecution.java:90)
	at org.apache.seatunnel.core.starter.flink.command.FlinkTaskExecuteCommand.execute(FlinkTaskExecuteCommand.java:59)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.example.flink.v2.SeaTunnelApiExample.main(SeaTunnelApiExample.java:39)

```

### Zeta or Flink or Spark Version

Flink: 1.18.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by en-hui** [comment]
我使用2.3.8-release分支未复现该问题，检查一下是否已经根据该文档进行了编译打包https://seatunnel.apache.org/docs/2.3.8/contribution/setup

另外你这个配置文件sink未配置query，所以要么配置query，要么配置generate_sink_sql = true

**Comment by hailin0** [comment]
https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/setup.md
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/5c2b26ee-1e68-4b49-af84-f89d395ec3aa">
