### ISSUE TITLE
SeaTunnel 实现doris实时 数据同步

### ISSUE THREAD

**Issue by Gumiry** [apache/seatunnel#7933]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

doris 实现实时数据同步的时候，一直在报错

### SeaTunnel Version

2.3.8

### SeaTunnel Config

```conf
config配置文件：env {
  execution.parallelism = 2
  execution.mode = "STREAMING"
}

source {
  connector = "doris"
  fenodes = "jdbc:mysql://127.0.0.1:8030"
  username = "root"
  password = "123"
  database = "demo"
  table = "source_table"
}

sink {
  connector = "doris"
  fenodes = "jdbc:mysql://127.0.0.1:8030"
 username = "root"
  password = "123"
  database = "demo"
  table = "target_table"
  batch_max_rows = 10000
  batch_interval_ms = 1000
  format = "json"
}
```

### Running Command

```shell
../bin/seatunnel.sh --config doris4.conf -e local
```

### Error Exception

```log
报错信息：Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:213)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at org.apache.seatunnel.core.starter.utils.ConfigBuilder.lambda$backfillUserVariables$9(ConfigBuilder.java:212)
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676)
        at org.apache.seatunnel.core.starter.utils.ConfigBuilder.backfillUserVariables(ConfigBuilder.java:206)
        at org.apache.seatunnel.core.starter.utils.ConfigBuilder.ofInner(ConfigBuilder.java:70)
        at org.apache.seatunnel.core.starter.utils.ConfigBuilder.lambda$of$1(ConfigBuilder.java:93)
        at java.util.Optional.orElseGet(Optional.java:267)
        at org.apache.seatunnel.core.starter.utils.ConfigBuilder.of(ConfigBuilder.java:93)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.<init>(MultipleTableJobConfigParser.java:151)
        at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.getJobConfigParser(ClientJobExecutionEnvironment.java:102)
        at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.getLogicalDag(ClientJobExecutionEnvironment.java:114)
        at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.execute(ClientJobExecutionEnvironment.java:182)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:160)
```

### Zeta or Flink or Spark Version

无

### Java or Scala Version

jdk8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
Please follow the doc to write config file. https://seatunnel.apache.org/docs/2.3.8/connector-v2/source/Doris#task-example

**Comment by Gumiry** [comment]
> Please follow the doc to write config file. https://seatunnel.apache.org/docs/2.3.8/connector-v2/source/Doris#task-example

BATCH的是可以的，但是STREAMING的不可以

**Comment by Hisoka-X** [comment]
doris source does not supported streaming mode for now.
