### ISSUE TITLE
[Bug] [DOC] Plugin PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='XXXXXX'} not found

### ISSUE THREAD

**Issue by YOMO-Lee** [apache/seatunnel#7959]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### English problem description

SeaTunnel connector development document  *seatunnel connectors v2/README. zh. md* There is an error in the description of the development document for a new connector.The article mentions

>Create Sink and Create Source are methods for creating Source and Sink, respectively, and currently do not need to be implemented

Actually, they should be implemented, otherwise it will cause an exception *Plugin Plugin Identifier {engineType='seattunnel ', pluginType='source', pluginName='XXXXXX'} not found*

In addition, there is no mention of the need to implement creatSink and creatSource in the *creation of a new seatunnel v2 connector*

### 中文问题描述

SeaTunnel连接器开发文档 *seatunnel-connectors-v2/README.zh.md* 关于一个新连接器的开发文档描述有错误
文中提到 
﻿
> createSink 和 createSource 分别是创建Source和Sink的方法，目前不用实现

实际上他们应该被实现，不然会引起异常 *Plugin PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='XXXXXX'} not found*
﻿
另外在 *创建新的seatunnel v2 connector* 中也没提及需要实现 createSink 和 createSource 

### SeaTunnel Version

DEV

### SeaTunnel Config

```conf
无
```

### Running Command

```shell
无
```

### Error Exception

```log
Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:226)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.example.engine.SeaTunnelEngineLocalExample.main(SeaTunnelEngineLocalExample.java:48)
Caused by: java.lang.RuntimeException: Plugin PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='OceanBase-CDC'} not found.
	at org.apache.seatunnel.plugin.discovery.AbstractPluginDiscovery.createPluginInstance(AbstractPluginDiscovery.java:237)
	at org.apache.seatunnel.engine.core.parse.ConnectorInstanceLoader.loadSourceInstance(ConnectorInstanceLoader.java:61)
	at org.apache.seatunnel.engine.core.parse.JobConfigParser.parseSource(JobConfigParser.java:79)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:370)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:209)
	at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.getLogicalDag(ClientJobExecutionEnvironment.java:114)
	at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.execute(ClientJobExecutionEnvironment.java:182)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:163)
	... 2 more
```

### Screenshots

![image](https://github.com/user-attachments/assets/afb3314b-0b86-41ac-a438-234d4b4c4b46)

![c8bfe9e01514e103654482f4c77b591](https://github.com/user-attachments/assets/b79d4cd7-ce1d-4df9-abde-3ac04c33f9fc)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by YOMO-Lee** [comment]
please assign to me
