### ISSUE TITLE
[Bug] [hive to clickhouse 2.3.8] Exception in thread "main" java.lang.NoSuchMethodError: org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(Lorg/apache/hadoop/hive/conf/HiveConf;)V

### ISSUE THREAD

**Issue by Toroidals** [apache/seatunnel#7962]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I updated version 2.3.8 of seatunnel. In this version of sink-hive doc, the description supports version 3.1.3 of hive. But after the experiment according to the description, the error was reported all the time.

24/11/01 18:00:50 INFO HiveMetaStoreProxy: hive client conf:Configuration: core-default.xml, core-site.xml, mapred-default.xml, mapred-site.xml, yarn-default.xml, yarn-site.xml, hdfs-default.xml, hdfs-rbf-default.xml, hdfs-site.xml, hdfs-rbf-site.xml, org.apache.hadoop.hive.conf.LoopingByteArrayInputStream@639c7f9c, file:/etc/spark3/3.3.1.0-002/0/hive-site.xml
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(Lorg/apache/hadoop/conf/Configuration;)V
        at org.apache.seatunnel.connectors.seatunnel.hive.utils.HiveMetaStoreProxy.<init>(HiveMetaStoreProxy.java:110)
        at org.apache.seatunnel.connectors.seatunnel.hive.utils.HiveMetaStoreProxy.getInstance(HiveMetaStoreProxy.java:139)
        at org.apache.seatunnel.connectors.seatunnel.hive.utils.HiveTableUtils.getTableInfo(HiveTableUtils.java:41)
        at org.apache.seatunnel.connectors.seatunnel.hive.source.config.HiveSourceConfig.<init>(HiveSourceConfig.java:83)
        at org.apache.seatunnel.connectors.seatunnel.hive.source.config.MultipleTableHiveSourceConfig.parseFromLocalFileSourceConfig(MultipleTableHiveSourceConfig.java:52)
        at org.apache.seatunnel.connectors.seatunnel.hive.source.config.MultipleTableHiveSourceConfig.<init>(MultipleTableHiveSourceConfig.java:39)
        at org.apache.seatunnel.connectors.seatunnel.hive.source.HiveSource.<init>(HiveSource.java:43)
        at org.apache.seatunnel.connectors.seatunnel.hive.source.HiveSourceFactory.lambda$createSource$0(HiveSourceFactory.java:46)
        at org.apache.seatunnel.core.starter.execution.PluginUtil.createSource(PluginUtil.java:90)
        at org.apache.seatunnel.core.starter.spark.execution.SourceExecuteProcessor.initializePlugins(SourceExecuteProcessor.java:127)
        at org.apache.seatunnel.core.starter.spark.execution.SparkAbstractPluginExecuteProcessor.<init>(SparkAbstractPluginExecuteProcessor.java:51)
        at org.apache.seatunnel.core.starter.spark.execution.SourceExecuteProcessor.<init>(SourceExecuteProcessor.java:61)
        at org.apache.seatunnel.core.starter.spark.execution.SparkExecution.<init>(SparkExecution.java:55)
        at org.apache.seatunnel.core.starter.spark.command.SparkTaskExecuteCommand.execute(SparkTaskExecuteCommand.java:59)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.spark.SeaTunnelSpark.main(SeaTunnelSpark.java:35)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:958)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
24/11/01 18:00:50 INFO SparkContext: Invoking stop() from shutdown hook

### SeaTunnel Version

2.3.8

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
  job.mode = "BATCH"
}
source{
    Hive {
    metastore_uri = "xxx"
    table_name = "dm.clickhouse_flie_test_03_tmp"
    result_table_name = "soure_table"
    parallelism = 4
  }
}
transform {

}
sink {
  ClickhouseFile {
  host = "xxx"
  database = "dm"
  table = "clickhouse_flie_test_04_tmp_all"
  username = "xx"
  password = "xxxxx"
  clickhouse_local_path = "/usr/bin/clickhouse local"
  file_temp_path = "/app/data/clickhouse_local"
  sharding_key = "id"
  node_free_password = true
} 
}
```

### Running Command

```shell
/app/data/apache-seatunnel-2.3.8/bin/start-seatunnel-spark-3-connector-v2.sh --master local[4] --deploy-mode client --config /app/data/seatunnel_ckfile_test_01.conf
```

### Error Exception

```log
24/11/01 18:00:49 INFO SingleEventLogFileWriter: Logging events to hdfs:/spark3-history/local-1730455245572.inprogress
24/11/01 18:00:50 INFO AbstractPluginDiscovery: Load SeaTunnelSource Plugin from /app/data/apache-seatunnel-2.3.8/connectors
24/11/01 18:00:50 INFO AbstractPluginDiscovery: Load Factory Plugin from /app/data/apache-seatunnel-2.3.8/connectors
24/11/01 18:00:50 INFO AbstractPluginDiscovery: Discovery plugin jar for: PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='Hive'} at: file:/app/data/apache-seatunnel-2.3.8/connectors/connector-hive-2.3.8-2.12.15.jar
24/11/01 18:00:50 INFO AbstractPluginDiscovery: Load plugin: PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='Hive'} from classpath
24/11/01 18:00:50 INFO HiveMetaStoreProxy: hive client conf:Configuration: core-default.xml, core-site.xml, mapred-default.xml, mapred-site.xml, yarn-default.xml, yarn-site.xml, hdfs-default.xml, hdfs-rbf-default.xml, hdfs-site.xml, hdfs-rbf-site.xml, org.apache.hadoop.hive.conf.LoopingByteArrayInputStream@639c7f9c, file:/etc/spark3/3.3.1.0-002/0/hive-site.xml
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(Lorg/apache/hadoop/conf/Configuration;)V
        at org.apache.seatunnel.connectors.seatunnel.hive.utils.HiveMetaStoreProxy.<init>(HiveMetaStoreProxy.java:110)
        at org.apache.seatunnel.connectors.seatunnel.hive.utils.HiveMetaStoreProxy.getInstance(HiveMetaStoreProxy.java:139)
        at org.apache.seatunnel.connectors.seatunnel.hive.utils.HiveTableUtils.getTableInfo(HiveTableUtils.java:41)
        at org.apache.seatunnel.connectors.seatunnel.hive.source.config.HiveSourceConfig.<init>(HiveSourceConfig.java:83)
        at org.apache.seatunnel.connectors.seatunnel.hive.source.config.MultipleTableHiveSourceConfig.parseFromLocalFileSourceConfig(MultipleTableHiveSourceConfig.java:52)
        at org.apache.seatunnel.connectors.seatunnel.hive.source.config.MultipleTableHiveSourceConfig.<init>(MultipleTableHiveSourceConfig.java:39)
        at org.apache.seatunnel.connectors.seatunnel.hive.source.HiveSource.<init>(HiveSource.java:43)
        at org.apache.seatunnel.connectors.seatunnel.hive.source.HiveSourceFactory.lambda$createSource$0(HiveSourceFactory.java:46)
        at org.apache.seatunnel.core.starter.execution.PluginUtil.createSource(PluginUtil.java:90)
        at org.apache.seatunnel.core.starter.spark.execution.SourceExecuteProcessor.initializePlugins(SourceExecuteProcessor.java:127)
        at org.apache.seatunnel.core.starter.spark.execution.SparkAbstractPluginExecuteProcessor.<init>(SparkAbstractPluginExecuteProcessor.java:51)
        at org.apache.seatunnel.core.starter.spark.execution.SourceExecuteProcessor.<init>(SourceExecuteProcessor.java:61)
        at org.apache.seatunnel.core.starter.spark.execution.SparkExecution.<init>(SparkExecution.java:55)
        at org.apache.seatunnel.core.starter.spark.command.SparkTaskExecuteCommand.execute(SparkTaskExecuteCommand.java:59)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.spark.SeaTunnelSpark.main(SeaTunnelSpark.java:35)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:958)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
24/11/01 18:00:50 INFO SparkContext: Invoking stop() from shutdown hook
```

### Zeta or Flink or Spark Version

Spark:3.3.0

### Java or Scala Version

java:1.8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by littlecool857** [comment]
i had the same question  i change the exec.jar  metastore.jar common.jar to 2.x version   ,then it works

**Comment by laixueyong** [comment]
> 我有同样的问题，我将 exec.jar metastore.jar common.jar 更改为 2.x 版本，然后它就可以工作了

![image](https://github.com/user-attachments/assets/df3e7b81-01ce-4f36-ac2e-da324eab8df8)
还是报这个问题  缺少什么jar包?

**Comment by littlecool857** [comment]
> > 我有同样的问题，我将 exec.jar metastore.jar common.jar 更改为 2.x 版本，然后它就可以工作了
> 
> ![image](https://private-user-images.githubusercontent.com/141210485/386491002-df3e7b81-01ce-4f36-ac2e-da324eab8df8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NTQ5MjcsIm5iZiI6MTczMTY1NDYyNywicGF0aCI6Ii8xNDEyMTA0ODUvMzg2NDkxMDAyLWRmM2U3YjgxLTAxY2UtNGYzNi1hYzJlLWRhMzI0ZWFiOGRmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQwNzEwMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hY2YyYTBmYjA4MTM5NDJjMjkzMTJiMzM4NmY0YTViMDA2ZjU1N2Y1ZTg2NjQwZDRmYWRiZjkxNTQwNzdmYzU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gXNZLfJq-zWVfM3ffeY7dkD_lGWECA0oxCJc300Pyf0) 还是报这个问题 缺少什么jar包?

我记得当时是把这三个jar包放在seatunnel的lib目录下了  你是不是放在的hive的lib目录下呢

**Comment by laixueyong** [comment]
> > > 我有同样的问题，我将 exec.jar metastore.jar common.jar 更改为 2.x 版本，然后它就可以工作了
> > 
> > 
> > ![图像](https://private-user-images.githubusercontent.com/141210485/386491002-df3e7b81-01ce-4f36-ac2e-da324eab8df8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NTQ5MjcsIm5iZiI6MTczMTY1NDYyNywicGF0aCI6Ii8xNDEyMTA0ODUvMzg2NDkxMDAyLWRmM2U3YjgxLTAxY2UtNGYzNi1hYzJlLWRhMzI0ZWFiOGRmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQwNzEwMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hY2YyYTBmYjA4MTM5NDJjMjkzMTJiMzM4NmY0YTViMDA2ZjU1N2Y1ZTg2NjQwZDRmYWRiZjkxNTQwNzdmYzU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gXNZLfJq-zWVfM3ffeY7dkD_lGWECA0oxCJc300Pyf0)还是报这个问题缺少什么jar包？
> 
> 我记得当时是把这三个jar包放在seatunnel的lib目录下面你不是放在hive的lib目录下呢

![image](https://github.com/user-attachments/assets/bcb51f3d-4f4c-424e-970b-711623e3dada)
换成2.1版本也是这个问题呀 你之前换的是2.几的版本呀

**Comment by littlecool857** [comment]
> > > > 我有同样的问题，我将 exec.jar metastore.jar common.jar 更改为 2.x 版本，然后它就可以工作了
> > > 
> > > 
> > > ![图像](https://private-user-images.githubusercontent.com/141210485/386491002-df3e7b81-01ce-4f36-ac2e-da324eab8df8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NTQ5MjcsIm5iZiI6MTczMTY1NDYyNywicGF0aCI6Ii8xNDEyMTA0ODUvMzg2NDkxMDAyLWRmM2U3YjgxLTAxY2UtNGYzNi1hYzJlLWRhMzI0ZWFiOGRmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQwNzEwMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hY2YyYTBmYjA4MTM5NDJjMjkzMTJiMzM4NmY0YTViMDA2ZjU1N2Y1ZTg2NjQwZDRmYWRiZjkxNTQwNzdmYzU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gXNZLfJq-zWVfM3ffeY7dkD_lGWECA0oxCJc300Pyf0)还是报这个问题缺少什么jar包？
> > 
> > 
> > 我记得当时是把这三个jar包放在seatunnel的lib目录下面你不是放在hive的lib目录下呢
> 
> ![image](https://private-user-images.githubusercontent.com/141210485/386508392-bcb51f3d-4f4c-424e-970b-711623e3dada.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NTgxNjgsIm5iZiI6MTczMTY1Nzg2OCwicGF0aCI6Ii8xNDEyMTA0ODUvMzg2NTA4MzkyLWJjYjUxZjNkLTRmNGMtNDI0ZS05NzBiLTcxMTYyM2UzZGFkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQwODA0MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZTRmMGVhMzVjMjU5NWZiOWNkMGU2ZGQ1ZTNlNzYzNmNlNjdlYjdlNDNmMjIzZTYxZDY5ODdjYjk4MmIwYzY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aUVNY5d2RNDYV_IrCwFrv6dPsJH0d347GN8Bo89vmYY) 换成2.1版本也是这个问题呀 你之前换的是2.几的版本呀

exec-2.3.9       metastore-2.3.4

**Comment by littlecool857** [comment]
> > > > 我有同样的问题，我将 exec.jar metastore.jar common.jar 更改为 2.x 版本，然后它就可以工作了
> > > 
> > > 
> > > ![图像](https://private-user-images.githubusercontent.com/141210485/386491002-df3e7b81-01ce-4f36-ac2e-da324eab8df8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NTQ5MjcsIm5iZiI6MTczMTY1NDYyNywicGF0aCI6Ii8xNDEyMTA0ODUvMzg2NDkxMDAyLWRmM2U3YjgxLTAxY2UtNGYzNi1hYzJlLWRhMzI0ZWFiOGRmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQwNzEwMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hY2YyYTBmYjA4MTM5NDJjMjkzMTJiMzM4NmY0YTViMDA2ZjU1N2Y1ZTg2NjQwZDRmYWRiZjkxNTQwNzdmYzU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gXNZLfJq-zWVfM3ffeY7dkD_lGWECA0oxCJc300Pyf0)还是报这个问题缺少什么jar包？
> > 
> > 
> > 我记得当时是把这三个jar包放在seatunnel的lib目录下面你不是放在hive的lib目录下呢
> 
> ![image](https://private-user-images.githubusercontent.com/141210485/386508392-bcb51f3d-4f4c-424e-970b-711623e3dada.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NTgxNjgsIm5iZiI6MTczMTY1Nzg2OCwicGF0aCI6Ii8xNDEyMTA0ODUvMzg2NTA4MzkyLWJjYjUxZjNkLTRmNGMtNDI0ZS05NzBiLTcxMTYyM2UzZGFkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQwODA0MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZTRmMGVhMzVjMjU5NWZiOWNkMGU2ZGQ1ZTNlNzYzNmNlNjdlYjdlNDNmMjIzZTYxZDY5ODdjYjk4MmIwYzY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aUVNY5d2RNDYV_IrCwFrv6dPsJH0d347GN8Bo89vmYY) 换成2.1版本也是这个问题呀 你之前换的是2.几的版本呀

而且我当时 是直接部署的hive  和Hadoop  没用cdh  不知道和这个有没有关系

**Comment by littlecool857** [comment]
> 24/11/01 18:00:50 INFO HiveMetaStoreProxy: hive client conf:Configuration: core-default.xml, core-site.xml, mapred-default.xml, mapred-site.xml, yarn-default.xml, yarn-site.xml, hdfs-default.xml, hdfs-rbf-default.xml, hdfs-site.xml, hdfs-rbf-site.xml, org.apache.hadoop.hive.conf.LoopingByteArrayInputStream@639c7f9c, file:/etc/spark3/3.3.1.0-002/0/hive-site.xml
> Exception in thread "main" java.lang.NoSuchMethodError: org.apache.hadoop.hive.metastore.HiveMetaStoreClient.(Lorg/apache/hadoop/conf/Configuration;)V
> at org.apache.seatunnel.connectors.seatunnel.hive.utils.HiveMetaStoreProxy.(HiveMetaStoreProxy.java:110)
> at org.apache.seatunnel.connectors.seatunnel.hive.utils.HiveMetaStoreProxy.getInstance(HiveMetaStoreProxy.java:139)
> at org.apache.seatunnel.connectors.seatunnel.hive.utils.HiveTableUtils.getTableInfo(HiveTableUtils.java:41)
> at org.apache.seatunnel.connectors.seatunnel.hive.source.config.HiveSourceConfig.(HiveSourceConfig.java:83)
> at org.apache.seatunnel.connectors.seatunnel.hive.source.config.MultipleTableHiveSourceConfig.parseFromLocalFileSourceConfig(MultipleTableHiveSourceConfig.java:52)
> at org.apache.seatunnel.connectors.seatunnel.hive.source.config.MultipleTableHiveSourceConfig.(MultipleTableHiveSourceConfig.java:39)
> at org.apache.seatunnel.connectors.seatunnel.hive.source.HiveSource.(HiveSource.java:43)
> at org.apache.seatunnel.connectors.seatunnel.hive.source.HiveSourceFactory.lambda$createSource$0(HiveSourceFactory.java:46)
> at org.apache.seatunnel.core.starter.execution.PluginUtil.createSource(PluginUtil.java:90)
> at org.apache.seatunnel.core.starter.spark.execution.SourceExecuteProcessor.initializePlugins(SourceExecuteProcessor.java:127)
> at org.apache.seatunnel.core.starter.spark.execution.SparkAbstractPluginExecuteProcessor.(SparkAbstractPluginExecuteProcessor.java:51)
> at org.apache.seatunnel.core.starter.spark.execution.SourceExecuteProcessor.(SourceExecuteProcessor.java:61)
> at org.apache.seatunnel.core.starter.spark.execution.SparkExecution.(SparkExecution.java:55)
> at org.apache.seatunnel.core.starter.spark.command.SparkTaskExecuteCommand.execute(SparkTaskExecuteCommand.java:59)
> at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
> at org.apache.seatunnel.core.starter.spark.SeaTunnelSpark.main(SeaTunnelSpark.java:35)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
> at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:958)
> at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
> at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
> at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
> at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
> at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
> at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

我理解你这个如果是通过flink提交的任务  可以检测一下 flink中 使用的对应的hive jar包的版本  这个错误通常是由hive和其他组件的版本不适配导致的

**Comment by 601madman** [comment]
只需要将 connect-hive模块下的 hive-exec 的版本由3.1.3 改成2.3.9, 然后重新编译打包，替换掉 connector 目录下的 connector-hive-2.3.8.jar 就行
