### ISSUE TITLE
[Bug] [JDBC-HIVE] hive as source，

### ISSUE THREAD

**Issue by NoPr** [apache/seatunnel#8032]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Using jdbc -hive as source, executing the script reports an error。The specified class cannot be found, but the jar package has been put in.
使用hive的jdbc做为source，报错找不到指定类，但是已经放入了jar包

### SeaTunnel Version

2.3.7

### SeaTunnel Config

```conf
env {
    parallelism = 1
    job.mode =  BATCH
}
source {
    Jdbc {
        result_table_name =  "ta_1856172468898095104_ble"
        driver = "org.apache.hive.jdbc.HiveDriver"
        url = "jdbc:hive2://127.0.0.1:10000/userdb"
        query = "select * from 'userdb'.'t_resource_unstructured_file'"
        user = "root"
        password = ""
    }
}
transform {}
sink {
    Hive {
        source_table_name = "ta_1856172468898095104_ble"
        table_name =  "btrc.test2233"
        metastore_uri = "thrift://127.0.0.1:9083"
    }
}
```

### Running Command

```shell
./bin/seatunnel.sh -c ***.config -e local
```

### Error Exception

```log
Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:211)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.api.table.factory.FactoryException: ErrorCode:[API-06], ErrorDescription:[Factory initialize failed] - Unable to create a source for identifier 'Jdbc'.
        at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:101)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:375)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:209)
        at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.getLogicalDag(ClientJobExecutionEnvironment.java:114)
        at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.execute(ClientJobExecutionEnvironment.java:182)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:158)
        ... 2 more
Caused by: java.lang.NoSuchMethodError: org.apache.hadoop.hive.common.auth.HiveAuthUtils.getSocketTransport(Ljava/lang/String;II)Lorg/apache/hive/org/apache/thrift/transport/TTransport;
        at org.apache.hive.jdbc.HiveConnection.createUnderlyingTransport(HiveConnection.java:561)
        at org.apache.hive.jdbc.HiveConnection.createBinaryTransport(HiveConnection.java:581)
        at org.apache.hive.jdbc.HiveConnection.openTransport(HiveConnection.java:341)
        at org.apache.hive.jdbc.HiveConnection.<init>(HiveConnection.java:228)
        at org.apache.hive.jdbc.HiveDriver.connect(HiveDriver.java:107)
        at org.apache.seatunnel.connec
```

### Zeta or Flink or Spark Version

seatunnel-2.3.7

### Java or Scala Version

java1.8

### Screenshots

![2e70c8ad2c2dff703f48e2eb456892c](https://github.com/user-attachments/assets/903eba8c-5d8f-4ecf-b9e6-ebe593d90d94)
![image](https://github.com/user-attachments/assets/fc4089fe-35dd-47d9-be57-49c6025336bc)
![image](https://github.com/user-attachments/assets/3dc31e47-6a6e-4296-9649-853f00b2e656)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liangjiaxing2022** [comment]
hive jdbc插件不支持sink

**Comment by NoPr** [comment]
> hive jdbc插件不支持sink
使用的hive是source部分的jdbc插件。sink部分使用的是metadata uri

**Comment by NoPr** [comment]
已解决。

**Comment by xinshuaiyong** [comment]
请问你如何解决的，我也碰到这个问题

**Comment by NoPr** [comment]
> 请问你如何解决的，我也碰到这个问题

我的JDK是17，我重新编译了项目，并且添加了hive-jdbc-3.1.3.jar。大小为123KB那个

**Comment by xinshuaiyong** [comment]
我这边是jdk1.8，集群，也添加了这个jar，并打包的时候会打到lib下，重新编译后，还是找不到驱动

**Comment by NoPr** [comment]
> 我这边是jdk1.8，集群，也添加了这个jar，并打包的时候会打到lib下，重新编译后，还是找不到驱动

![image](https://github.com/user-attachments/assets/6adb0e8a-3e6d-47cc-844c-2099ad42c3f7)
我现在zh只能给你看这个截图了，因为放假了。

**Comment by NoPr** [comment]
> 我这边是jdk1.8，集群，也添加了这个jar，并打包的时候会打到lib下，重新编译后，还是找不到驱动

而且我编译的时候没有放lib，是编译完后放进去的
