### ISSUE TITLE
[Bug] [connector-cdc-mongodb] There are unconfigured options, the options('schema') are required

### ISSUE THREAD

**Issue by jingpingxie** [apache/seatunnel#8054]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When I run the example without schema according to https://seatunnel.apache.org/zh-CN/docs/2.3.8/connector-v2/source/MongoDB-CDC , the exception will get, it seems schema is necessary, What should I do if without specify the schema because the filed data struct is variable.

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
env {
  # You can set engine configuration here
  parallelism = 1
  job.mode = "STREAMING"
  checkpoint.interval = 5000
}

source {
  MongoDB-CDC {
    hosts = "mongo0:27017"
    database = ["inventory","crm"]
    collection = ["inventory.products","crm.test"]
    username = stuser
    password = stpw
  }
}

# Console printing of the read Mongodb data
sink {
  Console {
    parallelism = 1
  }
}
```

### Running Command

```shell
mvn clean package -pl seatunnel-connectors-v2/connector-cdc/connector-cdc-mongodb -am -DskipTests -T 1C
```

### Error Exception

```log
Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:226)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.example.engine.SeaTunnelEngineLocalExample.main(SeaTunnelEngineLocalExample.java:48)
Caused by: org.apache.seatunnel.api.table.factory.FactoryException: ErrorCode:[API-06], ErrorDescription:[Factory initialize failed] - Unable to create a source for identifier 'MongoDB-CDC'.
	at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:101)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:375)
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:209)
	at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.getLogicalDag(ClientJobExecutionEnvironment.java:114)
	at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.execute(ClientJobExecutionEnvironment.java:182)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:163)
	... 2 more
Caused by: org.apache.seatunnel.api.configuration.util.OptionValidationException: ErrorCode:[API-02], ErrorDescription:[Option item validate failed] - There are unconfigured options, the options('schema') are required.
	at org.apache.seatunnel.api.configuration.util.ConfigValidator.validate(ConfigValidator.java:134)
	at org.apache.seatunnel.api.configuration.util.ConfigValidator.validate(ConfigValidator.java:95)
	at org.apache.seatunnel.api.configuration.util.ConfigValidator.validate(ConfigValidator.java:47)
	at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:111)
	at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:74)
	... 7 more
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by eee27** [comment]
```
MongoDB-CDC{
    hosts = "1.1.1.1:27017"
    database = ["db"]
    collection = ["db.collec"]
    username = "stuser"
    password = "stuser"
    schema = {
      fields {
    CREATE_DATE = STRING
    PRODUCT_NAME = STRING
    PRICE = "DECIMAL(18,8)"
      }
    }
  }
```
like this
