### ISSUE TITLE
[Bug] [Postgres CDC]java.lang.NoSuchMethodError: org.apache.seatunnel.connectors.cdc.base.source.reader.IncrementalSourceReader.isNoMoreSplitsAssignment()Z

### ISSUE THREAD

**Issue by tusi98** [apache/seatunnel#8055]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

The task cannot run properly

### SeaTunnel Version

2.3.8

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
  job.mode = "STREAMING"
  checkpoint.interval = 5000
  read_limit.bytes_per_second=7000000
  read_limit.rows_per_second=400
}

source {
  Postgres-CDC {
    result_table_name = "customers_Postgre_cdc"
    username = "xxx"
    password = "xxx"
    debezium = {publication.name = "dbz_publication_1"}
    database-names = ["xx"]
    schema-names = ["xxx"]
    table-names = ["xx.xxx.xxx"]
    base-url = "jdbc:postgresql://xxxxxxxxx:5432/xx?loggerLevel=OFF"
  }
}

transform {
}





sink {
  Console {
    source_table_name = "customers_Postgre_cdc"
  }
}
```

### Running Command

```shell
nohup /data/tmp/apache-seatunnel-2.3.4/bin/seatunnel.sh  --config /data/tmp/apache-seatunnel-2.3.4/tmp/pg2kafka.test.conf  >> /data/tmp/apache-seatunnel-2.3.4/log/pg2kafka.log 2>&1 &
```

### Error Exception

```log
Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:213)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: java.lang.NoSuchMethodError: org.apache.seatunnel.connectors.cdc.base.source.reader.IncrementalSourceReader.isNoMoreSplitsAssignment()Z
	at org.apache.seatunnel.connectors.cdc.base.source.reader.IncrementalSourceReader.pollNext(IncrementalSourceReader.java:115)
	at org.apache.seatunnel.engine.server.task.flow.SourceFlowLifeCycle.collect(SourceFlowLifeCycle.java:159)
	at org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask.collect(SourceSeaTunnelTask.java:127)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTask.stateProcess(SeaTunnelTask.java:168)
	at org.apache.seatunnel.engine.server.task.SourceSeaTunnelTask.call(SourceSeaTunnelTask.java:132)
	at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:693)
	at org.apache.seatunnel.engine.server.TaskExecutionService$NamedTaskWrapper.run(TaskExecutionService.java:1018)
	at org.apache.seatunnel.api.tracing.MDCRunnable.run(MDCRunnable.java:39)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:205)
	... 2 more
2024-11-14 11:33:24,231 INFO  [s.c.s.s.c.ClientExecuteCommand] [Thread-7] - run shutdown hook because get close signal
```

### Zeta or Flink or Spark Version

Zeta

### Java or Scala Version

java

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by tusiCHN** [comment]
please!!!look here!!!
