### ISSUE TITLE
[Bug] [CDC] mysql cdc to starrocks, how to add a new column with default value

### ISSUE THREAD

**Issue by maxinonline** [apache/seatunnel#8112]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

mysql cdc to starrocks, I hope to add a new column with default value, it can create table,but how to give a default value
mysql table pk is id
starrocks table pk is id、src
how to give 'src' column a default value, make it not null 

### SeaTunnel Version

2.3.8

### SeaTunnel Config

```conf
{
    "sink" : [
        {
            "base-url" : "jdbc:mysql://172.21.34.95:9030/",
            "enable_upsert_delete" : true,
            "password" : "******",
            "database" : "rl_ods",
            "batch_max_rows" : 10240,
            "save_mode_create_template" : "\n        CREATE TABLE IF NOT EXISTS `${database}`.`${table_name}` (\n        ${rowtype_primary_key},\n       `src` VARCHAR(20) NOT NULL DEFAULT 'db001',\n        ${rowtype_fields}\n        ) ENGINE=OLAP\n        PRIMARY KEY (${rowtype_primary_key},`src`)\n        DISTRIBUTED BY HASH (${rowtype_primary_key})PROPERTIES (\n        \"replication_num\" = \"3\"\n        )\n    ",
            "batch_max_bytes" : 52428800,
            "nodeUrls" : [
                "172.21.34.95:8030",
                "172.21.35.3:8030",
                "172.21.34.160:8030"
            ],
            "plugin_name" : "StarRocks",
            "table" : "tt_${table_name}",
            "username" : "******"
        }
    ],
    "source" : [
        {
            "base-url" : "jdbc:mysql://172.21.34.19:3306/test",
            "password" : "******",
            "startup.mode" : "initial",
            "debezium" : {
                "include.schema.changes" : true
            },
            "table-names" : [
                "test.test1",
                "test.test2"
            ],
            "plugin_name" : "MySQL-CDC",
            "username" : "******"
        }
    ],
    "env" : {
        "job.mode" : "STREAMING",
        "parallelism" : 1,
        "checkpoint.interval" : 10000
    }
}
```

### Running Command

```shell
./seatunnel.sh --config ../config/test_kc.tpl -i src=aaa
```

### Error Exception

```log
2024-11-23 14:53:40,791 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Fatal Error, 

2024-11-23 14:53:40,791 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Please submit bug report in https://github.com/apache/seatunnel/issues

2024-11-23 14:53:40,791 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Reason:SeaTunnel job executed failed 

2024-11-23 14:53:40,792 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:213)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: java.lang.RuntimeException: org.apache.seatunnel.connectors.seatunnel.starrocks.exception.StarRocksConnectorException: ErrorCode:[STARROCKS-02], ErrorDescription:[Writing records to StarRocks failed.] - The number of retries was exceeded, writing records to StarRocks failed.
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:253)
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:66)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:39)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:27)
	at org.apache.seatunnel.engine.server.task.flow.ShuffleSourceFlowLifeCycle.collect(ShuffleSourceFlowLifeCycle.java:121)
	at org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask.collect(TransformSeaTunnelTask.java:73)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTask.stateProcess(SeaTunnelTask.java:168)
	at org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask.call(TransformSeaTunnelTask.java:78)
	at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:693)
	at org.apache.seatunnel.engine.server.TaskExecutionService$NamedTaskWrapper.run(TaskExecutionService.java:1018)
	at org.apache.seatunnel.api.tracing.MDCRunnable.run(MDCRunnable.java:39)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.seatunnel.connectors.seatunnel.starrocks.exception.StarRocksConnectorException: ErrorCode:[STARROCKS-02], ErrorDescription:[Writing records to StarRocks failed.] - The number of retries was exceeded, writing records to StarRocks failed.
	at org.apache.seatunnel.connectors.seatunnel.starrocks.client.StarRocksSinkManager.flush(StarRocksSinkManager.java:92)
	at org.apache.seatunnel.connectors.seatunnel.starrocks.sink.StarRocksSinkWriter.prepareCommit(StarRocksSinkWriter.java:75)
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:188)
	... 15 more
Caused by: org.apache.seatunnel.connectors.seatunnel.starrocks.exception.StarRocksConnectorException: ErrorCode:[STARROCKS-01], ErrorDescription:[Flush batch data to sink connector failed] - Failed to flush data to StarRocks 
rl_ods/tt_test1
too many filtered rows
Error: NULL value in non-nullable column 'src'. Row: [1, NULL, 'aaa', 2024-10-25 14:41:06, NULL, 0]
Error: NULL value in non-nullable column 'src'. Row: [2, NULL, 'bbb', 2024-10-25 16:02:28, NULL, 0]
Error: NULL value in non-nullable column 'src'. Row: [3, NULL, 'ccc', 2024-10-25 16:04:42, NULL, 0]
Error: NULL value in non-nullable column 'src'. Row: [4, NULL, 'ddd', 2024-10-25 16:06:01, NULL, 0]
Error: NULL value in non-nullable column 'src'. Row: [5, NULL, 'eee', 2024-10-25 16:07:41, NULL, 0]


	at org.apache.seatunnel.connectors.seatunnel.starrocks.client.StarRocksStreamLoadVisitor.doStreamLoad(StarRocksStreamLoadVisitor.java:130)
	at org.apache.seatunnel.connectors.seatunnel.starrocks.client.StarRocksSinkManager.flush(StarRocksSinkManager.java:85)
	... 17 more

	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:205)
	... 2 more
 
2024-11-23 14:53:40,792 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - 
===============================================================================



Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:213)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: java.lang.RuntimeException: org.apache.seatunnel.connectors.seatunnel.starrocks.exception.StarRocksConnectorException: ErrorCode:[STARROCKS-02], ErrorDescription:[Writing records to StarRocks failed.] - The number of retries was exceeded, writing records to StarRocks failed.
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:253)
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:66)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:39)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:27)
	at org.apache.seatunnel.engine.server.task.flow.ShuffleSourceFlowLifeCycle.collect(ShuffleSourceFlowLifeCycle.java:121)
	at org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask.collect(TransformSeaTunnelTask.java:73)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTask.stateProcess(SeaTunnelTask.java:168)
	at org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask.call(TransformSeaTunnelTask.java:78)
	at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:693)
	at org.apache.seatunnel.engine.server.TaskExecutionService$NamedTaskWrapper.run(TaskExecutionService.java:1018)
	at org.apache.seatunnel.api.tracing.MDCRunnable.run(MDCRunnable.java:39)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.seatunnel.connectors.seatunnel.starrocks.exception.StarRocksConnectorException: ErrorCode:[STARROCKS-02], ErrorDescription:[Writing records to StarRocks failed.] - The number of retries was exceeded, writing records to StarRocks failed.
	at org.apache.seatunnel.connectors.seatunnel.starrocks.client.StarRocksSinkManager.flush(StarRocksSinkManager.java:92)
	at org.apache.seatunnel.connectors.seatunnel.starrocks.sink.StarRocksSinkWriter.prepareCommit(StarRocksSinkWriter.java:75)
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:188)
	... 15 more
Caused by: org.apache.seatunnel.connectors.seatunnel.starrocks.exception.StarRocksConnectorException: ErrorCode:[STARROCKS-01], ErrorDescription:[Flush batch data to sink connector failed] - Failed to flush data to StarRocks 
rl_ods/tt_test1
too many filtered rows
Error: NULL value in non-nullable column 'src'. Row: [1, NULL, 'aaa', 2024-10-25 14:41:06, NULL, 0]
Error: NULL value in non-nullable column 'src'. Row: [2, NULL, 'bbb', 2024-10-25 16:02:28, NULL, 0]
Error: NULL value in non-nullable column 'src'. Row: [3, NULL, 'ccc', 2024-10-25 16:04:42, NULL, 0]
Error: NULL value in non-nullable column 'src'. Row: [4, NULL, 'ddd', 2024-10-25 16:06:01, NULL, 0]
Error: NULL value in non-nullable column 'src'. Row: [5, NULL, 'eee', 2024-10-25 16:07:41, NULL, 0]


	at org.apache.seatunnel.connectors.seatunnel.starrocks.client.StarRocksStreamLoadVisitor.doStreamLoad(StarRocksStreamLoadVisitor.java:130)
	at org.apache.seatunnel.connectors.seatunnel.starrocks.client.StarRocksSinkManager.flush(StarRocksSinkManager.java:85)
	... 17 more

	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:205)
	... 2 more
2024-11-23 14:53:40,793 INFO  [s.c.s.s.c.ClientExecuteCommand] [ForkJoinPool.commonPool-worker-19] - run shutdown hook because get close signal
```

### Zeta or Flink or Spark Version

zeta

### Java or Scala Version

java version "11.0.25" 2024-10-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.25+9-LTS-256)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.25+9-LTS-256, mixed mode)

### Screenshots

mysql> desc tt_test1;
+------------+--------------+------+-------+---------+-------+
| Field      | Type         | Null | Key   | Default | Extra |
+------------+--------------+------+-------+---------+-------+
| id         | int          | NO   | true  | NULL    |       |
| src        | varchar(20)  | NO   | true  | db001   |       |
| name       | varchar(400) | NO   | false | NULL    |       |
| created_at | datetime     | YES  | false | NULL    |       |
| age        | int          | YES  | false | NULL    |       |
+------------+--------------+------+-------+---------+-------+
5 rows in set (0.00 sec)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dufeng1010** [comment]
if one column of source table is nullable column, but target table's matching column is not null。you can use transform, for example:


```
      transform {
          Sql {
              source_table_name = "test1"
              query = "select id, COALESCE(src, '111') as src, name, age from test1"
          }
      }
```

**Comment by luyfuMinimalism** [comment]
Has this been resolved now
