### ISSUE TITLE
[Bug] [Clickhouse-Seatunnel] Bug 使用spark版本的seatunnel同步就集群CK到新集群CK出现问题

### ISSUE THREAD

**Issue by qianjiangchao1992** [apache/seatunnel#8166]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

我这边ck数据同步到ck，出现类似bug

### SeaTunnel Version

2.3.8

### SeaTunnel Config

```conf
env {
    spark.app.name = seatunnel_ck_to_ck
    parallelism = 2
    job.mode = "BATCH"
    checkpoint.interval  = 3000
    spark.executor.memory= 4g
    spark.executor.instances = 2
    }

    source {
      Clickhouse {
        host = "xxx:8123"
        database = "xxxx"
        sql = "select * from SOAR_DB.test_all where report_date='2024-05-01' order by update_time desc limit 1 by id "
        username = "xxx"
        password = "xxxx"
        result_table_name = "middle_dt"
        clickhouse.config = {
          "socket_timeout": "300000"
        }
      }
    }

    sink {
      Clickhouse {
            source_table_name = "middle_dt"
            host = "xxx:8123"
            database = "xxxx"
            cluster="xxxx"
            table = "test"
            username = "xxx"
            password = "xxxx"
            bulk_size = 200000
            clickhouse.socket_timeout = 600000  # 连接超时600s
            retry = 3
        }
  }
```

### Running Command

```shell
apache-seatunnel-2.3.8/bin/start-seatunnel-spark-2-connector-v2.sh --master spark://xxxx:7077 --deply-mode client --config export_test.conf
```

### Error Exception

```log
Driver stacktrace:
        at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1925)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1913)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1912)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1912)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:948)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:948)
        at scala.Option.foreach(Option.scala:257)
        at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:948)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2146)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2095)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2084)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
        at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:759)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2067)
        at org.apache.spark.sql.execution.datasources.v2.WriteToDataSourceV2Exec.doExecute(WriteToDataSourceV2Exec.scala:64)
        ... 32 more
Caused by: org.apache.seatunnel.connectors.seatunnel.clickhouse.exception.ClickhouseConnectorException: ErrorCode:[COMMON-08], ErrorDescription:[Sql operation failed, such as (execute,addBatch,close) etc...] - Clickhouse prepare statement error: Code: 47. DB::Exception: Unknown expression identifier 'results' in scope SELECT results FROM test WHERE 0. (UNKNOWN_IDENTIFIER) (version 24.4.1.2088 (official build))
```

### Zeta or Flink or Spark Version

spark 2.4.8

### Java or Scala Version

1.8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by qianjiangchao1992** [comment]
如果我把sink改为Console是可以正常打印数据的，因此确定是sink的问题
