### ISSUE TITLE
[Bug] Seatunnel的FTP在读取中文路径下的文件

### ISSUE THREAD

**Issue by strll** [apache/seatunnel#8202]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Seatunnel的FTP在读取中文路径下的文件的时候显示文件找不到的问题
![qq_pic_merged_1733225904013](https://github.com/user-attachments/assets/038b5946-df2b-4271-90d2-db2a1744d66e)

### SeaTunnel Version

2.3.8

### SeaTunnel Config

```conf
在所有的FTP的配置中 只要是ftp路径中出现中文都会触发这个问题
由于内网开发我无法提供具体的文件配置信息
```

### Running Command

```shell
使用api接口时触发
```

### Error Exception

```log
抛出的异常是 Seatunnel read file 。。。。 failed
这里我的解决方式是对文件的路径进行UDF8编码 我修改的是 下面这个文件
org/apache/seatunnel/connectors/seatunnel/file/ftp/system/SeaTunnelFTPFileSystem.java
具体的修改内容我在https://blog.csdn.net/qq_47431361/article/details/143817316?spm=1001.2014.3001.5502 
这个里面有记录
问题的出现主要是因为getFileStatus 和open 这两个方法中未对中文路径进行编码导致无法读取到 修改之后我测试问题可以解决
```

### Java or Scala Version

8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
Would you like to submit a PR to solve this issue? It's not difficult, and I encourage you to give it a try! Here are some helpful resources to get started:  
- [Contribution Setup Guide](https://seatunnel.apache.org/docs/contribution/setup)  
- [Code Submission Guide](https://seatunnel.apache.org/community/submit_guide/submit-code)  

If anyone else would like to help implement this function, please leave a message here, and you can submit a PR. Thank you!  

By the way, since this might be your first contribution, I think we can have a more in-depth communication to help you get familiar with SeaTunnel. Feel free to contact me on LinkedIn ([David Zollo](https://www.linkedin.com/in/davidzollo)) or WeChat(davidzollo). When adding me, please let me know your GitHub ID. I'd be happy to assist you!

**Comment by faketrader** [comment]
v2.3.9 纯英文的路径也有问题.

FTPClient 报 501:

![Image](https://github.com/user-attachments/assets/dc89ace5-8686-4ba7-b80e-e006651463e8)

FTP 服务器 (SFTPGo in Docker)：

```json
{"level":"warn","time":"2025-03-13T09:26:01.116","sender":"ftpserverlib","server_id":"FTP_0","clientId":"50","err":"data connection ip address 127.0.0.1 does not match control connection ip address 192.168.65.1","message":"Could not validate active data connection requirement"}
```

直接用 FTPClient，或者其他客户端是能读到的：

![Image](https://github.com/user-attachments/assets/9fbf8f15-5352-4302-8a24-34febb3d85bb)

日志

```log
2025-03-13 16:29:42,695 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - 
===============================================================================



Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:228)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.api.table.factory.FactoryException: ErrorCode:[API-06], ErrorDescription:[Factory initialize failed] - Unable to create a source for identifier 'FtpFile'.
        at org.apache.seatunnel.api.table.factory.FactoryUtil.restoreAndPrepareSource(FactoryUtil.java:119)
        at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:68)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:404)
        at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:236)
        at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.getLogicalDag(ClientJobExecutionEnvironment.java:123)
        at org.apache.seatunnel.engine.client.job.ClientJobExecutionEnvironment.execute(ClientJobExecutionEnvironment.java:191)
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:165)
        ... 2 more
Caused by: org.apache.seatunnel.connectors.seatunnel.file.exception.FileConnectorException: ErrorCode:[FILE-03], ErrorDescription:[Get file list failed] - Get file list from this path [/test/with_header.csv] failed
        at org.apache.seatunnel.connectors.seatunnel.file.config.BaseFileSourceConfig.parseFilePaths(BaseFileSourceConfig.java:76)
        at org.apache.seatunnel.connectors.seatunnel.file.config.BaseFileSourceConfig.<init>(BaseFileSourceConfig.java:64)
        at org.apache.seatunnel.connectors.seatunnel.file.ftp.config.FTPFileSourceConfig.<init>(FTPFileSourceConfig.java:43)
        at org.apache.seatunnel.connectors.seatunnel.file.ftp.config.MultipleTableFTPFileSourceConfig.getBaseSourceConfig(MultipleTableFTPFileSourceConfig.java:32)
        at org.apache.seatunnel.connectors.seatunnel.file.config.BaseMultipleTableFileSourceConfig.parseFromFileSourceConfig(BaseMultipleTableFileSourceConfig.java:56)
        at org.apache.seatunnel.connectors.seatunnel.file.config.BaseMultipleTableFileSourceConfig.<init>(BaseMultipleTableFileSourceConfig.java:41)
        at org.apache.seatunnel.connectors.seatunnel.file.ftp.config.MultipleTableFTPFileSourceConfig.<init>(MultipleTableFTPFileSourceConfig.java:27)
        at org.apache.seatunnel.connectors.seatunnel.file.ftp.source.FtpFileSource.<init>(FtpFileSource.java:27)
        at org.apache.seatunnel.connectors.seatunnel.file.ftp.source.FtpFileSourceFactory.lambda$createSource$0(FtpFileSourceFactory.java:48)
        at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:131)
        at org.apache.seatunnel.api.table.factory.FactoryUtil.restoreAndPrepareSource(FactoryUtil.java:91)
        ... 8 more
Caused by: java.io.FileNotFoundException: File /test/with_header.csv does not exist.
        at org.apache.seatunnel.connectors.seatunnel.file.ftp.system.SeaTunnelFTPFileSystem.getFileStatus(SeaTunnelFTPFileSystem.java:530)
        at org.apache.seatunnel.connectors.seatunnel.file.ftp.system.SeaTunnelFTPFileSystem.listStatus(SeaTunnelFTPFileSystem.java:477)
        at org.apache.seatunnel.connectors.seatunnel.file.ftp.system.SeaTunnelFTPFileSystem.listStatus(SeaTunnelFTPFileSystem.java:462)
        at org.apache.seatunnel.connectors.seatunnel.file.hadoop.HadoopFileSystemProxy.lambda$listStatus$8(HadoopFileSystemProxy.java:183)
        at org.apache.seatunnel.connectors.seatunnel.file.hadoop.HadoopFileSystemProxy.execute(HadoopFileSystemProxy.java:327)
        at org.apache.seatunnel.connectors.seatunnel.file.hadoop.HadoopFileSystemProxy.listStatus(HadoopFileSystemProxy.java:183)
        at org.apache.seatunnel.connectors.seatunnel.file.source.reader.AbstractReadStrategy.getFileNamesByPath(AbstractReadStrategy.java:110)
        at org.apache.seatunnel.connectors.seatunnel.file.config.BaseFileSourceConfig.parseFilePaths(BaseFileSourceConfig.java:73)
        ... 18 more
```
