### ISSUE TITLE
[Bug] [connector-cdc-oracle ] Unsupport read partition table

### ISSUE THREAD

**Issue by Ashal** [apache/seatunnel#8229]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

oracle实时监听不到分区表,历史数据也不会同步，实时数据也不会监听
<img width="971" alt="image" src="https://github.com/user-attachments/assets/33dfbdb8-a571-4362-af24-e05ad3382b02">
在flinkcdc中已经修复该问题
<img width="1428" alt="image" src="https://github.com/user-attachments/assets/98cdef8a-c4a6-4857-8f48-b1948a6c7a30">

### SeaTunnel Version

2.3.7，2.3.8

### SeaTunnel Config

```conf
env {
  job.mode = "STREAMING"
  parallelism = 1
  checkpoint.interval = 10000
  read_limit.rows_per_second=40960
}
source {
 Oracle-CDC {
    base-url = "jdbc:oracle:thin:@//10.9.3.71:1521/DEV"
    username = "logminer_erp"
    password = "NxJ89TX0Bbc"
    database-names = ["DEV"]
    schema-names = ["XLA"]
    table-names = ["DEV.XLA.XLA_AE_LINES"]
    table-names-config = [
      {
        table = "DEV.XLA.XLA_AE_LINES",
        primaryKeys = ["APPLICATION_ID","AE_HEADER_ID","AE_LINE_NUM"]
      }

    ]

    source.reader.close.timeout = 120000
    skip_analyze = true
    use_select_count = true
    exactly_once = false
  }
}


sink {
  Doris {
    fenodes = "zxxx"
    username = root
    password = "888888g"
    database = "oracle_cdc"
    table = "${table_name}"
    sink.label-prefix = "prod-oracle"
    sink.enable-2pc = "false"
    sink.enable-delete = "true"
    generate_sink_sql = true
    doris.batch.size = 40960
    doris.config {
      format = "json"
      read_json_by_line = "true"
    }
    schema_save_mode = "CREATE_SCHEMA_WHEN_NOT_EXIST"
    data_save_mode = "APPEND_DATA"
    save_mode_create_template = """
      CREATE TABLE IF NOT EXISTS `${database}`.`${table_name}` (
      ${rowtype_primary_key},
      ${rowtype_fields}
      ) ENGINE=OLAP
        UNIQUE KEY (${rowtype_primary_key})
        DISTRIBUTED BY HASH (APPLICATION_ID)
        PROPERTIES (
          "replication_allocation" = "tag.location.default: 1",
          "in_memory" = "false",
          "storage_format" = "V2",
          "disable_auto_compaction" = "false"
        )
      """
  }
}
```

### Running Command

```shell
集群模式启动
```

### Error Exception

```log
无错误
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by tyansc** [comment]
遇到同样的问题，可以正常读取oracle的非分区表，而分区表会直接报错，有没有解决办法？

 2024-12-16 14:31:42,542 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Fatal Error,

2024-12-16 14:31:42,542 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Please submit bug report in https://github.com/apache/seatunnel/issues

2024-12-16 14:31:42,542 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Reason:SeaTunnel job executed failed

2024-12-16 14:31:42,543 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:213)
        at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
        at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: java.lang.NullPointerException
        at org.apache.seatunnel.connectors.cdc.base.source.enumerator.IncrementalSplitAssigner.createIncrementalSplit(IncrementalSplitAssigner.java:240)
        at org.apache.seatunnel.connectors.cdc.base.source.enumerator.IncrementalSplitAssigner.createIncrementalSplits(IncrementalSplitAssigner.java:197)
        at org.apache.seatunnel.connectors.cdc.base.source.enumerator.IncrementalSplitAssigner.getNext(IncrementalSplitAssigner.java:106)
        at org.apache.seatunnel.connectors.cdc.base.source.enumerator.IncrementalSourceEnumerator.assignSplits(IncrementalSourceEnumerator.java:172)
        at org.apache.seatunnel.connectors.cdc.base.source.enumerator.IncrementalSourceEnumerator.run(IncrementalSourceEnumerator.java:70)
        at org.apache.seatunnel.engine.server.task.SourceSplitEnumeratorTask.stateProcess(SourceSplitEnumeratorTask.java:323)
        at org.apache.seatunnel.engine.server.task.SourceSplitEnumeratorTask.call(SourceSplitEnumeratorTask.java:141)
        at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:693)
        at org.apache.seatunnel.engine.server.TaskExecutionService$NamedTaskWrapper.run(TaskExecutionService.java:1018)
        at org.apache.seatunnel.api.tracing.MDCRunnable.run(MDCRunnable.java:39)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

        at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:205)
        ... 2 more

**Comment by davidzollo** [comment]
If anyone who'd like to help fix this issue, please leave a message here. Thank you!  
Here are some helpful resources to get started:  
- [Contribution Setup Guide](https://seatunnel.apache.org/docs/contribution/setup)  
- [Code Submission Guide](https://seatunnel.apache.org/community/submit_guide/submit-code)  

By the way, since this might be your first contribution, I think we can have a more in-depth communication to help you get familiar with SeaTunnel. Feel free to contact me on LinkedIn ([David Zollo](https://www.linkedin.com/in/davidzollo)) or WeChat (taskflow). When adding me, please let me know your GitHub ID. I'd be happy to assist you!

**Comment by HK-hub** [comment]
你好，请问在Flink CDC Connector Oracle那个版本中修复的哦，目前3.3版本还是没有修复

![Image](https://github.com/user-attachments/assets/ead7d59e-b0f3-4d70-81f8-ae5517d19405)
