### ISSUE TITLE
[Bug] [Module Name] .IllegalArgumentException: Cannot get split 

### ISSUE THREAD

**Issue by slcnx** [apache/seatunnel#8247]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

4]:5801 [seatunnel] [5.1] task 50001 error with exception: [java.lang.IllegalArgumentException: Cannot get split 'api.letiku.net.yjy_user_sheet_chapter_total' to get databaseName and tableName], cancel other task in taskGroup TaskGroupLocation{jobId=918434149218385921, pipelineId=1, taskGroupId=30001}.

version: 2.3.8

```
# run on 192.168.102.230:22

docker run --rm -p 5801:5801  -it apache/seatunnel ./bin/seatunnel-cluster.sh -r master
docker run -d --name seatunnel_worker_2          --rm     -e ST_DOCKER_MEMBER_LIST=192.168.102.230:5801  apache/seatunnel     ./bin/seatunnel-cluster.sh -r worker
```

prepare configure table1.template

```
env {
  # You can set SeaTunnel environment configuration here
  parallelism = 2
  job.mode = "STREAMING"
  checkpoint.interval = 10000
}

source {
  MySQL-CDC {
    base-url = "jdbc:mysql://pc-2ze416vjr75gwb568.rwlb.rds.aliyuncs.com:3306"
    username = "xxxxx"
    password = "xxx"
    table-pattern = "api\\.letiku\\.net\\.yjy_user_sheet_chapter_total"
    startup.mode = "initial"
    # 添加连接参数
    connection.pool.size = 20
    connection-properties {
      useSSL = false
      allowPublicKeyRetrieval = true
      characterEncoding = "utf-8"
      serverTimezone = "Asia/Shanghai"
    }

    # 添加 CDC 相关配置
    server-time-zone = "Asia/Shanghai"
    chunk-key-even-distribution-factor-upper-bound = 1000
    chunk-key-even-distribution-factor-lower-bound = 0.05
    sample-sharding-threshold = 1000
  }
}

sink {
  Console {
  }

  # If you would like to get more information about how to configure SeaTunnel and see full list of sink plugins,
  # please go to https://seatunnel.apache.org/docs/connector-v2/sink
}

```

connect 192.168.102.230:5801 master, to sync table.
`
docker run --name seatunnel_client -v /root/table1.template:/root/sync-table.template     -e ST_DOCKER_MEMBER_LIST=192.168.102.230:5801     --rm apache/seatunnel     ./bin/seatunnel.sh -c /root/sync-table.template
`

### SeaTunnel Version

2.3.8

### SeaTunnel Config

```conf
env {
  # You can set SeaTunnel environment configuration here
  parallelism = 2
  job.mode = "STREAMING"
  checkpoint.interval = 10000
}

source {
  MySQL-CDC {
    base-url = "jdbc:mysql://pc-2ze416vjr75gwb568.rwlb.rds.aliyuncs.com:3306"
    username = "xxxxx"
    password = "xxx"
    table-pattern = "api\\.letiku\\.net\\.yjy_user_sheet_chapter_total"
    startup.mode = "initial"
    # 添加连接参数
    connection.pool.size = 20
    connection-properties {
      useSSL = false
      allowPublicKeyRetrieval = true
      characterEncoding = "utf-8"
      serverTimezone = "Asia/Shanghai"
    }

    # 添加 CDC 相关配置
    server-time-zone = "Asia/Shanghai"
    chunk-key-even-distribution-factor-upper-bound = 1000
    chunk-key-even-distribution-factor-lower-bound = 0.05
    sample-sharding-threshold = 1000
  }
}

sink {
  Console {
  }

  # If you would like to get more information about how to configure SeaTunnel and see full list of sink plugins,
  # please go to https://seatunnel.apache.org/docs/connector-v2/sink
}
```

### Running Command

```shell
docker run --name seatunnel_client -v /root/table1.template:/root/sync-table.template     -e ST_DOCKER_MEMBER_LIST=192.168.102.230:5801     --rm apache/seatunnel     ./bin/seatunnel.sh -c /root/sync-table.template
```

### Error Exception

```log
2024-12-09 09:38:37,453 INFO  [p.MultipleTableJobConfigParser] [main] - add common jar in plugins :[]
2024-12-09 09:38:37,466 INFO  [.s.p.d.AbstractPluginDiscovery] [main] - Load SeaTunnelSink Plugin from /opt/seatunnel/connectors
2024-12-09 09:38:37,472 INFO  [.s.p.d.AbstractPluginDiscovery] [main] - Discovery plugin jar for: PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='MySQL-CDC'} at: file:/opt/seatunnel/connectors/connector-cdc-mysql-2.3.8.jar
2024-12-09 09:38:37,474 INFO  [.s.p.d.AbstractPluginDiscovery] [main] - Discovery plugin jar for: PluginIdentifier{engineType='seatunnel', pluginType='sink', pluginName='Console'} at: file:/opt/seatunnel/connectors/connector-console-2.3.8.jar
2024-12-09 09:38:37,478 INFO  [p.MultipleTableJobConfigParser] [main] - start generating all sources.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2024-12-09 09:38:38,601 INFO  [.s.c.s.j.c.AbstractJdbcCatalog] [main] - Catalog MySQL established connection to jdbc:mysql://pc-2ze416vjr75gwb568.rwlb.rds.aliyuncs.com:3306
2024-12-09 09:38:56,069 INFO  [o.a.s.a.t.c.CatalogTableUtil  ] [main] - Get catalog tables, cost time: 17467 ms
2024-12-09 09:38:56,084 INFO  [.s.c.s.j.c.AbstractJdbcCatalog] [main] - Catalog MySQL closing
2024-12-09 09:38:56,167 INFO  [o.a.s.a.t.f.FactoryUtil       ] [main] - get the CatalogTable from source MySQL-CDC: MySQL.api.letiku.net.yjy_user_sheet_chapter_total
2024-12-09 09:38:56,180 INFO  [.s.p.d.AbstractPluginDiscovery] [main] - Load SeaTunnelSource Plugin from /opt/seatunnel/connectors
2024-12-09 09:38:56,185 INFO  [.s.p.d.AbstractPluginDiscovery] [main] - Discovery plugin jar for: PluginIdentifier{engineType='seatunnel', pluginType='source', pluginName='MySQL-CDC'} at: file:/opt/seatunnel/connectors/connector-cdc-mysql-2.3.8.jar
2024-12-09 09:38:56,188 INFO  [p.MultipleTableJobConfigParser] [main] - start generating all transforms.
2024-12-09 09:38:56,188 INFO  [p.MultipleTableJobConfigParser] [main] - start generating all sinks.
2024-12-09 09:38:56,193 INFO  [.s.p.d.AbstractPluginDiscovery] [main] - Load SeaTunnelSink Plugin from /opt/seatunnel/connectors
2024-12-09 09:38:56,194 INFO  [.s.p.d.AbstractPluginDiscovery] [main] - Discovery plugin jar for: PluginIdentifier{engineType='seatunnel', pluginType='sink', pluginName='Console'} at: file:/opt/seatunnel/connectors/connector-console-2.3.8.jar
2024-12-09 09:38:56,199 INFO  [o.a.s.a.t.f.FactoryUtil       ] [main] - Create sink 'Console' with upstream input catalog-table[database: api.letiku.net, schema: null, table: yjy_user_sheet_chapter_total]
2024-12-09 09:38:56,270 INFO  [o.a.s.e.c.j.ClientJobProxy    ] [main] - Start submit job, job id: 918436466177081346, with plugin jar [file:/opt/seatunnel/connectors/connector-console-2.3.8.jar, file:/opt/seatunnel/connectors/connector-cdc-mysql-2.3.8.jar]
2024-12-09 09:38:56,867 INFO  [o.a.s.e.c.j.ClientJobProxy    ] [main] - Submit job finished, job id: 918436466177081346, job name: SeaTunnel_Job
2024-12-09 09:38:56,953 WARN  [o.a.s.e.c.j.JobMetricsRunner  ] [job-metrics-runner-918436466177081346] - Failed to get job metrics summary, it maybe first-run


2024-12-09 09:46:08,590 INFO  [o.a.s.e.s.TaskExecutionService] [hz.main.generic-operation.thread-49] - [10.33.0.4]:5801 [seatunnel] [5.1] deploying TaskGroup TaskGroupLocation{jobId=918438274609971203, pipelineId=1, taskGroupId=30000} success
2024-12-09 09:46:08,593 WARN  [o.a.s.e.s.TaskExecutionService] [BlockingWorker-TaskGroupLocation{jobId=918438274609971203, pipelineId=1, taskGroupId=30000}] - [10.33.0.4]:5801 [seatunnel] [5.1] Exception in org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask@29c96b5c
java.lang.IllegalArgumentException: Cannot get split 'api.letiku.net.yjy_user_sheet_chapter_total' to get databaseName and tableName
	at org.apache.seatunnel.api.table.catalog.TablePath.of(TablePath.java:69) ~[seatunnel-starter.jar:2.3.8]
	at org.apache.seatunnel.api.table.catalog.TablePath.of(TablePath.java:50) ~[seatunnel-starter.jar:2.3.8]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_342]
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1580) ~[?:1.8.0_342]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_342]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_342]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_342]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_342]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_342]
	at org.apache.seatunnel.api.sink.multitablesink.MultiTableSink.getSinkTables(MultiTableSink.java:160) ~[seatunnel-starter.jar:2.3.8]
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.<init>(SinkFlowLifeCycle.java:120) ~[seatunnel-starter.jar:2.3.8]
	at org.apache.seatunnel.engine.server.task.SeaTunnelTask.convertFlowToActionLifeCycle(SeaTunnelTask.java:232) ~[seatunnel-starter.jar:2.3.8]
	at org.apache.seatunnel.engine.server.task.SeaTunnelTask.convertFlowToActionLifeCycle(SeaTunnelTask.java:207) ~[seatunnel-starter.jar:2.3.8]
	at org.apache.seatunnel.engine.server.task.SeaTunnelTask.init(SeaTunnelTask.java:132) ~[seatunnel-starter.jar:2.3.8]
	at org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask.init(TransformSeaTunnelTask.java:51) ~[seatunnel-starter.jar:2.3.8]
	at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:691) ~[seatunnel-starter.jar:2.3.8]
	at org.apache.seatunnel.engine.server.TaskExecutionService$NamedTaskWrapper.run(TaskExecutionService.java:1018) ~[seatunnel-starter.jar:2.3.8]
	at org.apache.seatunnel.api.tracing.MDCRunnable.run(MDCRunnable.java:39) ~[seatunnel-starter.jar:2.3.8]
```

### Zeta or Flink or Spark Version

1

### Java or Scala Version

1

### Screenshots

1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by chengwei977** [comment]
I'm also having the same issue with the same version
