### ISSUE TITLE
[Bug] [ClassLoader] Fix Default Value of ClassLoader Cache Mode

### ISSUE THREAD

**Issue by MyeoungDev** [apache/seatunnel#8288]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

The official [documentation](https://seatunnel.apache.org/docs/seatunnel-engine/separated-cluster-deployment/#45-class-loader-cache-mode) specifies that the default value for classloader-cache-mode is true.
However, upon inspection of the internal code in ServerConfigOptions.class, the CLASSLOADER_CACHE_MODE default value is set to false.

As a result, when running the SeaTunnel Server with default settings, the ClassLoader cache mode is not enabled.
This causes the ClassLoader to repeatedly create and release instances for each job, leading to OutOfMemoryError: Metaspace issues.

I believe the default value of CLASSLOADER_CACHE_MODE should be updated to true to align with the documentation and prevent unnecessary ClassLoader creation and memory issues.

### SeaTunnel Version

2.3.8

### SeaTunnel Config

```conf
seatunnel:
  engine:
    history-job-expire-minutes: 1440
    backup-count: 1
    queue-type: blockingqueue
    print-execution-info-interval: 60
    print-job-metrics-info-interval: 60
    slot-service:
      dynamic-slot: true
    checkpoint:
      interval: 10000
      timeout: 60000
      storage:
        type: hdfs
        max-retained: 3
        plugin-config:
          namespace: /tmp/seatunnel/checkpoint_snapshot
          storage.type: hdfs
          fs.defaultFS: file:///tmp/ # Ensure that the directory has written permission
    telemetry:
      metric:
        enabled: true
```

### Running Command

```shell
./bin/seatunnel-cluster.sh -d -r master
```

### Error Exception

```log
2024-12-10 16:23:43,080 ERROR [o.a.s.e.s.TaskExecutionService] [seatunnel-coordinator-service-27] - [localhost]:5801 [seatunnel] [5.1] TaskGroupID : taskGroupLocation is null  deploy error with Exception: java.lang.OutOfMemoryError: Metaspace

2024-12-11 09:51:17,878 WARN  [Log4j2HttpPostCommandProcessor] [hz.main.cached.thread-19] - [localhost]:5801 [seatunnel] [5.1] An error occurred while handling request HttpCommand [HTTP_POST]{uri='/hazelcast/rest/maps/submit-jobs'}AbstractTextCommand[HTTP_POST]{requestId=0}
org.apache.seatunnel.api.table.factory.FactoryException: ErrorCode:[API-06], ErrorDescription:[Factory initialize failed] - Unable to create a source for identifier 'LocalFile'.
	at org.apache.seatunnel.api.table.factory.FactoryUtil.createAndPrepareSource(FactoryUtil.java:101) ~[seatunnel-starter.jar:2.3.6]
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parseSource(MultipleTableJobConfigParser.java:361) ~[seatunnel-starter.jar:2.3.6]
	at org.apache.seatunnel.engine.core.parse.MultipleTableJobConfigParser.parse(MultipleTableJobConfigParser.java:209) ~[seatunnel-starter.jar:2.3.6]
	at org.apache.seatunnel.engine.server.rest.RestJobExecutionEnvironment.getLogicalDag(RestJobExecutionEnvironment.java:85) ~[seatunnel-starter.jar:2.3.6]
	at org.apache.seatunnel.engine.server.rest.RestJobExecutionEnvironment.build(RestJobExecutionEnvironment.java:108) ~[seatunnel-starter.jar:2.3.6]
	at org.apache.seatunnel.engine.server.rest.RestHttpPostCommandProcessor.handleSubmitJob(RestHttpPostCommandProcessor.java:133) ~[seatunnel-starter.jar:2.3.6]
	at org.apache.seatunnel.engine.server.rest.RestHttpPostCommandProcessor.handle(RestHttpPostCommandProcessor.java:82) ~[seatunnel-starter.jar:2.3.6]
	at org.apache.seatunnel.engine.server.rest.RestHttpPostCommandProcessor.handle(RestHttpPostCommandProcessor.java:60) ~[seatunnel-starter.jar:2.3.6]
	at com.hazelcast.internal.ascii.TextCommandServiceImpl$CommandExecutor.run(TextCommandServiceImpl.java:402) ~[seatunnel-starter.jar:2.3.6]
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217) ~[seatunnel-starter.jar:2.3.6]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[seatunnel-starter.jar:2.3.6]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[seatunnel-starter.jar:2.3.6]
Caused by: java.lang.OutOfMemoryError: Metaspace
```

### Zeta or Flink or Spark Version

Zeta

### Java or Scala Version

1.8

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Hisoka-X** [comment]
Already changed in #7938
