### ISSUE TITLE
[Bug] [SeaTunnel Runs On Spark] java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.encoders.RowEncoder.apply

### ISSUE THREAD

**Issue by yinrui97** [apache/seatunnel#8303]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I tried to submit a seatunnel job using spark engine, it failed with exceptions, probably Seatunnel 2.3.8 does not support Spark 3.5.3?

I followed the instruction on "How do I troubleshoot NoClassDefFoundError, ClassNotFoundException and other issues?" FAQ, see the detailed exception stacktrace.

### SeaTunnel Version

2.3.8

### SeaTunnel Config

```conf
The config has no issue, it can work well in SeaTunnel Zeta engine
```

### Running Command

```shell
./bin/start-seatunnel-spark-3-connector-v2.sh --master local --deploy-mode client --config /path/to/my.conf
```

### Error Exception

```log
....
[Loaded org.apache.spark.sql.catalyst.encoders.RowEncoder from file:/Users/xxx/opt/spark/jars/spark-sql-api_2.13-3.5.3.jar]
[Loaded com.fasterxml.jackson.databind.ser.impl.PropertySerializerMap$Double from file:/Users/xxx/opt/spark/jars/jackson-databind-2.15.2.jar]
Exception in thread "main" [Loaded java.lang.Throwable$WrappedPrintStream from /Users/xxx/opt/jdk1.8.0_421.jdk/Contents/Home/jre/lib/rt.jar]
java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.encoders.RowEncoder.apply(Lorg/apache/spark/sql/types/StructType;)Lorg/apache/spark/sql/catalyst/encoders/ExpressionEncoder;
	at org.apache.seatunnel.core.starter.spark.execution.TransformExecuteProcessor.sparkTransform(TransformExecuteProcessor.java:166)
	at org.apache.seatunnel.core.starter.spark.execution.TransformExecuteProcessor.execute(TransformExecuteProcessor.java:134)
	at org.apache.seatunnel.core.starter.spark.execution.SparkExecution.execute(SparkExecution.java:71)
	at org.apache.seatunnel.core.starter.spark.command.SparkTaskExecuteCommand.execute(SparkTaskExecuteCommand.java:60)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.spark.SeaTunnelSpark.main(SeaTunnelSpark.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:1029)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:194)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:217)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
....
```

### Zeta or Flink or Spark Version

Spark 3.5.3

### Java or Scala Version

1.8.0_421

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by yinrui97** [comment]
`org.apache.spark.sql.catalyst.encoders.RowEncoder` class in `spark-sql-api_2.13-3.5.3.jar` does not have **apply** method
