### ISSUE TITLE
[Bug] [PG JDBC] postgresql -> postgresql 错误: 未实现跨数据库关联

### ISSUE THREAD

**Issue by 20100507** [apache/seatunnel#8324]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

How to synchronize the postgresql data of A to the postgresql data of B using jdbc

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
env {
    job.mode=BATCH
    job.name=23232323

}

source {

Jdbc {
        url="jdbc:postgresql://xxxxx:5866/iceberg?currentSchema=public&stringtype=unspecified"
        driver="org.postgresql.Driver"
        user="sysdba"
        password="xxxx"
        query="SELECT            id, name        FROM test"

    }
}

transform {

}

sink {

Jdbc {
        url="jdbc:postgresql://xxxx:5866/AQGKGL163237782511d6653676c4b62b390ca77a4fe10abd_iceberg"
        driver="org.postgresql.Driver"
        user="sysdba"
        password="xxx"
        database="AQGKGL163237782511d6653676c4b62b390ca77a4fe10abd_iceberg"
        table="public.test"
        generate_sink_sql=true
        primary_keys=["id"]
    }
}
```

### Running Command

```shell
./seatunnel.sh -c test.conf
```

### Error Exception

```log
2024-12-18 14:43:49,888 ERROR org.apache.seatunnel.core.starter.SeaTunnel - 
===============================================================================



Exception in thread "main" org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:191)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: org.apache.seatunnel.engine.common.exception.SeaTunnelEngineException: java.lang.RuntimeException: org.apache.seatunnel.connectors.seatunnel.jdbc.exception.JdbcConnectorException: ErrorCode:[COMMON-10], ErrorDescription:[Flush data operation that in sink connector failed]
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:232)
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:61)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:39)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:27)
	at org.apache.seatunnel.engine.server.task.group.queue.IntermediateBlockingQueue.handleRecord(IntermediateBlockingQueue.java:71)
	at org.apache.seatunnel.engine.server.task.group.queue.IntermediateBlockingQueue.collect(IntermediateBlockingQueue.java:51)
	at org.apache.seatunnel.engine.server.task.flow.IntermediateQueueFlowLifeCycle.collect(IntermediateQueueFlowLifeCycle.java:52)
	at org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask.collect(TransformSeaTunnelTask.java:73)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTask.stateProcess(SeaTunnelTask.java:168)
	at org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask.call(TransformSeaTunnelTask.java:78)
	at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:613)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.seatunnel.connectors.seatunnel.jdbc.exception.JdbcConnectorException: ErrorCode:[COMMON-10], ErrorDescription:[Flush data operation that in sink connector failed]
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.JdbcOutputFormat.flush(JdbcOutputFormat.java:136)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.sink.JdbcSinkWriter.prepareCommit(JdbcSinkWriter.java:88)
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:166)
	... 15 more
Caused by: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO AQGKGL163237782511d6653676c4b62b390ca77a4fe10abd_iceberg.public.test (id, name) VALUES ('12345', '32233232') ON CONFLICT (id) DO UPDATE SET id=EXCLUDED.id, name=EXCLUDED.name was aborted: 错误: 未实现跨数据库关联: "aqgkgl163237782511d6653676c4b62b390ca77a4fe10abd_iceberg.public.test"
  位置：13  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleCompletion(BatchResultHandler.java:186)
	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:878)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:916)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1684)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.executor.FieldNamedPreparedStatement.executeBatch(FieldNamedPreparedStatement.java:533)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.executor.SimpleBatchStatementExecutor.executeBatch(SimpleBatchStatementExecutor.java:51)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.executor.BufferReducedBatchStatementExecutor.executeBatch(BufferReducedBatchStatementExecutor.java:89)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.JdbcOutputFormat.attemptFlush(JdbcOutputFormat.java:165)
	at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.JdbcOutputFormat.flush(JdbcOutputFormat.java:130)
	... 17 more
Caused by: org.postgresql.util.PSQLException: 错误: 未实现跨数据库关联: "aqgkgl163237782511d6653676c4b62b390ca77a4fe10abd_iceberg.public.test"
  位置：13
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:316)
	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:874)
	... 24 more

	at org.apache.seatunnel.engine.client.job.ClientJobProxy.waitForJobComplete(ClientJobProxy.java:122)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:184)
	... 2 more
2024-12-18 14:43:49,889 INFO  org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand - run shutdown hook because get close signal
[root@jykj3 job]# ls
```

### Java or Scala Version

jdk1.8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by davidzollo** [comment]
Would you like to submit a PR to solve this issue? it's not difficult, can you have a try? 
https://seatunnel.apache.org/docs/contribution/setup
https://seatunnel.apache.org/community/submit_guide/submit-code

By the way, if anyone who'd like to help to implement this function, please leave a message then you can submit a PR, thank you.

**Comment by CosmosNi** [comment]
I tested it on the new version and there is no problem.Try upgrading the version.

**Comment by 20100507** [comment]
Yes; I also updated to the latest version and this problem no longer exists
