### ISSUE TITLE
[Bug] [Connector-V2] Source Oracle-CDC Sink Clickhouse run error

### ISSUE THREAD

**Issue by bwcxyk** [apache/seatunnel#8325]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Oracle DDL
```sql
CREATE TABLE test
(
ID       INT,
NAME     VARCHAR(32),
QUANTITY INT,
PRIMARY KEY (id)
);
```
Clickhouse DDL
```sql
CREATE TABLE test (
`ID`       Int32,
`NAME`     String,
`QUANTITY` Int32
) ENGINE = MergeTree
PRIMARY KEY ID
ORDER BY ID;
```
Source Oracle-CDC to Sink Clickhouse , Run error.
```
java.math.BigDecimal cannot be cast to java.lang.Integer
```
Source Oracle to Sink Clickhouse , Run is ok.

### SeaTunnel Version

2.3.8

### SeaTunnel Config

```conf
env {
  parallelism = 1
  job.mode = "STREAMING"
}


source {
  Oracle-CDC {
    result_table_name = "customers"
    base-url = "jdbc:oracle:thin:@192.168.1.70:1521:orcl"
    source.reader.close.timeout = 120000
    username = "system"
    password = "oracle"
    database-names = ["ORCL"]
    schema-names = ["TMS_USER"]
    table-names = ["ORCL.TMS_USER.TEST"]
    table-names-config = [
      {
        table = "ORCL.TMS_USER.TEST"
        primaryKeys = ["ID"]
      }
    ]
  }
}

sink {
  Clickhouse {
    host = "192.168.0.24:8123"
    database = "default"
    table = "test"
    username = "admin"
    password = "admin"

    # cdc options
    primary_key = "ID"
    support_upsert = true
    allow_experimental_lightweight_delete = true
  }
}
```

### Running Command

```shell
./bin/seatunnel.sh -c streaming.oracle2clickhouse.conf -m local
```

### Error Exception

```log
2024-12-18 16:56:48,285 ERROR [o.a.s.e.s.d.p.PhysicalVertex  ] [hz.main.seaTunnel.task.thread-4] - Job SeaTunnel_Job (921687257885179905), Pipeline: [(1/1)], task: [pipeline-1 [Source[0]-Oracle-CDC]-SourceTask (1/1)] end with state FAILED and Exception: java.lang.RuntimeException: org.apache.seatunnel.connectors.seatunnel.clickhouse.exception.ClickhouseConnectorException: ErrorCode:[COMMON-10], ErrorDescription:[Flush data operation that in sink connector failed] - Clickhouse execute batch statement error
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:253)
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:66)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:39)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTransformCollector.collect(SeaTunnelTransformCollector.java:27)
	at org.apache.seatunnel.engine.server.task.group.queue.IntermediateBlockingQueue.handleRecord(IntermediateBlockingQueue.java:70)
	at org.apache.seatunnel.engine.server.task.group.queue.IntermediateBlockingQueue.collect(IntermediateBlockingQueue.java:50)
	at org.apache.seatunnel.engine.server.task.flow.IntermediateQueueFlowLifeCycle.collect(IntermediateQueueFlowLifeCycle.java:51)
	at org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask.collect(TransformSeaTunnelTask.java:73)
	at org.apache.seatunnel.engine.server.task.SeaTunnelTask.stateProcess(SeaTunnelTask.java:168)
	at org.apache.seatunnel.engine.server.task.TransformSeaTunnelTask.call(TransformSeaTunnelTask.java:78)
	at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:693)
	at org.apache.seatunnel.engine.server.TaskExecutionService$NamedTaskWrapper.run(TaskExecutionService.java:1018)
	at org.apache.seatunnel.api.tracing.MDCRunnable.run(MDCRunnable.java:39)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.apache.seatunnel.connectors.seatunnel.clickhouse.exception.ClickhouseConnectorException: ErrorCode:[COMMON-10], ErrorDescription:[Flush data operation that in sink connector failed] - Clickhouse execute batch statement error
	at org.apache.seatunnel.connectors.seatunnel.clickhouse.sink.client.ClickhouseSinkWriter.flush(ClickhouseSinkWriter.java:128)
	at org.apache.seatunnel.connectors.seatunnel.clickhouse.sink.client.ClickhouseSinkWriter.prepareCommit(ClickhouseSinkWriter.java:97)
	at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:188)
	... 17 more
Caused by: java.lang.ClassCastException: java.math.BigDecimal cannot be cast to java.lang.Integer
	at org.apache.seatunnel.connectors.seatunnel.clickhouse.sink.inject.IntInjectFunction.injectFields(IntInjectFunction.java:34)
	at org.apache.seatunnel.connectors.seatunnel.clickhouse.sink.client.executor.JdbcRowConverter.toExternal(JdbcRowConverter.java:79)
	at org.apache.seatunnel.connectors.seatunnel.clickhouse.sink.client.executor.InsertOrUpdateBatchStatementExecutor.exist(InsertOrUpdateBatchStatementExecutor.java:131)
	at org.apache.seatunnel.connectors.seatunnel.clickhouse.sink.client.executor.InsertOrUpdateBatchStatementExecutor.hasInsert(InsertOrUpdateBatchStatementExecutor.java:68)
	at org.apache.seatunnel.connectors.seatunnel.clickhouse.sink.client.executor.InsertOrUpdateBatchStatementExecutor.addToBatch(InsertOrUpdateBatchStatementExecutor.java:83)
	at org.apache.seatunnel.connectors.seatunnel.clickhouse.sink.client.executor.ReduceBufferedBatchStatementExecutor.executeBatch(ReduceBufferedBatchStatementExecutor.java:76)
	at org.apache.seatunnel.connectors.seatunnel.clickhouse.sink.client.ClickhouseSinkWriter.flush(ClickhouseSinkWriter.java:126)
	... 19 more
```

### Zeta or Flink or Spark Version

Zeta

### Java or Scala Version

```
openjdk version "1.8.0_432"
OpenJDK Runtime Environment (build 1.8.0_432-8u432-ga~us1-0ubuntu2~22.04-ga)
OpenJDK 64-Bit Server VM (build 25.432-bga, mixed mode)
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by bwcxyk** [comment]
Data Type issues, INT converted to DECIMAL.
```sql
CREATE TABLE test
(
ID       number(8),
NAME     varchar(32),
QUANTITY number(8),
PRIMARY KEY (id)
);
```
Is ok

**Comment by bwcxyk** [comment]
Data Type issues, INT converted to DECIMAL.
```sql
CREATE TABLE test
(
ID       number(8),
NAME     varchar(32),
QUANTITY number(8),
PRIMARY KEY (id)
);
```
Is ok
