### ISSUE TITLE
bug mysqlcdc to mysql error

### ISSUE THREAD

**Issue by sandea** [apache/seatunnel#8326]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

2024-12-18 16:38:52,410 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - 

===============================================================================

2024-12-18 16:38:52,410 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Fatal Error, 

2024-12-18 16:38:52,410 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Please submit bug report in https://github.com/apache/seatunnel/issues

2024-12-18 16:38:52,412 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Reason:SeaTunnel job executed failed 

2024-12-18 16:38:52,414 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:213)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: java.lang.NullPointerException
	at sun.nio.fs.UnixPath.normalizeAndCheck(UnixPath.java:77)
	at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
	at java.nio.file.Paths.get(Paths.java:84)
	at org.apache.seatunnel.core.starter.utils.FileUtils.getConfigPath(FileUtils.java:49)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:132)
	... 2 more

### SeaTunnel Version

2.3.8

### SeaTunnel Config

```conf
env {
  # You can set SeaTunnel environment configuration here
  execution.parallelism = 2
  job.mode = "STREAMING"
  # 10秒检查一次，可以适当加大这个值
  checkpoint.interval = 10000
  #execution.checkpoint.interval = 10000
  #execution.checkpoint.data-uri = "hdfs://localhost:9000/checkpoint"
}

# 配置数据源
source {
  MySQL-CDC {
    # 数据库账号
    username = "root"
    password = "123456"
    # 源表，格式：数据库名.表名
    table-names = ["source.test_table"]
    base-url = "jdbc:mysql://127.0.0.1:3306/source?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true"
    startup.mode = "initial"
  }
}
# 配置目标库
sink {

  jdbc {
    url = "jdbc:mysql://127.0.0.1:3306/sink?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true"
    driver = "com.mysql.cj.jdbc.Driver"
    user = "root"
    password = "123456"

    generate_sink_sql = true
        # 目标数据库名
    database = "sink"
    # 目标表名
    table = "test_table"
    # 主键名称
    primary_keys = ["id"]
    field_ide = LOWERCASE
    schema_save_mode = "CREATE_SCHEMA_WHEN_NOT_EXIST"
    data_save_mode="APPEND_DATA"
  }
}
```

### Running Command

```shell
bin/seatunnel.sh config/mysql_to_mysql_config
```

### Error Exception

```log
2024-12-18 16:38:52,410 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - 

===============================================================================


2024-12-18 16:38:52,410 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Fatal Error, 

2024-12-18 16:38:52,410 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Please submit bug report in https://github.com/apache/seatunnel/issues

2024-12-18 16:38:52,412 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Reason:SeaTunnel job executed failed 

2024-12-18 16:38:52,414 ERROR [o.a.s.c.s.SeaTunnel           ] [main] - Exception StackTrace:org.apache.seatunnel.core.starter.exception.CommandExecuteException: SeaTunnel job executed failed
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:213)
	at org.apache.seatunnel.core.starter.SeaTunnel.run(SeaTunnel.java:40)
	at org.apache.seatunnel.core.starter.seatunnel.SeaTunnelClient.main(SeaTunnelClient.java:34)
Caused by: java.lang.NullPointerException
	at sun.nio.fs.UnixPath.normalizeAndCheck(UnixPath.java:77)
	at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
	at java.nio.file.Paths.get(Paths.java:84)
	at org.apache.seatunnel.core.starter.utils.FileUtils.getConfigPath(FileUtils.java:49)
	at org.apache.seatunnel.core.starter.seatunnel.command.ClientExecuteCommand.execute(ClientExecuteCommand.java:132)
	... 2 more
```

### Zeta or Flink or Spark Version

Zeta

### Screenshots

![image](https://github.com/user-attachments/assets/0af62764-fe8d-4e21-b595-c15af10322c6)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hailin0** [comment]
add `--config` into shell commamd

```
bin/seatunnel.sh --config config/mysql_to_mysql_config -m local
```


docs
https://github.com/apache/seatunnel/blob/dev/docs/en/start-v2/locally/quick-start-seatunnel-engine.md#step-3-run-seatunnel-application
