### ISSUE TITLE
mysql 实时同步 msyql 出错

### ISSUE THREAD

**Issue by sandea** [apache/seatunnel#8342]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

mysql 实时同步 msyql 出错

### SeaTunnel Version

2.3.8

### SeaTunnel Config

```conf
env {
  # You can set SeaTunnel environment configuration here
  execution.parallelism = 2
  job.mode = "STREAMING"
  # 10秒检查一次，可以适当加大这个值
  checkpoint.interval = 10000
  #execution.checkpoint.interval = 10000
  #execution.checkpoint.data-uri = "hdfs://localhost:9000/checkpoint"
}

# 配置数据源
source {
  MySQL-CDC {
    # 数据库账号
    username = "root"
    password = "123456"
    # 源表，格式：数据库名.表名
    table-names = ["source.test_table"]
    base-url = "jdbc:mysql://127.0.0.1:3306/source?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&allowPublicKeyRetrieval=true"
    startup.mode = "initial"
  }
}
# 配置目标库
sink {

  jdbc {
    url = "jdbc:mysql://127.0.0.1:3306/sink?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&allowPublicKeyRetrieval=true"
    driver = "com.mysql.cj.jdbc.Driver"
    user = "root"
    password = "123456"

    generate_sink_sql = true
        # 目标数据库名
    database = "sink"
    # 目标表名
    table = "test_table"
    # 主键名称
    primary_keys = ["id"]
    field_ide = LOWERCASE
    schema_save_mode = "CREATE_SCHEMA_WHEN_NOT_EXIST"
    data_save_mode="APPEND_DATA"
  }

}
```

### Running Command

```shell
./bin/seatunnel.sh --config config/mysql_to_mysql_config -m local
```

### Error Exception

```log
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:172)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:862)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:444)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:230)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:226)
	at io.debezium.jdbc.JdbcConnection.lambda$patternBasedFactory$1(JdbcConnection.java:244)
	at org.apache.seatunnel.connectors.seatunnel.cdc.mysql.config.CustomMySqlConnectionConfiguration$1.connect(CustomMySqlConnectionConfiguration.java:52)
	at io.debezium.jdbc.JdbcConnection.connection(JdbcConnection.java:888)
	at io.debezium.jdbc.JdbcConnection.connection(JdbcConnection.java:883)
	at io.debezium.jdbc.JdbcConnection.query(JdbcConnection.java:548)
	at io.debezium.jdbc.JdbcConnection.query(JdbcConnection.java:496)
	at org.apache.seatunnel.connectors.seatunnel.cdc.mysql.utils.TableDiscoveryUtils.listTables(TableDiscoveryUtils.java:47)
	at org.apache.seatunnel.connectors.seatunnel.cdc.mysql.source.MySqlDialect.discoverDataCollections(MySqlDialect.java:97)
	... 9 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:59)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:103)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:149)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:165)
	at com.mysql.cj.protocol.a.NativeProtocol.negotiateSSLConnection(NativeProtocol.java:355)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.negotiateSSLConnection(NativeAuthenticationProvider.java:789)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:499)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:217)
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1411)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:165)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:982)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:852)
	... 20 more
Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:171)
	at sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:103)
	at sun.security.ssl.TransportContext.kickstart(TransportContext.java:227)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:433)
	at com.mysql.cj.protocol.ExportControlled.performTlsHandshake(ExportControlled.java:213)
	at com.mysql.cj.protocol.StandardSocketFactory.performTlsHandshake(StandardSocketFactory.java:206)
	at com.mysql.cj.protocol.a.NativeSocketConnection.performTlsHandshake(NativeSocketConnection.java:99)
	at com.mysql.cj.protocol.a.NativeProtocol.negotiateSSLConnection(NativeProtocol.java:350)
	... 27 more

	at org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator.reportCheckpointErrorFromTask(CheckpointCoordinator.java:390) [seatunnel-starter.jar:2.3.8]
	at org.apache.seatunnel.engine.server.checkpoint.CheckpointManager.reportCheckpointErrorFromTask(CheckpointManager.java:184) [seatunnel-starter.jar:2.3.8]
	at org.apache.seatunnel.engine.server.checkpoint.operation.CheckpointErrorReportOperation.runInternal(CheckpointErrorReportOperation.java:48) [seatunnel-starter.jar:2.3.8]
	at org.apache.seatunnel.engine.server.task.operation.TracingOperation.run(TracingOperation.java:44) [seatunnel-starter.jar:2.3.8]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) [seatunnel-starter.jar:2.3.8]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:273) [seatunnel-starter.jar:2.3.8]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) [seatunnel-starter.jar:2.3.8]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213) [seatunnel-starter.jar:2.3.8]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:175) [seatunnel-starter.jar:2.3.8]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:139) [seatunnel-starter.jar:2.3.8]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) [seatunnel-starter.jar:2.3.8]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [seatunnel-starter.jar:2.3.8]
2024-12-19 16:18:58,772 INFO  [.s.e.s.c.CheckpointCoordinator] [hz.main.generic-operation.thread-38] - start clean pending checkpoint cause CheckpointCoordinator inside have error.
2024-12-19 16:18:58,773 INFO  [.s.e.s.c.CheckpointCoordinator] [hz.main.generic-operation.thread-38] - Turn checkpoint_state_922040277638578177_1 state from RUNNING to FAILED
2024-12-19 16:18:58,773 WARN  [o.a.s.e.s.d.p.SubPlan         ] [hz.main.generic-operation.thread-38] - Job SeaTunnel_Job (922040277638578177), Pipeline: [(1/1)] checkpoint have error, cancel the pipeline
2024-12-19 16:18:58,778 INFO  [o.a.s.e.s.d.p.SubPlan         ] [hz.main.generic-operation.thread-38] - Job SeaTunnel_Job (922040277638578177), Pipeline: [(1/1)] turned from state RUNNING to CANCELING.
2024-12-19 16:18:58,778 INFO  [o.a.s.e.s.d.p.PhysicalVertex  ] [hz.main.generic-operation.thread-38] - Job SeaTunnel_Job (922040277638578177), Pipeline: [(1/1)], task: [pipeline-1 [Source[0]-MySQL-CDC]-SplitEnumerator (1/1)] state process is start
2024-12-19 16:18:58,779 INFO  [o.a.s.e.s.d.p.PhysicalVertex  ] [hz.main.generic-operation.thread-38] - Job SeaTunnel_Job (922040277638578177), Pipeline: [(1/1)], task: [pipeline-1 [Source[0]-MySQL-CDC]-SplitEnumerator (1/1)] turned from state RUNNING to CANCELING.
2024-12-19 16:18:58,779 INFO  [o.a.s.e.s.d.p.PhysicalVertex  ] [hz.main.generic-operation.thread-38] - Send cancel Job SeaTunnel_Job (922040277638578177), Pipeline: [(1/1)], task: [pipeline-1 [Source[0]-MySQL-CDC]-SplitEnumerator (1/1)] operator to member [localhost]:5802
2024-12-19 16:18:58,779 INFO  [o.a.s.e.s.TaskExecutionService] [hz.main.generic-operation.thread-38] - [localhost]:5802 [seatunnel-443671] [5.1] Task (TaskGroupLocation{jobId=922040277638578177, pipelineId=1, taskGroupId=1}) need cancel.
2024-12-19 16:18:58,780 INFO  [o.a.s.e.s.d.p.PhysicalVertex  ] [hz.main.generic-operation.thread-38] - Job SeaTunnel_Job (922040277638578177), Pipeline: [(1/1)], task: [pipeline-1 [Source[0]-MySQL-CDC]-SourceTask (1/1)] state process is start
2024-12-19 16:18:58,780 WARN  [o.a.s.e.s.TaskExecutionService] [BlockingWorker-TaskGroupLocation{jobId=922040277638578177, pipelineId=1, taskGroupId=1}] - [localhost]:5802 [seatunnel-443671] [5.1] Interrupted task 20000 - org.apache.seatunnel.engine.server.task.SourceSplitEnumeratorTask@470ae3c
2024-12-19 16:18:58,780 INFO  [o.a.s.e.s.TaskExecutionService] [BlockingWorker-TaskGroupLocation{jobId=922040277638578177, pipelineId=1, taskGroupId=1}] - [localhost]:5802 [seatunnel-443671] [5.1] taskDone, taskId = 20000, taskGroup = TaskGroupLocation{jobId=922040277638578177, pipelineId=1, taskGroupId=1}
2024-12-19 16:18:58,783 INFO  [o.a.s.e.s.TaskExecutionService] [BlockingWorker-TaskGroupLocation{jobId=922040277638578177, pipelineId=1, taskGroupId=1}] - [localhost]:5802 [seatunnel-443671] [5.1] taskGroup TaskGroupLocation{jobId=922040277638578177, pipelineId=1, taskGroupId=1} complete with CANCELED
2024-12-19 16:18:58,783 ERROR [.s.e.s.c.CheckpointCoordinator] [hz.main.generic-operation.thread-39] - report error from task
org.apache.seatunnel.common.utils.SeaTunnelException: java.util.concurrent.CancellationException
	at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2276)
	at org.apache.seatunnel.engine.server.task.AbstractTask.close(AbstractTask.java:102)
	at org.apache.seatunnel.engine.server.task.SourceSplitEnumeratorTask.close(SourceSplitEnumeratorTask.java:123)
	at org.apache.seatunnel.engine.server.TaskExecutionService$BlockingWorker.run(TaskExecutionService.java:710)
	at org.apache.seatunnel.engine.server.TaskExecutionService$NamedTaskWrapper.run(TaskExecutionService.java:1018)
	at org.apache.seatunnel.api.tracing.MDCRunnable.run(MDCRunnable.java:39)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

	at org.apache.seatunnel.engine.server.checkpoint.CheckpointCoordinator.reportCheckpointErrorFromTask(CheckpointCoordinator.java:390) [seatunnel-starter.jar:2.3.8]
	at org.apache.seatunnel.engine.server.checkpoint.CheckpointManager.reportCheckpointErrorFromTask(CheckpointManager.java:184) [seatunnel-starter.jar:2.3.8]
	at org.apache.seatunnel.engine.server.checkpoint.operation.CheckpointErrorReportOperation.runInternal(CheckpointErrorReportOperation.java:48) [seatunnel-starter.jar:2.3.8]
	at org.apache.seatunnel.engine.server.task.operation.TracingOperation.run(TracingOperation.java:44) [seatunnel-starter.jar:2.3.8]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) [seatunnel-starter.jar:2.3.8]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:273) [seatunnel-starter.jar:2.3.8]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) [seatunnel-starter.jar:2.3.8]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213) [seatunnel-starter.jar:2.3.8]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:175) [seatunnel-starter.jar:2.3.8]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:139) [seatunnel-starter.jar:2.3.8]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) [seatunnel-starter.jar:2.3.8]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [seatunnel-starter.jar:2.3.8]
```

### Zeta or Flink or Spark Version

Zeta

### Screenshots

![image](https://github.com/user-attachments/assets/0971e385-81ce-4742-b444-d36e56e1996e)
![image](https://github.com/user-attachments/assets/ee7f64d2-9e23-4eed-9f98-f441b82b8bdd)
![image](https://github.com/user-attachments/assets/bd461d43-9d0d-463f-9040-b85e53c27a68)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FrommyMind** [comment]
Which version of mysql do you using？
And can you check your mysql variables with :
```
show variables like 'tls_version';
```

**Comment by sandea** [comment]
mysql 5.7

**Comment by sandea** [comment]
![image](https://github.com/user-attachments/assets/a30ad1b6-cfb7-4fc8-b313-5e34148ce1fe)

**Comment by sandea** [comment]
> Which version of mysql do you using？ And can you check your mysql variables with :
> 
> ```
> show variables like 'tls_version';
> ```

![image](https://github.com/user-attachments/assets/ef3993f5-9f93-4720-8f7a-7357c27c9e51)

**Comment by sandea** [comment]
batch data is success，stream mode is report there errors

**Comment by FrommyMind** [comment]
Add `enabledTLSProtocols=TLSv1.2` to you jdbc url and retry.

**Comment by chunhongZheng** [comment]
SeaTunnel Version  2.3.8 
There are similar problems。
batch data is success，stream mode is report there errors 。
and the configuration file information is as follows:

{
	    "sink" : [
	        {
	            "plugin_name" : "Console"
	        }
	    ],
	    "source" : [
	        {
	            "base-url" : "jdbc:mysql://xxx:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf8&connectionTimeZone=Asia/Shanghai&enabledTLSProtocols=TLSv1.2",
	            "password" : "******",
	            "startup.mode" : "initial",
	            "table-names" : [
	                "test.user"
	            ],
	            "plugin_name" : "MySQL-CDC",
	            "username" : "******"
	        }
	    ],
	    "env" : {
	        "job.mode" : "STREAMING",
	        "parallelism" : 1,
	        "checkpoint.interval" : 10000
	    }
	}

**Comment by FrommyMind** [comment]
No issue with seatunnel version 2.3.8, and mysql 5.7

## Step 1:  Run seatunnel 2.3.8 with docker.

```bash
docker network create seatunnel-network 

docker run -d --name seatunnel_master \
    --network seatunnel-network \
    --rm \
    -p 5801:5801 \
    apache/seatunnel:2.3.8 \
    ./bin/seatunnel-cluster.sh -r master
    

docker run -d --name seatunnel_worker_1 \
    --network seatunnel-network \
    --rm \
    -e ST_DOCKER_MEMBER_LIST=192.168.80.3:5801 \
    apache/seatunnel:2.3.8 \
    ./bin/seatunnel-cluster.sh -r worker

```

## Step 2: Run mysql 5.7

create config folder
```
mkdir /opt/mysql5.7/
```
the `my.cnf` config file
```
[mysqld]
log_bin = /var/lib/mysql/mysql-bin.log
expire_logs_days = 10
max_binlog_size = 100M
server-id = 1
```
run docker
```
docker run --name mysql-5.7.44 -p23307:3306  -v /opt/mysql5.7/my.cnf:/etc/mysql/my.cnf \
-v /opt/mysql5.7/data:/var/lib/mysql \
-e MYSQL_ROOT_PASSWORD=123456 -d mysql:5.7.44
```
create user and database;
create table and insert data;
```msyql
create user test_user identified by 'xxxxxxxxx';
GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'test_user' ;

create database test_db;
use test_db;
CREATE TABLE `users` (
  `id` int NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `email` varchar(100) NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
  );
  
insert into users (username, email) values ('aaa', 'aaa@example.com'),('bbb', 'bbb@example.com'),('ccc', 'ccc@example.com');
```
The seatunnel config `mysql-streaming.conf`.
```
env {
  job.mode="STREAMING" 
  checkpoint.interval=10000 
  parallelism=1
}
source {
  MySQL-CDC {
    plugin_output = "fake"
    password="xxxxxxxxx"
    username=test_user
    base-url="jdbc:mysql://xxx.xxx.xxx.xxx:23307/test_db?useUnicode=true&useSSL=false&characterEncoding=utf8&connectionTimeZone=Asia/Shanghai&enabledTLSProtocols=TLSv1.2"
    startup.mode="initial"
    table-names=["test_db.users"]
  }
}

sink {
 Console {
    plugin_input = ["fake"]
  }
}

```

## Step 3: Run the job

```
/opt/seatunnel/bin/seatunnel.sh -c mysql-streaming.conf
```

**Comment by chunhongZheng** [comment]
The problem has been resolved. Upgrade mysql-connector-java-8.0.11.jar to mysql-connector-java-8.0.30.jar
