### ISSUE TITLE
[FAQ] java.io.FileNotFoundException: HADOOP_HOME and hadoop.home.dir are unset.

### ISSUE THREAD

**Issue by huchao-hu** [apache/seatunnel#8365]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

![image](https://github.com/user-attachments/assets/72930aab-0366-4cba-8391-ff16bfc82c7c)
使用 seatunnel-engine-examples模块测试 mysql cdc 同步到clickhouse 会报错说没有 HADOOP_HOME and hadoop.home.dir are unset

### SeaTunnel Version

2.3.8版本-release 源码

### SeaTunnel Config

```conf
seatunnel:
    engine:
        backup-count: 1
        queue-type: blockingqueue
        print-execution-info-interval: 60
        slot-service:
            dynamic-slot: true
        checkpoint:
            interval: 300000
            timeout: 10000
            storage:
                type: hdfs
                max-retained: 3
                plugin-config:
                    namespace: /tmp/seatunnel/checkpoint_snapshot/
                    storage.type: local
                    fs.defaultFS: file:///tmp/
        jar-storage:
            enable: false
            connector-jar-storage-mode: SHARED
            connector-jar-storage-path: ""
            connector-jar-cleanup-task-interval: 3600
            connector-jar-expiry-time: 600
        telemetry:
            metric:
                enabled: false
```

### Running Command

```shell
直接在idea mian方法启动的
```

### Error Exception

```log
Caused by: java.io.FileNotFoundException: java.io.FileNotFoundException: HADOOP_HOME and hadoop.home.dir are unset. -see https://wiki.apache.org/hadoop/WindowsProblems
	at org.apache.hadoop.util.Shell.fileNotFoundException(Shell.java:549)
	at org.apache.hadoop.util.Shell.getHadoopHomeDir(Shell.java:570)
	at org.apache.hadoop.util.Shell.getQualifiedBin(Shell.java:593)
	at org.apache.hadoop.util.Shell.<clinit>(Shell.java:690)
	at org.apache.hadoop.util.StringUtils.<clinit>(StringUtils.java:78)
	at org.apache.hadoop.conf.Configuration.getBoolean(Configuration.java:1665)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:474)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:227)
	at org.apache.seatunnel.engine.checkpoint.storage.hdfs.HdfsStorage.initStorage(HdfsStorage.java:68)
	at org.apache.seatunnel.engine.checkpoint.storage.hdfs.HdfsStorage.<init>(HdfsStorage.java:57)
	at org.apache.seatunnel.engine.checkpoint.storage.hdfs.common.HdfsFileStorageInstance.getOrCreateStorage(HdfsFileStorageInstance.java:53)
	at org.apache.seatunnel.engine.checkpoint.storage.hdfs.HdfsStorageFactory.create(HdfsStorageFactory.java:74)
	at org.apache.seatunnel.engine.server.checkpoint.CheckpointManager.<init>(CheckpointManager.java:105)
	at org.apache.seatunnel.engine.server.master.JobMaster.initCheckPointManager(JobMaster.java:288)
	at org.apache.seatunnel.engine.server.master.JobMaster.init(JobMaster.java:271)
	at org.apache.seatunnel.engine.server.CoordinatorService.lambda$submitJob$4(CoordinatorService.java:511)
	at org.apache.seatunnel.api.tracing.MDCRunnable.run(MDCRunnable.java:39)
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hawk9821** [comment]
Please install hadoop locally

**Comment by huchao-hu** [comment]
Isn't there a local mode to boot? Do you still need to install hadoop? @hawk9821

**Comment by fcb-xiaobo** [comment]
> Isn't there a local mode to boot? Do you still need to install hadoop? @hawk9821

This shouldn't affect usage, right? The task can still run normally

**Comment by huchao-hu** [comment]
@fcb-xiaobo Currently, the startup fails and cannot be used normally

**Comment by hawk9821** [comment]
> Isn't there a local mode to boot? Do you still need to install hadoop? @hawk9821

The error log is so obvious that the problem with the Hadoop Client environment can be solved by following the log prompts.

**Comment by davidzollo** [comment]
Under Linux, there is no need to configure HADOOP_HOME; under Windows, HADOOP_HOME may be required (I haven't verified this on Windows).
SeaTunnel uses HDFS protocol to save Checkpoint and other related information. We use HDFS protocol to support write local files. HDFS supports the local file system.
