### ISSUE TITLE
[Bug] [Flink] The flink e2e is faulty

### ISSUE THREAD

**Issue by Carl-Zhou-CN** [apache/seatunnel#8383]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

The flink e2e is faulty

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
no
```

### Running Command

```shell
no
```

### Error Exception

```log
2024-12-21T04:36:24.7267949Z Caused by: java.lang.RuntimeException: org.apache.seatunnel.connectors.seatunnel.assertion.exception.AssertConnectorException: ErrorCode:[ASSERT-01], ErrorDescription:[Rule validate failed] - row num :98 fail rule: AssertFieldRule.AssertRule(ruleType=MIN_ROW, ruleValue=100.0, equalTo=null)
2024-12-21T04:36:24.7269684Z 	at org.apache.seatunnel.api.sink.multitablesink.MultiTableSinkWriter.close(MultiTableSinkWriter.java:349) ~[?:?]
2024-12-21T04:36:24.7270960Z 	at org.apache.seatunnel.translation.flink.sink.FlinkSinkWriter.close(FlinkSinkWriter.java:123) ~[?:?]
2024-12-21T04:36:24.7272592Z 	at org.apache.flink.streaming.api.transformations.SinkV1Adapter$SinkWriterV1Adapter.close(SinkV1Adapter.java:156) ~[flink-dist-1.15.3.jar:1.15.3]
2024-12-21T04:36:24.7274000Z 	at org.apache.flink.util.IOUtils.closeAll(IOUtils.java:254) ~[flink-dist-1.15.3.jar:1.15.3]
2024-12-21T04:36:24.7274951Z 	at org.apache.flink.util.IOUtils.closeAll(IOUtils.java:233) ~[flink-dist-1.15.3.jar:1.15.3]
2024-12-21T04:36:24.7275939Z 	at org.apache.flink.util.IOUtils.closeAll(IOUtils.java:222) ~[flink-dist-1.15.3.jar:1.15.3]
2024-12-21T04:36:24.7277311Z 	at org.apache.flink.streaming.runtime.operators.sink.SinkWriterOperator.close(SinkWriterOperator.java:218) ~[flink-dist-1.15.3.jar:1.15.3]
2024-12-21T04:36:24.7278986Z 	at org.apache.flink.streaming.runtime.tasks.StreamOperatorWrapper.close(StreamOperatorWrapper.java:163) ~[flink-dist-1.15.3.jar:1.15.3]
2024-12-21T04:36:24.7280928Z 	at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.closeAllOperators(RegularOperatorChain.java:125) ~[flink-dist-1.15.3.jar:1.15.3]
2024-12-21T04:36:24.7282531Z 	at org.apache.flink.streaming.runtime.tasks.StreamTask.closeAllOperators(StreamTask.java:1000) ~[flink-dist-1.15.3.jar:1.15.3]
2024-12-21T04:36:24.7284042Z 	at org.apache.flink.streaming.runtime.tasks.StreamTask.afterInvoke(StreamTask.java:879) ~[flink-dist-1.15.3.jar:1.15.3]
2024-12-21T04:36:24.7285474Z 	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:762) ~[flink-dist-1.15.3.jar:1.15.3]
2024-12-21T04:36:24.7286917Z 	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:948) ~[flink-dist-1.15.3.jar:1.15.3]
2024-12-21T04:36:24.7288303Z 	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:927) ~[flink-dist-1.15.3.jar:1.15.3]
2024-12-21T04:36:24.7289617Z 	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:741) ~[flink-dist-1.15.3.jar:1.15.3]
2024-12-21T04:36:24.7290250Z 	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:563) ~[flink-dist-1.15.3.jar:1.15.3]
2024-12-21T04:36:24.7290697Z 	at java.lang.Thread.run(Unknown Source) ~[?:?]
```

### Zeta or Flink or Spark Version

flink e2e 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Carl-Zhou-CN** [comment]
[60_Run _ transform-v2-it-part-1 (8, ubuntu-latest).txt](https://github.com/user-attachments/files/18245934/60_Run._.transform-v2-it-part-1.8.ubuntu-latest.txt)
